### ISSUE TITLE
Support multiple assertion libraries/test runners for the TestAdapter class

### ISSUE THREAD

**Issue by microsoftly** [microsoft/botbuilder-js#100]
Users of the BotTester framework found it useful to be able to use different testing frameworks when running their tests. While its internal chai solution would throw an error when assertions failed, users still requested the ability to have support for multiple libraries. 

For reference, here's [the issue thread on the BotTester framework repo](https://github.com/microsoftly/BotTester/issues/7).

**Comment by Stevenic** [comment]
If you have some thoughts for how to achieve that I'd love to see a PR. Look at the TestAdapter in the [M2](https://github.com/Microsoft/botbuilder-js/blob/m2/libraries/botbuilder-core-extensions/src/testAdapter.ts) branch though.

**Comment by Stevenic** [comment]
Was just working on getting better code coverage on the TestAdapter and we'll need to do some re-factoring to support alternate frameworks. Should be just a matter of abstracting out the adapters internal calls to assert. Again open to feedback on how to approach this.

**Comment by microsoftly** [comment]
I would recommend something like the implementation in the BotTester framework;  define an interface for an expectation, e.g.
``` typescript
export interface IExpectation {
    notToBeEmpty(): void;
    toEqual(value: {}): void;
    toInclude(value: {}): void;
    toBeTrue(): void;
    toDeeplyInclude(value: {}): void;
}
```
Then for each assertion library, implement accordingly. Using examples from my repo:
1. [chai](https://github.com/microsoftly/BotTester/blob/master/src/assertionLibraries/ChaiExpectation.ts)
2. [ava](https://github.com/microsoftly/BotTester/blob/master/src/assertionLibraries/AvaExpectation.ts) (small note on this one, I used a hack to get it out quickly for user consumption, it actually uses the ```ChaiExpectation``` under the hood)

For some frameworks like ava, you will need to [expose a test context](https://github.com/microsoftly/BotTester/blob/master/src/assertionLibraries/AvaExpectation.ts#L16). These can be passed in when constructing the test adapter.

Lastly, the end user needs a way of defining which library to use (you can always default to assert or some other frequently used library like chai). This can be done by passing in test options to the test Object, all with standard defaults. To go even further, a config file that exposes test options can be useful as well (e.g. set timeout, default address, test framework, etc ...) can give the end user many options for how to configure their tests.

**Comment by microsoftly** [comment]
If you're okay with this approach, I can help with the dev

**Comment by Stevenic** [comment]
@microsoftly if you'd like to take a crack at re-working the `TestAdapter` class to support the above abstraction I'd say go for it.

**Comment by Stevenic** [comment]
Closing old issue
