### ISSUE TITLE
Typing indicator bug in MS Teams

### ISSUE THREAD

**Issue by rafaelbbtsaccount** [microsoft/botbuilder-js#1027]
## Versions
"botbuilder": "^4.4.0",
"botbuilder-ai": "^4.4.0",
"botbuilder-dialogs": "^4.4.0"

## Describe the bug
After adding the middleware **ShowTypingMiddleware**, the type indicator not going away in MS Teams Channnel. It works fine in others channels, but not in MS Teams.

## To Reproduce
Use on adapter: 
`.use(new ShowTypingMiddleware());`

then test in MS Teams.

## Expected behavior
The typping should show and leave before the bot responds.

[bug]

**Comment by iMicknl** [comment]
Related to https://github.com/microsoft/botbuilder-dotnet/issues/1877. 
This clearly isn’t a SDK issue, maybe both issues can be moved to [BotFrameworkServices](https://github.com/microsoft/BotFramework-Services)?

**Comment by dmvtech** [comment]
As @iMicknl pointed out, this is a Teams issue. It is currently fixed, but yet in a public ring. Keep an eye on https://github.com/microsoft/botbuilder-dotnet/issues/1877 for resolution/updates. Closing this.
