### ISSUE TITLE
QnA Maker default answer

### ISSUE THREAD

**Issue by diberry** [microsoft/botbuilder-js#1028]
Current the BF SDK doesn't return the QnA Maker default answer stored in the web app service for QnA Maker because it is wrapped to not expose it. The samples instead show a different hard-coded string that the customer must maintain. 

Would you accept PRs for the SDKs to expose this default answer already maintained by QnA Maker in their web app service as a property that the BF can access? 

This would reduce the hard-code strings from 2, in different places, that the customer has to maintain, to 1 in its original and proper location.

**Comment by stevengum** [comment]
@gabog, I think @vipeketi would have some valuable insight on how to implement this feature 😄

**Comment by vipeketi** [comment]
@somigithub  for your information.

**Comment by pchoudhari** [comment]
@diberry , the default message in the QnA Maker app settings is when there is zero match in the search results, however the default message in the SDK is when the returned scores are below the specified threshold.

I think there is a specific use case for both. What do you think?

**Comment by diberry** [comment]
@pchoudhari - I know this issue is on the JS repo but it is valid for all languages -- so -- in that regard, the C# preview SDK, allows a developer to [pass the threshold in](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cognitiveservices.knowledge.qnamaker.models.querydto.scorethreshold?view=azure-dotnet#Microsoft_Azure_CognitiveServices_Knowledge_QnAMaker_Models_QueryDTO_ScoreThreshold) with the query runtime request. Does the response to generateAnswer return enough information so that a customer would know no answer was returned based on which of the 2 cases so the client application could manage the flow? 

@nerajput1607 fyi

**Comment by pchoudhari** [comment]
Yes, GenerateAnswer will zero results when there is no match. In this case too, the bot developer would want their custom response to the user (like when results are below the threshold value)

**Comment by pchoudhari** [comment]
@diberry , I'm closing this issue. Let me know if you need further clarification.
