### ISSUE TITLE
Auth: Support required endorsements in Authentication Layer

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-js#1029]
Parity for this C# PR: https://github.com/microsoft/botbuilder-dotnet/pull/2019

**Comment by carlosscastro** [comment]
This can safely wait for R7, since some things being planned may affect how we expose endorsements.

**Comment by cleemullins** [comment]
@carlosscastro, how is this coming? It been sitting for a long time...

**Comment by carlosscastro** [comment]
Planning to have a PR out for this around 12/4. The change will be small but get somewhat deep in the auth layers.
