### ISSUE TITLE
OAuthPrompt should default to InputHints.AcceptingInput (Cherrypick to Master Needed)

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#1042]
## Describe the bug
OAuthPrompt in JS default to using `InputHints.ExpectingInput`. As this prompt usually receives another non-message activity with the successful OAuth flow, the bot should not use ExpectingInput.

For channels such as WebChat, an activity with the inputHint ExpectingInput would turn on the mic when it should not (again, because of the particulars of an OAuth flow).

```ts
const msg: Partial<Activity> = typeof prompt === 'object' ? 
  {...prompt} : MessageFactory.text(prompt, undefined, InputHints.ExpectingInput);
```

## Expected behavior
If you pass in a string instead of a full Activity, the OAuthPrompt should use `InputHints.AcceptingInput` instead of defaulting to `InputHints.ExpectingInput`.

## Additional context
~This bug does not exist in C# because the prompt takes the `Activity` in `PromptOptions` and does not set a default `InputHint`.~ _Edit again because I forgot to take this out apparently, but the bug was in C# as well._

It's unclear what the default inputHint should be for the prompts, **BUT** `TurnContext.sendActivity()` will set `inputHint` to `InputHints.AcceptingInput` **IF** the first param in the method is a string. ([source](https://github.com/microsoft/botbuilder-js/blob/c7ab4c2e6f6ceaec640537d9c113de3162f3a17c/libraries/botbuilder-core/src/turnContext.ts#L156-L163))

The channels that **respect** `InputHints` needs to be documented. 

[bug]

Python Tracking Issue:
https://github.com/microsoft/botbuilder-python/issues/247

C# Tracking Issue:
https://github.com/microsoft/botbuilder-dotnet/issues/2210

**Comment by cleemullins** [comment]
Fixed in the 4.5 Branch via PR #1043.

Needs to be Cherry-picked into master.

**Comment by v-kydela** [comment]
> This bug does not exist in C# because the prompt takes the Activity in PromptOptions and does not set a default InputHint.

Maybe I'm misunderstanding, but it looks like a default `InputHint` is set in three places: https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L109

```c#
                    if (opt.Prompt != null && string.IsNullOrEmpty(opt.Prompt.InputHint))
                    {
                        opt.Prompt.InputHint = InputHints.ExpectingInput;
                    }

                    if (opt.RetryPrompt != null && string.IsNullOrEmpty(opt.RetryPrompt.InputHint))
                    {
                        opt.RetryPrompt.InputHint = InputHints.ExpectingInput;
                    }
```

```c#
            // Set input hint
            if (string.IsNullOrEmpty(prompt.InputHint))
            {
                prompt.InputHint = InputHints.ExpectingInput;
            }
```

**Comment by johnataylor** [comment]
@v-kydela you  are correct and we also fixed it in the C#
