### ISSUE TITLE
Typing indicator not going away in MS Teams channel

### ISSUE THREAD

**Issue by rafaelbbtsaccount** [microsoft/botbuilder-js#1049]
## Versions
botbuilder 4.5.0

## Describe the bug

I was using a typing indicator in my chatbot wich worked fine. However, since a few days the typing indicator in MS Teams just keeps showing for 5~10 seconds, even when a message has been sent; normally this wasn't the case. The typing indicator still works in webchat or any other channel.

## To Reproduce

```
const adapter = new teams.TeamsAdapter({
    appId: 'xxxxxxxx',
    appPassword: 'xxxxxxx',
    channelService: process.env.ChannelService,
    openIdMetadata: process.env.BotOpenIdMetadata
}).use(new ShowTypingMiddleware());
```

## Expected behavior
I want the indicator to go away when a message has been send by the bot.

[bug]

**Comment by dmvtech** [comment]
This is a known issue. It is an issue with the Teams client. This issue has a fix, but has not yet rolled out to public release rings. Please find more information here:
https://github.com/Microsoft/botbuilder-dotnet/issues/1877
