### ISSUE TITLE
Storage is still a Middlware Component

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-js#105]
Tracking bug for Alignment, so we don't forget. 

The C# SDK has changed this (per our discussion) from being a Middleware component to being something that's just directly passed in. 

C# Code
```
          return new BotFrameworkAdapter(applicationId, applicationPassword)
                    .Use(new UserState<UserData>(new MemoryStorage()))
                    .Use(new ConversationState<ConversationData>(new MemoryStorage()))
```

JS Code that needs to be updated (from M2 Branch):
```
const bot = new Bot(adapter)
    .use(new MemoryStorage())
    .use(new BotStateManager())
```

**Comment by Stevenic** [comment]
It's already no longer middleware:

https://github.com/Microsoft/botbuilder-js/blob/m2/libraries/botbuilder-core-extensions/src/memoryStorage.ts#L15

MemoryStorage just implements Storage and is NOT Middleware.
