### ISSUE TITLE
BUG: TriggerAction at Node.js gives wrong message

### ISSUE THREAD

**Issue by nao3301** [Microsoft/botbuilder-js#106]
When the bot catches up with an interruppted dialog it don't says the last message again. instead it says : I didn't understand. Please try again. but then continues the right dialog

**Comment by Stevenic** [comment]
I'm assuming this is a bot using the v3 version of the SDK. If so could you please re-open your issue over [here](https://github.com/Microsoft/botbuilder/issues) as this repo is for an unreleased version 4 of the SDK and isn't currently monitored by our support engineers.

**Comment by Stevenic** [comment]
closing
