### ISSUE TITLE
Issue with number recognizer in dialogs prompts sample

### ISSUE THREAD

**Issue by jithware** [Microsoft/botbuilder-js#107]
Steps to reproduce:

cd botbuilder-js/samples/dialogs/prompts-ts
node ./lib/app.js

Result:

botbuilder-js/samples/dialogs/prompts-ts/node_modules/botbuilder-choices/lib/recognizeChoices.js:12
const numberModel = Recognizers.NumberRecognizer.instance.getNumberModel("en-us");
                                                         ^
TypeError: Cannot read property 'getNumberModel' of undefined

**Comment by Stevenic** [comment]
Can you run the command below and tell me the version number you have installed?

```
npm list @microsoft/recognizers-text-suite
```

Looks like they just updated this package yesterday and I'm wondering if you somehow got that version.

**Comment by Stevenic** [comment]
My other question would be are you using windows or a mac?

**Comment by Stevenic** [comment]
Could you try this again? I just published a new release that should fix the issue.

**Comment by Stevenic** [comment]
Closing... Please let me know if you still hit this issue

**Comment by jithware** [comment]
Thanks Steve for the quick fix.  Looks like the above issue is resolved however it appears to be in  datetimePrompt.js as well:

... botbuilder-js/samples/dialogs/prompts-ts/node_modules/botbuilder-dialogs/lib/prompts/datetimePrompt.js:6
const dateTimeModel = Recognizers.DateTimeRecognizer.instance.getDateTimeModel('en-us');
                                                             ^
TypeError: Cannot read property 'getDateTimeModel' of undefined

Steps to reproduce:

cd botbuilder-js/samples/dialogs/prompts-ts
npm install
node ./lib/app.js

Additional info:

npm list @microsoft/recognizers-text-suite
dialogs-prompts-ts@1.0.0 botbuilder-js/samples/dialogs/prompts-ts
└─┬ botbuilder-dialogs@4.0.0-m1.10
  ├── @microsoft/recognizers-text-suite@1.0.0 
  └─┬ botbuilder-choices@4.0.0-m1.10
    └── @microsoft/recognizers-text-suite@1.0.0 

uname -a
Darwin  16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64
