### ISSUE TITLE
[Botbuilder-AI] Remove @azure-ms-rest dependency

### ISSUE THREAD

**Issue by Bill7zz** [microsoft/botbuilder-js#1071]
## Issue description
**Botbuilder-ai** has a pinned version of `@azure/ms-rest` [v1.8.13](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-ai/package.json#L24). This version is being used to create a credential that’s used by the LUIS client. 
Right now, the versions are compatibles, but some time ago we had an issue because the LUIS client upgraded its version of `@azure/ms-rest`, which caused some differences between the interfaces.
To avoid this happening again, we want to eliminate the `@azure/ms-rest` dependency. However, we can’t do this because of the coupling between LUIS client and `@azure/ms-rest`. 

Currently, the [LuisRecognizer](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-ai/src/luisRecognizer.ts) class depends on `@azure-ms-rest` to create a [LUISRuntimeClient](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/cognitiveservices/cognitiveservices-luis-runtime/src/lUISRuntimeClient.ts) object.

```
const creds: msRest.TokenCredentials = new msRest.TokenCredentials(this.application.endpointKey);
const baseUri: string = this.application.endpoint || 'https://westus.api.cognitive.microsoft.com';
this.luisClient = new LuisClient(creds as any, baseUri);
```
This implementation caused build issues. The solution was to cast the credentials as `any` to avoid the build to break.

## Possible solution
- Create a LUIS client manually that does not depend on `@azure/ms-rest`.

**Comment by cleemullins** [comment]
I don't think this work will happen.
