### ISSUE TITLE
[BF-Connector] Remove @azure/ms-rest-js dependency

### ISSUE THREAD

**Issue by Bill7zz** [microsoft/botbuilder-js#1072]
## Issue description

Initially, the **BotFramework-Connector** library was generated by Autorest using `@azure/ms-rest`. With time the autogenerated files were modified to add new functionalities.
 
The last time we attempted to generate **BotFramework-Connector** with a newer version of Autorest and  `@azure/ms-rest`, there was a sizable delta between the generated code and the old code. So we decided to set the `@azure/ms-rest` version to [1.2.6](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botframework-connector/package.json#L22).

Now, we reached a point in which we cannot add more functionalities without updating the `@azure/ms-rest` version. This is the case of the proxy support, only available on `1.8.x` versions of `@azure/ms-rest` (#717)

As depending on autogenerated code reduces the possibility to add more functionalities and also makes a dependency couple implementation, it's necessary to stop depending on the autogenerated code and remove the `@azure/ms-rest` dependency.

## Possible solution

Because the current implementation of the **BotFramework-Connector** is tightly coupled to `@azure/ms-rest`, remove this dependency means to redefine most of the library. 

We suggest:

- Regenerate the **BotFramework-Connector** base client using [OpenApi](https://github.com/OpenAPITools/openapi-generator) which doesn’t use `@azure/ms-rest` to have the base structure of the library. **This code will be generated once, and every change/update will be made manually.**

- Make an assessment of the functionalities added in the current implementation of the library. Then porting that into the newest, adding the proxy support at the time.

**Comment by cleemullins** [comment]
I don't believe this work will be done.
