### ISSUE TITLE
RegExp in `removeMentionText` is not supported in IE11

### ISSUE THREAD

**Issue by compulim** [microsoft/botbuilder-js#1075]
## Versions
What package version of the SDK are you using: `4.5.0`
What nodejs version are you using: N/A
What browser version are you using: IE11
What os are you using: Windows

## Describe the bug

[The regular expression pattern on this line of `turnContext.ts`](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/turnContext.ts#L117) is not supported in IE11.

## To Reproduce

1. Open IE11 F12
2. In the "Console" tab, type `/(?<=<at.*>)(.*?)(?=<\/at>)/i`

## Expected behavior

IE11 should returns the `RegExp` object.

In fact, it say `Unexpected quantifier`.

## Screenshots

![image](https://user-images.githubusercontent.com/1622400/61403801-ef954080-a88a-11e9-8513-81826440586a.png)

## Additional context

Found this while fixing `javascript_es6/01.browser-echo` sample.

[bug]

**Comment by tracyboehrer** [comment]
This should be resolved because of the change in:
https://github.com/microsoft/botbuilder-js/pull/1088
