### ISSUE TITLE
Use `import from` instead of `require` in `testAdapter.ts`

### ISSUE THREAD

**Issue by compulim** [microsoft/botbuilder-js#1076]
## Versions
What package version of the SDK are you using: `4.5.0`
What nodejs version are you using: N/A
What browser version are you using: IE11
What os are you using: Windows

## Describe the bug

In [`testAdapter.ts` line 9](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/testAdapter.ts#L9), it should use `import assert from 'assert';` instead of `import assert = require('assert');`.

## To Reproduce

1. Clone `botbuilder-samples`
1. Go to `samples/javascript_es6/01.browser-echo`
1. Run `npm ci`
1. Run `npm run build`

## Expected behavior

It build successfully.

Instead, Webpack is reporting:

```
SyntaxError: C:\Users\JohnDoe\Source\Repos\BotBuilder-Samples\samples\javascript_es6\01.browser-echo\node_modules\botbuilder-core\src\testAdapter.ts: `import =` is not supported by @babel/plugin-transform-typescript
Please consider using `import <moduleName> from '<moduleName>';` alongside Typescript's --allowSyntheticDefaultImports option.
```

## Additional context

Found this while fixing `samples/javascript_es6/01.browser-echo` sample.

Also, please consider not exposing/publishing `TestAdapter` if it is not used in production code.

[bug]

**Comment by stevengum** [comment]
@cleemullins, per discussions with @compulim, I will change the output of the libraries in the repo to ES5 output and run all the unittests. 

If those tests pass then I'll test a browser bot with the new transpiled libraries.

@compulim correct me if I'm wrong, but moving to the least common denominator (`"es5"`) for output from our libs shouldn't break any users who are creating browser bots right now. Is this a fair assumption?

**Comment by cleemullins** [comment]
@jspruance There is a PR already out for this, but needs to be tested changing the output of the TS compiler to ES5 instead of ES.Next. Also the transpiled code needs to be tested in a browser bot.

**Comment by jspruance** [comment]
I've tested with the output of the TS compiler set to ES5 and it works without errors (unit tests & bot in browser (Chrome)) as long as the compiler is run with the es2015 & dom type definitions, ex:

[tsconfig.json]
"target": "ES5",
"lib": [ "es2015", "dom" ],

However, since TypeScript does not polyfill and only transforms syntax, there's no guarantee that es6 objects (ie Promise, map, etc.) will work in all cases - we would need to ensure support is available in the browser where the bot is running. If we want to guarantee true es5 compatability, one option could be to add a Babel transpilation step, after TS.

The browser bot doesn't seem to work in IE11 (with 'esNext' or 'es5' output).

**Comment by jspruance** [comment]
I merged Steven Gum's changes relating to this ticket ('import assert') into my PR relating to outputing ES5 from TypeScript compilation. Pending code review:

https://github.com/microsoft/botbuilder-js/pull/1232

**Comment by jspruance** [comment]
TS compiler output updated to 'es6' per discussions / PR review.

**Comment by sgellock** [comment]
@jspruance @cleemullins @stevengum is the work for this issue complete?  I can't tell by reading through the issue history if we have remaining work or not.

**Comment by jspruance** [comment]
@sgellock  Work for this is complete - we're just waiting for code review approval on the PR:
https://github.com/microsoft/botbuilder-js/pull/1232

**Comment by jspruance** [comment]
These changes have been merged to master.
