### ISSUE TITLE
Issue with date time recognizer in datetimePrompt.js

### ISSUE THREAD

**Issue by jithware** [Microsoft/botbuilder-js#108]
Thanks Steve for the quick fix in #107 . Looks like the initial issue is resolved however it appears to be in datetimePrompt.js as well:

... botbuilder-js/samples/dialogs/prompts-ts/node_modules/botbuilder-dialogs/lib/prompts/datetimePrompt.js:6
const dateTimeModel = Recognizers.DateTimeRecognizer.instance.getDateTimeModel('en-us');
^
TypeError: Cannot read property 'getDateTimeModel' of undefined

Steps to reproduce:

cd botbuilder-js/samples/dialogs/prompts-ts
npm install
node ./lib/app.js

Additional info:

npm list @microsoft/recognizers-text-suite
dialogs-prompts-ts@1.0.0 botbuilder-js/samples/dialogs/prompts-ts
└─┬ botbuilder-dialogs@4.0.0-m1.10
├── @microsoft/recognizers-text-suite@1.0.0
└─┬ botbuilder-choices@4.0.0-m1.10
└── @microsoft/recognizers-text-suite@1.0.0

uname -a
Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64

**Comment by Stevenic** [comment]
Try it now. Should be fixed. Not sure how that slipped by. Thanks :)

**Comment by jithware** [comment]
All set. Thank you!
