### ISSUE TITLE
Invalid module path in botbuilder-ai

### ISSUE THREAD

**Issue by fukuhiro** [microsoft/botbuilder-js#1089]
## Versions
botbuilder-ai 4.5.0  
Linux

## Describe the bug
> \> tsc
> node_modules/botbuilder-ai/lib/qnamaker-interfaces/index.d.ts:12:15 - error TS2307: Cannot find module './qnamakerTraceinfo'.
> 12 export * from './qnamakerTraceinfo';

## To Reproduce
1. Write code using botbuilder-ai.  
    e.g. `import * as appInsights from 'botbuilder-applicationinsights';`
2. execute `tsc`
3. See error

[bug]

**Comment by SamuelTassell** [comment]
I'm getting the same issue while trying to build on Linux with our pipeline. It's just a naming issue I think...

`export * from './qnamakerTraceinfo';` should be: `export * from './qnamakerTraceInfo';`. Builds fine on mac but it's not case sensitive. Bit of an issue for us to be honest.

**Comment by cleemullins** [comment]
A quick update:

1. PR #1090 has been merged to master. Thanks @fukuhiro! 
2. The PR has been cherry-picked over to the 4.5 branch. See the [merge here](https://github.com/microsoft/botbuilder-js/commit/1981590a62a54deab80b2d4391ca4a7fdd4fccc3).
3. The resulting file (in 4.5) [is seen here](https://github.com/microsoft/botbuilder-js/blob/4.5/libraries/botbuilder-ai/src/qnamaker-interfaces/index.ts) - with the correct casing. 
4. The [4.5.3 Build has run](https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=72567).
5. The 4.5.3 Packages are on the daily build server now. For example, [BotBuilder 4.5.3 is here](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder/4.5.3).

@dmvtech is testing these packages tonight, with a before/after check.

Plan is to release to NPM in the morning, provided testing goes as expected.

**Comment by dmvtech** [comment]
Confirmed working on Ubuntu 19.04.

**Comment by cleemullins** [comment]
The 4.5.3 SDK has been pushed to NPM. 

Thanks everyone for reporting this, providing a good repo case, and even submitting the PR to fix the issue.
