### ISSUE TITLE
FileStorage should use truly unique identifier for eTag instead of simple increment 

### ISSUE THREAD

**Issue by DeniseMak** [Microsoft/botbuilder-js#110]
In the C# SDK it was causing problems for the FileStorage implementation to copy the MemoryStorage implementation. Using a GUID instead of an increment would fix that. For parity and robustness can the Node.js SDK do that too?

See https://github.com/Microsoft/botbuilder-dotnet/pull/266 for parallel fix to C# SDK.

**Comment by Stevenic** [comment]
I changed the code in the `m2` branch to do just that but as I said in #111 there are bigger issues with `FileStorage`.

**Comment by Stevenic** [comment]
Making this a P3 as there's discussion around removing `eTag` all together.

**Comment by Stevenic** [comment]
I think this core issue is addressed
