### ISSUE TITLE
transcriptLogger should update activity.Id on the cloned activity

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-js#1101]
## Describe the bug

https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/transcriptLogger.ts#L52

```js
context.onSendActivities(async (ctx: TurnContext, activities: Partial<Activity>[], next2: () => Promise<ResourceResponse[]>) => {
// run full pipeline
const responses: ResourceResponse[] = await next2();
activities.forEach((a: ResourceResponse) => this.logActivity(transcript, this.cloneActivity(a)));

return responses;
});
```
The cloned activity in the code above should include the ResourceResponse.id retrieved from sending the activity to the server.  Currently, all outgoing activities logged will NOT have an activity.id

## Expected behavior
Activities logged should contain the actual id of the activity (which is determined by the server, when sending the message). 

[bug]

**Comment by sgellock** [comment]
Please file a PR

**Comment by EricDahlvang** [comment]
PR filed: https://github.com/microsoft/botbuilder-js/pull/1114
