### ISSUE TITLE
if writing an item with eTag='*', the eTag written to storage gets set to NaN

### ISSUE THREAD

**Issue by DeniseMak** [Microsoft/botbuilder-js#111]
This was seen in the m2 branch.
If the item you're writing to fileStorage has an eTag of '*', the following line of code in fileStorage.ts sets the newObj.eTag to NaN.
```
newObj.eTag = (parseInt(newObj.eTag || '0') + 1).toString();
```

**Comment by Stevenic** [comment]
This particular bug has been fixed in the `m2` branch but the current `FileStorage` provider has bigger issues and needs to be completely re-written.

**Comment by Stevenic** [comment]
should be fixed
