### ISSUE TITLE
[BotBuider-AI] Replace request with node-fetch 

### ISSUE THREAD

**Issue by Bill7zz** [microsoft/botbuilder-js#1116]
## Describe the issue
In the #1107 the LUIS API is being replaced with a custom client which uses `request`. In order to make it browser compatible it's necessary to use `node-fetch` instead of `request`.

## Posible solution
Update the custom LUIS client to use `node-fetch`

**Comment by munozemilio** [comment]
This will be partially done in recognizer V3,  V2 will be replaced in R8

**Comment by johnataylor** [comment]
moving this clean up to the quality milestone (note there are other places where we use http calls - for example axios in the BotFrameworkHttpClient) 😞

**Comment by joshgummersall** [comment]
We intend to resolve this as part of the next SDK major version. Closing this issue for now.
