### ISSUE TITLE
The application insights readme has some dead links

### ISSUE THREAD

**Issue by benbrown** [microsoft/botbuilder-js#1118]
# Describe the bug

This page links to samples that no longer exist:
https://github.com/microsoft/botbuilder-js/tree/master/libraries/botbuilder-applicationinsights

## To Reproduce

Click on the qnamaker or luis examples within the body or the footer of this document. It leads to 404s!

## Expected behavior

We should link to useful examples for applying App Insights to these recognizers.

[bug]

**Comment by Zerryth** [comment]
Links used to go to:

![image](https://user-images.githubusercontent.com/35248895/63462832-aa77a780-c410-11e9-8da5-097cd820f64f.png)
and
![image](https://user-images.githubusercontent.com/35248895/63462899-cd09c080-c410-11e9-9696-1c3950596912.png)

So looks like fixing of this readmes bug depends on completion of this [samples issue tracking building JS AppInsights samples](https://github.com/microsoft/BotBuilder-Samples/issues/1707)
