### ISSUE TITLE
DCR: We should change to javascript libraries to use Async/await instead of raw Promise.then() pattern

### ISSUE THREAD

**Issue by tomlm** [Microsoft/botbuilder-js#112]
**Reasons for**
1. Raw Promise() introduces .then() complexity to code base making dealing with simple things like sending multiple responses difficult.
2. node 7.6 supports async/await native 
3. all major browsers support promises and async await native with exception of IE 11
4. typescript has robust async/await polyfill for downlevel javascript environments, as well as other polyfill libraries
5. it makes code much more compliant with C# 
6. python is adding async/await

**Reasons against**
1. polyfill for downlevel environments injects complex code 
2. IE doesn't support it

What do people think?

**Comment by LarsLiden** [comment]
+1

**Comment by Stevenic** [comment]
Our JS library is designed to support Node 6.x and above for the broadest possible reach. If you look at the numbers in [this report](https://nodesource.com/node-by-numbers) you'll see that 6.x is still in wide spread use.  I looked at [react](https://github.com/facebook/react) to see what they do and while they use `async/await` some in their unit tests they avoid it in their actual libraries. So internally I'd prefer to do the same thing especially given that everything is already coded to use promises and has full unit tests.

With that said, I did go through and update the typescript samples in the `m2` branch to use `async/await` as I agree that if you're using TypeScript you're more apt to be ok with that pattern. I left the JavaScript samples using promises as we want them to work on Node 6.x and I think it's useful to have samples that show both approaches.  Just like we don't want to force developers to use TypeScript by only providing TS samples, we also shouldn't push developers to adopt new language features they may not be comfortable using yet.

**Comment by Stevenic** [comment]
A medium post arguing against the use of `async/await` in JavaScript:

https://medium.com/@benlesh/async-await-it-s-good-and-bad-15cf121ade40

Just to illustrate that not everyone is a fan and it's not the role of our SDK to chose any one side of something new that's still being debated by the community.

**Comment by justinwilaby** [comment]
I thought I might chime in a bit with some insight coming from a UI-Centric developer.

Steve's concerns have merit and paint a pretty clear picture of why he chose to use Promises over async/await. Promises are common, widely accepted within the community and are generally a safe strategy, albeit a slightly more legacy approach. Consideration must be given to simplicity, readability and compatibility which Steve has done by choosing to use promises. I think async/await can **also** accomplish these goals without some of the technical debt that may be accruing when using only Promises. 

To that end, here is my list of pros/cons for using async/await:

**Pros** 
1. We're no longer writing legacy code - Promises are generally thought of as a legacy implementation for *sequential* async operations and using them for this purpose in new code almost guarantees that we'll have to rewrite vast areas of code sooner. 
2. The JavaScript community, particularly on the UI side is trending towards the use of async/await - This means nearly all JS developers worth their salt will know how to be effective with them already. I would say that they've been around long enough not to be labeled as a new JS feature.
3. [Babel 7 has a helper](https://github.com/babel/babel/blob/4da3f3bc64841e0b4b7906c6c26af73920264095/packages/babel-helpers/src/helpers.js#L196)  (not a polyfill - async/await cannot be polyfilled) that's super easy to read in case someone is concerned about it. 
4. Source maps are solid for maintaining breakpoints and the developer tools on most all browsers maintain call stacks quite well even when helpers are involved.
5. The potential for better readability of code increases by an order of magnitude. e.g. `this` is never ambiguous, temporal dead zones are less likely, error handling is superior, and variable shadowing is more easily recognized.

**Cons**
1. Promises would still be required for *concurrent* processing. Async/await does not have a `Promise.all()` equivalent.
2. Transpilation will be mandatory for older platforms. 
3. Any project prior to TS 1.7 would break with no mitigation options other than an update to >1.7

**Comment by tomlm** [comment]
1. Promise.All() returns a Promise, so 
```javascrit
await Promise.All(...)
``` 
2. When posting critiques of async/await, pick one which is newer then 2 years ago.
https://hackernoon.com/6-reasons-why-javascripts-async-await-blows-promises-away-tutorial-c7ec10518dd9 is only 6 months old for example, things have come a long way

**Comment by Stevenic** [comment]
We're shifting all of the samples and docs towards async/await and while I'm more open to library code using this as well I see no need to force that.  Our code works and in JS at least sometimes its just easier to work with promises. async/await don't get you out of having to know promises.

Closing this for now.
