### ISSUE TITLE
BotFrameworkAdapter.createConversation fails to handle group conversation requests

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-js#1124]
## Versions
What package version of the SDK are you using: 4.6 (master)
What nodejs version are you using: v10.16.0
What browser version are you using: n/a
What os are you using: Windows 10.

## Describe the bug
According to the Bot Connector protocol, _create conversation_ allows the bot to request that a channel create a group conversation. However, the `BotFrameworkAdapter.createConversation` implementation seems to limit requests to direct, one-on-one conversations.
- Also, this diverges with the .NET implementation, which does allow the bot to request a group conversation.

## To Reproduce
1. Read the code inside BotFrameworkAdapter.createConversation:
    https://github.com/microsoft/botbuilder-js/blob/8bd254a4dbb3e94937a7b8d748f7365c70f44574/libraries/botbuilder/src/botFrameworkAdapter.ts#L265-L287
1. Error: note that on line 276 this is always assumed to be a direct conversation, whether or not the initial value of the `reference` property indicates this should be a group conversation.

## Expected behavior
- The protocol supports the creation of group conversations, the method signature does not prohibit the creation of group conversations, the implementation should allow the creation of group conversations.
- The implementation should match/support the functionality of the underlying protocol here.
- I think the behavior of this method could be corrected without introducing a breaking change.

## Additional context

Here's commentary from Dan, taken from an email thread:

1. If the channel “agrees” to create the conversation, the ResourceResponse returned contains an id containing the ID of the conversation the channel created.
   > [Dan] Correct, and the concepts you’re describing are correct
1. Q: If the conversation is created, is the channel expected to send conversationUpdate activities?
   > [Dan] Typically, but not necessarily in all cases, depending on what is most appropriate for the channel and what is possible.
   >
   > For example, creating a conversation in SMS yields a successful conversation ID (think of it as an idempotent create request) and it does not create a conversationUpdate because SMS conversations do not really have a beginning nor an end.
   >
   > Channels that can send conversation on create typically do.
1. The bot can try to create a group conversation, but this isn’t supported by most channels.
   > [Dan] Correct 
1. Q: If the CreateConversation request payload includes an activity, who is the intended recipient of that activity, that is, should the channel send that to the bot when the conversation is created, or to the non-bot members of the conversation? 
   > [Dan] Activities sent to channels do not have an intended recipient. The bot includes the Activity in the request and the channel handles the work of enumerating the recipients and changing the Activity for them. Typically bot participants do not receive any Activities they originated. Bots may or may not receive Activities originated by other bots depending on the channel.
   - Presumably, the channel will update the activity’s conversation property (and any other conversation-specific fields) before sending the activity.
     > [Dan] Yes – the correct way to think about this is that the Activity that a bot sends to a channel is merely a request to send content. The channel receives it and, if it accepts the request, stores or records the content as part of the conversation. Then, as a subsequent operation, the channel creates new Activities that reflect that the message/content was accepted into the conversation. These Activities are the ones that are sent to users/other bots/etc.
     >
     > In many cases these two Activities (the one the bot sent and the one the client receives) appear or act as if they are the same Activity, possibly with some fields changed. However the channel is not bound to that concept, and a more correct interpretation is that these two Activities are different, but closely related.! 

[bug]

**Comment by JonathanFingold** [comment]
Any thoughts on this? This should get fixed sooner rather than later.

**Comment by Virtual-Josh** [comment]
Hey @Kaiqb,

I just ran across this issue. I don't know who it should belong to, but can you route it to the right person?

**Comment by Kaiqb** [comment]
@JonathanFingold - is this still an issue in 4.8?

**Comment by JonathanFingold** [comment]
@Kaiqb - yes, here's what's in master now. the inner isGroup parameter is still hard-coded to `false`.

I'm not sure why this hasn't created problems with the Teams channel.

```csharp
        const response = await client.conversations.createConversation(parameters);


        // Initialize request and copy over new conversation ID and updated serviceUrl.
        const request: Partial<Activity> = TurnContext.applyConversationReference(
            { type: 'event', name: 'createConversation' },
            reference,
            true
        );


        const conversation: ConversationAccount = {
            id: response.id,
            isGroup: false,
            conversationType: null,
            tenantId: reference.conversation.tenantId,
            name: null,
        };
        request.conversation = conversation;
        request.channelData = parameters.channelData;


        if (response.serviceUrl) { request.serviceUrl = response.serviceUrl; }


        // Create context and run middleware
        const context: TurnContext = this.createContext(request);
        await this.runMiddleware(context, logic as any);
```

**Comment by JonathanFingold** [comment]
Here's an updated code link, as the file was edited (but the bug still remains)

https://github.com/microsoft/botbuilder-js/blob/c39c7744eaf1bc82e897789202420659a03c460f/libraries/botbuilder/src/botFrameworkAdapter.ts#L369-L392

**Comment by joshgummersall** [comment]
We added support for passing `Partial<ConversationParameters>` in the `createConversation` parameter list. See [the code on `main` here](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/botFrameworkAdapter.ts#L466). This should resolve the issue, feel free to reopen this issue if that is not the case.

**Comment by JonathanFingold** [comment]
Perhaps I'm not reading this correctly, and please correct me if I'm wrong, but at line 511 `isGroup` is hard coded to `false` on the conversation account, then that account is added to request and sent out without further modification. Won't this always result in a non-group conversation?

https://github.com/microsoft/botbuilder-js/blob/3b772bbb59ce3b5bd328b890696a17a92b8194e6/libraries/botbuilder/src/botFrameworkAdapter.ts#L509-L525

**Comment by joshgummersall** [comment]
Good point, I'll have a PR shortly.

**Comment by joshgummersall** [comment]
@JonathanFingold okay, it should be resolved now on `main`. That code will be published in a daily build tomorrow.
