### ISSUE TITLE
Streaming extension: Please provide package-lock.json or lockdown on all versions

### ISSUE THREAD

**Issue by compulim** [microsoft/botbuilder-js#1127]
## Versions

Node 12

## Describe the bug

If `package-lock.json` is not provided, running `npm install` on the client box will be undeterministic. That means, in the future, anyone running `npm install` will be installing packages that are significantly more updated than today. 

In that case, the build will break and we will not be able to reproduce the build because we don't exactly know what version we were using when building.

Please either, include `package-lock.json` (recommended), or make sure all the versions are locked down at least.

Locking down the version is *not recommended* because transient packages are still not locked down. That means, we are still susceptible to the problem mentioned above for transient packages (indirect dependencies). So I would *highly recommend* to use `package-lock.json` to shrinkwrap it down.

## Repro steps

1. Fresh clone, make sure no `node_modules` folder
   - Easiest is run `git clean -fdx` if you have a dirty repo
1. Run `npm ci`

It should work as expected.

`npm ci` is `npm install` but for CI pipeline to verify build quality. If it can run successfully, it guarantees a reproducible build in any of time in the future (given no packages are unpublished).

[bug]

**Comment by cleemullins** [comment]
We explicilty deleted all the package-lock files. The lockdown approach is worth discussion.

**Comment by carlosscastro** [comment]
Discussed offline, we are doing the right thing already. Closing :)
