### ISSUE TITLE
Streaming extension: Some files using double quotes, while most use single quotes

### ISSUE THREAD

**Issue by compulim** [microsoft/botbuilder-js#1129]
## Versions

`master`

Node 12.

## Describe the bug

For consistencies, please update all TypeScript file to use a single way of quotes.

For example, `Interfaces/IAssemblerParams.ts` is using double quotes, while `Interfaces/IHeader.ts` is using single quotes.

## Additional context

Please consider adding Prettier or ESLint to the project. You can copy the rules from Web Chat.

[bug]

**Comment by DDEfromOR** [comment]
+1 to fixing this, but we need to be careful where the rules are copied from, there seem to be inconsistencies between lint rules across our repos. This library lives in BotBuilder and should use the same rules it does.
