### ISSUE TITLE
Streaming extensions: Unassigned variable is by default falsy, no need to assign false

### ISSUE THREAD

**Issue by compulim** [microsoft/botbuilder-js#1136]
## Versions

`master` and Node 12.

## Describe the bug

https://github.com/microsoft/botbuilder-js/blob/master/libraries/botframework-streaming-extensions/src/NamedPipe/NamedPipeServer.ts#L66

Line 66, `let incomingConnect = false;`, the assignment of `false` value to `incomingConnect` is useless. Just leave it and it will be `undefined` and thus, falsy.

Same to `this._isDisconnecting`. Since this is a private member, it okay to use truthy/falsy, instead of `true`/`false`.

[bug]

**Comment by tdurnford** [comment]
Other occurrences of incorrectly setting variables to false:

https://github.com/microsoft/botbuilder-js/blob/8bd254a4dbb3e94937a7b8d748f7365c70f44574/libraries/botframework-streaming-extensions/src/NamedPipe/NamedPipeClient.ts#L48
https://github.com/microsoft/botbuilder-js/blob/8bd254a4dbb3e94937a7b8d748f7365c70f44574/libraries/botframework-streaming-extensions/src/NamedPipe/NamedPipeServer.ts#L52
https://github.com/microsoft/botbuilder-js/blob/8bd254a4dbb3e94937a7b8d748f7365c70f44574/libraries/botframework-streaming-extensions/src/NamedPipe/NamedPipeServer.ts#L66
https://github.com/microsoft/botbuilder-js/blob/8bd254a4dbb3e94937a7b8d748f7365c70f44574/libraries/botframework-streaming-extensions/src/NamedPipe/NamedPipeServer.ts#L67
https://github.com/microsoft/botbuilder-js/blob/60bb8386379ba57c155638c6d7776b0bccb1122d/libraries/botframework-streaming-extensions/src/PayloadTransport/PayloadReceiver.ts#L55
https://github.com/microsoft/botbuilder-js/blob/60bb8386379ba57c155638c6d7776b0bccb1122d/libraries/botframework-streaming-extensions/src/PayloadTransport/PayloadReceiver.ts#L80
https://github.com/microsoft/botbuilder-js/blob/60bb8386379ba57c155638c6d7776b0bccb1122d/libraries/botframework-streaming-extensions/src/Payloads/StreamManager.ts#L21
https://github.com/microsoft/botbuilder-js/blob/60bb8386379ba57c155638c6d7776b0bccb1122d/libraries/botframework-streaming-extensions/src/Payloads/StreamManager.ts#L40
https://github.com/microsoft/botbuilder-js/blob/60bb8386379ba57c155638c6d7776b0bccb1122d/libraries/botframework-streaming-extensions/src/Payloads/StreamManager.ts#L48
https://github.com/microsoft/botbuilder-js/blob/60bb8386379ba57c155638c6d7776b0bccb1122d/libraries/botframework-streaming-extensions/src/Payloads/StreamManager.ts#L54
https://github.com/microsoft/botbuilder-js/blob/60bb8386379ba57c155638c6d7776b0bccb1122d/libraries/botframework-streaming-extensions/src/WebSocket/NodeWebSocket.ts#L23
