### ISSUE TITLE
findTopIntent doesn't resolve correctly

### ISSUE THREAD

**Issue by GeekTrainer** [Microsoft/botbuilder-js#114]
The code for findTopIntent doesn't map the intents properly, and doesn't return a topIntent. The following JavaScript resolves the issue:

``` javascript
    static findTopIntent(recognizerResults) {
        return new Promise((resolve, reject) => {
            let top = undefined;

            const intents = recognizerResults[0].intents;
            Object.keys(intents).forEach(name => {
                if(!top || intents[name] > top.score) {
                    top = {
                        name: name,
                        score: intents[name]
                    };
                }
            });
            resolve(top);
        });
    }
```

https://github.com/Microsoft/botbuilder-js/blob/e562aa6f395f76c50fee396b7edee1c549f05186/libraries/botbuilder/src/recognizer.ts#L175

**Comment by Stevenic** [comment]
I've asked @emadelwany to take a look at this. I have another patch going out tomorrow for auth tokens never being updated after they expire which I'd like to piggyback this fix on.

**Comment by Stevenic** [comment]
Thanks @emadelwany

**Comment by Stevenic** [comment]
This should be fixed.
