### ISSUE TITLE
Streaming extensions: Near-synchronous messaging not working

### ISSUE THREAD

**Issue by compulim** [microsoft/botbuilder-js#1142]
## Versions

`master` and Node 12.

## Describe the bug

When using proactive messaging, a pause is required, otherwise, `context.sendActivity` will be a no-op.

## To Reproduce

Use the following code in your bot. And try to comment/uncomment `await sleep(1000);` line and see their difference.

```js
function handleMessage(context) {
  // The code below is wrapped as "async" without "await" because we want to "spin it off to mimic as if on another thread".

  (async function (adapter, reference) {
    await adapter.continueConversation(reference, async continuedContext => {
      // Without the sleep below, the continuedContext.sendActivity will fail silently (no-op)
      // No exceptions were thrown
      await sleep(1000);

      await continuedContext.sendActivity({
        inputHint: 'acceptingInput',
        text: 'This activity is accepting input.',
        type: 'message'
      });
    });
  })(context.adapter, TurnContext.getConversationReference(context.activity));
}

function sleep(ms = 0) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
```

## Expected behavior

Proactive messaging should work even synchronously or near-synchronously.

## Additional context

I checked a few things:
- `context.adapter` should be good
- The result of `TurnContext.getConversationReference` should be good
- `adapter.continueConversation` did not throw any exceptions
- `continuedContext.sendActivity` did not throw any exceptions
- If the sleep is set to `0`, it sometimes don't send, and sometimes send
   - It is more reliable to set it to `1000` to workaround the problem
- It feels like the named pipe or some wiring down under, is having troubles when resuming too fast
   - When it fail, it will take > 5s before the bot can respond to any further requests
   - `sleep(0)` essentially released the "synchronous stress" on the JavaScript side by allowing JavaScript message loop to run, but we are still seeing the problem
   - Looks like something outside of JavaScript

[bug]

**Comment by ckkashyap** [comment]
The issue was due to the sendbuffer getting overwritten. It has been fixed in this PR - https://github.com/microsoft/botbuilder-js/commit/d6b1ae39b9a305b678e81d97630c7c5af67f5964#diff-fb4743955fefe54bb110544005a770ee
