### ISSUE TITLE
Element implicitly has an 'any' type because expression of type '"attemptCount"' can't be used to index type '{}'.   Property 'attemptCount' does not exist on type '{}'.

### ISSUE THREAD

**Issue by tolotrasamuel** [microsoft/botbuilder-js#1155]
## Versions
What package version of the SDK are you using.
~4.5.1
What nodejs version are you using
10
What os are you using
Windows 10
## Describe the bug

node_modules/botbuilder-dialogs/src/prompts/prompt.ts(211,17): error TS7053: Element implicitly has an 'any' type because expression of type '"attemptCount"' can't be used to index type '{}'.
  Property 'attemptCount' does not exist on type '{}'.

## To Reproduce
1.Set noImplicitAny to true and run tsc

## Expected behavior
Give a clear and concise description of what you expected to happen.
Should compile

## Additional context

[bug]

**Comment by cleemullins** [comment]
Thanks for the 2 PR's that would fix this. I've asked @stevengum to review them both.

**Comment by CezaryMarcjan** [comment]
@Stevenic Look at these PRs if they're not breaking w can take them

**Comment by tolotrasamuel** [comment]
Any news, please?

**Comment by carlosscastro** [comment]
Hi @tolotrasamuel ! thanks for your PR. We are evaluating whether this is the route we want to go and what the implications are, given that it is quite at the core of the dialog system. We'll get back with a resolution shortly. Thanks!
