### ISSUE TITLE
documentdb v1.x client sdk deprecation (V3 JS SDK)

### ISSUE THREAD

**Issue by prashanthmadi** [microsoft/botbuilder-js#1162]
botbuilder-azure uses 1.x version of documentdb that is going to be deprecated in next 12 months.
https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-node

Please plan for upgrade.

https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-azure/package.json#L24

**Comment by EricDahlvang** [comment]
> we'll be retiring and no longer supporting version 1.x of the JavaScript SDK on **August 30, 2020**. After that date, you’ll no longer be able to use it to access Azure Cosmos DB.

**Comment by EricDahlvang** [comment]
This also affects the V3 SDK: https://github.com/microsoft/BotBuilder-V3/issues/164

**Comment by prashanthmadi** [comment]
@christopheranderson as you are moving from cosmosdb to bot world thought you might be interested in this..

**Comment by jspruance** [comment]
we expect the cosmosdb library to continue working beyond Aug 20, 2020 so there's no need to upgrade v3, especially since it is being phased out.

more details here:
https://github.com/microsoft/botframework-sdk/issues/5634

closing this ticket.
