### ISSUE TITLE
ShowTypingMiddleware provoke silent error behaviour

### ISSUE THREAD

**Issue by tolotrasamuel** [microsoft/botbuilder-js#1170]
## Versions
What package version of the SDK are you using.
 "botbuilder": "~4.5.3",
What nodejs version are you using
10
What browser version are you using
Chrome
What os are you using
Windows 10
## Describe the bug
Give a clear and concise description of what the bug is.
When I use the ShowTypingMiddleware middleware, onTurnError is not working anymore 
When there is a javascript expection, nothing happens, no error logs as well

## To Reproduce
1.  Use the ShowTypingMiddleWare

```
const botFrameworkAdapter = new BotFrameworkAdapter({
    appId: process.env.MicrosoftAppID,
    appPassword: process.env.MicrosoftAppPassword
});
botFrameworkAdapter.use(new ShowTypingMiddleware())
// Catch-all for errors.
botFrameworkAdapter.onTurnError = async (context, error) => {
    // This check writes out errors to console log
    // NOTE: In production environment, you should consider logging this to Azure
    //       application insights.
    console.error(`\n [onTurnError]: ${ error }`);
    // Send a message to the user
    await context.sendActivity(`Oops. Something went wrong!`);
    // Clear out state
    await conversationState.delete(context);
};
```
## Expected behavior
Give a clear and concise description of what you expected to happen.
ShowTypingMiddleWare should not impact onTurnError

[bug]

**Comment by CoHealer** [comment]
@stevkan , please attempt a repro

**Comment by stevkan** [comment]
@tolotrasamuel, I was able to repro the issue you are experiencing. That being said, this has already been reported as a possible bug in issue #726. I would suggest you add a comment and/or +1 the conversation to add weight to the issue and move the conversation along.

In the mean time, I am closing this particular issue in favor of the one already reported.

**Comment by tolotrasamuel** [comment]
@stevkan. I saw that issue earlier but it was closed without solution.
Now that you are closing this too, there is no open issue on this bug
