### ISSUE TITLE
UpdateActivityHandler definition is different for C#/JS

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-js#1184]
## Versions
What package version of the SDK are you using. Daily (9/18/19)
What nodejs version are you using: n/a
What browser version are you using: n/a
What os are you using: n/a

## Describe the bug
The signature and implementation of the _update activity_ handler is different between .NET and JavaScript, and the .NET one more closely matches the Bot Framework protocol.

In the .NET SDK, the handler returns a ResourceResponse object.
```csharp
public delegate Task<ResourceResponse> UpdateActivityHandler(ITurnContext turnContext, Activity activity, Func<Task<ResourceResponse>> next);
```
https://github.com/microsoft/botbuilder-dotnet/blob/ea31885753e15065f694c588309fccdc493eb61a/libraries/Microsoft.Bot.Builder/ITurnContext.cs#L54

In the JavaaScript SDK, the handler returns void.
```typescript
export type UpdateActivityHandler = (context: TurnContext, activity: Partial<Activity>, next: () => Promise<void>) => Promise<void>;
```
https://github.com/microsoft/botbuilder-dotnet/blob/ea31885753e15065f694c588309fccdc493eb61a/libraries/Microsoft.Bot.Builder/ITurnContext.cs#L54

The Bot Framework protocol [on success] returns a resource response object that contains "the ID for the resource."

## To Reproduce
1. Look at the code cited above.
1. Compare to what the Swagger file defines the underlying behavior to be.
1. Error: C# and JS implementations diverge, and the JS seems to be the one in error.

## Expected behavior
C# and JS implementations have the same semantics and align with the underlying protocol.

## Additional context
Any such divergence between the 2 (and soon to be more) SDKs has an exponential impact on the effort needed to support the documentation.

[bug]

**Comment by JonathanFingold** [comment]
This discrepancy extends to the TurnContext's _update activity_ method, too.

**Comment by stevengum** [comment]
Related to this: https://github.com/microsoft/botbuilder-js/issues/1037

**Comment by stevengum** [comment]
> Creating a new method to return a ResourceResponse for an UpdateActivity-type operation doesn't add utility to the SDK. After testing, the ResourceResponse returned for UpdateActivity contains the Id of the activity that was just updated. You cannot update an activity without its Id, so the return value doesn't add any value.
> 
> As such, we've decided to not increase our surface area nor will we implement any breaking changes.
> 
> Closing issue.

[Link to comment](https://github.com/microsoft/botbuilder-js/issues/1037#issuecomment-554859875)
