### ISSUE TITLE
Adaptive cards 1.1 do not render as images in Slack

### ISSUE THREAD

**Issue by yochay** [microsoft/botbuilder-js#1185]
## Versions
What package version of the SDK are you using - 4.4

## Describe the bug
Adaptive cards 1.0 on Slack is rendered as an image, since Slack doesn't support Adaptive cards. Adaptive card 1.1 is not rendering at all.

## Expected behavior
Adaptive cards render as images on any channel that doesn't support Adaptive cards. 

[bug]

**Comment by stevengum** [comment]
@yochay is this a customer reported issue? 

This also sounds like a service issue. We may need a support engineer to repro this and verify that its not related to the version or language of the SDK being used.

**Comment by gabog** [comment]
Closing due to lack of inactivity.
