### ISSUE TITLE
Port Search based Messaging extension to JS

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-js#1198]
Port search based messaging extension to JS from C#

https://github.com/microsoft/botbuilder-dotnet/tree/master/tests/Teams/SearchBasedMessagingExtension

**Comment by Virtual-Josh** [comment]
This is done.

**Comment by EricDahlvang** [comment]
@stevengum  already did this in the sample repo: https://github.com/microsoft/BotBuilder-Samples/tree/teams-samples/experimental/teams/javascript_nodejs/scenarios/search-extension-bot  (I'll just bring this over to use the sdk libs)

**Comment by EricDahlvang** [comment]
Closing (pr submitted awaiting review: https://github.com/microsoft/botbuilder-js/pull/1267 )
