### ISSUE TITLE
Port Activity Update & Delete scenario to JS

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-js#1199]
Port Activity Update/Delete scenario to JS from C#

https://github.com/microsoft/botbuilder-dotnet/tree/master/tests/Teams/Activity%20Update%20%26%20Delete

**Comment by EricDahlvang** [comment]
Closing ... PR is submitted and awaiting CR https://github.com/microsoft/botbuilder-js/pull/1260
