### ISSUE TITLE
TableStorage provider should add gzip option

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-js#12]
I'm assuming that our TableStorage provider only supports storing objects in a single text column which limits us to 64k.  We should add a gzip option as lots of people will want to store more data then that in conversation state.

We can also up the limit by spanning objects across multiple text columns.

**Comment by cristianossd** [comment]
Hello, @Stevenic, I would like to work on this

**Comment by cleemullins** [comment]
We have depricated the Table Storage Provider, and this Issue is no longer relevant.
