### ISSUE TITLE
ConsoleAdapter and WebChatAdapter should send conversationUpdate activities

### ISSUE THREAD

**Issue by billba** [microsoft/botbuilder-js#120]
It is boilerplate in most Bot Framework bots to produce a greeting using `conversationUpdate` activities. It would be easier to share bot code if `ConsoleAdapter` and `WebChatAdapter` sent these too. Without these it will be unclear to most developers how or when their bot should send a greeting.

Ideally these would mimic a single-user conversation, i.e. send two `conversationUpdate` activities, one for the bot and one for the user.

**Comment by Stevenic** [comment]
Totally agree. in fact I'm labeling this a bug as it was an oversight on my part.

**Comment by Stevenic** [comment]
Old issue
