### ISSUE TITLE
Port BFCard scenario from C# to JS

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-js#1201]
https://github.com/microsoft/botbuilder-dotnet/tree/master/tests/Teams/CardsBotFramework

**Comment by daveta** [comment]
@EricDahlvang : Doh - I actually was working on this one..  Just put a PR.

**Comment by daveta** [comment]
https://github.com/microsoft/botbuilder-js/commit/28407d398c9434562e39abadcdc3a50344296b5f
