### ISSUE TITLE
[Fix Ready] Port Conversation Update scenario from C# to JS

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-js#1203]
https://github.com/microsoft/botbuilder-dotnet/tree/master/tests/Teams/ConversationUpdate

**Comment by Virtual-Josh** [comment]
For more context, these helper functions are going to be needed as an extension on the turnContext

```
public static class TeamsTurnContextExtensions
    {
        public static async Task<ResourceResponse> TeamsSendToChannelAsync(this ITurnContext turnContext, string teamsChannelId, IActivity activity, CancellationToken cancellationToken = default)
        {
            var originalConversationId = turnContext.Activity.Conversation.Id;
            turnContext.Activity.Conversation.Id = teamsChannelId;
            var result = await turnContext.SendActivityAsync(activity, cancellationToken).ConfigureAwait(false);
            turnContext.Activity.Conversation.Id = originalConversationId;
            return result;
        }

        public static Task<ResourceResponse> TeamsSendToGeneralChannelAsync(this ITurnContext turnContext, IActivity activity, CancellationToken cancellationToken = default)
        {
            // The Team Id is also the Id of the general channel
            var teamId = turnContext.Activity.TeamsGetTeamId();

            if (string.IsNullOrEmpty(teamId))
            {
                throw new Exception("The current Activity was not sent from a Teams Team.");
            }

            return turnContext.TeamsSendToChannelAsync(teamId, activity, cancellationToken);
        }
    }
```

**Comment by Virtual-Josh** [comment]
https://github.com/microsoft/botbuilder-dotnet/pull/2605

**Comment by Virtual-Josh** [comment]
So there's a lot of overloaded terms here so let me attempt to separate and clarify.

There's 3 separate things that all happened around this ticket. The first thing is a bugfix that ensures the conversationReference is applied in the conversationUpdate and delete scenarios. That was fixed by Kyle in C# [here](https://github.com/microsoft/botbuilder-dotnet/pull/2516/files). I looked and I don't see a similar PR in JS. I'm not sure if that's because the issue doesn't exist in JS, or if it just hasn't been done. I would follow up with him to see if he checked JS. If it's not fixed in JS, it likely will need to be.

There is the actual conversationUpdate scenario which is the top link. That scenario covers all of the various flavors of conversation update (add/remove member, Teams channels added/removed/renamed, etc). You should be able to look at the code in that scenario for the method signatures and how to interact with it from the UI. If you have any questions let me know since I wrote that one. 

Finally, there's these helper methods which are linked above (which I'll just make their own ticket for clarity). The Teams SDK had 3 helpers that we didn't end up capturing in another structure. Those helpers are SendToChannel, SendToGeneralChannel, and NotifyUser. The first 2 methods are related to the conversation we had about needing to fiddle with the turnContext under the hood. Notify user is a strictly additive function which sets a property on the turnContext. I'll link all of the code in the other ticket. The easiest way to get at these functions is to wireup the onMessage method to accept some keywords. I'll link to the Helper scenario in the other ticket. 

If there's anything else I can clarify let me know. I know this isn't always the most straight forward thing.

**Comment by daveta** [comment]
https://github.com/microsoft/botbuilder-js/commit/61f6115ff8ac5fc794829b3cd0eb66be933707fd

**Comment by daveta** [comment]
Merged into main with stgum/TeamsHandler branch.
