### ISSUE TITLE
Port Proactive Message scenario from C# to JS

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-js#1209]
https://github.com/microsoft/botbuilder-dotnet/tree/master/tests/Teams/ProactiveMessages

**Comment by cleemullins** [comment]
Make sure a sample include a path using the Adapter and continue Conversation.

**Comment by tsuwandy** [comment]
Since other scenario samples already have proactive message, we decided this is unnecessary.
