### ISSUE TITLE
M2: on*Activity() all need a `context` parameter

### ISSUE THREAD

**Issue by billba** [Microsoft/botbuilder-js#121]
None of the `on*Activity` methods includes a `context` argument.

On the one hand they may not strictly be necessary. After all, in order to access these in the first place you need a `context`, and you can just close over it:

```ts
context.onSendActivity((activities, next) => {
    const state = conversationState.get(context);
    // do something with state
});
```

On the other hand, it makes it harder to just provide a function:

```ts
function doThing(context, activities, next) {
    const state = conversationState.get(context);
    // do something with state
}

context.onSendActivity((activities, next) => doThing(context, activities, next));
```

If `context` were an argument you could just do:

```ts
context.onSendActivity(doThing);
```

**Comment by Stevenic** [comment]
They actually do now but I haven't updated the docs yet. @cleemullins noticed this on Tuesday. I published the fix Tuesday but forgot to re-gen the docs.

**Comment by Stevenic** [comment]
fixed
