### ISSUE TITLE
Port Reply to Channel scenario from C# to JS

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-js#1210]
https://github.com/microsoft/botbuilder-dotnet/tree/master/tests/Teams/ReplyToChannel

**Comment by daveta** [comment]
Eric's already looking at this one..

**Comment by EricDahlvang** [comment]
This is waiting for https://github.com/microsoft/botbuilder-dotnet/pull/2658 to be ported to .js

**Comment by EricDahlvang** [comment]
PR submitted, awaiting review: https://github.com/microsoft/botbuilder-js/pull/1269
