### ISSUE TITLE
[BotFramework-Streaming-Extensions] Missing to export interfaces

### ISSUE THREAD

**Issue by Batta32** [microsoft/botbuilder-js#1222]
## Versions
Package version `botframework-streaming-extensions` - [v4.6.0-preview.76590](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botframework-streaming-extensions)

Nodejs v10.8.0

OS Windows 10

## Describe the bug
Using the library `botframework-streaming-extensions` to implement the latest changes of WebSocket in [botframework-solutions/botbuilder-skills](https://github.com/microsoft/botframework-solutions/tree/master/lib/typescript/botbuilder-skills) (TypeScript), we need to use `IStreamingTransportClient` and `IReceiveResponse` in order to have the same consistency as C# version. However, those interfaces are not exposed.

Is there any reason to do not export them?

## To Reproduce
1. Install `botframework-streaming-extensions` library using the registry of `botbuilder-v4-js-daily` in a project
2. Try to import `IReceiveResponse`, or `IStreamingTransportClient `
3. Check the following error **Module /node_modules/botframework-streaming-extensions/lib"' has no exported member 'IStreamingTransportClient'. Did you mean 'IStreamingTransportServer'?**

## Expected behavior
Import the `IStreamingTransportClient` and `IReceiveResponse` interfaces in order to use it internally.

## Screenshots

_Error during the import of those interfaces_
![image](https://user-images.githubusercontent.com/11904023/65781176-8a2ebd00-e121-11e9-87b6-336b81c90230.png)

_index file of `botframeworks-streaming-extensions`_
![image](https://user-images.githubusercontent.com/11904023/65781186-8dc24400-e121-11e9-9db1-c42d5e5cc9ae.png)

## Additional context

[bug]

**Comment by DDEfromOR** [comment]
@Batta32 we've merged the PR to add IStreamingTransportClient and IReceiveResponse to the exported classes.
