### ISSUE TITLE
[Fix Ready] Port the Teams Helper methods

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-js#1226]
Port the Teams helper methods. C# scenario is found [here](https://github.com/microsoft/botbuilder-dotnet/tree/master/tests/Teams/Helpers).

These are the 3 helper methods:

```
 public static class TeamsActivityExtensions
    {
        public static string TeamsGetTeamId(this IActivity activity)
        {
            var channelData = activity.GetChannelData<TeamsChannelData>();
            return channelData?.Team?.Id;
        }

        public static void TeamsNotifyUser(this IActivity activity)
        {
            var teamsChannelData = activity.ChannelData as TeamsChannelData;
            if (teamsChannelData == null)
            {
                teamsChannelData = new TeamsChannelData();
                activity.ChannelData = teamsChannelData;
            }

            teamsChannelData.Notification = new NotificationInfo
            {
                Alert = true,
            };
        }
    }
```

and 

```
public static class TeamsTurnContextExtensions
    {
        public static async Task<ResourceResponse> TeamsSendToChannelAsync(this ITurnContext turnContext, string teamsChannelId, IActivity activity, CancellationToken cancellationToken = default)
        {
            var originalConversationId = turnContext.Activity.Conversation.Id;
            turnContext.Activity.Conversation.Id = teamsChannelId;
            var result = await turnContext.SendActivityAsync(activity, cancellationToken).ConfigureAwait(false);
            turnContext.Activity.Conversation.Id = originalConversationId;
            return result;
        }

        public static Task<ResourceResponse> TeamsSendToGeneralChannelAsync(this ITurnContext turnContext, IActivity activity, CancellationToken cancellationToken = default)
        {
            // The Team Id is also the Id of the general channel
            var teamId = turnContext.Activity.TeamsGetTeamId();

            if (string.IsNullOrEmpty(teamId))
            {
                throw new Exception("The current Activity was not sent from a Teams Team.");
            }

            return turnContext.TeamsSendToChannelAsync(teamId, activity, cancellationToken);
        }
    }
```

There's one thing to note about the ```notifyUser``` method. If you look at the bot code you'll see the card section has 1 additional property, ```Summary```. This field allows the developer to provide a set of text for Teams to show in the Notification feed IF AND ONLY IF the activity has an attachment. If it doesn't have an attachment the Notification feed will just show the Activity.text.

**Comment by daveta** [comment]
>There's one thing to note about the notifyUser method. If you look at the bot code you'll see the card section has 1 additional property, Summary. This field allows the developer to provide a set of text for Teams to show in the Notification feed IF AND ONLY IF the activity has an attachment.

Any chance for a pointer to code?  I'm lazy ;)

**Comment by Virtual-Josh** [comment]
> There's one thing to note about the notifyUser method. If you look at the bot code you'll see the card section has 1 additional property, Summary. This field allows the developer to provide a set of text for Teams to show in the Notification feed IF AND ONLY IF the activity has an attachment.
> 
> Any chance for a pointer to code?  I'm lazy ;)
> BTW - excellent docs.

The C# code in the bot can be found here:
https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Teams/Helpers/Bots/HelperBot.cs

Let me know if you need anything else.

**Comment by daveta** [comment]
@Virtual-Josh : Can you take a look at [checking](https://github.com/microsoft/botbuilder-js/commit/950c331b605895ad53daac86f359426cc11d6adb)? Not sure how to apply your last comment - I just kept faithful to port..

BTW: Could not apply extension methods since interface.  In theory could apply for `TurnContext`, but kept it consistent.

**Comment by daveta** [comment]
Merged into main with stgum/TeamsHandler branch.
