### ISSUE TITLE
M2: ConsoleAdapter and WebChatAdapter needs startConversation/continueConversation

### ISSUE THREAD

**Issue by billba** [Microsoft/botbuilder-js#123]
Every adapter should have these.

**Comment by Stevenic** [comment]
I was already thinking about moving these to the Adapter interface as there's at least one piece of middleware I want to implement that would need at least `continueConversation()` exposed off the adapter.

Need to vet that change with the broader team though.

**Comment by Stevenic** [comment]
Made `continueConversation()` a required method.

**Comment by sgellock** [comment]
These are now samples.
