### ISSUE TITLE
M2: ConsoleAdapter and BotFrameworkAdapter perform different functions

### ISSUE THREAD

**Issue by billba** [microsoft/botbuilder-js#124]
```ts
consoleAdapter.listen(context => { /* bot logic */});

botFrameworkAdapter.processRequest(req, res, async (context) => { /* bot logic */});
```

Given that the signatures have to be different, there's no reason these can't both be called `processRequest`.

**Comment by Stevenic** [comment]
that's fair...

**Comment by billba** [comment]
Also, `consoleAdapter.listen()` is synchronous but `botFrameworkAdapter.processRequest()` is async. They should both be the same.

**Comment by billba** [comment]
Actually for parity I think what I would expect is:

```ts
consoleAdapter.listen(text =>
    consoleAdapter.processRequest(text, async (context) => {
        ....
    }
)

**Comment by Stevenic** [comment]
That feels really odd... Forcing me to pass the output from one `ConsoleAdapter` method to another method off the exact same object for the sake of parity is just odd... I've never seen that let along written something that requires that... Its simply odd.

 If you're striving for parity at that level then I think what you're looking for is this:

```JS
const rl = this.createInterface({ input: process.stdin, output: process.stdout, terminal: false });
rl.on('line', (line: string) => {
     consoleAdapter.processRequest(line, async (context) => {
          .....
     });
});
```

That's true parity in that the logic for receiving the users input is external to the adapter... The problem with this is that I'd argue that there's really only one way to accept console input and you're making every bot developer re-implement the exact same code over and over again.  The advantage to having the server code external to the connector is that there's not a single right way of writing your server logic and there are actually multiple server frameworks we support.

A compromise might be to expose a `ConsoleAdapter.processRequest(text, logic)` and a separate `ConsoleAdapter.listen(logic)` which wraps processRequest() in a more traditional way. I'm not sure when you would ever want to call processRequest() over listen() but I guess you could if you wanted to.

**Comment by billba** [comment]
Yes, I was just thinking along the lines of "true parity is to have no adapter have a message loop at all". And I agree, that seems didactic. So at this point I take back *both* my suggestions, because I don't like either of them. 

But it is really hard to wrap your head around (read: "explain to developers") what this new Adapter abstraction actually *is* if some adapters have a message loop and some don't.

**Comment by Stevenic** [comment]
Lets discuss more tomorrow then.

**Comment by Stevenic** [comment]
We no longer ship a console adapter
