### ISSUE TITLE
[BotFramework-Streaming-Extensions] Not Starting NamedPipe Server

### ISSUE THREAD

**Issue by bwamie** [microsoft/botbuilder-js#1259]
## Versions
Node.js:  v12.10.0
OS: Windows

## Describe the bug
await Promise.all blocks execution therefore function never returns. The NamedPipe server(s) never start listening.

## To Reproduce
Create a node.js bot
Download source code and enable streaming.

## Additional context
I was debugging both the bot and DirectLine ASE locally.

[[bug]](https://github.com/microsoft/botbuilder-js/blob/9a2bdabe2ee2a4566e8e4b0f26e028ff07ea4872/libraries/botframework-streaming-extensions/src/NamedPipe/NamedPipeServer.ts#L78)

**Comment by DDEfromOR** [comment]
This was addressed quite some time ago with #1266, resolving.
