### ISSUE TITLE
Port messaging extension - configure settings from C# to JS

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-js#1261]
Port message extension - configure settings

https://github.com/microsoft/botbuilder-dotnet/tree/master/tests/Teams/ComposeMessagingExtensions

**Comment by Virtual-Josh** [comment]
This is very similar to the action based extension scenario. I'm not sure who did that one, but it should be fairly straight forward to do. The manifest in this one does have 1 difference:

```bash
"canUpdateConfiguration": true,
```

**Comment by EricDahlvang** [comment]
I'll do this one.

**Comment by Virtual-Josh** [comment]
Done.

**Comment by EricDahlvang** [comment]
Closing: pr submitted, awaiting review https://github.com/microsoft/botbuilder-js/pull/1265
