### ISSUE TITLE
M2: middleware method name is unintuitive

### ISSUE THREAD

**Issue by billba** [Microsoft/botbuilder-js#127]
If I want to create an object which can be used as middleware, I need to call a method `onProcessRequest`. This is presumably meant to align with the `processRequest` method of (most) adapters.

The problem is that this method is also run before `startConversation` and `continueConversation`.  Based on the naming, I would not assume that.

At the very least a more neutral name such as 'adapterMiddleware` would be vastly preferred.

Even better, in #128 I proposed renaming `.use()` to `.onTurn()`, which exactly describes what it does: _runs on every turn_. Then we could use the same name `onTurn` name for the middleware method.

Now the naming of these methods guides you towards their purpose, not away.

**Comment by billba** [comment]
Just to make matters worse, `processRequest` is not standard across middleware (see #125). So the `onProcessRequest` is particularly meaningless for `ConsoleAdapter` which doesn't even have a `processRequest`.

**Comment by Stevenic** [comment]
It's been renamed to `onTurn` as agreed.
