### ISSUE TITLE
The name of .use() is unintuitive

### ISSUE THREAD

**Issue by billba** [Microsoft/botbuilder-js#128]
(this is extracted from a conversation in #74)

The name `.use()` is a nice homage to Express, but ironically it is not particularly expressive, nor does it mean anything to .net developers.

My proposed replacement is `.onTurn()`, which exactly describes what it does: _runs on every turn_.

Then, as described in #127, you can use the same name `onTurn` name for the middleware method.

Now the naming of these methods guides you towards their purpose, not away.

**Comment by Stevenic** [comment]
I'm personally mulling this over but would like others, including @tomlm and @cleemullins  to weigh in.  

So the additional arguments for leaving it `.use()` are that besides the fact this is the syntax used by Express and Restify, it's also the syntax used by other bot building JavaScript frameworks like BotKit and BotPress.  Honestly, if you've been programming in Node for more than a month, you have a pretty good sense that `.use()` means you're adding a plugin to something so I'm not sure I agree with the whole "unintuitive" comment.

**Comment by billba** [comment]
The name itself is unintuitive. It conveys nothing about middleware.

Obviously if you are familiar with the convention as used by other Node libraries, then you're fine.

**Comment by billba** [comment]
After discussing this with some .net folks it seems this is in common enough usage to be considered ubiquitous.
