### ISSUE TITLE
Card schemas are more restrictive than necessary

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botbuilder-js#1293]
## Versions
What package version of the SDK are you using. 4.6.0-preview1
What nodejs version are you using: 10 & 12
What browser version are you using: n/a
What os are you using: windows 10

## Describe the bug
Give a clear and concise description of what the bug is.

TypeScript types for the cards are more restrictive than necessary. For example, `ReceiptCard` requires `tap` to be present.

## To Reproduce
Try using `CardFactory.receiptCard(receiptCard: ReceiptCard)` in TypeScript with the content from a sample like: https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/06.using-cards/dialogs/mainDialog.js#L222-L256

<details>
<summary>Example `ReceiptCard` interface</summary>
```js
{
            title: 'John Doe',
            facts: [
                {
                    key: 'Order Number',
                    value: '1234'
                },
                {
                    key: 'Payment Method',
                    value: 'VISA 5555-****'
                }
            ],
            items: [
                {
                    title: 'Data Transfer',
                    price: '$38.45',
                    quantity: 368,
                    image: { url: 'https://github.com/amido/azure-vector-icons/raw/master/renders/traffic-manager.png' }
                },
                {
                    title: 'App Service',
                    price: '$45.00',
                    quantity: 720,
                    image: { url: 'https://github.com/amido/azure-vector-icons/raw/master/renders/cloud-service.png' }
                }
            ],
            tax: '$7.50',
            total: '$90.95',
            buttons: CardFactory.actions([
                {
                    type: 'openUrl',
                    title: 'More information',
                    value: 'https://azure.microsoft.com/en-us/pricing/details/bot-service/'
                }
            ])
        }
```
</details>

## Expected behavior
Give a clear and concise description of what you expected to happen.

Interface should be the least restrictive necessary.

## Screenshots

n/a

## Additional context

More popular cards don't suffer from this in TypeScript because their CardFactory builders are nicer and don't require the interface being passed in for their respective card.

[bug]

**Comment by stevengum** [comment]
@stevenic we could change the factory to take a `Partial<ReceiptCard>`, or we could mark properties as optional in the ReceiptCard interface... Optional properties would help users using ReceiptCard from only the `botframework-schema` library.
