### ISSUE TITLE
[engineering] Use consistent http request library

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botbuilder-js#1301]
**Is your feature request related to a problem? Please describe.**

We currently require several different http libraries across our js dependencies. This creates lots of extra stuff to download & install when we npm install.

These are the libraries I've found:

- node-fetch
- axios
- request
- request-promise

**Describe the solution you'd like**

We should standardize which library we use and remove other library usages. 

I'd recommend node-fetch as it is very lightweight and browser friendly if we ever need to have isomorphic js support from the SDK.

**Describe alternatives you've considered**

Alternatively, the Azure SDK team also recommends `axios`. It is less ideal for browser usage, imo, but browser isn't a critical scenario for us.

**Additional context**

[enhancement]

**Comment by stevengum** [comment]
@stevenic wants to use [`isomorphic-fetch`](https://www.npmjs.com/package/isomorphic-fetch) if I recall correctly. 

This feedback (using isomorphic-fetch) has been shared with @Aliandi in https://github.com/microsoft/botbuilder-js/pull/1224.

**Comment by christopheranderson** [comment]
Just took a look at `isomorphic-fetch` and my initial reaction would be to avoid it in a library (though it might be helpful if we were building an "app").

`isomorphic-fetch` depends on `node-fetch` - https://npm.anvaka.com/#/view/2d/isomorphic-fetch

It adds 400kb of other stuff on top of `node-fetch`. It also adds `fetch` to `global` which I'd argue isn't desirable given that we're a library and we'd bring that behavior along.

**Comment by alopix** [comment]
Is this issue still being looked at?
We saw an issue with the (now possibly not maintained) botbuilder-skills package, which also uses an old version of one of the libraries used in the other packages.

**Comment by stevengum** [comment]
Thanks for the interest @alopix, we're planning on picking this up for R8. @christopheranderson and I have been talking offline and are working on an engineering plan.

**Comment by christopheranderson** [comment]
`request` has been deprecated - https://www.npmjs.com/package/request

We should definitely prioritize the switch now.

**Comment by christopheranderson** [comment]
We're going with `node-fetch` based on it meeting our browser/node multi-targeting needs and that the Azure JS libs are standardizing on it.

**Comment by sgellock** [comment]
removing chris Anderson.  Colonel-Major, we should either assign to Steve or Steven

**Comment by axelsrz** [comment]
We're currently blocking this thread due not having enough context to know how/if this would impact browser compatibility, along as beign a breaking change.
