### ISSUE TITLE
[nit] Avoid @types/node usage in public dependencies

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botbuilder-js#1302]
* EDIT: This was edited to become a tracking issue, the problem specified below will be tracked per library.

**Is your feature request related to a problem? Please describe.**

It is not ideal to have public dependencies on `@types/node`. It can cause issues due to type conflicts across node versions. Additionally, if any code is used from the browser, it can cause issues with webpack/rollup/etc.

**Describe the solution you'd like**

Remove @types/node dependency anywhere we're exposing a node.js type on one of our types.

Where we do expose a node.js type on our types, we should consider an alternative more scoped type or our own interface which duplicates the required surface area.

**Describe alternatives you've considered**

Can keep the dependency and set the version to "*" to set the user have greater control (since we can use `engine` setting to signal to users on versions older than we support).

[enhancement]

## Tracking Status
**adaptive-expressions**
- [ ] PR
- [ ] Merged

**botbuilder**
- [ ] PR
- [ ] Merged

**botbuilder-ai**
- [ ] PR
- [ ] Merged

**botbuilder-applicationinsights**
- [ ] PR
- [ ] Merged

**botbuilder-azure**
- [ ] PR
- [ ] Merged

**botbuilder-core**
- [ ] PR
- [ ] Merged

**botbuilder-dialogs**
- [ ] PR
- [ ] Merged

**botbuilder-dialogs-adaptive**
- [ ] PR
- [ ] Merged

**botbuilder-dialogs-declarative**
- [ ] PR
- [ ] Merged

**botbuilder-lg**
- [ ] PR
- [ ] Merged

**botbuilder-testing**
- [ ] PR
- [ ] Merged

**botframework-config**
- [ ] PR
- [ ] Merged

**botframework-connector**
- [ ] PR
- [ ] Merged

**botframework-schema**
- [ ] PR
- [ ] Merged

**botframework-streaming**
- [ ] PR
- [ ] Merged

**Comment by lukiffer** [comment]
Agreed – this is causing projects that have specific `@types/node` version dependencies from building since it's bundled into the package:

```
node_modules/botframework-connector/lib/connectorApi/models/index.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '<redacted_root>/node_modules/botframework-connector/node_modules/@types/node/ts3.2/index.d.ts' and '<redacted_root>/node_modules/@types/node/ts3.7/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~
```

`npm ls @types/node` produces:

```
example-project@1.0.0 <redacted_root>
└─┬ @types/restify@8.4.1
  ├─┬ @types/bunyan@1.8.6
  │ └── @types/node@13.13.6  deduped
  ├── @types/node@13.13.6
  └─┬ @types/spdy@3.4.4
    └── @types/node@13.13.6  deduped
```

**Comment by joshgummersall** [comment]
Closing in favor of https://github.com/microsoft/botbuilder-js/issues/2429 and https://github.com/microsoft/botbuilder-js/issues/2427.
