### ISSUE TITLE
[Teams] TeamsActivityHandler Cleanup & Tests

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#1314]
Need tests for:
- [X] handleTeamsCardActionInvoke
- [X] handleTeamsMessagingExtensionQuery
- [X] handleTeamsMessagingExtensionSelectItem
- [X] handleTeamsMessagingExtensionBotMessagePreviewEdit
- [X] handleTeamsMessagingExtensionBotMessagePreviewSend
- [X] handleTeamsMessagingExtensionFetchTask
- [X] handleTeamsMessagingExtensionConfigurationQuerySettingUrl
- [X] handleTeamsMessagingExtensionConfigurationSetting

Need scenario with:
- handleTeamsCardActionInvoke

Other:
- Messaging Extension search handles the onSelectItem incorrectly

**Comment by stevengum** [comment]
@mrivera-ms this is a good candidate for SouthWorks to help out on. The listed methods in the original post should be `protected` or `public` and need to be covered by tests.

**Comment by axelsrz** [comment]
Closing this given that all subtasks are done
