### ISSUE TITLE
[engineering systems] Should run tests across full version support matrix

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botbuilder-js#1320]
**Is your feature request related to a problem? Please describe.**

We only test against V10. V12 is about to hit LTS, but we're not running tests there to catch any errors it might support. Additionally, we don't run tests for V8. Do we support V8?

**Describe the solution you'd like**

Run our tests against all supported major versions of Node.js

[enhancement]

**Comment by stevengum** [comment]
WIP on `stgum/test`

**Comment by stevengum** [comment]
To answer the original question, we support Node LTS (even releases) 10 and 12. We moved to Node 10 a few minor releases after 4.0 to make use of RegExp Named Groups.

I’m adding Node 14 CI in preparation for it becoming the new primary sta
