### ISSUE TITLE
LG Expressions cannot have \' or } in them

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-js#1329]
## Versions
Latest version of botbuilder-expresssion-parser:4.5.9 and botbuilder-lg:4.6.14 of node although I suspect it is also in the dotnet version since it seems connected to the grammar.

## Describe the bug
You cannot put ' or {} into string expressions in templates.

## To Reproduce
This template does not work.  (It also uses a custom function which can be replaced with anything that generates a list.) 
```
# template
- \```
# @{property}Entity(value)
- SWITCH: {value}
@{join(foreach(schema.properties[property].enum, enum, concat('CASE: {\'', enum, '\'}\n', foreach(phrases(enum), phrase, concat('- ', phrase, '\n')))), '\n')}
- DEFAULT: I don't understand {value}
\```
```

## Expected behavior
You should be able to include ' or {} in any .lg expression.

[bug]

**Comment by boydc2014** [comment]
close due do duplicated with https://github.com/microsoft/botbuilder-dotnet/issues/2759
