### ISSUE TITLE
[BotBuilder-Dialogs] - Export channel file

### ISSUE THREAD

**Issue by Batta32** [microsoft/botbuilder-js#1354]
**Is your feature request related to a problem? Please describe.**
As [botframework-solutions](https://github.com/microsoft/botframework-solutions) developer, I would like to import the `functions` and `constants` of `channel` in order to use it in `BotBuilder-Solutions` library of TypeScript (as [C# library](https://github.com/microsoft/botframework-solutions/blob/next/sdk/csharp/libraries/microsoft.bot.builder.solutions/Feedback/FeedbackMiddleware.cs#L63) does).

They are exported but not in the `index` of the `choices` folder, so it is not possible to import them using the `botbuilder-dialogs` library.

_Lack of channel export file in the index file_
![image](https://user-images.githubusercontent.com/11904023/67498363-aefd4e00-f655-11e9-83ef-cbf8c23c18ec.png)

**Describe the solution you'd like**
I would like to have the export of the `channel` file in the `choices index` as it follows.

![image](https://user-images.githubusercontent.com/11904023/67498416-c9372c00-f655-11e9-91db-7a5aa9e24053.png)

**Describe alternatives you've considered**
\-

**Additional context**
While working in a parity of the last release of the [[C#] BotBuilder-Solutions library](https://github.com/microsoft/botframework-solutions/releases/tag/v0.6-beta) in the TypeScript one, we needed to use the `supportsSuggestedAction` function of the `channel` file but in `botbuilder-dialogs` is not exported correctly.

[enhancement]

**Comment by cleemullins** [comment]
@batta32, this seems like an oversight on our part, and we should be able to pick this up in R8.
