### ISSUE TITLE
appears coverage is being reported on test code

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/botbuilder-js#136]
for example:

connector.test.suite.js

appears in the coverage report from nyc

**Comment by Stevenic** [comment]
I was wondering why it was so low.

**Comment by Stevenic** [comment]
Actually the issue looks to be that in most cases the coverage is against our `src` files and not our `lib` files.

**Comment by Stevenic** [comment]
I think I have it more accurately covering the code we're actually shipping and we're up to 32% now which is obviously still in the red.  We're still reporting some auto generated code which I'm working to eliminate.

**Comment by Stevenic** [comment]
I have coverage up to 70% by excluding all of the auto-generated **botframework-xxxx** packages.  I had to add the exclusions into the root package.json.
