### ISSUE TITLE
 Impossible to set ListStyle.none to ChoicePrompt.

### ISSUE THREAD

**Issue by rodolZ80** [microsoft/botbuilder-js#1370]
## Versions
Botbuilder version 4.5.3
NodeJS version 10.16.3

## Describe the bug
It is impossible to set ListStyle.none to ChoicePrompt.

## To Reproduce
1.  Set a promptOptions with style as ListStyle.none
`const promptOptions: PromptOptions = { prompt: 'Say a letter' ,  choices: ['A', 'B'], style: ListStyle.none }`
2.  Call to a prompt type ChoicePromt with this promptOptions
`return await stepContext.prompt('CHOICE_PROMPT', promptOptions);`
3. Options A and B are shown on the screen when they should not be shown.

## Expected behavior
Show only the text  'Say a letter'  in the screen. (client)

## Additional context
The problem is in ChoicePrompt.ts
The style is set to ListStyle.auto by default
Line 67: ` this.style = ListStyle.auto;`
In the onPrompt method if the options.style is false, null undefined or 0 , the assigned style will be the default one (ListStyle.auto).
Line 83: `const choiceStyle: ListStyle = options.style || this.style;`
The number none is assigned the value 0 . 
File prompt.ts Line 17 :
```
export enum ListStyle {
    /**
     * Don't include any choices for prompt.
     */
    none,
```
`

[bug]

**Comment by mdrichardson** [comment]
@rodolZ80 I'm able to reproduce this and will submit a PR to fix it once I have the time to. In the meantime, I was able to get it work doing this:

```js
const choicePrompt = new ChoicePrompt(<yourPromptId>);
choicePrompt.style = ListStyle.none;

this.addDialog(choicePrompt);
```

**Comment by mdrichardson** [comment]
@rodolZ80 GREAT work tracking down what needed to be fixed. Made for an easy PR.
