### ISSUE TITLE
DialogContext.prompt includes unnecessary (and uncallable) overloads

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-js#1372]
## Versions
What package version of the SDK are you using: **4.6 preview**
What nodejs version are you using: n/a
What browser version are you using: n/a
What os are you using: **Windows 10 Pro x64**

## Describe the bug
DialogContext.prompt includes an implementation signature and two overload signatures (3 signatures). This creates two sources of confusion:
1. Only 2 signatures show up as options in VS Code.
1. Only 2 signatures get documented through our publishing pipeline.

## To Reproduce
1. Notice that 3 signatures are present in the library for [DialogContext.prompt](https://github.com/microsoft/botbuilder-js/blob/ef4123ef3250d4eacabe21b0fd85448878d0bf60/libraries/botbuilder-dialogs/src/dialogContext.ts#L206-L212).
   ```javascript
    public async prompt(dialogId: string, promptOrOptions: string | Partial<Activity> | PromptOptions): Promise<DialogTurnResult>;
    public async prompt(dialogId: string, promptOrOptions: string | Partial<Activity> | PromptOptions, choices: (string | Choice)[]): Promise<DialogTurnResult>;
    public async prompt(
        dialogId: string,
        promptOrOptions: string | Partial<Activity>,
        choices?: (string | Choice)[]
    ): Promise<DialogTurnResult> {
   ```
2. Edit bot code in VS Code and examine the tool tips when you start to add a call to the DialogContext's prompt method. The IDE recognizes only 2 signatures:
   - 1/2 is `prompt(dialogId: string, promptOrOptions: string | Partial<Activity> | PromptOptions): Promise<DialogTurnResult<any>>`
   - 2/2 is `prompt(dialogId: string, promptOrOptions: string | Partial<Activity> | PromptOptions, choices: (string | Choice)[]): Promise<DialogTurnResult<any>>`
3. Look at our documentation for [DialogContext](https://docs.microsoft.com/en-us/javascript/api/botbuilder-dialogs/dialogcontext?view=botbuilder-ts-latest) and scroll down to the methods section. Our publishing pipeline recognizes only these same two signatures.
4. Error, this is confusing and seems to indicate that there is unnecessary code in the repo.

## Expected behavior
We should not have unnecessary code in the repo. In addition, we could simplify this to just the one implementation signature without it being a breaking change. This would:
- make this class slightly easier to understand and use
- make this method easier to document

## Additional context
re: [TypeStrong/typedoc issue 1122](https://github.com/TypeStrong/typedoc/issues/1122)

Note the closing comment:
> In this case, I'd argue that you shouldn't have overloads in the first place. You should only have the implementation signature.

[bug]

**Comment by sgellock** [comment]
@stevenic, can you look.  breaking change?

**Comment by cleemullins** [comment]
@christopheranderson Could you take a quick look at this and see if there's a way to resolve this w/o introducing a breaking change? I don't think @stevenic will be able to get to this.

**Comment by Stevenic** [comment]
This is the way TypeScript works so By Design.
