### ISSUE TITLE
[Engineering] Investigate using yarn and alternative monorepo tooling

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#1383]
### Edit:
Alternatives to rush and pnpm may involve some sort of combination of yarn and another tool, especially as Yarn 2 now contains desired functionality we would obtain by using rush and pnpm.

[Yarn 2 stable release blog post](https://dev.to/arcanis/introducing-yarn-2-4eh1#new-protocol-raw-portal-endraw-)

GitHub repository for Yarn 2: https://github.com/yarnpkg/berry

___ 

### Original post _(Out of date)_:

Historically we've experienced difficulties with using lerna. This is a tracking item for investigating the use of [rush](https://rushjs.io/) and [pnpm](https://pnpm.js.org/).

### Path to success
- [ ] Test branch with `rush` and `pnpm` configured
- [ ] Functional Pipeline that contains `rush` and `pnpm` tasks

[enhancement]

**Comment by christopheranderson** [comment]
FYI - there is a branch with this: https://github.com/christopheranderson/botbuilder-js/tree/chrande/rush

We've opted to focus on CLI repo for now since it is less busy to test rush there.

Overall, perf is really nice, especially on local machine with higher number of cores.

**Comment by Virtual-Josh** [comment]
Add Workspaces and Workspace Depdencies

**Comment by stevengum** [comment]
The work is currently being done on this branch: [`josh/yarn`](https://github.com/microsoft/botbuilder-js/tree/josh/yarn)

**Comment by Virtual-Josh** [comment]
The josh/yarn branch has yarn installed, and I believe the workspace configuration setup. I'd have to do a little more testing/wait for yarn2 documentation to get more fleshed out. It does not have `workspace constraints` or `portals` setup.

**Comment by stevengum** [comment]
Closing via https://github.com/microsoft/botbuilder-js/pull/2984, let's follow up on any additional pieces of work in new issues.
