### ISSUE TITLE
[Documentation] Docs seem out of sync with code; cannot find 'Bot' class 

### ISSUE THREAD

**Issue by microsoftly** [Microsoft/botbuilder-js#139]
Several places in the docs and comments refer to an instantiatable class ```Bot```, but I can't find any evidence of this class existing. I imagine these docs are outdated.

A few examples:
* https://github.com/Microsoft/botbuilder-js/wiki/Using-LUIS-and-QnA-Maker#using-luis
* https://github.com/Microsoft/botbuilder-js/blob/a19f787657c2f0e85bc93f5b078cc3481774ba01/libraries/botbuilder-dialogs/lib/dialogSet.d.ts#L32

**Comment by Stevenic** [comment]
Yes... We're working to update the docs.

**Comment by v-ducvo** [comment]
Content updated with working sample code. We can close this item now...
