### ISSUE TITLE
dialogContext.cancelAllDialogs() does not return cancelled status

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-js#1391]
## Versions
4.6.x

## Describe the bug
Currently, when calling dialogContext.cancelAllDialogs() the returned dialogTurnResult.status is 'complete', the expected behavior is to be 'cancelled' like in dotnet
 
## To Reproduce
Pull the [CoreBot](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/13.core-bot) project from samples and update [Line 54](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/13.core-bot/tests/dialogs/cancelAndHelpDialog.test.js#L54) to assert for status = cancelled

```
assert.strictEqual(client.dialogTurnResult.status, 'cancelled');
```
The test will fail, the expected behavior is for the test to pass so it behaves the same as dotnet.

Once this is fixed in the JS SDK, we need to update samples and generators to match.

FYI: @sgellock, @axelsrz,  @tracyboehrer

**Comment by Stevenic** [comment]
This ended up being a regression in C#.
