### ISSUE TITLE
Unusual types in Teams Schema

### ISSUE THREAD

**Issue by beauzeaux** [microsoft/botbuilder-js#1398]
## Versions
botbuilder ^4.6.0

## Describe the bug
[botframework-schema/src/teams/index.ts](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botframework-schema/src/teams/index.ts) has a few overly generic types. 

[Type1](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botframework-schema/src/teams/index.ts#L1249) - an input type (?)
[Type2](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botframework-schema/src/teams/index.ts#L1337) - this appears to be the task module response type
[Type3](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botframework-schema/src/teams/index.ts#L1353) - this appears to be the messaging extension response type

## To Reproduce
index.d.ts in distributed botbuilder js sdk

## Expected behavior
I would expect these to have more precise type names.

[bug]

**Comment by cleemullins** [comment]
Spoke with @virtual-josh, and expecting to wrap this up today.
