### ISSUE TITLE
[Question] Will the Direct Line API be changed in V4?

### ISSUE THREAD

**Issue by microsoftly** [Microsoft/botbuilder-js#140]

**Comment by Stevenic** [comment]
Not that I'm personally aware of.

**Comment by dandriscoll** [comment]
Neither the Direct Line protocol nor the core Bot Framework protocol are undergoing major revisions at this time. v4 applies only to the Bot Builder SDK.

We're continually adding features to the core protocols but these are typically additive and are not breaking.
