### ISSUE TITLE
Deprecate Payments

### ISSUE THREAD

**Issue by Jeffders** [microsoft/botbuilder-js#1418]
## Version
4.6

## Describe the bug
Payments support is being deprecated. We need to deprecate/obsolete all of the payments schema objects in the Microsoft.Bot.Schema namespace.

**Comment by cleemullins** [comment]
@jeffders, I don' think we're going to get to this in R7. I've pushed it to R8. 

Let me know if there's a business need to do this sooner.

**Comment by cleemullins** [comment]
I'll leave this targeted to R8, but there's a reasonable chance Michael can land this in R7.
