### ISSUE TITLE
npm install fails at downloading cldr-data dependency

### ISSUE THREAD

**Issue by ubreddy** [microsoft/botbuilder-js#1430]
## Versions
What package version of the SDK are you using. 4.6.1
What nodejs version are you using : 11.5.0
npm version: 6.7.0
What os are you using : windows 10

## Describe the bug
Give a clear and concise description of what the bug is.
npm install botbuilder-dialogs  fails to install dependency... 

It gets stuck after downloading 90%. Tried multiple times...

![image](https://user-images.githubusercontent.com/2233628/69162670-0b4b7480-0b13-11ea-8d71-49c75c85b36c.png)

## Expected behavior
npm install should have installed the module and all its required dependencies.

[bug]

**Comment by jwiley84** [comment]
![image](https://user-images.githubusercontent.com/17333688/69171856-95fb8780-0ab1-11ea-86e8-5a5d0f919993.png)


I am unable to repro this issue, however, one thing I did notice was the difference in the size of our downloads. For some reason, yours is literally 3* larger then mine. Further research show that occasionally cldr-data fails on initial installation, but is alright on further installations. This possibly accounts for the size difference.

I can see from your image that you terminated the installation at 94%. Can you post the error you receive if it continues?

**Comment by ubreddy** [comment]
Finally after multiple tries it worked.. Thanks
