### ISSUE TITLE
cldr-data dependency in botbuilder-dialogs almost 300MB in size

### ISSUE THREAD

**Issue by SirensOfTitan** [microsoft/botbuilder-js#1440]
## Versions
What package version of the SDK are you using. *46.1*
What nodejs version are you using *v13.1.0*
What browser version are you using N/A
What os are you using *Linux*

## Describe the bug
botbuilder-dialogs seems to pull in the full cldr-data repo, which lands as 296MB on my computer:
```bash
> npm-why cldr-data
  app > botbuilder-adapter-slack > botkit > botbuilder-dialogs > cldr-data@35.1.0
  app > botkit > botbuilder-dialogs > cldr-data@35.1.0

> cd node_modules && du -hs * | sort -h
[...]
296M	cldr-data
```

I'm not familiar with how the npm `cldr-data` dependency works, but `botbuilder-dialogs` uses a handful of files from `cldr-data`, why are we pulling in the entire dependency?   Is my config wrong somewhere?  

## To Reproduce
Install `botbuilder-dialog` or anything that depends on it.  

## Expected behavior
`botbuilder-dialog` cherry-picks what it needs from cldr-data

**Comment by jwiley84** [comment]
Related: https://github.com/microsoft/botbuilder-js/issues/1430

**Comment by benbrown** [comment]
Hi @SirensOfTitan, we are working on a resolution to this issue. It will likely be included in our next release.
