### ISSUE TITLE
[bf-connector] Cleanup Errors in authentication code

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#1445]
In `botframework-connector/authentication` we return normal JS errors with non-normalized error messages.

This has led to manual `Error.message` parsing in determining the correct HTTP Status code to send back to the caller of the bot. 

See https://github.com/microsoft/botbuilder-js/pull/1433#discussion_r349991588.

**Comment by stevengum** [comment]
Moving to R8 as this is a P2.

**Comment by cleemullins** [comment]
@zerryth, pushing this to your backlog. We've been punting this for a while, and I would love to see it make it's way into R8. Given your current queue, I believe this is something we can do.

**Comment by Zerryth** [comment]
Sounds good!

**Comment by johnataylor** [comment]
moving to R9
