### ISSUE TITLE
Issue with Enterprise App registered bot

### ISSUE THREAD

**Issue by VaradVenkatKrishna** [microsoft/botbuilder-js#1447]
I am getting the following error when we try to connect to the deployed bot. 

We followed App registration manually and entered App Id and Password while creating a web app bot. after the deployment bot is throwing the below issue. 

```
[onTurnError] unhandled error: Error: Bad Request
(node:2588) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 500 ERROR
 Error: Bad Request
    at MicrosoftAppCredentials.<anonymous> (D:\home\site\wwwroot\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:132:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\home\site\wwwroot\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at BotFrameworkAdapter.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:638:27)
    at Generator.throw (<anonymous>)
    at rejected (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:13:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Investigated further, it looks like an issue with setting of manifest "signInAudience": "AzureADMyOrg" we want this setting to be but not working, 
 if we change it to "AzureADandPersonalMicrosoftAccount"

but with AzureADMyOrg how to make it work?

**Comment by stevkan** [comment]
Did you create your own AppId and Password or were they auto-generated by the Azure service? To clarify, you are wanting to use "AzureADMyOrg", correct?

Also, are you certain you have the necessary AD app registration permissions assigned that would allow a user to connect and log in? Some companies establish IT policies that block user access without specific access having been granted.

**Comment by VaradVenkatKrishna** [comment]
Our App registration admin team has created the app registration manually with the "signInAudience": "AzureADMyOrg" settings. 
 and as per the documentation here https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0#app-registration
its says only "AzureADandPersonalMicrosoftAccount"

and in this document  https://docs.microsoft.com/en-us/azure/bot-service/abs-quickstart?view=azure-bot-service-4.0#feedback
it says "AzureADMultipleOrgs",  "AzureADandPersonalMicrosoftAccount"

But not "AzureADMyOrg", What is the solution for a single-tenant organization.

Yes we have all the permissions but only the above configuration is causing bot not connecting to Azure AD

**Comment by stevkan** [comment]
@VaradVenkatKrishna, the bot's app registration must be set to one of the multi-tenant options (`AzureADandPersonalMicrosoftAccount` or `AzureADMultipleOrgs`) and **not** `AzureADMyOrg`. The reason for this is the bot needs to be able to access the BotFramework connector services (i.e., the channels able to be configured in your bot's Azure settings - Facebook, Twilio, etc.). If not set to multi-tenant, then the bot will fail, as mentioned in the docs.

If this is regarding [user authentication](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp), that is achieved via a separate app registration. It is in this that any of the three options are available to select. In and of itself, this app registration doesn't make a bot inaccessible to users (assuming a user is already on the same channel as the bot), but it does restrict user's from conversing beyond the authentication step with the bot.

Does this help?

**Comment by VaradVenkatKrishna** [comment]
@stevkan Yes Understood. Thank you.

**Comment by tommyJimmy87** [comment]
Hi @stevkan, just one quick question about this, since I'm using Microsoft Teams as channel, what I understood is that we have anyway to use the "botframework" organization for make Teams retrieve the Auth Token (this also means that anyway the Bot App ID that we are using in Teams must have the Multi Org enabled). 
Is this right?
