### ISSUE TITLE
[Tests] Fix BotFrameworkAdapter.getTokenStatus() test

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#1449]
> This test has been throwing an uncaught promise exception. I rewrote the test so that it properly fails, and skipped it because it was already failing in master. I will file an issue for someone to look into this test.

_Originally posted by @stevengum in https://github.com/microsoft/botbuilder-js/pull/1337_

This test has been failing for a while now, but the test was also incorrectly written and throwing uncaught promise exceptions. 

This issue is to track fixing and reenabling the test.

**Comment by mdrichardson** [comment]
Fixed via https://github.com/microsoft/botbuilder-js/pull/2414
