### ISSUE TITLE
[Feature Request] i18n support

### ISSUE THREAD

**Issue by tao1** [Microsoft/botbuilder-js#145]
This feature request is a duplicate of https://github.com/Microsoft/BotBuilder-Calling/issues/2
## System Information (Required)
* SDK Language: NODE
* SDK Version: 3.0.1
* Development Environment: AZURE_BOT_SERVICE

## Issue Description
Please add support for other cultures, only en-US is currently supported by Prompt.culture().
So my bot understands french language but only speaks english :(

## Code Example
```
const calling = require('botbuilder-calling');
const playPrompt = new calling.PlayPromptAction(session).prompts([calling.Prompt.text(session, 'Je parle français').culture('fr-FR')]);
session.beginDialog('BotBuilder:Prompts', {
    promptType: calling.PromptType.record,
    action: playPrompt.toAction(),
    maxRetries: 1
});
```

## Steps to Reproduce the Issue
1. Make a Skype bot with calling enabled
2. Use PlayPrompt with fr-FR culture
3. Skype bot speaks in english

## Expected Behavior
My bot speaks french.

## Actual Results
My bot speaks english.

**Comment by Stevenic** [comment]
Unfortunately... I don't believe that skype is investing in new features for the existing service.
