### ISSUE TITLE
[Engineering] Node.js 12.x support plan

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#1452]
## Versions
What Node.js version are you using? **10.x**

## Description
Using Node.js ^12.x breaks one of the `TokenResolver` tests. As it is the current LTS, we should start preparing to target or "officially" support it.

### Re: Azure App Services
Currently, we officially support 10.x which is the current runtime available on Windows App Services. 

Our Node.js samples' ARM templates provision a Windows App Service and it is also what the Web App Bots use.

**12.x is supported on Linux App Services.**

### Additional

[**Node.js Releases**](https://nodejs.org/en/about/releases/) on 11/22/2019

![image](https://user-images.githubusercontent.com/14935595/69454912-1fae8d80-0d1c-11ea-82d5-4719d30d43e1.png)

**Comment by cleemullins** [comment]
Enable a CI build in JS using Node12. Leave the EXISTING Node 10 build running as well.

**Comment by BruceHaley** [comment]
A new Node 12.x build has bee created.
The Node 10 build name: BotBuilder-JS-master-CI
The Node 12 build name: BotBuilder-JS-master-CI-node12
In this build, test TokenResolver is failing.
