### ISSUE TITLE
TrainAPI call not working

### ISSUE THREAD

**Issue by wehnicde** [microsoft/botbuilder-js#1454]
## Versions
Package of SDK (idk, I just generated that bot, so the newest?)
nodejs v10.14.1
Chrome V78.0.3904.108
Win 10

## Describe the bug
The feedback with the trainAPI doesn't work, theres an error if you click on an suggested answer.

`[onTurnError] unhandled error: TypeError: Cannot read property 'callTrainAsync' of undefined
(node:3044) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 500 ERROR
 ReferenceError: InputHints is not defined
    at BotFrameworkAdapter.adapter.onTurnError [as turnError] (D:\home\site\wwwroot\index.js:46:72)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at BotFrameworkAdapter.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:638:27)
    at Generator.throw (<anonymous>)
    at rejected (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:13:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3044) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

## To Reproduce
1. Generate a new qnaBot with qnamaker.ai
2. Type in a question which calls the trainAPI 
3. Click on a suggested Answer

## Expected behavior

It should say "thanks for your feedback" and give the suggestion to the qnaMaker.

## Screenshots
My screenshots are from my html doc, but the issue is the same in the azure test webchat.

![image](https://user-images.githubusercontent.com/57532084/69783459-df378f80-11b3-11ea-8d78-5b9c04079f04.png)

![image](https://user-images.githubusercontent.com/57532084/69783638-32a9dd80-11b4-11ea-89b1-60a00e43bab5.png)
(sending will change to sending failed after a while)

## Additional context
The feature is not necessary, but as it is generated by the qnaMaker I think it should work. 

[bug]

**Comment by anusharavindrar** [comment]
@BeschtPlaier a few more questions to repro your issue. Did you test your bot locally on the emulator or any other channel? Are you still getting the same error? How long does it take for the status to change to 'sending failed'? Does your knowledge base work as expected in the qnamaker portal?

**Comment by BeschtPlaier** [comment]
I tested the bot at the Azure test in Webchat feature. 
Yes its still the same Error
Idk it is the standart sending failed time, same time as if i have no network connection, i think 20 seconds or something.
Everyting works fine exept the Training feature, so yea, my knowledgebase in the qnamaker portal works as expected. The training feature gets implemented at the BotCode at Azure

**Comment by anusharavindrar** [comment]
@wehnicde I am guessing there is something wrong in the bot code specifically to do with calling the Train API. Can you post your code on your implementation so far? Also, you can try testing the qnamaker-activelearning-bot [sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/48.qnamaker-active-learning-bot) with your KB credentials to see if it works as expected .

**Comment by anusharavindrar** [comment]
@wehnicde are you still working on this?

**Comment by wehnicde** [comment]
yea I am. Sorry had a busy week. 
What do you mean by 

> Can you post your code on your implementation so far?

I will try the sample and post it here as soon as I got to try it.

**Comment by wehnicde** [comment]
Ähm, I don't know what have changed, but now it is working as expected.
