### ISSUE TITLE
await dialogContext.continueDialog() returns null

### ISSUE THREAD

**Issue by samueleorfei** [microsoft/botbuilder-js#1457]
## Versions
What package version of the SDK are you using: 4.3.4
What nodejs version are you using: 13.2.0
What browser version are you using: //
What os are you using: Windows 10 1903

## Describe the bug
```typescript
const dialogContext = await this.dialogs.createContext(turnContext);
const results = await dialogContext.continueDialog();
```
with dialogs being a `DialogSet` and `turnContext` the parameter from the `onTurn` method. While on the first dialogs `results.status` is correctly "empty" or "waiting" at some point after calling a `ChoiceInput` dialog, `results` will be `null`

## To Reproduce
I'm not be able to reproduce it without showing the full code (and I can't) but it would be enough to understand in which cases it can return null

## Expected behavior
The docs states it can return undefined or a working object https://docs.microsoft.com/it-it/javascript/api/botbuilder-dialogs/dialogturnresult?view=botbuilder-ts-latest

## Additional context

[bug]

Regards,
Samuele

**Comment by mdrichardson** [comment]
@Samuele I'm not seeing anything in the SDK that jumps out that would cause `continueDialog` to return `null`.

* If you upgrade your botbuilder/botframework packages, does this still occur?
* Are you calling `endDialog(null)` anywhere?
* Although you can't share your code, can you share the exact flow? Something like:

```
User joins chat ->
  Bot sends welcome message ->
    User says anything ->
      Bot begins Waterfall dialog. First step is Choice prompt ->
        User enters a valid choice. continueDialog returns null
```

...or whatever the actual flow is. I'd like to try to replicate this so I can dig into it more and see what the cause of this might be.

**Comment by samueleorfei** [comment]
Hi @mdrichardson thanks for the answer.
I tried different versions of Node.js and BotFramework and I also update all the packages of the project but the error still occur and there is no "endDialog(null)".
The current flow is: 

1) Ask User for language -> Choice Prompt
2) Ask user how can be helped -> Choice Prompt
3) Check if the user is in the database. If yes, ask user if he wants to use the saved data. If no, it takes another path.

If the user data is not in the database, ask user the following information:
4) Name -> Text Prompt
5) Email -> Text Prompt
6) Phone Number -> Number Prompt

If the user accept the saved data, skip the previous steps and jump directly to these:
7) Problem Title -> Text Prompt
8) Ask the user if he wants to send audio of the problem -> Choice Prompt
9) If Yes, send audio -> Attachment Prompt
10) If no, send text -> Text Prompt
11) Ask Problem priority -> Choice Prompt

Here, If the user is in the database, whatever is the answer at the step 3, continueDialog() return null and the flow breaks. 
Instead, if the user is not in the database, there is no errors and the bot flow continue fine with the other dialogs:
12) Ask user company -> Text Prompt -> Save all user data to database
13) Ask if user wants to send images of the problem -> Choice Prompt
14) If yes, ask images -> Attachment Prompt
15) If no, ask if user wants to send other useful files -> Choice Prompt
16) If yes, ask file -> Attachment Prompt
17) If no, ask user to send the email with the user data -> Choice Prompt

If yes send email else no.

18) Ask user to maintain the user data or delete it.
19) End dialog with message. (endDialog(message))

**Comment by mdrichardson** [comment]
@samueleorfei So, it breaks at step 3 if the user is in the database, before being able to move onto the next step?

This is really difficult to debug without seeing code. I think, at a minimum, it would be helpful to see the code around `continueDialog()` and the entire dialog around checking if the user is in the database (feel free to remove or obfuscate sensitive code).

I believe I've seen this issue before if you end a prompt or dialog with simply `await <xyz>` and not `return await <xyz>`. That *shouldn't* make a difference, but I have seen this occur with that.

**Comment by samueleorfei** [comment]
@mdrichardson I just discovered the problem. It was just a string mismatch between the actual Dialog name and the called one, so it was calling a non existing dialog only when the user data was present. But I still don't get why it returns null instead of undefined or any other behaviour that allows me to understand what's going on

**Comment by mdrichardson** [comment]
@samueleorfei Glad you figured it out! I'm not sure why it would return null, either. I'd imagine it lies somewhere pretty deep in the code. Do you have a repo you can link me to that can reproduce the issue? If so, I'd be happy to dig into it.
