### ISSUE TITLE
Tests: Retrieve new emulator token or change auth tests

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#146]
This is a low priority issue since the tests are commented out. Since we circulated the certs last week, the emulator auth test that should pass fails due to how we run the test (using a copy-pasted bearer token and not retrieving a new token like in botbuilder-dotnet).

Going ahead we should either retrieve a new token or setup the tests to use environmental variables in [travis](https://docs.travis-ci.com/user/environment-variables/).

**Comment by Stevenic** [comment]
I just configured Travis to use encrypted copies of our keys for LUIS & QnA Maker so agree that we should do something similar for the auth unit tests. I disabled them because they weren't working.

**Comment by Stevenic** [comment]
Old issue
