### ISSUE TITLE
Revise JS Code Coverage Implementation

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-js#1480]
Our existing Coveralls solution has unexpected results for code coverage. It's also not clear if the correct set of files are being measured.

We need to evaluate, and possibly change, our overall Code Coverage reporting mechanism in R8. The solution should work well with both GitHub and the Public Azure Devops build that we're moving to.

https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops

**Comment by Stevenic** [comment]
What's wrong with using coveralls?  I'm not opposed to changing to something else but I need to be able to run coverage locally as well as in the cloud.

**Comment by cleemullins** [comment]
Coveralls is great. We just don't belive the numbers it's reporting. Need to re-eval.

**Comment by stevengum** [comment]
For the original concerns around moving away from coveralls, we would still use nyc as our code coverage reporting tool. Developers would still be able to get code coverage data on their local machines.

As @cleemullins mentioned, the core concern around coveralls lies with reliability and accuracy of the code coverage reported by coveralls.

Anecdotally speaking, the coverage comparison algorithm by coveralls seems to report the wrong diff for PRs.
