### ISSUE TITLE
BotFrameworkAdapter createConversation is missing conversationParameters

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-js#1497]
C# and Python implementations of createConversation include the option of providing conversationParameters the JavaScript appears to be missing that.

This is necessary if this method is to be used to start a thread within a channel within a Team.

The other Teams scenario of starting a one on one chat is covered because the default conversationParameters code is used and that works.

As it is without this fix you can't use the adapter  createConversation for the create thread scenario, however you should be able to use the raw connector.

**Comment by cleemullins** [comment]
@clearab To look at this and figure out why it was punted from R10. Seems like a clear bug that should be fixed.
