### ISSUE TITLE
Add warning if requests take longer then 10 seconds to process

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-js#15]
The bot has roughly 10-12 seconds to respond to a received activity before the channel times out. A channel timing out can result in some cases the message being re-delivered and in the case of cortana the skill being prematurely ended. 

This feature would add a piece of middleware or sample that would log out that the bot is taking too long and the developer should investigate why. It could for instance log a warning for requests longer than 8 seconds and an error for requests longer then 12 seconds.

**Comment by bashdx** [comment]
Hello, if you could point me in the right direction, please, I would give it a shot.

**Comment by Stevenic** [comment]
@bashdx awesome! There's a [Creating Middleware](https://github.com/Microsoft/botbuilder-js/wiki/Creating-Middleware) guide that gives a basic overview of creating middleware and if you need sample inspiration feel free to check out all the middleware I've built in my [botbuilder-toybox-middleware](https://github.com/Stevenic/botbuilder-toybox/tree/master/packages/botbuilder-toybox-middleware) package.

I actually had started working on this when I realized that the lifetime semantics for middleware are more complicated then they probably should be.  I have a proposal to fix this (issue #74) and I believe that's going to make it in so when that does you'll probably have to do a small rework of your middleware but nothing major.  In prep for that change I would just time from the start of the call to `createContext()` to the end of `createContext()`.  

As for where to package up your code we haven't fully figured out the packaging story for middleware in the core SDK yet so I'd just publish it as your own extension on NPM and then we can point to it from our [Extension Directory](https://github.com/Microsoft/botbuilder-js/wiki/Extension-Directory). If you post a link to your code back here I'll be happy to look it over and provide feedback :)

**Comment by bashdx** [comment]
@Stevenic Thank you for the warm welcome. I'll check out your guide and examples and start coding ASAP.

**Comment by bashdx** [comment]
@Stevenic Hello Steven, I got started and have a first result. You can find it [here](https://github.com/bashdx/botbuilder-longrun-warning-middleware). I tried to fiddle a little with `context.delay()`, unfortunately that did not really work and I was only able to have a delay of about 1ms. I will continue tomorrow. Also, I am happy for any advice, hints, you name it! Thank you

**Comment by bashdx** [comment]
@Stevenic Thank you for your thoughts on the topic. I committed the changes to the repository. Could you please check it out? I hope it fits better this time. If things are fine, I will go into making a npm-package from the repository. Looking forward for your comments.

**Comment by Stevenic** [comment]
Looks good to me :)

**Comment by bashdx** [comment]
Hello @Stevenic I am currently trying to create my node package. As suggested by the npmjs packaging guide, I wanted to test it locally first. When trying to install the botbuilder packages the following happened:

![image](https://user-images.githubusercontent.com/28575699/36508483-231b8c72-175d-11e8-88cf-59b77c9f42db.png)

I tried to use the same versions I have in my package directory, but nothing helped. Also this did not happen before.

Thank you for your help - if we can solve this, I can test and create the package.

**Comment by Stevenic** [comment]
Let me submit a fix

**Comment by Stevenic** [comment]
try again

**Comment by bashdx** [comment]
Hello @Stevenic thank you for fixing the issue. Everything worked. You can find the package [here](https://www.npmjs.com/package/botbuilder-timeoutwarning-middleware). My installation attempt from npm into a new test directory was successful :)
Could you please check it out? What I am not sure about are the dependencies in `package.json`. Currently they include the packages mentioned in the "Getting Started" section of the Wiki. If this is not desired, I will remove those dependencies. I will work on the documentation as soon as possible.
Could you please have a look at the result? Thank you, hope to hear from you.

**Comment by Stevenic** [comment]
@bashdx you're not actually importing any modules so you technically have no dependencies right? I would think at most you might have the `botbuilder` dependency but definitely not `botbuilder-services` or `restify`.  Also you might add a pointer to your github repo in your package.json file to make it easier for others to get back to your code from NPM.

**Comment by bashdx** [comment]
@Stevenic actually, I DO have all three modules as dependencies in `package.json`. But I guess I could remove them since they should be brought in by the application that uses the my package, right? If so, I would remove those dependencies and re-publish the package.
I am pretty new to npm so I am still trying to get the hang of it.

**Comment by Stevenic** [comment]
You would need to increment the version number to republish but yes. I'll add a pointer to your package in our extension directory

**Comment by Stevenic** [comment]
Added you to the directory. Thanks again! :)

**Comment by bashdx** [comment]
Cool, @Stevenic ! Thank you for guiding me :)
