### ISSUE TITLE
M2: Node LUIS Client causes Confusion

### ISSUE THREAD

**Issue by sayar** [Microsoft/botbuilder-js#151]
Recommended Priority: P2: Feature-level issue to solve for friction.

The LUIS Client in `botframework-luis` is exposed, and shouldn't be. The Client is just there to enable the LUIS Recognizer but it's confusing to developers if they need to use it or the recognizer. Further, creating a new LUIS client does not take the appId and subscriptionKey as a parameter in the constructor. The developer has to pass it in every time they call getIntentsAndEntities which requires them to have access to the variables throughout their codebase. It would be preferable to simplify the API so that getIntentsAndEntities can be simply take the query text (and options).

Expected Code:
```js
let client = new LuisClient({
	appId: “”
	subscriptionKey: “”,
	serviceEndpoint: “”
});
client.getIntentsAndEntitiesV2(query_text);
```

Actual Code:
```js
let client = new LuisClient(serviceEndpoint);
client.getIntentsAndEntitiesV2(appId, subscriptionKey, query_text);"
```

**Comment by Stevenic** [comment]
We'll likely end up hiding the client all together but good to have this issue to make we finalize what we want to do here.

**Comment by sgellock** [comment]
we've reworked the LUIS client to take into account this feedback and other feedback.  See v4 SDK
