### ISSUE TITLE
[Bug] ConversationIds in Teams channel may be too long to be an Application Insights' session ID

### ISSUE THREAD

**Issue by dvrax** [microsoft/botbuilder-js#1512]
## Versions

What package version of the SDK are you using: 
* botbuilder: 4.7.0
* botbuilder-applicationinsights: 4.7.0
* botbuilder-core: 4.7.0

What nodejs version are you using: v13.2.0

## Describe the bug
The ApplicationInsightsTelemetryClient class sets the application insights' session id to be the conversation id of the chat, however conversation ids can be arbitrarily long (the spec does not specify a max length that I saw), but session ids are limited to 64 characters. This causes application insights to reject tracking events when conversing through certain channels (Teams in particular is where I saw it exposed).

## To Reproduce
Run this echo bot (with logging), connecting to the Teams channel.

```javascript
const {
  ApplicationInsightsTelemetryClient,
  TelemetryInitializerMiddleware
} = require("botbuilder-applicationinsights");
const restify = require("restify");
const {
  ActivityHandler,
  BotFrameworkAdapter,
  TelemetryLoggerMiddleware
} = require("botbuilder");

class EchoBot extends ActivityHandler {
  constructor() {
    super();
    this.onMessage(async (context, next) => {
      await context.sendActivity(`You said '${context.activity.text}'`);

      await next();
    });

    this.onMembersAdded(async (context, next) => {
      const membersAdded = context.activity.membersAdded;
      for (let cnt = 0; cnt < membersAdded.length; ++cnt) {
        if (membersAdded[cnt].id !== context.activity.recipient.id) {
          await context.sendActivity("Hello and welcome!");
        }
      }
      await next();
    });
  }
}

const bot = new EchoBot();

const adapter = new BotFrameworkAdapter({
  appId: "app-id",
  appPassword: "app-password"
});
const telemetryClient = new ApplicationInsightsTelemetryClient("ikey");

// Enable internal debug/warning logs to stdout
telemetryClient.configuration.setInternalLogging(true, true);

adapter.use(
  new TelemetryInitializerMiddleware(
    new TelemetryLoggerMiddleware(telemetryClient, true),
    true
  )
);
adapter.onTurnError = async (context, error) => {
  await context.sendActivity("Something went wrong.");
  telemetryClient.trackException({ exception: error });
};

const server = restify.createServer();
server.use(restify.plugins.bodyParser());

server.post("/api/messages", (req, res) => {
  adapter.processActivity(req, res, async turnContext => {
    await bot.run(turnContext);
  });
});
server.listen(3978, function() {
  console.log(`\n${server.name} listening to ${server.url}.`);
});
```

This will result in these logs being written to the console, and no data being logged in application insights:

```
ApplicationInsights:Sender [
  `{"itemsReceived":7,"itemsAccepted":2,"errors":[{"index":2,"statusCode":400,"message":"100: Field 'ai.session.id' on type 'ContextTagKeys' is too long. Expected: 64 characters, Actual: 131"},{"index":3,"statusCode":400,"message":"100: Field 'ai.session.id' on type 'ContextTagKeys' is too long. Expected: 64 characters, Actual: 131"},{"index":4,"statusCode":400,"message":"100: Field 'ai.session.id' on type 'ContextTagKeys' is too long. Expected: 64 characters, Actual: 131"},{"index":5,"statusCode":400,"message":"100: Field 'ai.session.id' on type 'ContextTagKeys' is too long. Expected: 64 characters, Actual: 131"},{"index":6,"statusCode":400,"message":"100: Field 'ai.session.id' on type 'ContextTagKeys' is too long. Expected: 64 characters, Actual: 131"}]}`
]
```

## Expected behavior
Some details of the conversation are logged to application insights using the specified ikey (e.g. messages send and received by the bot).

## Additional context
This problem is caused by the Conversation Id from Teams being longer than 64 characters. The conversationId is used as the session ID for application insights, which is limited to 64 characters, documented [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/data-model-context#session-id).

[This line](https://github.com/microsoft/botbuilder-js/blob/05e8d9f79e67b06ad921a0bfefc2b1a9b8959cbe/libraries/botbuilder-applicationinsights/src/applicationInsightsTelemetryClient.ts#L138) (corresponding [dotnet line here](https://github.com/microsoft/botbuilder-dotnet/blob/09242abf0da38ca5095f036d81e1a1ed2f8e3a22/libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs#L64), probably has the same issue) is likely the culprit. I plan on working around it by sha256 hashing the conversationId and using the hex digest as the session Id instead, but I'll leave it up to you all the right way to sort this out for the libraries.

**Comment by dmvtech** [comment]
This looks very similar to issue with [issue ](https://github.com/microsoft/botbuilder-dotnet/issues/1197) we had with cosmos previously. Looks like we [handle it](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Azure/CosmosDBKeyEscape.cs) in the SDKs for cosmos now.

> I plan on working around it by sha256 hashing the conversationId and using the hex digest as the session Id instead

Yeah, that's a good [workaround that I've used before](https://github.com/microsoft/botbuilder-dotnet/issues/1197#issuecomment-448810142).

Not going to attempt a repro, agree it looks like a bug.

**Comment by dvrax** [comment]
If anyone is curious about the workaround I've implemented for my use case, here's the simple telemetry processor I wrote to sha256 hash all session ids (even if they are already short enough).


```javascript
const appInsights = require('applicationinsights');
const crypto = require('crypto');

module.exports = function truncateSessionId(envelope, context) {
  const originalSessionId =
    envelope.tags[appInsights.defaultClient.context.keys.sessionId];
  if (originalSessionId) {
    envelope.tags[appInsights.defaultClient.context.keys.sessionId] = crypto
      .Hash('sha256')
      .update(originalSessionId)
      .digest('hex');
  }
  return true;
};
```

Use by adding this line:
```javascript
telemetryClient.defaultClient.addTelemetryProcessor(truncateSessionId)
```

**Comment by cleemullins** [comment]
This approach will probably work fine for some solutions. The problem is that we encode data into the conversation Id for both Teams and Skills. Doing a hash means that data is lost, and the Skill won't work properly. For things like an AppInsight key, that's probably fine. For long-running conversations over Skills where the ConversationId is persisted to the database and needs to be maintained, that solution won't work. 

Our more recent CosmosDB implementations have fixed this.
