### ISSUE TITLE
[PORT] Updating mention stripping scenario for Teams with special character support

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1519]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3107

Fixing bug: #3106

**Comment by Stevenic** [comment]
@stevengum  does this need to be ported to JS?

**Comment by johnataylor** [comment]
The JavaScript code can use this function:
```
function escapeRegExp(string) {
  return string.replace(/[.*+\-?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
}
```

(refer to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Escaping)

**Comment by johnataylor** [comment]
Looking at this more closely it seems odd that the C# code uses regex at all. The JavaScript code looks correct, and doesn't bother with a regex. Test coverage looks good in both repos.

The C# code not only shouldn't use regex (perhaps) but also its not clear how the upper part of the if (when mention text == null) ever happens.

Closing this for JavaScript as there doesn't appear to be any issue here.
