### ISSUE TITLE
M2: Directline Upload API doesn't work as expected

### ISSUE THREAD

**Issue by sayar** [Microsoft/botbuilder-js#152]
When uploading attachments (e.g. photos to detect using CogServices), context.request.attachment[0].contentUrl returns URL(http://YOURBOTURL/v3/attachments/USERID/a/views/original), and it seems like it is getting a binary of attachments but it is not returned correctly. It either doesn't work as expected, or needs a sample to show how it work. 

Expected return is 
context.request.attachment[0].content URL = http://YOUR_BOT_URL/v3/attachments/USER_ID/CONVERSATION_ID(or something)/userphoto1.jpg

Current return is
context.request.attachment[0].content URL = http://YOURBOTURL/v3/attachments/USERID/a/views/original

**Comment by Stevenic** [comment]
Is this not just the cached image minus the extension?  We need to store the image you uploaded somewhere so that you can download it. We're not fully understanding the issue here? Is it just that you don't like the url?

**Comment by Stevenic** [comment]
Closing for now. We can re-open if more info comes in.

**Comment by ayako** [comment]
@Stevenic Let me more info about this issue. Using Direct Line, when bot gets attachment (image in our case) from user, it captures and returns url like  https://directline.botframework.com/attachments/xxxxxxxxxx/xxxxxx/x/content.bin?xxxxxxxxxxxxxxxxx . But this means nothing (just shows black screen in browser) and we cannot use this attachment.

**Comment by Stevenic** [comment]
Sorry... I just closed this because there was no followup.

**Comment by craigjensen** [comment]
The upload api requires you to send the raw image bytes in the post body.  You should also set the ContentType and ContentDisposition headers.

**Comment by sayar** [comment]
@ayako is following up with the customer this week.

**Comment by Stevenic** [comment]
Thanks @sayar

**Comment by mchsudhakar** [comment]
@Stevenic @sayar Hi Guys, is there an update on this? Is this bug still open and being worked on?

**Comment by mchsudhakar** [comment]
Hi @dandriscoll is there a work around for this ?

**Comment by ayako** [comment]
@mchsudhakar @stevenic @sayar thank you & sorry late response, finally customer succeeded to send img using Direct Line as @craigjensen suggested. Thank you very much!

**Comment by sgellock** [comment]
closing.  issue is resolved
