### ISSUE TITLE
[PORT] Update adapters for Skills compatibility

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1523]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3148

microsoft/botbuilder-dotnet#3147  - Added additional ContinueConversationAsync overload for custom adapters for skills compatibility.
~microsoft/botbuilder-dotnet#3146 - Move 'BotIdentityKey' const to BotAdapter and made it public.~ Done via #1763

**Comment by garypretty** [comment]
Dependent on #1623

**Comment by Stevenic** [comment]
These changes need to be applied to all JS adapters for skills to work.

**Comment by benbrown** [comment]
Part 1 is here -> #1763, this includes moving the BotIdentityKey to BotAdapter and changing the BotFrameworkAdapter's implementation of continueConversation to include the overload.

The other change will need to be applied to the adapters hosted in the Botkit repo... which will have to happen _after_ the changes to BotAdapter are published.

**Comment by stevengum** [comment]
We moved the BotIdentityKey to the BotAdapter in #1736, so porting microsoft/botbuilder-dotnet#3146 has been completed.

**Comment by cleemullins** [comment]
Closing per Ben and Steven.

**Comment by antishok** [comment]
Hi, what about porting https://github.com/microsoft/botbuilder-dotnet/issues/3147 ?
It seems adapters are still not working with skills.
Thanks
