### ISSUE TITLE
M2: Node BotBuilder Context Missing Members List, causes confusion

### ISSUE THREAD

**Issue by sayar** [Microsoft/botbuilder-js#153]
Recommended Priority: P2: Feature-level issue to solve for friction

context.request no longer contains a list of all the members (only newly added/removed members). There is no way to find all the members currently in a conversation without keeping track of the state yourself which could be problematic for directline/channel-specific implementations. Bot Framework v3 does not follow this pattern and returns all the members in a conversation.

**Comment by Stevenic** [comment]
Filling this as an enhancement as we need to add support to the `adapter` to retrieve the conversation members list.  @cleemullins and @tomlm the same issue likely exists for C#.

**Comment by Stevenic** [comment]
Should be resolved by PR #201
