### ISSUE TITLE
M2: Node BotBuilder Unclear how to identify bot via ID

### ISSUE THREAD

**Issue by sayar** [Microsoft/botbuilder-js#154]
Recommended Priority: P2: Feature-level issue to solve for friction

In V3, you were able to determine if the member added to a conversation was a bot or a human. There is no documented way to accomplish this in v4 as the `context.request.address.id` no longer exists. By default bot is called "default-bot" but developers shouldn't be hardcoding to that.

**Comment by Stevenic** [comment]
Its true that the `address` object is missing from the request but the data is still there. You just have to compare the added members `id` against `context.request.recipient.id`. Yes we need to document this and provide samples.

**Comment by sgellock** [comment]
In v4 we added 'role' so you can tell if a recipient is a bot or not.

**Comment by Kaiqb** [comment]
This (turnContext.Activity.Recipient.Id) is used in the Welcome sample and also in the supporting docs.
