### ISSUE TITLE
[PORT] Added netcoreapp3.0 to the target framerworks list and conditional co…

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1546]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3215

Added netcoreapp3.0 to the target framerworks list and conditional compilation options per recommendation from the ASP.Net Core team (see [this issue](https://github.com/aspnet/AspNetCore/issues/18098) for additional details)

Resolves #3213

**Comment by Stevenic** [comment]
Platform specific
