### ISSUE TITLE
[PORT] RegExRecognizer refactor and fix for Capture groups 

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1548]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3196

RegExRecognizer didn't correctly pass capture group results to the EntityRecognizerSet

Also had bugs around mapping from Entity to RecognizerResult format, cleaned it up

**Comment by Stevenic** [comment]
Needs porting to JS

**Comment by chon219** [comment]
Resolved in 4.future.
