### ISSUE TITLE
[PORT] fix include activity and enum camelcase

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1552]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3229

fix #3220 
fix #3228 
* rename IncludeActivity => activityProcessed with default value of true, and dialog actions to always set TurnPath.ACTIVITYPROCESSED when passing focus to another dialog
* fixed unit tests around ActivityProcessed behavior
* added appropriate attributes and updated .schema and dialog files for enums

**Comment by luhan2017** [comment]
already resolved
