### ISSUE TITLE
[BotFramework-Expressions] @types/lru-cache should be added in dependencies

### ISSUE THREAD

**Issue by Batta32** [microsoft/botbuilder-js#1553]
## Versions
What package version of the SDK are you using.
* [botframework-expressions@4.7.0-preview](https://www.npmjs.com/package/botframework-expressions/v/4.7.0-preview)
* [botbuilder-lg@4.7.0-preview](https://www.npmjs.com/package/botbuilder-lg/v/4.7.0-preview)

What nodejs version are you using
10.8.0

What browser version are you using
\-

What os are you using
Windows 10

## Describe the bug
Give a clear and concise description of what the bug is.
The `@types/lru-cache` is missing in `botframework-expressions` as `dependency` in the `package.json`.

## To Reproduce
1. Add `botbuilder-lg` dependency version 4.7.0-preview (latest in npmjs) in the `package.json`
2. Install the dependencies with `npm install`
3. Compilate the solution with `npm run build`
4. See the that `@types/lru-cache` dependency is missing in `botframework-expressions`

## Expected behavior
Give a clear and concise description of what you expected to happen.
The compilation of the solution using `botbuilder-lg@4.7.0-preview` should be successful.
This should be fixed if `@types/lru-cache` is added in `dependencies` instead of `devDependencies` from the [package.json](https://github.com/microsoft/botbuilder-js/blob/7ff5fa8e5794a3990dda240a73b2cb0d161c49d1/libraries/botframework-expressions/package.json#L34) of `botframework-expressions` library

## Screenshots
_Error of a missing @types/lru-cache dependency_
![image](https://user-images.githubusercontent.com/11904023/71927154-9f30d880-3173-11ea-80f5-5ca383aeab74.png)

_@types/lru-cache is used as devDependencies in botframework-expressions library_
![image](https://user-images.githubusercontent.com/11904023/71927225-c9829600-3173-11ea-8337-6350a124bb72.png)

## Additional context
\-

[bug]

**Comment by Danieladu** [comment]
can you provide the "build" script in `package.json`? 
It would be better if `tsconfig.json` could be provided. 😊
