### ISSUE TITLE
[PORT] Changed $mappings to $entities

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1555]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3226

* Changed $mappings to $entities and remove logic for defining if not present.
* Change $expectedOnly to work over entities and support both a global and per-property definition.
* Fix bug where local binding of null would result in looking up local variables in global scope.
* Integrated ambiguity processing with other entity processing to make it more robust.
* Replace AdaptiveEvents.Ask with AdaptiveEvents.EndOfActions.
* Fix bug where @ would not work with anything after the primary property because first() was being applied beyond the first entity.

**Comment by luhan2017** [comment]
already resolved
