### ISSUE TITLE
[PORT] Add Obsolete attribute to all Microsoft.Bot.Configuration classes

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1559]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3214

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/3188

(also add more specific error message for null region)

**Comment by Stevenic** [comment]
Need to deprecate the JS versions of these classes.
