### ISSUE TITLE
[PORT] Add Microsoft.Ask 

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1560]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3237

This allows computing expected properties with an expression or using an explicit list of property names.

**Comment by luhan2017** [comment]
We don't have Microsoft.Ask in JS package yet. Assign to @chon219

**Comment by Stevenic** [comment]
Moved to R10
