### ISSUE TITLE
[PORT] Make multiple languages limited to the language of the entry lg file

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1577]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3241

If we have an entry file: `a.xxx.lg`, (xxx is the locale, en-us, en, fr-fr .etc.)all the import file while is imported by this entry file or the children file, would fallback language from xxx.

So, if a user uses `a.en.lg` as entry file, and import `b.en-us.lg`, it would make some exception because LG would find a.lg file from `b.en.lg` and with the fallback file `b.lg`, even if the current locale is "en-us".

**Comment by Danieladu** [comment]
it should porting to AdaptiveDialog
