### ISSUE TITLE
[Documentation] Error in Prompting Users code

### ISSUE THREAD

**Issue by armanrahman22** [Microsoft/botbuilder-js#158]
https://github.com/Microsoft/botbuilder-js/wiki/Prompting-Users
This: 
const adapter = new botbuilder.BotFrameworkAdapter({ ... });

should be: 
const adapter = new BotFrameworkAdapter({ ... }); 

because the import statement is:
const { BotFrameworkAdapter, ConversationState, MemoryStorage } = require('botbuilder');

**Comment by Stevenic** [comment]
Fixed! Thanks
