### ISSUE TITLE
Channel returns 401 on BotFrameworkAdapter.ContinueConversation calls

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-js#1580]
## Version
4.7.0

## Describe the bug
See https://github.com/microsoft/botbuilder-dotnet/issues/3245 for details on the issue.

## To Reproduce
JS uses different caching mechanisms than C#, we need to test and see if we can repro the issue here.

**Comment by stevengum** [comment]
@gabog and I reproduced this issue today. I will be working on a fix for 4.7.1.

**Comment by stevengum** [comment]
While the PR contains the fix and a description, this is a known issue with 401 "Unauthorized" errors and proactive messaging. 

More information can be found under [**Avoiding 401 "Unauthorized" Errors**](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp#avoiding-401-unauthorized-errors) under the [_Send proactive notifications_](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp) to users docs page.
