### ISSUE TITLE
ActivityHandler does not directly support the EndOfConversation method

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-js#1582]
4.7

The other platforms have method to handle EndOfConversation messages (called via onTurn).  In JS you must override the onUnrecognizedActivityType method and check the Activity type.

**Comment by gabog** [comment]
Hi @stevengum, I think this was addressed in R9, can you confirm?

**Comment by gabog** [comment]
Actually, it was added, closing it
