### ISSUE TITLE
TaskModuleResponseBase interface definition does not support additional necessary fields

### ISSUE THREAD

**Issue by benbrown** [microsoft/botbuilder-js#1588]
## Versions
What package version of the SDK are you using.
4.7

## Describe the bug
The definition of TaskModuleResponseBase only includes the type field. However, there are several other fields used when responding to teams. 

This is problematic when using the typedefs and defining the `handleTeamsTaskModuleFetch` method on the ActivityHandler class.

## Expected behavior
The typedef should include the other possible fields, or at least allow wildcard fields.

[bug]

**Comment by gabog** [comment]
Hi @benbrown, is this issue JS only or happens in C# too?

**Comment by benbrown** [comment]
I would assume C# too.

**Comment by benbrown** [comment]
The only field in the C# version is type:

https://github.com/microsoft/botbuilder-dotnet/blob/d8ecbd83addd6ba8d1cdade41e5b8298f5cf3809/libraries/Microsoft.Bot.Schema/Teams/Generated/TaskModuleResponseBase.cs

**Comment by EricDahlvang** [comment]
These classes and interfaces were auto-generated from the teams swagger file.  The api allows for a response of TaskModuleResponse which json is either:

```json
{
task: {
     type: 'message',
     value: 'string only here'
}}
```

or

```json
{
task: {
     type: 'continue',
     value: TaskModuleTaskInfo instance here
}}
```

In dotnet, this is accomplished via inheritance of a shared base class containing only the type field, while the value field is on the inheriting class.  I don't see how this is a problem in dotnet.  (also: we are planing to add some helper classes/factory, to assist in generating these complex response types)

Nonetheless, w could potentially address this javascript issue with a union field on TaskModuleResponse:

change from 
```javascript
export interface TaskModuleResponse {
  task?: TaskModuleResponseBase;
}
```

to:

```javascript
export interface TaskModuleResponse {
  task: TaskModuleContinueResponse | TaskModuleMessageResponse;
}
```


@benbrown would this address what you've raised here?
