### ISSUE TITLE
define state manager behavior for endOfConversation and deleteUserData

### ISSUE THREAD

**Issue by DeniseMak** [microsoft/botbuilder-js#159]
It'd be useful for the SDK to provide an option to automatically clear ConversationState on receiving an endOfConversation activity, and automatically clear UserState when receiving deleteUserData.  

If we don't provide this as a built-in option of the state manager, then we should provide a sample showing how to do it as middleware.

**Comment by sgellock** [comment]
document endOfConversation through a sample.  this is on the v4 Sample list.
@dandriscoll does any channel send 'deleteUserData' events?

**Comment by Stevenic** [comment]
Old issue
