### ISSUE TITLE
[PORT] Optimizations to reduce unit test duration during CI

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1594]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3274

Moved adaptive Microsoft.Bot.Builder.Dialogs.Adaptive.Tests to the beginning of the solution.
Added MaxCpuCount to runsettings.

Updated Debug-Windows and Release-Windows targets to make sure all the projects are included in the build.

**Comment by gabog** [comment]
NA
