### ISSUE TITLE
[PORT] Update stale link

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1597]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3275

Fixes #3271 

The main README has:

[# Click here to find out what's new with Bot Framework](https://github.com/Microsoft/botframework/blob/master/whats-new.md#whats-new) which points to an archived Repo. 

It was updated for Ignite in November. If we're still going to use it, feel free to disregard this PR.

I also considered linking to the Releases page of this repo, but felt it was better to just remove the link.

**Comment by Stevenic** [comment]
Platform specific
