### ISSUE TITLE
[BotBuilder-Core] Handle Uncaught Exceptions

### ISSUE THREAD

**Issue by Batta32** [microsoft/botbuilder-js#1599]
## Versions
What package version of the SDK are you using.
[botbuilder-core@4.7.0](https://www.npmjs.com/package/botbuilder-core/v/4.7.0)

What nodejs version are you using
[nodejs@10.8.0](https://nodejs.org/en/blog/release/v10.8.0/)

What browser version are you using
\-

What os are you using
Windows 7

## Describe the bug
Give a clear and concise description of what the bug is.
Having a **Firewall** configured in a deployed resource (e.g. `Cosmos DB`), the execution flow is stopped due to a **Uncaught Exception** when the bot is trying to reach to the resource. It would be helpful to manage these kind of unhandled exceptions.

![image](https://user-images.githubusercontent.com/11904023/72904003-f6ef4800-3d0c-11ea-901d-3bc97be6d783.png)

## To Reproduce
Using a [Skill](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill) in TypeScript from [botframework-solutions](https://github.com/microsoft/botframework-solutions) repository.

1. Open a terminal in the Skill's folder in order to deploy it executing the following command, providing the `appId`, `appPassword`, `luisAuthoringKey` and `luisAuthoringRegion`

```bash
pwsh.exe -File deployment\scripts\deploy.ps1 -name "<BOT_NAME>" -location "<LOCATION>" -appId "<APP_ID>" -appPassword "<APP_PASSWORD>" -luisAuthoringKey "<LUIS_AUTHORING_KEY>" -luisAuthoringRegion "<LUIS_AUTHORING_REGION>"
```

2. Go to the Skill's resource group in Azure Portal
3. Select the `CosmosDB` resource -> `Firewall and virtual networks`
4. Choose the `Allow access from: Selected networks`, and configure a random IP in the firewall section in order to reproduce the 403 error when trying to access the resource

![image](https://user-images.githubusercontent.com/11904023/72904033-01a9dd00-3d0d-11ea-981a-ff617ac3dcfc.png)

5. Open an instance of Visual Studio Code at the root folder of the Skill 
6. Install the dependencies executing `npm install`
7. Create a `launch.json` for debugging

![image](https://user-images.githubusercontent.com/11904023/72904056-0bcbdb80-3d0d-11ea-9532-5b59d6f44dfb.png)

8. Press F5 to start debugging and wait for the Skill to be running 
9. In the `Debugging` options, select `All Exceptions`

![image](https://user-images.githubusercontent.com/11904023/72904072-12f2e980-3d0d-11ea-874f-c2f2e8c97e76.png)

10. Open the `Bot Framework Emulator`
11. Create a new Bot's connection passing the skill's endpoint (which was retrieved after the initialization), the `appId` and the `appPassword` values
12. Send an utterance to the Skill (e.g.`run sample dialog`)
13. Check that the debugging was stopped due to an Uncaught Exception
14. As the exception is not managed by a try/catch sentence, the workflow is stopped and the conversation is not continued

## Expected behavior
Give a clear and concise description of what you expected to happen.
The `Uncaught Exceptions` should be correctly handled in the [Promises](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/botStatePropertyAccessor.ts#L102).

![image](https://user-images.githubusercontent.com/11904023/72904099-1e461500-3d0d-11ea-82ab-75d50822ec8c.png)

## Screenshots
\-

## Additional context
In addition to this, we implemented the `onTurnError` handler in the Skill to handle all the uncaught exceptions - [botframework-solutions#2900](https://github.com/microsoft/botframework-solutions/pull/2900)

[bug]

**Comment by Stevenic** [comment]
This is by design. We don't explicitly eat errors. You should implement `onTurnError` as you stated to catch exceptions raised while processing an activity and for exceptions that occur outside of a message flow you should add your own `try/catch` around setup calls or use `process.on('uncaughtException')`

**Comment by Batta32** [comment]
Thanks @Stevenic, I'll close this issue as you mentioned it's by design.

We implemented the `onTurnError` handler in the TypeScript Skill of [botframework-solutions#2900](https://github.com/microsoft/botframework-solutions/pull/2900) to handle all the uncaught exceptions.
