### ISSUE TITLE
[PORT] [Slack Adapters] Add Slack Functional Test

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1603]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3108

## Proposed Changes
Add a new Functional test for _SlackTestBot_.

## Details
- Add the new **_SlackClientTest_** to FunctionalTests project to test sending a message to the _SlackTestBot_ deployed in Azure with ARM Templates and check its response.
- Update the `template-with-new-rg.json` and the `template-with-preexisting-rg.json` in the _SlackTestBot_ to take the Slack credentials that will be used to deploy the bot on Azure.
- Add the class **_SlackHistoryRetrieve_** to manage the retrieving of Slack Messages.

### Steps to configure the Nightly Build Pipeline:
1- Define the following environment variables:

**BotGroup**: It's the name for the resource group.
**SlackBotName**: It's the name of the bot
**SlackBotToken**: It's the Bot User OAuth Access Token  from the Slack App ( * )
**SlackClientSigningSecret**: It's the Signing Secret from the Slack App ( * )
**SlackVerificationToken**: It's the Verification Token from the Slack App ( * )
**SlackChannel**: It's the channel ID from the application

( * ) Mark these variables as secret.

2- A NETCore task to **publish** the _SlackTestBot_.

![image](https://user-images.githubusercontent.com/44245136/70443141-64edf180-1a76-11ea-8a7b-509daf3451a2.png)

The arguments are:
```PowerShell
--output $(System.DefaultWorkingDirectory)\tests\Adapters\Microsoft.Bot.Builder.Adapters.Slack.TestBot\PublishedBot --framework netcoreapp2.1
```
3- An Azure CLI task to **create the resources in Azure** and deploy the bot.

![image](https://user-images.githubusercontent.com/44245136/70449312-88b63500-1a80-11ea-89d5-776db49438d9.png)

The inline script is the following:
```PowerShell
call az deployment create --name "$(BotGroup)" --template-file "$(System.DefaultWorkingDirectory)\tests\Adapters\Microsoft.Bot.Builder.Adapters.Slack.TestBot\DeploymentTemplates\template-with-new-rg.json" --location "westus" --parameters appId="$(AppId)" appSecret="$(AppSecret)" botId="$(SlackBotName)" botSku=F0 newAppServicePlanName="$(SlackBotName)" newWebAppName="$(SlackBotName)" groupName="$(BotGroup)" groupLocation="westus" newAppServicePlanLocation="westus" slackVerificationToken="$(SlackVerificationToken)" slackBotToken="$(SlackBotToken)" slackClientSigningSecret="$(SlackClientSigningSecret)"

call az webapp deployment source config-zip --resource-group "$(BotGroup)" --name "$(SlackBotName)" --src "$(System.DefaultWorkingDirectory)\tests\Adapters\Microsoft.Bot.Builder.Adapters.Slack.TestBot\PublishedBot\PublishedBot.zip"
```

4- A PowerShell task to **set the environment variables** needed to run the test

![image](https://user-images.githubusercontent.com/44245136/70443369-c7df8880-1a76-11ea-812b-15d41b3c85f3.png)

The script is:
```PowerShell
echo '##vso[task.setvariable variable=SLACK_CHANNEL]$(SlackChannel)'
echo '##vso[task.setvariable variable=SLACK_BOT_TOKEN]$(SlackBotToken)'
```

Finally, the new test will run with the rest of the functional tests and the bot should be deleted with the other resources deployed in the pipeline.

_**Note**: As a pre-requisite, the SlackTestBot must be previously connected with a Slack App._

**Comment by Stevenic** [comment]
unit tests
