### ISSUE TITLE
[PORT] Make sure ResourceExplorer has no System.IO dependencies

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1605]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3234

ResourceExplorer should have no direct System.IO dependencies, as that should all be in the FolderResourceProvider.

This delta moves LoadProject => FolderResourceProvider.

**Comment by Stevenic** [comment]
Platform Specific
