### ISSUE TITLE
[PORT] add javascript action

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1606]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3277

* replaced jurassic with jint
* updated to match exsting patterns

**Comment by Stevenic** [comment]
Need to add a new JavaScript action. This should be sandboxed and run in EVAL.

**Comment by luhan2017** [comment]
@stevenic, @vishwacsena, do we need to enable this in JS package? It should be just the CodeAction in JS?

**Comment by luhan2017** [comment]
@chon219 , This should be the CodeAction in JS, we should make it in R10.

**Comment by chon219** [comment]
> @chon219 , This should be the CodeAction in JS, we should make it in R10.

We already have a CodeAction in JS, are they the same thing?

**Comment by stevengum** [comment]
@luhan2017 and @chon219 from what we've discussed in the past, [`CodeAction`](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-dialogs-adaptive/src/actions/codeAction.ts) addresses the `"add javascript action"` to the JS SDK. I think this can be closed, right?

**Comment by stevengum** [comment]
@stevenic, do you think this is still required?

**Comment by chon219** [comment]
> @luhan2017 and @chon219 from what we've discussed in the past, [`CodeAction`](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-dialogs-adaptive/src/actions/codeAction.ts) addresses the `"add javascript action"` to the JS SDK. I think this can be closed, right?

Do we still need an action to parse & run a javascript code snippet?

**Comment by chon219** [comment]
**JavaScript Action** should not be a part of Adaptive SDK itself, closing this issue.
