### ISSUE TITLE
createNumberPrompt doesn't handle error and throws exception with non-numerics

### ISSUE THREAD

**Issue by cicorias** [Microsoft/botbuilder-js#161]
Using the sample at https://github.com/Microsoft/botbuilder-js/wiki/Prompting-Users#using-prompts

If a non-numeric value is supplied, the error catching expectation that the result will be `undefined` isn't true. Instead an exception is thrown.

using
```
  "dependencies": {
    "botbuilder": "^4.0.0-m2.2",
    "botbuilder-prompts": "^4.0.0-m2.2",
```

![image](https://user-images.githubusercontent.com/1080406/38258828-7b54ca0e-3731-11e8-8e05-73535c0c76d8.png)

**Comment by Stevenic** [comment]
I just published M3 bits so would be great if you could check to see if your still seeing this.  It passes the unit test on this but I can see if I can reproduce the issue.

**Comment by Stevenic** [comment]
I literally just published M3 so if you could verify it still reproduces it would help. If it does I'll take a look first thing tomorrow.

**Comment by Stevenic** [comment]
I'll close this for now as the unit tests all pass. Please reply if this still re-produces and I will re-open
