### ISSUE TITLE
[PORT] Enable deserialization for OAuthPrompt Dialog With TypeHandling.None

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1617]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3294

This PR is to provide an option to use safe deserialization (TypeHandling.None) of OAuthPrompt dialog instead of requiring to use TypeHandling.All. 

Partially fixes this issue  [#2437](https://github.com/microsoft/botbuilder-dotnet/issues/2437).

Added an extensions method on object which can be used in other places so that other Dialogs can also this for safe deserialization.

       public static T CastTo<T>(this object obj)
        {
            if (obj is T asT)
            {
                return asT;
            }
            else if (obj is JObject asJobject)
            {
                // If types are not used by storage serialization, and Newtonsoft is the serializer
                // the item found can be a JObject.
                return asJobject.ToObject<T>();
            }
            else if (obj is JArray asJarray)
            {
                // If types are not used by storage serialization, and Newtonsoft is the serializer
                // the item found can be a JArray.
                return asJarray.ToObject<T>();
            }
            else if (obj == null)
            {
                return default(T);
            }
            else
            {
                throw new InvalidOperationException("Data is not in the correct format for casting.");
            }

**Comment by Stevenic** [comment]
platform specific
