### ISSUE TITLE
[PORT] [Adaptive] Add simple/flexible multiple language generator for non-adaptive

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1618]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3260

Add simple/flexible multiple language generator for non-adaptive developers.

refer: #3061

**Comment by Stevenic** [comment]
LG related

**Comment by Danieladu** [comment]
relate to adaptiveDialog. We will port them in the next generation

**Comment by Danieladu** [comment]
Close this one, LG multi-lang would be redo in this pr: #2053
