### ISSUE TITLE
[PORT] Add build YAML files for code coverage

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1621]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3126

## Description
This pull request adds YAML files to set up build pipelines for code coverage.

## Specific Changes
We added two YAML files inside the folder `build-CI-yaml` in the root folder.
The added files are:
- `build-code-coverage-w-coverlet.yml`
- `code-coverage-w-coverlet-steps.yml`

## How to use
The next steps will guide you through the configuration of a Build pipeline based on the YAML file.

### Set up build pipeline
1- Create a pipeline using the classic editor, this option allows us to select the YAML file to configure the pipeline.
![image](https://user-images.githubusercontent.com/38112957/70465480-cecec100-1a9f-11ea-8321-49eb42c126f2.png)

2- Configure the repository and branch.
![image](https://user-images.githubusercontent.com/38112957/70626234-ce9b0680-1c02-11ea-8e13-d59ad5b50481.png)

3- In the Configuration as code, select the YAML option.
![image](https://user-images.githubusercontent.com/38112957/70465840-9b406680-1aa0-11ea-9598-b6f47dd9c6cd.png)

4- In section YAML, write the build name and select the build YAML file inside the folder `build-CI-yaml` in the root of the directory.
![image](https://user-images.githubusercontent.com/38112957/70626458-42d5aa00-1c03-11ea-92c0-3d7093580094.png)

5- Hit Save & Queue, select the branch you want to use to run the build and click Save and Run
![image](https://user-images.githubusercontent.com/38112957/70631784-7cf77980-1c0c-11ea-8f0c-f3d51969287e.png)

## Testing
In the image below, you can see the pipelines running using these YAML files to set them up.
![image](https://user-images.githubusercontent.com/38112957/70631850-90a2e000-1c0c-11ea-891a-c0b638d2ffe4.png)

**Comment by Stevenic** [comment]
Platform specific
