### ISSUE TITLE
[PORT] Add YAML files to set up build pipelines for nightly tests 

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1622]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3150

## Description
This pull request adds YAML files to set up build pipelines running nightly tests.

## Specific Changes
We added three YAML files inside the folder `build/yaml`.
The added files are:
- `nightly-simple-build-test`: builds the project and run the tests inside the pipeline.
- `nightly-build-functional-test-unix`: deploys a bot in Azure in a Linux environment and runs the tests for that bot.
- `nightly-build-functional-test-windows`: deploys a bot in Azure in a Windows environment and runs the tests for that bot.

These files are configured to run the pipeline nightly in the master branch if there were changes. This can be edited in the file or using the UI in the pipeline set up.

## How to use
The next steps will guide you through the configuration of a Build pipeline for the nightly functional test. 

### Prerequisites
These requisites are not needed for the `nightly-simple-build-test`.
- Azure DevOps organization.
- Azure subscription. Required to create and delete Azure resources.
- One app registration in Azure. [More info](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app)
- Configure an Azure Connection Service. [Steps here](#add-a-connection-service)
- Luis service subscription

### Set up the build pipeline
1- Create a new build pipeline. Then, select the _**Use classic editor**_ option.
![image](https://user-images.githubusercontent.com/37461749/73196597-a1e97280-410e-11ea-805a-7ab99ffee9e8.png)

2- Configure the repository and branch. Then, in the configuration as code, click on _**Apply**_ for the YAML file option. 
![image](https://user-images.githubusercontent.com/37461749/73197535-37393680-4110-11ea-9dfa-66e3ed45e825.png)

3- In the **YAML** section, write the build name and select the build YAML file inside the folder `build/yaml/` in the root of the directory.
![image](https://user-images.githubusercontent.com/37461749/73198127-4bc9fe80-4111-11ea-9e8c-4e22e1f192ff.png)

4- In the **Variables** section add the following variables.
- For the `nightly-build-functional-test-windows`:
  - BotName
  - BotGroup
  - TestBotAppdId
  - TestBotAppSecret
  - LUISAPPIDSECRET
  - LUISSUBSCRIPTIONKEYSECRET
  - AzureSubscription (Connection name from Connected Service)

- For the `nightly-build-functional-test-unix`:
  - BotName
  - BotGroup
  - TestBotAppdId
  - TestBotAppSecret
  - LUISAPPIDSECRET
  - LUISSUBSCRIPTIONKEYSECRET
  - AzureSubscription (Connection name from Connected Service)
  - AzureDeploymentUser
  - AzureDeploymentPassword

- For the `nightly-simple-build-test` you don't need to add any variable.

### Create an Azure Resource Manager service connection
This step is required to use your Azure Subscription for the Windows and Linux CI builds. If you already have a Connection Service configured, save its Connection name to use it later as _AzureSubscription_.

For more info go to [this link](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml).

1-  Navigate to Project settings -> Service Connections -> New service connection.
![image](https://user-images.githubusercontent.com/37461749/73199575-d7448f00-4113-11ea-8bb1-d85c7b92ba4c.png)

2- Select **Azure Resource Manager** and click Next. Then, select **Service principal (manual)**
![image](https://user-images.githubusercontent.com/37461749/73199960-a1ec7100-4114-11ea-8816-20320c57650b.png)

3- In the **New Azure Service Connection** section, complete the next fields. Then, click on **verify and save**. 
   - Subscription Id (stand for Azure Subscription Id)
   - Subscription Name
   - Services Principal Id
   - Service principal key
   - Tenant ID
   - Services connection name (Name used to refer to this service connection in the pipelines)

![image](https://user-images.githubusercontent.com/37461749/73202899-ce0af080-411a-11ea-91b6-a1849a0c02c3.png)

## Testing
In the following images, you can see the builds running in a pipeline from the YAML file.
![image](https://user-images.githubusercontent.com/38112957/70828308-e375c680-1dc9-11ea-9ecc-2b72dbe1ec4e.png)

**Comment by Stevenic** [comment]
Platform specific
