### ISSUE TITLE
[PORT] .NET Core 3.1 - retarget integrations libs plus adapter compat

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1629]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3302

* Retarget integration libraries to target .NET Core 3.1
* Admends to adapters to ensure async operations used (sync operations blocked by default in .NET Core 3+)

# Changed projects
* Adapters
* integration

**Comment by Stevenic** [comment]
Platform specific
