### ISSUE TITLE
 Property 'activity' does not exist on type 'BotContext'

### ISSUE THREAD

**Issue by andhdo** [Microsoft/botbuilder-js#163]
The examples shows a way to access the activity attribute of the context parameter; 
```
...
// Listen for incoming requests 
server.post('/api/messages', (req, res) => {
  // Route received request to adapter for processing
  adapter.processRequest(req, res, async (context) => {
    if (context.activity.type === 'conversationUpdate' && context.activity.membersAdded[0].name === 'Bot') {
      ...
```
however, when the solution is compiled, it give us the following error error: 
```
error TS2339: Property 'activity' does not exist on type 'BotContext'.
```
it was tested using the current botframework-4 dependencies: 
```
# bot libraries
npm install --save botbuilder@preview
npm install --save botbuilder-ai@preview
npm install --save botbuilder-dialogs@preview
```

**Comment by Stevenic** [comment]
The current published bits are the M2 bits. The checked in code is our M3 code. I haven't published the M3 bits yet because we're finalizing one or two last changes

**Comment by Stevenic** [comment]
The M3 bits are now published. look for an M3.5 release soon though which will likely include a few more breaking changes around the way you work with state.
