### ISSUE TITLE
[PORT] [Teams] adding helper to send messages to channel

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1631]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3292

# Changed projects
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Tests
* Teams

[R8,teams]

**Comment by Stevenic** [comment]
Needs port to JS

**Comment by cleemullins** [comment]
@johnataylor to investigate

**Comment by johnataylor** [comment]
this is a dup of #1680

**Comment by johnataylor** [comment]
PR is in now
