### ISSUE TITLE
[PORT] [Facebook Adapters] Add Facebook functional test

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1632]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3250

NOTE: YAML file to set up a pipeline with this functional test in PR #3262

### Description
This pull request adds a functional test for the Facebook Adapter.

### Changes made
We added the class `FacebookChatTests.cs` with the functional test for Facebook.
Also we edited the templates `template-with-new-rg.json` and `template-with-preexisting-rg.json` from the PrimaryTestBot to include the required variables to deploy it to Azure.

### Testing
![image](https://user-images.githubusercontent.com/38112957/72013638-09618000-323d-11ea-8c58-7b54c03aac6a.png)

# Changed projects
* Adapters

[channel adapters]

**Comment by Stevenic** [comment]
Unit tests
