### ISSUE TITLE
[PORT] Add build YAML for Twilio functional test

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1634]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3287

## Description
Adds a YAML file to set up a pipeline to run the functional test for Twilio.

This pull request depends on the test added in the PR #3286 

## Changes made
We added the file `botbuilder-dotnet-ci-twilio-test.yml` inside the build/yaml folder.

### Before Setup
The following step by step guide uses a **Trial Twilio account**, which should last for approximately 200 text messages or runs of the test. If you want to use this functional test for an unlimited amount of time, you will need to **upgrade** your account to a paid version and add a balance to it.

### Requirements
This test requires a valid phone number to receive text messages from the bot when it answers. 
You can use a personal number, register a second Twilio account or buy a second number in a no trial account.

### Prerequisites
- Valid phone number, required to receive the messages from the bot.
- Azure subscription, required to deploy the bot to Azure.
- App Registration in [Azure Portal](https://portal.azure.com/), we need its **AppId** and **AppSecret**. More info [here](https://docs.microsoft.com/en-us/graph/auth-register-app-v2).
- Azure DevOps organization.
- Configured Service Connection in Azure DevOps (Steps below).
- Set up a Twilio account (Steps below).

### Set up Twilio account

1. Go to [Twilio's page](https://www.twilio.com/try-twilio) to sign up for a free trial account.

   >  The signup process requires a valid phone number to receive text messages, this number will be the one we will be using to receive the messages as the **SenderNumber**. 

   You can later check this number or verify a new one to use in the test in the [Verified Caller IDs](https://www.twilio.com/console/phone-numbers/verified) dashboard. Trial accounts can only send text messages to numbers verified there.

2. Go to your [Console Dashboard](https://www.twilio.com/console), click on **Get Trial Number** to register a new phone number with SMS capabilities, this will be your TwilioNumber, also take note of your account sid (**TwilioAccountSid**) and auth token (**TwilioAuthToken**).
![image](https://user-images.githubusercontent.com/37461749/73271590-a0c44e00-41bf-11ea-8a4a-8b496e6b6dcd.png)

3. Go to your [Twilio's Active Numbers](https://www.twilio.com/console/phone-numbers/incoming) dashboard and click in your number.
![image](https://user-images.githubusercontent.com/37461749/73275587-1a5f3a80-41c6-11ea-8314-fcb608e0f094.png)

   Then, scroll down to the **Messaging** section.

   In the **A message comes in** field, select "Webhook" and fill it with the *Bot Web App URL*. `https://<BOT_NAME>.azurewebsites.net/api/messages`

   >  The URL may change depending on the value for the **BotName** variable you choose in the pipeline.
   
   ![image](https://user-images.githubusercontent.com/37461749/73277742-5b0c8300-41c9-11ea-906d-b120c8c0422c.png)

### Set up build pipeline
1. Create a new build pipeline. Then, select the _**Use classic editor**_ option.
![image](https://user-images.githubusercontent.com/37461749/73196597-a1e97280-410e-11ea-805a-7ab99ffee9e8.png)

2. Configure the repository and branch. Then, in the configuration as code, click on _**Apply**_ for the YAML file option. 
![image](https://user-images.githubusercontent.com/37461749/73197535-37393680-4110-11ea-9dfa-66e3ed45e825.png)

3. In section YAML, write the build name and select the build YAML file inside the folder `build/yaml` in the root of the directory.
![image](https://user-images.githubusercontent.com/37461749/73291334-b6953b80-41de-11ea-86f7-24d6d349bc11.png)

4. In the Variables section add the following variables.
  - **AppId** (From app registration).
  - **AppSecret** (From app registration).
  - **AzureSubscription** (Name of your **Azure Resource Manager service connection**).
  - **SenderNumber** (Number where the bot will be sending the messages, in format `+123456423`).
  - **TwilioAccountSid** (Twilio account Sid, you can see it in your [Twilio's dashboard](https://www.twilio.com/console)).
  - **TwilioAuthToken** (Twilio Auth token, you can see it in your [Twilio's dashboard](https://www.twilio.com/console)).
  - **TwilioNumber** (Twilio number, you can see it in your [Twilio's dashboard](https://www.twilio.com/console), in format `+123456423`).
  - **BotName** (The name that will be used to deploy the bot to Azure).
  - **BotGroup** (The resource grop name used to deploy the bot to Azure).

5. (Optional) Configure the triggers for the pipeline. By default, this pipeline runs every time a pull request is created or a commit is made in the master branch.

### Create an Azure Resource Manager service connection
This step is required to use your Azure Subscription for the Windows and Linux CI builds. If you already have a Connection Service configured, save its Connection name to use it later as _AzureSubscription_.
For more info go to [this link](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml).

1-  Navigate to Project settings -> Service Connections -> New service connection.
![image](https://user-images.githubusercontent.com/37461749/73199575-d7448f00-4113-11ea-8bb1-d85c7b92ba4c.png)

2- Select **Azure Resource Manager** and click Next. Then, select **Service principal (manual)**
![image](https://user-images.githubusercontent.com/37461749/73199960-a1ec7100-4114-11ea-8816-20320c57650b.png)

3- In the **New Azure Service Connection** section, complete the next fields. Then, click on **verify and save**. 
   - Subscription Id (stand for Azure Subscription Id)
   - Subscription Name
   - Services Principal Id
   - Service principal key
   - Tenant ID
   - Services connection name (Name used to refer to this service connection in the pipelines)
![image](https://user-images.githubusercontent.com/37461749/73202899-ce0af080-411a-11ea-91b6-a1849a0c02c3.png)

## Testing
In the image below you can see the run of a pipeline set up using this YAML file.
![image](https://user-images.githubusercontent.com/38112957/72922767-69235500-3d2c-11ea-9c07-26e4e46a44ab.png)

[channel adapters]

**Comment by Stevenic** [comment]
Unit tests
