### ISSUE TITLE
[PORT] Create test for waterfall cancellation telemetry

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1643]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3314

For https://github.com/microsoft/botbuilder-js/issues/1619

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Tests

**Comment by Stevenic** [comment]
@stevengum does this test exist yet in JS? I saw that the bug was from JS

**Comment by stevengum** [comment]
@Stevenic, you merged it earlier today 👍 

Closing as the issue was resolved via #1639
