### ISSUE TITLE
Module '"/botframework-connector/lib"' has no exported member 'ConnectorClientOptions'.

### ISSUE THREAD

**Issue by ryanbuening** [microsoft/botbuilder-js#1653]
## Versions
botframework-connector 4.7.1

## Describe the bug
I am not able to import ConnectorClientOptions from botframework-connector

## To Reproduce
npm i botframework-connector

## Expected behavior
Should be able to import ConnectorClientOptions

## Screenshots
![2020-01-31 13_48_39-● Chat component ts - Chat Web - Visual Studio Code](https://user-images.githubusercontent.com/812974/73565942-a5436d80-4430-11ea-8c5e-409a008d8d57.png)

[bug]

**Comment by ryanbuening** [comment]
Also, I don't see how this example on the Readme is valid:

`var client = new BotConnector.ConnectorClient(credentials, 'https://slack.botframework.com')`

With botframework-connector 4.7.1 it appears that ConnectorClient's signature is `ConnectorClient(credentials: ServiceClientCredentials, options?: ConnectorClientOptions)`

am I missing something?

**Comment by v-kydela** [comment]
Hi @ryanbuening 

`ConnectorClientOptions` is an interface. If you're using JavaScript then I'm afraid you won't be able to import interfaces. This behavior is universal to TypeScript/JavaScript and is therefore unrelated to the Bot Builder SDK. However, you can use a TypeScript interface as a guide to help you build your JavaScript objects.

With regard to the readme file [here](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botframework-connector), it looks like you have discovered a bug. The sample code seems to have been copied from Bot Builder v3. If that gets fixed, would you consider your issue resolved?

**Comment by ryanbuening** [comment]
Makes sense. Yes, this can be marked as resolved. Thanks.

**Comment by CoHealer** [comment]
@v-kydela please close after the commit is merged into master

**Comment by v-kydela** [comment]
@CoHealer - That will happen automatically when the PR is merged
