### ISSUE TITLE
[PORT] Do unexpected assigns before expected assigns.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1659]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3334

Add HasEvents flag to entity event queues.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests

**Comment by Stevenic** [comment]
Needs porting

**Comment by luhan2017** [comment]
already resolved
