### ISSUE TITLE
[PORT] Optimize performance of LG evaluation

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1660]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3327

close: #3297

Today, every time a free LG text like "@{welcome}" is evaluated by creating a new "anonymous template" to wrap this free text, and create a temporary LG file with the new content = original content + new anonymous template, for evaluation.

This is not performance friendly. In this pr, we just parse the additional part, so that there is no need to reparse the original content. 

# Changed projects
* Microsoft.Bot.Builder.LanguageGeneration
* Microsoft.Bot.Expressions.Properties
* Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests

**Comment by Danieladu** [comment]
combine with #1712
