### ISSUE TITLE
Add support for skill OAuthCard to Emulator and WebChat (JS)

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-js#1662]
See [parent Issue](https://github.com/microsoft/botframework-sdk/issues/5654)

**Comment by mrivera-ms** [comment]
@gabog , do you have any updates on this?

**Comment by gabog** [comment]
Checked it OAuthCard works fine for JS, this was probably addressed in some other PR but we forgot to update this issue. Closing it
