### ISSUE TITLE
[PORT] [OAuth] small oauth fix

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1667]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3333

The existing overload of GetOauthSignInLinkAsync function with a userId as argument isn't working. It was hardcoding directline, passing empty conversations etc. This PR is to fix that.

# Changed projects
* Microsoft.Bot.Builder

**Comment by Stevenic** [comment]
Needs port

**Comment by mdrichardson** [comment]
@cleemullins @Stevenic 

I don't *believe* this needs a port. This particular fix addresses [one of the C# overloads](https://github.com/microsoft/botbuilder-dotnet/pull/3333/files#diff-1f0c90c6fa85dfcad121531bcb2092edR815) (there are 3 overloads + the original. Note the `userId` argument):

```csharp
public virtual async Task<string> GetOauthSignInLinkAsync(ITurnContext turnContext, AppCredentials oAuthAppCredentials, string connectionName, string userId, string finalRedirect = null, CancellationToken cancellationToken = default)
```

The node version only has [a single function (no overloads), which doesn't accept `userId` as an argument](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/botFrameworkAdapter.ts#L574):

```js
public async getSignInLink(context: TurnContext, connectionName: string): Promise<string> {
```

**Do we want to close this or do you want me to add the overloads to Node?**

**Comment by mdrichardson** [comment]
@cleemullins Disregard previous message. I see a couple of PRs that add additional overloads. I'll write up a PR that adds an overload that accepts `userId`, unless you have any objections. 

@carlosscastro Thoughts?
