### ISSUE TITLE
botframework-streaming should separate main/browser exports

### ISSUE THREAD

**Issue by compulim** [microsoft/botbuilder-js#1669]
## Versions

`master` as of right now.

## Describe the bug

> I briefed @stevengum and @ckkashyap offline on this one.

In https://github.com/microsoft/botbuilder-js/blob/master/libraries/botframework-streaming/src/index.ts, it is exporting `namedPipe.js`, which depends on Node.js `net` package.

Instead, we should have 2 entrypoints, one for Node.js and one for browser. For the browser one, it should not export `namedPipe.js`.

## To Reproduce

1. Create a Webpack project
1. Include `botframework-streaming`
1. Run Webpack to bundle

## Expected behavior

Webpack should not throw error.

Instead, Webpack is complaining it cannot bundle `net` package. This is because `botframework-streaming/namedPipe.js` depends on `botframework-streaming`.

## Additional context

Also same for Node.js, which should not include dependencies that is targeting only browsers.

[bug]

**Comment by stevengum** [comment]
https://github.com/webpack/webpack/issues/4674

After syncing with @compulim in person, we're going use the package.json's `"main"` and `"browser"` field. We'll use either `es5-index.js` or `browser-index.js` for the `"browser"`/ES5-transpiled code.
