### ISSUE TITLE
botframework-streaming should publish ES5 code to NPM

### ISSUE THREAD

**Issue by compulim** [microsoft/botbuilder-js#1670]
## Versions

`master` as of right now.

## Describe the bug

`botframework-streaming` is not working in IE11.

Probably, it is related to `tsconfig.json` not emitting ES5 code.

https://github.com/microsoft/botbuilder-js/blob/master/libraries/botframework-streaming/tsconfig.json#L3

If non-ES5 is highly desirable for efficiency reason, please publish dual entrypoints to NPM, with `browser` pointing to ES5 code and `main` point to ES6+ code.

## To Reproduce

1. Create a web project (e.g. Webpack)
1. Include `botframework-streaming` in the dependencies and the bundle
1. Open the web project in IE11

## Expected behavior

`botframework-streaming` should work in IE11.

Instead, it throw syntax error when loading in IE11.

## Additional context

[bug]

**Comment by stevengum** [comment]
@compulim can you confirm if the dependency chain below is correct? 

> botframework-streaming -> botframework-directlinejs -> botframework-webchat

**Comment by stevengum** [comment]
https://github.com/microsoft/botbuilder-js/issues/1669#issuecomment-589383079
