### ISSUE TITLE
[PORT] [Expression] Expanding max/min built-in functions can take list params

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1671]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3345

closes: #3343 

Now max/ min functions can also take a list of numeric values as a parameter.
For example:
max(createArray(1, 2, 3))
min(createArray(1, 2, 3))

Also they can take a mixing of numeric lists and numeric values. 
max(createArray(1, 2, 3), 5)
min(createArray(1, 2, 3), 5)

# Changed projects
* Microsoft.Bot.Expressions
* Microsoft.Bot.Expressions.Tests

**Comment by Stevenic** [comment]
Needs port
