### ISSUE TITLE
Common async pitfall throws cryptic error

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/botbuilder-js#168]
When a developer doesn't return a promise or await asynchronous code, the context object gets disposed and this error is thrown: ```TypeError: Cannot perform 'set' on a proxy that has been revoked```.

This is the most common trap that developers fall into, so we need a less cryptic error message (e.g. "The context object has been disposed. Did you forget to return a promise/await asynchronous code?").

**Comment by Stevenic** [comment]
Unfortunately we're using revocable proxies to support this so we're not in control of the error message.  JavaScript generates this.  I'm not sure what we can do other then document what it means if you see this error.  If we switched to using a manually coded dispose() we could end up with gaps where the developer could end up using the context object without any error being raised which would also be bad as their bot might not actually work.

The other option would be to always require returning a `Promise` from their bot logic as I can throw a more descriptive error if you forget to do that.  We already try to code all the samples that way.

**Comment by Stevenic** [comment]
The plan is to push developers towards using `async/await` which should help as we don't have any control over the error returned by the proxy.

**Comment by sgellock** [comment]
fixed.
