### ISSUE TITLE
[PORT] Cleanup and consolidate TypeFactory/loading/configuration/ExpressionEngine/registration etc.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1685]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3350

* Add HostContext for global assets like IConfiguration
* Add ComponentRegistration discovery
* Break interfaces apart for components registrations
* Added Expression.Parse with global function table
* Removed IExpressionEngineFactory
* drop SetStateConfiguration
* Merge TypeFactory and DeclarativeTypeLoader with ResourceExplorer
* Added DialogManager.TurnState to allow dialog manager to set initial TurnState for registering * components like LanguageGenerator and ResourceExplorer
* Dropped adapter .Use methods and moved them to DialogManager * (UseResourceExplorer/UseLanguageGeneration etc)
* Drop Resource Plugins
* Merge RefResolver into ResourceExplorer
* rename TypeRegistration to DeclarativeTypeRegistration
* Add Configuration.UseLuisSettings()

# Changed projects
* Microsoft.Bot.Builder.AI.LUIS
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Debugging
* Microsoft.Bot.Builder.Dialogs.Declarative
* Microsoft.Bot.Builder.LanguageGeneration
* Microsoft.Bot.Builder
* Microsoft.Bot.Expressions.Properties
* Microsoft.Bot.Expressions
* Microsoft.Bot.Builder.AI.QnA.Tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Profiling
* Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.Dialogs.Declarative.Tests
* Microsoft.Bot.Builder.Dialogs.Tests
* Microsoft.Bot.Builder.TestBot.Json
* Microsoft.Bot.Builder.Tests
* Microsoft.Bot.Expressions.Tests

[R8,adaptive]

**Comment by Stevenic** [comment]
Needs port

**Comment by luhan2017** [comment]
already resolved.
