### ISSUE TITLE
Unable to generate List Template in Facebook messenger

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/botbuilder-js#1686]
i'm trying to generate list template through the postman and the content i have took from https://developers.facebook.com/docs/messenger-platform/reference/template/list

i'm getting error like List template on Messenger Platform is deprecated on API 4.0. It will be removed from all versions soon.

![Screenshot (41)](https://user-images.githubusercontent.com/51915291/74082786-89b91200-4a83-11ea-9dad-6bf286991816.png)

**Comment by jwiley84** [comment]
Hi @KoradaRajesh 

This issue is unrelated to the Microsoft Bot Framework, so I'm going to close it. Perhaps asking [here](https://developers.facebook.com/support/) would be a better place to get an answer.
