### ISSUE TITLE
[PORT] [Expression]Add string interpolation

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1687]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/2968

fix: #2785

# Changed projects
* Microsoft.Bot.Builder.LanguageGeneration
* Microsoft.Bot.Expressions
* Microsoft.Bot.Builder.LanguageGeneration.Tests
* Microsoft.Bot.Expressions.Tests

[adaptive]

**Comment by Danieladu** [comment]
combine with #1703
