### ISSUE TITLE
[PORT] Merge temporary assembly Expressions.Properties into Expressions

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1689]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3365

* Switch to string Interpolation instead of LGFile
* Cleaned up semantics around switchcondition (it's not a stringExpression) and case (it's always a constant). 
* Moved Evaluate() from extension method to LGFile

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.LanguageGeneration
* Microsoft.Bot.Expressions.Properties
* Microsoft.Bot.Expressions
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.TestBot.Json
* Microsoft.Bot.Builder.Tests
* Microsoft.Bot.Expressions.Tests

[R8,adaptive]

**Comment by Stevenic** [comment]
Needs port

**Comment by luhan2017** [comment]
already resolved
