### ISSUE TITLE
ProcessRequest should be renamed ProcessActivity

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-js#169]
In the Adapters, the ProcessRequest method should be renamed to ProcessActivity. This was done in C# as part of the M2 naming migration.

**Comment by Stevenic** [comment]
It is called [processActivity()](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/botFrameworkAdapter.ts#L74) ????

**Comment by Stevenic** [comment]
closing as it is.
