### ISSUE TITLE
Adaptive Skill Dialog in the SDK (JS)

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-js#1691]
See [parent](https://github.com/microsoft/botframework-sdk/issues/5745)

**Comment by cleemullins** [comment]
This seems very tightly coupled with #1970. Seems like they might be dupes of each other.

**Comment by Stevenic** [comment]
This is really just a place holder issue at this point. The core adaptive changes have been merged into Master but china is still working on parity issues. Should we close it?

**Comment by Stevenic** [comment]
@cleemullins this is the caller side of skills. the other issue is for the receive side of things.

**Comment by stevengum** [comment]
@stevenic is this closed by 2177?

**Comment by cleemullins** [comment]
I'll chase this down today with @stevenic.

**Comment by Stevenic** [comment]
This work is completed
