### ISSUE TITLE
No proper example available for beginners

### ISSUE THREAD

**Issue by pradeeprajr93** [microsoft/botbuilder-js#1692]
The readme file shows following snippet..

`const client = new DialogTestClient('test', dialog_to_test, dialog_options, OptionalMiddlewares)`

But in that, there is no proper example for "dialog_options".

Kindly help.

**Comment by mdrichardson** [comment]
@pradeeprajr93 The `botbuilder-testing` package isn't very actively worked on. That being said, you can see in the [source code](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-testing/src/dialogTestClient.ts#L37) that `dialog_options`/`initialDialogOptions`:

> initialDialogOptions (Optional) additional argument(s) to pass to the dialog being started.

So, when `DialogTestClient` calls `beginDialog()`, [it passes in those `dialog_options`/`initialDialogOptions`](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-testing/src/dialogTestClient.ts#L92).

**Comment by mdrichardson** [comment]
@pradeeprajr93 I believe my comment addresses your issue fully, so I'm going to close this issue. Feel free to re-open if you disagree.
