### ISSUE TITLE
[PORT] TriggerTree and MostSpecificSelector classes

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-js#1696]
We need to port the `MostSpecificSelector` class from C# which has a dependency on TriggerTree.

Once the selector has been ported we need to update `AdaptiveDialog` to use this selector by default instead of `FirstSelector`.

**Comment by luhan2017** [comment]
@chrimc62 are you going to work on this?

**Comment by chrimc62** [comment]
@luhan2017 I believe your team has picked this up, right?

**Comment by luhan2017** [comment]
Yes, we will look into this in R10.
