### ISSUE TITLE
[PORT] SkillDialog

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1698]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3346

Relates to #3311.

This is a first prototype of SkillDialog for preview. 

This PR includes also a set of test projects (under FunctionalTests/Skills/DialogToDialog31) that use a the SkillDialog to call an echo bot and Dialog bot that takes different events and messages.

The SkillDialog and related classes is included in the **Microsoft.Bot.Builder.Skills.csproj** preview package. 

The prototype is included in the **Microsoft.Bot.Builder.Skills.sln** file. 

# Changed projects
* Microsoft.Bot.Builder.Skills
* Microsoft.Bot.Builder
* integration
* Microsoft.Bot.Builder.Skills.Tests

**Comment by gabog** [comment]
NA
