### ISSUE TITLE
Add goodbye middleware

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-js#17]
Another important piece of middleware is a component that is always listening for the user to say "goodbye" or "I'd like to start over". When it detects either of these intents it should first clear the conversation sand then send a reply to the user or return them to the beginning of the conversation.

This could be done as a sample or middleware but it's another important feature that every production bot needs to help combat users getting into a stuck state.

**Comment by Stevenic** [comment]
I thought about this as middleware and its more useful as a sample I believe.

**Comment by bashdx** [comment]
Hey, @Stevenic, count me in!

**Comment by Stevenic** [comment]
Awesome!

**Comment by bashdx** [comment]
I am sorry - I got your answer among the mails, but didn't see it belonged here. I will come up with something and report back to you.

**Comment by bashdx** [comment]
@Stevenic After checking around I am not quite sure about the requirements:

- Do you want this sample for v4?
- Shall it be a sample or a middleware or both?
- The current documentation on [MSDN](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-quickstart) appears to be for v3, at least I didn't find anything in the node packages for v4 matching the class structure in the samples there
- Shall the entire dialog stack be reset (conversation end) upon hitting any of the keywords or shall only the current dialog be reset?

I guess it will help us to clarify your requirements first. Thank you for your support.
Best regards

**Comment by Stevenic** [comment]
I honestly think it's probably best done as a sample but I think you could do it as middleware if you want. We were actually planning to close this and a couple of other similar issues for now as we have a ton of moving pieces right now.

**Comment by bashdx** [comment]
So could you please tell me how to proceed? I don't know whether it will serve a purpose if you currently have other plans. 
Besides I don't know if I am on the right way - I would need a hint from you here.
Thank you and regards

**Comment by Stevenic** [comment]
I would actually hold off for another week to be honest as the entire middleware architecture is about to change. I just don't want you to have to rework a bunch of stuff.

**Comment by bashdx** [comment]
I appreciate your honesty. Please come back to me when we can tackle this or something else :)

**Comment by Stevenic** [comment]
cool :)
