### ISSUE TITLE
[PORT] Event factory for handoff protocol

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1707]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3347

From https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/handoff-library with minor changes

# Changed projects
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Tests

**Comment by Stevenic** [comment]
Needs porting

**Comment by stevengum** [comment]
This is in progress, following up with artul and carlosscastro offline.
