### ISSUE TITLE
[PORT] add typing activity to activityhandler

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1708]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3384

# Changed projects
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Tests

**Comment by stevengum** [comment]
Fixed via https://github.com/microsoft/botbuilder-js/pull/1706
