### ISSUE TITLE
[PORT] Remove default value for inputHint from activityFactory

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1711]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3382

ref: #3344

Remove default value when just using the text activity.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests

**Comment by Stevenic** [comment]
Needs porting

**Comment by Danieladu** [comment]
fixed by https://github.com/microsoft/botbuilder-js/pull/1883
