### ISSUE TITLE
[PORT] Create WebSocketClient.ConnectAsyncEx method to accept CancellationToken optionally

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1723]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3399

Fixes #3155 
___

## Changes

**Added `ConnectAsyncEx` to take `CancellationToken` optionally.**
___

## Specifics

`WebSocketClient.ConnectAsync` should be cancel-able, as the operation could take a long time.

Here, `ConnectAsync` does not take in a `CancellationToken` 

https://github.com/microsoft/botbuilder-dotnet/blob/86d67b989c331fadc8f54efccf081586fc643c9a/libraries/Microsoft.Bot.Streaming/Transport/WebSocket/WebSocketClient.cs#L90

Added new method that accepts a `CancellationToken` that `ConnectAsync` will call.
____

Note: `WebSocketClient` implements `IStreamingTransportClient`, which requires:
https://github.com/microsoft/botbuilder-dotnet/blob/86d67b989c331fadc8f54efccf081586fc643c9a/libraries/Microsoft.Bot.Streaming/Transport/IStreamingTransportClient.cs#L40

The interface is already public. Let me know if we want to take this PR a step further, and derive from `IStreamingTransportClient` that has a Connect method that takes a cancellation token, and have `WebSocketClient` implement that derived interface. For now the edit is only on the class and not the interface

# Changed projects
* Microsoft.Bot.Connector
* Microsoft.Bot.Streaming
* Microsoft.Bot.Streaming.Tests

**Comment by EricDahlvang** [comment]
n/a
