### ISSUE TITLE
[PORT] DCR 3200 QnAMakerRecognizer improvements.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1724]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3376

DCR #3200 
* Cleaned up CrossTrainedRecgonizerSet to collect recgonizer result by id instead of top intent name.
* added expressions to better configure QnAMakerRecognizer 

# Changed projects
* AdaptiveExpressions
* Microsoft.Bot.Builder.AI.LUIS
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Debugging
* Microsoft.Bot.Builder.Dialogs.Declarative
* Microsoft.Bot.Builder.Dialogs
* AdaptiveExpressions.Tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.TestBot.Json

[DCR,P0,R8,WIP,adaptive]

**Comment by Stevenic** [comment]
Needs porting

**Comment by luhan2017** [comment]
relates to #1695. close this one.
