### ISSUE TITLE
[TASK] botbuilder-dialogs for JS is out of sync with C# dialogs

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-js#1725]
Need to merge core dialog changes from `future` branch to `master` to bring JS version of dialogs to parity with C#.

[bug]

**Comment by cleemullins** [comment]
Note: This is *NOT* a merge of future into master. This is a set of manual cherry-pick events.

**Comment by Stevenic** [comment]
Postponing to R9

**Comment by Stevenic** [comment]
This has been done
