### ISSUE TITLE
[PORT] Update DialogContext.cs

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1728]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3403

- Fix some broken links in the doc XML.
- Opportunistically fix some typos.

This will fix some of the doc build warnings (generated in the bot-docs-pr repo builds).

# Changed projects
* Microsoft.Bot.Builder.Dialogs

[docs]

**Comment by Kaiqb** [comment]
Not needed for JS or Python docs.
