### ISSUE TITLE
[PORT] Add Obsolete attribute to CosmosDbStorage 

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1729]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3396

Fixes: https://github.com/microsoft/botframework-sdk/issues/5634

Deprecate CosmosDbStorage and CosmosDbStorageOptions with recommendation to use CosmosDbPartitionedStorage, and fix compiler warnings in CosmosDbStorageTests

# Changed projects
* Microsoft.Bot.Builder.Azure
* Microsoft.Bot.Builder.Azure.Tests

**Comment by EricDahlvang** [comment]
closing, since this has already been merged: https://github.com/microsoft/botbuilder-js/pull/1715
