### ISSUE TITLE
[Engineering] npm run test fails with fresh git clone

### ISSUE THREAD

**Issue by Zerryth** [microsoft/botbuilder-js#1732]
## Versions
What package version of the SDK are you using: 4.7.1
What nodejs version are you using: v12.13.1
What browser version are you using: Chrome Version 80.0.3987.106 (Official Build) (64-bit)
What os are you using: Windows 10

## Describe the bug
Can't successfully run all the tests for botbuilder-js.

## To Reproduce
1. `git clone https://github.com/microsoft/botbuilder-js.git`
2. `npm install --global lerna nyc mocha typescript@2.7.2` to install pre-reqs
3. `npm i`
4. `npm run test`

Then this spits out instead of running tests:
![image](https://user-images.githubusercontent.com/35248895/74798565-f05bde00-5282-11ea-8c98-ad9e10797d48.png)

Also alternatively tried cloning again, and just following I tried following steps outlined in the ["Building the SDK" article in the bb-js Wiki](https://github.com/microsoft/botbuilder-js/wiki/Building-the-SDK), but this gets you an error even earlier, since it tells you to clone, then run tests, but no installing step before that...

## Expected behavior
For tests to successfully run when running `npm run test` on a newly cloned botbuilder-js repo.

I haven't touched this repo in like 6 months, so maybe there's a step that I'm forgetting and missing...? (Though to be fair, should be documented then if that's the case)

[bug]

**Comment by Zerryth** [comment]
This command works from the root `mocha "libraries\bot*\tests\**\*.test.js"` per @stevengum 
It doesn't look like it's a mocha issue

**Comment by stevengum** [comment]
Possibly related: https://github.com/istanbuljs/nyc/issues/1205

We're currently on `"^11.x.y"` so we're severely out of date with the latest major version of `nyc`

https://github.com/microsoft/botbuilder-js/blob/d449253afef4757de052e8364971ab1f727551ed/libraries/botbuilder/package.json#L38

![image](https://user-images.githubusercontent.com/14935595/75058719-5f5a5200-5490-11ea-883a-a5fa731a171a.png)

**Comment by stevengum** [comment]
Per my request, @zerryth updated the wiki to remove the heinous `npm install --global ...`  step... 

Thanks @Zerryth 👍
