### ISSUE TITLE
BotFrameworkAdapter.continueConversation doesn't accept locale as a parameter

### ISSUE THREAD

**Issue by scheyal** [microsoft/botbuilder-js#1739]
BotFrameworkAdapter.continueConversation doesn't accept locale as a parameter, this can be very useful for us when a user want to invoke a scenario proactively while the first message from the bot is localized, is it possible to add this as optional parameter and add it to the activity?
[stevenic] that’s a good point and feature suggestion.

Please consider for upcoming release.

**Comment by stevengum** [comment]
@scheyal is there a parent issue for this? After checking C#, this change would need to be ported to the other languages as well

**Comment by cleemullins** [comment]
I'm unclear of the status of this. I believe other platforms would need this, although there are [other locale related bugs filed](https://github.com/Microsoft/botbuilder-dotnet/issues?q=is%3Aissue+is%3Aopen+locale).

**Comment by cleemullins** [comment]
Looks related to this [C# Issue](https://github.com/microsoft/botbuilder-dotnet/issues/3645) as well.

**Comment by Stevenic** [comment]
Moving to R10 given it's not even done for C# yet

**Comment by mdrichardson** [comment]
This was fixed in #2105 by adding `locale` to `ConversationReference`. Also done in C#.
