### ISSUE TITLE
Documentation: JavaScript sample code in Prompting Users page needs improvements and should use modern JS language features and be more readable for novice JS developers

### ISSUE THREAD

**Issue by sayar** [Microsoft/botbuilder-js#174]
The  sample code should be readable and obvious to novice JavaScript developers.   For example; you should be using language features like the in-operator   instead of checking for undefined keys. You can see this throughout the sample code base but it starts in the [Prompting Users](https://github.com/Microsoft/botbuilder-js/wiki/Prompting-Users) page. For example you can change `if (state.prompt  === undefined)` to `if (!('prompt' in state))`.

**Comment by Stevenic** [comment]
I updated the prompt samples to use `in`. Do you have other specific suggestions?

**Comment by Stevenic** [comment]
Made the changes suggested
