### ISSUE TITLE
Documentation: JavaScript sample code for "Sending Attachments in a List format" should use be careful to use correct variable names or else will confuse the reader.

### ISSUE THREAD

**Issue by sayar** [Microsoft/botbuilder-js#175]
The sample JavaScript code in the "Cards and Attachment" page uses the variable name `messagewithCarouselofCards` when it should use `messagewithListofCards` else it is confusing for new developers. This is common across the documentation with other mismatched variables names.

**Comment by Stevenic** [comment]
Updated the names
