### ISSUE TITLE
[Parity] ActivityEx is not present in Botbuilder-JS

### ISSUE THREAD

**Issue by DiegoCardozo94** [microsoft/botbuilder-js#1753]
**Is your feature request related to a problem? Please describe.**
We detected that the implementation of [ActivityEx ](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/ActivityEx.cs)which is used in [DefaultActivityHandler ](https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/VA/VA/Bots/DefaultActivityHandler.cs#L78)(more specifically the [AsEventActivity method](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/ActivityEx.cs#L113)) is present in the C# version but we didn't find the equivalent in Botbuilder-JS for TypeScript version. 
 
**Describe the solution you'd like**
Migrate [ActivityEx ](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/ActivityEx.cs)into Botbuilder-JS.

**Additional context**
At this moment, we are migrating the changes in the C# Virtual Assistant to the TypeScript Virtual Assistant to support the GA Skills SDK. We found the following scenarios:
	• To prevent the migration being blocked in [DefaultActivityHandler](https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/VA/VA/Bots/DefaultActivityHandler.cs#L78), we manually implemented the validation from AsEventActivity as a workaround; we found this same method in the Skill's [MainDialog](https://github.com/microsoft/botframework-solutions/blob/10ae4d2f0fa595e9d1b1f5d5ba11f15fd3160e9a/templates/csharp/Skill/Skill/Dialogs/MainDialog.cs#L230).
	• A similar case in the Virtual Assistant's [MainDialog](https://github.com/microsoft/botframework-solutions/blob/10ae4d2f0fa595e9d1b1f5d5ba11f15fd3160e9a/templates/csharp/VA/VA/Dialogs/MainDialog.cs#L311), the method AsMessageActivity is used in C# but is missing in TypeScript.
	• In the Skill's [DefaultAdapter ](https://github.com/microsoft/botframework-solutions/blob/10ae4d2f0fa595e9d1b1f5d5ba11f15fd3160e9a/templates/csharp/Skill/Skill/Adapters/DefaultAdapter.cs#L42)class, the method CreateEndOfConversationActivity is used in C# but is missing in TypeScript.

@darrenj can help providing any further information on this.

**Comment by gabog** [comment]
Hi @DiegoCardozo94, we don't have plans to port ActivitityEx to TS, are there any specific methods you would like to see?

**Comment by Batta32** [comment]
Hi @gabog, we don't need any method urgently as we already incorporated some methods in [bot-solutions](https://github.com/microsoft/botframework-solutions/tree/master/sdk/typescript/libraries/bot-solutions) library.

Feel free to check and use the ported methods for your migration:
- [createReply](https://github.com/microsoft/botframework-solutions/blob/master/sdk/typescript/libraries/bot-solutions/src/extensions/activityEx.ts#L17)
- [createEventActivity](https://github.com/microsoft/botframework-solutions/blob/master/sdk/typescript/libraries/bot-solutions/src/extensions/activityEx.ts#L87)
- [createMessageActivity](https://github.com/microsoft/botframework-solutions/blob/master/sdk/typescript/libraries/bot-solutions/src/extensions/activityEx.ts#L91)
- [createEndOfConversationActivity](https://github.com/microsoft/botframework-solutions/blob/master/sdk/typescript/libraries/bot-solutions/src/extensions/activityEx.ts#L95)
- [applyConversationReference](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/ActivityEx.cs#L485)

**Comment by mrivera-ms** [comment]
@gabog, do we need a rollup issue in botframework-sdk to track these items?

**Comment by cleemullins** [comment]
Discussed with @mrivera-ms and this is currently blocked and won't make R10. Pushing to backlog for evaluation in R11.

**Comment by stevengum** [comment]
We're planning on taking the corresponding PR once it's cleaned up since it's spread to [Python](https://github.com/microsoft/botbuilder-python/pull/1182) as well.
