### ISSUE TITLE
[Parity] ClaimsValidator class is not present in Botbuilder-JS

### ISSUE THREAD

**Issue by DiegoCardozo94** [microsoft/botbuilder-js#1754]
**Is your feature request related to a problem? Please describe.**
The implementation of [ClaimsValidator ](https://github.com/microsoft/botbuilder-dotnet/commit/3583d0158a63af5bb9ec1d755f07cf7b48d62da8#diff-e17ea40ab79d636685adb64c7eb455fa)class has not been migrated to Botbuilder-JS. This class is used in [AllowedCallersClaimsValidator ](https://github.com/microsoft/botframework-solutions/pull/2925/files#diff-e7633e18d71158ba480573fc960ead24R1)file.

**Describe the solution you'd like**
Migrate the [ClaimsValidator ](https://github.com/microsoft/botbuilder-dotnet/commit/3583d0158a63af5bb9ec1d755f07cf7b48d62da8#diff-e17ea40ab79d636685adb64c7eb455fa)class to have the same behavior as the C# version in TypeScript.

**Additional context**
At this moment, we are migrating the changes from the C# Virtual Assistant to the TypeScript Virtual Assistant to support the GA Skills SDK. Fortunately, even though AllowedCallersClaimsValidator inherits from ClaimsValidator, this last one has only one method and is overrode by the first one. Because of this **we are not blocked for now**. 

@darrenj can help providing any further information on this.

**Comment by carlosscastro** [comment]
Javascript and C# are different. Claims validator is jsut a function in javascript. See here:

https://github.com/microsoft/botbuilder-js/blob/8a32d65669e293a6b3206e1d2d89ee296c8bb51d/libraries/botframework-connector/src/auth/jwtTokenValidation.ts#L130

Reactivate if you have any more questions on this, happy to chat.
