### ISSUE TITLE
[Auth] Port IAuthenticator and adapt SDK to support MSI implementation 

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-js#1772]
As per PR https://github.com/microsoft/botbuilder-dotnet/pull/3255

Azure App Service (and several other resource types) has a Managed Service Identity feature which simplifies management of application identity - see Microsoft.Azure.Services.AppAuthentication for more information.

By having AdalAuthenticator derive from an interface, I can then inject my own MsiAuthenticator that uses AzureServiceTokenProvider to get the token to call the channels.

I can inject my MsiAuthenticator via overriding BuildCredentialsAsync on BotFrameworkHttpAdapter and returning a MsiAppCredentials class that, in turn, returns the MsiAuthenticator

**Comment by carlosscastro** [comment]
@rggammon are you interested in porting your IAuthenticator change to js? Would love your contribution on this one. @cleemullins and I were delighted with your initiative of proposing this change on C# 👍 If not interested, I'll be happy to port it, up to you.

**Comment by rggammon** [comment]
@carlosscastro There currently isn't an AdalAuthenticator class. The idea here would be to create one, and have it implement IAuthenticator, correct?

**Comment by carlosscastro** [comment]
Gabo and I had a conversation on this one. Since this IAuthenticator is in the deep auth layer and is not openly documented as an extension point, or particularly valuable as an extension point, we'll leave it as-is. Also this area might undergo refactors soon, in which the extension points will be reconsidered holistically.
