### ISSUE TITLE
[PORT] Move Declarative test classes into Microsoft.Bot.Builder.Dialogs.Adaptive.Testing

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1775]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3425

Fix for DCR #3179 
This creates a new assembly for the declartive test scripts and mock LUIS classes
which lets us remove Mock library dependency from adaptive.
This also keeps Bot.Builder.Testing "pure" in that it doesn't take a dependency on declarative or adaptive libraries.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive.Testing
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.AI.QnA.Tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Profiling
* Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.Dialogs.Tests

[R8,adaptive]

**Comment by chon219** [comment]
Adaptive dialog related tests are already in botbuilder-dialogs-adaptive-tests package.
