### ISSUE TITLE
[PORT] add contentType to HttpAction

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1778]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3426

for DCR #3231 

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.TestBot.Json

[DCR,R8,adaptive]

**Comment by luhan2017** [comment]
already resolved
