### ISSUE TITLE
[Engineering] TokenResolver "should end polling" - All Builds Have the Same Failing Test

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botbuilder-js#1787]
All of the builds have one test that is currently failing with:

![image](https://user-images.githubusercontent.com/40401643/75277061-2e458e80-57bc-11ea-9f87-d6da49d09f8e.png)

I believe this has something to do with the tests being run in Node v12; they pass with Node v11 and lower.

I'm still digging into why this is, but so far, I've found that:

In the test, we pass in a log [here](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/tests/streaming/tokenResolver.test.js#L229):

```js
TokenResolver.checkForOAuthCards(adapter, context, activity, log);
```

Eventually, the log *does* get `'End Polling'` pushed to it [here](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/streaming/tokenResolver.ts#L77):

```js
if (log)
    log.push('End polling');
return;
```

However, `log` is an empty array by the time it gets back to [the assert](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/tests/streaming/tokenResolver.test.js#L233):

```js
assert(log.indexOf('End polling') !== -1, 'did not end polling');
```

This works in the latest v11 of Node, v11.15.0. This breaks in the next release, which is the first of v12, v12.0.0. I wasn't able to find anything that stands out in [the changelog](https://nodejs.org/fr/blog/release/v12.0.0/).

This could probably be fixed if we move everything to async/await, but I'm not sure. There might be an easier way.

**Comment by Stevenic** [comment]
I found the issue. Race condition in the test

**Comment by stevengum** [comment]
Will be fixed in https://github.com/microsoft/botbuilder-js/pull/1783 via https://github.com/microsoft/botbuilder-js/pull/1783/commits/f1b6fc28c73720a7262f1fa55560e0750d835e49
