### ISSUE TITLE
[PORT] use standard OAuthScopes in CreateOAuthApiClientAsync

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1790]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3439

Small change in code, revert behavior for using scope in `CreateOAuthApiClientAsync` per discussions with @lzc850612.

The code this PR is reverting does not exist in the other languages afaik.

# Changed projects
* Microsoft.Bot.Builder

**Comment by stevengum** [comment]
N/A
