### ISSUE TITLE
[PORT] Fix errors when From is null in telemetry

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1791]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3436

Fixes: #3395 

If `TelemetryLoggerMiddleware` is used and then `CreateConversationAsync()` is called, there are cases where `Activity.From` will be null, which causes things like this to throw:

```csharp
{ TelemetryConstants.FromIdProperty, activity.From.Id },
```

**Changes**:

Adds a few null-conditional operators, where appropriate.

**Testing**:

Added one test which calls `CreateConversationAsync()` while ensuring the `Activity.From` is null.

# Changed projects
* Microsoft.Bot.Builder
* integration
* Microsoft.Bot.Builder.Tests

**Comment by Kaiqb** [comment]
@garypretty - is this R8 or R9?

**Comment by garypretty** [comment]
@kaiqb I assigned to myself because I am doing some other telemetry work and made sense for me to pick it up. It wasn't assigned to a release but I should be able to get a PR out for it in the next couple of days to make R8

**Comment by Kaiqb** [comment]
@garypretty - not trying to push this into R8, but was asking for clarification. Thanks
