### ISSUE TITLE
FileStorage race condition prevent eTag from always being honored

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-js#181]
In FileStorage.write() we do concurrency checks outside of a lock which means that it's not guaranteed to be accurate should two separate writers attempt to update the same object at the same time. The result will be "Last Write Wins" even though the caller requested a concurrency check be made. This also appears to be resulting in periodic file corruptions due to the way async File I/O works in Node.

**Comment by sgellock** [comment]
done
