### ISSUE TITLE
[PORT] Add additional null check in Telemetry

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1810]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3452

Fixes: #3442 

Similar to [this PR](https://github.com/microsoft/botbuilder-dotnet/pull/3436), but adds a null check I missed (plus an additional test).

From

```csharp
if (items.ContainsKey(TelemetryBotIdInitializer.BotActivityKey))
```

To

```csharp
if (items != null && items.ContainsKey(TelemetryBotIdInitializer.BotActivityKey))
```

# Changed projects
* integration

**Comment by mdrichardson** [comment]
Port not needed. Already contains appropriate null checks:

* https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-applicationinsights/src/telemetryInitializerMiddleware.ts#L62
* https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-applicationinsights/src/applicationInsightsTelemetryClient.ts#L129
