### ISSUE TITLE
[PORT] Renamed SequenceContext to ActionContext

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1815]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3461

- Renamed class and file.
- Cleaned up various variable names.
- Made the context passed into actions a standard DC.
- Updated actions to work against their parent ActionContext for things like sequence manipulation.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs

[R8,adaptive]

**Comment by chon219** [comment]
Resolved in master.
