### ISSUE TITLE
[PORT] Add new function in expression

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1825]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3470

close #3465
close #3462
add new function `flatten` and `unique`
add object support for `indicesAndValues`

# Changed projects
* AdaptiveExpressions
* AdaptiveExpressions.Tests

[LG]

**Comment by Stevenic** [comment]
Needs porting

**Comment by Danieladu** [comment]
port in #1824 and #1813
