### ISSUE TITLE
[PORT] Switch from union to interface/implements in component schema

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1827]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3468

This fixes #3459 by changing $role: union to $role: interface and $role: union(kind) to $role: implements(kind) to make the meaning clearer.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.TestBot.Json

[adaptive]

**Comment by Stevenic** [comment]
Schema changes
