### ISSUE TITLE
[PORT] Set up key vault storage for functional test build secrets

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1831]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3476

For [BotBuilder-DotNet-Functional-Tests-Windows-yaml](https://fuselabs.visualstudio.com/SDK_v4/_build?definitionId=834&_a=summary) and [BotBuilder-DotNet-Functional-Tests-Linux-yaml](https://fuselabs.visualstudio.com/SDK_v4/_build?definitionId=779&_a=summary)

**Comment by Stevenic** [comment]
functional test
