### ISSUE TITLE
[PORT] Add originatingAudience to SkillHttpClient.PostActivityAsync

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1838]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3477

Fixes #3449
Fixes #3450
Fixes #3451

# Changed projects
* Microsoft.Bot.Builder
* integration
* Microsoft.Bot.Builder.TestProtocol
* Microsoft.Bot.Builder.Tests

**Comment by EricDahlvang** [comment]
closing since these issues already exist in the javascript repo
