### ISSUE TITLE
[PORT] Fixed issue with null attachment arrays in AttachmentInput

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1840]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3486

Fixes #3298

Added logic to `InputAction` that ensures an empty array is provided if `context.activity.attachments` is null.  Also added a unit test to cover `AttachmentInput`. 

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests

[adaptive,bug]

**Comment by Stevenic** [comment]
Needs porting
