### ISSUE TITLE
[PORT] Fix issues with TestBot.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1841]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3485

TestBot was no longer working because Tom remove the connection to user-secrets.  Added that back in and fixed some other minor issues.

# Changed projects
* Microsoft.Bot.Builder.AI.LUIS
* Microsoft.Bot.Builder.TestBot.Json

**Comment by Kaiqb** [comment]
dotnet specific.
