### ISSUE TITLE
[PORT] Port: refence a custom function in LG imports

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1863]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3513

Sync with https://github.com/microsoft/botbuilder-js/pull/1845

closes https://github.com/microsoft/botbuilder-dotnet/issues/3492

# Changed projects
* Microsoft.Bot.Builder.LanguageGeneration
* Microsoft.Bot.Builder.LanguageGeneration.Tests

**Comment by Danieladu** [comment]
has fixed
