### ISSUE TITLE
[PORT] Add 'ephemeral' as the list of options for Delivery Mode

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1866]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3502

We are adding a new option for DeliveryMode on the Activity. This property is a string, and the code comment lists all of the possible values. I have updated the code comment to list the new value of 'ephemeral'.

# Changed projects
* Microsoft.Bot.Schema

**Comment by stevengum** [comment]
Fixed via https://github.com/microsoft/botbuilder-js/pull/1856
