### ISSUE TITLE
[PORT] Add new fields and remove auto-generated text.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1868]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3499

fixes: #3497 

Changes:
- Add ChannelCount and MemberCount to TeamDetails object
- Remove auto-generated documentation
- Move file out of the generated folder to make clear this is no longer auto-generated

# Changed projects
* Microsoft.Bot.Schema

[parity with python]

**Comment by clearab** [comment]
Closing as duplicate.
