### ISSUE TITLE
[PORT] Add support for SSO to parent and child bot projects for manual testing

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1871]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3489

- Add support for SSO to parent and child bot projects for manual testing
- Fixed  a minor bug in oauthprompt

# Changed projects
* Skills

**Comment by johnataylor** [comment]
note parent and child are test projects

**Comment by Stevenic** [comment]
Needs porting

**Comment by cleemullins** [comment]
This is all test bot changes. R10.

**Comment by stevengum** [comment]
Moved to backlog, and unassigned swagatmishra2007 due to other higher priority work. When this issue is picked up for a specific milestone, it should be assigned to someone within the SDK team.

**Comment by joshgummersall** [comment]
Note: look at the latest code on `main` when porting.

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. Closing as Not Needed.
