### ISSUE TITLE
Wiki sample code error - prompt validation 

### ISSUE THREAD

**Issue by cbtham** [Microsoft/botbuilder-js#188]
Error: TypeError: context.sendActivity is not a function

![image](https://user-images.githubusercontent.com/5702935/38851519-623312c8-4259-11e8-8ce6-3efb31e034d9.png)

Steps to reproduce:-
1. Use prompt validation for ageprompt.
2. input any age not in range of 1-100.

The fix:-
Use context. 

await agePrompt.prompt(context, `I'm sorry I didn't understand. Please enter an age between 1 and 100.`);

**Comment by Stevenic** [comment]
Thanks... Fixed
