### ISSUE TITLE
[PORT] API naming for LG

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1880]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3480

link: #3443
API naming for LG
1. Rename 'LGFile' to "Templates"
2. Rename "CreateActivity" in "ActivityFactory" to "FromObject"
3. Rename "SimpleMultiLangGenerator.cs " to "MultiLanguageLG.cs" and move into LG library,
  and remove LG library and ILanguageGenerator dependencies
4. Rename "EvaluateTemplate" to "Evaluate", and the original "Evaluate" is replaced by a new name "EvaluateText"

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.LanguageGeneration
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests
* Microsoft.Bot.Builder.LanguageGeneration.Tests
* Microsoft.Bot.Builder.TestBot.Json
* Microsoft.Bot.Builder.Tests

[LG,P0]

**Comment by vishwacsena** [comment]
Tracked via https://github.com/microsoft/botbuilder-js/issues/1879
