### ISSUE TITLE
About AdaptiveDialog

### ISSUE THREAD

**Issue by simon-tannai** [microsoft/botbuilder-js#1884]
Hello !

I have seen that AdaptiveDialog is in preview into the last .net SDK version (https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/adaptive-dialog)

Is there any implementation of this new Dialog type into the Node.js SDK ? 
If not, is it intended ?

Thanks ! :)

**Comment by chrimc62** [comment]
We are actively working on this and @vishwacsena will supply the timeline.

**Comment by simon-tannai** [comment]
Thanks @chrimc62 ! 
Can you keep me in touch into this feed when you will have the timeline ?

**Comment by vishwacsena** [comment]
@simon-tannai we are actively working on bringing adaptive dialogs to JS/ TS. You can find the latest in this branch - https://github.com/microsoft/botbuilder-js/tree/4.future/libraries/botbuilder-dialogs-adaptive

We expect to be able to get a preview release of adaptive dialogs in JS/ TS in summer 2020 (hopefully mid-may timeframe).

Thanks for your interest and support!
