### ISSUE TITLE
[BotBuikder-AI] QnAMakerEndpoint generation in QnAMakerDialog differ from BotBuilder-DotNet

### ISSUE THREAD

**Issue by VictorGrycuk** [microsoft/botbuilder-js#1885]
## Versions
What package version of the SDK are you using. [4.8.0-preview-109324](https://www.npmjs.com/package/botbuilder-ai/v/4.8.0-preview-109324)
What nodejs version are you using. **v10.8.0**
What browser version are you using
What os are you using. **Windows 10 Pro**

## Describe the bug
The way that `QnAMakerDialog` handles the generation of `QnAMakerEndpoint` is different in [BotBuider-JS](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-ai/src/qnaMakerDialog.ts#L352-L356) than it is done in [BotBuider-DotNet](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs#L136-L141).

In DotNet, the `QnAMakerEndpoint` receives directly the hostname as parameter. However, JavaScript uses string interpolation to generate the host (`https://${this.hostName}.azurewebsites.net/qnamaker`).

We thought that better alternatives would be:
- Do away with the string template
- Modify the template to just `https://${this.hostName}/qnamaker`

Being tied to a string template makes it hard to work with. For example, we have the whole URL in the `cognitivemodel.json`, such as  `https//example-qnahost-5vkhuvk.azurewebsites.net`, but there is no easy way to get simply `example-qnahost-5vkhuvk`. We had to end up using `new URL(value.host).hostname.split('.')[0]` to obtain what the template expects.

## Expected behavior
We expect it to work similarly as the `QnAMakerDialog` in BotBuilder-DotNet.

## Screenshots

*The difference in the implementation between BotBuilder-DotNet and BotBuilder-JS*
![image](https://user-images.githubusercontent.com/39467613/76328061-94a4d380-62c9-11ea-9b2b-609fc0e6c309.png)

*How the endpoint is generated by passing the whole hostname*
![image](https://user-images.githubusercontent.com/39467613/76328096-a0909580-62c9-11ea-88a5-13301d0a8e25.png)

## Additional context
This was originated by porting the [BotFramework-Solution](https://github.com/southworks/botframework-solutions)'s `MainDialog` with the new [integration of QnAMakerDialog](https://github.com/southworks/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs#L79).

Another downside is that it would not be compatible with Azure Goverment domains as it has the `azurewebsites.net` hardcoded with no way to change it to `azurewebsites.us`.

[bug]

**Comment by chrimc62** [comment]
This looks like a difference and we will look into how we fix this in our next release.  It is a potentially breaking change.  Thanks for bringing it to our attention.

**Comment by stevengum** [comment]
This looks like it would be fixed by https://github.com/microsoft/botbuilder-js/pull/1999

**Comment by vipeketi** [comment]
PR merged, issue is fixed now.
