### ISSUE TITLE
[BotBuilder][4.8] Compilation error due to different AppCredential used

### ISSUE THREAD

**Issue by Batta32** [microsoft/botbuilder-js#1901]
## Versions
What package version of the SDK are you using.
[4.8.0](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder/4.8.0) from MyGet
What nodejs version are you using
10.8.0
What browser version are you using
\-
What os are you using
Windows 10

## Describe the bug
Give a clear and concise description of what the bug is.
Using [4.8.0](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder/4.8.0) of botbuilder's packages from MyGet, it throws a **compilation's error**.

This error shows up as `AppCredentials` of the method `exchangeToken` in [BotFrameworkAdapter](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/botFrameworkAdapter.ts#L712) and [ExtendedUserTokenProvider](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/extendedUserTokenProvider.ts#L94) are different.

`BotFrameworkAdapter` uses [AppCredentials](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botframework-connector/src/auth/appCredentials.ts) from `botframework-connector`, howerver `ExtendedUserTokenProvider` uses [AppCredentials](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/appCredentials.ts) from `botbuilder-core`.

![image](https://user-images.githubusercontent.com/11904023/76630650-25c0b800-651f-11ea-9f30-6b4abca66c25.png)

## Expected behavior
Give a clear and concise description of what you expected to happen.
The compilation of the botbuilder's packages should work correctly.

## Screenshots
![image](https://user-images.githubusercontent.com/11904023/76630676-2f4a2000-651f-11ea-8c23-7d1bdc00d267.png)

## Additional context
These changes are in [master](https://github.com/microsoft/botbuilder-js) and in [4.8](https://github.com/microsoft/botbuilder-js/tree/4.8) branch

[bug]

**Comment by stevengum** [comment]
Closing as fix was merged to `4.8` and cherry-picked to `master`.
