### ISSUE TITLE
[PORT] [OAuth]do not set signInLink to empty when OAuthAppCredentials is set

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1909]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3564

When OAuthAppCredentials is passed in as part OAuthPromptSettings, do not set SignInLink to be empty as Emulator/other first party channels will ignore this and get a SignInLink without the additional OAuthAppCredentials setting.

# Changed projects
* Microsoft.Bot.Builder.Dialogs

**Comment by EricDahlvang** [comment]
closing since this has been completed https://github.com/microsoft/botbuilder-js/pull/1907
