### ISSUE TITLE
[PORT] Debug Adapter Protocol Support for variablesReference in OutputEvent

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1913]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3582

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Debugging
* Microsoft.Bot.Builder.Dialogs

[R9]

**Comment by Stevenic** [comment]
This is C# specific...
