### ISSUE TITLE
[DOC] Readme is missing packages

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botbuilder-js#1916]
We're missing 4 packages from the of packages:
- adaptive-expressions
- botbuilder-lg
- botbuilder-testing
- botframework-streaming

**Comment by christopheranderson** [comment]
Also, we should get badges with the version number on them.

**Comment by garypretty** [comment]
Related to R10 Docs pillar tracking item https://github.com/microsoft/botframework-sdk/issues/5898

**Comment by garypretty** [comment]
Handling as part of #2403 and PR #2408. Closing.
