### ISSUE TITLE
ci: publish isn't working for adaptive-expressions without errors

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botbuilder-js#1917]
We had to unblock the last release with a try/catch block.

Basically, adaptive-expressions is failing in PowerShell, but it is successfully publishing to npm. We need to debug why it is throwing errors and also harden the publish script to survive errors.

See this release for details: https://fuselabs.visualstudio.com/SDK_v4/_releaseProgress?releaseId=5123&environmentId=5128&_a=release-environment-logs

**Comment by Danieladu** [comment]
Is this problem solved?

**Comment by christopheranderson** [comment]
I don't believe so. I'm planning to take a crack at this week for R9.

**Comment by BruceHaley** [comment]
The cause of this problem is that packages adaptive-expressions and botbuilder-lg are not being versioned properly. BotBuilder-JS-master-daily/113662 shows those 2 packages versioned as "4.8.0-preview", which is an invalid version. The fix needs to be in the original build, not in the publish.

**Comment by BruceHaley** [comment]
Cause: The build variable "PreviewPackageVersion" in the original build BotBuilder-JS-master-daily/113662 was set to "4.8.0-preview". It should have been set to "4.8.0-preview-$(Build.BuildNumber)". This is a by-hand step. I reran the build entering the correct version numbering. That build is #119227. That can now be published, and should publish without error.

**Comment by BruceHaley** [comment]
I suggest not changing the publish routine. Good that it fails when packages produced upstream are not versioned correctly. Possibly we could improve the upstream build to reduce the likelihood of human error when queuing a build.

**Comment by BruceHaley** [comment]
I fixed this by making npm only log errors. I changed the command:
    npm publish $_.FullName
...to read:
    npm publish $_.FullName --loglevel=error

**Comment by BruceHaley** [comment]
I have "hardened" the publish process against errors by adding the pipeline var ContinueOnError, settable at queue time. If set to 'true', publish errors will be ignored.
