### ISSUE TITLE
[PORT] [Exprssion] Add method for create an array by square bracket expression

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1945]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3613

In addition to createArray prebuilt function, now user can create an array by using [args1, args2, ...].
For example,
["hello", "world"] will return the same result as createArray("hello", "world")

# Changed projects
* AdaptiveExpressions
* AdaptiveExpressions.Tests

**Comment by cosmicshuai** [comment]
https://github.com/microsoft/botbuilder-js/pull/1926
