### ISSUE TITLE
rankerType options left

### ISSUE THREAD

**Issue by AlexGonRod** [microsoft/botbuilder-js#1951]
## Versions
What package version of the SDK are you using. - JS botbuilder-ai 4.8.0
What nodejs version are you using - v10.16.3

## Describe the bug
Currently in QnAMaker class the constructor doesn't initialize the rankerType option.

https://github.com/microsoft/botbuilder-js/blob/9befacb893820b2b7863f03e72617cfb057e618c/libraries/botbuilder-ai/src/qnaMaker.ts#L84
```
 const {
            scoreThreshold = 0.3,
            top = 1,
            strictFilters = [] as QnAMakerMetadata[],
            metadataBoost = [] as QnAMakerMetadata[],
            timeout = 100000
        } = options;

        this._options = {
            scoreThreshold,
            top,
            strictFilters,
            metadataBoost,
            timeout
        } as QnAMakerOptions;
```
The only file this is referenced is in  qnamakerOptions.ts.
```
 /**
     * Id of the current question asked.
     */
    qnaId?: number;

    /**
     * A value indicating whether to call test or prod environment of knowledgebase. 
     */
    isTest?: boolean;

    /**
     * Ranker types.
     */
    rankerType?: string;
```

There is nothing else in the class that would assign rankerType tor QnAMaker options to actual values of argument of options were passed in.

## To Reproduce

Create instance of QnAMaker, passing in an option such as rankerType: "QuestionOnly".

We can use postman to see the spected behaviour: https://docs.microsoft.com/azure/cognitive-services/qnamaker/concepts/best-practices#choosing-ranker-type

## Expected behavior
QnAMaker class initializes values of options if passed in and only returns possible answers found only in questions.

**Comment by congysu** [comment]
@trojenguri can you please take a look at this?  thanks.

**Comment by mrivera-ms** [comment]
There is an active PR in review.
