### ISSUE TITLE
[PORT] [Adaptive] Parity at R8 C# release

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-js#1968]
Goal is to get 4.Future branch at parity with R8 C# release and merge that into master. 

@luhan2017, you are on point to drive this. Please coordinate with @Stevenic where required. Per @Stevenic, he is not aware of any blocking issues from moving forward on this. 

As part of this, we also **MUST** get all the declarative and unit tests to JS.

**Comment by cleemullins** [comment]
This isn't an actionable Item as it's too broad. The 4.Future branch is also already merged.
