### ISSUE TITLE
[SkillDialog] Bring forward skill dialog implementation to JS

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-js#1969]
Tracking ticket to bring forward Skill dialog to JS.

**Comment by EricDahlvang** [comment]
@vishwacsena Is this issue tracking something other than https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/skillDialog.ts ?

**Comment by vishwacsena** [comment]
@EricDahlvang also need to bring forward adaptive pieces. Basically C# parity.

**Comment by clearab** [comment]
Closing as duplicate of: https://github.com/microsoft/botbuilder-js/issues/1691
