### ISSUE TITLE
Update DialogManager to work with Skills (JS)

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-js#1970]
See the [rollup issue](https://github.com/microsoft/botframework-sdk/issues/5792) for details.

**Comment by clearab** [comment]
@gabog @Stevenic Are we doing this in R9 now?

**Comment by mdrichardson** [comment]
Recommend implementing this change, as well: https://github.com/microsoft/botbuilder-js/issues/1970

**Comment by gabog** [comment]
[This PR](https://github.com/microsoft/botbuilder-dotnet/pull/3966) should be also included in the port
