### ISSUE TITLE
[PORT] Get AzureDeploymentPassword from new key vault.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1971]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3662

**Comment by stevengum** [comment]
This needs a milestone. This should be quickly resolved, but it's not clear if the underlying key vault's secrets are already setup for JS.

**Comment by BruceHaley** [comment]
This is already in use by pipeline [Run-JS-Functional-Tests-Linux](https://fuselabs.visualstudio.com/SDK_v4/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=549&view=Tab_Variables) (and by the "Gov" version of the same pipeline which has never been run). See "AzureDeploymentCredsVariableGroup". The key vault containing these creds is AzureDeployKeyVault. The creds in this key vault can be used by any pipeline that deploys a bot to an Azure Linux image. There are no other JS pipelines that do this. I believe that resolves this issue.
