### ISSUE TITLE
Intermittent http 400 errors when using CosmosDB storage

### ISSUE THREAD

**Issue by mikeblancas-ms** [microsoft/botbuilder-js#1972]
## Versions
What package version of the SDK are you using.
- v4.5.2
What nodejs version are you using
- v10.14
What browser version are you using
- Facebook Messenger channel
What os are you using

## Describe the bug
Give a clear and concise description of what the bug is.
- Getting a intermittent http 400 errors on CosmosDB usually on first connect to chat bot. "Sorry, it looks like something went wrong! [object Object]"

## To Reproduce
- It is difficult to reproduce. I get the error after the fact. Usually it is intermittent. Please see screenshot.

## Expected behavior
Give a clear and concise description of what you expected to happen.
- Don't have errors when using the in-memory storage

## Screenshots
- Here is a link to the screenshot
https://microsoftapc-my.sharepoint.com/:i:/g/personal/viblanca_microsoft_com/Efzk1jOl6mpHq0UT8q30RN8B-mckgLtusU_P6e5u3bZaVA?e=udxiew

## Additional context

[bug]

**Comment by jwiley84** [comment]
Can you show  me your `adapter.onTurnError`? Your error handler is trying to send the error object, but it needs to be stringified to be read in the bot.

**Comment by mdrichardson** [comment]
@mikeblancas-ms I second the need to see your onTurnError handler from `index.js`. We need to figure out what the error is before we can dig into the real problem. You error handler likely has something like:

```js
await context.sendActivity(`Sorry. It looks like something went wrong. ${ error }`);
```

The problem here is that `error` is an `Error` `Object` and not a `string`, so you'd need to change it to:

```js
await context.sendActivity(`Sorry. It looks like something went wrong. ${ JSON.stringify(error) }`);
```

What is your appId? We might be able to troubleshoot some errors on the backend as well.

**Comment by mdrichardson** [comment]
@mikeblancas-ms Any updates on this?

**Comment by mikeblancas-ms** [comment]
Hi Michael,

Its hard to reproduce the error when using cosmosdb storage. It happens intermittently. Do you have recommendations to make the error more reproducible?

Started to test using blob for storage.

Regards,
Mike

**Comment by mdrichardson** [comment]
@mikeblancas-ms Unfortunately, without knowing what the error is, I'm not sure how to reproduce it.

What makes you think it's a Cosmos issue? Where are you seeing the 400 errors?

**Comment by mikeblancas-ms** [comment]
Hi Michael,

Getting the http 400 errors on CosmosDB overview blade on azure portal. This is the only code that switches the storage between cosmosdb and inmemory in the bot:

var botStorage;

if(process.env.Environment === 'development') {
    // Development Environment
    // In-memory storage
    botStorage = new MemoryStorage();
} else {
    // Production Environment
    // Cosmos DB table storage
    botStorage = new CosmosDbStorage({
        serviceEndpoint: process.env.DB_SERVICE_ENDPOINT,
        authKey: process.env.AUTH_KEY,
        databaseId: process.env.DATABASE,
        collectionId: process.env.COLLECTION
    });
}

Regards,
Mike

**Comment by mdrichardson** [comment]
@mikeblancas-ms Can you copy/paste the errors? Using `await context.sendActivity(`Sorry. It looks like something went wrong. ${ JSON.stringify(error) }`);` should help a lot, too, because that should give us a stack trace.

**Comment by tonyanziano** [comment]
Hey @mikeblancas-ms , can you please respond to @mdrichardson by Wednesday or else will close the issue due to inactivity.

**Comment by mikeblancas-ms** [comment]
Hi Michael,

Have changed the storage to blob. Thanks for the support.

Regards,
Mike

**Comment by mikeblancas-ms** [comment]
Hi Tony,

Please close the issue. Thanks.

Regards,
Mike
