### ISSUE TITLE
[PORT] Fix local culture info changes the result of parsing number and datetime

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1979]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3631

fixes #3598 
use CultureInfo.InvariantCuture to make sure the cultureInfo of user's local machine won't affect the outcome of expresssion functions.
For example, in de-DE 
1.0 will be parsed to 10. 
03/12/2012 will be parsed to03,12,2012

# Changed projects
* AdaptiveExpressions
* AdaptiveExpressions.Tests

**Comment by cosmicshuai** [comment]
In JS, we don't have cultureInfo. The result from AdaptiveExpressions are from toString method instead of toLocaleString. 
So we can just close this.
We have a new solution to include locale in AdaptiveExpressions.
