### ISSUE TITLE
Skills + OAuth: Differentiate between regular and skill mode when receiving tokens (JS)

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-js#1991]
When doing Oauth, and a Skill gets an activity, the skill thinks it is in regular mode and not skill mode, so it uses the wrong connector client.

the fix is to ahve the Token Service add an additional claim and have the SDK act accordingly and know in what mode it is based on the claim.

**Comment by cleemullins** [comment]
Per @carlosscastro ETA is Monday 4/27 or 4/28, as the C# will land first.

**Comment by carlosscastro** [comment]
@stevengum  and I reviewed C# together and he kindly agreed to do the js side. Thanks :)
