### ISSUE TITLE
Add support to SkillDialog so SSO works with expectReply (JS)

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-js#1993]
See [parent](https://github.com/microsoft/botframework-sdk/issues/5780)

**Comment by stevengum** [comment]
ETA in C# is end of week: https://github.com/microsoft/botbuilder-dotnet/issues/3679

**Comment by cleemullins** [comment]
Blocked on C# Implementation

**Comment by stevengum** [comment]
Unblocked with merging of https://github.com/microsoft/botbuilder-dotnet/pull/3818

Additional changes are incoming for the SkillDialog per @gabog 
Additional changes for OAuthPrompt via https://github.com/microsoft/botbuilder-dotnet/pull/3822
