### ISSUE TITLE
[PORT] Debugger: preserve optional designer identifiers with source map range

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2003]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3637

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive.Testing
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Debugging
* Microsoft.Bot.Builder.Dialogs.Declarative
* Microsoft.Bot.Builder.Dialogs

[R9,adaptive]

**Comment by chon219** [comment]
We don't have debugger in JS sdk, closing this.
