### ISSUE TITLE
[PORT] [QnA Maker] header change for adding "Ocp-Apim-Subscription-Key"

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2008]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3690

For supporting QnAMaker V2 integration

# Changed projects
* Microsoft.Bot.Builder.AI.QnA

**Comment by stevengum** [comment]
Closed via #2001
