### ISSUE TITLE
Add ConnectorClientOptions to BotFrameworkAdapterSettings 

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-js#2013]
**Describe the solution you'd like**
The ability to set `ServiceClientOptions` when ConnectorClients are created

**Describe alternatives you've considered**
Hacking the `createConnectorClientInternal` method prototype on `BotFrameworkAdapter`, and accessing the ConnectorClient's properties directly:
```js
BotFrameworkAdapter.prototype.createConnectorClientInternal = function (serviceUrl, credentials) {
    // Set noRetryPolicy: true so ServiceClient code does not add one.
    // This code adds the default retry policies, with a modified exponentialRetryPolicy
    const client = new ConnectorClient(credentials, { baseUri: serviceUrl, noRetryPolicy: true });
    
    //retryCount, retryInterval, minRetryInterval, maxRetryInterval, requestTimeout
    client._requestPolicyFactories.push(retryWithTimeoutPolicy(3, 1000 * 2, 1000 * 1, 1000 * 4, 1000 * 5));
    client._requestPolicyFactories.push(systemErrorRetryPolicy());
    client._requestPolicyFactories.push(throttlingRetryPolicy());

    return client;
};
```

[enhancement]

**Comment by stevengum** [comment]
This would also get us proxy support and httpClient injection, so I'm all for this. 

I believe passing it in via BotFrameworkAdapterSettings should suffice, what do you think @EricDahlvang?

```ts
private createConnectorClientInternal(serviceUrl: string, credentials: AppCredentials): ConnectorClient {
    // Helper method for deep clone and setting of serviceUrl and combining/setting USER_AGENT
    // Clones/creates ClientOptions from BotFrameworkAdapter.settings.clientOptions,
    // a new property with a type of ServiceClientOptions
    const clientOptions= this.cloneOrCreateClientOptions(serviceUrl);

    if (BotFrameworkAdapter.isStreamingServiceUrl(serviceUrl)) {
        // Check if we have a streaming server. Otherwise, requesting a connector client
        // for a non-existent streaming connection results in an error
        if (!this.streamingServer) {
            throw new Error(`Cannot create streaming connector client for serviceUrl ${ serviceUrl } without a streaming connection. Call 'useWebSocket' or 'useNamedPipe' to start a streaming connection.`);
        }

        clientOptions.httpClient = clientOptions.httpClient || new StreamingHttpClient(this.streamingServer);

        return new ConnectorClient(credentials, clientOptions);
    }

    return new ConnectorClient(credentials, clientOptions);
}
```

**Comment by stevengum** [comment]
Using diffchecker, I compared the released [1.2.6](https://github.com/Azure/ms-rest-js/blob/1d4d6a6bea54fc038acacf66e89d4514e78c135a//lib/serviceClient.ts) ServiceClientOptions with what's in [`master`](https://github.com/Azure/ms-rest-js/blob/master/lib/serviceClient.ts) (2.x) of @azure/ms-rest-js. The latest from [`1.x`](https://github.com/Azure/ms-rest-js/blob/1.x/lib/serviceClient.ts) is the same as `master` for this interface.

![image](https://user-images.githubusercontent.com/14935595/79273190-7184bb00-7e57-11ea-872b-8df63ff6d196.png)

![image](https://user-images.githubusercontent.com/14935595/79273231-83fef480-7e57-11ea-918b-7ea8d5328f98.png)

While there are only additions and union types, we should still guard ourselves against relying on this type.

**Comment by EricDahlvang** [comment]
I don't think we can go to 2.0, due to the axios-based to node-fetch change.  This would be breaking, since developers are potentially customizing axios in their bot code right now.

**Comment by stevengum** [comment]
I'm not advocating for going to 2.0 and I'm aware of that change. The screenshots are a snippet indicating what the ServiceClientOptions delta is.
