### ISSUE TITLE
Upgrade ms-rest-js to 1.8.15

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-js#2018]
**Is your feature request related to a problem? Please describe.**
Current version we are using in the sdk: 1.2.6

**Describe the solution you'd like**
There have been bug fixes and enhancements since 1.2.6 (some of these will enable closing other issues): 
https://github.com/Azure/ms-rest-js/blob/master/Changelog.md

[enhancement]

**Comment by stevengum** [comment]
This isn't an endorsement (yet), but we would go to 1.8.14 to pick up this fix: https://github.com/Azure/ms-rest-js/pull/375
