### ISSUE TITLE
[PORT] Updates DialogManager to work with skills

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2019]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3709

Fixes #3657 

This PR includes the following changes: 

- Updated DialogManager to handle skill requests (in addition to parent bot requests). This includes:
  - Handling regular activities sent from the parent.
  - Handling EoC sent from the parent.
  - Handling a RePrompt event sent from the parent. 
- Added unit tests.
- Added end to end Parent->Skill sample with DialogManager for testing (under FunctionalTests\Skills\Adaptive\).
- Updated code in DialogManager and DialogManagerTests to follow SDK coding style conventions.  

I also refactored DialogManager OnTurnAsync in a couple of private methods to split the Skill/Parent processing logic and reduce duplication. 

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Tests

[R9,Skills]

**Comment by stevengum** [comment]
@clearab, @gabog is this still for R9 in JS?

**Comment by gabog** [comment]
I don't think so, this is for adaptive JS and I think that so far the plan is to have JS on parity with R8. Relabeling it to R10

**Comment by clearab** [comment]
This is actually a duplicate of: https://github.com/microsoft/botbuilder-js/issues/1970
