### ISSUE TITLE
[PORT] Update Microsoft.ContinueLoop.schema

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2027]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3740

Typo :sadtrombone:

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive

[R9,adaptive,schema]

**Comment by luhan2017** [comment]
There is no schema definition in the JS side, won't fix
