### ISSUE TITLE
[PORT] Ensured all Activities stored in transcript have Ids

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2036]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3701

Fixes #3665 
___

As, done in [JS's `TranscriptMiddlewareLogger`](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/transcriptLogger.ts#L63) already, ensure that all cloned activities in logger have Ids, so that when  logged into `MemoryTranscriptStore`, each `Item` also has an Id.

If an activity doesn't have an id, `MemoryTranscriptStore` will generate an Id for that activity/`Item` for the transcript storage, prefixing it with "`g_`" for "generated", as done in JS.

### Context
* Not all Activities created have Ids assigned to them ([Activity spec](https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#id) in botframework-sdk)
* `ContinuationToken` within the MemoryTranscriptStore.GetTranscriptActivitiesAsync relies on last `Activity.Id` of loaded `PagedResult`
* Because of the above 2 bullets, if an Activity without an Id is the last item in the `PagedResult`, we may end up infinitely loading the same `PagedResult` over and over again.

### Testing
In order to test that activities with null ids are assigned ids properly in transcript storage, I had to create a custom `TestAdapter`, since the one "off the shelf" automatically fills in an activity id, never allowing for null ids to pass through to the `TranscriptMiddlewareLogger` layer.
* Would have created an own separate class, however needed to derive from it, since `TestFlow` is tightly coupled to `TestAdapter` (it requires an adapter of specifically type `TestAdapter` instead of an interface)

# Changed projects
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Tests

**Comment by Zerryth** [comment]
already addressed in [`TranscriptLogger`](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/transcriptLogger.ts#L63)
