### ISSUE TITLE
[PORT] TestGetChannelsAsync was testing the same thing as TestGetTeamDetails…

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2043]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3707

…Async

# Changed projects
* Microsoft.Bot.Builder.Tests

**Comment by stevengum** [comment]
N/A, the JS tests are correctly returning the list channel IDs and names wrapped in an object. https://github.com/microsoft/botbuilder-js/blob/a57fecfe3c84cceb625300b945df026ba26921cb/libraries/botbuilder/tests/teamsInfo.test.js#L124-L126
