### ISSUE TITLE
[PORT] [Expression] Enable setProperty function creating object handling null correctly

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2059]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3771

closes: #3768 
In this PR,
setProperty({}, 'name', user.name).name will return null when user.name is null. It won't throws exception.
Also, create object with {} syntax,
{name: user.name}.name will have the same behavior as setProperty function.

# Changed projects
* AdaptiveExpressions
* AdaptiveExpressions.Tests

**Comment by Danieladu** [comment]
language specific. Close it.
