### ISSUE TITLE
Add TypeScript Consumer tests to CI

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#2069]
**Describe the solution you'd like**
Integrate the TypeScript consumer tests added by christopheranderson into our CI builds.

https://github.com/microsoft/botbuilder-js/pull/1904

[enhancement]

**Comment by cleemullins** [comment]
@johnataylor Myself, Monica, and Tracy remembered how much you loved working in Typescript and thought this would be a fun change for you. :)
