### ISSUE TITLE
[PORT] Move QnAMaker Dialog/Recognizer out of Adaptive and into QnA assembly

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2080]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3775

#3719 

* Merge QnAMakerDialog2 => QnAMakerDialog 
* Move QnAMakerDialog and QnAMakerRecognizer into QnA assembly
* Move schema definitions int QnA assembly
* Move ComponentRegistration into QnA Assembly
* remove dependencies between Adaptive and QnA
* NOTE: Needed to move ITemplate<> into a shared location as that was only dependency on Adaptive, so moved it into BotBuilder which is where IRecognizer lives.

# Changed projects
* AdaptiveExpressions
* Microsoft.Bot.Builder.AI.QnA
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.AI.QnA.Tests
* Microsoft.Bot.Builder.Dialogs.Declarative.Tests

**Comment by chon219** [comment]
I'll start working on this after PR #2347 being merged as there are some pending changes regarding `QnAMakerRecognizer`.

**Comment by chon219** [comment]
As mentioned in PR #2235 , this change requires introducing dependency to _adaptive-expressions_ to _botbuilder-ai_, @stevengum shall we need to move this to R11 as well?
