### ISSUE TITLE
Facebook API error. Cannot call API for app on behalf of user

### ISSUE THREAD

**Issue by bhushanvadgave** [microsoft/botbuilder-js#2090]
## Versions
NodeJS v10.16.3 (Docker Image)
BotBuilder NodeJS SDK v4.6.2

## Describe the bug
Our production bot service, for `facebook` channel users, while sending a reply message, is receiving errors intermittently.
```
{ Error: Facebook API error
    at new RestError (/usr/src/app/node_modules/@azure/ms-rest-js/dist/msRest.node.js:1397:28)
    at /usr/src/app/node_modules/@azure/ms-rest-js/dist/msRest.node.js:1849:37
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ServiceError',
  statusCode: 400,
  request:
   WebResource {
     streamResponseBody: false,
     url:
      'https://facebook.botframework.com/v3/conversations/2404829052872617-145456495523754/activities/YuCd3TYT9l',
     method: 'POST',
     headers: HttpHeaders { _headersMap: [Object] },
     body:
      '{"type":"message","serviceUrl":"https://facebook.botframework.com/","channelId":"facebook","from":{"id":"145456495523754","name":"akzo-prod-bot-eukdlx"},"conversation":{"isGroup":false,"id":"2404829052872617-145456495523754"},"recipient":{"id":"2404829052872617","name":"FACEBOOK_USER"},"text":"Xin thứ lỗi. Tôi không hiểu. Tôi vẫn đang học hỏi. Tôi sẽ đưa ra một yêu cầu dịch vụ khách hàng thay mặt bạn?","inputHint":"acceptingInput","suggestedActions":{"actions":[{"type":"imBack","title":"Có","value":"customerServiceYesNoOptions:Có"},{"type":"imBack","title":"Không","value":"customerServiceYesNoOptions:Không"}]},"replyToId":"YuCd3TYT9l"}',
     query: undefined,
     formData: undefined,
     withCredentials: false,
     abortSignal: undefined,
     timeout: 0,
     onUploadProgress: undefined,
     onDownloadProgress: undefined,
     operationSpec:
      { httpMethod: 'POST',
        path: 'v3/conversations/{conversationId}/activities/{activityId}',
        urlParameters: [Array],
        requestBody: [Object],
        responses: [Object],
        serializer: [Serializer] } },
  response:
   { body:
      '{\r\n  "error": {\r\n    "code": "ServiceError",\r\n    "message": "Facebook API error",\r\n    "innerHttpError": {\r\n      "statusCode": 400,\r\n      "body": {\r\n        "message": "Cannot call API for app 2465154263505931 on behalf of user 100014785928023",\r\n        "type": "OAuthException",\r\n        "code": 200,\r\n        "error_subcode": 0,\r\n        "fbtrace_id": "AYTB452R0pTzOD9aK6m-k7I"\r\n      }\r\n    }\r\n  }\r\n}',
     headers: HttpHeaders { _headersMap: [Object] },
     status: 400 },
  body:
   { error:
      { code: 'ServiceError',
        message: 'Facebook API error',
        innerHttpError: [Object] } } }
```

The piece of code that receives this error is below
```
        try{
            return await stepContext.prompt(promptName, promptOptions);
        }catch(error){
            LOGGER.error(error);
        }
``` 

All configurations of Facebook channel in Azure Portal and Facebook app in Facebook Developer portal looks correct. We have also tried removing Facebook channel configurations and recreating them.

Please note the errors are intermittent but frequent. Need your help.

**Comment by jwiley84** [comment]
Hi @bhushanvadgave This is almost certainly a Facebook issue. Is the issue occuring for the same 'user' each time? Does the user Id correlate to the bot, or is it a human user? It boils down to user's access token (to facebook) is no longer valid.

**Comment by bhushanvadgave** [comment]
@jwiley84 
The issue is occurring for all Bot users of facebook channel. I think this user ID is correlated with the bot. Our bot service does not use or refer to this user ID.

We tried connecting Facebook App+Page to different bot registration (that points to our staging bot service). And this setup is working properly without any errors. Our production bot service code is the same as that of staging. We suspect there is something wrong with the bot registration.

**Comment by jwiley84** [comment]
Can you check (on the facebook side) that your facebook app wasn't placed into Sandbox or Dev mode?

**Comment by bhushanvadgave** [comment]
The app is in development mode (Not sure how to check if it is in Sandbox mode). But this should not cause any problem right?

**Comment by jwiley84** [comment]
'Sandbox mode' is the old name for if the app was 'In Development'. It's still referred to as such in some documentation.  

If the app is set to 'In Development', the only people who can 'use' the bot are people you've set to the role of 'Tester' in the facebook developer portal, or the app Admin.

**Comment by jwiley84** [comment]
Closing issue.  If you have further issues concerning this, please reopen.
