### ISSUE TITLE
Missing link in Wiki

### ISSUE THREAD

**Issue by victor-kironde** [microsoft/botbuilder-js#2091]
The **Other Languages** section on the [Wiki](https://github.com/microsoft/botbuilder-js/wiki) Sidebar includes a self link to this repository instead of the [botbuilder-dotnet](https://github.com/Microsoft/botbuilder-dotnet) repository.

**Comment by Zerryth** [comment]
Thanks for reporting @victor-kironde 

Fixed! 😄 

![image](https://user-images.githubusercontent.com/35248895/80129286-b1305e80-854b-11ea-9905-2f5466b2092c.png)
