### ISSUE TITLE
[PORT] make converters internal

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2097]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3800

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Declarative

[Adaptive,R9]

**Comment by chon219** [comment]
This issue doesn't exist in js sdk, so we don't have to port this one.
