### ISSUE TITLE
[PORT] healthcheck feature

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2102]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3796

healthcheck feature fixes #3313

# Changed projects
* Microsoft.Bot.Builder
* Microsoft.Bot.Schema
* Microsoft.Bot.Builder.Tests

[changes required]

**Comment by johnataylor** [comment]
issue is tracked with https://github.com/microsoft/botbuilder-js/issues/1640
