### ISSUE TITLE
[PORT] Change onTeamsMemberAdded for Teams to use getMember()

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2104]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3798

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/3774

# Changed projects
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Tests

**Comment by EricDahlvang** [comment]
closing ... tracked in a separate issue.
