### ISSUE TITLE
[PORT] Update Microsoft.BeginDialog.schema

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2106]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3801

Add a "type" field for BeginDialog.dialog. Otherwise it will cause a error in Composer. 

![image](https://user-images.githubusercontent.com/32191031/80192079-3c434e80-8649-11ea-9c7c-b3b88a04c36f.png)

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.TestBot.Json
*

**Comment by gabog** [comment]
@luhan2017, does this apply to JS? can you close it if it doesn't?

Thanks

**Comment by luhan2017** [comment]
@gabog, it doesn't apply to JS, we don't have schema defined in JS yet.
