### ISSUE TITLE
Mentioning user with & in username causes 'Mention entity does not match text' error

### ISSUE THREAD

**Issue by matthiasdilger** [microsoft/botbuilder-js#2111]
## Versions
SDK 4.8
nodejs 10.20.1

## Describe the bug
When mentioning a user with & in the username in a MessageFactory.text() message the server responds with Error: Mention entity does not match text. Works fine for mentions in adaptive cards. Possibly related to [this previously reported issue](https://github.com/microsoft/BotFramework-Services/issues/204).
[Also see comment on this SO answer](https://stackoverflow.com/a/58534193). 

## To Reproduce
Create a user in Teams called "Test ($~&)"
Send a message from your bot mentioning the user
```
let mention = { mentioned:
   { id:
      '29:16xB25CaNg2TuYGVNbiEyHpb5T5N9-5al1bghslxHEhlc8FE-2EizBGV9a-YI9Z8V4JtgLbQmFp1VCJG92UDFRw',
     name: 'Test ($~&)',
     aadObjectId: '8b0379fe-2011-4d65-a932-891e820aa23e' },
  text: '<at>Test ($~&)</at>',
  type: 'mention' }
let message = MessageFactory.text('Hi <at>Test ($~&)</at>! ');
message.entities = [mention];
(send the message)
```
## Expected behavior
Message should be accepted. Works fine when using mentions in adaptive cards (Teams client developer preview).

## Workaround
Replacing & with `&amp;` makes the server accept the message but causes UI issues in the client. See below.

## Screenshots
<img width="548" alt="Screen Shot 2020-04-27 at 19 28 35" src="https://user-images.githubusercontent.com/5625718/80367795-45892100-88be-11ea-9db2-28505013513c.png">
<img width="974" alt="Screen Shot 2020-04-27 at 19 33 34" src="https://user-images.githubusercontent.com/5625718/80367802-48841180-88be-11ea-8f78-3f935e739219.png">

**Comment by jwiley84** [comment]
@matthiasdilger 

This is directly related to your other issue [here](https://github.com/microsoft/BotFramework-Services/issues/204). I'm going to close this issue so we can better track in one place.
