### ISSUE TITLE
QnA Maker scoreThreshold validation does not allow 1

### ISSUE THREAD

**Issue by matthew-clark02** [microsoft/botbuilder-js#2112]
## Versions
botbuilder-ai - v4.8.0
nodejs - v13.6.0
macOS Mojave - 10.14.6

## Describe the bug
When calling `QnAMaker.getAnswers()` with `{ "scoreThreshold": 1 }` the following validation error is thrown: 
```
TypeError: \"1\" is an invalid scoreThreshold. QnAMakerOptions.scoreThreshold must have a value between 0 and 1."
```

The API docs allow for a score of 1 to be passed through to force exact matching but the validation in the SDK prevents this.

## To Reproduce
1. Call `QnAMaker.getAnswers()` with `{ "scoreThreshold": 1 }`
## Expected behavior
A scoreThreshold of 1 should be valid.

## Additional context
The validation code can be found here:
https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-ai/src/qnamaker-utils/generateAnswerUtils.ts#L157

[bug]

**Comment by Zerryth** [comment]
Thank you for reporting @matthew-clark02 . Made a PR to fix the issue.
