### ISSUE TITLE
SkillDialog only support message and event types

### ISSUE THREAD

**Issue by alopix** [microsoft/botbuilder-js#2119]
Is there a reason why the new `SkillDialog` only supports `message` and `event` activity types? I find this very curious as a skill could as well support and kind of e.g. `invoke` activity type.

https://github.com/microsoft/botbuilder-js/blob/18cb9822fe4f1a745158ae532872c9db4f3f6e29/libraries/botbuilder-dialogs/src/skillDialog.ts#L153

**Comment by hcyang** [comment]
Hi @gabog, can you also take a look. Thanks.

**Comment by gabog** [comment]
This is being addressed as part of #3833, you should be able to send any type of activity after that.

**Comment by gabog** [comment]
Closing this one, check #2139 for a resolution.
