### ISSUE TITLE
botbuilder-dialogs-adaptive, botbuilder-dialogs-declarative require different versions of text recognizers package

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-js#2123]
We need to align on the text recognizer package versions used across our packages. Without this, adapive dialog package does not work on mac. 

Upon investigating with @Stevenic it appears that we are inconsistent across botbuilder-dialogs, botbuilder-dialogs-declarative, botbuilder-dialogs-adaptive.

**Comment by stevengum** [comment]
Fixed via https://github.com/microsoft/botbuilder-js/pull/2135.
