### ISSUE TITLE
[PORT] add null string support in StringUtils

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2136]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3826

close: #3825
Support `null` string in `Ellipsis` and `Hash` method

# Changed projects
* Microsoft.Bot.Builder

**Comment by Danieladu** [comment]
`StringUtils` does not exist in js library currently. This would be migrated when porting of #2121 is ready.

**Comment by luhan2017** [comment]
Close this, use #2121 to track
