### ISSUE TITLE
[PORT] [QnAMaker] Volitile LowScoreVariation and Active Learning Issue fix

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2140]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3786

For issue #3714 

# Changed projects
* Microsoft.Bot.Builder.AI.QnA
* Microsoft.Bot.Builder.AI.QnA.Tests

[changes required]

**Comment by cleemullins** [comment]
@vipeketi Thanks for the C# PR. Now we need the JS one. :)
