### ISSUE TITLE
[PORT] Move LuisAdaptiveRecognizer into LUIS assembly

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2142]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3830

Fixes #3805

* move LuisAdaptiveRecognizer and supporting files
* removed LUIS dependency from Adaptive
* move all unit tests as appropriate
* consolidate MockHTTP assembly version.

# Changed projects
* Microsoft.Bot.Builder.AI.LUIS
* Microsoft.Bot.Builder.AI.LUIS.Tests
* Microsoft.Bot.Builder.Ai.LUISV3.tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Profiling
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Connector.Tests
* 

[Adaptive,R9]

**Comment by stevengum** [comment]
This doesn't look like it exists in JS, and this could prevent botbuilder-ai from working in browsers.

Removed R9 tag.

**Comment by joshgummersall** [comment]
https://github.com/microsoft/botbuilder-js/issues/2640
