### ISSUE TITLE
[JS] Further enhance custom function registration

### ISSUE THREAD

**Issue by dclaux** [microsoft/botbuilder-js#2154]
**Is your feature request related to a problem? Please describe.**
This is a proposal to make custom function declaration/registration even more "natural"

**Describe the solution you'd like**
If the `customFunction` type was defined liked this:
```typescript
type customFunction = (...args: any[]) => any;
```
Note the "..." in front of `args`

Then developers could register custom functions in an even more natural way. Example:
```typescript
Expression.functions.add(
  "contoso.add",
  (a, b) => {
      let result = null;

      if (typeof a === "number" && typeof b === "number") {
          result = a + b;
      }

      return result;
  });
```
Note that the parameters to the method are "unwound" already, and the developers doesn't have to deal with an arg array as is currently the case.

**Describe alternatives you've considered**
None

[enhancement]

**Comment by Danieladu** [comment]
The disadvantages of this solution is that it can not handler parameters of unknown length. For example, someone just want to get the sum from the input, originally, the code can be:
```
Expression.functions.add(
  "contoso.sum",
  (args) => {
      let result = 0;

     for (const arg of args) {
          if (typeof arg  === "number") {
               result += arg ;
          } else {
               throw new Error(`${arg} is not number type.`)
          }
     }
      return result;
  });
```

But if we change the parameters to rest parameters, it is hard for user to complete such customization.

Maybe there is a better solution?

**Comment by Danieladu** [comment]
Hi David, your suggestion is great, this solution does make user calls more convenient.
But there are a few things should consider.
## Functions with rest parameters
For example, someone just want to get the sum from the input (length unknow), originally, the code can be:
```
Expression.functions.add(
  "contoso.sum",
  (args) => {
      let result = 0;

     for (const arg of args) {
          if (typeof arg  === "number") {
               result += arg ;
          } else {
               throw new Error(`${arg} is not number type.`)
          }
     }
      return result;
  });
```

User can use it as `contoso.sum(1, 2)`,  `contoso.sum(1, 2, 3)`
In your solution, the first parameter should be list:
```
Expression.functions.add(
  "contoso.sum",
  (list) => {
      let result = 0;

     for (const arg of list) {
          if (typeof arg  === "number") {
               result += arg ;
          } else {
               throw new Error(`${arg} is not number type.`)
          }
     }
      return result;
  });
```
User should use it as `contoso.sum([1, 2])`, `contoso.sum([1, 2, 3])`
Hmmm, that seems ok.

## Nullable parameters
Example, for split function, code for originally
```
Expression.functions.add(
  "contoso.split",
  (args) => {
  string seperator;
   if (args.length > 1) {
      seperator = args[1];
  } else {
      seperator = ' ';
  }
.....
```
and user can use it as `contoso.xx('name', ',')` or `contoso.xx('name')`
In your solution:
```
Expression.functions.add(
  "contoso.split",
  (input, seperator) => {
  string sep;
   if (seperator === undefined) {
      sep= seperator ;
  } else {
      sep= ' ';
  }
.....
```

and user just can use it as `contoso.xx('name', ',')`,  and if someone want to skip the second parameter, the undefined must be called like `contoso.xx(a, undefined)`

Any thoughts?

**Comment by joshgummersall** [comment]
@boydc2014 is this feature not complete?

**Comment by boydc2014** [comment]
> @boydc2014 is this feature not complete?

Hi, @joshgummersall this was logged as an idea when we are chatting with adaptive card team. 

Current we provided two ways to create a customized function. One is more powerful and requires more details and coding, the other is easier to use. 

This requirement is to make the latter approach even eaiser, with "...". 

I don't think we will do this, as we don't want to introduce a third approach, which might be confusing to folks. So closing this for now.
