### ISSUE TITLE
[PORT] Update schemas for dialog:merge

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2163]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3851

This fixes many issues in schema and takes advantage of new features.
$role extend(kind) to allow extending an existing kind.  This allowed removing allof and simplified schema.
If a kind does not have a $role it will not be a top-level object.  Usually this is because a role implements an interface.  If it does not you can use $role: [] to force it as a top-level kind.
schema:#/definitions/stringExpression allows referring to component.schema definitions.
External schemas are only referred to once and the schema is self-contained.
Removed $copy and $id from standard component definitions.
Removed -b from all dialog:merge calls.
Added title/description throughout.
Added missing schema in choiceInput.
Fixes #3836 

# Changed projects
* Microsoft.Bot.Builder.AI.LUIS
* Microsoft.Bot.Builder.AI.QnA
* Microsoft.Bot.Builder.Dialogs.Adaptive.Testing
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.Dialogs.Declarative.Tests
* Microsoft.Bot.Builder.TestBot.Json
*

**Comment by cleemullins** [comment]
I beleive this is needed in JS.

**Comment by stevengum** [comment]
@boydc2014 and @luhan2017, let's sync next week to discuss this issue and the background work that needs to be addressed first.

**Comment by joshgummersall** [comment]
@stevengum let's discuss this next week to see where to take this.

**Comment by joshgummersall** [comment]
Resolved via https://github.com/microsoft/botbuilder-js/pull/2986
