### ISSUE TITLE
[PORT] Timex function for hasFullDate and hasValidHour builtin-functions

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2165]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3780

closes: #2869 
Now we have 7 timex related functions:
HasFullDate, HasValidTime, HasValidDuration, HasValidDate, HasValidTimeRange, HasValidDateRange, IsPresent

# Changed projects
* AdaptiveExpressions
* AdaptiveExpressions.Tests

[changes required]

**Comment by cleemullins** [comment]
I believe this is needed in JS. Note the names have changed due to #2169
