### ISSUE TITLE
[PORT] Fix signature of LanguageGenerator base class

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2167]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3850

fixes #3558

LG returns an object when binding to herocards/activity.
object was being serialized to JSON, then run through code to detect if it's JSON and convert it to an object.  
This was all because LanguageGenerator.Generate() had signature of string for the return type.
Changes
* Changed Generate() to return an object
* Removed goofy code with double-deserialization
* Updated unit tests to not do goofy double-deserialization
* also made LGExtensions class name match other classes in system.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests

**Comment by cleemullins** [comment]
Not relevant for JS

**Comment by Danieladu** [comment]
should port to js

**Comment by Danieladu** [comment]
Fixed by :#2881
