### ISSUE TITLE
WebChat OAuth SSO doesn't continue after Login

### ISSUE THREAD

**Issue by Nitin2392** [microsoft/botbuilder-js#2170]
Hey,

The issue we're having right now is that once we click on the `Login` button in the OAuthPrompt from the webchat, the SSO takes over and the Sign in Happens but when the flow returns to the webchat, nothing happens and the bot just hangs. 

In the Microsoft Bot Framework (v4) bot that we're building, we have implemented the new SSO OAuth features that were recommended in this blog [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0&tabs=aadv2&viewFallbackFrom=azure-bot-service-4.0) and [here](https://blog.botframework.com/2018/09/01/using-webchat-with-azure-bot-services-authentication/). 

1) We initially had an `<iframe>` setup which prompted for the Magic code. 
2) We then changed the `<iframe>` setup and migrated to a DirectLine channel by changing the webchat's source code to exchange the bot secret for a token (we also pass a unique userId in the format - `dl_guid()`)
3) We pass that token down to `window.WebChat.createDirectLine` method sourced from the CDN - `https://cdn.botframework.com/botframework-webchat/latest/webchat.js`
4) We have AADV2 Setup with the right scopes and we also have the bot configured for this AAD. 
5) We also have `Enhanced Authentication options` enabled for the DirectLine channel and have the `localhost` dev environment & the hosted server environment added to the **Trusted Origin** list
6) We've also enabled 3rd party cookies in the browser

## Screenshots
![image](https://user-images.githubusercontent.com/3441046/80820346-b1140c80-8ba4-11ea-9526-212e171fbfbe.png)

## Bot Source Code

Here's a snippet from the AuthDialog that we are using (TypeScript)

```
export class AuthDialog extends BaseDialog {
  constructor(
    private dialogContextUtils: DialogContextUtils,
    private userManager: UserManager,
    appConfig: AppConfig
  ) {
    super(AUTH_DIALOG_ID, AUTH_WATERFALL_DIALOG, [
      step => this.promptStep(step),
      step => this.loginStep(step)
    ]);

    this.addDialog(
      new OAuthPrompt(OAUTH_PROMPT, {
        connectionName: appConfig.connectionName,
        text: 'Please login',
        title: 'Login',
        timeout: 300000
      })
    );
  }

  private async promptStep(step: WaterfallStepContext) {
    return await step.beginDialog(OAUTH_PROMPT);
  }

  private async loginStep(step: WaterfallStepContext) {
    const tokenResponse = step.result;

    if (tokenResponse) {
            await step.context.sendActivity(`Hi`);   
    }

    return await step.endDialog(tokenResponse);
  }
```

If we take a look at the code, the bot should essentially enter into `loginStep` but it doesn't (Tried it by setting breakpoints)

Would really appreciate some help with this issue.

**Comment by cleemullins** [comment]
@dmvtech, could you take a look at this?

**Comment by Nitin2392** [comment]
Thanks @cleemullins

**Comment by stevkan** [comment]
@Nitin2392, can you please test using sample [18.bot-authentication](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/18.bot-authentication)? I just want to narrow down whether the flow is related specifically to login, SSO, or something else.

Presently, I can run sample #18 without issue. I'll next try testing using the blogs you reference and see what results are returned.

**Comment by Nitin2392** [comment]
Sure @stevkan. I'll try that out and let you know what the results are

**Comment by stevkan** [comment]
If you can check / answer a few more questions, I'd appreciate it:

- I'm not real big on typescript, but why do you use the following setup for adding/calling steps vs what is demonstrated in our typescript samples ([here](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/typescript_nodejs/13.core-bot/src/dialogs/bookingDialog.ts), for example)? And, could this be part of the problem? Perhaps the steps aren't being called correctly?

```ts
super(AUTH_DIALOG_ID, AUTH_WATERFALL_DIALOG, [
      step => this.promptStep(step),
      step => this.loginStep(step)
]);
```

- Have you tried stepping thru slowly with a debugger from the `promptStep` to the `loginStep`? I ask as I was having the same issue when testing in my development test bot. Yet, when I stepped thru and slowed the login step down the `stepContext.result` was populating and getting read by the proceeding `if` statement.

- That being said, the issue seems to have resolved itself for me on its own. It is now functioning correctly and without pause. Can you double check that this is still an issue for you?

- Lastly, (if it isn't a moot point) did sample 18 work when tested?

**Comment by stevkan** [comment]
Closing due to a lack of activity. If the problem persists, please feel free to reopen.

**Comment by Nitin2392** [comment]
I apologize for not responding @stevkan! We got sidetracked into another project. 

So, we figured that we were missing out something and we fixed the issue. 

We had to add in this piece of code for things to work 
```
 this.onTokenResponseEvent(async (context, next) => {
      //Handle token exchange
    });
```

Thanks for your help!
