### ISSUE TITLE
[PORT] Replace UseState() with UseBotState() 

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2175]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3862

Fixes #3859 
and use untyped params so that order and type are not fixed.
Tweak RegisterMiddlewareClass so you can provide the key for the turnstate.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive.Testing
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.AI.QnA.Tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.Dialogs.Declarative.Tests
* Microsoft.Bot.Builder.Dialogs.Tests
* Microsoft.Bot.Builder.TestBot.Json
*

**Comment by chon219** [comment]
I'll start working on this after #2382 being merged.

**Comment by stevengum** [comment]
Pushing this out as the core change in #2504 adds surface area for a pattern that isn't normally used in JS.

Additionally, between this (`RegisterClassMiddleware`) and `DialogManager.InitialTurnState`, I think there might be some room for cleanup around the concept of initializing a `TurnContext.TurnState`.
