### ISSUE TITLE
[PORT] Remove $id from schema to prevent tests from changing assets.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2176]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3863

dialog:merge has also been updated.

# Changed projects
* Microsoft.Bot.Builder.TestBot.Json
*

**Comment by joshgummersall** [comment]
Not applicable to JS repo.
