### ISSUE TITLE
[PORT] Improve disconnect test so it actually tests disconnect.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2178]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3865

Closes #3861 

Tested using VSTest under netcore 2.1 and 3.1, now passes 100% of the time, vs around 50% of the time previously. Also now asserts the connection has been established and then torn down, to be sure the state has changed.

# Changed projects
* Microsoft.Bot.Streaming.Tests

**Comment by stevengum** [comment]
N/A
