### ISSUE TITLE
[PORT] Allow default(array) implicit assignment

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2180]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3869

Fixes #3868 

* If someone passes in null array, implicit assignment was attempting to .ToList() it.  Changed use IEnumerable and not try to use .ToList() which means null flows through correctly.
* Add more unit tests to verify default(T) behavior around implicit assignment.

# Changed projects
* AdaptiveExpressions
* AdaptiveExpressions.Tests

[P0,R9]

**Comment by sgellock** [comment]
QnADialog issue from C#

**Comment by stevengum** [comment]
N/A as we don't use implicit assignment
