### ISSUE TITLE
botbuilder-ai depends on moment without using it

### ISSUE THREAD

**Issue by alopix** [microsoft/botbuilder-js#2181]
The library botbuilder-ai depends on the package moment, which is not even used in the code. There's an import statement in types, but then not references.

[Code Search](https://github.com/microsoft/botbuilder-js/search?q=path%3A%2Flibraries%2Fbotbuilder-ai+moment&unscoped_q=path%3A%2Flibraries%2Fbotbuilder-ai+moment)

**Comment by cleemullins** [comment]
R10, our next milestone, has a cleanup of dependencies planned. Adding this to that milestone.
