### ISSUE TITLE
[BotBuilder] TestFlow class does not match C# counterpart

### ISSUE THREAD

**Issue by VictorGrycuk** [microsoft/botbuilder-js#2183]
## Versions
What package version of the SDK are you using. **[botbuilder@^4.8.0](https://www.npmjs.com/package/botbuilder/v/4.8.0)**
What nodejs version are you using **[v12.16.1](https://nodejs.org/en/blog/release/v12.16.1/)**
What browser version are you using
What os are you using **Windows 10 Pro**

## Describe the bug
The [JavaScript](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/testAdapter.ts#L537) implementation of `TestFlow` **does not** offer the same capabilities of its [C#](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/Adapters/TestFlow.cs) implementation.

Attempting to implement some functionalities based on the C# implementation of `TestFlow` is not possible to use the JavaScript version, especially those that rely on the `BotCallbackhandler` since its missing from JavaScript.

## To Reproduce
1. Clone [BotBuilder-DotNet](https://github.com/microsoft/botbuilder-dotnet).
1. Navigate to `/libraries/Microsoft.Bot.Builder/Adapters/`
1. Open `TestFlow.cs`
1. Clone [BotBuilder-JS](https://github.com/microsoft/botbuilder-js).
1. Navigate to `/libraries/botbuilder-core/src/`
1. Open `testAdapter.ts`, scroll down to [line 537](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/testAdapter.ts#L537).
1. Compare both implementations of `TestFlow`

## Expected behavior
I expect TestFlow in JavaScript to use the same implementation as in C#.

## Screenshots
`TestFlow` C# vs `TestFlow` JavaScript

![image](https://user-images.githubusercontent.com/39467613/81083906-8b9c4100-8ecb-11ea-89bb-bef39f4383bf.png)

## Additional context
While migrating bot-solution from the [botframework-solutions](https://github.com/microsoft/botframework-solutions) repository tests, we found that C# uses the callback's context to **[set the userProfileState](https://github.com/microsoft/botframework-solutions/blob/v0.8-beta/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/BotTestBase.cs#L135-L139)**, however, that is not possible to do it with the current implementation of TestFlow in JavaScript.

At the moment we rely on using [TestAdapter](https://github.com/microsoft/botframework-solutions/blob/v0.8-beta/templates/typescript/samples/sample-assistant/test/helpers/botTestBase.js#L102), but neither uses the BotCallbackHandler.

[bug]

**Comment by cleemullins** [comment]
@dmvtech, please work with @gabog as needed to iterate on this.

**Comment by stevkan** [comment]
@VictorGrycuk, thank you for bringing this to our attention. We'll begin bringing the two SDKs into parity. Please feel free to check back here for updates as work progresses.

**Comment by stevengum** [comment]
@stevkan what's the status on this?

**Comment by stevkan** [comment]
@stevengum, PR is near to being submitted for review. Working on writing tests and running, then will submit.

**Comment by pavolum** [comment]
Removing customer tags as this was opened by Southworks

**Comment by tsuwandy** [comment]
@stevkan, any update on this?  Was the PR submitted?  If so, could you close this?  Thanks!

**Comment by stevkan** [comment]
Working on finalizing PR for submission.

**Comment by stevengum** [comment]
@stevkan are there any updates on this issue?

**Comment by stevkan** [comment]
Needing assistance on completing the TestFlow/TestAdapter tests. Set up time with @joshgummersall for help.

**Comment by stevkan** [comment]
An error in the build process, when attempting to build a local copy, has been a roadblock for several weeks. However, I have finally gotten around the issue and will be moving forward on finalizing development of this.

**Comment by joshgummersall** [comment]
Both the [TestFlow](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-core/src/testAdapter.ts#L66) and [TestAdapter](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-core/src/testAdapter.ts#L66) constructors provide a callback parameter, so this is resolved.
