### ISSUE TITLE
[PORT] Get rid of HostContext

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2193]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3880

# Changed projects
* AdaptiveExpressions
* Microsoft.Bot.Builder.AI.LUIS
* Microsoft.Bot.Builder.AI.QnA
* Microsoft.Bot.Builder.Dialogs.Adaptive.Testing
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Debugging
* Microsoft.Bot.Builder.Dialogs.Declarative
* Microsoft.Bot.Builder.Dialogs
* Microsoft.Bot.Builder.LanguageGeneration
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.AI.LUIS.Tests
* Microsoft.Bot.Builder.AI.QnA.Tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Profiling
* Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.Dialogs.Declarative.Tests
* Microsoft.Bot.Builder.Dialogs.Tests
* Microsoft.Bot.Builder.TestBot.Json
*

**Comment by Stevenic** [comment]
This work has already been done
