### ISSUE TITLE
[PORT] [Expression] Add formatNumber, formatEpoch and  formatTicks as prebuilt functions

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2199]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3876

Refers to the first question in https://github.com/microsoft/botbuilder-dotnet/issues/3873

formatNumber(num1, num2), takes two arguments, the first one should be a numeric value, and the second one should be an integer. The returned value is a string
Examples
formatNumber(12.123, 2) =  "12.12"
formatNumber(20, 2) =  "20.00"
formatNumber(1.555, 2) = "1.56"
formatNumber(12.123, 4) = "12.1230"

Added formatEpoch and formatTicks. 
formatEpoch(1521118800) -> 2018-03-15T13:00:00.000Z
formatTicks(637243624200000000) -> 2020-05-06T11:47:00.000Z

Removed ticks functionality from formatDateTime.

Fixed an issue where JSON conversion would truncate 64 bit values and doubles.

# Changed projects
* AdaptiveExpressions
* AdaptiveExpressions.Tests
* Microsoft.Bot.Builder.LanguageGeneration.Tests

**Comment by Danieladu** [comment]
Fixed in #2198
