### ISSUE TITLE
[Expressions] formatNumber needs to support locale

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-js#2202]
## Describe the bug
formatNumber needs to support locale.  It takes in the locale and uses number.toLocaleString, but that and Intl.numberFormat doesn't actually work unless you have a special version of node.  The alternative is to use a package. Numeral and d3-format have the basics, but no locale specific information.  Numbro has locales, but is optimized for the browser.

## To Reproduce
formatNumber(12000.3, 3, 'fr-FR') should produce "12\x00a000,300", but it does not.

[bug]

**Comment by boydc2014** [comment]
this should be done when we port https://github.com/microsoft/botbuilder-dotnet/pull/4276, which just get merged today, @cosmicshuai will take the point of porting this.

**Comment by cleemullins** [comment]
Is there any update here? We're cutting RC0 of JS today.

**Comment by cleemullins** [comment]
I don't think we're quite ready to take this. Checked w/ @EricDahlvang and @carlosscastro and we'll push this issue and related PR to R11.
