### ISSUE TITLE
[Expression] Handler big number correctly

### ISSUE THREAD

**Issue by Danieladu** [microsoft/botbuilder-js#2211]
## Describe the bug
Currently, JS sdk uses `Number` to handler all number input, and with `BigInt` to handler `ticks()`.
So, there exists two issues
1. C# can use `long/int64` to handler the integer range **-2^63 ~ 2^63 -1**, but the range of `Number` in js is **-2^53+1 ~ 2^53**, [click to see more](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger).  So, there exists some gaps between these two languages.
For example, in C#, expression  `12345678912345678 + 1` would get the right answer , but in js, since, the number is out of the `Number` scope, the final result is not accurate. 

*Or keep the language diversity: Supports precise operation of a larger range of integers in  .net SDK.*

2. js use `bigint` to define the ticks result, so, there exist such issue:
`ticks(utcNow()) - 1` does not work, because bigInt cannot perform calculation operation directly with number.

*Or keep the language diversity: `ticks()` in node can only be used as the parameter of function `formatTicks()`*

[discussion]

**Comment by joshgummersall** [comment]
@chrimc62 has this already been addressed?

**Comment by joshgummersall** [comment]
@Danieladu I added this to R12, let me know if you have any concerns or want to assign this issue to me or someone else.
