### ISSUE TITLE
4.9.0 package.json version seems to be 4.9.0-rc5

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-js#2229]
## Versions
4.9.0

## Describe the bug
If you look at the package.json you will see the below which is incorrect.  I verfied with adaptive-expressions and botbuilder-lg.  
"version": "4.9.0-rc5"

## Expected behavior
package.json should match published version.

[bug]

**Comment by cleemullins** [comment]
I pull down the package:
```
npm i adaptive-expressions
```
When I look at the package.json, I see:
```
"_from": "adaptive-expressions",
  "_id": "adaptive-expressions@4.9.0",
  "_inBundle": false,
```
and further down in the file:
```
  "typings": "./lib/index.d.ts",
  "version": "4.9.0"
```

So I think this is good to go.
