### ISSUE TITLE
Spammers issue

### ISSUE THREAD

**Issue by khmerforce** [microsoft/botbuilder-js#2241]
Hi what would happen if a hacker put their spammer bot to write over millions of messages. Please explains.

**Comment by EricDahlvang** [comment]
Hi @khmerforce 

The bot would likely be throttled: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0#rate-limiting

If the concern is for your bot, you should be able to use similar ddos protection mechanisms as what you would use for any api or website.

Please direct questions to Stackoverflow. The Bot Framework Team monitors StackOverflow for questions, and prefers to use the github repositories for bug reports and feature requests.
