### ISSUE TITLE
[PORT] Support long/int64 in number constant

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2256]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3912

close: #3888
Support long/int64 constant input in Expression

# Changed projects
* AdaptiveExpressions
* AdaptiveExpressions.Tests

[R10]

**Comment by Danieladu** [comment]
language specific. close it.
