### ISSUE TITLE
package atob does not work in Web worker

### ISSUE THREAD

**Issue by Danieladu** [microsoft/botbuilder-js#2260]
package atob depends on `window` to evaluate the result in browser environment.
But in web worker, `window` is undefined.
attach:

![image](https://user-images.githubusercontent.com/7289268/82514676-ed55df80-9b48-11ea-9b3a-7f8a04267ac5.png)

**Comment by compulim** [comment]
Good to see someone run the bot in Web Worker. 👍🏻
