### ISSUE TITLE
[PORT] remove duplicate SourceContext

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2261]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3896

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Debugging
* Microsoft.Bot.Builder.Dialogs

**Comment by mrivera-ms** [comment]
Closing this item. Analyzed by Southworks: There is no SourceContext class in JS. Nothing to remove.
