### ISSUE TITLE
[PORT] Set Locale for EoC in DialogManager

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2263]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3875

align to #3739

# Changed projects
* Microsoft.Bot.Builder.Dialogs
* Microsoft.Bot.Builder.Dialogs.Tests

**Comment by mdrichardson** [comment]
Unassigning myself from this as #1970 needs to be merged in, first.
