### ISSUE TITLE
Teams shows "bad request" when a skill invocation ends

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-js#2265]
JS Version of https://github.com/microsoft/botbuilder-dotnet/issues/3956
## Version
4.9.1

## Describe the bug
When you call a skill from a bot on teams you'll get a "bad request" message when the skill ends.  I believe this is related to the issue of the post back completing on a second thread.

![image](https://user-images.githubusercontent.com/698939/82462434-6af9ec80-9a70-11ea-88c0-b2935ce5b22e.png)

[bug]

**Comment by gabog** [comment]
This Should be addressed as part of #1970, closing it.
