### ISSUE TITLE
[PORT] Per property operations

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2272]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3975

Update the runtime to handle per property operations.  This included a change to $defaultOperation where instead of a string, it is now an object going from property to an object of per-entity default operations.  Empty property and empty entity are defaults if not explicitly defined.

Made it much smarter around handling PROPERTYName and how it interacts with operations.
Fixed a bug where entities could be recursive causing a serialization error.
Fixed a bug where an unhandled item from the queue would terminate the dialog.
Updated the tests to include arrays and operations.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive.Testing
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.Dialogs.Declarative.Tests
* Microsoft.Bot.Builder.TestBot.Json
*

**Comment by luhan2017** [comment]
This should happen after the generated dialog is supported.

**Comment by luhan2017** [comment]
@chon219 let's verify the form dialog scenario and ported the test cases from C# first.

**Comment by joshgummersall** [comment]
When form dialog parity is prioritized we will address this as part of the initial port.
