### ISSUE TITLE
[PORT] [Expression] DateTime related prebuilt functions can handle DateTime object as an input

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2273]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3945

fixes: https://github.com/microsoft/botbuilder-dotnet/issues/3943

In DSM, a timestamp string will be saved as DateTime object, which will cause evaluation error.
In this PR, all related prebuilt functions can handle DateTime object as an input.

# Changed projects
* AdaptiveExpressions
* AdaptiveExpressions.Tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests

**Comment by cosmicshuai** [comment]
I checked the JS SDK does not have this issue. 
```
                {
                    "$kind": "Microsoft.SetProperty",
                    "property": "user.date",
                    "value": "2018-01-01T08:00:00.000Z"
                },
                {
                    "$kind": "Microsoft.SendActivity",
                    "activity": "${formatDateTime(user.date)}"
                }
```
In this scenario, the value user.date passed to Adaptive-Expression was still a string value. So we don't have any thing to do here.
