### ISSUE TITLE
telemetryLoggerMiddleware code issue for TS

### ISSUE THREAD

**Issue by rjgmail88** [microsoft/botbuilder-js#2274]
#### What project is affected?
Add a Skill in Power virtual agents
https://docs.microsoft.com/en-us/power-virtual-agents/configuration-add-skills#validation-performed-during-registering-a-skill

#### What language is this in?
Typescript

#### What happens?
When we try to executes steps mentioned in above document where are trying to add BF skill to PVA agent, following piece of code breaks 

File: /node_modules/botbuilder-core/lib/telemetryLoggerMiddleware.js
Function: fillReceiveEventProperties(...) has following lines 

```
properties[this.telemetryConstants.recipientIdProperty] = activity.recipient.id;
properties[this.telemetryConstants.recipientNameProperty] = activity.recipient.name;
```

As recipient is coming as NULL this is throwing an exception. So we had to modify the lines as follows which just sets recipient.id and recipient.name to empty string. 

```
properties[this.telemetryConstants.recipientIdProperty] = ( activity && activity.recipient && activity.recipient.id ) ? activity.recipient.id : '';

properties[this.telemetryConstants.recipientNameProperty] = ( activity && activity.recipient && activity.recipient.name ) ? activity.recipient.name : '';

```
#### What are the steps to reproduce this issue?
Steps 1: Create a BF TS skill (nodejs)
step 2: create a PVA bot (follow https://docs.microsoft.com/en-us/power-virtual-agents/fundamentals-get-started)
Step 3: Add a skill you created at step 1 to your PVA bot as step 2 using manifest file (follow https://docs.microsoft.com/en-us/power-virtual-agents/configuration-add-skills#validation-performed-during-registering-a-skill
)

#### What were you expecting to happen?
 We are expecting that recipient should be populated or this code check need to be added in. 

#### Can you share any logs, error output, etc.?
No

#### Any screenshots or additional context?

![image](https://user-images.githubusercontent.com/32375467/82361820-050a5800-99d1-11ea-8ed2-624a6738cd67.png)

**Comment by garypretty** [comment]
Hi @rjgmail88. Thanks for reporting. As you have identified, this is a bug in the JS middleware and the workaround you have implemented is the correct one until a fix is available in the SDK packages.  I am curious if you can provide a little more details though.  Is this failing when your skill is sending a message back to the user? It would be good to know a little more as I am surprised the recipient field is blank.

**Comment by rjgmail88** [comment]
Hi @garypretty, This code breaks when we PVA tries to register a skill we are adding using manifest file. This is what happens step by step 
1. We supply manifest of a BF JS skill in PVA tool 
2. Click add skill button and PVA starts parsing json. 
3. PAV actually makes a call to skill, while doing so request somehow passes to above piece of code. ( I have actually debugged this to find the root cause. )
4. After my fix - skill registration was finished. But later on for every message we send from PVA to a skill, I do see error on console but, it works as expected. This means there is one more place to fix. However, it doesn't cause any conversation breaks, so exception is handled somewhere I believe. 

Hope this helps, Let me know if I can provide more details, logs etc
