### ISSUE TITLE
DCR: add extra safety checks to DialogContext.continue() and begin() 

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-js#228]
The driver code for using dialogs, while flexible, is pretty easy to get wrong.  The two primary things I see happening are people calling `dc.continue()` and then calling `dc.begin()` without checking whether the bot responded or the reverse... They call `dc.begin()` and then call `dc.continue()` which you pretty much should never do. I've done both myself so it's pretty easy to accidentally do either.

One thought I had was to add some extra checks to DialogContext which try to catch these issues and either log a warning to the console or potentially even throw an exception.  in both cases I think you should be able to disable the the checks but I think adding them would save developers some grief.

**Comment by sgellock** [comment]
We believe the new dialog design addresses this.
