### ISSUE TITLE
Teams bot - Channel ID not identified when bot added to a specific channel.

### ISSUE THREAD

**Issue by anteater-seraphin** [microsoft/botbuilder-js#2289]
## Versions
What package version of the SDK are you using.
"botbuilder": "~4.7.0"

What nodejs version are you using
v14.0.0

What os are you using
Ubuntu 18.04 LTS

## Describe the bug
Using Ms Teams, when adding the bot to a specific channel, I listen to the onMembersAdded from the TeamsActivityHandler class to send a welcome message. 
The message gets sent to "General", no matter the channel where the bot was added to. 

The TeamsInfo.getTeamDetails(turnContext) method returns the "General" channel id as well. 

## To Reproduce
Here is a minimum reproducible exemple:
```
const { TeamsActivityHandler, TurnContext, TeamsInfo } = require("botbuilder");

class Bot extends TeamsActivityHandler {
  constructor() {
    super();

    
    this.onMembersAdded(async (turnContext, next) => {

      const teamsChannelId = await TeamsInfo.getTeamDetails(turnContext);
      console.log(teamsChannelId);

      await context.sendActivity("Hello");


      await next();
    });
  }

}

module.exports.Bot = Bot;
```
And our Teams app manifest:
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.6/MicrosoftTeams.schema.json",
  "manifestVersion": "1.6",
  "version": "1.0.0",
  "showLoadingIndicator": false,
  "id": "**************************",
  "packageName": "bot.teams.*******",
  "developer": {
    "name": "Company",
    "websiteUrl": "https://www.company.com",
    "privacyUrl": "https://www.company.com",
    "termsOfUseUrl": "https://www.company.com"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "AppName",
    "full": ""
  },
  "description": {
    "short": "Company bot",
    "full": "Interact with Company"
  },
  "accentColor": "#FFFFFF",
  "bots": [{
    "botId": "**********************************",
    "needsChannelSelector": true,
    "scopes": [
      "team"
    ],
    "supportsFiles": false,
    "isNotificationOnly": false
  }],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": []
}
```

## Expected behavior
I expect the turnContext.sendActivity('Welcome') to send the message to the channel where the bot was added.

[bug]

**Comment by clearab** [comment]
This is unfortunately the expected behavior currently. Even though the UI looks like you're selecting a particular channel to add the bot to, you're not - you're installing the app to the Team. Choosing a channel in that UI just indicates what channel you should be dropped in post-installation.

I'm opening an Issue in the Teams docs repository to continue this discussion - I'd like to make sure to bring this to their attention directly. You can find that Issue here: https://github.com/MicrosoftDocs/msteams-docs/issues/1728
