### ISSUE TITLE
[PORT] Make data and locale optional in multilingual LG

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2290]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3932

close: #3931

# Changed projects
* Microsoft.Bot.Builder.LanguageGeneration
* Microsoft.Bot.Builder.LanguageGeneration.Tests

[R10]

**Comment by Danieladu** [comment]
platform specific
