### ISSUE TITLE
[PORT] fix 'getPastTime' and 'getFutureTime' error result

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2291]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4002

issue: https://github.com/microsoft/botbuilder-js/issues/2281
`getPastTime` and `getFutureTime` are applying a time zone correction when they shouldn't, resulting in incorrect results.

# Changed projects
* AdaptiveExpressions
* AdaptiveExpressions.Tests

**Comment by Danieladu** [comment]
close it. Duplicate wit #2281
