### ISSUE TITLE
[PORT] Change xUnit test attribute to fit "TestCategory" filtering 

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2293]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3991

This merges to master. The previous PR of the same name was for merging to 4.9.
This means test runs can uniformly use "TestCategory" for filtering both xUnit and MSTest tests.

# Changed projects
* Microsoft.Bot.Connector.Tests

**Comment by stevengum** [comment]
N/A
