### ISSUE TITLE
[PORT] Don't throw exception on unhandled VersionChangeDetected event (#4000)

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2301]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4015

* disable throwing exception if dialog change not handled

* remove trace from versionChanged

Fix #4013 

# Changed projects
* Microsoft.Bot.Builder.Dialogs

**Comment by stevengum** [comment]
Fixed via https://github.com/microsoft/botbuilder-js/pull/2298
