### ISSUE TITLE
Replace Node.js packages in `botframework-streaming`

### ISSUE THREAD

**Issue by compulim** [microsoft/botbuilder-js#2311]
## Background

`buffer`, `crypto`, `stream` and other Node.js packages are not natively exist in browser or [JavaScriptCore](https://developer.apple.com/documentation/javascriptcore).

Webpack automatically find their corresponding packages in NPM registry, this feature is outlined here, https://webpack.js.org/configuration/node/, and is called "Node Interface".

The package which Webpack "automatically" pulled in, to replace Node.js-only packages, are outlined in this package, https://www.npmjs.com/package/node-libs-browser.

## How it works

- Publication side
   - On a package (e.g. `botframework-streaming`), it has code `require('stream')`
   - The package is published to a registry
- Consumption side
   - On a Webpack project, `npm install botframework-streaming`
   - When Webpack is executed, it change `require('stream')` into `require('stream-browserify')` on-the-fly

## Explanation

Webpack replace packages that are known to be native on Node.js platform, with a browser alternative (a.k.a. `node-libs-browser`).

If the consumer is on Webpack, everything is done automatically.

If the consumer is NOT on Webpack (e.g. Rollup or React Native), the project will fail to build. And sometimes, it is not trivial or recommended for consumer to configure the bundler pipeline. In other words, ejection is often a last resort.

Since `botframework-streaming` is a base library, it should be minimal on platform-dependent libraries. If any platform-dependent library is required to operate, it should use an isomorphic version.

Isomorphic means, a cross-platform package, and usually made up of multiple packages that each of them provide support for a set of platforms. And when they are used as a whole, they provide great cross-platform coverage.

Although the "Node Interface" feature makes developers life easier, that also means `botframework-streaming` will only works on Node.js and Webpack platform. And not working on other platforms including React Native.

## Actions

There are two options:

1. Replace `stream` package with an isomorphic version
   - On Node.js, use `stream`
   - On non-Node.js platform, use `stream-browserify`
      - Non-Node.js platform includes: modern browsers, JavaScriptCore, and other headless JavaScript engines
1. Replace `stream` package with packages that use JavaScript typed array feature
   - Today, Node.js is not using JS type array feature (e.g. `ArrayBuffer`, `Uint8Array`, etc)
   - Instead, Node.js use `buffer` package, which is native and unique to Node.js environment, I believe it is a superset of typed array
   - All browser platforms (> IE10) natively support typed array

I would recommend route 2 that use a standardized native feature. JavaScript typed array is a standardized feature across all modern JavaScript engines and it is also very high performance as engines usually implement it natively.

[enhancement]

**Comment by stevengum** [comment]
I like approach 2 as well for the native feature approach.

I'm not sure this will be picked up for R10, but I'm all for moving closer to the language's native features.

**Comment by Zerryth** [comment]
Will do, team!

**Comment by stevengum** [comment]
@Zerryth will follow up with @compulim for additional information.

At the moment, this is not tied to a specific scenario/customer-driven ask and is therefore not tied to a milestone.

**Comment by stevengum** [comment]
The fix here should address the following issues:

https://github.com/microsoft/BotFramework-DirectLineJS/issues/290
https://github.com/microsoft/BotFramework-DirectLineJS/issues/289
https://github.com/microsoft/BotFramework-DirectLineJS/issues/288

**Comment by Zerryth** [comment]
Reassigning to Steven, as he had worked on successfully repro-ing customer's issue in [DLJS issue#288](https://github.com/microsoft/BotFramework-DirectLineJS/issues/288)

**Comment by stevengum** [comment]
Addressing this ask will fix https://github.com/microsoft/botbuilder-js/issues/2394

**Comment by stevengum** [comment]
Unfortunately there isn't enough R10 bake time for the removal of the Node.js dependencies in the botframework-streaming.

The currently targeted milestone is R11

**Comment by felixvanleeuwen** [comment]
R11 tag was removed.
Are you still targeting a release for this issue?
