### ISSUE TITLE
[Adaptive-Expressions] Pick up updated antlr4ts package with ES5 support

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#2313]
ES5 support could be added into `antlr4ts` via https://github.com/tunnelvisionlabs/antlr4ts/pull/440, but this PR is currently blocked.

There are two tracking issues in tunnelvisionlabs/antlr4ts: [#311](https://github.com/tunnelvisionlabs/antlr4ts/issues/311) and [#326](https://github.com/tunnelvisionlabs/antlr4ts/issues/326).

**Comment by joshgummersall** [comment]
Related: https://github.com/microsoft/botbuilder-js/pull/2990

**Comment by joshgummersall** [comment]
Closing in favor of https://github.com/microsoft/botbuilder-js/issues/3209
