### ISSUE TITLE
[Adaptive] Support inline object initialization via constructor for dialogs

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-js#2314]
Today, you need to use the configure method to initalize a dialog with properties. This is a bit cumbersome. 
```js
new SetProperty().configure({
        property: new StringExpression("dialog.itemTitle"),
        value: new ValueExpression("=@itemTitle")
    }),
```

Ask is to support object initialization of a dialog via constructor so the below is possible 

```js
new SetProperty({
    property: "dialog.itemTitle",
    value: "=@itemTitle"
}),
```

**Comment by luhan2017** [comment]
1. constructor only accept a configure object parameter. 
2. in configure, we support multiple types including string type.
