### ISSUE TITLE
[Adaptive] botbuilder-dialogs-adaptive-tests package name is incorrect

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#2319]
## Versions
branch: `master`

## Describe the bug
botbuilder-dialogs-adaptive-tests should be botbuilder-dialogs-adaptive-testing

Per C#, it should be [botbuilder-dialogs-adaptive-testing](https://github.com/microsoft/botbuilder-dotnet/tree/28ab3a20ec992c411e7543575177f61785ec7200/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing) ([`master`](https://github.com/microsoft/botbuilder-dotnet/tree/master/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing))

When this issue is fixed, the CI needs to be updated with the new package name.

[bug]

**Comment by chon219** [comment]
We have two different packages in C# sdk:
- Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
- Microsoft.Bot.Builder.Dialogs.Adaptive.Testing

`Testing` is for testing framework and other test related components, while `Tests` only have test cases. Our package `botbuilder-dialogs-adaptive-tests` covers both testing framework and test cases, do we need to split this package into two? Thanks. @stevengum

**Comment by luhan2017** [comment]
adaptive-testing/
  src/
  tests/

**Comment by stevengum** [comment]
Per 7/2/20 sync-up, this packageisn't a "preview" ship blocker and has been accordingly de-prioritized.

It would still be better to get this done ahead of time so that we avoid any future issues through memory loss.
