### ISSUE TITLE
Creating Middleware documentation: link broken

### ISSUE THREAD

**Issue by tessmichi** [Microsoft/botbuilder-js#232]
The hyperlink for BotContext on the [Creating Middleware documentation](https://github.com/Microsoft/botbuilder-js/wiki/Creating-Middleware#botcontext-lifetime) looks like an outdated markdown file that doesn't exist anymore. It gives a 404 not found error.

The broken URL's path is https://github.com/Microsoft/botbuilder-js/tree/master/doc/botbuilder/interfaces/botbuilder.__global.botcontext.md

I tried to find the right file to point to so I could fix it myself but wasn't sure what to replace this with.

**Comment by Stevenic** [comment]
I'll work on updating that...

**Comment by vishwacsena** [comment]
Fixed.
