### ISSUE TITLE
[PORT] support expression in debug evaluate

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2325]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3971

Following changes:
* support expression in debug evaluate
* output error for expression grammar
* output error for evaluation process
* treat null as normal output instead of error (since value could be null)
![image](https://user-images.githubusercontent.com/2876650/82629269-b9022200-9c21-11ea-94e0-7ac17c1312f0.png)

Blockers:
* https://github.com/microsoft/botbuilder-dotnet/issues/3970 fixes debugging
* https://github.com/microsoft/botbuilder-dotnet/issues/3969 then we could tell if it is a null value or non-exist value

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Debugging

**Comment by stevengum** [comment]
@luhan2017 can you triage this for JS Adaptive RC1?

**Comment by luhan2017** [comment]
@stevengum , we don't have a debug package in the JS yet, so this is not a valid issue, I think we can just close it.

**Comment by stevengum** [comment]
Thanks @luhan2017! closing issue as this work is not yet implemented in JS.
