### ISSUE TITLE
[Engineering] Create Azure DevOps .yaml pipeline for main CI

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#2331]
We should stop using Azure DevOps Classic Pipelines and switch to .yaml-based pipelines.

- [x] Create .yaml based pipeline
- [x] Refactor pipeline to more closely follow dotnet factoring (where applicable)
- [x] Create separate stages for runtime compatibility

@BruceHaley FYI

**Comment by BruceHaley** [comment]
Splitting the pipeline into multiple .yml files makes sense once we have 2 or more yaml pipelines that can share them.

**Comment by BruceHaley** [comment]
Should BotBuilder-JS-master-CI-node12 be converted as part of this issue?

**Comment by stevengum** [comment]
Yes please 😄 

The build steps I think should be separated out for reusability as well. The input to the build stage should include the Node.js runtime.

**Comment by stevengum** [comment]
Closing via #2487
