### ISSUE TITLE
[botbuilder-lg] [bug] Infinite Loop in Imports

### ISSUE THREAD

**Issue by juharris** [microsoft/botbuilder-js#2340]
## Versions
What package version of the SDK are you using. botbuilder-lg: 4.9.2
What nodejs version are you using v10.18.1
What browser version are you using
What os are you using WSL

## Describe the bug
Having two language generation files that import each other causes an infinite loop/exception.
It's not really the loop that concerns me, I assume this means that LG is reloading templates if I import a file twice throughout my structure so I'm concerned about the impact to loading time.

## To Reproduce
In this example, I get an exception but I can't even see the whole trace because it's so long. With my templates that I actually use where the circular imports might not be so direct, `parseFile` just hangs.
a.lg:
```Markdown
> Import b.lg
[b](./b.lg)
# a
- a
```

b.lg:
```Markdown
> Import a.lg
[a](./a.lg)
# b
- b
```

code.ts:
```TypeScript
import { Templates } from 'botbuilder-lg'
Templates.parseFile('a.lg')
```

## Expected behavior
Should not cause an infinite loop/exception.

[bug]

**Comment by joshgummersall** [comment]
@luhan2017 @chon219 is this still an issue?

**Comment by chon219** [comment]
> @luhan2017 @chon219 is this still an issue? If so please prioritize and categorize with labels. Thanks!

@boydc2014 @Danieladu could you please help verify it?

**Comment by Danieladu** [comment]
yes. We have discussed this issue in another thread. Personal think this issue can be marked as backlog.
