### ISSUE TITLE
[PORT] Fix build breaks on linux

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2359]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4073

* fixed path case mismatches
* disabled tests that are windows only.

# Changed projects
* Microsoft.Bot.Builder.AI.LUIS.Tests
* Microsoft.Bot.Builder.AI.QnA.Tests
* Microsoft.Bot.Builder.Dialogs.Declarative.Tests
* Microsoft.Bot.Connector.Tests
*

**Comment by joshgummersall** [comment]
Not applicable to JS repo.
