### ISSUE TITLE
[PORT] Add Adaptive Teams component

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2376]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4051

Fixes #3562 DCR to add teams support to composer 

* Added **Microsoft.Bot.Builder.Dialogs.Adaptive.Teams** package
* Added **TeamsComponentRegistration** to add component 
* Added appropriate .schema files

Defined trigger classes which respond to events that TeamsActivityHandler models.
* **OnTeamsAppBasedLinkQuery**
* **OnTeamsCardAction**
* **OnTeamsChannelCreated**
* **OnTeamsChannelDeleted**
* **OnTeamsChannelRenamed**
* **OnTeamsFileConsent**
* **OnTeamsMessagingExtensionCardButtonClicked**
* **OnTeamsMessagingExtensionConfigurationQuerySettingUrl**
* **OnTeamsMessagingExtensionConfigurationSetting**
* **OnTeamsMessagingExtensionFetchTask**
* **OnTeamsMessagingExtensionQuery**
* **OnTeamsMessagingExtensionSelectItem**
* **OnTeamsMessagingExtensionSubmitAction**
* **OnTeamsO365ConnectorCardAction**
* **OnTeamsTaskModuleFetch**
* **OnTeamsTaskModuleSubmit**
* **OnTeamsTeamRenamed**

This should light up composer with ability to respond to teams events.

# Changed projects
* Adapters
* AdaptiveExpressions
* Microsoft.Bot.Builder.AI.LUIS
* Microsoft.Bot.Builder.ApplicationInsights
* Microsoft.Bot.Builder.Azure
* Microsoft.Bot.Builder.Dialogs.Adaptive.Teams
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Debugging
* Microsoft.Bot.Builder.LanguageGeneration
* Microsoft.Bot.Builder.TemplateManager
* integration
* Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.Tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.TestBot.Json
*

**Comment by luhan2017** [comment]
@stevengum, I remembered that you wanted to take this item, could you confirm?

**Comment by mdrichardson** [comment]
@chon219 @stevengum Are either of you working on this? If not, I can take this one.

**Comment by chon219** [comment]
@mdrichardson Are you still working on this? I can take this one.

**Comment by mdrichardson** [comment]
@chon219 I am, yes! Should have it finished min-January, I think.

**Comment by chon219** [comment]
@mdrichardson Thanks, have you started working on this? I have made some progress under branch [adaptive-teams](https://github.com/microsoft/botbuilder-js/tree/adaptive-teams), hope this can be helpful.

**Comment by mdrichardson** [comment]
@chon219 Looks like you've done a TON of work on this! Do you just want the issue re-assigned to you? Have you done testing in Composer, yet?

**Comment by chon219** [comment]
@mdrichardson I have not tested this in composer, please feel free to cherry-pick my code into that PR. Thanks.
