### ISSUE TITLE
[PORT] Support luis customized endpoint

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2379]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4011

User would like to publish the luis to mooncake.
eg. chinaeast2 region is targeting https://chinaeast2.api.cognitive.azure.cn instead of https://${region}.api.cognitive.microsoft.com.

https://github.com/microsoft/BotFramework-Composer/issues/2986

# Changed projects
* Microsoft.Bot.Builder.AI.LUIS

**Comment by chon219** [comment]
We don't have `LuisExtensions` in JS right now, closing this one.
