### ISSUE TITLE
[PORT] fix expandText return type error

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2388]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4132

small fix. Fix `expandText` returntype error.

# Changed projects
* Microsoft.Bot.Builder.LanguageGeneration
* Microsoft.Bot.Builder.LanguageGeneration.Tests

**Comment by Danieladu** [comment]
fixed by #2387
