### ISSUE TITLE
[PORT] Add OnContinueConversation trigger and ContinueConversationLater action

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2393]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4063

* Add **PostActivityAsync** method to **BotFrameworkHttpClient** to make it easy to post secure EventActivity to your bot
* Add **OnContinueConversation** trigger
* Add **ContinueConversationLater** action to BotBuilder.Azure
* Add unit tests, etc.

# Changed projects
* Microsoft.Bot.Builder.Azure
* Microsoft.Bot.Builder.Dialogs.Adaptive
* integration
* Microsoft.Bot.Builder.Azure.Tests
* Microsoft.Bot.Builder.Tests
* 

[changes required]

**Comment by stevengum** [comment]
@luhan2017, @joshgummersall and I want to sync with you regrading this issue. We have some questions about the specific deliverables and their timeframe 😄
