### ISSUE TITLE
Bot receives old time zone information after client time zone has been changed (Teams)

### ISSUE THREAD

**Issue by matthiasdilger** [microsoft/botbuilder-js#2395]
(This is probably a Teams specific issue but I am not sure where to file this. If there is a better place, please point me to it. Thanks.)

## Versions
SDK 4.9
nodejs 12.16.3

## Describe the bug
When a user changes the device's time zone without restarting Teams the bot keeps receiving the old time zone until the Teams client has been restarted.

## To Reproduce
User is in time zone UTC+8 and sends message to bot.
Bot receives:
`rawLocalTimestamp: '2020-06-22T12:30:17.8951823+08:00'`
User changes time zone to UTC-6 on device without restarting the Teams client. Teams client updates the UI correctly (message timestamps change)
User sends new message to bot and bot receives the old time zone:
`rawLocalTimestamp: '2020-06-22T12:30:17.8951823+08:00'`

## Expected behavior
Bot should always receive the correct current client time zone information.

## Additional context
Client versions where problem was reproduced:
Teams client on Mac OS X 10.15.4
Teams web version on Chrome with Mac OS X 10.15.4

[bug]

**Comment by Wajeed-msft** [comment]
Internal Tracker: [Bug 1095875: Bot receives old time zone information after client time zone has been changed](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1095875)

**Comment by clearab** [comment]
This is a known issue that is unlikely to be fixed soon, due to engineering complexity. The workaround is to restart the Teams client, which will update the timezone that is sent. We'll continue to track this internally, and a future version of the product (the Teams client) may include this change.
