### ISSUE TITLE
Port missing LuisTelemetryConstants for 'topTwoIntents' from C#

### ISSUE THREAD

**Issue by mrestorff** [microsoft/botbuilder-js#2398]
**Is your feature request related to a problem? Please describe.**
Currently, we are only able to log the top scoring intent to AppInsights via the integrated TelemetryClient in the LuisRecognizer. 
In C#, there is the [option to pass TelemetryProperties](https://github.com/microsoft/botbuilder-dotnet/blob/5ce4870d52bc06ba1d3349a7fe94e28c9c24b8e3/libraries/Microsoft.Bot.Builder.AI.LUIS/LuisTelemetryConstants.cs#L15-L16) that enable the logging of both the top scoring intent and the second highest scoring intent. This is not yet implemented in botbuilder-js.

**Describe the solution you'd like**
Port the LuisTelemetryConstants `Intent2Property` and `IntentScore2Property` from the [C# luis telemetry constants](https://github.com/microsoft/botbuilder-dotnet/blob/5ce4870d52bc06ba1d3349a7fe94e28c9c24b8e3/libraries/Microsoft.Bot.Builder.AI.LUIS/LuisTelemetryConstants.cs#L15-L16).
To enable usage of those constants, the corresponding properties will also have to be defined in LuisRecognizer.fillTelemetryProperties(). This can also be [ported from the C# project](https://github.com/microsoft/botbuilder-dotnet/blob/5ce4870d52bc06ba1d3349a7fe94e28c9c24b8e3/libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs#L387-L388).

Also, the LuisTelemetryConstants are [currently not exported from the package](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-ai/src/index.ts). This would have to be mitigated as well in order to enable easy use of them.

**Describe alternatives you've considered**
The current workaround is to create a custom telemetry event and log those properties there. However, this is additional code and effort that would not be necessary if those LuisTelemetryConstants were implemented.

[enhancement]

**Comment by v-kydela** [comment]
I've identified the [PR](https://github.com/microsoft/botbuilder-dotnet/pull/1424) and the [commit](https://github.com/microsoft/botbuilder-dotnet/pull/1424/commits/9282d57f83957b5390227c08df721ca46b4a5d40) where this was implemented in C#. I'm unsure why no issue was made to port this before.

@srinaath - I messaged you and am awaiting instruction

**Comment by mdrichardson** [comment]
@jwiley84 Has volunteered to take the port. Assigning.

**Comment by jwiley84** [comment]
Acknowledging, as it seems assigning me to github issues is not working.

**Comment by jwiley84** [comment]
Hi @mrestorff Just wanted to let you know this is still on my plate. We're discussing it internally, and you should see a PR with the changes in a few days.  Thank you for your patience in this.

**Comment by compulim** [comment]
@jwiley84 I think this is still on your plate, right?

**Comment by jwiley84** [comment]
Yes.

**Comment by jwiley84** [comment]
Hi @mrestorff Still working on this with a goal to have completed by the weekend. Thank you for your patience!

**Comment by tsuwandy** [comment]
@jwiley84, any update on this?

**Comment by ninggao** [comment]
@jwiley84, revisit to this, any updates on this?

**Comment by joshgummersall** [comment]
@jwiley84 do you have any updates on this issue?
