### ISSUE TITLE
[PORT] Fix 3 functional test builds

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2406]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4163

Botbuilder-DotNet-Facebook-Functional-Tests-yaml
BotBuilder-DotNet-Webex-Functional-Test-yaml
BotBuilder-DotNet-Functional-Tests-Windows-yaml

All the above will now deploy the test bot. However, the last one has the failing test SendDirectLineMessage: "Assert.AreEqual failed. Expected:<Echo: Testing Azure Bot GUID: d882954f-e6dc-4c84-b370-60d146e4ebdc>. Actual:<Where would you like to travel to?>." Looks like it got CoreBot functionality when it was expecting EchoBot functionality.

**Comment by stevengum** [comment]
N/A
