### ISSUE TITLE
[PORT] Change deployment template endpoint to .../api/mybot from .../api/messages

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2411]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4167

This fixes the Windows functional test error "Assert.AreEqual failed. Expected:<Echo: Testing Azure Bot GUID: d882954f-e6dc-4c84-b370-60d146e4ebdc>. Actual:<Where would you like to travel to?>.".

**Comment by joshgummersall** [comment]
Not applicable to JS repo.
