### ISSUE TITLE
Yeoman generator downloads wrong version of SDK

### ISSUE THREAD

**Issue by KatiePro** [Microsoft/botbuilder-js#242]
Followed instructions here: https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0

In the repo with the source code, the wrong version of the bot builder SDK gets downloaded ("^4.0.0-preview1.1" rather than "^4.0.0-preview1.2").

FIX: Run npm install on that internal repo. Check in package.json that the botbuilder version has been updated to "^4.0.0-preview1.2"

ADDITIONAL ERRORS: Even then, the generated echo bot template comes with errors built in. They seem to be typical Typescript errors that devs face a lot, probably changing something in the auto-generated tsconfig.json file:

- node_modules/botbuilder-core/lib/turnContext.d.ts(143,24): error TS2304: Cannot find name 'Map'.app.ts(28,39): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

Changing "target" to "ES2015" in tsconfig.json does NOT solve the above error.

**Comment by Stevenic** [comment]
We will try to replicate this.

**Comment by sgellock** [comment]
Thanks for the feedback.  We will address this issue as part of our stable release.  For now, you can run 'npm I botbuilder@preview' to get the latest release.
