### ISSUE TITLE
Avoid @types/node usage in botframework-connector

### ISSUE THREAD

**Issue by axelsrz** [microsoft/botbuilder-js#2427]
Tracking issue for #1302 respecting botframework-connector library

**Comment by marecektn** [comment]
The `@types/node` has been moved to `devDependencies` for version 4.11 but moved back do `dependencies` in 4.12+
Can you please elaborate why? It is difficult for our project to update to 4.14 since node types are in conflict. 
Thank you.

**Comment by joshgummersall** [comment]
@marecektn generally `@types` packages should be listed in `dependencies` whenever they show up in published declaration files (`*.d.ts`). The `botframework-connector` package includes a reference to Node types here:

```typescript
connectorApi/models/index.d.ts
5:/// <reference types="node" />
68:     * Always undefined in node.js.
74:     * The response body as a node.js Readable stream.
```

You could investigate using [`yarn resolution`](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) or some other mechanism to override the version, or perhaps use `skipLibCheck` and `as any` where necessary to circumvent the issue.
