### ISSUE TITLE
[PORT] Revert "Fixes issue #3960 [QnAMaker] [DotNet] Implementing QnAMaker's precise answering capability as an additional feature for BotFramework users"

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2430]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4170

Reverts microsoft/botbuilder-dotnet#3935

Reverting changes that include a preview feature of QnA Maker. 

# Changed projects
* Microsoft.Bot.Builder.AI.QnA
* Microsoft.Bot.Builder.AI.QnA.Tests

**Comment by mrivera-ms** [comment]
The associated PR in the dotnet repo was [reverted in PR4170](https://github.com/microsoft/botbuilder-dotnet/pull/4170), but the implementation was not ported to JS. We do not need this port at this point.
