### ISSUE TITLE
Increase coverage for botbuilder library

### ISSUE THREAD

**Issue by axelsrz** [microsoft/botbuilder-js#2432]
Increase unit test coverage of botbuilder package to 80%

**Comment by cleemullins** [comment]
Consider for Southworks to complete.

**Comment by denscollo** [comment]
We divided the issue into the existing classes in which we'll increase the CC, and create a PR for each one.

This is the list and its status:
#2484 ChannelServiceHandler
#2485 InspectionMiddleware
BotFrameworkAdapter
BotFrameworkHttpClient
TeamsInfo
TeamsActivityHandler
StatusCodeError
ChannelServiceRoutes

**Comment by axelsrz** [comment]
Closing due to complition.
