### ISSUE TITLE
baseUri should be optional for ConnectorClientOptions

### ISSUE THREAD

**Issue by amir-microsoft** [microsoft/botbuilder-js#2439]
## Versions
NodeJS v10.15.3
BotBuilder NodeJS SDK v4.9.2
My app is written is typescript

## Describe the bug
When Using customized ConnectorClientOptions for BotFrameworkAdapterSettings, the baseUri is required, but passing a value for it causes the sdk to stop working - bot is unable to send messages

## To Reproduce
const botFrameworkAdapterSettings: BotFrameworkAdapterSettings = {
  appId,
  appPassword,
  clientOptions: { baseUri: undefined, httpClient: new CustomAxiosHttpClient() }
};
const adapter: BotFrameworkAdapter = new BotFrameworkAdapter(botFrameworkAdapterSettings);

## Expected behavior
The baseUri should be optional at the very least, that will allow me to omit it, and still being able to transpile my typescript app without errors

**Comment by stevengum** [comment]
This was a bad one, thanks @EricDahlvang for fixing it.
