### ISSUE TITLE
[PORT] properly escape slashes in constant strings with StringExpression/ValueExpression

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2443]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4194

Fixes #4192 
 
## Description
When encoding a string as an expression we need to properly handle slash.

## Testing
* tests updated to validate round-trip slashes

# Changed projects
* AdaptiveExpressions
* AdaptiveExpressions.Tests

**Comment by mrivera-ms** [comment]
Per @boydc2014 , this will be taken for R10.
