### ISSUE TITLE
[PORT] Add missing code docs for Configuration lib

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2444]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4190

Towards #4052.

Adds missing code docs for configuration library.

Also removes the suppression of CS1309 as part of microsoft/botframework-sdk#5933

# Changed projects
* Microsoft.Bot.Configuration

**Comment by joshgummersall** [comment]
TODO: mark npm package as deprecated.

**Comment by joshgummersall** [comment]
Related: https://github.com/microsoft/botbuilder-js/issues/2436
