### ISSUE TITLE
[PORT] Add logging to BotFrameworkHttpClient.PostActivityAsync()

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2449]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4134

Fixes #3823

# Changed projects
* integration

**Comment by mdrichardson** [comment]
@gabog @mrivera-ms 

Does this *need* to be ported? Our JS SDK's [`botFrameworkHttpClient` doesn't have a logger](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/botFrameworkHttpClient.ts#L36) (and also doesn't log anything to the `console`), which is what [the original PR](https://github.com/microsoft/botbuilder-dotnet/pull/4134) changes:

![image](https://user-images.githubusercontent.com/40401643/93378899-ecd90700-f811-11ea-8f88-95fe78bc2bdb.png)

**Comment by gabog** [comment]
NA for JS, closing.
