### ISSUE TITLE
Increase coverage for dialogs-adaptive library

### ISSUE THREAD

**Issue by axelsrz** [microsoft/botbuilder-js#2450]
Increase unit test coverage of dialogs-adaptive library to 80%

**Comment by cleemullins** [comment]
@luhan2017 @chon219 This item has seen no forward progress in ~45 days. I've pushed this to R11, but we would like to see this move forward.

**Comment by chon219** [comment]
> @luhan2017 @chon219 This item has seen no forward progress in ~45 days. I've pushed this to R11, but we would like to see this move forward.

Hi, we are already working on this and we've already sent out a PR related to this issue: https://github.com/microsoft/botbuilder-js/pull/2659

And we will send out several PRs in the future to increase test coverage of `botbuilder-dialogs-adaptive`.
