### ISSUE TITLE
[PORT] fix for OnUnknownIntent title.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2486]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4229

Fixes #3959 

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive

[Adaptive,R10]

**Comment by chon219** [comment]
We don't have this in JS, closing this issue.
