### ISSUE TITLE
Out of call volume quota.

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/botbuilder-js#249]
I have followed this [document](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=jsaddref%2Cjsbotconfig#integrate-multiple-luis-apps-and-qna-services-with-the-dispatch-tool)  and implemented a BOT exactly as mentioned. I am seeing following error in VS code console.

```
BotFrameworkAdapter.processActivity(): 500 ERROR - Error: Out of call volume quota. Quota will be replenished in 7.02:41:23.
botFrameworkAdapter.ts:404
(node:92108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Out of call volume quota. Quota will be replenished in 7.02:41:23.
```

**Comment by Stevenic** [comment]
This an error from another component (most likely QnA maker) that's leaking down to the adapter. We'll need to discuss what's the right thing to do here.

**Comment by rjgmail88** [comment]
Thanks.

**Comment by vishwacsena** [comment]
The fix for this will be available in the next release. You will have a global error handler that you can use to catch issues before they bubble all the way up the stack.
