### ISSUE TITLE
Wrong JSON Serialization

### ISSUE THREAD

**Issue by sahithikkss** [microsoft/botbuilder-js#2509]
https://github.com/microsoft/botbuilder-js/blob/fd3e25fcabc54ac9edb591c56a5774481b2ea874/libraries/botbuilder-ai/src/qnaMakerDialog.ts#L316

**Comment by Virtual-Josh** [comment]
@stevkan  please route to the right person.

**Comment by Zerryth** [comment]
Would love to help, but @sahithikkss could you please provide additional information and state explicitly what you  mean by there's wrong JSON serialization? Don't have enough information to help currently.

**Comment by sahithikkss** [comment]
`records` is already in the format of `FeedbackRecords,` so need not be wrapped in {feedbackRecords: records}

`                await this.getQnAClient().callTrainAsync(records);
`
breaks trainAPI requests in active learning.

**Comment by sahithikkss** [comment]
Below issue lands on the correct line number. So, closing this issue.
https://github.com/microsoft/botbuilder-js/issues/2518
