### ISSUE TITLE
LUIS Dispatch Bot sdk V3 support?

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/botbuilder-js#251]
Is it possible to create LUIS Dispatch for existing V3 Bot ? We have v3 bot that's in production and we have gone so far now so its difficult to switch over v4 Bot. However, there are awesome capabilities like LUIS dispatch tool that we would like to leverage.

Ref:- [https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=jsaddref%2Cjsbotconfig#integrate-multiple-luis-apps-and-qna-services-with-the-dispatch-tool](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=jsaddref%2Cjsbotconfig#integrate-multiple-luis-apps-and-qna-services-with-the-dispatch-tool)

**Comment by rjgmail88** [comment]
Any update on this ?

**Comment by Stevenic** [comment]
@CezaryMarcjan can you help answer this?

**Comment by CezaryMarcjan** [comment]
Yes. The dispatch CLI produces a LUIS model which can be used by V3 bot as any other LUIS model. Please keep in mind that dispatcher is not GA yet (it is pre-release).
