### ISSUE TITLE
[PORT] Added null checks in telemetry logger middleware

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2516]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4248

Fixes #4247

# Changed projects
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Tests

**Comment by stevengum** [comment]
Duplicate of https://github.com/microsoft/botbuilder-js/issues/2274.

#2274 will be closed by https://github.com/microsoft/botbuilder-js/pull/2434
