### ISSUE TITLE
Wrong JSON Serialization

### ISSUE THREAD

**Issue by sahithikkss** [microsoft/botbuilder-js#2518]
https://github.com/microsoft/botbuilder-js/blob/d79b10b3997fef42a22617601913ed68022a6390/libraries/botbuilder-ai/src/qnamaker-utils/trainUtils.ts#L49

```
 var payloadBody = JSON.stringify({
            feedbackRecords: feedbackRecords
        });
```

`feedbackRecords`  is already in the format of FeedbackRecords, so need not be wrapped in `{feedbackRecords: records}` for serialization.

This breaks trainAPI requests in active learning as bad http request.

**Comment by Zerryth** [comment]
@sahithikkss it appears you're right about the the SDK malforming the request to QnA Maker. 

Looking at the QnA Maker [docs ](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/improve-knowledge-base)on Train API:

```http
POST https://<QnA-Maker-resource-name>.azurewebsites.net/qnamaker/knowledgebases/<knowledge-base-ID>/train
Authorization: EndpointKey <endpoint-key>
Content-Type: application/json
{"feedbackRecords": [{"userId": "1","userQuestion": "<question-text>","qnaId": 1}]}
```

We see the shape that it is expecting for `feedbackRecords` is the array of records itself.
We really should be sending `{ "feedbackRecords": feedbackRecords.feedbackRecords}` to the Train API, as the `{}` is meant to be the payload body, and who knows if in the future if the QnA team decide to add optional properties that we could send in the payload body--in which case we'd need the `{}` to be there.

We'll have the fix up within this milestone. Thanks for raising the issue!
