### ISSUE TITLE
Entity properties given inconsistent array nesting in LuisRecognizerOptionsV2

### ISSUE THREAD

**Issue by amvanmaren** [microsoft/botbuilder-js#2521]
## Versions

botbuilder: 4.6.2",
botbuilder-ai: 4.6.2
nodejs: 10.16.3
OS: Windows

## Describe the bug
If a property that is an array is to be added via the LuisRecognierOptionsV2 addProperty method, the array is inconsistently destroyed or kept.  
They array holding the value is kept if the property is a new property.  If the key value of the property is not found on the object, the property will be added and the array holding the new value will be kept, resulting in a nested array at index 0.  (line 335 of LuisRecognizerOptionsV2).
The array is destroyed if the property key is already found to be present on the object.  Here, the concat method merges both arrays resulting in the loss of the array that held the value to be added.  (line 333 of LuisRecognizerOptionsV2)

The final result:  Property values that are held in arrays and added via this addProperty method will result in a nested array at index 0 and simple values being stored at all other indices.   The problem is shown in Screenshot 1.

## To Reproduce
1.  For this output data from our LUIS model:  {
  "query": "who is alexander van maren smith",
  "topScoringIntent": {
    "intent": "UserInfo",
    "score": 1.0
  },
  "intents": [
    {
      "intent": "UserInfo",
      "score": 1.0
    },
    {
      "intent": "None",
      "score": 2.42741339E-06
    },
    {
      "intent": "WhoOwnsWhat",
      "score": 6.58162833E-07
    }
  ],
  "entities": [
    {
      "entity": "alexander",
      "type": "PersonName",
      "startIndex": 7,
      "endIndex": 15,
      "score": 0.9996592,
      "role": "First"
    },
    {
      "entity": "van",
      "type": "PersonName",
      "startIndex": 17,
      "endIndex": 19,
      "score": 0.997405648,
      "role": "Last"
    },
    {
      "entity": "maren",
      "type": "PersonName",
      "startIndex": 21,
      "endIndex": 25,
      "score": 0.855693936,
      "role": "First"
    },
    {
      "entity": "smith",
      "type": "PersonName",
      "startIndex": 27,
      "endIndex": 31,
      "score": 0.9425993,
      "role": "Last"
    },
    {
      "entity": "alexander van maren smith",
      "type": "builtin.personName",
      "startIndex": 7,
      "endIndex": 31
    },
    {
      "entity": "alexander",
      "type": "PersonFName",
      "startIndex": 7,
      "endIndex": 15,
      "resolution": {
        "values": [
          "Alexander"
        ]
      }
    },
    {
      "entity": "van",
      "type": "PersonFName",
      "startIndex": 17,
      "endIndex": 19,
      "resolution": {
        "values": [
          "Van"
        ]
      }
    },
    {
      "entity": "alexander",
      "type": "PersonLastName",
      "startIndex": 7,
      "endIndex": 15,
      "resolution": {
        "values": [
          "Alexander"
        ]
      }
    },
    {
      "entity": "smith",
      "type": "PersonLastName",
      "startIndex": 27,
      "endIndex": 31,
      "resolution": {
        "values": [
          "Smith"
        ]
      }
    },
    {
      "entity": "who is",
      "type": "UserInfoIntentSynonyms",
      "startIndex": 0,
      "endIndex": 5,
      "resolution": {
        "values": [
          "UserInfo"
        ]
      }
    }
  ]
}

2. Use this LUIS response as and try to extract the PersonFName and PersonLastName entities from this after being processed by the LuisRecognizerV2.  

## Expected behavior
The nesting of arrays should be consistent, regardless of which index a value is being held at.  
Arrays to be added should either be consistently destroyed or kept, regardless if they are new property keys or not.
My proposed solution is shown in Screenshot2.
The other possible solution that would keep the array holding a property value, would need to avoid the use of the concat method.

## Screenshots
Screenshot1: 
Here is a screenshot of the inconsistent nesting of a property's values resulting from arrays being concatenated.  
![image](https://user-images.githubusercontent.com/68241330/87333634-03f23480-c503-11ea-899d-0fcb42f86e2f.png)

Screenshot2:
Here is a screenshot for my suggested fix which will result in the array being consistently destroyed for a value stored at index 0.
![image](https://user-images.githubusercontent.com/68241330/87333271-85959280-c502-11ea-8552-a0a6a22443d1.png)

Screenshot3:
Using the solution from Screenshot2, the object consistently concatenates the arrays resulting in a consistently nested object: 
![image](https://user-images.githubusercontent.com/68241330/87333976-90045c00-c503-11ea-82cc-bea8159db77b.png)

## Additional context
We are currently blocked because of this, what is the proposed solution?  

[bug]

**Comment by compulim** [comment]
@munozemilio Please take a look at this one.

**Comment by munozemilio** [comment]
Hello @amvanmaren I will include this as part of our next release. Thanks for reporting.

**Comment by EricDahlvang** [comment]
@munozemilio  Should this be labeled R11?

**Comment by carlosscastro** [comment]
Yes, this will ship in R11 .

**Comment by joshgummersall** [comment]
Thank you for the detailed and complete bug report. This is an unfortunate scenario where we have a clear bug that has existed in the SDK for long enough to be effectively grandfathered in. The likelihood of this bugfix negatively affecting existing customers means that our hands are tied.

The `LuisRecognizerV3` implementation does not appear to contain the same bug, so I hope it's tractable to move to the newer implementation. If you feel that this is not possible, please reopen the issue to discuss other options.
