### ISSUE TITLE
[PORT] SkillHandler should forward resourceResponse

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2525]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4264

Fixes #4072 

(and starts on the end to end test bot consolidation)

# Changed projects
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Tests
* Skills

**Comment by johnataylor** [comment]
The JavaScript looks good here.
