### ISSUE TITLE
Track key unhandled DialogEvents in telemetry

### ISSUE THREAD

**Issue by garypretty** [microsoft/botbuilder-js#2529]
SDK tracking issue microsoft/botframework-sdk#5861

Send a trace activity and log a trace event via the telemetry client for 'versionChanged' and 'error' dialog events.

.NET PR https://github.com/microsoft/botbuilder-dotnet/pull/4270

**Comment by mrivera-ms** [comment]
@luhan2017 and @chon219 , could you please let us know if this is on track to be done in R10? Thank you.

**Comment by chon219** [comment]
> @luhan2017 and @chon219 , could you please let us know if this is on track to be done in R10? Thank you.

We already have a PR and I think it is ready to be merged, @stevengum can you verify that? Thanks.
