### ISSUE TITLE
continueConversation() does not match the C# SDK

### ISSUE THREAD

**Issue by navzam** [Microsoft/botbuilder-js#253]
In the C# SDK, `ContinueConversation` takes the bot's ID as a parameter, which is "critical to the BotFrameworkAdapter which is multi-tenant aware" (from [here](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs#L170)):
```
public virtual Task ContinueConversation(string botId, ConversationReference reference, Func<ITurnContext, Task> callback)
```

`continueConversation` in this Node SDK does NOT take the bot's ID as a parameter (from [here](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/botAdapter.ts#L47)):
```
public abstract continueConversation(reference: Partial<ConversationReference>, logic: (revocableContext: TurnContext) => Promiseable<void>): Promise<void>;
```

**Comment by Stevenic** [comment]
The BotId should be in the conversation reference. It's `reference.bot.id`. Is there another Bot Id you're looking for?  

It's a valid point that they're out of alignment.

**Comment by navzam** [comment]
I assume it's wanting the app ID, based on some of the C# samples that retrieve it:

```
// The BotFrameworkAdapter sets the identity provider on the context object.
var claimsIdentity = context.Services.Get<IIdentity>("BotIdentity") as ClaimsIdentity;

// For requests from a channel, the app ID is in the Audience claim of the JWT token.
// For requests from the emulator, it is in the AppId claim.
// For unauthenticated requests, we have anonymouse identity provided auth is disabled.
// For Activities coming from Emulator AppId claim contains the Bot's AAD AppId.
var botAppIdClaim =
    (claimsIdentity.Claims?.SingleOrDefault(claim => claim.Type == AuthenticationConstants.AudienceClaim)
    ?? claimsIdentity.Claims?.SingleOrDefault(claim => claim.Type == AuthenticationConstants.AppIdClaim));
```

But the C# sample also has notes like this
> The GetAppId method is a work around to enable proactive messaging in the .NET SDK.

so now I'm unsure which SDK needs to match the other.

**Comment by Stevenic** [comment]
So the real issue is the C# SDK supports multiple bots from within a single adapter which is why they need that ID passed in. The thing is it's rare that you will ever have multiple bots so the Node SDK just has you create a new adapter for each bot. I believe the plan is to change the C# SDK to work the way the Node SDK works. Not the other way around.
