### ISSUE TITLE
SDK Documentation: remove or improve emitEvent method in DialogContext class documentation (javascript v4)

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/botbuilder-js#2548]
[referring to this article in the documentation](https://docs.microsoft.com/en-us/javascript/api/botbuilder-dialogs/dialogcontext?view=botbuilder-ts-latest#emitevent-string--any--boolean--boolean-)

I came across this trying to solve [my question in SO](https://stackoverflow.com/questions/62894797/bot-framework-v4-node-js-how-to-go-to-next-waterfall-step-based-on-external-tri). I need to be able to move to the next waterfall step when triggered by an enternal event.

I guess this is adaptive dialog functionality that by accident ended up in the 'normal' botbuilder dialog section
If not, could you please improve the documentation. For instance with an example how to catch the emitted event.

Thank you

**Comment by munozemilio** [comment]
@garypretty could you please take a look at this one?

**Comment by garypretty** [comment]
@HesselWellema thank you for raising this issue. Yes, the emitEvent method is for use within adaptive dialogs which, as you are seeing, have some of the related classes within the Bot.Builder.Dialogs library.  We can certainly look to update the reference documentation to make this clearer.  For your information, you can read more about using events within adaptive here https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-dialog-triggers?view=azure-bot-service-4.0

**Comment by jwiley84** [comment]
@HesselWellema Did the link Gary posted answer your question?

**Comment by HesselWellema** [comment]
Tnx
