### ISSUE TITLE
Title for conversation-update-es6 sample isn't clear

### ISSUE THREAD

**Issue by tessmichi** [Microsoft/botbuilder-js#255]
When users new to the bot framework look for how to add a welcome message, the title of this sample will not trigger that this is the answer to their question unless they know that "conversation update" is the activity type they're looking for.

Additionally, in this sample, there is a comparison of the name of the added user to ignore "Bot," but there should at least be a comment here stating that the bot's "name" will not always be "Bot." As a matter of fact, it will only really be "Bot" when using the emulator.

**Comment by Stevenic** [comment]
Thanks we're reviewing our samples.

**Comment by sgellock** [comment]
Addressed in the v4 Samples refresh
