### ISSUE TITLE
TurnContext.updateActivity fails silently when invalid activity id supplied

### ISSUE THREAD

**Issue by kavins14** [microsoft/botbuilder-js#2550]
## Versions
What package version of the SDK are you using: 4.7.1
What nodejs version are you using: v12.16.3
What browser version are you using: N/A
What os are you using: Windows 10

## Describe the bug
[`TurnContext.updateActivity`](https://docs.microsoft.com/en-us/javascript/api/botbuilder-core/turncontext?view=botbuilder-ts-latest#updateactivity-partial-activity--) fails silently when an invalid activity id is supplied. 
## To Reproduce
1. Set up a working bot framework nodejs applicaton.
2. Call `TurnContext.updateActivity` with invalid activity id.

## Expected behavior
If the `TurnContext.updateActivity` method failed it should throw an error or give some kind of feedback to work with. It would be nice to know if the operation failed (or succeeded) so I can proceed with a fallback.

## Screenshots
Here's a code snippet that fails silently when run: 
![image](https://user-images.githubusercontent.com/18351436/87962784-c141d680-ca85-11ea-8e89-1c5bc775163e.png)
Note that the method doesn't return anything either.

[bug]

**Comment by munozemilio** [comment]
@stevengum can you please assign this to the right person?

**Comment by kavins14** [comment]
Awaiting the method call like this: `await context.updateActivity({...})` fixed it
