### ISSUE TITLE
[PORT] Add installation update to ActivityHandler

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2551]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4294

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/4287

# Changed projects
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Tests

**Comment by EricDahlvang** [comment]
separate issue tracking this already
