### ISSUE TITLE
Support for using TeamsInfo without a TurnContext

### ISSUE THREAD

**Issue by brycepolly** [microsoft/botbuilder-js#2556]
**Is your feature request related to a problem? Please describe.**
I'm in the process of porting Polly over from v3 to v4 botbuilder for Teams, and this is a bit of a stumbling block.  We do mostly  out of band communication and api calls for our application into Teams where we do not have a TurnContext to supply to the  TeamsInfo static methods for api calls.  

**Describe the solution you'd like**
Overload method for all the api calls that just takes the params required to make the call.  Looking into TeamsInfo it mostly uses the TurnContext for the service url, conversation id, and the adapter for credentials which can be easily supplied directly to the method calls.

**Describe alternatives you've considered**
I'm currently going to just extract all the internals of TeamsInfo out into our own helper class to do these calls as described above for our application as needed.

[enhancement]

**Comment by EricDahlvang** [comment]
Hi @brycepolly 

Thank you for raising this enhancement request.  However, the TeamsInfo helper is intended to be used from within the bot while processing a message, not for out of band processing.

Apart from duplicating the code, another option is to construct a ConversationReference with the necessary fields, and call adapter.ContinueConversation ...then within the callback you will have access to the context and can use the TeamsInfo as is.

**Comment by brycepolly** [comment]
Thanks, unfortunate to hear but I have already abstracted the `TeamsActivityHandler` and combined in the functionality of `TeamsInfo` into it so that its usable for us, so not blocked at least.   

The structure of `adapter.continueConversation` seems to not really be async-await and uses a callback instead (even though it returns a promise?), which makes it difficult to work with for error handling forcing me to wrap the entire usage of it in a new Promise in a helper methods to not deal with that throughout our code.

Example
```
    const result = await new Promise<void>((resolve, reject) => {
      this.adapter.continueConversation(conversation, async t1 => {
         try {
            const updateResult = await t1.updateActivity(updateActivity);
            resolve(updateResult);
         } catch(e) {
            reject(e);
         }
      });
    });
```

Ideally I would just await the `continueConversation` and get back the turn context;
```
const conversationTurnContext = await adapter.continueConversation(conversationInfo);
const updateResult = await conversationTurnContext.updateActivity(foo);
```

**Comment by EricDahlvang** [comment]
This is a reasonable request and useful in some scenarios.  However, we do not have plans to update the sdk with these helper methods. As such we recommend you use this in your own code. 

Closing the issue
