### ISSUE TITLE
Conversation update sample not working

### ISSUE THREAD

**Issue by michhar** [Microsoft/botbuilder-js#256]
Ran the conversation update sample (https://github.com/Microsoft/botbuilder-js/tree/master/samples/conversation-update-es6) and it gave this error:

C:\Users\michhar.REDMOND\Documents\bin\github\botbuilder-js\samples\conversation-update-es6\app.js:24
            await context.sendActivity(`Hello "${context.activity.membersAdded[0].name}"!`);
            ^^^^^

Seems it needs the 'async' specification for this function. 

`adapter.processActivity(req, res, async (context) => {`

**Comment by Stevenic** [comment]
Thanks.
