### ISSUE TITLE
Change AdaptiveExpressions pre-built classes from Public to Internal

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#2560]
"parent" issue first filed in https://github.com/microsoft/botbuilder-dotnet/issues/4312, related to https://github.com/microsoft/botbuilder-js/issues/2559

> Built in functions folder in AdaptiveExpressions library.
> 
> [bug]
>
> [Comment](https://github.com/microsoft/botbuilder-dotnet/issues/4312#issue-663900889) @EricDahlvang 

@boydc2014 @chrimc62 can we prioritize this for R10?

Any currently public prebuilt functions/classes we should make internal, and this would be a **breaking change**.

We should sync with the Adaptive Cards team to verify that we don't make internal any public functions they're using.

**Comment by boydc2014** [comment]
thanks @stevengum , i will follow up with AdpativeCards for this, sorry i missed this one earlier, somehow the dotnet one didn't showup in my query used in Kamran's report.

**Comment by boydc2014** [comment]
I just chatted with AdaptiveCards folks, they are directly refering any specific function implementation right now, what they refer, besides expression class, is ExpressionType class which is a table of string constants. So it's safe for us to make the implementation internal.

**Comment by boydc2014** [comment]
C# one is merged, we will proceed on this one, and expected to be closed soon.
