### ISSUE TITLE
Entity should allow custom fields

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-js#2561]
## Versions
4.n

## Describe the bug
Entity type should allow custom fields:
https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#entity

The mapper is currently stripping custom Entity fields.

## Additional context
From @stevengum 👍

Ideally, our Entity interface should look like the following:
![image](https://user-images.githubusercontent.com/11055362/88213732-faa54e00-cc0d-11ea-9886-94182f1c3c41.png)

The corresponding mapper should also support the updated interface.

___

Alternatively, any Mapper that references the Entity CompositeMapper (i.e. SemanticAction and Activity CompositeMappers) should replace the current the Composite type “Entity” with the autorest equivalent of OpenAPI’s “allOf” while using “Entity” and “Object” Mappers.
 
As an example, the Activity’s entities property would then be defined as such in the interface:
 
![image](https://user-images.githubusercontent.com/11055362/88213817-16105900-cc0e-11ea-84cc-2459e751c214.png)

 

[bug]

**Comment by stevengum** [comment]
This is a bug for not following the botframework-activity spec and therefore an unintended breaking change for v3-to-v4 users who consume and send `Entity` over the wire.

**Comment by mrivera-ms** [comment]
@stevengum , do we still have time to take this for R10?
