### ISSUE TITLE
Identify and communicate supported JavaScript environments for Adaptive, LG and Declarative libraries

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#2565]
- [ ] Readmes for each library clearly states the supported environments (i.e. Node.js, browser)
- [ ] ~main README.md~ _`libraries/README.md`_ has table indicating supported environments

@chrimc62, @stevenic, @luhan2017, @boydc2014 FYI

I'm placing this in R11, but it's a P0 before the Adaptive/Declarative Dialog libraries go GA.

Any changes to a specific library to support required environments (e.g. adaptive-expressions) should be tracked in separate issues.

**Comment by stevengum** [comment]
Pushing out to R12, initial libraries/README.md work completed in https://github.com/microsoft/botbuilder-js/pull/2900

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. Closing as Not Needed.
