### ISSUE TITLE
[PORT] Set qna answer startIndex and endIndex

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2566]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4292

Fixes #4227  

## Specific Changes

  - 
  -
  -

## Testing

# Changed projects
* Microsoft.Bot.Builder.AI.QnA
* Microsoft.Bot.Builder.AI.QnA.Tests

**Comment by luhan2017** [comment]
The qna recognizer stuff will be blocked without this feature. so mark it as P0
