### ISSUE TITLE
Bot NodeJS 4.9.2 slowness and stop to answer

### ISSUE THREAD

**Issue by DanielTizon** [microsoft/botbuilder-js#2570]
## Versions
What package version of the SDK are you using. 
botbuilder 4.9.2

What nodejs version are you using
12.13.0

What browser version are you using
Firefox 78.0.2

What os are you using
Mac OS 10.15.6

## Describe the bug
Production Bot is not responding some times, and it is random, it happens sometimes even when you are doing the same actions. It is showing DirectLine errors in channel tab:

Hora | Mensaje | Id. de correlación
-- | -- | --
24/7/2020 10:09:17 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|e5d2d1c6698b0a43b0b7a6ebb33b7ba9.d74c17a6_d74c17aa_
24/7/2020 10:07:32 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|b09b8f4e5a479e419544c4fe0a0b201e.7a52f179_7a52f17a_
24/7/2020 10:07:28 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|312311809f0e1443981b7ab9d3874494.5f1b5420_
24/7/2020 10:07:26 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|8462f23ba89e104199853a3e0113dd83.b8df819e_b8df81a0_
24/7/2020 10:07:12 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|7f19e162019e6f4587c900a5441c0aae.686a0eb4_
24/7/2020 10:06:48 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|f1e47e5f7df2384d8871bded71bea265.3125e0a3_
24/7/2020 10:06:41 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|ad5a916f048b5f43943a6a259fc132d7.b9f57fd4_b9f57fd6_
24/7/2020 10:06:17 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|940436ede457a642bb4c63433cfe0c07.74734057_74734058_
24/7/2020 10:05:55 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|1fcfbfe06c23e14288483465e75d6822.99a51853_99a51858_
24/7/2020 10:05:40 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|632f185749842a4892c1f0dfcf8adb6e.71c9a8ce_71c9a8d0_
24/7/2020 10:05:21 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|8b41d11ffc9d094bb2351995fec33c73.b9f56c42_
24/7/2020 10:04:52 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|d03dad1d1f760843b6bdbc126a496bc3.4d72b749_
24/7/2020 10:03:29 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|d35b75e49c20dc4d99109c0a0ccd0fdd.71c99253_
24/7/2020 10:02:59 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|0b827c7655df8d41acd60ed5cdc3f825.4d72a2e2_
24/7/2020 10:02:23 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|0d409559cd5419488987cd70d04de339.7a52a4a4_
24/7/2020 10:01:09 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|f908c68696d2f9489914948b5a4d9da6.2eecb273_
24/7/2020 10:01:01 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|7464143468584243b8d54943178dd18d.9d58b9c9_
24/7/2020 10:00:56 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|876f2d5e3ef2944badd9be23d844cb3f.61975a2a_
24/7/2020 9:58:26 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|1b969dd91f33da40be9bdb467d60843b.2eec8a63_
24/7/2020 9:57:51 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|02d1542e50e5ce45a7f0b05d979c6f98.7a5262f9_7a5262fa_

## To Reproduce
Go to the webchat, and say "Mostrar Ayuda", and sometimes it doesnt show any message. Other times, it doesnt show some suggested actions, and so on.

## Expected behavior
The bot works correctly and it doesn't stop to answer randomly

## Additional context
We updated recently to botbuilder 4.9.2, and we have tried to update to 4.9.3 and we still have slowness problems and bot doesn't answering some times. 

[bug]

**Comment by dmvtech** [comment]
Do you have a reproduction of this issue? Can you share a repository of the repro (sanitized of personal information/keys/etc)?  What channels does it reproduce in? Are you testing using `Test in Web Chat` or 'full' Web Chat? Does it reproduce in Emulator?

**Comment by DanielTizon** [comment]
Well, like I said, it happens randomly, so you only need to speak with the bot, and sometimes it fails with the first messagge and other times, it happens after 4-5 messagges. We use DirectLine channel with Web Chat v4.6. And we have started to see this message after update botbuilder/botbuilder-azure/botbuilder-dialogs/botframework-connector to v4.9.2. And we have upgraded to 4.9.3 and we are facing to the same problems.

Anyways, we continue getting this problems in the Directline channel tab, so it looks clear that messagges are not getting correctly sent to my bot.


Hora | Mensaje | Id. de correlación
-- | -- | --
25/7/2020 8:12:14 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|2b306c8fe27ab74997d3ca637c58cdd5.9d9a6a6_
25/7/2020 7:55:50 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|dfb7e6e2b1b07644982ff97e63722e93.666b4aae_666b4ab0_
25/7/2020 7:55:01 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|eb20c1d72a99ac4e8abeecf8c5cbd2f8.746a14d3_
25/7/2020 7:42:24 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|4c4f143f6206ff4ba51899ed7f6399b1.e2081289_e208128a_
25/7/2020 7:33:48 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|40bd0a0c78c83948b0dfc8e245c39ef8.ca1b993a_
25/7/2020 6:49:55 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|a07fd1fbbc019f4fb8ce344c1f191138.aa54ecbe_
25/7/2020 6:45:58 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|520e052530baec40ae2b85e2968ac06b.4c944368_
25/7/2020 6:33:43 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|ebd0d91e6fcf884598011cc2b032076b.beb276b0_
25/7/2020 6:16:13 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|5c30ee538121354784ab3adff6775b1f.cdcffb2c_cdcffb2d_
25/7/2020 6:15:42 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|a482d59494edfd428f78773ae85f6999.4e0086ef_4e0086f1_
25/7/2020 6:03:35 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|791a9fce0b67a948b2239dab697392e5.5a12f01b_
25/7/2020 5:54:50 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|a7d87120992c7649b50d887ce40c1a7c.4090981a_
25/7/2020 5:47:22 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|79c0a2e011f66d4ba7c1b5b048b6e272.3d3d8eff_
25/7/2020 5:45:17 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|1268eec52e7df3439345ea34ebf293f7.cdcf0550_
25/7/2020 4:59:44 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|2351d11602a0ce44925fe6e3b039f565.1e8c833e_1e8c833f_
25/7/2020 4:59:24 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|0ac953872d7cbb4c8e54647a057a25ba.4c8b67c0_4c8b67c1_
25/7/2020 4:55:34 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|1615269ac923e246897afdcb380a9168.9cbd85e_9cbd85f_
25/7/2020 2:44:53 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|1812bddcf95bdb4590986e60b0a92d9b.235a66c0_
25/7/2020 1:40:33 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|3bda67fcd517894aba46a5121236f10e.3d31fa23_
25/7/2020 1:10:33 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|2187abcdc904fe4dbe02e736f8b81c15.7a78570b_

**Comment by DanielTizon** [comment]
And I want add that we are using custom axios http client, because a microsoft tech recommended it for a Random ECONNRESET problem that we were having:

https://github.com/microsoft/botbuilder-js/issues/2054

**Comment by DanielTizon** [comment]
I have updated to @azure/ms-rest-js 2.0.8, is it the best version for botbuilder 4.9.3??

**Comment by dmvtech** [comment]
Where does the bot code run? Is it in Azure or on-prem location? Although it doesn't happen consistently, can you reproduce this issue locally? Meaning running the bot on a development/testing machine and reproduce the issue (at all)?

ms-rest-js 2.0.8 should be fine.

**Comment by DanielTizon** [comment]
The bot runs in Azure, and when I runs the bot locally the error doesnt happens.

I have been speaking with a support engineer of Microsoft, and he gave me the next information:

> Microsoft had a service incident for direct line (west Europe).
> The issue manifested as 502/503 reports from the direct line and was intermittent.
> Our Product Developers detected it at 2020-07-24 04:26:14 PDT.
> It was mitigated it at 2020-07-24 05:41:00 PDT

How can I have access to these problems? Do you have any directline channel status web?

Our problem was that this service incident for directline coincided with the release of a new version of our bot. And we thought that it could be a problem related with the new version of our bot that was updated to 4.9.2 botbuilder version. Also I think that the channel messages "There was an error sending this message to your bot: HTTP status code GatewayTimeout" were confusing us, because we though that it was related with users not receiving messagges, but it only means that one message from the bot takes more than 15 secs to be sent to the user.

Plz tell me if I can check these issues or service incidents in any web, because it would help to know what is happening before openning an issue here.

**Comment by dmvtech** [comment]
@DanielTizon Unfortunately there is nothing like that at the moment for Direct Line service. You can keep an eye out or file an issue in the [Direct Line repository](https://github.com/microsoft/BotFramework-Services/issues) in the future.

**Comment by stevkan** [comment]
Closing, per request from @dmvtech.
