### ISSUE TITLE
[PORT] use new HttpContent each time for HttpRequestMock

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2572]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4199

## Description

use new HttpContent each time: when used by some custom action, they may dispose it so we can't reuse HttpContent

## Specific Changes

add HttpResponseMockContent to generate HttpContent

## Testing

update TestScriptTests_HttpRequestMock.test.dialog for repeating bytearray response

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive.Testing
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* 

[Adaptive,changes required]

**Comment by luhan2017** [comment]
relates to #2391

**Comment by joshgummersall** [comment]
This will be completed as part of the port and doesn't need to be tracked separately.
