### ISSUE TITLE
[PORT] Add missing XML docs to Microsoft.Bot.Builder.TemplateManager

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2573]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4282

Related to #4052 

# Changed projects
* Microsoft.Bot.Builder.TemplateManager

[BF Docs,R10,changes required]

**Comment by garypretty** [comment]
Closing. To be handled as part of #2465
