### ISSUE TITLE
[PORT] Adding documentation for Teams classes

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2576]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4313

Adds the various summary, param, and return documentation for the Teams classes. 

# Changed projects
* Microsoft.Bot.Builder

**Comment by johnataylor** [comment]
In the JavaScript code this corresponds to the teamsActivityHelpers.ts
