### ISSUE TITLE
'botbuilder-prompts' only downloads as a separate entity using [npm install botbuilder-prompts--save]

### ISSUE THREAD

**Issue by KatiePro** [Microsoft/botbuilder-js#258]
Prompts library downloads differently depending on the method used.

#### botbuilder-dialogs/src/prompts contains:
- attachmentPrompt
- choicePrompt
- datetimePrompt
- index
- numberPrompt
- **prompt**
- textPrompt

#### botbuilder-prompts/src contains:
- attachmentPrompt
- choicePrompt
- **confirmPrompt**
- datetimePrompt
- index
- **internal**
- numberPrompt
- **oauthPrompt**
- textPrompt

The documentation points entirely to botbuilder-dialogs. It took me working specifically on samples/simple-prompt-bot-es6 to even realize that botbuilder-prompts existed as its own entity.

**Comment by Stevenic** [comment]
Thanks... Looks like this was fixed.
