### ISSUE TITLE
[PORT] Add missing XML documentation to Microsoft.Bot.Builder.Dialogs.Declarative.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2592]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4289

Related to #4052

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Declarative

[BF Docs,R10]

**Comment by garypretty** [comment]
Closing. To be handled as part of #2465
