### ISSUE TITLE
[PORT] add qna maker extension

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2598]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4293

Fixes #4290 

## Specific Changes

  - 
  -
  -

## Testing

# Changed projects
* Microsoft.Bot.Builder.AI.QnA
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.AI.QnA.Tests
* Microsoft.Bot.Builder.TestBot.Json

**Comment by stevengum** [comment]
N/A
