### ISSUE TITLE
[PORT] Add missing documentation to all visible classes, methods, properties and parameters in Adaptive-Expressions

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2600]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4308

fixes: #4283 
Add documentation in Adaptive-Expressions, for visible classes, methods, properties and parameters, including

- Built-in Functions
- FuntionUtils
- ExpressionProperty
- TriggerTree

# Changed projects
* AdaptiveExpressions

**Comment by cosmicshuai** [comment]
this is a part of #2602

**Comment by cosmicshuai** [comment]
this is a part of #2602
