### ISSUE TITLE
Ensure documentation is provided for all visible methods, properties and parameters

### ISSUE THREAD

**Issue by axelsrz** [microsoft/botbuilder-js#2602]
Missing code documentation needs to be completed across the repo, in line with this issue in .NET https://github.com/microsoft/botbuilder-dotnet/issues/4052.

There are several classes, properties and methods that don't have code documentation associated to them.

As part of #2465, we enabled code analysis and enforced treating warnings as errors. 

This issue involves:

1. Replacing the `warn` for an `error` from each require-jsdoc respecting a specific library

```
"files": ["libraries/adaptive-expressions/src/*.ts", "libraries/adaptive-expressions/src/**/*.ts"],
...
"jsdoc/require-jsdoc": ["warn", { ...
``` 

2. Compile and address all the documentation errors provided by the linter.

This will impact multiple projects, it is recommended to address each project in a separate PR and walk up the dependency stack, Here is a list of projects that need to be addressed:

- [ ] adaptive-expressions
- [ ] botbuilder
- [ ] botbuilder-ai
- [ ] botbuilder-applicationinsights
- [ ] botbuilder-azure
- [ ] botbuilder-core
- [ ] botbuilder-dialogs
- [ ] botbuilder-dialogs-adaptive
- [ ] botbuilder-dialogs-adaptive-tests
- [ ] botbuilder-dialogs-declarative
- [ ] botbuilder-lg
- [ ] botbuilder-testing
- [ ] botframework-config
- [ ] botframework-connector
- [ ] botframework-schema
- [ ] botframework-streaming

# Additional info:

- To run the report delete all the rules other than jsdoc/require-jsdoc and run:
```
eslint -f html  ./libraries/*/src/*.ts ./libraries/*/src/**/*.ts | Out-File -FilePath .\report.html
```

**Comment by cosmicshuai** [comment]
@axelsrz 
I changed the settings in overrides, by replacing the warn for an error. However after running `npm run eslint`, it still only showed warning. And also suggesting missing jsdoc warning on private methods. Is there any work around for correcting .eslintrc.json?

**Comment by axelsrz** [comment]
@cosmicshuai Yes, you have to remove the "only-warn" plugin.

**Comment by joshgummersall** [comment]
Closing in favor of https://github.com/microsoft/botbuilder-js/issues/2840
