### ISSUE TITLE
[PORT] Update master with SSO + Teams changes. Cherry picked main changes + test update.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2608]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4333

Some manual additions to the cherry picks as there was some divergence with the fxcop changes and others in the last few days.

# Changed projects
* Microsoft.Bot.Builder.Dialogs
* Microsoft.Bot.Builder.Dialogs.Tests

**Comment by joshgummersall** [comment]
Related: https://github.com/microsoft/botbuilder-dotnet/pull/4677
