### ISSUE TITLE
QnA Maker-Sample refers to appsettings.json which isn't in the files

### ISSUE THREAD

**Issue by theangellmethod** [Microsoft/botbuilder-js#261]
https://github.com/Microsoft/botbuilder-js/tree/master/samples/qna-maker-bot-es6

This refers to appsettings.json but it looks like you are meant to add the information in app.js.

"_Update appsettings.json with your QnAMaker-Host, QnAMaker-KnowledgeBaseId and QnAMaker-EndpointKey. You can find this information under "Settings" tab for your QnA Maker Knowledge Base at QnAMaker.ai_"

**Comment by Stevenic** [comment]
Thanks. fixed
