### ISSUE TITLE
Need a sample that calls QnA Maker directly instead of in middleware

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/botbuilder-js#262]
The QnA Maker sample included in the repo calls QnA Maker from middleware, which is useful for a very specific scenario (a very simple QnA bot), but not for bots that just have an FAQ conversation flow. Please include a sample that demonstrates how to use the QnA Maker module in botbuilder-ai to pass a question to the service and decide what to do with the scored answers on your own.

**Comment by Stevenic** [comment]
Was about to file the same bug. I'll go a step further and say that we should re-consider even supporting QnA Maker as middleware.

**Comment by szul** [comment]
@Stevenic Wasn't the whole purpose of SDK v4 to support extensibility through middleware? Is Microsoft now backtracking on this?

**Comment by ryanvolum** [comment]
@szul , middleware represents a nice encapsulation of logic, but isn't the answer for everything. As it stood, the QnAMaker middleware would take over a conversation if it's confidence met a certain threshold, which is rarely desired and breaks multi-turn conversations. I think it's totally reasonable for QnA Maker middleware to exist and for devs to use it in _some_ contexts, but if our QnA Maker sample hides all the logic to call the API and react to the response, then developers won't know how to layer in QnA Maker in _any_ context

**Comment by szul** [comment]
@ryanvolum Okay, so it sounds like you aren't ditching the middleware interface, you are just looking to add a more direct way of calling it as well.

**Comment by benbrown** [comment]
This new sample includes a direct call to the QnAMaker service, and shows how to handle at least a positive and negative result:

https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/11.qnamaker
