### ISSUE TITLE
CSP headers block 4.9.2

### ISSUE THREAD

**Issue by felixvanleeuwen** [microsoft/botbuilder-js#2620]
## Screenshots
![image](https://user-images.githubusercontent.com/64589372/88930229-7c832000-d27b-11ea-98a7-ab702044d0a9.png)
![image](https://user-images.githubusercontent.com/64589372/88930264-8a38a580-d27b-11ea-8e63-991af890beff.png)

## Version
4.9.2

## Describe the bug
When updating from 4.7.0. to 4.9.2 our CSP headers goes off on the bit of code in the screenshot.

## Steps to reproduce
1. Block 'unsafe-eval' script sources;
2. Update webchat to 4.9.2;
3. Get page containing ReactWebChat;

## Expected behavior
Webchat works.

[Bug]

**Comment by compulim** [comment]
Thanks @EricDahlvang.

In the meanwhile, please downgrade Web Chat to 4.9.1.

I am unsure if it can be fixed in 4.10.0 (which will be released in ~2 weeks). But this is P0 to P1 IMO.

**Comment by peterinnesmsft** [comment]
We are looking to target this for an upcoming patch release. Will provide further details soon.
