### ISSUE TITLE
[PORT] Test dialog:merge in integration builds

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2636]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4334

We have checked-in some bad schema even though dialog:merge verifies and there is a test for it.  The test was disabled on the build server, but is now enabled by installing the bf tool.  This check-in also cleans-up the bad schema.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Declarative.Tests
* Microsoft.Bot.Builder.TestBot.Json
*

**Comment by mdrichardson** [comment]
@joshgummersall @chrimc62 Does this one actually need to be ported? [The parent PR changes 6 files](https://github.com/microsoft/botbuilder-dotnet/pull/4334/files):

1. `ci-test-steps.yml`
  * Only needs changing if schema merge tests get run
2. `Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.AttachmentInput.schema`
  * Changes already present in JS
3. `Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnCancelDialog.schema`
  * Changes already present in JS
4. `Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaMergeTests.cs`
  * [Does not exist in JS](https://github.com/microsoft/botbuilder-js/tree/main/libraries/botbuilder-dialogs-declarative/tests). I ctrl+shift+f'd `dialog:merge` and wasn't able to find anything similar, either. @joshgummersall I can port the whole file over to JS, if that's what we want.
5. `tests/Microsoft.Bot.Builder.TestBot.Json/CustomSteps/Testbot.JavascriptAction.schema`
  * Pretty sure this [doesn't exist in JS](https://github.com/microsoft/botbuilder-js/tree/main/libraries/testbot). Again, @joshgummersall I could probably port it, if needed.
6. `tests/tests.schema`
  * I think maybe this is generated? The diff says:

![image](https://user-images.githubusercontent.com/40401643/98290074-fbb08000-1f5d-11eb-81d3-8eaf2753a4c4.png)

**Comment by joshgummersall** [comment]
I think the gist of this with respect to the JS repo is: we want to also ensure that our schema files are correct. At the moment we have no test or CI to handle this so it's a manual, honor-system test.

Once the monorepo yarn refactor PR (https://github.com/microsoft/botbuilder-js/pull/2984) lands, we should probably do the following:

- Add the botframework CLI as a `devDependency`
- Add a script to the root `package.json` file called something like `test:schemas` that does the equivalent of `bf schema:merge **/*.schema` (honestly not sure if that's the right command, but that's the idea)
- Add a job to our CI that invokes this command to ensure that schemas merge together properly

@chrimc62 please feel free to comment/critique this approach if it doesn't make sense.

**Comment by mdrichardson** [comment]
@joshgummersall Gotcha. Best to hold off on this one until the monorepo refactor PR is merged?

**Comment by joshgummersall** [comment]
Yeah, I'm sure it'll be a nightmare merge conflict otherwise.
