### ISSUE TITLE
[PORT] Use Resource.Id as default Id for referenced objects 

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2638]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4368

Fixes #4367

## Specific Changes
Changed resourceExplorer to Apply resource.id to referenced objects.

## Testing
Updated unit tests to have referenced objects too to validate.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Declarative
* Microsoft.Bot.Builder.Dialogs.Declarative.Tests

[R10]

**Comment by stevengum** [comment]
This is for a Preview library, assigning to @boydc2014 for triaging.

**Comment by boydc2014** [comment]
> This is for a Preview library, assigning to @boydc2014 for triaging.

Thanks, i just chatted with @mrivera-ms  on this, we put an R11 on it now, before i get more details into it, since this package is not fully partiality with C# yet, so the porting probably can't be started immediately.
