### ISSUE TITLE
No Dialogs Docs

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/botbuilder-js#264]
There are several dialogs samples in the Node repo, but no docs to explain what dialogs do and when to use them. The one link (in the dialogs sample README) doesn't resolve.

**Comment by Stevenic** [comment]
It's a little buried but its here:

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=js

I've updated all of our doc links to point to the right place at least.
