### ISSUE TITLE
[PORT] add constructor overload

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2641]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4377

Fixes #5853

- adds another constructor to QnAMakerDialog
- we intend a deeper refactoring of this code in the next milestone - this change just adds the missing constructor

# Changed projects
* Microsoft.Bot.Builder.AI.QnA

**Comment by joshgummersall** [comment]
It looks like `dialogId` is already an optional parameter with a default ([see here](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-ai/src/qnaMakerDialog.ts#L127)).
