### ISSUE TITLE
CSP Issue caused by botframework-streaming library

### ISSUE THREAD

**Issue by rajdhandus** [microsoft/botbuilder-js#2647]
## Versions
What package version of the SDK are you using.
botframework-streaming 4.9.2

## Describe the bug
Give a clear and concise description of what the bug is.
CSP error noticed in the client side browser because of new Function() code in [doesGlobalFileReaderExist.ts](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botframework-streaming/src/utilities/doesGlobalFileReaderExist.ts#L9)

https://developers.google.com/web/fundamentals/security/csp/#eval_too

**Comment by compulim** [comment]
Assigning to @stevengum as he own `botframework-streaming`.
