### ISSUE TITLE
[PORT] BotFrameworkAdapter: Make CreateConversationAsync agnostic to the credential type

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2668]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4332

Pending on decision around binary compat. This PR as-is breaks binary compat. If binary compat is to be maintained, then I'll swap to overloading instead of non-breaking modification.

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/3962

# Changed projects
* Microsoft.Bot.Builder

**Comment by joshgummersall** [comment]
Consider moving the API to service client credentials rather than just app credentials.

**Comment by joshgummersall** [comment]
@johnataylor it seems like the Javascript BotFrameworkAdapter already uses the generic `AppCredentials` type for [its internal credentials reference](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/botFrameworkAdapter.ts#L204). Logic exists [in the constructor](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/botFrameworkAdapter.ts#L239) to create the relevant concrete credentials instance.

There is [a helper method](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/botFrameworkAdapter.ts#L1438) that builds a MicrosoftAppCredentials instance but it appears to be specific to bot-to-bot communication.

The [`createConversation` method](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/botFrameworkAdapter.ts#L456) itself does not accept a `credentials` reference, so I'm not sure what needs to be ported. Is this still relevant to the JS SDK? What else am I missing?

**Comment by joshgummersall** [comment]
https://github.com/microsoft/botbuilder-js/issues/3533
