### ISSUE TITLE
Botbuilder docs do not include MessageFactory

### ISSUE THREAD

**Issue by theangellmethod** [Microsoft/botbuilder-js#267]
https://github.com/Microsoft/botbuilder-js/tree/master/doc/botbuilder

is missing MessageFactory although it is used in the wiki.

**Comment by Stevenic** [comment]
I'm going to remove those docs to help avoid further confusion. The real reference docs are over here:

https://docs.microsoft.com/en-us/javascript/api/botbuilder-core-extensions/messagefactory
