### ISSUE TITLE
[Composer] lg templates CRUD functions is not friendly to composer

### ISSUE THREAD

**Issue by lei9444** [microsoft/botbuilder-js#2679]
In composer,  we use web worker to do lg full parse. But the parse result object contains template CRUD methods. We can't pass them from the worker thread  to main thread. If we want to get benefits from the template CRUD methods, we have to do a full parse in main thread and this may take a long time.

**Describe the solution you'd like**
1. parse result is a pure object without any functions.
2. provide extra template CRUD utility methods

**Comment by Danieladu** [comment]
Sync with the Composer team, the problem has been solved. Close it now.
