### ISSUE TITLE
npm README for botbuilder-dialogs-adaptive is very out of date

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-js#2680]
## Versions
What package version of the SDK are you using: 4.9.3-preview
What nodejs version are you using: n/a
What browser version are you using: n/a
What os are you using: n/a

## Describe the bug
The description of [botbuilder-dialogs-adaptive 4.9.3-preview](https://www.npmjs.com/package/botbuilder-dialogs-adaptive) on npm discusses how to create and run waterfall dialogs, when it should describe how to create and run adaptive dialogs with the dialog manager.

## To Reproduce
1. Open [botbuilder-dialogs-adaptive 4.9.3-preview](https://www.npmjs.com/package/botbuilder-dialogs-adaptive) on npm.
1. Error: read the description and notice that there is no information about adaptive dialogs.

## Expected behavior
The package description should be accurate and describe how to use classes in the package.

## Additional context
Users are excited about this new feature ([When will this be available for nodejs? #1859](https://github.com/MicrosoftDocs/bot-docs/issues/1859)). It's embarrassing to point them to npm right now.

[bug]

**Comment by luhan2017** [comment]
@vishwacsena , could you please take this? anything we can leverage?

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. Closing as Not Needed.

**Comment by JonathanFingold** [comment]
@mrivera-ms The https://www.npmjs.com/package/botbuilder-dialogs-adaptive page still talks about waterfall dialogs, even though the package has the adaptive dialog bits in it. Even just a minimal but relevant description of what is actually in the package would be both helpful and expected.
