### ISSUE TITLE
[PORT] Fix schema bugs in Microsoft.Ask.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2690]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4432

The Microsoft.Ask schema had two errors that did not match the Microsoft.Ask implementation.
1) expectedProperties was missing the items specification.
2) defaultOperation was an objectExpression rather than a stringExpression.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* 

[R10]

**Comment by cleemullins** [comment]
Spoke w/ @tomlm and we can take this next cycle.

**Comment by joshgummersall** [comment]
Resolved via https://github.com/microsoft/botbuilder-js/pull/2986
