### ISSUE TITLE
Optimize mocha tests

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botbuilder-js#2695]
1. [X] Clean up the leaks found by running the tests with `--check-leaks`
    * [PR](https://github.com/microsoft/botbuilder-js/pull/2698)
2. [ ] Do some testing with `-p` for parallel and `-j` for # of cores to see if we can get some speed improvements.
    * INVESTIGATED:
      * Requires upgrading from mocha v6 to v8, [which would drop support for node versions < v10.12.0](https://github.com/mochajs/mocha/releases/tag/v8.0.0)
        * Possible alternative is [`mocha-parallel-tests`](https://www.npmjs.com/package/mocha-parallel-tests)
      * Cuts test time IN HALF!!!!! (with a 4 core CPU)
      * In CI/CD pipelines, this reduces test time from ~1:15 to ~0:50, so ~35% savings
	  * Currently can't get test coverage reports when in parallel mode. [tracking issue](https://github.com/mochajs/mocha/issues/4372)
		* Tried using [`mocha-parallel-tests`](https://www.npmjs.com/package/mocha-parallel-tests) instead and 15 tests failed due to some quirks with using node worker processes
		* Update 10/1: Still an issue on latest mocha and nyc releases
3. [X] Also need to investigate why some tests are throwing `MaxListenersExceeded` warning
    * [PR](https://github.com/microsoft/botbuilder-js/pull/2699)

**Comment by joshgummersall** [comment]
We'll hold off on parallel testing for now. Other CI improvements have made the test suite more performant.
