### ISSUE TITLE
Please create js dialog samples (not just ts)

### ISSUE THREAD

**Issue by michhar** [Microsoft/botbuilder-js#270]
All of the dialog samples are in typescript - could you  make some with plain javascript?

https://github.com/Microsoft/botbuilder-js/tree/master/samples/dialogs

**Comment by Stevenic** [comment]
Sure... I'll work on that.

**Comment by szul** [comment]
@michhar You should be good with these samples up to a point. Just remove the typings, the interfaces, and maybe modify the import statements. If you get stuck, you can review the generated code, which looks like it has been checked into GitHub.

**Comment by sgellock** [comment]
@michhar we are updating our samples.  here is a list of all the samples we are in the process of updating.  please refer to https://github.com/Microsoft/botbuilder-dotnet/issues/834.  We will be adding both typescript and javascript
