### ISSUE TITLE
[PORT] Fix AdaptiveExpressions tests failing

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2704]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4428

closes: #4420 
fix some tests about `isMatch(getPreviosViableTime('TXX:40:20'), 'T[0-2][0-9]:40:20)'` failing issues
Now all this type functions are tested by endsWith function `endsWith(getPreviousViableDate('XXXX-07-10'), '-07-10')`

I run the pipeline for 9 times to check whether it will fail again. And all of them passed.
@EricDahlvang @boydc2014  could you take a look?

# Changed projects
* AdaptiveExpressions.Tests

**Comment by cosmicshuai** [comment]
https://github.com/microsoft/botbuilder-js/pull/2707 changes all related test
