### ISSUE TITLE
Add method to fetch/identify team owners in Teams

### ISSUE THREAD

**Issue by matthiasdilger** [microsoft/botbuilder-js#2706]
**Is your feature request related to a problem? Please describe.**
Teams has two kinds of team member roles: Owner and member. There is currently no way for the bot to quickly identify an owner of a team. Having this would make it possible to support additional functionality specifically for an owner of the current team.

**Describe the solution you'd like**
TeamsInfo.getTeamOwners(context , teamId), TeamsInfo.getPagedTeamOwners(context, teamId) or similar would be great. It would work the same as TeamsInfo.getTeamMembers(context, teamId), etc.
Edit: An "isOwner" flag in the member details would also work, e.g. TeamsInfo.getTeamMember(context, teamId, userId) would return isOwner: true

**Describe alternatives you've considered**
I tried to get the teams owner via oauth but I think only tenant admins can agree to permissions (like Group.Read.All) that would allow checking if the user is an owner. It would be great to get this functionality without implementing oauth.

**Comment by clearab** [comment]
Migrated to the Teams repository here: https://github.com/MicrosoftDocs/msteams-docs/issues/1990

**Comment by AndreMaz** [comment]
@tracyboehrer sorry for tagging you but you seem to be maintainer of this lib. 

I want find out the owners of a teams. Is it possible to include the `isOwner` flag in `TeamsInfo.getMember(context, userId)` response? 

As the og user said:
> It would be great to get this functionality without implementing oauth
