### ISSUE TITLE
[PORT] Enable schema merge tests

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2725]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4474

This is in conjunction with the fixes in bf cli dialog:merge. 
Enable schema tests. (Although needed to filter out one test which is valid but fails validation.)
Switch to public schema references.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Declarative
* Microsoft.Bot.Builder.Dialogs.Declarative.Tests
*

**Comment by joshgummersall** [comment]
This is pending resolution to https://github.com/microsoft/botbuilder-dotnet/issues/4492.

**Comment by joshgummersall** [comment]
Related: https://github.com/microsoft/botbuilder-js/issues/2636

**Comment by mdrichardson** [comment]
Holding off until [refactor PR](https://github.com/microsoft/botbuilder-js/pull/2984) gets merged

**Comment by joshgummersall** [comment]
Closing in favor of https://github.com/microsoft/botbuilder-js/issues/2636.
