### ISSUE TITLE
[PORT] Fixes for test scripts.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2731]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4482

Added missing schema for Microsoft.Test.CustomEvent.
Removed comments from test script.
Fixed update scripts.
Made it so asserts show the activity and added tests.
Added --dialog to TestBot so you don't have to rename files.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive.Testing
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.Dialogs.Declarative.Tests
* Microsoft.Bot.Builder.TestBot.Json
*

**Comment by mrivera-ms** [comment]
Needs investigation. @JuanAr please evaluate if there is any work needed here.

**Comment by denscollo** [comment]
Hi @mrivera-ms , we reviewed this issue and found that is not necessary to port the missing schema for Microsoft.Test.CustomEvent as this is not implemented in JS.
As for the port of the new test script `AssertReply_Assertions_Failed`, we created the PR #2808 .
Please, let us know if you have any questions.

**Comment by mrivera-ms** [comment]
Thank you, @denscollo . Closing this item as not needed.
