### ISSUE TITLE
Trace activities not filtered on DeliveryMode.ExpectReplies

### ISSUE THREAD

**Issue by alopix** [microsoft/botbuilder-js#2732]
## Versions
What package version of the SDK are you using. 4.9.3
What nodejs version are you using 12.16.1
What browser version are you using -
What os are you using -

## Describe the bug
When using `DeliveryMode.ExpectReplies` to send an activity using directline (e.g. also used to communicate with a skill), the response will not run through the same filter as with a non-expected replies activity.
Instead of filtering `Trace` activities, every type of activity will go into the `bufferedResponses` and be sent to the client.

## To Reproduce
1. Running a simple JS sample that sends a response.
2. Send an activity using `DeliveryMode` = `ExpectReplies`.
3. Observe `BotFrameworkAdapter.sendActivities` never being called which results in the funny comment [`// Just eat activity`](https://github.com/microsoft/botbuilder-js/blob/54e4c2ded75436c00fe182dcb4c0c077f45741bc/libraries/botbuilder/src/botFrameworkAdapter.ts#L980) and more importantly the result of it filtering traces never being executed. The issue starts in [`TurnContext.sendActivities`](https://github.com/microsoft/botbuilder-js/blob/31e2d7aabbdf99b91323621cf6f1077e03228410/libraries/botbuilder-core/src/turnContext.ts#L468) which will not call the adapter's `sendActivities` but the adapter continuing the `processActivity` execution which will send the `TurnContext.bufferedReplyActivities`.

## Expected behavior
Same behaviour when calling `sendActivity/ies` for either type of `DeliveryMode`, which filters traces. Alternatively, the possibility to set an option to also filter trace activities for these scenarios.

## Screenshots
\-

## Additional context
\-

**Comment by cleemullins** [comment]
@joshgummersall to work with @stevengum to try to get this into R11.
