### ISSUE TITLE
[PORT] add StatusCode & ReasonPhrase to HttpResponseMock

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2733]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4426

Fixes #4360

## Description

add StatusCode & ReasonPhrase to HttpResponseMock

## Specific Changes

  - Mock HttpResponseMessage instead of Content

## Testing

Update TestScriptTests_HttpRequestMock.test.dialog

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive.Testing
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
*

**Comment by joshgummersall** [comment]
@luhan2017 is this issue tied to R11? If so, could you please apply the appropriate labels for sizing and priority? Thank you.

**Comment by luhan2017** [comment]
relates to #2391

**Comment by joshgummersall** [comment]
This will be completed as part of the port and doesn't need to be tracked separately.
