### ISSUE TITLE
TeamsActivityHandler unhandled errors from member added events

### ISSUE THREAD

**Issue by brycepolly** [microsoft/botbuilder-js#2749]
## Versions
What package version of the SDK are you using. 4.9
What nodejs version are you using 12.18

## Describe the bug
TeamsActivityHandler is internally calling `getMember` on member added events, which occasionally cause an unhandled member not found exception.
https://github.com/microsoft/botbuilder-js/blob/a8e7913244b0c274584c6995b97483ec0ec9d00b/libraries/botbuilder/src/teamsActivityHandler.ts#L446

## To Reproduce
Run botbuilder on Teams at a large scale (Polly)

## Expected behavior
Not call fetchMember internally, should be my responsibility as a consumer of the class if I need that information.  This also increases our API load against our bots rate limits against our wishes.  

## Additional context
["Error: Member not found in conversation.","at new RestError (/home/core/node_modules/@azure/ms-rest-js/lib/restError.ts:18:5)","at /home/core/node_modules/@azure/ms-rest-js/lib/policies/deserializationPolicy.ts:117:27","at runMicrotasks (<anonymous>)","at processTicksAndRejections (internal/process/task_queues.js:97:5)"]

**Comment by clearab** [comment]
The code for this should only fire in the instance that Teams isn't returning a fully constructed Teams Channel Account object (or the conversationUpdate was for the bot getting added), and we should be catching exceptions. Teams should be consistently returning the correct object now, so this code should very rarely ever fire. How often are you seeing this happen?

@EricDahlvang @johnataylor @stevengum

**Comment by EricDahlvang** [comment]
Hi @brycepolly 

Which version of 4.9 are you using?  Is it 4.9.3?  We did have a bug in the initial 4.9.0 release, fixed with: https://github.com/microsoft/botbuilder-js/commit/923f610a9368f1501b125eb84f66ea07f3084f2e#diff-f330eece1e4bff71280d863e05620dbf

**Comment by brycepolly** [comment]
This was happening a few times an hour for us.  Looking at the code I saw that the `MembersAdded` event bypasses all this stuff, so I switched over to that instead as we selectively call fetchMember anyway on that event.  The bigger issue is the internal throw inside that method, no way for my event handler to catch that and still try to process the event.

**Comment by clearab** [comment]
@EricDahlvang is that catching the wrong error type? Should that be `memberNotFound` and not `conversationNotFound`?

**Comment by EricDahlvang** [comment]
@clearab  the error code returned from Teams is 'ConversationNotFound'.  Presumably, this is due to the conversation not being found in the member's list of conversations.?

Dotnet is the same: https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs#L488

**Comment by pavolum** [comment]
@EricDahlvang if this is expected how should we move forward with the issue? Should it be closed?

**Comment by pavolum** [comment]
@brycepolly can you please respond with which version of 4.9 are you using? Is it 4.9.3? We did have a bug in the initial 4.9.0 release.

If this is the case then you simply need to upgrade and the bug should be resolved. If not we will investigate further.

**Comment by brycepolly** [comment]
@pavolum  Sorry, missed the other message. Looks like we are on 4.9.2, so maybe an upgrade would solve this but I have already moved over to the other `MembersAdded` event anyway.  Feel free to close this if you wish.
