### ISSUE TITLE
Confirm Prompt missing default prompt text that C# version has

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/botbuilder-js#275]

**Comment by Stevenic** [comment]
Is this for the yes/no buttons?

**Comment by csiebler** [comment]
It looks like it is not showing the confirmation message properly:

![image](https://user-images.githubusercontent.com/525867/41359139-219945d6-6f2a-11e8-86a0-bb0095b7f573.png)

After hitting either button, the confirmation messages (and other messages sent for the step) appear:

![image](https://user-images.githubusercontent.com/525867/41359260-6384141c-6f2a-11e8-804b-ac6c6420851c.png)

Here's the code:

```javascript
...
    async function(dc, values) {
        await dc.context.sendActivity(`Recognized values: ${JSON.stringify(values)}`);
        await dc.prompt('textPrompt', 'Where are you heading to?');
    },
    async function(dc, values) {
        await dc.context.sendActivity(`Recognized values: ${JSON.stringify(values)}`);
        await dc.prompt('confirmPrompt', `Is this all ok?`);
    },
    async function (dc, values) {
        await dc.context.sendActivity(`Recognized values: ${JSON.stringify(values)}`);
        await dc.end();
    }
```

**Comment by sgellock** [comment]
Fixed
