### ISSUE TITLE
Add Chrome functional tests back to .yaml

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-js#2770]
https://github.com/microsoft/botbuilder-js/blob/master/libraries/browser-functional-tests/browser-tests-build-ci.yml

ChromeBrowser install is failing the build:

Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
Downloading from file: https://chromedriver.storage.googleapis.com/85.0.4183.38/chromedriver_win32.zip
Saving to file: \85.0.4183.38\chromedriver\chromedriver_win32.zip
Received 1040K...
Received 2080K...
Received 3120K...
Received 4160K...
Received 5080K total.
Extracting zip contents to  \85.0.4183.38\chromedriver.
Copying to target path \libraries\browser-functional-tests\node_modules\chromedriver\lib\chromedriver
Done. ChromeDriver binary available atlibraries\browser-functional-tests\node_modules\chromedriver\lib\chromedriver\chromedriver.exe

I tried upgrading the chromedriver": "^85.0.0", did not help.

Found this:
https://developercommunity.visualstudio.com/content/problem/1173642/encountering-chrome-driver-download-will-not-be-pe.html

**Comment by stevengum** [comment]
Let’s find a lucky assignee for this issue next week. Thanks for filing the tracking issue @EricDahlvang!
