### ISSUE TITLE
[PORT] logPersonalInformation flag missing in QnAMakerDialog

### ISSUE THREAD

**Issue by matiasroldan6** [microsoft/botbuilder-js#2779]
## Describe the bug
The class [QnAMakerDialog ](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-ai/src/qnaMakerDialog.ts#L63) is missing the **logPersonalInformation** flag which [is present in C#](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs#L328). This causes, among other things, issues with telemetry reporting in Power BI.
The flag, in turn, is not being passed by constructor to QnAMaker in the method [getQnAClient](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-ai/src/qnaMakerDialog.ts#L417), unlike the [behavior in C#](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs#L469).

![image](https://user-images.githubusercontent.com/20074735/92954228-79ae4a00-f439-11ea-94e7-e0687b4a10fb.png)

![image](https://user-images.githubusercontent.com/20074735/92954258-89c62980-f439-11ea-9571-6170c0e75eb1.png)

## Expected behavior
The class QnAMaker should have parity with C#, and telemetry should be being reported.

## Additional context
- This problem was reported in a comment of issue microsoft/botframework-solutions#3612.
- [This is the PR](https://github.com/microsoft/botbuilder-dotnet/pull/3715) where the **logPersonalInformation** property and other telemetry changes were added in C#

**Comment by tsuwandy** [comment]
@stevengum , @EricDahlvang, could one of you take a look?

**Comment by Zerryth** [comment]
@matiasroldan6 , can confirm that you are correct, we are missing `logPersonalInformation` in `QnAMakerDialog.getQnAClient()`.
Looks like the JS SDK also fails to pass along options as well.

Working on a fix now.
