### ISSUE TITLE
LanguageTranslator does not translate suggestedActions

### ISSUE THREAD

**Issue by csiebler** [microsoft/botbuilder-js#278]
It seems like `LanguageTranslator` does not translate `SuggestedActions` when using `translateBackToUserLanguage: true`. This causes the bot to default back to "native" language of the bot as soon as the user clicks the buttons of the suggested action (as expected).

![image](https://user-images.githubusercontent.com/525867/41342135-c92fa6b6-6efb-11e8-9700-792e8e2773f3.png)

Which turns into:

![image](https://user-images.githubusercontent.com/525867/41341996-72c7d69a-6efb-11e8-9d0d-3e86972202ed.png)

**Expected behaviour:**

`LanguageTranslator` also translates the suggested actions, so that the language stays in the language the user is currently writing in.

**Reproduce via:**

Versions:
```
  "dependencies": {
    "botbuilder": "^4.0.0-preview1.2",
    "botbuilder-ai": "^4.0.0-preview1.2",
    "botbuilder-azure": "^4.0.0-preview1.2",
    "botbuilder-dialogs": "^4.0.0-preview1.2",
    "dotenv": "^6.0.0",
    "restify": "^7.1.1"
  }
```

```javascript
const translator = new LanguageTranslator({
    translatorKey: TRANSLATOR_KEY,
    noTranslatePatterns: new Set(),
    nativeLanguages: ['en'],
    translateBackToUserLanguage: true
});
adapter.use(translator);
```

Suggested action message:

```javascript
const options = ["Request Refund", "Show Refund Status"];
const actions = MessageFactory.suggestedActions(options, "Hello, how can I help you?");
await dc.context.sendActivity(actions);
```

Thanks,
Clemens

**Comment by Stevenic** [comment]
This is a known limitation.

**Comment by sgellock** [comment]
We need to create/update the sample

**Comment by stevengum** [comment]
Translation middleware was taken out via #370, and a sample is being worked on in branch [johtaylo/translation-sample](https://github.com/Microsoft/botbuilder-js/tree/johtaylo/translation-sample). Let's see if we can support for SuggestedActions in the sample...

**Comment by Stevenic** [comment]
We no longer build in language translation
