### ISSUE TITLE
TelemetryLoggerMiddleware doesn't handle missing Teams tenant information

### ISSUE THREAD

**Issue by mrestorff** [microsoft/botbuilder-js#2781]
Caused by #2528 

## Versions
- botbuilder v4.10.3
- nodejs version v12.18.1
- Windows Server

## Describe the bug
The [latest version change to the telemetryLoggerMiddleware](https://github.com/microsoft/botbuilder-js/commit/bc95461422f3b3ad74bc0374db7e70e8c6c72a9f#diff-f3bf96f36a847b10436ea6e93f5a1a35R336) introduces an issue where undefined Teams tenant information in the channelData object throws an error on every interaction in Teams-connected bots.
```
onTurnError]: TypeError: Cannot read property 'tenant' of undefined
at TelemetryLoggerMiddleware.populateAdditionalChannelProperties (D:\home\site\wwwroot\node_modules\botbuilder-core\lib\telemetryLoggerMiddleware.js:280:63)
```

## To Reproduce
1. Connect bot to teams tenant that hides its tenent information
2. Trigger a telemetry logging event through a bot connected to teams

## Expected behavior
As the conditional operator is intended to check for channelData.tenant, it should also account for a case in which tenant is undefined.

Changing
`properties['TeamsTenantId'] = channelData.tenant ? channelData.tenant.id : '';`
to
`properties['TeamsTenantId'] = channelData?.tenant ? channelData.tenant.id : '';`
accounts for the tenant property missing and should mitigate this issue.

**Comment by tdurnford** [comment]
@stevengum Can you take a look at this?

**Comment by stevengum** [comment]
Thanks for reporting this @mrestorff, that seems like a straight forward issue.

@clearab, @microsoft/bf-teams this is something we need to account for in the other languages as well.

**Comment by stevengum** [comment]
The next stable release is tied to the R11 milestone, but a nightly build addressing this issue should be available sooner.
