### ISSUE TITLE
MessageFactory.suggestedActions cannot be serialized

### ISSUE THREAD

**Issue by ctstone** [Microsoft/botbuilder-js#279]
Getting this error when I use suggested actions:
```
Error "activity.suggestedActions.actions.value must be of type object." occurred in serializing the payload

  at Conversations.<anonymous> (C:\Source\cai-bot\cai-bot-app\node_modules\botbuilder\node_modules\botframework-connector\lib\generated\operations\conversations.js:725:42)
  at Generator.next (<anonymous>)
  at C:\Source\cai-bot\cai-bot-app\node_modules\botbuilder\node_modules\botframework-connector\lib\generated\operations\conversations.js:14:71
  at new Promise (<anonymous>)
  at __awaiter (C:\Source\cai-bot\cai-bot-app\node_modules\botbuilder\node_modules\botframework-connector\lib\generated\operations\conversations.js:10:12)
  at Conversations.replyToActivityWithHttpOperationResponse (C:\Source\cai-bot\cai-bot-app\node_modules\botbuilder\node_modules\botframework-connector\lib\generated\operations\conversations.js:678:16)
  at Conversations.replyToActivity (C:\Source\cai-bot\cai-bot-app\node_modules\botbuilder\node_modules\botframework-connector\lib\generated\operations\conversations.js:1504:25)
  at next (C:\Source\cai-bot\cai-bot-app\node_modules\botbuilder\lib\botFrameworkAdapter.js:430:62)
  at Promise (C:\Source\cai-bot\cai-bot-app\node_modules\botbuilder\lib\botFrameworkAdapter.js:450:13)
  at new Promise (<anonymous>)
```

Using `"botbuilder": "^4.0.0-preview1.2"`

I am sending a very simple set of options, copied from [docs](https://docs.microsoft.com/en-us/javascript/api/botbuilder-core-extensions/messagefactory#suggestedactions):
```JavaScript
MessageFactory.suggestedActions(['red', 'green', 'blue'], `Choose a color`);
```

The serialized value is shown in the error text:
```JSON
{
  "actions": [
    {
      "type": "imBack",
      "value": "red",
      "title": "red"
    },
    {
      "type": "imBack",
      "value": "green",
      "title": "green"
    },
    {
      "type": "imBack",
      "value": "blue",
      "title": "blue"
    }
  ]
}
```

The [CardAction API](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-3.0#cardaction-object) does specify `value` property as an `object`, but it varies depending on the action `type`. However, I found another [CardAction API definition](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-rich-cards?view=azure-bot-service-3.0#process-events-within-rich-cards) where `value` is defined as a string.

<strike>If I modify [cardFactory.ts](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core-extensions/src/cardFactory.ts#L238) to completely omit `value`, it works as expected. I guess the workaround would be to send an array of `Action` objects rather than `string`s.</strike>. Omitting `value` prevents `imBack` from inserting the text into the chat.

**Comment by ctstone** [comment]
Issue appears to originate in [this commit](https://github.com/Microsoft/botbuilder-js/commit/b29251c2671da5bdaedf3a9ff2b1a45d8cbab1ae#diff-e4dece20e18b686e679f41524f387d20L240).

**Comment by ctstone** [comment]
For now this workaround fixes the issue:

```TypeScript
import { CardAction } from 'botbuilder/node_modules/botframework-connector/lib/generated/models/mappers';

CardAction.type.modelProperties.value.type.name = 'String';
```

**Comment by Stevenic** [comment]
I'll try to reproduce the issue.

**Comment by Stevenic** [comment]
Which channel are you using? I created a new bot from scratch and the issue doesn't repo for me using the emulator. Here's my code:

```
import { BotFrameworkAdapter, MemoryStorage, ConversationState, MessageFactory } from 'botbuilder';
import * as restify from 'restify';

// Create server
let server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
    console.log(`${server.name} listening to ${server.url}`);
});

// Create adapter
const adapter = new BotFrameworkAdapter({ 
    appId: process.env.MICROSOFT_APP_ID, 
    appPassword: process.env.MICROSOFT_APP_PASSWORD 
});

// Define conversation state shape
interface EchoState {
    count: number;
}

// Add conversation state middleware
const conversationState = new ConversationState<EchoState>(new MemoryStorage());
adapter.use(conversationState);

// Listen for incoming requests 
server.post('/api/messages', (req, res) => {
    // Route received request to adapter for processing
    adapter.processActivity(req, res, async (context) => {
        if (context.activity.type === 'message') {
            const msg = MessageFactory.suggestedActions(['red', 'green', 'blue'], `Choose a color`);
            await context.sendActivity(msg);
        } else {
            await context.sendActivity(`[${context.activity.type} event detected]`);
        }
    });
});
```

**Comment by ctstone** [comment]
This is in web chat client. Also, I’m using express, but I don’t think that should make a difference. I’ll try to put together an e2e repro tonight or tomorrow.

Sent from mobile

________________________________

**Comment by ctstone** [comment]
The issue is in `ms-rest-js`. `botframework-connector` requires `ms-rest-js@^0.2.5`, and at some point my private package manager got stuck on `ms-rest-js@0.2.6` which should be fine, given the version semantics.

However, there is a regression in `ms-rest-js` versions `0.2.6` and `0.2.7` that is causing the error described above. See [my repo](https://github.com/ctstone/bf-suggested-action-repro) for repro.

Today the highest version of `ms-rest-js` that satisfies `^0.2.5` is `0.2.8`, which appears to resolve the regression, and explains why you were not able to repro the issue using a fresh project.

Does it make sense to update `botframework-connector/package.json` to `ms-rest-js@^0.2.8`?

**Comment by Stevenic** [comment]
Added PR #289

**Comment by stevengum** [comment]
Closing per [review](https://github.com/Microsoft/botbuilder-js/pull/289#pullrequestreview-136474521) on #289 which was merged into master 2 days ago.
