### ISSUE TITLE
Get the current TurnContext out of DialogTestClient

### ISSUE THREAD

**Issue by MatthiasGwiozda** [microsoft/botbuilder-js#2797]
**Is your feature request related to a problem? Please describe.**
I want to get the values of a `new ConversationState(new MemoryStorage())` while testing a dialog. I would like to check if the dialog saves specific properties in the MemoryStorage.

**Describe the solution you'd like**
Expose the TurnContext of the current turn in the test so I can access the data in the conversationState.

**Describe alternatives you've considered**

1. Find the saved Values directly out of the MemoryStorage -> I can't find the values that are saved there.
2. I tried to get the values with `statePropertyAccessor.get(client.dialogContext.context);`. The `client` is the DialogTestClient. I get the following error:
![image](https://user-images.githubusercontent.com/22172694/94260248-1be92a00-ff30-11ea-8b8c-a275e487f1e9.png)

**Comment by joshgummersall** [comment]
@stevkan could you investigate this issue and get back to us? Thanks.

**Comment by v-kydela** [comment]
Hello, @MatthiasGwiozda 

Most dialogs are tested with a test adapter and `TestFlow`, which makes it easy to define an on-turn handler that gets a turn context. Can you explain why you prefer to use a dialog test client?

**Comment by v-kydela** [comment]
@MatthiasGwiozda - Are you still working on this?

**Comment by MatthiasGwiozda** [comment]
> Hello, @MatthiasGwiozda
> 
> Most dialogs are tested with a test adapter and `TestFlow`, which makes it easy to define an on-turn handler that gets a turn context. Can you explain why you prefer to use a dialog test client?

Im using a dialogTestClient because it's straightforward. We found a documentation [here](https://www.npmjs.com/package/botbuilder-testing).

What exactly do you mean with `TestFlow`? could you show me a documentation? how can I use this to test dialogs?

**Comment by v-kydela** [comment]
Here is the documentation:

- https://docs.microsoft.com/en-us/javascript/api/botbuilder-core/testadapter
- https://docs.microsoft.com/en-us/javascript/api/botbuilder-core/testflow

To get an idea for how it works, you should have a look at the tests in the dialogs library: https://github.com/microsoft/botbuilder-js/tree/main/libraries/botbuilder-dialogs/tests

Here's an example of a choice prompt test: 

```js
    it('should not recognize, then re-prompt without error for falsy input.', async function () {
        const adapter = new TestAdapter(async (turnContext) => {
            const dc = await dialogs.createContext(turnContext);

            const results = await dc.continueDialog();
            if (results.status === DialogTurnStatus.empty) {
                await dc.prompt('prompt', 'Please choose a color.', stringChoices);
            } else if (results.status === DialogTurnStatus.complete) {
                const selectedChoice = results.result;
                await turnContext.sendActivity(selectedChoice.value);
            }
            await convoState.saveChanges(turnContext);
        });
        // Create new ConversationState with MemoryStorage and register the state as middleware.
        const convoState = new ConversationState(new MemoryStorage());

        // Create a DialogState property, DialogSet and ChoicePrompt.
        const dialogState = convoState.createProperty('dialogState');
        const dialogs = new DialogSet(dialogState);
        const choicePrompt = new ChoicePrompt('prompt');
        // Change the ListStyle of the prompt to ListStyle.none.
        choicePrompt.style = ListStyle.none;

        dialogs.add(choicePrompt);

        await adapter.send('Hello')
            .assertReply('Please choose a color.')
            .send('')
            .assertReply('Please choose a color.')
            .send({ type: ActivityTypes.Message, text: null })
            .assertReply('Please choose a color.')
            .send('1')
            .assertReply('red');
    });
```

Does this resolve your issue?

**Comment by MatthiasGwiozda** [comment]
The testAdapter works completly different from the DialogTestClient. Where can I see the reply of the bot?

The following line sends a message:

```JavaScript
await adapter.send('Hello')
```

Afterwards you are directly asserting that the reply contains specific values.

When I can't see the replyof the bot I will have a tough task to debug complex dialogs. With the DialogTestClient it's easy to see the reply:

```JavaScript
const reply = await client.sendActivity("hi");
```

So do I have to decide if I can see the reply or want to use the TurnContext?

**Comment by v-kydela** [comment]
@MatthiasGwiozda - What do you mean by "see the reply"? With `TestFlow`, you assert the reply. Is there something you want to do with the reply other than check that the reply is correct? I thought you were trying to write a unit test.

**Comment by MatthiasGwiozda** [comment]
Yes sure. But what do you do if you want to test:

- Adaptive Card - Properties
- Button - Properties

This will be hard without the reply of the bot in the debugger as json - object.

**Comment by v-kydela** [comment]
@MatthiasGwiozda - Are you saying the problem is that you need to be able to assert more than just the activity's text? That's easily done with `TestFlow`, as can be seen in this [choice prompt test](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-dialogs/tests/choicePrompt.test.js#L864-L869):

```js
        adapter.send('Hello')
            .assertReply(response => {
                assert(response.attachments.length === 2);
                assert(response.attachments[0].contentType === CardFactory.contentTypes.adaptiveCard);
                assert(response.attachments[1].contentType === CardFactory.contentTypes.heroCard);
            });
```

I can help you if you let me know what you're trying to do and what you're having difficulty with. Are you willing to give it a try?

**Comment by v-kydela** [comment]
@MatthiasGwiozda - Are you still working on this?

**Comment by MatthiasGwiozda** [comment]
Ok this example is nice. When would I use [botbuilder-testing](https://www.npmjs.com/package/botbuilder-testing) instead of TestFlow?

And why are there two possibilities to do the same tests?

**Comment by v-kydela** [comment]
@MatthiasGwiozda - While I have spent some time trying to figure out the unique purpose of [`DialogTestClient`](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-testing/src/dialogTestClient.ts), it's still a mystery to me. My best guess is that while `TestFlow` is used to test dialogs from the bot's perspective, `DialogTestClient` is used to test dialogs from the client's perspective. That is to say, a client won't know what's going on inside a bot with its turn context and all that, and will just see the bot's outgoing activities. In the end, a dialog test client will end up just giving you less information so it's still hard to see why that would be preferred over `TestFlow`. A dialog test client uses a test adapter internally anyway.

It's possible that these two overlapping classes were just a result of multiple teams working on the SDK simultaneously and coming up with their own ways of doing things.

Does this resolve your issue?

**Comment by MatthiasGwiozda** [comment]
Understood! Thank you for your time. I think we have to switch to TestFlow as it gives us more flexibility.

Everything we can do with DialogTestClient, TestFlow can do it aswell. And even more.
