### ISSUE TITLE
SentimentAnalysis LUIS

### ISSUE THREAD

**Issue by DHOFM** [Microsoft/botbuilder-js#280]
Hi,
i do not find any implementation of the LUIS sentimentAnalysis in the object model of the bot builder Framework. The plain JSON looks like this
...
"sentimentAnalysis": {
    "label": "neutral",
    "score": 0.5
...

Is there any reference or will it come in a later release?

Kind regards,

Dirk

**Comment by DHOFM** [comment]
i have debugged the botbuilder and the problem is, that there is no implementation
 of sentimentAnalysis. This could be added easily as it looks like this:
in the LuisRecognizer.js class you find the recognize function and after

try {
                    if (res && res.statusCode === 200) {
                        result = JSON.parse(body);

the result has an object called sentimentAnalysis but there is no further implementation
of this (see the onRecognize implementation in the LuisRecognizer)

Will this be added or can i fork my own implementation for further releases?

**Comment by yochay** [comment]
complete with  #340
