### ISSUE TITLE
Restore JSDoc configuration in eslint configuration file(s) and emit errors in CI

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#2840]
In https://github.com/microsoft/botbuilder-js/commit/7b7484b1a85e6196203b43fcb40bc3c271b258a2 via #2814 the JSDoc eslint ovrerides were removed.

We may restore parts of the [overrides](https://github.com/microsoft/botbuilder-js/commit/7b7484b1a85e6196203b43fcb40bc3c271b258a2#diff-df39304d828831c44a2b9f38cd45289cL25-L29), but the JSDoc lint violations will be treated as errors in CI.

_Overrides snippet:_
```json
"FunctionDeclaration": true,
"MethodDefinition": true,
"ClassDeclaration": true,
"ArrowFunctionExpression": false,
"FunctionExpression": false
```

**Comment by stevengum** [comment]
Moving out to R12 with the expectation that this will come online in phases (potentially a package-by-package basis)

**Comment by joshgummersall** [comment]
Closing in favor of https://github.com/microsoft/botbuilder-js/issues/2745 as we do have JSDoc linting.
