### ISSUE TITLE
TestAdapter uses wrong type for template parameter in constructor

### ISSUE THREAD

**Issue by ctstone** [Microsoft/botbuilder-js#285]
The constructor for `TestAdapter` asks for a `ConversationReference` template, but merges this with a value that is type `Partial<Activity>`.

This does not affect tests written in JavaScript, but for tests written in TypeScript, it is a compile error.

Incompatible types makes it impossible (without assigning to `any`) to overwrite the default `Activity` test values for `from`, `recipient`, etc., in unit tests.

**Comment by Stevenic** [comment]
Thanks... Just took the PR
