### ISSUE TITLE
formatDateTime(<date>, 'dd/MM/yyyy) should produce "dd/MM/yyyy" and not "dd:MM:yyyy"

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#2864]
## Versions
adaptive-expressions ^4.9.2

## Describe the bug
Originally reported in https://github.com/microsoft/AdaptiveCards/issues/4842

> I agree that `formatDateTime(<date>, 'dd/MM/yyyy)` should produce "dd/MM/yyy" and not "dd:MM:yyyy". This would be an Adaptive Expression issue though.
>
> {{DATE}} uses the system's (browser's) locale settings to generate date/time strings in the user's selected locale.

_@dclaux via https://github.com/microsoft/AdaptiveCards/issues/4842#issuecomment-702856391_

`formatDateTime(<date>, 'dd/MM/yyyy)` isn't covered in [our unit tests](https://github.com/microsoft/botbuilder-js/blob/2fff3d8a62c44ba07be2a528672e7d9206a8b916/libraries/adaptive-expressions/tests/expressionParser.test.js#L496-L516) and needs to be added.

@boydc2014 can you size this issue and assign a priority and owner for R11? Thanks!

**Comment by stevengum** [comment]
@boydc2014 The [original issue's author](https://github.com/microsoft/AdaptiveCards/issues/4842#issuecomment-703164981) indicated that `dd/MM/yy` is also a desirable format.

**Comment by boydc2014** [comment]
Thanks @stevengum, @cosmicshuai will look at this soon
