### ISSUE TITLE
Unused locale argument in defaultTokenizer

### ISSUE THREAD

**Issue by stevengum** [Microsoft/botbuilder-js#287]
The optional string arg `locale` is not used at all in the [defaultTokenizer][defaultTokenizer].

```ts
export function defaultTokenizer(text: string, locale?: string): Token[] {
```

  [defaultTokenizer]: https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-choices/src/tokenizer.ts#L65

**Comment by Stevenic** [comment]
That's correct.  The default tokenizer doesn't do any locale specific tokenization but its replaceable with one that does.
