### ISSUE TITLE
Obtain new code coverage badges via Azure DevOps

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#2871]
Continuation of https://github.com/microsoft/botbuilder-js/issues/1480

Obtaining the code coverage badge from Azure Devops isn't straightforward as the JS builds run on a private ADO project. 

The PR CI for botbuilder-dotnet runs in a public ADO project, so services such as https://shields.io can get the data without any issue:

![Azure DevOps coverage](https://img.shields.io/azure-devops/coverage/fuselabs/sdk_public/730)

Which was obtained from https://shields.io/category/coverage.

**Comment by joshgummersall** [comment]
I think Coveralls provides badges that are public.

[![Coverage Status](https://coveralls.io/repos/github/microsoft/botbuilder-js/badge.svg?branch=main)](https://coveralls.io/github/microsoft/botbuilder-js?branch=main)

**Comment by stevengum** [comment]
Now that I think about it, the Coveralls reports are fine for `main`. Most of the team's frustrations with Coveralls stemmed from the poor reporting for PRs.

Closing issue.
