### ISSUE TITLE
tests should not ship with botbuilder-dialogs-adaptive (and maybe others)

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-js#2879]
We currently ship tests with botbuilder-dialogs-adaptive.  We should not it just makes packages big.

 Directory of C:\tmp\dumb\node_modules\botbuilder-dialogs-adaptive\tests

10/08/2020  04:30 PM    <DIR>          .
10/08/2020  04:30 PM    <DIR>          ..
10/26/1985  01:15 AM            27,037 activityFactory.test.js
10/26/1985  01:15 AM             3,613 adaptiveCard.json
10/26/1985  01:15 AM             6,943 beginSkill.test.js
10/26/1985  01:15 AM             3,449 choiceSet.test.ts
10/26/1985  01:15 AM               720 expressionProperty.test.ts
10/26/1985  01:15 AM             1,837 inputDialog.test.js
10/26/1985  01:15 AM             1,182 languageGeneratorConverter.test.js
10/08/2020  04:30 PM    <DIR>          lg
10/26/1985  01:15 AM            10,862 LGGenerator.test.js
10/26/1985  01:15 AM             1,028 lgTelemetryUtil.js
10/26/1985  01:15 AM             1,818 logAction.test.js
10/26/1985  01:15 AM                84 mocha.opts
10/08/2020  04:30 PM    <DIR>          qna
10/26/1985  01:15 AM             3,889 qnaMakerRecognizer.test.js
10/26/1985  01:15 AM            19,693 recognizer.test.js
10/26/1985  01:15 AM             1,757 sendActivity.test.js
10/26/1985  01:15 AM             1,930 updateActivity.test.js

**Comment by stevengum** [comment]
As @benbrown mentioned offline, this problem might be more widespread than just  BotBuilder-dialogs-adaptive. We’ll need to check the new/preview adaptive/declarative libraries.

**Comment by joshgummersall** [comment]
Reopening to track other libraries.
