### ISSUE TITLE
TeamsActivityHandler <teams event>Event() methods have incorrect doc strings

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botbuilder-js#2897]
Per discussion w/ @stevengum, there's two different ways that developers can handle Teams Activities:

1. Use the older callback chaining by passing in callbacks, or
2. Use inheritance and override the methods in `TeamsActivityHandler`

The methods in [`TeamsActivityHandler`](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/teamsActivityHandler.ts) are *supposed* to fit the following scheme:

* Methods **starting with `handle`** (e.g. `handleTeamsTaskModuleFetch()`) must be overridden by the developer, if the developer wants the bot to handle Invoke activities, and
* Methods **ending with `Event`** (e.g. `onTeamsMembersAddedEvent()`) can be used by passing in callbacks, however
* Methods **starting with `on` and *not* ending in `Event`** (e.g. `onTeamsMembersAdded()`) can be overridden

The code in `TeamsActivityHandler` supports this. However, the [documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics-teams?view=azure-bot-service-4.0&tabs=javascript#teams-bot-logic) and the doc strings in the code are wrong. Both of these [suggest that the developer override the `...Event()` methods](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/teamsActivityHandler.ts#L681):

```js
    /**
     * Override this in a derived class to provide logic for when members other than the bot
     * leave the channel, such as your bot's good-bye logic.
     * @param handler
     * @returns A promise that represents the work queued.
     */
    public onTeamsMembersRemovedEvent(
        handler: (
            membersRemoved: TeamsChannelAccount[],
            teamInfo: TeamInfo,
            context: TurnContext,
            next: () => Promise<void>
        ) => Promise<void>
[...]
```

**To-do:**
- [ ] JS SDK Fix
- [ ] Docs Fix @JonathanFingold: I might submit a docs PR for this, but let me know if you'd prefer to.

**Comment by JonathanFingold** [comment]
@mdrichardson I'm swamped this week. I can update the article next week, or if you want to address it before then, I can review your PR.

**Comment by mdrichardson** [comment]
@JonathanFingold No problem. I'll make a PR for it in the docs repo after I finish the code portion.
