### ISSUE TITLE
Typing indicator support on V4

### ISSUE THREAD

**Issue by angie4u** [Microsoft/botbuilder-js#290]
Hello team, I tried to use typing indicator on V4 refer to this code. 
https://github.com/Microsoft/botbuilder-js/blob/5ee414f3b7ee9e7cd6f337a9a71605947e19f70e/doc/botbuilder/enums/botbuilder.activitytypes.md#typing
My code is here and Bot returns **typing** message literally.
```
await dc.context.sendActivity(ActivityTypes.Typing)
```
![image](https://user-images.githubusercontent.com/16282358/42144791-005e4a60-7df8-11e8-8421-d83a2e245f30.png)
Could you check if this feature is currently under development or if I referenced the wrong library?

**Comment by Stevenic** [comment]
You need to send it as an activity object:

```
await dc.context.sendActivity({ type: ActivityTypes.Typing });
```

**Comment by angie4u** [comment]
Thanks for reply! It works well! I will close this issue!

**Comment by sanjeevgaut** [comment]
Hi It worked for me also in localhost/emulator. but when i deployed in azure it is not working. 
i can see there is delay in the response but typing is not coming

**Comment by NereaCabiedasMoreno** [comment]
i add this in my bot await dc.context.sendActivity({ type: ActivityTypes.Typing }); but not work

**Comment by sanjeevgaut** [comment]
Please try below.
var typing = new Activity() { Type = ActivityTypes.Typing };
      await stepContext.Context.SendActivityAsync(typing);

**Comment by NereaCabiedasMoreno** [comment]
@sanjeevgaut 
[onTurnError] unhandled error: DialogContextError: Activity is not defined
