### ISSUE TITLE
Change vmImage from macOS-10.15 to ubuntu-18.04 for all JS builds

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/botbuilder-js#2901]
Prerequisite: Orchestrator must first be Ubuntu-compliant. Dave Taniguchi's area.

**Comment by stevengum** [comment]
Primary goals here are to keep things fast and simple. Ubuntu images are generally smaller than other images which can aid in reducing CI duration. Additionally, there's still the filename case-sensitivity that is important to ensure the SDKs can built and be properly consumed across non-Windows platforms.

@joshgummersall, @mrivera-ms @munozemilio, @axelsrz do either you have any insights into this feature request?

**Comment by joshgummersall** [comment]
Works for me 👍

**Comment by BruceHaley** [comment]
Reopening this issue because the fix was reverted: Orchestrator errored under the switch to Ubuntu. Once Orchestrator is made ready for Ubuntu, this fix can be reapplied.

**Comment by joshgummersall** [comment]
Resolved.
