### ISSUE TITLE
Override AuthenticationConstants and or GovernmentConstants

### ISSUE THREAD

**Issue by Yobikap** [microsoft/botbuilder-js#2904]
Hi,

I have the following use case.

From our security department we have to be in control what goes in or out our network.
So we have an internal gateway and an external gateway. Our implementation of bot framework is deployed inside our internal gateway and all connections made from that goes through internal gateway to our the external gateway (internet).

Now the problem arise, when the bot framework does try to make connection when vpc = true we get the following error:

2020-10-15T15:06:35.952Z    9e9cccb4-89c5-43c0-b96d-c1d3cb19afca    ERROR    JwtTokenExtractor.getIdentity:err! FetchError: 
request to https://login.botframework.com/v1/.well-known/openidconfiguration failed, reason: getaddrinfo EAI_AGAIN login.botframework.com
    at ClientRequest.<anonymous> (/var/task/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}

So how do we override the constants in AuthenticationConstants that does contain the url to i.e. https://login.botframework.com/v1/.well-known/openidconfiguration

We would like to change the url to for example:
https://our-internal-gateway.com/botframework/login/v1/*

**Comment by ryanlengel** [comment]
@joshgummersall can you take a look at this? Thank you!

**Comment by efortes** [comment]
+1 :)

**Comment by joshgummersall** [comment]
@Yobikap in this case, it looks like you should be able to achieve this by modifying [this variable](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botframework-connector/src/auth/channelValidation.ts#L18). Can you give that a try?

@efortes perhaps this will cover your use case as well.

**Comment by efortes** [comment]
@joshgummersall I used the `botFrameworkConfig.openIdMetadata` config to override the url ( I still have to see if this is sufficient )

**Comment by chrimc62** [comment]
@johnataylor can you comment?  We have a new cloudadapter that is designed to do exactly this.  There is a C# preview in a few days and plan to bring to JS soon.

**Comment by joshgummersall** [comment]
Related: https://github.com/microsoft/botbuilder-js/issues/3000

**Comment by joshgummersall** [comment]
@efortes I suspect using `botFrameworkConfig.openIdMetadata` solved your problem. Feel free to reopen this issue if that's not the case.
