### ISSUE TITLE
IT (Italian) locale: when employing "numberPrompt", entering\]number (for example "1") , he gets the   E_MISSING_BUNDLE exception

### ISSUE THREAD

**Issue by scheyal** [microsoft/botbuilder-js#2916]
## Versions
What package version of the SDK are you using.
What nodejs version are you using
What browser version are you using
What os are you using

## Describe the bug
Give a clear and concise description of what the bug is.

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by joshgummersall** [comment]
This looks like a dupe of https://github.com/microsoft/botbuilder-js/issues/2911.
