### ISSUE TITLE
Qna Maker: While Opening Knowledge base, getting error: Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key.

### ISSUE THREAD

**Issue by usheveta** [Microsoft/botbuilder-js#294]
While opening my Knowledge bases in QnA Maker I'm getting the following error:
Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key.

How can we update the subscription key and where we need to update them?

**Comment by szul** [comment]
Can you provide some more context? Are you talking about opening your knowledge base inside of your chatbot code? Can you provided a code example of what you are trying?

Your subscription key is the access key on the cognitive service resource that QnA Maker creates in the Azure Portal. If you're using QnA Maker from the command line, you'll put this in your `.qnamakerrc`.

To use the QnA Maker from the botbuilder-js SDK, it currently needs (as of "4.0.0-preview1.2") , the knowledgeBaseId, endpointKey, and host. The endpoint key is on the QnA Maker web site when you log in, when you click on your name in the top right, and go to "manage endpoint keys."

It's possible that your endpoint key is wrong. If this is wrong, you will get an authorization exception in your code.

**Comment by sgellock** [comment]
Thanks again.
