### ISSUE TITLE
Formflow : Change flow of messages in Microsoft Bot Framework

### ISSUE THREAD

**Issue by usheveta** [Microsoft/botbuilder-js#296]
Hi,

I'm trying to change the flow of the form by the following code:

namespace FormBot.Models
{
    
    [Serializable]
    public enum SiteTemplate
    {
        Blog = 1,
        ProjectSite = 2,
        CommunitySite = 3,
        TeamSite = 4
    }
    
    [Serializable]
    public enum ConfidentialData
    {
        Yes = 1,
        No = 2,
    }
    [Serializable]
    public class RequestForm
    {
        public string SiteName { get; set; }
        public SiteTemplate siteTemplate;
        public string SiteOwner { get; set; }
        public ConfidentialData ConfidentialData;
        public bool AddOrRemoveUsers = true;
        public static IForm<RequestForm> BuildForm()
        {
            return new FormBuilder<RequestForm>()
                .Message("Welcome to Site Creation.")
                .Field(new FieldReflector<RequestForm> (nameof(siteTemplate))
                .SetActive(state => state.AddOrRemoveUsers)
                     .SetNext((value, state) =>
                     {
                         var selection = (SiteTemplate)value;

                         if (selection == SiteTemplate.Blog)
                         {
                             state.SiteOwner = null;
                             //state.SenderPhoneNumber = null;
                             return new NextStep(new[] { nameof(ConfidentialData) });
                         }
                         else
                         {
                             return new NextStep();
                         }
                     }))
                     .Field(nameof(SiteOwner))
                     .Field(nameof(SiteName))
                 .OnCompletion(async (context, profileForm) =>
                 {
                     // Tell the user that the form is complete  
                     await context.PostAsync("Thanks for Giving your parameters to create a site.");
                 })
                .Build();
        }
    }
}

But when ever I select
 selection == SiteTemplate.Blog, it goes in the loop and return "Sorry, my bot code is having an issue."

I'm not sure what I'm missing here. Kindly let me know what can be done.
Thanks.

**Comment by szul** [comment]
Might be better off posting this in the botbuilder-dotnet repo.

**Comment by sgellock** [comment]
please post on StackOverflow
