### ISSUE TITLE
Port: Fix issues with ExpectReplies and Invoke in SkillDialog

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-js#2962]
While adding BufferedReplies, type of InvokeResponse should be added to TurnState:

```cs
                        if (activity.Type == ActivityTypesEx.InvokeResponse)
                        {
                            TurnState.Add(BotFrameworkAdapter.InvokeResponseKey, activity);
                        }
```

https://github.com/microsoft/botbuilder-dotnet/pull/4845

And, on the Skill Dialog side, only one InvokeResponse should be sent.

**Comment by gabog** [comment]
Hi @joshgummersall, this is a last minute bug that we need to port to JS, would you be able to address it so it goes in the next RC for R11?

**Comment by joshgummersall** [comment]
Yep, working on it.
