### ISSUE TITLE
Unable to use WebPack 4 with an OOTB TypeScript Echo Bot

### ISSUE THREAD

**Issue by AkumaTen** [microsoft/botbuilder-js#2998]
Hello!
I generated a simple TypeScript Echo bot that works as expected if built with npm run build. I tried to add WebPack 4.44.2 to the OOTB code and ts.config.json, and now I get:

### WebPack errors and warnings if target is default

- first warning: WARNING in ./node_modules/formidable/lib/incoming_form.js 1:43-50
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
- last warning: WARNING in ./node_modules/restify/lib/server.js
Module not found: Error: Can't resolve 'http2' in '&lt;my bot dir&gt;\node_modules\restify\lib'
- first error: ERROR in ./node_modules/pidusage/lib/bin.js
Module not found: Error: Can't resolve 'child_process' in '&lt;my bot dir&gt;\node_modules\pidusage\lib'
- last error: ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in '&lt;my bot dir&gt;\node_modules\tunnel-agent'

### WebPack warnings if target is node

- first warning: WARNING in ./node_modules/formidable/lib/incoming_form.js 1:43-50
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
- last warning: WARNING in ./node_modules/ws/lib/validation.js
Module not found: Error: Can't resolve 'utf-8-validate' in '&lt;my bot dir&gt;\node_modules\ws\lib'

## Versions
What package version of the SDK are you using: generator-botbuilder@4.10.3
What nodejs version are you using: v10.21.0
What os are you using: Microsoft Windows [Version 10.0.19041.572]

## Expected behavior
able to use WebPack 4 with the OOTB generated Bot Code

**Comment by joshgummersall** [comment]
The [`javascript_nodejs`](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs) and [`typescript_nodejs`](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/typescript_nodejs) samples are intended to run in a Node.js environment. It's no surprise that Webpack fails to compile the project when the target is not `node`. In fact, the two errors cite missing packages that are native to Node.js.

There are a few browser-based samples, however. In particular, the [01.browser-echo](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_es6/01.browser-echo) might serve as a good template for your use case.

Hopefully, this is helpful. Please reopen the issue if you need further help with this issue.

**Comment by AkumaTen** [comment]
@joshgummersall thanks for the web sample!
I'm anyway interested in having that Bot running on Node and tested with the emulator. I tried the build with the default target to see the differences.

How can I setup WebPack to successfully suppress the warnings with target = node?  
Thanks

**Comment by joshgummersall** [comment]
Here are the steps I took (note that this will use webpack 5. I'm not sure if there is any configuration that doesn't apply to webpack 4):

```bash
yo botbuilder # select echobot, typescript, create "echobot" directory
cd echobot
npm i --save-dev webpack webpack-cli webpack-node-externals ts-loader
```

Now, use this webpack config:

```javascript
const path = require('path');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  target: 'node',
  externals: [nodeExternals()],
  entry: './src/index.ts',
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader'
      }
    ]
  },
  resolve: {
    extensions: ['.ts']
  },
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  }
}
```

Modify the `package.json` scripts to invoke `webpack` for building (rather than `tsc`) and then change `lib/index.js` to `dist/bundle.js` everywhere.

I'm not a webpack expert by any means. That said, when you're running a bot in Node.js, there's no reason to bundle dependencies. They will be resolved correctly at runtime by Node.js. It slows down your webpack build quite a bit, and you don't gain any real benefits. If you were building a bundle to serve to the browser, you would want to bundle everything.

**Comment by AkumaTen** [comment]
It works, great!
What happens to node_modules once the Bot is deployed in Azure? Are the modules installed automtically in Azure because of package.json?

**Comment by joshgummersall** [comment]
[This guide](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=javascript) walks through deploying a bot to Azure. In particular, there is a step where you produce a Zip file with your entire source code along with all dependencies. As long as you have everything installed and working locally, that Zip file should contain everything Azure needs to run the bot.

**Comment by AkumaTen** [comment]
Thank you very much for your support!

**Comment by joshgummersall** [comment]
@AkumaTen glad to help!
