### ISSUE TITLE
DeliveryMode.Expect Replies doesn't send first batch of buffered activities

### ISSUE THREAD

**Issue by Zerryth** [microsoft/botbuilder-js#3008]
## Versions
* `@next` version, which at the time of testing: 4.12.0-dev.20201105.708bc57
* Emulator

## Describe the bug
After forwarding first message from user to skill, first set of buffered activities, never get sent back to the user.

## To Reproduce
1. Get a copy of sample 81.[skills-skilldialog](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/81.skills-skilldialog).
2. Use `DeliveryMode.ExpectReplies` in DialogRootBot's MainDialog by adding ` skillDialogArgs.activity.deliveryMode = DeliveryModes.ExpectReplies;`:

```js
    async callSkillActionStep(stepContext) {
        const selectedSkill = stepContext.values[this.selectedSkillKey];

        let skillActivity;
        switch (selectedSkill.id) {
            case 'DialogSkillBot':
                skillActivity = this.createDialogSkillBotActivity(stepContext.result.value, stepContext.context);
                break;
            // We can add other case statements here if we support more than one skill.
            default:
                throw new Error(`Unknown target skill id: ${ selectedSkill.id }`);
        }

        // Create the BeginSkillDialogOptions and assign the activity to send.
        const skillDialogArgs = { activity: skillActivity };

        skillDialogArgs.activity.deliveryMode = DeliveryModes.ExpectReplies;

        // Save active skill in state.
        await this.activeSkillProperty.set(stepContext.context, selectedSkill);

        // Start the skillDialog instance with the arguments.
        return await stepContext.beginDialog(selectedSkill.id, skillDialogArgs);
    }
```
3. Run both DialogRootBot and DialogSkillBot.
4. Speak to the bot, selecting DialogSkillBot as the skill you want to call. 
   * To mimic the message that I would get from DL Speech (what I was originally testing), I typed in "book flight" instead of selecting with a number choice
5. **Notice how after saying "book flight", which should be the first message forwarded to the skill, you get no response**
6. Type in a city name, despite not seeing a response from the bot, to continue the dialog (what the dialog is expecting you to respond with)
    * Notice how you can now see subsequent activities responses from Skill --> Parent --> User, despite not seeing the first set of buffered activities

## Expected behavior
For user to receive all buffered activities

## Additional context
Originally encountered when trying to verify if streaming works with skills in JS ([issue#2981](https://github.com/microsoft/botbuilder-js/issues/2918)).
___
### Expected
*Emulator, Default DeliveryMode*
![image](https://user-images.githubusercontent.com/35248895/98410173-05eb8080-2029-11eb-9fd9-4b723c634c1f.png)

* Saying "book flight" is the first message from the user, that will get forwarded to the skill.
* Notice how the response to book flight is the LUIS result, and a question of "To what city would you like to travel?"
* Additionally the traces from the first response to the skill actually show up as well

### Actual
*Emulator, DeliveryMode.ExpectReplies*
![image](https://user-images.githubusercontent.com/35248895/98410417-7eead800-2029-11eb-9001-f1edc881677f.png)

*Web Chat + DL Speech, DeliveryMode.ExpectReplies*
![image](https://user-images.githubusercontent.com/35248895/98410463-95912f00-2029-11eb-91c4-4170e2bef6ac.png)

* Notice how in the actual, *the first batch of buffered activities to reply with that contain the skill's first response to the user's "book flight" message are gone*
   * 2 messages containg LUIS result + asking user "To what city..." is missing
   * Several traces are not there 
   * Stepping through there are supposed to be 5 activities sent total, none make it through
* However, since I happen to know what the dialog is expecting, I notice that I could continue the dialog by telling it a city name
   * Then you notice the buffered replies actually come through, but only for the subsequent activities--you never get the first set of missing activities

___
### How it affects other parts of the SDK:
From #2981 
> * If you want to use skills with streaming, you need to use `DeliveryMode.ExpectReplies`, as the default mode won't work
> * Skills + streaming works, but in a buggy manner
>   * You don't get the first set of buffered activities after connecting to a skill, which makes it appear like your conversation dies
>   * In this artificial environment, where I am a user that happens to know what to say next to continue the dialog, I managed to get the dialog to go on, and was therefore able to see skills + streaming work in action, after the initial bug
>  * Given that this behavior happens in both streaming and non-streaming scenarios, it appears ExpectReplies is what's behaving oddly, not the streaming bits

**Comment by EricDahlvang** [comment]
Please try cloning the skillActivity before changing the delivery mode:

```js
        skillActivity = JSON.parse(JSON.stringify(skillActivity));
        skillActivity.deliveryMode = DeliveryModes.ExpectReplies;
```

Otherwise, the underlying turn context's DeliveryMode is changed and messages are sent back to the emulator as part of the body of the response.  The emulator is not expecting this.

**Comment by Zerryth** [comment]
@EricDahlvang you've done it! Things are working as expected now 🎊 

```js
    async callSkillActionStep(stepContext) {
        const selectedSkill = stepContext.values[this.selectedSkillKey];

        let skillActivity;
        switch (selectedSkill.id) {
            case 'DialogSkillBot':
                skillActivity = this.createDialogSkillBotActivity(stepContext.result.value, stepContext.context);
                break;
            // We can add other case statements here if we support more than one skill.
            default:
                throw new Error(`Unknown target skill id: ${ selectedSkill.id }`);
        }

        // Create the BeginSkillDialogOptions and assign the activity to send.
        skillActivity = JSON.parse(JSON.stringify(skillActivity));
        const skillDialogArgs = { activity: skillActivity };
        skillDialogArgs.activity.deliveryMode = DeliveryModes.ExpectReplies;

        // Save active skill in state.
        await this.activeSkillProperty.set(stepContext.context, selectedSkill);

        // Start the skillDialog instance with the arguments.
        return await stepContext.beginDialog(selectedSkill.id, skillDialogArgs);
    }
```

![image](https://user-images.githubusercontent.com/35248895/99294445-eb6b9100-27f8-11eb-986e-c906317fca8a.png)
