### ISSUE TITLE
Updated ms-rest-js version causes build to fail

### ISSUE THREAD

**Issue by BKHMSI** [Microsoft/botbuilder-js#301]
This latest [commit](https://github.com/Microsoft/botbuilder-js/commit/f37679ad26ec64421f175a8ba9fdd1b0f01c7bb7) that upgraded the ms-rest-js package to 0.3.1 from 0.2.5 gives me the following errors when running `npm test`

<img width="1280" alt="test" src="https://user-images.githubusercontent.com/14313972/42884458-acc878ae-8a9e-11e8-9c41-2bf33704d3cd.png">

**Comment by stevengum** [comment]
This should be fixed by #299, when it is merged.
