### ISSUE TITLE
[PORT] Make cycle detection throw an exception instead of returning null

### ISSUE THREAD

**Issue by chon219** [microsoft/botbuilder-js#3021]
https://github.com/microsoft/botbuilder-dotnet/pull/4606

Remove the two-step passes and the cache logic. Just throw an exception when detecting the loop.

**Comment by chon219** [comment]
We cannot implement _cycle detection_ feature right now because we don't have callstack support in js sdk, but cycle reference is supported.

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. Closing as Not Needed.
