### ISSUE TITLE
Create Mocks for our CogService calls and CosmosDB tests

### ISSUE THREAD

**Issue by stevengum** [Microsoft/botbuilder-js#303]
1. Create mocks for our Cognitive Services tests, specifically the services LUIS, QnA Maker and Translation.
2. Create mocks for the CosmosDB tests (or a suitable alternative) as the current tests fail with alarming consistency.

___

Currently the CosmosDB Storage tests timeout with these [helpful messages](https://github.com/Azure/azure-documentdb-node/blob/15cf138373beb86b9678e5cb4d09ad2c2fe1fb34/source/lib/endpointDiscoveryRetryPolicy.js#L61) spread throughout the [test results](https://travis-ci.org/Microsoft/botbuilder-js/builds/405933054#L604):

```bash
Error trying to connect, refreshing the regions list from database account and will retry the request.
```

**Comment by benbrown** [comment]
Part 1 is complete.

We still need Cosmos DB mocks.

**Comment by cleemullins** [comment]
Pushing to 4.4, as we'll be updating the CosmosDB stuff at that time.

**Comment by gabog** [comment]
Hi @stevengum, I had a talk with @cleemullins the emulators are running in the build agent for node in the new Azure DevOps pipeline and the tests are running there.

![image](https://user-images.githubusercontent.com/12264946/55803335-25ff3a80-5aa8-11e9-9102-070406227ce2.png)
