### ISSUE TITLE
[PORT] Add support for choosing assignment or operations

### ISSUE THREAD

**Issue by chon219** [microsoft/botbuilder-js#3040]
https://github.com/microsoft/botbuilder-dotnet/pull/4855

This adds support for choosing an assignment or operation. For example, "help" for your name will ask if you want to assign help to your name or get help.

Improved robustness for handling op + property when values are required.

Fixed some bugs around global operations and choosing between properties.

**Comment by joshgummersall** [comment]
@mdrichardson, here's another Adaptive parity issue for you when you get a chance.

**Comment by mdrichardson** [comment]
Note: I'll be rolling this into this one: https://github.com/microsoft/botbuilder-js/issues/3297
