### ISSUE TITLE
Adaptive Expressions does not offer minified bundle

### ISSUE THREAD

**Issue by matthidinger** [microsoft/botbuilder-js#3053]
### Use this [query](https://github.com/Microsoft/botbuilder-js/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
I'm using the adaptive-expressions bundle via a <script> tag, which we made available in PR #2940. That bundle currently weights 2.9MB and I didn't see a minified version or any consumption help in [the README](https://www.npmjs.com/package/adaptive-expressions). E.g., no explanation on how to consume via the <script> tag including a minified/non-min version.

**Describe the solution you'd like**
A minified version of the bundle should be provided to keep networking traffic down. Some basic usage docs in the README would also help.

/cc @atishayv

**Comment by stevengum** [comment]
`adaptive-expressions-ie11` has been minified via #3068, `adaptive-expressions` is still a WIP.
