### ISSUE TITLE
Update JS repo with new LUIS client SDK for JS

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-js#306]
This is to bring forward this change from C# Microsoft/botbuilder-dotnet#775 to JS

**Comment by sgellock** [comment]
@vishwacsena can you talk to Chris.  It's resolved, but there is additional work that needs to be tracked.

**Comment by benbrown** [comment]
It looks like we are using the most recent version of the library `azure-cognitiveservices-luis-runtime`. Is there another LUIS client library as well?

https://github.com/Microsoft/botbuilder-js/blob/e37311e13bf397ca80c5f475d91d6698d1a8b826/libraries/botbuilder-ai/package.json#L27

https://www.npmjs.com/package/azure-cognitiveservices-luis-runtime

**Comment by sgellock** [comment]
this is now done.
