### ISSUE TITLE
Botchat.js file takes 3 secs to load

### ISSUE THREAD

**Issue by deepanigi** [Microsoft/botbuilder-js#307]
Hi,

Is there any compressed version (gziped) of botchat.js .Right now i am using from the cdn link but it takes 504kb .

`https://cdn.botframework.com/botframework-webchat/latest/botchat.js`

**Comment by stevengum** [comment]
@deepanigi, this is the repository for the v4 botbuilder-js SDK. Can you please [**file an issue**](https://github.com/Microsoft/BotFramework-WebChat/issues/new) in the [BotFramework-WebChat](https://github.com/Microsoft/BotFramework-WebChat) repo? Someone more familiar with WebChat will be able to help you there. Thanks!
