### ISSUE TITLE
OrchestratorAdaptiveRecognizer Initialize not checking if resolver is null.

### ISSUE THREAD

**Issue by ecuellar2** [microsoft/botbuilder-js#3073]
I'm using 4.1.6 version of botbuilder-ai-orchestrator node module.
I am using OrchestratorAdaptiveRecognizer (orchestratorAdaptiveRecognizer.js)

I noticed recognize() performs the check below before calling Initialize().
(OrchestratorAdaptiveRecognizer.orchestrator === null || this.resolver === null)

But then in Initialize() it performs a slightly different check below.
(OrchestratorAdaptiveRecognizer.orchestrator == null && this.resolver == null) 

Is this intentional? I was expecting both to be using || to be consistent.
Otherwise, you hit onturnerror if you have orchestrator set but don't yet have your resolver set. In this case Initialize() would not do anything.

**Comment by taicchoumsft** [comment]
Transferred this ticket from CLI to botbuilder-js.
