### ISSUE TITLE
Base64 method in adaptive-expressions is not compatible with browsers

### ISSUE THREAD

**Issue by chon219** [microsoft/botbuilder-js#3084]
## Versions
main branch

## Describe the bug
`Buffer` is used for converting objects to base64 string in builtinFunctions.base64 of adaptive-expressions, which is only available in node.js.

## Expected behavior
adaptive-expressions should be compatible with browsers

## Additional context
https://stackoverflow.com/questions/246801/how-can-you-encode-a-string-to-base64-in-javascript/247261

**Comment by joshgummersall** [comment]
@chon219 I believe this is something `browserify` will handle for us. If you build adaptive expressions and then look try to load `lib/browser.js` in the browser, it should work. If it doesn't we should absolutely fix that 😄 .

**Comment by chon219** [comment]
> @chon219 I believe this is something `browserify` will handle for us. If you build adaptive expressions and then look try to load `lib/browser.js` in the browser, it should work. If it doesn't we should absolutely fix that 😄 .

Thx, I'm working on something converting strings to base64, can I use `Buffer` in botbuilder-js?

**Comment by joshgummersall** [comment]
You shouldn't have to do anything different from the Node.js code of `Buffer.from('some string', 'utf8').toString('base64')`. See https://github.com/joshgummersall/browserified for an example. Clone the repo, run `yarn && yarn build` and then open `index.html` in a browser and check the console output.

**Comment by chon219** [comment]
> You shouldn't have to do anything different from the Node.js code of `Buffer.from('some string', 'utf8').toString('base64')`. See https://github.com/joshgummersall/browserified for an example. Clone the repo, run `yarn && yarn build` and then open `index.html` in a browser and check the console output.

Thanks Josh, closing this issue.😁
