### ISSUE TITLE
CosmosDbPartitionedStorage Incorrectly requires authKey so you can't use token providers

### ISSUE THREAD

**Issue by JedLJRobertson** [microsoft/botbuilder-js#3085]
## Versions
npm package 4.11.0
node v10.15.3
nodeJS
Windows

## Describe the bug
CosmosClient, which the CosmosDbPartitionedStorage uses to access Cosmos, supports two authentication methods: authKey or tokenProvider. The latter is useful as it allows you to get more secure resource tokens that limit access as necessary and use them for access to the CosmosDB.

Theoretically, this should work fine (as far as I understand), _but_ CosmosDbPartitionedStorage throws an error if you do not set the authkey property. If you set the authKey property, then CosmosDB will try to use the given authKey instead of the given tokenProvider.

## To Reproduce
1. Try to construct a CosmosDbPartitionedStorage as follows:

```const botStorage = new CosmosDbPartitionedStorage({
    cosmosDbEndpoint: 'https://xxx.documents.azure.com:443/',
    cosmosClientOptions: {
        endpoint: 'https://xxx.documents.azure.com:443/',
        tokenProvider: async(info) => { console.log(info); return 'abc'; }
    },
    databaseId: 'some-database',
    containerId: 'some-container',
    compatibilityMode: false,
})
```

2. The code will fail as the constructor throws an error.

## Expected behavior
No error should be thrown, instead the CosmosClient can be created with the given configuration. Potentially, CosmosDbPartitionedStorage could check if either an authKey or tokenProvider are provided, but perhaps that verification should be a responsibility of CosmosClient and not CosmosDbPartitionedStorage.

## Note

I commented out the offending `throw` statement and it works.

**Comment by joshgummersall** [comment]
@JedLJRobertson, thanks for filing this issue! Can you take a look at the PR I just submitted? I think this covers your use case, but please review if you get a moment.

**Comment by JedLJRobertson** [comment]
Yes, those changes would fix the issue, I can add an approval to the PR if that's custom here? 

Thanks so much for looking at that so quickly Josh.
@joshgummersall

**Comment by joshgummersall** [comment]
Nope, I just wanted to triple check. Thanks!
