### ISSUE TITLE
[BotBuilder-Core] extendedUserTokenProvider interface does not match C# counterpart

### ISSUE THREAD

**Issue by Batta32** [microsoft/botbuilder-js#3089]
## Versions
What package version of the SDK are you using.
[botbuilder-core@4.11.0](https://www.npmjs.com/package/botbuilder-core/v/4.11.0)
What nodejs version are you using
[12.16.1](https://nodejs.org/en/blog/release/v12.16.1/)
What browser version are you using
\-
What os are you using
Windows 10 Pro

## Describe the bug
Give a clear and concise description of what the bug is.
The JavaScript implementation of `extendedUserTokenProvider` is missing the definition of `GetTokenStatus` method compared to C#.

## To Reproduce
1. Clone [BotBuilder-DotNet](https://github.com/microsoft/botbuilder-dotnet)
1. Navigate to `/libraries/Microsoft.Bot.Builder/OAuth/`
1. Open `IExtendedUserTokenProvider.cs`
1. Scroll down to [line 75](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/OAuth/IExtendedUserTokenProvider.cs#L75)
1. Clone [BotBuilder-JS](https://github.com/microsoft/botbuilder-js)
1. Navigate to `/libraries/botbuilder-core/src/`
1. Open `extendedUserTokenProvider.ts`
1. Search the `GetTokenStatus` method
1. Check that the method doesn't exist in the TypeScript interface

## Expected behavior
Give a clear and concise description of what you expected to happen.
I expect `extendedUserTokenProvider` in JavaScript to use the same implementation as in C#.

## Screenshots
_Missing method that is present in C#_
![image](https://user-images.githubusercontent.com/11904023/100116220-3cf7c980-2e52-11eb-8537-154c16833b9e.png)

## Additional context
\-

**Comment by joshgummersall** [comment]
The `ExtendedUserTokenProvider` extends from `IUserTokenProvider` which does hold the method in question. [See here for details](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-core/src/userTokenProvider.ts#L39). Please reopen this if there is something else missing. Thanks for filing the issue!
