### ISSUE TITLE
[BotBuilder-Core] ActivityHandler class does not match C# counterpart

### ISSUE THREAD

**Issue by Batta32** [microsoft/botbuilder-js#3100]
## Versions
What package version of the SDK are you using.
[botbuilder-core@4.11.0](https://www.npmjs.com/package/botbuilder-core/v/4.11.0)
What nodejs version are you using
[12.16.1](https://nodejs.org/en/blog/release/v12.16.1/)
What browser version are you using
\-
What os are you using
Windows 10 Pro

## Describe the bug
Give a clear and concise description of what the bug is.
The JavaScript implementation of `ActivityHandler` contains different method's implementation compared to C#. The main difference we found is in the `onConversationUpdateActivity` method.

## To Reproduce
1. Clone [BotBuilder-DotNet](https://github.com/microsoft/botbuilder-dotnet)
1. Navigate to `/libraries/Microsoft.Bot.Builder`
1. Open `ActivityHandler.cs`
1. Scroll down to [line 172](https://github.com/microsoft/botbuilder-dotnet/blob/665410b8efa8da5ff70b70efec19a4a5fc7a5d4d/libraries/Microsoft.Bot.Builder/ActivityHandler.cs#L172)
1. Clone [BotBuilder-JS](https://github.com/microsoft/botbuilder-js)
1. Navigate to `/libraries/botbuilder-core/src/`
1. Open `activityHandler.ts`
1. Scroll down to [line 664](https://github.com/microsoft/botbuilder-js/blob/150dfe563c9d3132bec55c4604503bceb462ff78/libraries/botbuilder-core/src/activityHandler.ts#L664)
1. See the differences

## Expected behavior
Give a clear and concise description of what you expected to happen.
I expect `ActivityHandler` in JavaScript to use the same implementation as in C#.

## Screenshots
![image](https://user-images.githubusercontent.com/11904023/100782404-1eae4280-33eb-11eb-8412-3096d2c94a7b.png)

## Additional context
Using Direct Line Channel, the Virtual Assistant and the Skill receives the `ConversationUpdate` Activity by duplicated sending the welcome message by duplicated as well.

Reviewing the TypeScript bots present in [BotBuilder-Samples](https://github.com/microsoft/BotBuilder-Samples), we noticed that the logic that should be present in the _ActivityHandler > dispatchConversationUpdateActivity_, is present in the `membersAdded` event of the bots. See [example](https://github.com/microsoft/BotBuilder-Samples/blob/8e8fed1f4f09932ff63cbdea8de70306b41dc424/generators/generator-botbuilder/generators/app/templates/empty/bot.ts#L12).

See related information:
- [Microsoft Bot displays unnecessary duplicated messages in WebChat?](https://stackoverflow.com/a/62346827/8271560)
- [Identical Threads in Microsoft Bot are Duplicating Welcoming Message](https://stackoverflow.com/a/62346702/8271560)

**Comment by stevengum** [comment]
This differing behavior was shipped in the initial implementation, to avoid breaking changes for customers we've left the ActivityHandler behavior as is. However, the expected C# logic was implemented in the ActivityHandlerBase class and could be reimplemented in a subclass of ActivityHandler. Alternatively, @Batta32 you could directly subclass ActivityHandlerBase which would make the VA Template/Solution more aligned. (No event listeners, all desired methods must be implemented in a subclass)

https://github.com/microsoft/botbuilder-js/blob/150dfe563c9d3132bec55c4604503bceb462ff78/libraries/botbuilder-core/src/activityHandler.ts#L84

https://github.com/microsoft/botbuilder-js/blob/150dfe563c9d3132bec55c4604503bceb462ff78/libraries/botbuilder-core/src/activityHandlerBase.ts#L116-L134

**Comment by Batta32** [comment]
Thanks @stevengum for the detailed information! That's a great idea, however, we are following a parity with the C# bots extending the `DefaultActivityHandler` to [`TeamsActivityHandler`](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs#L21) (VA) and [`ActivityHandler`](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/skill/SkillSample/Bots/DefaultActivityHandler.cs#L17) (Skill).

We think that the **best approach** is to add the same logic that the TypeScript samples bots contain in the [`onMembersAdded`](https://github.com/microsoft/BotBuilder-Samples/search?l=TypeScript&q=membersAdded) method as they are extending to the [`ActivityHandler`](https://github.com/microsoft/BotBuilder-Samples/search?l=TypeScript&q=extends+ActivityHandler) and not to the `ActivityHandlerBase` class.
Applying this we can have a parity between C# VA/Skill - TypeScript VA/Skill and also, parity with the BotBuilder-Samples bots.

**Comment by stevengum** [comment]
Thanks for filing this issue and providing additional information! 

Given that the TypeScript samples should mirror the behavior of the JS samples, the team will need to have a discussion whether or not to change the _JS & TS samples'_ behavior to match C#. In the meantime, I'm closing this issue as a `wontfix` because these changes in the SDK would be breaking.
