### ISSUE TITLE
Rendered AdaptiveCard throws Exception if text has HTML markup

### ISSUE THREAD

**Issue by alevinetx** [microsoft/botbuilder-js#3117]
## Versions
What package version of the SDK are you using.
    "adaptive-expressions": "4.11.0",
    "botbuilder": "4.11.0",
    "botbuilder-ai": "4.11.0",
    "botbuilder-dialogs": "4.11.0",
    "botbuilder-dialogs-adaptive": "4.11.0-preview",
    "botbuilder-dialogs-declarative": "4.11.0-preview",
    "botbuilder-lg": "4.11.0",

What nodejs version are you using

$ node --version
v13.14.0

$ npm --version
6.14.4

What browser version are you using
n/a

What os are you using
cygwin/win7

## Describe the bug
Text that contains HTML markup causes an error when rendering an Adaptive Card in the context of "Send A Response" activity
`DialogContextError: Error: Error: Unexpected token in JSON at position ...`

The same source content renders fine when using adaptivecards.io/designer/

## To Reproduce
1. Send a Response Bot Response:
```# RealTicketCard(ticket)
[Activity
    attachments = ${json( TicketTemplate(  ticket )  )}
]

# TicketTemplate(root)
....
 {
     "type": "TextBlock",
     "text": "Text with HTML in it : ${root.badHtmlField} "
  }
```

Bad text looks like this:
```
<p>words and words and words.</p>\n\n<p>words and words and words again</p>
```

## Expected behavior
I assumed it would silently ignore the markup in the text itself, likely passing it through as literal text.

## Screenshots
n/a

## Additional context
If there's a recommended scrubber to use to sanitize the text before passing it in to templates, that would be useful to know

**Comment by alevinetx** [comment]
The stack trace points to 
``` 
botbuilder-dialogs-adaptive\lib\generators\multiLanguageGeneratorBase.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\me\mybot\runtime\node_modules\botbuilder-dialogs-adaptive\lib\generators\multiLanguageGeneratorBase.js:10:12)
```

where the rendered js section looks like this:
```
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
10:    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
14:         step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
```

**Comment by hcyang** [comment]
Hi @stevkan, any update?

**Comment by alevinetx** [comment]
@stevkan  
 `
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
`

and I should clarify, it's during the interpolation process that I mean rendering (replacing tokens with real values), and not the client visual display.   So this is happening before it reaches the UI.  But, I'm using both Teams and the Emulator during my dev work.

**Comment by stevkan** [comment]
Hi @alevinetx, the error you are receiving is due to the `\n\n` bit of code needing to be properly escaped. If you are wanting new lines to be rendered using that code, then it needs to be updated to `\\n\\n`. Once escaped, the text (with the remaining HTML) displays.

As for scrubbing any HTML out of a string, there are various recommendations already available on the web. There are many more, but here are a couple discussions:

- https://stackoverflow.com/questions/6234773/can-i-escape-html-special-chars-in-javascript
- https://stackoverflow.com/questions/1787322/htmlspecialchars-equivalent-in-javascript
