### ISSUE TITLE
Issue: Text formatting in adaptive card on Teams Android App doesn't reflect

### ISSUE THREAD

**Issue by razxssd** [microsoft/botbuilder-js#3129]
## Versions
What package version of the SDK are you using.
4.11.0
What nodejs version are you using
14.2.0
What browser version are you using
Teams App
What os are you using
Android

## Describe the bug
Hi,

I have implemented an adaptive card published on a channel through bot framework.

We have applied italic formatting as per documentation ("_text_") (https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html) but while it's rendered in desktop and ios app, it not correctly diplayed in andorid app.

Here the card payload and app screenshots for reference.

Adaptive card:

`{

      "type": "AdaptiveCard",

      "body": [

        {

          "type": "ColumnSet",

          "columns": [

            {

              "type": "Column",

              "items": [

                {

                  "type": "Image",

                  "url": "https://i.ibb.co/m8Z5Hfc/telegram-logo.png",

                  "size": "Small"

                }

              ],

              "width": "auto"

            },

            {

              "type": "Column",

              "items": [

                {

                  "type": "TextBlock",

                  "weight": "Bolder",

                  "text": "12312314",

                  "wrap": true

                },

                {

                  "type": "TextBlock",

                  "spacing": "None",

                  "text": "Received On 2020-12-7 10:22:35",

                  "isSubtle": true,

                  "wrap": true

                }

              ],

              "width": "stretch"

            }

          ]

        },

        {

          "type": "FactSet",

          "facts": [

            {

              "title": "Message",

              "value": "_Hello_"

            },

            {

              "title": "Assigned To",

              "value": "hello.eduard@hello.it"

            },

            {

              "title": "Due Date",

              "value": "2020-12-8 10:22:35"

            }

          ]

        },

          {

          "type": "ActionSet",

          "actions": [

            {

              "type": "Action.Submit",

              "title": "Close",

              "data": { "action": "close" }

            }

          ]

        }

      ],

      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",

      "version": "1.2"

    }`

## Expected behavior
The text should be formatted correctly on each platform / OS, like Desktop / Android / IOS

## Screenshots
Result on Desktop:

[Desktop Screenshoot](https://i.ibb.co/PjdgwHw/Teams-desktop.jpg)

As you can see 'Hello' text is formatted ok on desktop, but on Android the result is this:

[Android Screenshoot](https://i.ibb.co/nL5DpKx/teams-android.jpg)

While on IOS it's working too:

[IOS Screenshoot](https://i.ibb.co/8M5fQ86/teams-ios.jpg)

**Comment by joshgummersall** [comment]
@razxssd I think this issue should be reported to the [microsoft/AdaptiveCards](https://github.com/microsoft/AdaptiveCards) repository.
