### ISSUE TITLE
Moment.js is now in legacy/maintenance mode

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#3133]
Relevant read: https://momentjs.com/docs/#/-project-status/

In some areas of the SDK, `moment` and `moment-timezone` are not being used in _integral-and-non-replaceable_ manners and could potentially be easily replaced (the SDK should not be shipping any public dependency on `moment`). However, this may not be the case in some of the newer Adaptive-related libraries. @boydc2014, @chon219, or @Danieladu are more familiar with these libraries and probably have invaluable insight here.

In addition to Moment.js' legacy status, size of the package is a nudge to consider moving from `moment` if possible.

The Moment.js team has [recommended a few alternatives](https://momentjs.com/docs/#/-project-status/recommendations/) to `moment` that should be explored (including [moment/luxon](https://github.com/moment/luxon) and [Day.js](https://github.com/iamkun/dayjs/)).

**Comment by Danieladu** [comment]
Attach the guideline and practice https://github.com/you-dont-need/You-Dont-Need-Momentjs/blob/master/README.md
