### ISSUE TITLE
Blob Storage conditional header(s) is not met

### ISSUE THREAD

**Issue by luspac** [Microsoft/botbuilder-js#314]
I am having an issue with Blob Storage. 

I am able to read and write information to Blob Storage but receive a warning:
Unhandled promise rejection (rejection id: 1): StorageError: The condition specified using HTTP conditional header(s) is not met.

To access the Blob Storage I pass in my settings. 
```
const {BlobStorage} = require('botbuilder-azure');

var storage = new BlobStorage({
    containerName: '<container name>',
    storageAccountOrConnectionString: '<account or connection string>',
    host: '<host>'
});
```

The definition of BlobStorage requires a storageAccessKey but I immediately get thrown an error if I add that parameter to the Blob Storage connection. 

The way in which I am accessing the storage is handled in this function below. Any insight into this would be much appreciated. 

```
async function logMessageText(storage, context) {
    let utterance = context.activity.text;
    let storeItems = await storage.read(["UtteranceLog"])
    console.log(storeItems);
    try {
        // check result
        var utteranceLog = storeItems["UtteranceLog"];

        if (typeof (utteranceLog) != 'undefined') {
            // log exists so we can write to it
            storeItems["UtteranceLog"].UtteranceList.push(utterance);

            try {
                await storage.write(storeItems)
                context.sendActivity('Successful write to utterance log.');
            } catch (err) {
                context.sendActivity(`Write failed of UtteranceLog: ${err}`);
            }

        } else {
            context.sendActivity(`need to create new utterance log`);
            storeItems["UtteranceLog"] = { UtteranceList: [`${utterance}`]}

            try {
                await storage.write(storeItems)
                context.sendActivity('Successful write to log.');
            } catch (err) {
                context.sendActivity(`Write failed: ${err}`);
            }
        }
    } catch (err) {
        context.sendActivity(`Read rejected. ${err}`);
    };
}
```

**Comment by xtellurian** [comment]
I'm seeing the same issue.

```js
const adapter = new BotFrameworkAdapter({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

var container_name = process.env.BLOB_CONTAINER; // container name
var storageAccountName = process.env.STORAGE_ACCOUNT_NAME; // single string, eg, 'test'
var storageAccountKey = process.env.STORAGE_ACCOUNT_KEY; //base64 encoded key
storage = new BlobStorage({ storageAccountOrConnectionString: storageAccountName, containerName: container_name, storageAccessKey: storageAccountKey });

const conversationState = new ConversationState<EchoState>(storage);
adapter.use(conversationState);
```

Authentication is correct - the container was created.

No blobs are created.

Package info:
-- botbuilder-azure@4.0.0-preview1.2
  -- azure-storage@2.10.0

-- botbuilder@4.0.0-preview1.2

**Comment by yochay** [comment]
@stevengum  will update storage packages

**Comment by stevengum** [comment]
Currently investigating...

**Comment by szul** [comment]
@stevengum In my case, no blobs were actually created in the blob containers.

Something to note: With both this and table storage, something like @xtellurian's code is what throws the error for me; however, if I take that same blob storage or table storage object that has been initialized, and try to read/write to it, I can do so successfully. The error seems to be exclusively with state management.

**Comment by stevengum** [comment]
#369 is currently on hold while we wait for @stevenic to weigh in.

**Comment by sgellock** [comment]
fix merged into master.
