### ISSUE TITLE
 getting error applicationId of undefined for luis while integrating bot composer luis todo bot using Botbuilder-js sdk

### ISSUE THREAD

**Issue by GLakshmiSravanthi** [microsoft/botbuilder-js#3152]
### Issue
 we are using bot builder-JS SDK with version 4.11.0 . We are taking the bot files from the bot composer and trying to run bot with that files. We integrated the files and able to run the bot but when we are using luis it is asking for the secret keys and we are passing it through expression as we get from the bot composer but it was unable to get the keys.

When we checked in the bot composer folder the folder structure is like this 
![image](https://user-images.githubusercontent.com/67416683/102348848-7b535500-3fc8-11eb-9da7-6cb84f72b30e.png)

 
From here we have `. dialog file` for every parent and child dialogs in recognizer folder and there is `appsettings.json` and `luis.settings.composer.westus.json` file.
The content in the dialog file will be like this, there are expressions to get the keys
```
{
  "$kind": "Microsoft.LuisRecognizer",
  "id": "LUIS_additem",
  "applicationId": "=settings.luis.additem_en_us_lu.appId",
  "version": "=settings.luis.additem_en_us_lu.version",
  "endpoint": "=settings.luis.endpoint",
  "endpointKey": "=settings.luis.endpointKey"
}
```
So, we kept the secret keys in two .json files but when we run the bot it is unable to get the keys from the json files and getting error that application ID of undefined for luis 
![image](https://user-images.githubusercontent.com/67416683/102348715-47782f80-3fc8-11eb-88b4-cd40eb917bfe.png)

 

### Solutions we tried
We removed the expression in the `.dialog file` and placed the secret keys in the file bot working fine.
### Our question 
Is there any function in botbuilder-js SDK that it will take the settings from the appsettings.json file?
Or is there any way to set the settings so that when the bot runs it will take from the appsettings.json or .env file

@stevengum please help us in solving this issue.

**Comment by dmvtech** [comment]
I am investigating this.

**Comment by dmvtech** [comment]
Hi @GLakshmiSravanthi, to clarify you are running the bot without composer (like exporting the Node runtime and using `node .\lib\webapp.js`), correct?

When running in Composer, you will be using the LUIS _authoring_ key and LUIS applications applicable to that. So, now that you are running with the prediction resource, I assume you might be able to just update the application IDs (`appId`) to be the ones in your prediction resource, but I am not sure if that is the suggested/appropriate approach. I will investigate further.

**Comment by GLakshmiSravanthi** [comment]
Thanks for the response 
yes @dmvtech we are not using the bot composer.
Okay let me more clarify 
we are creating the bot in bot composer and then we are taking the exported files. We are integrating exported bot files to our project using BotBuilder-js SDK, here we are reading the recourses from the files and loading in to ResourceExplorer and then we are adding the dialog's. 
![image](https://user-images.githubusercontent.com/67416683/102436317-500b4d00-403e-11eb-9f51-ff0221ecabb9.png)

 
> When running in Composer, you will be using the LUIS _authoring_ key and LUIS applications applicable to that. So, now that you are running with the prediction resource, I assume you might be able to just update the application IDs (`appId`) to be the ones in your prediction resource, but I am not sure if that is the suggested/appropriate approach. I will investigate further.

In bot composer when we click on run bot will get a popup asking to give luis authoringKey. Yes have to change the prediction resources but where we have to change. When we checked in `.dialog file` got the expression like this `"=settings.luis.additem_en_us_lu.appId"`. We got two settings files from bot composer on is `appsettings.json file` as 
![image](https://user-images.githubusercontent.com/67416683/102437199-2b17d980-4040-11eb-8e8f-bd3a46091a97.png)
In this file we don't have appId, so we placed authoringKey and endpointKey. But when we checked in another settings file i.e  `luis.settings.composer.westus.json` here we have appId
![image](https://user-images.githubusercontent.com/67416683/102437590-c4df8680-4040-11eb-9e82-946663937d69.png)

so, we updated in both files but when run the bot it is unable to get the keys with the expression. 
 > I assume you might be able to just update the application IDs (`appId`) to be the ones in your prediction resource
 
 Does it means we need to manually replace the expression with values in resource file.

**Comment by gabog** [comment]
Hi @dmvtech, do you have any updates on this issue?
Thanks

**Comment by dmvtech** [comment]
Hi @GLakshmiSravanthi 

Still trying to discover what is the correct approach. 

@luhan2017 Let me know when we can discuss this.

**Comment by dmvtech** [comment]
Hi @GLakshmiSravanthi Can you check the [LUIS portal](https://www.luis.ai/applications/), and verify you have an LUIS application that has that Id (`b31aeaf3-3511-495b-a07f-571fc873214b`). This _should_ match the same Id listed in the `luis.settings.composer.westus.json` file. If found in the portal, go to **Manage->Azure Resources** and let me know if it has a prediction resource assigned or not.

**Comment by GLakshmiSravanthi** [comment]
hi @dmvtech 
ID in `luis.settings.composer.westus.json` file match with the Luis application id in portal. No, it don't have prediction resources.

**Comment by GLakshmiSravanthi** [comment]
hi @dmvtech 
Is there any update on this issue?

**Comment by GLakshmiSravanthi** [comment]
hi @dmvtech
Is there any update on this issue?

**Comment by GLakshmiSravanthi** [comment]
when can we expect update on the issue ?  @gabog , @stevkan please once check on the issue
Thank you

**Comment by dmvtech** [comment]
Hi @GLakshmiSravanthi My apologies for the delay.

Once you have authored your bot and LUIS applications using Composer and the LUIS authoring key, what you want to do is go into your LUIS portal and [assign a prediction resource](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-how-to-azure-subscription#assign-a-resource-to-an-app). Then you would set (as you already have) your [prediction] endpoint key (and other prediction endpoint values as needed) so that now these LUIS applications will then be accessible through the prediction endpoint. 

Please test and let me know if you still come across issues.

**Comment by GLakshmiSravanthi** [comment]
@dmvtech tried with prediction resources but unable to resolve the Issue.
I tried to check in code of botbuilder-js modules, correct me if I gave wrong information.

checked from where getting the error `"Invalid applicationId value detected: undefined Please make sure your applicationId is a valid LUIS Application Id, e.g. "b31aeaf3-3511-495b-a07f-571fc873214b"."` got to know that it is from [validateLuisApplication()](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-ai/src/luisRecognizer.ts#L591) function and this function is used in [constructor](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-ai/src/luisRecognizer.ts#L322) to check the Luis key. I tried to log the values of `application` because from that taking the `applicationId, endpoint, endpointKey ` values. 

![image](https://user-images.githubusercontent.com/67416683/104811928-d9bc5f00-5824-11eb-95cc-906a108e669f.png)

_**Tried two scenario's**_
_Without giving the applicationId and endpointKey in `ToDoBotWithLuisSample-0.en-us.lu.dialog` file_
![image](https://user-images.githubusercontent.com/67416683/104811973-11c3a200-5825-11eb-9bb5-837738f3148b.png)
_Logs_ 
![image](https://user-images.githubusercontent.com/67416683/104811994-33248e00-5825-11eb-8bc4-df0b4eeb4fe6.png)
If the equations for applicationId and endpointKey getting the values are undefined.

_With giving the applicationId and endpointKey in `ToDoBotWithLuisSample-0.en-us.lu.dialog` file_
![tempsnip](https://user-images.githubusercontent.com/67416683/104812069-bc3bc500-5825-11eb-880b-6ff0be477bf8.png)
_Logs_
![tempsnip](https://user-images.githubusercontent.com/67416683/104812098-ec836380-5825-11eb-944b-13259db019ed.png)
If we gave the direct values `application` getting the values.

could you please explain us why applicationId and endpointKey are getting the their default values i.e. undefined when we tried to give the applicationId by an equation.

**Comment by a-b-r-o-w-n** [comment]
@dmvtech are you able to take a look at this again?

**Comment by luhan2017** [comment]
@GLakshmiSravanthi do you have the code logic to read the settings from luis.settings.composer.westus.json? Similar as this https://github.com/microsoft/BotFramework-Composer/blob/main/runtime/node/src/shared/helpers.ts#L63. We need to have this logic to load the settings correctly.

**Comment by chon219** [comment]
If you don't want to use the stock `webapp.js` exported from composer, you have to do the following things to load correct settings from files:
1. load settings via `getSettings(projectRoot)`: e.g. https://github.com/microsoft/BotFramework-Composer/blob/73c0bcecc04cf809838fc23870cb5613722fcd22/runtime/node/src/shared/composerBot.ts#L54
2. set settings to your dialog manager's initial state with correct key `settings`: e.g. https://github.com/microsoft/BotFramework-Composer/blob/73c0bcecc04cf809838fc23870cb5613722fcd22/runtime/node/src/shared/composerBot.ts#L94

**Comment by GLakshmiSravanthi** [comment]
Thankyou all 
It worked

**Comment by dmvtech** [comment]
Great to hear. Glad you got it working. Thanks again for your patience.

**Comment by stevkan** [comment]
Closing, per request.
