### ISSUE TITLE
Missing replyToId from the context.activity in the MessagingExtension card.

### ISSUE THREAD

**Issue by svalio** [microsoft/botbuilder-js#3159]
## Versions
What package version of the SDK are you using. "botbuilder": "^4.11.0",
What nodejs version are you using: node:12.16.3
What browser version are you using: --
What os are you using: macOs

## Describe the bug
Give a clear and concise description of what the bug is.
I am using compose extension to render adaptive card. The adaptive card has Action. Submit button on it. As mentioned in this article I expect to receive a "replyToId" field from the context.activity, but when I click on the submit button replyToId equals "-1".

## To Reproduce
1. Go to Compose extension section
2. Select any card with the submit action button 
3. Click on the submit button 
4. See error, replyToId = -1

## Expected behavior
I would like to see the actual replyToId value so I could update this card after submitting as mentioned here: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions#inbound-message-example

## Screenshots
![image](https://user-images.githubusercontent.com/36510050/103095656-0efcd500-460a-11eb-906a-8936327f2c4a.png)
https://user-images.githubusercontent.com/36510050/103095797-90546780-460a-11eb-910a-300ff8fd166d.mov

**Comment by EricDahlvang** [comment]
Hi @svalio 

Unfortunately, Adaptive Card submit actions do not include a replyToId in the activity:
https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions#adaptive-cards-actions

**Comment by clearab** [comment]
The adaptive card submit action does not include a replyToId field because there is no guarantee that the action came from any particular message. You could have sent the same card multiple times to various contexts. If you want to update the message that contains the adaptive card, you'll need to store the necessary information when you send the message.
