### ISSUE TITLE
Add uuid function to botbuilder-stdlib

### ISSUE THREAD

**Issue by joshgummersall** [microsoft/botbuilder-js#3160]
See [here](https://github.com/microsoft/botbuilder-js/pull/3151#discussion_r548073591) for context.

**Comment by chon219** [comment]
Can we just use [this library](https://github.com/uuidjs/uuid) to create RFC-compliant UUIDs instead of using our own implementation which may cause potential collision?

**Comment by joshgummersall** [comment]
@chon219 I've used that library a lot in past projects, so I don't see why not - I wonder why we didn't use that from the beginning, though. Does it work in all our environments, i.e., browser, React Native, etc.?

**Comment by chon219** [comment]
@joshgummersall It should work in all our environments, quoted from the README of this library:

> Cross-platform - Support for ...
> CommonJS, ECMAScript Modules and CDN builds
> Node 8, 10, 12, 14
> Chrome, Safari, Firefox, Edge, IE 11 browsers
> Webpack and rollup.js module bundlers
> React Native / Expo
