### ISSUE TITLE
Messaging extensions: Missing Input.ChoiceSet options in adaptive card

### ISSUE THREAD

**Issue by rmincheva** [microsoft/botbuilder-js#3169]
## Versions
botbuilder v4.11.0
nodejs v13.12.0
OS Ubuntu 18.04.3 LTS

## Describe the bug
A messaging extension returns from search a list of items. After selecting an item from the list, an adaptive card is rendered containing the following items :

- A single select  (Input.ChoiceSet -> style: 'compact', sMultiSelect: false)
- A ShowCardAction -> shows another adaptive card containing a single select

The options of the single select are missing. When clicking on the showCardAction, the options of the select in the child adaptive card are present. When pasting the card in the chat, the options of both selects are missing. When replacing the single selects with radios (Input.ChoiceSet -> style: 'expanded', sMultiSelect: false), the options are present. The same card can be returned also from the bot and then everything is rendered correctly.

## Expected behavior
The single select options are present after selecting the item from the search result of a message extension and after pasting the card in the chat

## Screenshots

1. When an item from the search result is selected ->
![ms_teams_messaging_extension_1_selected_item](https://user-images.githubusercontent.com/76813555/103411350-c85e2c00-4b6f-11eb-85ba-1a528e669743.png)

2. When the card is pasted in the chat ->
![ms_teams_messaging_extension_2_pasted_card](https://user-images.githubusercontent.com/76813555/103411397-078c7d00-4b70-11eb-8b7b-fe1440b0ec47.png)

3. When the bot returns the same card  ->
![ms_teams_messaging_extension_3_returned_from_bot](https://user-images.githubusercontent.com/76813555/103411419-21c65b00-4b70-11eb-8f1a-227443ae7c04.png)

**Comment by v-kydela** [comment]
Thank you for the report, @rmincheva. Would you be willing to provide some additional information?

1. Repro steps
1. Links to any documentation or samples you've followed
2. The Adaptive Card JSON
3. The relevant parts of your messaging extension code
4. The relevant parts of your app manifest

**Comment by Nikitha-MSFT** [comment]
@rmincheva as kyle  mentioned - Could you please share more details?

**Comment by rmincheva** [comment]
**Preconditions**
A search based messaging extension with one parameter "query" is created. After the search request is executed a list of items is returned. After an item is selected(tapped) another request is made for retrieving additional data for the item and a detailed card is shown.

**Steps to reproduce**
1. Enter a search query.
2. Select an item -> A card is shown, containing a select "dummySelect", but the select options are missing.
3. Click the "Forward" action -> Another card is shown, containing a select "forwardAssignee" -> the options are present (this is correct).
4. Copy the card and paste it in a chat -> The select options of the "dummySelect" in the main card are missing.
5. Click the "Forward" action-> The select options of the "forwardAssignee" select are missing.

**Message extension code**

The following function is executed when the user enters the search query->
```javascript 
async function searchJobs(context, action) {
    const {httpConfig} = context
    const query = action.parameters.find(parameter => parameter.name === 'query')
    const jobs = await https.searchJobs({query: query && query.value, httpConfig})
    const attachments = jobs.map(job => {
        const {descriptionId, name, locale} = job
        const card = JobThumbnailCard({name})
        card.content.tap = {
            type: 'invoke',
            value: {
                commandId: messageCommands.getJobByDescriptionId,
                parameters: {
                    descriptionId,
                    locale
                }
            }
        }
        return {...card}
    })
    return MessageFactory.createListMessage(attachments)
}
```

After an item from the search result is clicked the following function is executed->

```javascript
async function getJobByDescriptionId(context, action) {
    const {httpConfig} = context
    const {descriptionId, locale} = action.parameters
    const job = await https.getJobByDescriptionId({descriptionId, locale, httpConfig})
     .
     .
     .
    const assignees = [
        {
            name: 'Assignee 1',
            id: '1'
        },
        {
            name: 'Assignee 2',
            id: '2'
        }
    ]
    return MessageFactory.createListMessage([JobCard({...job, assignees})])
}
```

**The Adaptive card JSON (JobCard)**
 ```json
 {
  "contentType": "application/vnd.microsoft.card.adaptive",
  "content": {
    "version": "1.2",
    "body": [
      {
        "weight": "Bolder",
        "size": "Medium",
        "type": "TextBlock",
        "text": "J-2735"
      },
      {
        "isSubtle": true,
        "wrap": true,
        "type": "TextBlock",
        "text": " this is a description "
      },
      {
        "id": "dummySelect",
        "choices": [
          {
            "title": "Option 1",
            "value": "1"
          },
          {
            "title": "Option 2",
            "value": "2"
          }
        ],
        "type": "Input.ChoiceSet",
        "style": "compact",
        "isMultiSelect": false
      }
    ],
    "actions": [
      {
        "title": "Forward",
        "card": {
          "body": [
            {
              "id": "forwardAssignee",
              "choices": [
                {
                  "title": "Assignee 1",
                  "value": "1"
                },
                {
                  "title": "Assignee 2",
                  "value": "2"
                }
              ],
              "type": "Input.ChoiceSet",
              "style": "compact",
              "isMultiSelect": false
            },
            {
              "id": "forwardComment",
              "isMultiline": true,
              "placeholder": "Enter your forward comment",
              "type": "Input.Text"
            }
          ],
          "actions": [
            {
              "title": "Submit",
              "data": {
                "commandId": "forwardJob",
                "instanceId": 3080,
                "locale": 0
              },
              "type": "Action.Submit"
            }
          ]
        },
        "type": "Action.ShowCard"
      }
    ]
  },
  "preview": {
    "contentType": "application/vnd.microsoft.card.thumbnail",
    "content": {
      "title": "J-2735",
      "text": " this is a description ",
      "images": [
        {
          "url": "https://picsum.photos/id/160/500"
        }
      ]
    }
  }
}
```

Have in mind that if the selects are replaced with radios, the options are displayed correctly:
The Adaptive card with radios
```json
{
  "contentType": "application/vnd.microsoft.card.adaptive",
  "content": {
    "version": "1.2",
    "body": [
      {
        "weight": "Bolder",
        "size": "Medium",
        "type": "TextBlock",
        "text": "J-2735"
      },
      {
        "isSubtle": true,
        "wrap": true,
        "type": "TextBlock",
        "text": " this is a description "
      },
      {
        "id": "dummySelect",
        "choices": [
          {
            "title": "Option 1",
            "value": "1"
          },
          {
            "title": "Option 2",
            "value": "2"
          }
        ],
        "type": "Input.ChoiceSet",
        "style": "expanded",
        "isMultiSelect": false
      }
    ],
    "actions": [
      {
        "title": "Forward",
        "card": {
          "body": [
            {
              "id": "forwardAssignee",
              "choices": [
                {
                  "title": "Assignee 1",
                  "value": "1"
                },
                {
                  "title": "Assignee 2",
                  "value": "2"
                }
              ],
              "type": "Input.ChoiceSet",
              "style": "expanded",
              "isMultiSelect": false
            },
            {
              "id": "forwardComment",
              "isMultiline": true,
              "placeholder": "Enter your forward comment",
              "type": "Input.Text"
            }
          ],
          "actions": [
            {
              "title": "Submit",
              "data": {
                "commandId": "forwardJob",
                "instanceId": 3080,
                "locale": 0
              },
              "type": "Action.Submit"
            }
          ]
        },
        "type": "Action.ShowCard"
      }
    ]
  },
  "preview": {
    "contentType": "application/vnd.microsoft.card.thumbnail",
    "content": {
      "title": "J-2735",
      "text": " this is a description ",
      "images": [
        {
          "url": "https://picsum.photos/id/160/500"
        }
      ]
    }
  }
}
```

**App manifest** 
```json
.
.
 "composeExtensions": [
    {
      "botId": "15d66618-4f03-4a3a-b18d-558eea92e92d",
      "canUpdateConfiguration": true,
      "commands": [
        {
          "id": "searchJobs",
          "type": "query",
          "title": "Jobs",
          "description": "Your Jobs search query",
          "initialRun": false,
          "fetchTask": false,
          "context": [
            "compose",
            "commandBox",
            "message"
          ],
          "parameters": [
            {
              "name": "query",
              "title": "Search Query",
              "description": "Your search query",
              "inputType": "text"
            }
          ]
        }
      ]
    }
  ]
  .
  .
  ```
  
**Followed examples and documentation**

1. https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/50.teams-messaging-extensions-search
2. https://adaptivecards.io/explorer/

**Comment by gabog** [comment]
Hi @Nikitha-MSFT, do you have any updates on this issue?

Thanks

**Comment by Nikitha-MSFT** [comment]
We are able to repro the issue at our end. Raised a bug.

**Comment by gabog** [comment]
Hi @Nikitha-MSFT, is there a link to the bug that we can share with @rmincheva for tracking? 

Thanks

**Comment by clearab** [comment]
The Teams group is currently working on this Issue, but there is not ETA on a fix. Updates will be provided as they become available.

**Comment by clearab** [comment]
I'm migrating this issue over to the Teams folks so that they may follow up directly. Please go here for further tracking https://github.com/MicrosoftDocs/msteams-docs/issues/3556
