### ISSUE TITLE
Missing LICENSE files and invalid package.json

### ISSUE THREAD

**Issue by j-buckland** [microsoft/botbuilder-js#3192]
- The workspaces in the `libraries` directory are missing LICENSE files (e.g. [here](https://github.com/microsoft/botbuilder-js/tree/main/libraries/botbuilder-core)). Although it's strictly not necessary as there is one at the root of the repo, it would make it clearer for users to have the LICENSE file alongside the package.json. This is fairly common practice (e.g. https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2864)

- The package.json files for the packages in the `libraries` directory have version which don't match the tags of the code, or the root level package.json. (See [package.json](https://github.com/microsoft/botbuilder-js/blob/4.11.0/libraries/botbuilder-core/package.json#L5) where the version is the file is 4.1.6, the tag of the code is 4.11.0. I understand that you are using [lerna](https://github.com/lerna/lerna#independent-mode) to manage versions, but I would suggest making sure the version listed in the code at the tag agrees with whatever lerna uses (even if the workspace package.json doesn't have a version - it's better for it not be wrong). This would make it less confusing for those new to your project to understand!

**Comment by joshgummersall** [comment]
Thanks for reporting, @j-buckland! I've added the issue to our backlog.

**Comment by sw-joelmut** [comment]
@mrivera-ms in progress
