### ISSUE TITLE
High severity security vulnerability (axios) in current sdk version 

### ISSUE THREAD

**Issue by amir-microsoft** [microsoft/botbuilder-js#3199]
## Versions
What package version of the SDK are you using - 4.12.0
What nodejs version are you using 14.11.0

## Describe the bug
you have a dependency on @azure/ms-rest-js": "1.9.0" which is using an outdated version of axios (0.19), which has a High severity security vulnerability: Server-Side Request Forgery

## Expected behavior
you should upgrade to @azure/ms-rest-js": "1.9.1", which is using axios 0.21.1

**Comment by joshgummersall** [comment]
We have a patch going out tomorrow. If you are using the 4.12 version you must be on the "next" tag which should be patched already. Thanks for submitting the issue!

**Comment by amir-microsoft** [comment]
sorry, I was mistaken @joshgummersall - I'm using 4.10.3, so it's not patched.
You are saying you are releasing a patch version tomorrow? for 4.11?

**Comment by joshgummersall** [comment]
We will have a patch for 4.10 and 4.11 going out first thing tomorrow.

**Comment by amir-microsoft** [comment]
That's great. Thanks!
