### ISSUE TITLE
context.deleteActivity not working with Teams iOS app

### ISSUE THREAD

**Issue by matthiasdilger** [microsoft/botbuilder-js#3208]
## Versions
botbuilder 4.9.0
nodejs v12.16.2
iOS 14.3
latest version of Teams mobile app for iOS

## Describe the bug
sending context.deleteActivity(activityId) to the Teams iOS client has no effect, the activity is not deleted
Works on android, web and desktop

## To Reproduce
The bot sends an adaptive card to the user with an Action.Submit button "delete"
The user presses the button
The bot receives the activity and executes `context.deleteActivity(context.activity.replyToId)`
Nothing happens

## Expected behavior
The app should delete the card

## Additional context
Works on android, web and desktop

**Comment by clearab** [comment]
The client has no control really over the conversation log - does the message delete successfully after updating the UI? Maybe by navigating away and back?

**Comment by clearab** [comment]
@tacri can you escalate to the right folks?

**Comment by matthiasdilger** [comment]
> does the message delete successfully after updating the UI? Maybe by navigating away and back?

@clearab Yes, but not always. 

Example #1:
iOS user is inside chat with bot
bot sends adaptive card
user presses delete
UI does not update
user navigates back
in the list of chats the last status for the bot chat is "message has been deleted"
user navigates to chat again and card is gone

Example #2:
iOS user is in list of chats, not inside bot chat
bot sends card
user uses desktop to delete the card, this reflects on desktop immediately
iOS: in the list of chats the last status for the bot chat is "message has been deleted"
user navigates to bot chat on iOS but card is still there (even though the user has not previously opened the bot chat on iOS)
user navigates back to list of chats and right back into the bot chat
card is gone

This is some sort of caching issue on iOS and not related to the bot-framework. Thank you for forwarding it.

**Comment by clearab** [comment]
Yeah, this is almost certainly going to be an issue with the Teams iOS client. I'll make sure a bug get's filed on the right team.

**Comment by joshgummersall** [comment]
@clearab are we all set here?

**Comment by clearab** [comment]
@Wajeed-msft did a bug get filed for this one?

**Comment by RamaMohanaChary** [comment]
Hi @matthiasdilger,

We have tested the issue from our end, able to reproduce the issue. 
Took this issue as a high priority and raised a bug for this issue, concerned team is working on it, 
At present we don't have any ETA to share with you.

**Comment by matthiasdilger** [comment]
Just tested this again on iOS and the issue has been fixed. Thank you!
