### ISSUE TITLE
Investigate stale NPM Packages

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-js#3215]
The below list of NPM packages is stale. To maintain hygiene across the suite of NPM packages, we need to go through this list and take corrective action as needed on a per-package basis.

We have 2 options for each:

1. Mark as deprecated, [according to NPM rules](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions). 
2. Unpublish. Some of these packages are early -alpha, or -preview versions and are misleading. We should consider unpublishing these packages. 

The list of packages that need to be examined is:

1. botconnector. Last published 5 years ago as "0.9.6". 
2. botbuilder-calling. Last published 4 years ago. 
3. botbuilder-location. Last published 4 years ago. 
4. botbuilder-cognitiveservices. Last published 3 years ago. 
5. hubot-botframework. Last published 3 years ago. 
6. botframework-connector-auth. Last published 3 years ago as an "-alpha" version. **Consider unpublishing**
7. botbuilder-services. Last published 3 years ago as an "-alpha" version. **Consider unpublishing**
8. botbuilder-node. Last published 3 years ago as an "-alpha" version. **Consider unpublishing**
9.  botframework-luis. Last published 3 years ago as an "-preview" version. **Consider unpublishing**
10. botbuilder-choices. Last published 3 years ago as an "-preview" version. **Consider unpublishing**
11. botbuilder-schema. Last published 3 years ago using a weird version (4.0.0-m1.5). This was published by steven_ickman, and should have it's ownership normalized. 
12. botbuilder-core-extensions. Last published 3 years ago as an "-preview" version. **Consider unpublishing**
13. botbuilder-prompts. Last published 3 years ago as an "-preview" version. **Consider unpublishing**
14. generator-botbuilder-python. Last published 3 years ago. Need to clarify intent with with @axelsrz and @tracyboehrer 
15. generator-botbuilder-java. Last published 3 years ago. Need to clarify intent with with @tracyboehrer and @LeeParrishMSFT 
16. generator-botbuilder-assistant. Last published a year ago, and doesn't align with VA timelines. 
17. botframework-expressions. Last published a year ago, as a 4.7.2-preview version. **Consider unpublishing**
18. botframework-webchat-adapter-ic3. Last published a year ago with an "0.1.0-master" version. Clarify intent with @cwhitten and @compulim. **Consider unpublishing**

**Comment by joshgummersall** [comment]
I think the safest bet is to deprecate these packages - this will introduce warnings for consumers. In any case, it looks like all the packages have >1 owner/maintainer, which may make them ineligible for unpublishing. I'll go ahead and start deprecating these old packages today.

**Comment by EricDahlvang** [comment]
This is a v3 sdk package for luis and qna: **botbuilder-cognitiveservices**

was here: https://github.com/microsoft/BotBuilder-CognitiveServices

now here: https://github.com/microsoft/BotBuilder-V3/tree/main/Cognitive%20Services/Node

**Comment by joshgummersall** [comment]
Deprecating packages is pretty safe - existing consumers can still use them.
