### ISSUE TITLE
Remove .js & .map generated files form /lib/ folders

### ISSUE THREAD

**Issue by JuanAr** [Microsoft/botbuilder-js#323]
TypeScript compiler generates .js and .map files in the lib/ folder based on .ts files. These files could be ignored from the git repository since each time the solution is built those files will be overwritten.
Moreover, .js files might be inadvertently kept in the working folder exposing obsolete classes (they might no longer exists in .TS files) leading to runtime errors.

Should we remove the files and add the lib/ folders to the .gitignore file to prevent this in the future?

**Comment by stevengum** [comment]
There is a PR that enacts this enhancement and is currently in the review phase: #325 

Thanks for the suggestion!

**Comment by sgellock** [comment]
resolved, fixed.
