### ISSUE TITLE
DC.cancelAllDialogs(true) is not cancelling the skill level dialog stack

### ISSUE THREAD

**Issue by SreekanthOAuth** [microsoft/botbuilder-js#3236]
## Versions
"botbuilder": "^4.11.0",
"botbuilder-ai": "^4.11.0",
Typescript
Node Js: v11.6.0
Windows 10

## Describe the bug
We have VA and Skill. When the user wants to cancel the dialog in the middle of the conversation, we are calling cancelAllDialogs(true) to cancel all the dialogs. But it's not canceling all the dialogs.

Eg: 

**VA**: Click from below Department // here Department is the skill.
**User**: Create an order - This utterance would connect to skill.
**VA**: What do you want? -> [Served from Skill]
**User**: Cancel // this utterance begins the CancelDialog
**VA**: Are you sure you want to cancel the order? -> [Served from VA] // first step in CancelDialog waterfall to get the confirmation.
**User**: Yes // **we are trying to cancel the dialogs**
**VA**: Ok, Let's start over. // here all dialogs supposed to be closed.  [Served from VA] // Closing the all dialogs in CancelDialog by using cancelAllDialogs(true).
User: Show my previous order
**VA**: Sorry, we are not supporting this. Please try again // **This is actually the next step of What do you want?. Since the dialog is not canceled this is continuing.**  [Served from Skill]

## Expected behavior
All dialogs should be canceled.

But, when the dialog been served from VA and try to cancel by this method, then the dialogs are been canceled. This issue is only when we have connected to skill.

Thanks,
Sreekanth from Ecolab

**Comment by v-kydela** [comment]
Thank you for the report, @SreekanthOAuth 

If the skill has its own dialog state, then I would expect cancelling dialogs in the consumer to not affect the dialogs in the skill. It's hard to say without knowing more about your project, but it looks like your consumer dialogs may be canceled correctly and the "Show my previous order" utterance starts a new skill dialog in the consumer, and that skill dialog connects to the skill which already has a dialog underway. If that's the case, I can see two possible solutions:

1. In addition to cancelling the dialogs in the consumer, you could send an activity to the skill which indicates to the skill that it should also cancel its own dialogs
2. You could make sure the skill is using conversation state for its dialog state and also make sure a new skill conversation ID is generated each time a new skill dialog is started

To help us resolve this issue, please provide the following:

1. Repro steps
2. Links
3. Screenshots
4. The response you're expecting from the skill, as opposed to "Sorry, we are not supporting this. Please try again"

**Comment by v-kydela** [comment]
@SreekanthOAuth - Are you still working on this?

**Comment by SreekanthOAuth** [comment]
@v-kydela  - This is been fixed and working fine.
Thanks for the suggestion.

**Comment by v-kydela** [comment]
@SreekanthOAuth - Would you describe your solution in case other developers have the same problem?

**Comment by SreekanthOAuth** [comment]
@v-kydela . Sure.

We are checking the currently active dialog is skill level or not. If the active dialog is skill then we are not canceling the dialog in VA. So, it transfers to skill level and there we cancel the dialog in the interruption method. So for next step starts as expected.

Thanks,
Sreekanth
