### ISSUE TITLE
The latest Adaptive-Expressions pakcage breaks Composer client

### ISSUE THREAD

**Issue by cosmicshuai** [microsoft/botbuilder-js#3274]
After upgrade the version of Adaptive-Expressions to "4.12.0-dev-20210204.01545ea7b057". The Composer in browser was broken.
![image](https://user-images.githubusercontent.com/17074777/107010317-24e8e280-67d1-11eb-9307-356a57e0c4a9.png)
![image](https://user-images.githubusercontent.com/17074777/107010348-303c0e00-67d1-11eb-9a9c-a30bc61f37ae.png)

However, if I switched the version to the date befrore 20210125, there was no error occured. 
I think it was caused by https://github.com/microsoft/botbuilder-js/pull/3222, the tinify dropped something.

**Comment by boydc2014** [comment]
@joshgummersall should be put this in R12? since it's a blocker for composer. At composer side, we are pinning the version to the day before the tinify as a mitigation now.

**Comment by joshgummersall** [comment]
@boydc2014 a fix (courtesy of @stevengum) will be in the daily build tomorrow.
