### ISSUE TITLE
Teams: Action.Submit on adaptive card (invoked from message extension) sometimes sends wrong service url

### ISSUE THREAD

**Issue by matthiasdilger** [microsoft/botbuilder-js#3280]
## Versions
SDK 4.9
nodejs 12.20.1

## Describe the bug
Teams user invokes message extension of bot by using ellipsis on Teams message
Bot replies with a form in an adaptive card
User submits the form. The activity received by the bot **sometimes** contains a serviceUrl that is not valid for this user
Bot gets the conversation reference from the activity (TurnContext.getConversationReference(context.activity)) and sends a confirmation message to this user (adapter.createConversation(conversationRef, ...) using the wrong serviceUrl which results in error response with status code 403, code 'BadArgument' and message 'User is from different region'

Observed the following examples:
User installed the bot, install event received contained serviceUrl https://smba.trafficmanager.net/apac/
User submits adaptive card and serviceUrl received is https://smba.trafficmanager.net/jp/

User installed the bot, install event received contained serviceUrl https://smba.trafficmanager.net/emea/
User submits adaptive card and serviceUrl received is https://smba.trafficmanager.net/fr/

## To Reproduce
Note: This happens rarely (< 1% of the time?)

Teams user invokes message extension of bot
Bot receives invoke and replies with adaptive card that contains Action.Submit
Teams user clicks submit and bot receives wrong service url in handleTeamsMessagingExtensionSubmitAction()

## Expected behavior
The activity should always have a service url that allows the bot to send a reply to the user

## Additional context
I was only able to reproduce this issue for the message extension interaction described above but the issue could be in other interactions as well.
Workaround: catch BadArgument error, lookup serviceUrl from bot installation event and send the message again

**Comment by Virtual-Josh** [comment]
Hey @EricDahlvang,

Can you take a look at this?

**Comment by clearab** [comment]
@Wajeed-msft this one is for y'all :)

**Comment by matthiasdilger** [comment]
Should I send the activity logs somewhere?

**Comment by matthiasdilger** [comment]
It seems this issue might be related as well:

https://github.com/microsoft/botbuilder-js/issues/3298

**Comment by clearab** [comment]
Also seems to be related: https://github.com/microsoft/botframework-sdk/issues/6184

@tacri @Wajeed-msft

**Comment by matthiasdilger** [comment]
Hi @Wajeed-msft @clearab 

I am currently not seeing this issue anymore, it seems something has been changed (?) I will keep an eye on it for the next few days.

**Comment by matthiasdilger** [comment]
Have not observed this issue in the last couple of days, closing this issue. Thank you!
