### ISSUE TITLE
LUIS.AI 500 Character Limit

### ISSUE THREAD

**Issue by OneUp5hroom** [microsoft/botbuilder-js#3289]
## Describe the bug
When a customer submits a string over 500 Characters LUIS returns an error.

## To Reproduce
1. Send more than 500 Characters to a bot using LUIS

## Expected behavior
The 500 Character Limit is a built in limitation of LUIS, it would be expected that the bot framework truncate the text sent to LUIS to be 500 Characters or less. Allowing LUIS to return an intent and not cause an error. 

## Additional context
Error: "query" with value "#Text sent to bot#" should satisfy the constraint "MaxLength": 500 at failValidation. ... LUISRuntimeClient.ServiceClient.sendOperationRequest

Any questions let me know!
Thanks!

**Comment by joshgummersall** [comment]
Thanks for filing this issue, @OneUp5hroom!

From the perspective of the SDK, duplicating validation that an external API performs is wrought with issues. The simplest example is managing validation changes (what if LUIS decides to truncate to 400 characters in the future?).

A more complicated example is performing context-aware truncation (where should we truncate a given piece of text?). Simply chopping off characters 501+ would likely produce unintended results as well.

The LUIS API should be used for utterances (short phrases), not large pieces of text. See [this issue](https://github.com/microsoft/botframework-sdk/issues/2823#issuecomment-306928202) for some historical context.

Unfortunately, this is not an issue that we can fix properly inside the SDK.

**Comment by OneUp5hroom** [comment]
Yeah the problem we are running into is customers don't fully understand that copy pasting huge blocks of text is not the greatest lol. We have had instances where they copy paste large text blocks into the bot (long strings from emails...etc). The initial idea when submitting this was for the bot to not return an error from LUIS but allow the conversation to continue with whatever LUIS decides to return, which will probably be garbage but at least the customer doesn't get presented with an error. 

The reason I wanted to post here was if we can implement something in the framework for interacting with LUIS to handle this it could be done in one place, if we are to do it for the VA and all of our Skills it will be a lot more touch points and duplication of code. But it is possible for us to throw some error handling in and return a "training" message to let them know they submitted too much text.

What it sounds like from your message is this is not a problem that you guys are wanting to handle in the framework its self. If that is correct we can proceed with our own custom fix.... though I think it would be a good add to have a way to limit the characters a customer can submit to the bot. In a perfect world it could be configurable by the devs so we can set what we would like to set the limit to, it could even default to unlimited... this is probably getting into feature request territory though.

**Comment by joshgummersall** [comment]
That all makes sense - however, we don't feel comfortable duplicating LUIS API validation logic. In this case, you should proceed with the custom fix.

**Comment by OneUp5hroom** [comment]
Sounds good, thanks @joshgummersall
