### ISSUE TITLE
Create a read.me for NPM and overall for specific name space like Dialogs

### ISSUE THREAD

**Issue by yochay** [Microsoft/botbuilder-js#331]
There is a way to surface specific read.me for npm

- Ben

**Comment by benbrown** [comment]
- [ ] dialogs
- [ ] botbuilder
- [ ] core
- [ ] ai
- [ ] azure
- [ ] config
- [ ] schema?

**Comment by benbrown** [comment]
see #419

**Comment by stevengum** [comment]
@benbrown can we add instructions on how to get daily/nightly builds in each README? I noticed this didn't get in for #419. 

@sgellock, @stevenic

**Comment by benbrown** [comment]
#419 got merged, so now check out #421

**Comment by benbrown** [comment]
Botbuilder:  https://github.com/Microsoft/botbuilder-js/blob/benbrown/mainreadme/libraries/botbuilder/README.md

Botbuilder-ai:  https://github.com/Microsoft/botbuilder-js/blob/benbrown/mainreadme/libraries/botbuilder-ai/README.md

Botbuilder-core: https://github.com/Microsoft/botbuilder-js/blob/benbrown/mainreadme/libraries/botbuilder-core/README.md

Botbuilder-azure: https://github.com/Microsoft/botbuilder-js/blob/benbrown/mainreadme/libraries/botbuilder-azure/README.md

Botbuilder-dialog: https://github.com/Microsoft/botbuilder-js/blob/benbrown/mainreadme/libraries/botbuilder-dialogs/README.md

**Comment by sgellock** [comment]
Closing this ticket as it's address in the following pull, which has a merge dependency on published packages to npm.  Microsoft/botbuilder-js#421
