### ISSUE TITLE
Dialog will break if two version of botbuilder-dialog package exists

### ISSUE THREAD

**Issue by dilin-MS** [microsoft/botbuilder-js#3342]
Hi, we are developing a node package `my-package-A` based on botbuilder. 

The issue we met is that:
1. Our package `my-package-A` has `botbuilder-dialogs` package of the following version as dependency. And we develop a class `MySsoPrompt` extending `Dialog`.
    ```json
    "botbuilder-dialogs": "^4.11.1",
    ```
    ```javascript
    export class MySsoPrompt extends Dialog {}
    ```    

2. Our user has their `test-example` project which install our package `my-package-A` and also have installed certain version `4.11.0` of botbuilder package as dependency:
    ```json
    "my-package-A": "0.0.1",
    "botbuilder-dialogs": "4.11.0",
    ```
3. In this situation, when run `npm install` to install dependencies for `test-example` project, there will be two different version of `botbuilder-dialogs`
    ```powershell
    PS C:\mypath\test-example> npm list botbuilder-dialogs
    test-example@1.0.0 C:\mypath\test-example
    +-- my-package-A@0.0.1
    | `-- botbuilder-dialogs@4.11.1
    `-- botbuilder-dialogs@4.11.0
    ```
4. When we build the `test-example` project it will fail
 ```
    src/dialogs/mainDialog.ts:23:24 - error TS2345: Argument of type 'MySsoPrompt' is not assignable to parameter of type 'Dialog<{}>'.
  Types have separate declarations of a private property '_id'.

 23         this.addDialog(new MySsoPrompt(MY_SSO_PROMPT,
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 24             {
    ~~~~~~~~~~~~~
...
 27             }
    ~~~~~~~~~~~~~
 28         ));
    ~~~~~~~~~


Found 1 error.
```
source code:
```javascript
// test-example/src/dialogs/mainDialog.ts
        this.addDialog(new MySsoPrompt(MY_SSO_PROMPT,
            {
                tokenStore: this.TokenStore,
                scopes: this.requiredScopes
            }
        ));
```
It seems with `my-package-A` points `Dialog` definition to `4.11.1` while `this.addDialog()` points `Dialog` definition to `4.11.0` and the error occurs.

We have confirmed that this error only occurs when there are different versions of `botbuilder-dialog` packages exists. Our question is that `4.11.1` and `4.11.0` has the same major version number which inticates it should not include breaking changes. Then why does this error occurs? Can we resolve it? Thanks!

**Comment by joshgummersall** [comment]
Currently, we test and verify our packages with locked versions. Unfortunately, this is by design and is not something we will be fixing at the moment. You could try to use `peerDependencies` to provide a more permissive version resolution mechanism such that `test-package` can choose the underlying version.
