### ISSUE TITLE
Skills don't work in the DirectLine Speech channel

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-js#3365]
## Versions
What package version of the SDK are you using. 4.11
What nodejs version are you using 10.16.4
What browser version are you using n/a
What os are you using Windows

## Describe the bug
The skill throws a 500 error when talking to the DL speech client through the Windows Voice Assistant Client. 

## To Reproduce
1. Deploy this JS [host](https://github.com/microsoft/BotFramework-FunctionalTests/tree/josh/jsTestBranch/Bots/JavaScript/Consumers/CodeFirst/WaterfallHostBot) bot and this JS [skill](https://github.com/microsoft/BotFramework-FunctionalTests/tree/josh/jsTestBranch/Bots/JavaScript/Skills/CodeFirst/WaterfallSkillBot) bot
2. Follow the instructions [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0) to start the `Windows Voice Assistance Client` 
3. Send the bot the message `normal` then `2` then `2` then `1`

## Expected behavior
The skill should respond with a list of cards that the skill supports.

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/110188283-feb66280-7dcf-11eb-9568-d3d95d7da89f.png)

## Additional context
The skill and host work as expected in the webchat and DirectLine clients. It's only DirectLine Speech that has this issue.

**Comment by EricDahlvang** [comment]
I'm not sure if this is the problem, but the parent bot looks to be missing an await, on the streamingAdapter.useWebSocket line:

https://github.com/microsoft/BotFramework-FunctionalTests/blob/josh/jsTestBranch/Bots/JavaScript/Consumers/CodeFirst/WaterfallHostBot/index.js#L170


This project works with speech and skills, and might provide some guidance:
https://github.com/EricDahlvang/CertificateAppCredentials-CustomHeader-Sockets-Skills

**Comment by Virtual-Josh** [comment]
Thanks for the link. I'll take a look and update this ticket based on the result.

**Comment by Virtual-Josh** [comment]
I updated my host and skill with the `async` calls and it still blows up. I have other tests to finish so I'm going to leave this be for the moment. I'll circle back if I have time at the end to do a deeper dive into the diff between the two projects to see if I can figure out what's going on.

**Comment by Zerryth** [comment]
fwiw, I think from the past we established that skills + streaming only work if you're using DeliveryMode.ExpectReplies

* [Verify if Streaming bots can call skills](https://github.com/microsoft/botbuilder-js/issues/2918)
* [DeliveryMode.Expect Replies doesn't send first batch of buffered activities](https://github.com/microsoft/botbuilder-js/issues/3008)

**Comment by joshgummersall** [comment]
Yep - needs expect replies. Tested recently using this pattern and it works.
