### ISSUE TITLE
[Testing Skills Everywhere] Create conversation isn't implemented in the channel service handler.

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-js#3366]
This is a tracking issue. 

CreateConversation isn't implemented in the channel service handler so I'm unable to test if this works or not. 

[link](https://github.com/microsoft/botbuilder-dotnet/issues/5153) to same issue in dotnet.

**Comment by joshgummersall** [comment]
Following the .NET issue.
