### ISSUE TITLE
Add support for new Command and CommandResult Activities (JS)

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-js#3372]
To be completed once C# is done (see https://github.com/microsoft/botbuilder-dotnet/pull/5374 and https://github.com/microsoft/botbuilder-java/issues/1079 for details on the classes involved)
See [parent](https://github.com/microsoft/botframework-sdk/issues/6212)

**Comment by joshgummersall** [comment]
Resolved via https://github.com/microsoft/botbuilder-js/pull/3517
