### ISSUE TITLE
DialogManager refactor (JS)

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-js#3373]
To be completed when dotnet is done.
see [parent](https://github.com/microsoft/botframework-sdk/issues/6227)

**Comment by joshgummersall** [comment]
See https://github.com/microsoft/botbuilder-js/issues/3389

**Comment by joshgummersall** [comment]
See also https://github.com/microsoft/botbuilder-js/issues/3389

**Comment by mdrichardson** [comment]
Per @stevengum, this is closed by [this PR](https://github.com/microsoft/botbuilder-js/pull/3401)
