### ISSUE TITLE
TurnContextStateCollection.get() should return unknown or T

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#3400]
Currently `TurnContextStateCollection` extends `Map<any, any>`, so `TurnContextStateCollection.get()` returns `any` which is a poor TypeScript practice.

By providing a wrapper around `Map.prototype.get()`, TypeScript developers will be forced to type the return value of `TurnContextStateCollection.get()`, possible through one of the following methods:

```ts
class TurnContextStateCollection extends Map<any, unknown> {
    get<T = unknown>(key: any): T; 
    get(key: any): unknown {
        return super.get(key);
    }
}

type ObjectWithOwner = {
    owner: string;
}

const collection = new TurnContextStateCollection();
const myObj = { owner: 'me' };
collection.set('testKey', myObj);

// With type argument
const typedObj = collection.get<ObjectWithOwner>('testKey');
typedObj.owner;

// Without type argument
const someObj: ObjectWithOwner = collection.get('testKey');
someObj.owner;

// Without any typing
const unknownObj = collection.get('testKey');
unknownObj.owner; // Object is of type 'unknown'. (2571)

```

This proposal is a **breaking change** as TypeScript consumers of the SDK will need to update their code if they're not already typing the return value.

**Comment by joshgummersall** [comment]
Definitely on board with this, but I wonder if we can take it a step further and provide a way to pass a `runtype` so that the type will be checked at runtime.

We also could do progressive typing where we leave the default as `any` but still support manually passing a type parameter (and ideally a `runtype` for checking).

**Comment by stevengum** [comment]
Using runtypes is a good idea! This moves validation to the SDK's realm, which could clean up customer code. And other than "It's not what we normally do," I've yet to think of any major reasons as to why it would be bad if we did that.

For the proposed changes I'd prefer to _not_ use `get<T = any>(): T` or any signature that defaults to a return type of `any`, but having an opt-in path is usually better than just breaking changes 😆. (defaulting to `unknown` over keeping current behavior)

```ts
class TypedMap extends Map<K, any> {
  get<T>(key: K): T {
    return super.get(key);
  }

  getTyped<T>(key: K, runtype: rt.Runtype<T>): T {
    const value = this.get(key);
    return runtype.check(value);
  }
}
```
