### ISSUE TITLE
Address linter issues  

### ISSUE THREAD

**Issue by benbrown** [Microsoft/botbuilder-js#349]
tslint is now highlighting a bunch of code hygiene issues.

we need to address as many as possible, and adjust the rules to reflect our real goals for code style.

**Comment by stevengum** [comment]
Not sure if this is the right place for it; but @benbrown and @johnataylor should we disable the TSLint if the mocha tests get a `'1'` status code?  I suppose the first question is actually "can we stop the travis build if a unit test fails?"

**Comment by stevengum** [comment]
Disregard previous comment; we should run both regardless so that diligent devs clean up their code before it gets merged, even if the build breaks on a unit test... We should in the future evaluate whether or not tslint should throw errors or just warnings.

**Comment by benbrown** [comment]
Work in progress in the `benbrown/linter` branch fyi

**Comment by benbrown** [comment]
I've gone through all the files in `botbuilder` and `botbuilder-ai` now and updated them to the best of my ability. There are a few warnings still coming out of each project, which I'm still working on.

**Comment by benbrown** [comment]
`botbuilder-dialogs` is now updated, and I've also merged in the recent changes from master.

**Comment by benbrown** [comment]
The vast majority of linter errors have been corrected, and the linter rules have been updated. This has been merged!
