### ISSUE TITLE
[QnAMakerDialog] Using Azure App Gateway for QnAMaker host causes malformed host when creating QnA client

### ISSUE THREAD

**Issue by ng-username** [microsoft/botbuilder-js#3508]
## Versions
What package version of the SDK are you using: **4.11.0**
What nodejs version are you using: **v11.10.1**
What browser version are you using: **n/a, encountering issue using the Bot Framework Emulator**
What os are you using: macOS Catalina

## Describe the bug
By initializing an instance of the `qnaMakerDialog.ts` class using an Azure Application Gateway endpoint as the QnAMaker host, a malformed host is created in the class instance which results in an invalid url being queried when attempting to generate a QnA answer. As an example, when trying to create a `qnaMakerDialog` using the following as taken from the Virtual Assistant template:

```javascript
return new QnAMakerDialog(
                    qnaEndpoint.knowledgeBaseId,
                    qnaEndpoint.endpointKey, // <--- qnaEndpoint.endpointKey = https://my-app-name.my-company.com/qnamaker
                    qnaEndpoint.host,
                    this.templateManager.generateActivityForLocale("UnsupportedMessage") as Activity,
                    undefined,
                    this.templateManager.generateActivityForLocale("QnaMakerAdaptiveLearningCardTitle").text,
                    this.templateManager.generateActivityForLocale("QnaMakerNoMatchText").text,
                    undefined,
                    undefined,
                    undefined,
                    knowledgebaseId
                );
```

The initializing of this class results in the class' `getHost()` method being called with the following result:

```javascript
private getHost(dc: DialogContext): string {
        // The host value from the above code snippet is taken in here, starting out as https://my-app-name.my-company.com/qnamaker
        let host: string = this.hostname.getValue(dc.state);
        // hostName does not include 'qnamaker/v5', so the v5 API hostName will not be returned
        if (host.includes('qnamaker/v5')) {
            return host;
        }

        // V4 API logic
        // the hostName does not contain all the necessary information according to this check, so it is not returned
        if (/^https:\/\/.*\.azurewebsites\.net\/qnamaker\/?/i.test(host)) {
            return host;
        }

        // Thus, the logic decides to add the following parts to the hostname
        if (!/https?:\/\//i.test(host)) {
            host = 'https://' + host;
        }

        if (host.endsWith('.azurewebsites.net')) {
            // Add the remaining required path
            return host + '/qnamaker';
        }

        if (!host.endsWith('.azurewebsites.net/qnamaker')) {
            host = host + '.azurewebsites.net/qnamaker';
        }

        // Therefore, the resulting hostName is https://my-app-name.my-company.com/qnamaker.azurewebsites.net/qnamaker
        return host;
    }
```

This results in the following malformed url that is queried to generate a QnA answer, which leads to a failed query:
`https://my-app-name.my-company.com/qnamaker.azurewebsites.net/qnamaker/knowledgebases/*kbId*/generateanswer`

## Expected behavior
We should expect to be able to provide an Azure Application Gateway endpoint to query a QnAMaker instance for answers, as I am currently able to do so when implementing the `QnAMakerTelemetryClient` class and its `.getAnswers()` method.

**Comment by msomanathan** [comment]
@joshgummersall Could you please help check if this is an issue with URL building in JS bot?

**Comment by joshgummersall** [comment]
@ng-username, have you tried using `https://my-app.my-company.com/qnamaker/v5` as the host? That should force the code to use the host without any transformations.

**Comment by ng-username** [comment]
> @ng-username, have you tried using `https://my-app.my-company.com/qnamaker/v5` as the host? That should force the code to use the host without any transformations.

Appending `/v5` to the our provided QnAMaker endpoint results in a 404 at `https://my-app.my-company.com/qnamaker/v5/knowledgebases/*kbId*/generateanswer` when trying to query a KB for an answer

**Comment by joshgummersall** [comment]
Ah - that's fair enough. I'm assigning this over to my colleague @mdrichardson for further handling.

**Comment by mdrichardson** [comment]
v5 API is currently in preview and not really functional, in my quick testing. So, I've created a PR to address this.
