### ISSUE TITLE
Adaptive Expressions 'divide' with float is not returning a float

### ISSUE THREAD

**Issue by stefangomez** [microsoft/botbuilder-js#3527]
## Versions
What package version of the SDK are you using. **4.12.0**
What nodejs version are you using **14.7.0**

## Describe the bug
Adaptive Expressions, divide is not working as expected nor as documented. In the documentation, if one of the arguments is a float, a float is expected to be returned. See docs here: https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#div

and screenshot of it: ![divide docs screenshot](https://drops.nafets.io/up269K/Screen-Shot-2021-04-05-21-07-53.99.png)

## To Reproduce
1. try expression: `div(11.2, 2)`

## Expected behavior
returns `5` instead of `5.6`
also, the docs have a funny example. `div(11.2, 3)` does not equal `5.5` :)

## Additional context
also doesn't work for `11.2 / 2`

**Comment by joshgummersall** [comment]
@stefangomez, thanks for submitting the issue and a patch to fix it!
