### ISSUE TITLE
`yarn:lint` not catching some test "warnings" which should actually be "errors"

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botbuilder-js#3548]
Example: [this shouldn't be an arrow function](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/tests/botFrameworkAdapter.test.js#L303)

Needs investigating.

**Comment by joshgummersall** [comment]
Many libraries still use the [only-warn](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/.eslintrc.json#L3) plugin, unfortunately. Closing in favor of https://github.com/microsoft/botbuilder-js/issues/2745.

**Comment by mdrichardson** [comment]
Oh yeah, we talked about that.

**Comment by joshgummersall** [comment]
All good! It's confusing to say the least.
