### ISSUE TITLE
Getting 404 status: Dependecy error Azure Blob

### ISSUE THREAD

**Issue by SreekanthOAuth** [microsoft/botbuilder-js#3557]
#### What project is affected?

https://github.com/microsoft/botframework-solutions/tree/master/templates/typescript/samples/sample-assistant

And we are using below versions,

```
"botbuilder": "^4.11.0",
"botbuilder-ai": "^4.11.0",
"botbuilder-applicationinsights": "^4.11.0",
"botbuilder-azure": "^4.11.0",
"botbuilder-dialogs": "^4.11.0",
"botbuilder-lg": "^4.11.0",
"botbuilder-testing": "^4.7.0",
"botframework-config": "^4.11.0",
"botframework-connector": "^4.11.0",
```

#### What language is this in?

Typescript

#### What happens?

Seeing below the log in Application insights when we are trying to chat with the bot

![image](https://user-images.githubusercontent.com/24246902/113688356-dc717680-96e6-11eb-88c1-e9db0aa7c790.png)

#### What are the steps to reproduce this issue?

Create the Virtual assistant by following below reference

https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/typescript/3-create-project/

Then create the container in blob storage, eg:- virtual-assistant-state

Then create the userState and conversationState with BlobStorage

```
// Configure storage
const storage: BlobStorage = new BlobStorage({
    // tslint:disable-next-line: no-unsafe-any
    containerName: blobStorageContainerState,
    storageAccountOrConnectionString: appsettings.blobStorage.connectionString
});
const userState: UserState = new UserState(storage);
const conversationState: ConversationState = new ConversationState(storage);
```

In defaultAdapter.ts file, we are using the middle like below,

```
this.use(new TranscriptLoggerMiddleware(transcriptStore));
this.use(new SetLocaleMiddleware(settings.defaultLocale || 'en-us'));
this.use(new ShowTypingMiddleware());
this.use(new FeedbackMiddleware(conversationState, telemetryClient, new FeedbackOptions()));
this.use(new EventDebuggerMiddleware());
this.use(new SetSpeakMiddleware());
this.use(new AutoSaveStateMiddleware(this.conversationState, this.userState)); // here we are using both conversationState and userState
this.use(new TelemetryLoggerMiddleware(telemetryClient, true));
```
#### What were you expecting to happen?

This dependency 404 error should not come.

Please let us know if you need any details on this.

Thanks,
Sreekanth (Ecolab)

**Comment by joshgummersall** [comment]
@Batta32 is correct - we use certain APIs to detect whether a resource exists before trying to the resource. This is a standard use of the Azure Blob Storage APIs and HTTP/REST semantics. Hopefully, there is a way to filter out these sorts of 404 errors from your Application Insights logs.
