### ISSUE TITLE
Receives UnhandledPromiseRejectionWarning message during bot SSO

### ISSUE THREAD

**Issue by blackchoey** [microsoft/botbuilder-js#3601]
## Versions
What package version of the SDK are you using. 4.11.1
What nodejs version are you using  10
What browser version are you using  Microsoft Edge 90.0.818.38
What os are you using  Windows

## Describe the bug
We're building a Teams bot app with SSO enabled. According to bot SSO flow https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-sso?view=azure-bot-service-4.0 , the bot application should return 412 if token exchange failed. But we observed following UnhandledPromiseRejectionWarning message in console when returning 412: 
![image](https://user-images.githubusercontent.com/16605901/115651844-97904580-a35e-11eb-83aa-2e6e914b441a.png)

The SSO functionality is working well, the bug is about unexpected output in console.

## Expected behavior
There's no UnhandledPromiseRejectionWarning message in console during bot SSO flow.

## Additional context
This seems related to following source code: https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/botFrameworkAdapter.ts#L1244

**Comment by joshgummersall** [comment]
The reason why this is logged as an unhandled rejection is your call to `adapter.processActivity` does not have an `await` with a `try`/`catch` or a call to `.catch(...)`. The `412` response, as you mentioned, is normal during the OAuth flow. If you want to ignore it you can add logic to the code that catches the error.
