### ISSUE TITLE
Add Alexa and remove Cortana from Channels enum

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#3603]
Port https://github.com/microsoft/botbuilder-dotnet/pull/5457

- [x] Adding `Alexa` to `Channels` enum (#3698)
- [x] Verify with Service team which channels can be removed/deprecated
- [ ] Remove `Cortana` from `Channels` enum (WIP in #3730)

**Comment by joshgummersall** [comment]
This could incorporate @carlosscastro's feedback to reconcile the internal channel list with what is available to customers.

**Comment by stevengum** [comment]
This has been added to the `cloud-adapter` staging branch which will be merged into `main` for the R14 milestone.

**Comment by stevengum** [comment]
Checked in with the service team, Cortana can be removed as a channel.

**Comment by stevengum** [comment]
Closing as #3730 landed in a staging branch for `main`.
