### ISSUE TITLE
 [onTurnError] unhandled error: DialogContextError: result is not defined

### ISSUE THREAD

**Issue by shubham8886** [microsoft/botbuilder-js#3614]
Hi team,

I am getting  "[onTurnError] unhandled error: DialogContextError: result is not defined" error when i am below piece of code

            this.addDialog(new TextPrompt('TextPrompt'))            
                .addDialog(new WaterfallDialog(MAIN_WATERFALL_DIALOG_, [             
                    this.abc.bind(this),
                    this.actStep.bind(this)          
            ]));

where as when i am using below code application is working file.

            this.addDialog(new TextPrompt('TextPrompt'))            
                .addDialog(new WaterfallDialog(MAIN_WATERFALL_DIALOG_, [             
                    this.actStep.bind(this)          
            ]));

Please find attachment for my .js file
[main01Dialog.zip](https://github.com/microsoft/botbuilder-js/files/6376858/main01Dialog.zip)

**Comment by joshgummersall** [comment]
You've got an error in your `abc` function. The function body is:

```js
async abc(stepContext) {
  return await stepContext.context.sendActivity(`You said: ${result}`);
}
```

However, `result` is never defined. So this is expected behavior.
