### ISSUE TITLE
subArray([0], 1, 0) should not return an error

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-js#3616]
## Describe the bug
subArray([0], 1, 0) returns [] in C# and an error in Javascript.  See screen shots in LG playground.  The reason this arises is when you have an array you are using to control a recursive function where you remove an element each time this is the expression you use.

## Expected behavior
Both languages should return [].

## Screenshots
Failure in JS.
![image](https://user-images.githubusercontent.com/17637681/116128282-9ec89380-a67d-11eb-9a25-9689fac969c4.png)

Working in C#.
![image](https://user-images.githubusercontent.com/17637681/116128368-b43dbd80-a67d-11eb-8933-8358d2b12fe3.png)

**Comment by chrimc62** [comment]
Sigh.  The second parameter is an end index, not an offset and the example which actually fails in JS and works in C# is subArray([9], 1, 1) which happens when popping elements off an array.
![image](https://user-images.githubusercontent.com/17637681/116285787-54114f00-a743-11eb-8d78-8432322b30a8.png)
![image](https://user-images.githubusercontent.com/17637681/116285894-7905c200-a743-11eb-97a8-f238d8c9c8df.png)

**Comment by Danieladu** [comment]
hi chris, so, I try to understand your requirements.
Firstly, what do you think is the expected action of the start index out of the range, for example, 
`[1]`, only contains one item, so, if the start index is 1, it indeed out of range, it should be `0` only.
Or do you mean we should tolerate the start index while equals to the length of the array.
For example, 
```
subArray([1], 1, 1)   -> []
subArray([1], 0, 0)   -> []
subArray([1], -1, 0)  -> error, start index out of range
subArray([1], 0, 1) -> [1]
subArray([1], 1, 2) -> error, end index out of range
```

That's what you mean ? (Treat the index valid while is equals to the length of array/string)

**Comment by Danieladu** [comment]
@chrimc62  See the draft pr above. Is that the right fix?
