### ISSUE TITLE
Add `test:compat` to CI

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botbuilder-js#3632]
Related: https://github.com/microsoft/botbuilder-js/pull/3628#discussion_r621500935

Looks like it hasn't been updated in awhile, so it needs to be updated and also added to CI so that it stays up-to-date.

**Comment by joshgummersall** [comment]
I think `test:compat` is a command across many packages. Perhaps it can be extracted to the root `package.json` file and run across all packages? The CI job ought to operate just like the `test:schemas` command in that it should run the command and fail if there's a diff detected.

**Comment by mdrichardson** [comment]
@joshgummersall Will do!
