### ISSUE TITLE
Welcome message on Slack

### ISSUE THREAD

**Issue by FKSI** [Microsoft/botbuilder-js#365]
I'm trying to send a welcome message when the user join the conversation. It's working fine with webchat with the following code:

`if (context.activity.type === 'conversationUpdate' && context.activity.membersAdded[0].name !== 'Bot')`

**Comment by nrishoj** [comment]
@FKSI, closed due to false alarm, or?

**Comment by FKSI** [comment]
Yes false alarm :).
