### ISSUE TITLE
Adaptive expression bundle parsed size is around 1.3MB which takes long time to download the bundle

### ISSUE THREAD

**Issue by atishayv** [microsoft/botbuilder-js#3654]
## Versions
4.11.0

## Describe the bug
Currently the bundle size of adaptive-expression library is around 1.3 mb
![image](https://user-images.githubusercontent.com/13940020/117258584-bf0d0500-ae6a-11eb-99ef-ab36438a1222.png)

of which the major file sizes are for antlr4ts library which is around 400kb and the built in functions which is around 200kb.

This takes a lot of time in browser to download the bundle, parse the content and then actually parse the expression.
Is there a way this can be optimised ?
One way we were thinking of is lazy loading the code which is not required for processing of expression. Also lazy loading the built in functions only when its present in expression

Wanted to figure out whats the best way to optimise this ?

## Additional context
We use adaptive card with templating and adaptive expression to render the card in client side. The browser takes a lot of time in downloading the adaptive expression chunk and parsing it, which increases the rendering time of adaptive card.

**Comment by boydc2014** [comment]
Offline synced with @atishayv and we identified that this is not an issue with adpative-expression, there is some issue in customer's environment setup causing the loading time seems to be high(300-500ms). 

Per out tests, the average loading time for adaptive-expression is about 10-50ms depends on the cpu performance. So it should be good enough. Close this for now.
