### ISSUE TITLE
Adaptive Runtime - OnTurnError exception handler text is not consistent with C#

### ISSUE THREAD

**Issue by darrenj** [microsoft/botbuilder-js#3655]
When testing a C# adaptive runtime based Bot and a JS adaptive runtime based Bot the error handling experience is not symmetrical. Not saying the C# approach is the best approach but we should agree the base experience of runtime error handling  including design input on "copy" and update both to be the same.

JS
![image](https://user-images.githubusercontent.com/33519520/117314739-f5547f80-ae7e-11eb-8377-2da2be877e69.png)

C#
https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/CoreBotAdapter.cs#L28

**Comment by joshgummersall** [comment]
This behavior was changed [late in R13 in .NET](https://github.com/microsoft/botbuilder-dotnet/pull/5353/files#diff-63b3a31f8a08f6c8f60e7be89510fdedb6802390d2b1f99566377150bee3a3dfL61). I actually think the experience is better in JS (which is how the `onTurnError` handler has behaved forever, even in [the .NET samples](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/13.core-bot/AdapterWithErrorHandler.cs)). I think this issue belongs in the .NET repo.
