### ISSUE TITLE
Add tag to botbuilder-ai-orchestrator so shows up in Composer

### ISSUE THREAD

**Issue by daveta** [microsoft/botbuilder-js#3656]
## Versions
What package version of the SDK are you using: `4.13.1`

What nodejs version are you using: `10, 12, 14`
What os are you using: `Windows`

## Describe the bug
Please add appropriate tags to the Orchestrator recognizer package to enable it to show up in Composer.
https://www.npmjs.com/package/botbuilder-ai-orchestrator

There is a workaround to add a custom feed.

## To Reproduce
1. Go to 'Package Manager'
2. Select 'npm'
3. Scroll down - no orchestrator package.

## Expected behavior
Orchestrator package should show up in npm feed.

![image](https://user-images.githubusercontent.com/6182197/117339000-15227e00-ae54-11eb-9845-033ed7dd089d.png)

 > NOTE: **Workaround:**
Add a new feed without the filter..
 
![image](https://user-images.githubusercontent.com/6182197/117340529-d8f01d00-ae55-11eb-8f02-574e92f07a3e.png)

**Comment by joshgummersall** [comment]
We'll likely take this in a patch release

**Comment by sgellock** [comment]
Shiproom - meta data changes.  low risk for a core scenario
