### ISSUE TITLE
Investigate: TS tests probably don't need to build first

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botbuilder-js#3658]
Example: [botbuilder-dialogs-adaptive-testing](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-dialogs-adaptive-testing/package.json)

I think we can just use `mocha --require ts-node/register`

Find other libraries using TS tests and see if they need to be pre-built.

**Comment by joshgummersall** [comment]
Generally we require files from the `lib` directory which is why we have a separate build step. If we can require from `src` using `ts-node` that would be great. The ideal end game is all our tests written in Typescript as well.

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. Closing as Not Needed.
