### ISSUE TITLE
Underscore dependency has high security vulnerability in botbuilder-azure

### ISSUE THREAD

**Issue by tomSauret847** [microsoft/botbuilder-js#3669]
## Versions
What package version of the SDK are you using. 4.13.2
What nodejs version are you using 10.24.1
What os are you using Windows

## Describe the bug
  High            Arbitrary Code Execution                                      
                                                                                
  Package         underscore                                                    
                                                                                
  Patched in      >=1.12.1                                                      
                                                                                
  Dependency of   botbuilder-azure                                              
                                                                                
  Path            botbuilder-azure > documentdb > underscore                    
                                                                                
  More info       https://npmjs.com/advisories/1674     

## To Reproduce
1. run NPM Audit

## Expected behavior
No high security vulnerabilities

**Comment by joshgummersall** [comment]
@tomSauret847, thanks for filing this issue. I'm going to pin this with some details as this has come up over the day or two.

As you noted, the vulnerable code is included indirectly via the `azure-storage` and `documentdb` packages. Unfortunately, both are no longer being updated. Until we can deprecate and remove the SDK classes that rely on these packages, the warning will continue to appear.

For now, our suggestion is to make sure you don't use any of the (now deprecated) classes that indirectly import vulnerable code. Luckily, all of the affected classes have replacements (listed in the table below).

| Class                                                                      | Why?                                  | Use Instead
|-----------------------------------------------|--------------------------|------------------------------------
| `botbuilder-azure.CosmosDbStorage`              | imports `documentdb`    | `botbuilder-azure.CosmosDbPartitionedStorage`
| `botbuilder-azure.BlobStorage`                         | imports `azure-storage` | `botbuilder-azure-blobs.BlobsStorage `
| `botbuilder-azure.AzureBlobTranscriptStore ` | imports `azure-storage`  | `botbuilder-azure-blobs.BlobsTranscriptStore `

**Comment by tomSauret847** [comment]
Thank you @joshgummersall for the quick reply. I did move one of my bots over to the classes you listed above but I am receiving an error with the TranscriptLoggerMiddleWare when using the botbuilder-azure-blogs.BlobTranscriptStore. Has there been any other issues with the middleware reported? The error I am receiving is 
TranscriptLoggerMiddleware logActivity failed: "`activity.localTimezone` must be defined"
Error: `activity.localTimezone` must be defined
    at Object.assertCondition (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-stdlib\lib\assertExt.js:15:15)
    at condition (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-stdlib\lib\types.js:26:17)
    at C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-stdlib\lib\types.js:40:13
    at Object.string (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-stdlib\lib\types.js:347:5)
    at Object.exports.assertActivity (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botframework-schema\lib\index.js:134:32)
    at BlobsTranscriptStore.<anonymous> (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-azure-blobs\lib\blobsTranscriptStore.js:204:31)
    at Generator.next (<anonymous>)
    at C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-azure-blobs\lib\blobsTranscriptStore.js:10:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-azure-blobs\lib\blobsTranscriptStore.js:6:12)

Please let me know if you need anymore information

**Comment by joshgummersall** [comment]
We haven't seen anything reported yet. Would you mind opening a separate issue with those details so we can investigate?

**Comment by joshgummersall** [comment]
Issue with transcript logger resolved via: https://github.com/microsoft/botbuilder-js/issues/3684
