### ISSUE TITLE
Runtime skills configuration nesting mistake

### ISSUE THREAD

**Issue by joshgummersall** [microsoft/botbuilder-js#3674]
The skills credential provider was attempting to extract `MicrosoftAppId` and `MicrosoftAppPassword` from the `runtimeSettings` -> `skills` scope in `appsettings.json`, whereas it should be using the root configuration scope.

**Comment by sgellock** [comment]
Shiproom - parent issue tracked with https://github.com/microsoft/BotFramework-Composer/issues/7766
