### ISSUE TITLE
Test project parity with botbuilder-dotnet

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#3676]
**Describe the solution you'd like**
It should be easy for JS SDK contributors to test Adaptive Runtime and Skills-related changes without having to:
1. use `npm pack`
2. use symlinks
3. create a test project and manually git ignore it or create another branch separate from their workstream for testing.

Additionally, we likely don't need _every_ test project in [microsoft/botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet/). The test projects should be deliberately chosen and then learnings should be applied back to `botbuilder-dotnet` to clean up that repo/solution.

**Comment by mrivera-ms** [comment]
This has been reviewed by the SDK team. Closing as not needed.
