### ISSUE TITLE
Create holistic test solution for Adaptive Runtime code/scenarios

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#3677]
Stemming from [comment](https://github.com/microsoft/botbuilder-js/pull/3675#pullrequestreview-658145428) (https://github.com/microsoft/botbuilder-js/pull/3675).

The SDK needs to have tests for the Adaptive Runtime bots' configuration via `appsettings.json`. The main concerns around unit tests for this stem from the need for a full `appsettings.json` file, this file's source of truth and avoiding drift.

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. Closing as Not Needed.
