### ISSUE TITLE
chore: Required for runtime GA: add api-extractor

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botbuilder-js#3701]
-runtime libraries' public methods are currently too frequently update to make `api-extractor` worthwhile, so add it in right before GA.

Steps:

1. Copy `api-extractor.json` from another library,
2. Add `"test:compat": "api-extractor run --verbose"` to `package.json` scripts
3. Run `yarn test:compat`
4. Fix any errors
5. Copy `./temp/*.md` file to `./etc/*.md`
6. Run `yarn test:compat`
7. Commit changes

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. Closing as Not Needed.
