### ISSUE TITLE
[botbuilder-azure] NodeJS application stalls if you read an empty array of keys

### ISSUE THREAD

**Issue by alexrecuenco** [microsoft/botbuilder-js#3706]
https://github.com/microsoft/botbuilder-js/blob/cb74e856dab0f81e0943694c8c9b1d8bfafbc781/libraries/botbuilder-azure/src/blobStorage.ts#L183

`await blobStorage.read([])` will never resolve.

Is there a strong reason why botbuilder is not using the async/await notation? There are a few bugs like this around.

**Comment by joshgummersall** [comment]
Please update to `botbuilder-azure-blobs.BlobsStorage`, the `BlobStorage` class is deprecated and uses libraries that are deprecated.
