### ISSUE TITLE
[botbuilder-azure] Asynchronous function can either throw or resolve to a rejected promise

### ISSUE THREAD

**Issue by alexrecuenco** [microsoft/botbuilder-js#3707]
https://github.com/microsoft/botbuilder-js/blob/cb74e856dab0f81e0943694c8c9b1d8bfafbc781/libraries/botbuilder-azure/src/blobStorage.ts#L274

I believe this should instead be `Promise.reject(new Error(...))`. Otherwise, this asynchronous function has two failure modes. (Code using async/await will catch it, but code as used in this codebase might have a harder time reasoning about it)

**Comment by joshgummersall** [comment]
Please update to `botbuilder-azure-blobs.BlobsStorage`, the `BlobStorage` class is deprecated and uses libraries that are deprecated.
