### ISSUE TITLE
JS Adaptive/Runtime GA

### ISSUE THREAD

**Issue by joshgummersall** [microsoft/botbuilder-js#3726]
The plan to go GA with the JS Adaptive packages involves the following work items:

- [ ] Update package READMEs to conform to standard template
- [ ] Ensure JSDoc comments are sufficient and include xrefs
- [ ] Enable API Extractor for all new packages
- [ ] Additional test coverage for adaptive runtime packages
- [ ] Update JS Functional Tests to use the new adaptive runtime packages
- [ ] Create a sample component package
- [ ] Work with docs team to ensure new packages are included and docs site snippets are updated
- [ ] Improve type validation (zod) errors (https://github.com/microsoft/botbuilder-js/issues/3727)
- [ ] Identify (and implement) classes that need custom toJSON() functionality
- [x] Add downlevel-dts to new adaptive runtime packages (https://github.com/microsoft/botbuilder-js/pull/3737)
- [x] Add new adaptive runtime packages to Typescript consumer tests (https://github.com/microsoft/botbuilder-js/issues/3736)
- [ ] Take a pass at fixing (or ignoring irrelevant) eslint security warnings
- [ ] Take a pass at dependencies to ensure they are up-to-date and free from CVEs
- [ ] Double check public @types/* dependencies
- [ ] Coordinate with Components team to ensure New Bot Templates use non-preview packages and tilde for semver
- [ ] Coordinate with Composer team to remove "Preview" designation
- [ ] (Possibly) update samples to use new apative runtime packages
- [ ] (Possibly) update Bot Framework Solutions to use new apative runtime packages
- [ ] (Possibly) update `generator-botbuilder` to use new adaptive runtime packages
- [ ] (Possibly) update `generator-botbuilder` to create a component package

Additional nice-to-haves include:

- [ ] Interface expressing `$kind` constraint, along with clean up of JS Adaptive converters
- [ ] Add test project to the SDK repo for devs
- [ ] Final revision of public APIs, access modifiers (public/protected/private)
- [ ] Final revision of exported types/classes/etc.

**Comment by mrivera-ms** [comment]
This has been reviewed by the SDK team. Closing as not needed.
