### ISSUE TITLE
composeExtension with type "message" will not return text to compose message area with Messaging Extensions

### ISSUE THREAD

**Issue by mateowinn** [microsoft/botbuilder-js#3742]
## Versions
What package version of the SDK are you using: **4.11.1**
What nodejs version are you using: **12.14.0**
What browser version are you using: **n/a, MacOS Teams app**
What os are you using: **MacOS**

## Describe the bug
The MS docs (and even this library's in-line code comments) seem to indicate that it is possible to return plaintext to a user's compose message area with Messaging Extensions if you specify `text` and `type: 'message'` in the `composeExtension` return value of the `handleTeamsMessagingExtensionSelectItem` method in `TeamsActivityHandler`, like so:

```javascript
async handleTeamsMessagingExtensionSelectItem(context, obj) {
	return {
		composeExtension: {
			type: 'message',
			text: 'Here is the message you want to send to your friends!'
		}
	};
}
```

Unfortunately, while no error is thrown and the value is seemingly returned to the client app, nothing ever shows up. I can get the regular card attachment behavior, i.e.

```javascript
async handleTeamsMessagingExtensionSelectItem(context, obj) {
	return {
		composeExtension: {
			type: 'result',
			attachmentLayout: 'list',
			attachments: [CardFactory.thumbnailCard(obj.description)]
		}
	};
}
```

to work just fine, but never plaintext. Perhaps I am missing some key piece because there are no definitive examples for this usage?

## To Reproduce
1. Setup the [messaging extension search example](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/50.teams-messaging-extensions-search) project.
2. Replace the contents of `handleTeamsMessagingExtensionSelectItem` in `/bots/teamsMessagingExtensionsSearchBot.js` with
```javascript
return {
	composeExtension: {
		type: 'message',
		text: 'Here is the message you want to send to your friends!'
	}
};
```
3. Initiate a query (anything) to your bot in Teams.
4. Select one of the item options.
5. Wait for nothing to happen.

## Expected behavior
I would expect the text "Here is the message you want to send to your friends!" to populate my compose message area much the same way that Cards can populate there before hitting the Send button, but nothing happens at all.

**Comment by joshgummersall** [comment]
@mateowinn, I am looking into this. Thanks for reporting!

**Comment by clearab** [comment]
Unfortunately, you cannot currently respond to that invoke with plain text message. You can respond to the original query with plain text, which will insert it into the search results lists, but you can't insert plain text into the compose message area.

**Comment by mateowinn** [comment]
@clearab that's unfortunate. Do you know what the timeline is for allowing plaintext insertions into the compose message area?

**Comment by mrivera-ms** [comment]
@clearab, could you please follow up with the customer? Closing this issue.

**Comment by clearab** [comment]
Sorry, no there isn't a timeline to share. If you'd like to see it prioritized, please reach out to the Team group directly via one of the methods here https://docs.microsoft.com/en-us/microsoftteams/platform/feedback

**Comment by mateowinn** [comment]
Will do. Thanks!

**Comment by mateowinn** [comment]
@clearab one last question: is this feature impossible currently because _Teams_ doesn't support it or because _botbuilder-js_ doesn't support it?

**Comment by clearab** [comment]
Hi - The Bot Framework SDKs will essentially never block you from something like this, as you can always manipulate the JSON directly. The SDK is just helping create the JSON response, but you could always manually create the response if you preferred. The Teams documentation contains examples of JSON payloads you can use for this purpose if you desire.

**Comment by mateowinn** [comment]
@clearab thanks for the response. So are you saying that it actually *is* possible to return a custom payload that will load plaintext in the compose message box? I haven't run across these JSON examples before - would you mind linking them?

**Comment by clearab** [comment]
No, in this case Teams will just ignore the payload and do nothing.

You can find the JSON payloads on the JSON tab of any Teams bot documentation page that has code samples. An example is here: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=json
