### ISSUE TITLE
AnalyzeTemplate should not throw an exception on recursive templates

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-js#3791]
## Versions
Package: 4.13.6
Node: 12.19.1

## Describe the bug
When analyzing this template a recursive loop exception is raised.
```
# sortNumber(number, divisor)
> Return a string with leading zeros out to divisor
- ${if(divisor == 1,
    string(number),
    concat(string(div(number, divisor)), sortNumber(mod(number, divisor), div(divisor, 10))))}
```

## Expected behavior
sortNumber should list itself as one of the templates it uses and there should be no exception.

![image](https://user-images.githubusercontent.com/17637681/123024769-7368d900-d38e-11eb-9c5d-0de0c9a88bd8.png)

**Comment by joshgummersall** [comment]
@Danieladu, `git blame` shows you are someone that's pretty familiar with this code. Could you take a look?

**Comment by Danieladu** [comment]
> @Danieladu, `git blame` shows you are someone that's pretty familiar with this code. Could you take a look?

Sure

**Comment by Danieladu** [comment]
@chrimc62 You have created the same issue before: https://github.com/microsoft/botbuilder-js/issues/3619, and we fixed it in https://github.com/microsoft/botbuilder-js/pull/3621 two months ago. But the change would appears in 4.14 version.
Could you take a look and make sure it meets your requirements.

**Comment by joshgummersall** [comment]
I've added a test case via the linked PR, but I'll close this issue as it does not reproduce in `main`.
