### ISSUE TITLE
Teams: Wrong value returned for Input.Time in adaptive card

### ISSUE THREAD

**Issue by matthiasdilger** [microsoft/botbuilder-js#3861]
This is a Teams specific bug I believe, sorry for filing it here, could somebody please forward it? Thank you.

## Versions
SDK 4.13
nodejs 12.16

## Describe the bug 
When the Teams client is set to Chinese or Korean the Input.Time in an adapative card is localized, 2:30pm in Chinese is "2:30 下午". The value of the Input.Time upon submitting the card to the bot should be 14:30 but instead it is 02:30 (am!). It works fine for US style 2:30pm notation, where the value is 14:30.

## To Reproduce
Set your Teams client to Chinese or Korean.
The bot sends an adaptive card with an Input.Time and a submit button
Set a time in the afternoon, like 2:30 下午
Submit the card
The bot receives '02:30' in the submitAction

## Expected behavior
The bot should always receive 24 hr time, 14:30 in the example above.

**Comment by clearab** [comment]
Posted for the Teams group here: https://docs.microsoft.com/en-us/answers/questions/472574/wrong-value-returned-for-inputtime-in-adaptive-car.html
