### ISSUE TITLE
Feature request: Allow sending trace messages to client

### ISSUE THREAD

**Issue by alopix** [microsoft/botbuilder-js#3865]
Currently, both the old `BotFrameworkAdapter` and the new `CloudAdapter` prevent trace activities from being sent to the client. There are some use-cases where this might be useful though (e.g., certain test scenarios).
Would it be possible to add an option to the `CloudAdapterBase` class that would allow trace messages to be sent?
It could be a simple boolean or a function that determines per request if traces should be forwarded.

Happy to suggest a PR myself but wanted to know if it would even have a chance getting merged.

https://github.com/microsoft/botbuilder-js/blob/7afa288668abd45b680bc0cd8bc7a58f3e276f34/libraries/botbuilder-core/src/cloudAdapterBase.ts#L75

**Comment by stevengum** [comment]
Thanks for filing this and opening a PR @alopix! Could you expand on the certain test scenarios that you're facing?

As a workaround, you could could add a SendActivitiesHandler to your TurnContext instance to grab or create a ConnectorClient instance and forcibly send the trace activity. Have you explored this approach to get unblocked?

https://github.com/microsoft/botbuilder-js/blob/3dc3d7e7ceb949ab18d1f236fd6a2daf46c53e16/libraries/botbuilder-core/src/turnContext.ts#L53-L57

One caveat is that I'm not sure the channel (DLS in this case) will respect this ActivityType and send it to the end client.

**Comment by alopix** [comment]
The scenario is to run trace analysis just like in the botbuilder emulator but for using any other client—especially since the emulator only supports DirectLine and not DirectLine Speech and others.
