### ISSUE TITLE
Feature request: custom webSocketFactory for CloudAdapter

### ISSUE THREAD

**Issue by alopix** [microsoft/botbuilder-js#3866]
With the old `BotFrameworkAdapter` it was possible to set a custom `webSocketFactory` to e.g., use a custom `createWebSocket` or add some metric possibility etc.
This is not possible with the new `CloudAdapter` since the factory is hardcoded as `NodeWebSocketFactory`.

Happy to suggest a PR myself but wanted to know if it would even have a chance getting merged.

https://github.com/microsoft/botbuilder-js/blob/7afa288668abd45b680bc0cd8bc7a58f3e276f34/libraries/botbuilder/src/cloudAdapter.ts#L219

**Comment by mrivera-ms** [comment]
Assigning to @msomanathan for PR review.
