### ISSUE TITLE
Facin error like {"error":{"code":"ServiceError","message":"Unknown"}} while send message

### ISSUE THREAD

**Issue by mohandass-pat** [microsoft/botbuilder-js#3876]
## Describe the bug
I'm using the Microsoft botframework-connector library in Nodejs. Where I can successfully create a conversation. but with using that conversation id I cannot able to send a message.

SDK version: 4.14.1
[](url)
## To Reproduce
After creating a conversation send a message using (sendToConversation). it will return an unknown error.

## Expected behavior
To successfully send a message
![Screenshot from 2021-07-21 21-38-15](https://user-images.githubusercontent.com/43599092/126522258-79cd23c9-8795-409a-ac33-0385dda63b32.png)

Here I have attached the error screenshot.

**Comment by mohandass-pat** [comment]
Solved. I was not passing tenant Id and I was using the wrong ServiceURI. Fixed Now.

**Comment by joshgummersall** [comment]
Thanks for the update, glad you were able to resolve the issue!
