### ISSUE TITLE
BotFrameworkAdapter does not work correctly with express 4.x

### ISSUE THREAD

**Issue by ctstone** [Microsoft/botbuilder-js#388]
`BotFrameworkAdapter` defines a [`WebResponse`](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/botFrameworkAdapter.ts#L49-L52) interface with a `send(..)` definition that does not match the express 4.x [send definition](http://expressjs.com/en/4x/api.html#res.send) (the deprecated 3.x express does contain a [matching API](http://expressjs.com/en/3x/api.html#res.send)).

Because of this, messages sent by the client are not acknowledged (emulator shows `sending...` followed by an option to retry), and the emulator shows an error: `Unexpected token A in JSON at position 0 in "http:": Accepted... `. Most likely the server is sending `202 Accepted` in the body instead of the status, which of course is not valid JSON.

Other than the false indicator that the message failed, the bot behaves normally.

Would you consider changing the `WebResponse` interface (and related calls) to:

```TypeScript
export interface WebResponse {
    end(...args: any[]): void;
    send(body: any): any;
    status(status: number): any;
}
```

This is still compatible with the restify APIs for [status](http://restify.com/docs/response-api/#status) and [send](http://restify.com/docs/response-api/#send).

Reasons I like to use express instead of restify:

1. integrate bot with existing site built on express
2. restify seems to have some optional (native?) dependencies (using node-gyp) and shows a bunch of (harmless?) errors when it can't find Python. not a great experience for POCs and would probably break automated builds since npm returns a non-zero error code.

**Comment by sgellock** [comment]
let's investigate the impact given where we are at.

**Comment by stevengum** [comment]
@ctstone, closing this issue as #445 was merged in.
