### ISSUE TITLE
Attachments is undefined when using Direct Line App Service Extensions

### ISSUE THREAD

**Issue by compulim** [microsoft/botbuilder-js#3887]
## Versions

`4.14.1`.

Tested with Web Chat `4.14.0` (latest production as of now).

## Describe the bug

When connecting via DL ASE to a bot, uploading a file to the bot, should appear in the `activity.attachments` array. Instead, it is `undefined`.

## To Reproduce

1. Provision a new JS-based Echo Bot
2. Update the bot to support DL ASE
   - https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-node-bot?view=azure-bot-service-4.0
3. Make sure the bot is using `4.14.1` (or later) version of SDK
   - `npm install botbuilder@4.14.1`
4. Modify the `bot.js` as follow

```diff
-     const replyText = `Echo: ${context.activity.text || ''}`;
+     const replyText = `Echo: ${context.activity.text || ''}\n\n(With ${
+       (context.activity.attachments || []).length
+     } attachments, \`${typeof context.activity.attachments}\`)`;
```

5. Connect to the bot via DL ASE using Web Chat
   - Ping both `/.bot/` endpoint and `/api/messages` endpoint to make sure the bot is up and ready
   - HTML template at https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/i.protocol-direct-line-app-service-extension
   - Or, use the Web Chat Loader, see how in Additional Context
6. Upload a file to the bot

## Expected behavior

Bot should say, "Echo: (With 1 attachments, object)".

Instead, it said, "Echo: (With 0 attachments, undefined)".

### Direct Line App Service Extension

It says 0 attachments when connecting to the bot via DL ASE.

![image](https://user-images.githubusercontent.com/1622400/127212826-55624558-aeca-4cdf-9af2-ff96330f83d4.png)

### Direct Line (Web Socket)

It works when connecting to the bot via Web Socket and uploading a file to it.

![image](https://user-images.githubusercontent.com/1622400/127212749-d2aafd57-5370-4108-bf7d-48574baeb281.png)

### Direct Line App Service Extension to a C# bot

It works when connecting to a C# bot via DL ASE.

Steps:

1. Provision a new C# bot with Echo Bot template
2. Update the bot to support DL ASE
   - https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0
3. Update `EchoBot.csproj` to use latest version of Bot SDK 4.14.1, the bot template was using 4.11.0

```diff
-   <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.11.0" />
+   <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.14.1" />
```

4. Update `EchoBot.cs`
   - You can use Project Kudu (a.k.a. SCM) to modify the code. Run `deploy.cmd` after your change.

```diff
-           var replyText = $"Echo: {turnContext.Activity.Text}";
+           var replyText = $"Echo: {turnContext.Activity.Text}\n\n(With {turnContext.Activity.Attachments?.Count} attachments)";
```

5. Connect to the bot via DL ASE using Web Chat
   - Ping both `/.bot/` endpoint and `/api/messages` endpoint to make sure the bot is up and ready
   - HTML template at https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/i.protocol-direct-line-app-service-extension
   - Or, use the Web Chat Loader, see how in Additional Context
6. Upload a file to the bot

![image](https://user-images.githubusercontent.com/1622400/127213405-6d5eaef1-32f6-4e3c-8d42-d9834ba3eb2d.png)

### Test matrix

We tested the scenario through JS and C#, and via Web Socket or ASE.

As it only failed on JS via DL ASE, we believe this is an issue on Bot SDK.

| Protocol | JavaScript bot | C# bot |
| - | - | - |
| Direct Line Web Socket | ✔️ | ✔️ |
| Direct Line App Service Extension | ❌ | ✔️ |

### HTTP request to obtain a token for DL ASE

Paste the following into Fiddler Composer, replace `BOT_URL` and `BOT_SECRET`. The `BOT_SECRET` should be the Direct Line secret, not the DL ASE secret.

```http
POST http://BOT_URL.azurewebsites.net/.bot/v3/directline/tokens/generate HTTP/1.1
User-Agent: Fiddler
authorization: Bearer BOT_SECRET
Host: BOT_URL.azurewebsites.net

{"User":{"Id":"dl_1234"}}
```

### Test in Web Chat

To quickly test in Web Chat, you can use [Web Chat Loader](https://compulim.github.io/webchat-loader). Follow all the highlighted fields below. `BOT_TOKEN` should be the token you obtained from `/.bot/v3/directline/` endpoint (DL ASE specific token). You can use the HTTP request trace above to obtain a token.

![image](https://user-images.githubusercontent.com/1622400/127214292-ef65052a-b368-4996-84d8-f6ed811fd676.png)

**Comment by joshgummersall** [comment]
@compulim, is this a regression?

**Comment by compulim** [comment]
In short, I don't know.

@ckkashyap owns the client side of the network layer. He has some E2E tests for uploading an attachment. But unfortunately, he is testing against a C# bot (a.k.a. `dljstestbot`).

I can't find any E2E tests for JS route. Do you know any?
