### ISSUE TITLE
[Rendering] Content Security Policy violations in adaptive-expressions npm library

### ISSUE THREAD

**Issue by paulcam206** [microsoft/botbuilder-js#3889]
@BenBullock1992 commented on [Wed Jun 09 2021](https://github.com/microsoft/AdaptiveCards/issues/5978)

# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- NodeJS

# Target Application

Angular single-page web application

# Problem Description

When serving our Angular application through our Node.js/Express.js web server, we are seeing Content Security Policy violations coming from the adaptive-expressions npm library when we try to render an Adaptive Card.

The violation is being raised as this library calls functions like "eval()" and "new Function()" which are considered dangerous since they are susceptible to XSS attacks.

Please could you advise on possible workarounds which will not compromise our security?

# Version of SDK

"adaptive-expressions": "^4.12.0",
"adaptivecards": "^2.9.0",
"adaptivecards-templating": "^2.1.0"

**Comment by joshgummersall** [comment]
A quick `grep` through the codebase shows no obvious direct use of `eval` or `new Function()` - can you share a minimal `index.html` file illustrating the security violations?

**Comment by BenBullock1992** [comment]
I've done a little digging and can see that the violation is coming from browser.js inside the adaptive-expressions NPM package.

Path: node_modules/adaptive-expressions/lib/browser.js

I'm unable to share an index.html file with you but here is a screenshot of the error:

<img width="1045" alt="screenshot" src="https://user-images.githubusercontent.com/12212783/127978227-de11542b-c0fc-4eaa-9a85-0217f5b48f54.png">

**Comment by joshgummersall** [comment]
It looks like the `return Function` piece of code is due to browserify using [node-util](https://github.com/browserify/node-util) when bundling. I suspect the `core.js` use of `eval` is for a similar reason. How are you consuming the `adaptive-expressions` package? Are you bundling it yourself?

**Comment by BenBullock1992** [comment]
No, we're not bundling it ourselves as Angular manages this for us.

We render Adaptive Cards in our Angular application so have the following three NPM dependencies installed:

"adaptive-expressions": "^4.14.1"
"adaptivecards": "^2.9.0"
"adaptivecards-templating": "^2.1.0"

We use the adaptivecards-templating library for expanding our data into our template. This library has a peer dependency on adaptive-expressions. We're not specifically using anything from adaptive-expressions ourselves.

**Comment by joshgummersall** [comment]
At the moment, there isn't much we can do without a larger overhaul of our browser bundling tools and possibly the existing package dependencies.

Our use of `browserify` introduces a transitive dependency on `is-generator-function` which uses `return Function("...")` internally. While we could potentially remove the direct use of `require("util")` within `adaptive-expressions`, it's quite difficult to do the same through all the transitive dependencies as well (i.e., dependencies of the dependencies listed in `libraries/adaptive-expressions/package.json`).

Unfortunately, unblocking your scenario (without changing your CSP settings) is quite difficult and not something we have prioritized at the moment.

**Comment by shhnjk** [comment]
What version of `browserify` are you using? After [this change](https://github.com/inspect-js/is-generator-function/commit/bce7ca64ae45c8453e6406abf480e55a90100aa0), `Function` constructor wouldn't be called unless `isGeneratorFunction` is actually called.
