### ISSUE TITLE
Adaptive Dialog: "StringExpression accepts string or Expression as the value."

### ISSUE THREAD

**Issue by dschenzer** [microsoft/botbuilder-js#3895]
## Versions
What package version of the SDK are you using.
4.14.1 

What nodejs version are you using
v16.5.0

What os are you using
Windows 10

## Describe the bug
Give a JavaScript coded `Adaptive Dialog`, when using a `String Expression` to define a property for a `Text Input`. 
The evaluation of assigning the `String Expression` is failing as the [test ](https://github.com/microsoft/botbuilder-js/blob/1ffeb7c01326a436442ad5ca84060c857f56e4b5/libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts#L41) for `StringExpression.setValue()` does not evaluate to `true`.

## To Reproduce
Given the following Adaptive Dialog: 
![image](https://user-images.githubusercontent.com/5458637/128492597-01ef9880-6fa8-4b33-8846-616472e3fee0.png)

When the String Expression is getting parsed it should test correctly for Expression and set the value:
![image](https://user-images.githubusercontent.com/5458637/128492902-a22c4bae-f263-4b69-984b-053dddbf2350.png)

## Expected behavior
The String Expression parsing should not throw. 

## Additional context
The user code is written in JavaScript. 
Please, see the _debug console_ in VS Code. 

FYI @Danieladu, that issue is blocking me from progressing at the moment.

**Comment by gabog** [comment]
Hi @joshgummersall, can you please take a look at this issue?

Thanks

**Comment by joshgummersall** [comment]
@dschenzer, `instanceof` has a slightly subtle implication: you must use the same `MAJOR.MINOR.PATCH` package version across all your SDK packages.

If you download the `botbuilder` package, you'll notice we explicitly list the same version for all the SDK packages it depends on. In particular, `botbuilder@4.14.0` references `botbuilder-core@4.14.0` without a `^` and `~`.

On the other hand, if your `package.json` lists different versions, the `instanceof` check will fail as each library imports different Javascript types with different prototype chains.

Can you share your `package.json` file so I can help locate the issue?

**Comment by dschenzer** [comment]
@joshgummersall thanks a lot for that info. As one might tell I'm much more familiar with .NET, so I learned something already. 

Following the package.json
![image](https://user-images.githubusercontent.com/5458637/128683423-02880461-f40f-48a2-88a5-f060060ea098.png)
