### ISSUE TITLE
Interruption from ComponentDialog if AdaptiveDialog was triggered

### ISSUE THREAD

**Issue by dschenzer** [microsoft/botbuilder-js#3905]
## Versions
What package version of the SDK are you using.
4.14.1

What nodejs version are you using
v16.5.0

What os are you using
Windows 10

## Describe the bug
When the bots start we have a `ComponentDialog` which asks for user profile information. If directly afterwards an `AdaptiveDialog` is triggered a `ChoiceInput` is rendered. And immediately afterwards the `ComponentDialog` continues. 

The questions in the following screenshot about FirstName, LastName are comming from the `ComponentDialog` and the "LanguageCard" is an `AdaptiveCard` 

## To Reproduce
1. Bot start, and initial profile action is asked. `ComponentDialog` ran. 
2. Immediately an `AdaptiveDialog` is triggered with the "language questions"
3. It renders an `AdaptiveCard` using `ChoiceInput`-prompt 
4. `ComponentDialog` continues with next questions and get resumed. 

`{
          "$kind": "Microsoft.ChoiceInput",
          "property": "user.languageChoice",
          "prompt": "LanguageCard",
          "maxTurnCount": 3,
          "alwaysPrompt": true,
          "allowInterruptions": "false",
          "outputFormat": "value",
          "choices":
					[
            {
              "value": "en-US", 
              "synonyms": ["english", "englisch", "inglés"]
            },
            {
              "value": "de-DE",
              "synonyms": ["german", "deutsch", "alemán"]
            },
            {
              "value": "es-ES",
              "synonyms": ["spanish", "spanisch", "español"]
            }
          ],
          "defaultLocale": "en-us",
          "style": "list",
          "choiceOptions":
					{
            "inlineSeparator": ", ",
            "inlineOr": " or ",
            "inlineOrMore": ", or ",
            "includeNumbers": true
          },
          "recognizerOptions":
					{
            "noValue": false
          }
        },`

## Expected behavior
When an `AdaptiveDialog` is triggered the `ComponentDialog` which ran before should not be able to interrupt it. 

## Screenshots
![image](https://user-images.githubusercontent.com/5458637/130046798-0670f0b8-124a-4079-9b60-cc0736eabbb6.png)

## Additional context
JavaScript is used. 
And `ComponentDialog` is triggered on bot start.

**Comment by joshgummersall** [comment]
Can you share some sample code that reproduces the issue?

**Comment by stevkan** [comment]
@dschenzer, if you can, the preference would be for the component => adaptive => component dialog code so we can see the what is happening.

**Comment by Danieladu** [comment]
hi @dschenzer  I could not reproduce your issue. Everything works fine. 
Attach my bot and screenshot:
[BugReport.zip](https://github.com/microsoft/botbuilder-js/files/7019205/BugReport.zip)
![image](https://user-images.githubusercontent.com/7289268/130181325-3f80683b-279b-4626-bcc4-005fd596a3c7.png)

You may change the "allowInterruptions" property to `true` in "ComponentDialog".
Thanks!

**Comment by dschenzer** [comment]
The customer abandoned the approach to use a hybrid model of Component and adaptive dialogs. We are in a state where we have both and it is a big problem for us. So are trying to redo all remaining Component Dialogs with Adaptive Dialogs. 

I'm not allowed to share this code publicly. Although I understand it is hard for you guys to help otherwise.
