### ISSUE TITLE
Long ChoicePrompt option defaults to numbered list though channel supports card actions

### ISSUE THREAD

**Issue by ryub3n** [microsoft/botbuilder-js#3907]
## Versions
What package version of the SDK are you using: 4.14.1
What nodejs version are you using: 12.18.4
What os are you using: MacOS Catalina

## Describe the bug
Not sure if it's intended but it's a hassle

## To Reproduce
1. Create a ChoicePrompt with two options with one being a long text e.g. 'The Pokemon Company (TPC)' and 'Others'
2. The choices are displayed as a numbered list

## Expected behavior
Should give a hero card even if it's too long as the channel supports it

https://github.com/microsoft/botbuilder-js/blob/1a565e9bc3617401c7b01cdf04ae791fc279897b/libraries/botbuilder-dialogs/src/choices/choiceFactory.ts#L133

**Comment by mrivera-ms** [comment]
We are not taking feature requests in this repo. Closing as "Won't Fix".
