### ISSUE TITLE
[Dialogs] Language difference in behavior for Dialog.onComputeId()

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#3908]
## Versions
What package version of the SDK are you using. `4.14.x`

## Describe the bug
[`Dialog.OnComputeId()`](https://github.com/microsoft/botbuilder-dotnet/blob/003fbc1daa44f8fff5cb771a251672c748724808/libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs#L258-L261) in the .NET SDK uses [`Object.GetType()`](https://docs.microsoft.com/en-us/dotnet/api/system.object.gettype?view=netcore-3.1) to use the Type's Name of the class if `OnComputeId()` is not overridden. In the JS SDK, an error is thrown if [Dialog.onComputeId()](https://github.com/microsoft/botbuilder-js/blob/1a565e9bc3617401c7b01cdf04ae791fc279897b/libraries/botbuilder-dialogs/src/dialog.ts#L486-L488) is not overridden.

The [Java SDK](https://github.com/microsoft/botbuilder-java/blob/d45fcdb0dbdaab52bfd665dc2498c396c2bea158/libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/Dialog.java#L299-L301) and [Python SDK](https://github.com/microsoft/botbuilder-python/blob/70fee41f4f122143fd27ac22dc17642642d915c3/libraries/botbuilder-dialogs/botbuilder/dialogs/dialog.py#L165-L170) both appear to perform the same behavior as .NET.

## Example
The JS implementation of [`SendHandoffActivity`](https://github.com/microsoft/botbuilder-js/blob/1a565e9bc3617401c7b01cdf04ae791fc279897b/libraries/botbuilder-dialogs-adaptive/src/actions/sendHandoffActivity.ts#L30) in Composer/AdaptiveDialog bots will thrown a runtime error whenever `SendHandoffActivity.onComputeId()` is called. To workaround the bug in the SDK, developers must subclass it and register it as a custom component.

When using the .NET SDK, developers just register [SendHandOffActivity](https://github.com/microsoft/botbuilder-dotnet/blob/003fbc1daa44f8fff5cb771a251672c748724808/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SendHandoffActivity.cs#L13) and no errors are thrown.

## Additional context
This issue was found when working with a customer on a MVP.

**Comment by mrivera-ms** [comment]
Triaged with the team. Will not take this port as Adaptive for JS is in preview.
