### ISSUE TITLE
After some time all teams chat messages result in "Authorization has been denied for this request."

### ISSUE THREAD

**Issue by 01** [microsoft/botbuilder-js#3914]
## Versions
What package version of the SDK are you using.
**botbuilder@4.14.1**
What nodejs version are you using
**v12.13.1**
What browser version are you using
**N/A**
What os are you using
**Windows** 

## Describe the bug
After some non consistent amount of time or other factor  (seems to be approx 12-48 hours ) all requests to Teams chat protocol  fails with 401, and continue to fail until app is restarted.  This does not seem to affect directline chat protocol, and occurs regardless of proactive message or regular bot reply. 

## To Reproduce
Have not been able to reproduce. It appears to be random, or dependent on time (maybe token refresh issue)

## Expected behavior
No 401 errors, or at minimum way to recover or remedy. 

## Screenshots
![image](https://user-images.githubusercontent.com/17934292/131346094-dd7e049a-2ba7-4251-9226-40ab3b7959e2.png)

## Additional context
This application is utilizing both directline and teams chat protocol as well as proactive messaging. All operations are used with the actual bot adapter initialized for the bot, nowhere is context.adapter being used or creation of a new connector client. This is a major issue as causing major outages for our IT Helpdesk.

**Comment by 01** [comment]
Any guidance on this would be much appreciated. This is become a consistent critical issue for us for heavily used application. At bare minimum would like to know best way to recover from this scenario

**Comment by joshgummersall** [comment]
@01 can you share the full stack trace?

**Comment by 01** [comment]
@joshgummersall 

So this is the error along with activity example that caused it. Can provide 100s but there is no consistency with activity type and after the first Authorization error any message from bot, be it proactive or regular response results in this Authorization error on teams chat protocol.  Odd thing is reinitializing the adapter doesnt resolve issue only restart of node process (resulting in reinitialization of adapter in same manner) seems to fix it. 

`are.ts:126) ERROR [TelemetryInitializerMiddleware.onTurn] Error on Telemetry middleware  {
  error: RestError: Authorization has been denied for this request.
      at new RestError (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\@azure\ms-rest-js\lib\restError.ts:18:5)
      at D:\home\site\wwwroot\node_modules\botbuilder\node_modules\@azure\ms-rest-js\lib\policies\deserializationPolicy.ts:117:27
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    code: undefined,
    statusCode: 401,
    request: WebResource {
      streamResponseBody: false,
      url: 'https://smba.trafficmanager.net/amer/v3/conversations/a%3A1fW_orn9VamKXr4d0TaoMk_Fi-e1XmdL6BIP85xT9qbmsxKWF5WVAHhUp5Ng6w1GylKXpQede2vxXY7lGzIenNGknnTX4V2CNRCzfCzeVsZJeoIee6nbtpPL1pyzdflBz/activities/f%3A97af441a-0c1e-a216-f4b6-*********',
      method: 'POST',
      headers: [HttpHeaders],
      body: '{"type":"message","serviceUrl":"https://smba.trafficmanager.net/amer/","channelId":"msteams","from":{"id":"28:50cdaf65-cf3a-456a-8c4a-*********","name":"Help Desk"},"conversation":{"conversationType":"personal","id":"a:1fW_orn9VamKXr4d0TaoMk_Fi-e1XmdL6BIP85xT9qbmsxKWF5WVAHhUp5Ng6w1GylKXpQede2vxXY7lGzIenNGknnTX4V2************","tenantId":"971f0e31-00d6-4e42-b8e0-**********"},"recipient":{"id":"29:1StogpCCOwA_daaoMs3VVf0k-GIqtwHTqy3rWc8YKZgS8zUsR4F_vTid8OyPsnJhnMJZ3RcZo********","name":"Sher,******","aadObjectId":"f687ad01-5a53-4188-8d31-*********"},"locale":"en-US","text":"Thanks for contacting the Help Desk! Message me if you need anything else.","inputHint":"acceptingInput","replyToId":"f:97af441a-0c1e-a216-f4b6-c******"}',
      query: undefined,
      formData: undefined,
      withCredentials: false,
      abortSignal: undefined,
      timeout: 0,
      onUploadProgress: undefined,
      onDownloadProgress: undefined,
      proxySettings: undefined,
      keepAlive: undefined,
      agentSettings: undefined,
      operationSpec: [Object]
    },
    response: {
      body: '{"message":"Authorization has been denied for this request."}',
      headers: [HttpHeaders],
      status: 401
    },
    body: { message: 'Authorization has been denied for this request.' }
  },
  activity: {
    type: 'event',
    name: 'ContinueConversation',
    channelId: 'msteams',
    locale: 'en-US',
    serviceUrl: 'https://smba.trafficmanager.net/amer/',
    conversation: {
      conversationType: 'personal',
      tenantId: '971f0e31-00d6-4e42-b8e0-*****',
      id: 'a:1fW_orn9VamKXr4d0TaoMk_Fi-e1XmdL6BIP85xT9qbmsxKWF5WVAHhUp5Ng6w1GylKXpQede2vxXY7lGzIenNGknnTX4V2CNRCzfCzeVsZJeoIee6nb***********'
    },
    from: {
      id: '29:1StogpCCOwA_daaoMs3VVf0k-GIqtwHTqy3rWc8YKZgS8zUsR4F_vTi************************',
      name: '******',
      aadObjectId: '*****'
    },
    recipient: {
      id: '28:50cdaf65-cf3a-***-8c4a-*******',
      name: 'Help Desk'
    },
    id: 'f:97af441a-0c1e-a216-f4b6-******'
  }
}`

**Comment by joshgummersall** [comment]
@01 have you tried manually refreshing the adapter's token? Try something like the following:

```diff
diff --git a/samples/javascript_nodejs/02.echo-bot/index.js b/samples/javascript_nodejs/02.echo-bot/index.js
index 99bb0fecc..c1bd60c47 100644
--- a/samples/javascript_nodejs/02.echo-bot/index.js
+++ b/samples/javascript_nodejs/02.echo-bot/index.js
@@ -1,27 +1,29 @@
 // Catch-all for errors.
 const onTurnErrorHandler = async (context, error) => {
+    // Attempt to manually refresh token on 401 error
+    if (error.statusCode === 401) {
+        const { credentials } = adapter;
+        if (credentials) {
+            try {
+                await credentials.getToken(true);
+            } catch (err) {
+                console.error("Unable to refresh token...", err);
+            }
+        }
+    }
```

This is, of course, a workaround but it may unblock your scenario. There is logic to refresh the token automatically if it expires, but there must be a race condition or edge case that isn't handled. This should ensure the token is "force refreshed" whenever the Bot receives a 401 error.

This diff is based on [sample 02](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/javascript_nodejs/02.echo-bot/index.js).

**Comment by 01** [comment]
@joshgummersall  Perfect, exactly guidance I was looking for thank you. Not sure why didnt think of this as use the exact logic for getting attachments an authorization fails. I assumed creating a new BotAdapter would in turn grab a token, but fact its static cache makes sense for behavior was witnessing.

Thank you.

**Comment by joshgummersall** [comment]
Sorry for the delayed reply! Feel free to reopen the issue if the problem continues.

**Comment by cgvalayev** [comment]
Hey @joshgummersall that is a good workaround but Im curious if any progress has been made to resolve this permanently? We are getting same exact error:
NodeJS: v14.x.x
botbuilder-sdk: 4.16.0
