### ISSUE TITLE
listTranscripts (BlobsTranscriptStore) showing duplicates

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/botbuilder-js#3924]
"dependencies": {
        "botbuilder-azure": "^4.14.1",
        "botbuilder-azure-blobs": "^4.14.1-preview",
        "botbuilder-core": "~4.14.0",
        "dotenv": "^8.2.0",
        "path": "^0.12.7",
        "readline": "^1.3.0"
    },
  
**BlobsTranscriptStore.listTranscripts results in a list showing the conversation ID for each occurence of an activity in that conversation.**

To reproduce:
.1 clone the 01. console-log-echo sample locally
.2 NPM install
.3 NPM install 'botbuilder-azure-blobs'
.4 add a .ENV file with
```
AZURE_STORAGE_CONNECTION_STRING=<Valid connection string>
STATE_BLOB_CONTAINER_NAME=<some name for the container>
```
5. add the following code to index.js

```
const { BlobsTranscriptStore } = require('botbuilder-azure-blobs');
const myTranscriptStorage = new BlobsTranscriptStore(process.env.AZURE_STORAGE_CONNECTION_STRING, process.env.TRANSCRIPT_BLOB_CONTAINER_NAME);
var transcriptMiddleware = new TranscriptLoggerMiddleware(myTranscriptStorage);
adapter.use(transcriptMiddleware);
```

6. replace 

```
const bot = new EchoBot();
```
by

```
const bot = new EchoBot(myTranscriptStorage);
```

7. Add a constructot to bot.js

```
constructor(myTranscriptStorage) {
        this.myTranscriptStorage = myTranscriptStorage;
    }
```

8 In the else statement of the onTurn handler add

```
          const conversationList = await this.myTranscriptStorage.listTranscripts('console');
                console.log(conversationList);
```

9. Start index.js

You will see that every time you type a new message in the console (in the same conversation), the list with duplicatie conversation id-'s gets longer.

## Expected behavior
I would expect a list with conversation ID's without duplicates

**Comment by HesselWellema** [comment]
I am using a workaround (removing duplicates after downloading). So maybe this would be a product suggestion

**Comment by srinaath** [comment]
@anusharr  Any updates on this ticket?

**Comment by anusharr** [comment]
@HesselWellema, apologize for the delay in response. Let me attempt a repro on my end and update the thread accordingly with my findings.

**Comment by anusharr** [comment]
I am able to reproduce the issue with the list showing conversation id and timestamp based on the last entry. Do you mind sharing a screenshot of the list on the console as well as in your container on Azure? Also, when you specify that you are removing duplicates, are you deleting the item from the container?

**Comment by HesselWellema** [comment]
Tnx @anusharr 

After my transcript items are shown on the console, my bot sends some additional activities. So the list with activities in the container is a bit longer. Hope that is not a problem.

Wrt your question about removind duplicates: I remove duplicates in the result of listTranscripts.

```
            let uniqueList = [...new Set(listWithDuplicates)];
```

After that I use the list with unique conversation Id's  to get the activities with getTranscriptActivities. The result I use to share transcripts of the bot with my customer.

![item in listTranscripts result (console)](https://user-images.githubusercontent.com/23032884/133564063-9eaa568e-fd5c-4754-a7eb-fdda5b666c8b.png)
![transcripts  container](https://user-images.githubusercontent.com/23032884/133564091-26e5e6a5-7c50-434d-a4c2-41b075bca2f0.png)

**Comment by anusharr** [comment]
@HesselWellema, can you share a screenshot of your recent blob transcript json entry along with the listTranscript screenshot after removing the duplicates?
