### ISSUE TITLE
send a number throught DialogTestClient class's sendActivity method

### ISSUE THREAD

**Issue by Zakaria-Khorf** [microsoft/botbuilder-js#3930]
Hello, 

I am using the botbuilder DialogTestClient 's sendActivity method to send prompts to my bot while testing but the method only accepts string types and in my bot i use number promts to prompt the user for numbers . Do you have any idea on how i can overturn this problem ? 

Thanks in advance

**Comment by joshgummersall** [comment]
We generally direct usage questions to [StackOverflow](https://stackoverflow.com/questions/tagged/botframework?tab=Newest), please ask there.
