### ISSUE TITLE
Proactive bot requires reinstall to MS Teams' team after restify restart

### ISSUE THREAD

**Issue by mateusmlo** [microsoft/botbuilder-js#3957]
## Versions
SDK: ~4.14.0
Node.js: 16.3.0
Browser: Edge 94.0.992.50
OS: Windows 11

## Describe the bug
I'm currently building a simple bot that sends proactive messages to a MS Teams' team. Everything works fine, except that upon restarting the restify server the bot won't send anything to Teams unless it is reinstalled (the messages are logged to the console and this works just fine, so the problem is in the connection to Teams somehow), and we can't figure out why this is happening. For context, I built the bot on top of the [proactive messages sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/16.proactive-messages). 

## To Reproduce
It is quite a lot of work to reproduce so I'll just leave what I've done: have a restify server listening on port 3978, tunnel it through ngrok, add the https address to the Bot resource messaging endpoint on Azure, then build a bot on Teams using App Studio. Upon hitting the URL https://[[NGROK URL]]/api/notify, the bot should then search if it is someone's birthday by reading a csv file and then post a nice birthday message to the team's General channel. But as I said, it works just fine until I CTRL+C the restify server and start it again: the bot won't work again unless reinstalled to the team, and in my opinion this behaviour makes no sense.

## Expected behavior
The bot should work normally after killing the server and restarting it.

**Comment by stevkan** [comment]
Closing as resolved.

**Comment by mateusmlo** [comment]
Hello @stevkan! First of all, pardon me for the huge delay in following up your reply. We got tied up in another project's demands with a holiday in between, so it took a lot of time.
I've checked here and indeed I'm using the CloudAdapter class, following recent updates in the aforementioned sample. Since you managed to make it work using the BotFrameworkAdapter, would you suggest I change back to this one instead of the CloudAdapter?
