### ISSUE TITLE
BotFrameworkAdapter appears to corrupt the dialog stack when a waterfall step returns Dialog.EndOfTurn

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-js#398]
@v-ducvo , please add repo code when you get a chance.

Short form, we tried defining a waterfall step that ended with:
```js
return Dialog.EndOfTurn;
```
But then the dialog context on the next turn showed nothing on the stack, even though there were more steps defined for the dialog. (We're using last night's bits.)

**Comment by Stevenic** [comment]
Why are you returning the result of `dc.context.sendActivity()` ?  That returns the ID of the message that was created not a DialogTurnResult.

**Comment by v-ducvo** [comment]
Yes. I did a test to check the return value and it is the ID...but, if it is causing the dialog to be cleared when I make this call in a component dialog, why doesn't it do the same when I'm in the "mainMenu" dialog? The behavior is not consistent.

**Comment by Stevenic** [comment]
I'm not sure why your stack is getting cleared but it's probably something else. The code below works fine:

```
const { BotFrameworkAdapter, ConversationState, UserState, BotStateSet, MemoryStorage } = require('botbuilder');
const { DialogSet, WaterfallDialog, Dialog } = require('botbuilder-dialogs');
const restify = require('restify');

// Create server
let server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
    console.log(`${server.name} listening to ${server.url}`);
});

// Create adapter
const adapter = new BotFrameworkAdapter( { 
    appId: process.env.MICROSOFT_APP_ID, 
    appPassword: process.env.MICROSOFT_APP_PASSWORD 
});

// Add state middleware
const storage = new MemoryStorage();
const convoState = new ConversationState(storage);
const userState = new UserState(storage);
adapter.use(new BotStateSet(convoState, userState));

// Listen for incoming requests 
server.post('/api/messages', (req, res) => {
    // Route received request to adapter for processing
    adapter.processActivity(req, res, async (context) => {
        // Dispatch to dialogs
        const dc = await dialogs.createContext(context);
        await dc.continue();
        if (context.activity.type === 'message' && !context.responded) {
            await dc.begin('test');
        }
    });
});

// Create dialog set and add dialogs
const dialogState = convoState.createProperty('dialogState');
const dialogs = new DialogSet(dialogState);

dialogs.add(new WaterfallDialog('test', [
    async (dc, step) => {
        return await dc.context.sendActivity(`What's your name?`);
    },
    async (dc, step) => {
        await dc.context.sendActivity(`Hi ${step.result}!`);
        return await dc.end();
    }
]));
```

Let my try a variant the uses a `ComponentDialog`

**Comment by v-ducvo** [comment]
Clone my bot and run the code...put a breakpoint on the line where "dc.continue()" is called...then check the "dc" object, you'll see that the stack is empty.
Here is a link to our samples repo: [Modular Bot Logic](https://github.com/Microsoft/BotFramework-Samples/tree/snippets4ignite/docs-samples/V4/JS/modular-bot-logic)

**Comment by Stevenic** [comment]
Ok the COmponentDialog version repro's the problem. Let me debug it

**Comment by v-ducvo** [comment]
Great! Thanks.

**Comment by Stevenic** [comment]
The test below is failing because your not returning the **required** DialogTurnResult. I'm hesitant to fix this because you can't just return anything you want from a function and expect things to work.  I need to talk it over with the team. 

https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/componentDialog.ts#L33

**Comment by Stevenic** [comment]
If anything... I think we would add logic to detect that you returned an invalid response type and then throw an error.

**Comment by v-ducvo** [comment]
if ending a waterfall step requires a DialogTurnResult to be returned, then we should throw an error if a dev tries what I did; otherwise, they will get unexpected behavior and they won't know why. 

Because it worked for me, I assumed I could return "whatever"...anyways, in the doc, we will make sure to call it out and will update the sample code snippet so that the bot returns an "EndOfTurn" after the send activity message....

I think between the error message and the updated content/snippet should resolve this issue.
