### ISSUE TITLE
Incorrect check against Content-Type instead of content-type in httpRequest

### ISSUE THREAD

**Issue by NickHeap2** [microsoft/botbuilder-js#3992]
## Describe the bug
Incorrect check against Content-Type instead of content-type in httpRequest.
if (key.toLowerCase() === 'Content-Type')
should be
if (key.toLowerCase() === 'content-type')
Currently the check doesn't change content-type to Content-Type.

## To Reproduce
Bug is in libraries/botbuilder-dialogs-adaptive/src/actions/httpRequest.ts at line 271

## Expected behavior
The check should change content-type to Content-Type.

## Additional context
Happy to submit a PR with the change.

**Comment by joshgummersall** [comment]
@NickHeap2 in the [`fetch` spec](https://fetch.spec.whatwg.org/#terminology-headers), my understanding is headers are serialized as case-insensitive. The logic in your PR is sound, but I don't think the fix will actually change any behavior?
