### ISSUE TITLE
Bot framework V4. Unable to use ⭐ emoji in suggested actions

### ISSUE THREAD

**Issue by kevit-samir-katyar** [microsoft/botbuilder-js#4007]
## Versions
What package version of the SDK are you using - 4.1.6
What nodejs version are you using - v14.18.2
What browser version are you using - Chrome
What os are you using - ubuntu 

## Describe the bug
I need to implement rating\review functionality in one of my bots. My plan was to use suggested actions and emojis in a waterfall dialog. As soon as I use star ⭐ in the options, the dialog does not go to the next step when this option is selected. It does work for other emoji-like 😁
I am testing it in the emulator..

async askFeedbackStep(stepContext) {
        const CHOICES = ['⭐','😀'];
        return await stepContext.prompt(FEEDBACK_PROMPT, {
            choices: ChoiceFactory.toChoices(CHOICES),
            style: ListStyle.suggestedAction
        });
    }
} 

So if the user selects the first option with the code below, the option is not accepted and the dialog prompt is shown again. With the second option, the dialog goes to the next step.

## Screenshots
![image](https://user-images.githubusercontent.com/48083009/145208793-d93130d7-e719-4cbb-94e4-268334e4cd19.png)

**Comment by kevit-samir-katyar** [comment]
@JuanAr can i get any update on this

**Comment by ceciliaavila** [comment]
Hi @kevit-samir-katyar, thanks for opening this issue. This is currently in our backlog and we'll be reviewing this issue this week.

**Comment by kevit-samir-katyar** [comment]
@ceciliaavila sure
