### ISSUE TITLE
CosmosDb throwing "documentdb_1.ConnectionPolicy is not a constructor" error at compile time

### ISSUE THREAD

**Issue by v-ducvo** [Microsoft/botbuilder-js#403]
**This issue was reported in an email. I'm posting the content of that email here to track the status of this issue.**

I’m running into this error and am not sure what the work around is. I am getting this at compile time.

In my bot, I have created a new CosmosDbStorage object like this:
```javascript
const storage = new CosmosDbStorage({
    serviceEndpoint: "https://lucascosmos.documents.azure.com:443/", 
    authKey: "xCmY4dZqZACCVUoExxAbfa38MwPjShqbm2TTqNhzKnqlTCLSc8mTio1TeCbEu2dCCg8VmNAohRARuUMPmmrRPg==", 
    databaseId: "Tasks",
    collectionId: "Items"
});
```

This failed with the error:
```javascript
c:\Users\v-ducvo\Documents\botdocs\samples\BotFramework-Samples\docs-samples\V4\JS\node_modules\botbuilder-azure\lib\cosmosDbStorage.js:32 
const policy = new documentdb_1.ConnectionPolicy(); 
^ 
TypeError: documentdb_1.ConnectionPolicy is not a constructor 
at new CosmosDbStorage (c:\Users\v-ducvo\Documents\botdocs\samples\BotFramework-Samples\docs-samples\V4\JS\node_modules\botbuilder-azure\lib\cosmosDbStorage.js:32:24) 
at Object.<anonymous> (c:\Users\v-ducvo\Documents\botdocs\samples\BotFramework-Samples\docs-samples\V4\JS\manage-conversation-and-user-state\azure-cosmos-db.js:40:17) 
```

Looking at line 67 of the source file, I see that connectionPolicyConfigurator is an optional field:
```javascript
/**
     * Creates a new ConsmosDbStorage instance.
     *
     * @param settings Setting to configure the provider.
     * @param connectionPolicyConfigurator (Optional) An optional delegate that accepts a ConnectionPolicy for customizing policies. More information at http://azure.github.io/azure-documentdb-node/global.html#ConnectionPolicy
     */

    public constructor(settings: CosmosDbStorageSettings, connectionPolicyConfigurator: (policy: ConnectionPolicy) => void = null)
```

…so, why am I getting this error at compile time? The failure came at [line 67](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-azure/src/cosmosDbStorage.ts#L67) where it tries to create a new ConnectionPolicy():

`const policy: ConnectionPolicy = new ConnectionPolicy();`

How can I avoid this error from my code?

**Comment by daveta** [comment]
Chatted with @v-ducvo, seeing same results. 
C# appears to work fine, the js version appears to be broken.  Think we need some js chops to investigate.
