### ISSUE TITLE
Migrate from azure-storage and documentdb to @azure/cosmos

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/botbuilder-js#4074]
_Note: This issue may be covered in the v5.1 issue #3995._

The libraries azure-storage and documentdb are deprecated as of September 2020. Recommended is to upgrade to @azure/cosmos.
https://www.npmjs.com/package/azure-storage
https://www.npmjs.com/package/documentdb

libraries/botbuilder-azure/package.json shows:
 ```
 "dependencies": {
    "@azure/cosmos": "^3.3.1",
    "@types/documentdb": "^1.10.5",
    "azure-storage": "2.10.2",
    "documentdb": "^1.15.3",
```

Looks like we already have a dependency on @azure/cosmos. It also looks like migration from the outmoded libraries needs to be completed and the azure-storage and documentdb dependencies removed.

The migration guide: [Guide for migrating to @azure/storage-blob v12 from azure-storage](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/storage-blob/MigrationGuide.md)

**Comment by mrivera-ms** [comment]
Assigning @JuanAr for investigation.

**Comment by sw-joelmut** [comment]
@mrivera-ms, the libraries `azure-storage` and `documentdb` are used by the [CosmosDbStorage](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-azure/src/cosmosDbStorage.ts#L82-L92), [BlobStorage](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-azure/src/blobStorage.ts#L99-L109) and [AzureBlobTranscriptStore](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-azure/src/azureBlobTranscriptStore.ts#L24-L33) **deprecated** classes.
Should we still make the migration despite the deprecated classes?
