### ISSUE TITLE
Consistency of method names across ComponentDialog and Dialog

### ISSUE THREAD

**Issue by carlosscastro** [Microsoft/botbuilder-js#408]
ComponentDialog has methods
                dialogBegin
                dialogContinue
                dialogResume
                dialogReprompt
                dialogEnd
                onDialogBegin
                onDialogContinue
                onDialogEnd
                onDialogReprompt
 
DialogContext
                begin()
                cancelAll()
                continue()
               end()
 
etc.
Shouldn’t these be the same method names?

**Comment by sgellock** [comment]
Will need a final list of name changes so we can optimize for the docs team

**Comment by carlosscastro** [comment]
Tracking progress

- [ ] dotnet PR
- [ ] dotnet Merged
- [ ] js PR
- [ ] js Merged
- [ ] samples PR
- [ ] samples Merged

**Comment by carlosscastro** [comment]
PR merged: https://github.com/Microsoft/botbuilder-js/pull/434
