### ISSUE TITLE
Chatbot working on emulator but not working on Web Chat and Direct Line after publishing to Azure

### ISSUE THREAD

**Issue by kpietraszkoGit** [microsoft/botbuilder-js#4107]
Hello,
When I try to deploy and test the bot on Azure I'm getting the following error: There was an error sending this message to your bot: HTTP status code InternalServerError. I also have error 502 in the browser console: https://directline.botframework.com/v3/directline/conversations/1Td3aCZWwMV92LyotjCNuT-eu/activities 502
Use: JavaScript
Deployment Environment: Azure Bot Service
MicrosoftAppId and MicrosoftAppPassword has been set correctly in the .env file.
I use Luis and Snowflake too.
Please let me know if there is any information which I can provide to help resolve my issue.

**Comment by kpietraszkoGit** [comment]
@stevkan thank you for answer.
This is my App Service Configuration: 
<img width="514" alt="confAppService" src="https://user-images.githubusercontent.com/54677750/153160310-965dd055-52cd-4027-9ca1-badcf21abe6f.PNG">
I think everything is ok in the configuration.
When I want to test a bot in Azure. The window is empty and the bot is not responding. 
<img width="325" alt="testWebChat" src="https://user-images.githubusercontent.com/54677750/153161746-2ab60a79-cdd5-489d-b73b-844c178f74d5.PNG">
However, the bot works fine in the Bot Framework Emulator.
Unfortunately I can't send all the code for you.
What are you interested in the code?
Is it possible that my Microsoft ID and password have expired?

**Comment by kpietraszkoGit** [comment]
Hi,
I have a URL address and an endpoint like in the pictures, I think it is correct.
<img width="523" alt="BotEndPoint" src="https://user-images.githubusercontent.com/54677750/153609370-85aeaf8a-1cb8-4856-b346-15213001eaf2.PNG">
<img width="257" alt="appServiceURL" src="https://user-images.githubusercontent.com/54677750/153609376-6209a110-c889-4d05-ac60-29f98253bb50.PNG">
What else can I check? Maybe some code fragment will help?
Thx for your answer.

**Comment by stevkan** [comment]
@kpietraszkoGit, thank you for your patience. If you haven't already, can you add/enable Application Insights in Azure? Then when attempting to chat via Web Chat you can see more of what is happening when the connector gets the request and forwards it to the bot, and what kind of response the bot is returning with.

When the connector gets an error code from the bot, it is only going to return a 500 type error code to the client even tho the bot may be returning a 400 type error code.
