### ISSUE TITLE
[botframework-connector] upgrade and clean up dependencies

### ISSUE THREAD

**Issue by restfulhead** [microsoft/botbuilder-js#4123]
1. `@azure/identity` uses a beta version,  @azure/ms-rest-js is also very outdated. This could also have security implications. Suggest to upgrade.
2. Is it necessary to pin `jsonwebtoken` to a specific patch version? I suggest to use `^8.0.1` of `~8.0.1` instead of `8.0.1`. This would make it more compatible. 
3. There are a few type dependencies, which should be defined as dev dependencies `@types/jsonwebtoken` and `@types/node`.

current package.json:
```
"dependencies": {
    "@azure/identity": "2.0.0-beta.6",
    "@azure/ms-rest-js": "1.9.1",
    "@types/jsonwebtoken": "7.2.8",
    "@types/node": "^10.17.27",
    "adal-node": "0.2.3",
    "axios": "^0.25.0",
    "base64url": "^3.0.0",
    "botbuilder-stdlib": "4.1.6",
    "botframework-schema": "4.1.6",
    "cross-fetch": "^3.0.5",
    "jsonwebtoken": "8.0.1",
    "rsa-pem-from-mod-exp": "^0.8.4",
    "zod": "~1.11.17"
  },
```

**Comment by mrivera-ms** [comment]
Assigning to @JuanAr for investigation.

**Comment by ceciliaavila** [comment]
@mrivera-ms in progress
