### ISSUE TITLE
Not able to Make call with Skype BOT using Skype IOS version 8.81.0.268

### ISSUE THREAD

**Issue by sunijk** [microsoft/botbuilder-js#4146]
HI Team,

We are facing some issue while making a call with Skype BOT using IOS Skype version 8.81.0.268. Instead of making a normal video call it popups with a group call and the end user is not able to attend the call.

![image](https://user-images.githubusercontent.com/14799495/156370259-603acf88-6c92-4573-93f8-82a9ccb83061.png)

With previous version of  Skype version, we were able to make video calls using the same BOT. And also the version of skype is working with Android ( 8.81.0.268).

To make a video call using the Skype Bot we are using the following code

<img width="483" alt="image" src="https://user-images.githubusercontent.com/14799495/156370889-9b4e2524-099b-4338-aaf5-0114068a9ec3.png">

Is this issue due to the latest version 8.81.0.268 update, Or any suggestion to overcome to this issue.

**Comment by arturl** [comment]
Thanks for clarification @sunijk. Transferring to the Bot Framework JS repo.

**Comment by sunijk** [comment]
Any update on this?

**Comment by dmvtech** [comment]
I am investigating this. Please stand by.

**Comment by dmvtech** [comment]
@sunijk What is `ag` that you are passing in to `CreateCallingCard(__)` ? (Where you are value to the id: `ag.Id`)

**Comment by sunijk** [comment]
We are calling the CreateCallingCard() from send activity and the ag.Id is the skype handle name of the user .

<img width="443" alt="image" src="https://user-images.githubusercontent.com/14799495/158751398-abf01271-1d8e-44b7-96cf-93dabc50bed7.png">

sample skype handle 

![image](https://user-images.githubusercontent.com/14799495/158751876-39e712ad-a4cb-4953-8c0a-6c8fd7c06c4c.png)

The skype handle is the same skype name available in the Profile ->settings of the skype user

![image](https://user-images.githubusercontent.com/14799495/158752251-a83cb3ad-7571-400e-b1d7-e4e5db4a65d0.png)

**Comment by dmvtech** [comment]
I have confirmed there is no difference in the output from the bot between Skype on Windows 10, Android or iOS. This is an issue with the Skype connector or the Skype clients themselves. 

There is nothing in the outgoing activity that is different other than the IDs and timetamps, and the attachments are _identical_:

```
    attachments: [
      {
        content: {
          buttons: [
            {
              title: '📞 CALL',
              type: 'call',
              value: 'skype:live:.cid._________________'
            }
          ],
          images: [],
          title: '⏱ Click here to call'
        },
        contentType: 'application/vnd.microsoft.card.hero'
      }
    ],
```

I'm closing this as this is not a a bug/issue with the SDK.
