### ISSUE TITLE
BlobsTranscriptStore blobkey not persisting '/' for virtual directory

### ISSUE THREAD

**Issue by Sprinkle** [microsoft/botbuilder-js#4176]
## Versions
What package version of the SDK are you using. `4.15.0`
What nodejs version are you using `14`

## Describe the bug
Trying to use the blobsTranscriptStore to record transcript.  From the code, expecting the blob created for activity in Azure Storage to follow the pattern of `container/{channelId]/{conversationId}/{Timestamp.ticks}-{activity.id}.json`

https://github.com/microsoft/botbuilder-js/blob/64926f42264863ee5d3519522013e238aa295b3c/libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts#L61-L69

But instead the blog key ended up with the '/' also URIencoded so the blob name in Azure blob ended up to be `container%2F{channelId}%2F{conversationId}%2F{Timestamp.ticks}-{activid.id}.json`.  Which makes it not compatible with the virtual directory feature of the Azure Blob with the actual character '/' in the key. 

It looks like it is because the way `sanitizeBlobKey` is implemented, which also sanitized the '/' character.

https://github.com/microsoft/botbuilder-js/blob/a7000885acca69f52a0c7f301a44835f3f8f100e/libraries/botbuilder-azure-blobs/src/sanitizeBlobKey.ts#L4-L18

## To Reproduce
Steps to reproduce the behavior in a adaptive dialog bot with bot composer.
1. Configure 'appsettings.json'
   1. set 'runtimeSettings::features::traceTranscript' to 'true'
   2. set 'runtimeSettings::features::blobTranscript' with 'connectionString' and 'containerName'
2. Interact with the bot
3. Check the transcript created in Azure blob container

## Expected behavior
The blob created to have a key with actual '/' in the name rather than sanitized with %2F

## Screenshots
Blob key with %2F generated.  Expect to be real '/' such that it becomes "virtual directory" in storage explorer.

![image](https://user-images.githubusercontent.com/1852906/161103006-58441341-8205-4e64-9bbb-d4d082fb49d7.png)

**Comment by ramfattah** [comment]
Hello @Sprinkle, I'm investigating this.

**Comment by ramfattah** [comment]
@Sprinkle, 

Thank you for raising this issue. 

I'm able to repro this. I followed the issue's ticket [steps to reproduce](https://github.com/microsoft/botbuilder-js/issues/4176#:~:text=Configure%20%27appsettings.json,Azure%20blob%20container) in composer.
![image](https://user-images.githubusercontent.com/38049078/161204448-07304210-3175-44a4-b96f-47af4f96a7f1.png)

**Comment by tdurnford** [comment]
@ramfattah Any updates here?

**Comment by Sprinkle** [comment]
Thanks for looking into this.  Also there seems to be another implementation of sanitizeKey in another file, if may have the same issue.

https://github.com/microsoft/botbuilder-js/blob/98b1499456b28662f9b7d7c37ee6c0841f87fde5/libraries/botbuilder-azure/src/blobStorage.ts#L297-L318

**Comment by ramfattah** [comment]
@Sprinkle 

It seems this sanitizeKey method in `botbuilder-azure` library does not return the [encodeURIComponent](https://github.com/microsoft/botbuilder-js/blob/0c17b50b6ef4dbfe741d1509e697f0b534814103/libraries/botbuilder-azure-blobs/src/sanitizeBlobKey.ts#L17) key.

Are you getting the same issue of blob key not persisting '/'  for the `botbuilder-azure` library as well?

**Comment by Sprinkle** [comment]
@ramfattah yes it does, the `escape` function seems to do something similar.  This blobsStorage is used by the bot state storage.

https://github.com/microsoft/botbuilder-js/blob/98b1499456b28662f9b7d7c37ee6c0841f87fde5/libraries/botbuilder-azure/src/blobStorage.ts#L317

Same issue as the transcripts.  When using BlobsStorage for bot state, the blob don't have / in the key.

![image](https://user-images.githubusercontent.com/1852906/163335448-ee9f866b-84a0-4cde-b664-4af8a8e00f55.png)

**Comment by ramfattah** [comment]
Hey @Sprinkle 

in JS 4.16 SDK, there is now an optional setting in the [blobsTranscriptStore.ts](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts#:~:text=decodeTranscriptKey%3F%3A%20boolean%3B) that allows you to flip the `decodeTranscriptKey` boolean property to true and it will fix this bug. 

#

BlobsTranscriptStore implementation example: 

``` diff
            const connectionString = "mykey";
            const containerName = "transcripts";

            const blobClient = () =>
                connectionString && containerName
                    ? new BlobsTranscriptStore(connectionString, containerName)
                    : null;

+            const BlobsTranscriptStoreOptions = {
+                decodeTranscriptKey: true,
+            };

            const client = blobClient();
            await client.logActivity(
                context.activity,
+                BlobsTranscriptStoreOptions
            );

```

**Comment by Sprinkle** [comment]
Great, thank you @ramfattah, will test it out when 4.16 SDK is available.

Shall I open another issue for the problem in the `botbuilder-azure` `BlobStorage` code?

**Comment by ramfattah** [comment]
@Sprinkle,

Sure, that would be great.
Feel free to mention me in that new issue and I'll try to assign it to myself and track it. 

#

Thank you so much for your contribution to Bot Framework.
