### ISSUE TITLE
Language Understanding (LUIS) V3 doesn't support Bing Spell Check API

### ISSUE THREAD

**Issue by mountju** [microsoft/botbuilder-js#4247]
## Version
"botbuilder": "~4.15.0",
"botbuilder-ai": "~4.15.0",

## Describe the bug
I try to improve LUIS intents prediction accuracy. Because there is an issue when missing one letter leads LUIS to a wrong intent. I use the [tutorial](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-tutorial-bing-spellcheck), but still I don't get the expected value "alteredQuery" in the JSON returned form LUIS.
this is how I use it:

```
const luisConfig: LuisApplication = {
    applicationId: [APP_ID_GOES_HERE],
    endpointKey: [KEY_GOES_HERE],
    endpoint: [ENDPOINT_GOES_HERE],
};
```

```
const recognizerOptions: LuisRecognizerOptionsV2 = {
    apiVersion: 'v2',
    bingSpellCheckSubscriptionKey: [KEY_GOES_HERE];
    includeAllIntents: true,
    log: true,
    spellCheck: true,
    log: true,
    includeInstanceData: true
};
```
```
const luisRecognizer = new LuisRecognizer(luisConfig, recognizerOptions, true);
```

## Expected behavior
As per documentation I should get the response as follows:
``` 
"query": "bouk me a fliht to kayro",
  "prediction": {
    "alteredQuery": "book me a flight to cairo",
    "topIntent": "book a flight",
    "intents": {
      "book a flight": {
        "score": 0.9480589
      }
      "None": {
        "score": 0.0332136229
      }
    },
    "entities": {}
  }
}
```

## But the reality is different - there is no "alteredQuery"
``` 
"query": "bouk me a fliht to kayro",
  "prediction": {
    "topIntent": "book a flight",
    "intents": {
      "book a flight": {
        "score": 0.9480589
      }
      "None": {
        "score": 0.0332136229
      }
    },
    "entities": {}
  }
}
```

**Comment by anishprasad01** [comment]
Closing in favor of [duplicate issue](https://github.com/microsoft/botframework-sdk/issues/6513).
