### ISSUE TITLE
Custom Question Answering previous prompt buttons do not pass question ID

### ISSUE THREAD

**Issue by hlavacek** [microsoft/botbuilder-js#4253]
## Versions
What package version of the SDK are you using: 4.1.6
What nodejs version are you using: v14.17.3
What browser version are you using: N/A
What os are you using: N/A

## Describe the bug
This issue is little related to #4242. We have a custom question answering bot, which has many questions with prompts. The issue is, if users asks one question which will give out couple prompt button answers. User clicks on one and as fixed in #4242, this now correctly passes the QnaID into the custom question answering. But then if the user scrolls up in the bot and selects a different button prompt (or the same), then the QnaID is not sent to custom question answering and only the text is used to match the answer - which may be wrong. This flow works correct when using the "Test" functionality in Custom Question Answering in Language studio.

## To Reproduce

1. Create a knowledge base with 3 questions, the idea is that the prompt will reference one question, but the text will be from a different one:
    - Qna ID: 1,  "question 1" - answer should contain prompt: "Question 2 explanation text", reference to Qna ID 2
    - Qna ID: 2, "question 2" - answer should be "question 2 answer"
    - Qna ID: 3, "Question 2 explanation text" - answer should be "question 2 wrong answer"
2. deploy the knowledge base and test with with local bot (not with the "Test" button in language studio, there it works correct), for example with [sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/48.customQABot-all-features)
3. use the following question flow:
    1. "question 1" - should give prompt with text "Question 2 explanation text" 
    2. Click on the prompt button
    3. With the fix for #4242 this gives a correct answer with Qna ID 2 the first time
    4. scroll up and click the button again 
    5. Now the wrong answer with Qna ID 3 is shown

## Expected behavior
On any of the button clicks, the framework should keep the reference to the QnaID with the prompt button and send the correct QnA ID to the Custom Question Answering.

## Additional context
I have checked the code and in my understanding the QnaId for the prompts is kind of stored within the conversation context, but that is closed once user selects the button first time. So for the latter clicks to the same buttons (or other buttons from the past), the button QnaIDs are no longer available and just the text is passed. 

In my case I was able to do a fix for this issue in [qnaCardBuilder.ts](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-ai/src/qnaCardBuilder.ts#L78), by changing the prompts from 'imBack' into 'messageBack' type, and also keeping the qnaId in the value:

```(javascript)
  buttonList.push({
    value: prompt.qnaId,
    type: 'messageBack',
    title: prompt.displayText,
    displayText: prompt.displayText,
  });
```

Then also I had to fix the code on few places to correctly use the qnaId from the button and not from the context. But not sure if this would be a preferred solution for the framework.

**Comment by ramfattah** [comment]
Hi @Arsh-Kashyap, can you please take a look at this issue?

Thanks.

**Comment by Arsh-Kashyap** [comment]
Hi @ramfattah, I discussed this issue with the team. This is expected by design. If this is an ask we can discuss it internally in a meeting to support this.
I need to look what functionality "messageBack" type brings for us and if this would be a good solution we will take that into consideration.
