### ISSUE TITLE
Missing support for adaptiveCard/action type invoke in TeamsActivityHandler

### ISSUE THREAD

**Issue by ashwinvc** [microsoft/botbuilder-js#4259]
## Versions

SDK Version: **4.15.0**
NodeJS Version: **12.18.3**
Browser Version: **Chrome**
OS: **Windows 11**

## Describe the bug
While writing a JS Bot for Teams, we would be over-riding the `handleAdaptiveCardAction` method inside the `botbuilder/src/teamsActivityHandler.ts` file for `adaptiveCard/action` invokes. However this type of invoke is not being returned in the `onInvokeActivity` method of the same file and this is affecting the ability to handle such invokes in the latest bots being developed.

## Expected behavior
Would need the `adaptiveCard/action` type of invoke to return an invoke response using the above method.

## Screenshots
The following are the requested changes to help override the existing methods:
![Screenshot (170)](https://user-images.githubusercontent.com/26198609/171999429-9542a503-6e1a-4e75-8dff-23114b52bf6b.png)

**Comment by ashwinvc** [comment]
@stevkan @ramfattah can you pls help looking into this as it'll unblock our customers building JS bots

**Comment by ramfattah** [comment]
Hello @ashwinvc, we are investigating.

**Comment by ramfattah** [comment]
Hi @ashwinvc

looks like the `adaptiveCard/action` type of invoke is already checked in the base class [/activityHandler /](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-core/src/activityHandler.ts), in method [onInvokeActivity](https://github.com/microsoft/botbuilder-js/blob/e7d845eeacb32824af93652d07e46aabf30e800e/libraries/botbuilder-core/src/activityHandler.ts#L499).

https://github.com/microsoft/botbuilder-js/blob/e7d845eeacb32824af93652d07e46aabf30e800e/libraries/botbuilder-core/src/activityHandler.ts#L508

Perhaps the customer could use [ActivityHandler](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-core/src/activityHandler.ts) to return an invoke response; example using `ActivityHandler.onAdaptiveCardInvoke` ?

**Comment by ramfattah** [comment]
Update: In .NET SDK, the [handleAdaptiveCardAction](https://github.com/microsoft/botbuilder-js/blob/e7d845eeacb32824af93652d07e46aabf30e800e/libraries/botbuilder/src/teamsActivityHandler.ts#L523) method is not available in [TeamsActivityHandler](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs) class. Only in JS SDK.

**Comment by vcashwin** [comment]
Sure thing. Will work with the ActivityHandler methods. But wouldnt it be easier to add the changes mentioned in the description, since it enables for ease to work with! @ramfattah
