### ISSUE TITLE
Unable to install botbuilder-ai-orchestrator on my existing bot

### ISSUE THREAD

**Issue by vivekpassan** [microsoft/botbuilder-js#4280]
I have created a bot with azure bot framework composer and it seems to be working fine. Now I want to add other bots as skills in it and I am required to install the botbuilder-ai-orchestrator bit it is failing with the following error

`Command failed: npm install --loglevel=error --save botbuilder-ai-orchestrator npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead. npm ERR! code ERESOLVE npm ERR! ERESOLVE could not resolve npm ERR! npm ERR! While resolving: BotName@undefined npm ERR! Found: botbuilder-dialogs-declarative@4.15.0-preview npm ERR! node_modules/botbuilder-dialogs-declarative npm ERR! peer botbuilder-dialogs-declarative@"~4.15.0-preview" from @microsoft/bot-components-teams@1.2.1 npm ERR! node_modules/@microsoft/bot-components-teams npm ERR! @microsoft/bot-components-teams@"^1.2.1" from the root project npm ERR! botbuilder-dialogs-declarative@"4.15.0-preview" from botbuilder-ai@4.15.0 npm ERR! node_modules/botbuilder-ai npm ERR! botbuilder-ai@"4.15.0" from botbuilder-ai-luis@4.15.0-preview npm ERR! node_modules/botbuilder-ai-luis npm ERR! botbuilder-ai-luis@"4.15.0-preview" from botbuilder-dialogs-adaptive-runtime@4.15.0-preview npm ERR! node_modules/botbuilder-dialogs-adaptive-runtime npm ERR! botbuilder-dialogs-adaptive-runtime@"4.15.0-preview" from botbuilder-dialogs-adaptive-runtime-integration-express@4.15.0-preview npm ERR! node_modules/botbuilder-dialogs-adaptive-runtime-integration-express npm ERR! 1 more (the root project) npm ERR! botbuilder-ai@"4.15.0" from botbuilder-ai-qna@4.15.0-preview npm ERR! node_modules/botbuilder-ai-qna npm ERR! botbuilder-ai-qna@"4.15.0-preview" from botbuilder-dialogs-adaptive-runtime@4.15.0-preview npm ERR! node_modules/botbuilder-dialogs-adaptive-runtime npm ERR! botbuilder-dialogs-adaptive-runtime@"4.15.0-preview" from botbuilder-dialogs-adaptive-runtime-integration-express@4.15.0-preview npm ERR! node_modules/botbuilder-dialogs-adaptive-runtime-integration-express npm ERR! 1 more (the root project) npm ERR! 2 more (botbuilder-dialogs-adaptive, botbuilder-dialogs-adaptive-runtime) npm ERR! npm ERR! Could not resolve dependency: npm ERR! botbuilder-ai-orchestrator@"*" from the root project npm ERR! npm ERR! Conflicting peer dependency: botbuilder-dialogs-declarative@4.16.0-preview npm ERR! node_modules/botbuilder-dialogs-declarative npm ERR! peer botbuilder-dialogs-declarative@"4.16.0-preview" from botbuilder-ai-orchestrator@4.16.0 npm ERR! node_modules/botbuilder-ai-orchestrator npm ERR! botbuilder-ai-orchestrator@"*" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force, or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution. npm ERR! npm ERR! See C:\Users\username\AppData\Local\npm-cache\eresolve-report.txt for a full report. npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\username\AppData\Local\npm-cache\_logs\2022-07-14T10_23_29_714Z-debug-0.log`

Node version installed on my machine is 16.16.0 Below is the list of dependencies already insatlled "@microsoft/bot-components-teams": "^1.2.1", "botbuilder-ai-luis": "4.15.0-preview", "botbuilder-ai-qna": "4.15.0-preview", "botbuilder-dialogs-adaptive-runtime-integration-express": "4.15.0-preview", "cross-env": "latest"

**Comment by anishprasad01** [comment]
Hi @vivekpassan,

- What Composer version are you using?
- How are you installing the package? Through the UI package manager or some other method?
- Have you tried any other Node versions? We recommend 14.x LTS.

I am unable to reproduce this issue on Composer 2.1.2 with Node 14.20.0.

**Comment by anishprasad01** [comment]
Could you try removing the old packages and installing the new package in the terminal and let me know what happens?

**Comment by vivekpassan** [comment]
@anishprasad01  That did the trick. Thank you very much for your help.
