### ISSUE TITLE
CustomQuestionAnswering answers return empty metadata

### ISSUE THREAD

**Issue by jesus-diaz-rivero** [microsoft/botbuilder-js#4288]
## Versions
SDK: 4.16.0
NodeJS: 16.15.1
Browser: Chrome 103
OS: macOS 11.2.3

## Describe the bug
When using the CustomQuestionAnswering class to query against a Language project, the answers returned contain empty arrays in place of the actual metadata key/value pairs configured in Language Studio.

## To Reproduce
1. Go to Language Studio
2. Create a dummy project
3. Create random Question/Answer pairs with some metadata tags
4. Initialize an instance of the CustomQuestionAnswering class in a node project.
5. Call getAnswers or generateAnswers
6. Inspect result
7. Compare result vs. a call against the REST API as documented here (https://docs.microsoft.com/en-us/rest/api/cognitiveservices/questionanswering/question-answering/get-answers?tabs=HTTP#knowledgebaseanswercontext)

## Expected behavior
Output of the get/generateAnswer methods should include all metadata tags

## Screenshots
N/A

## Additional context
At a first glance it seems the issue is that, unlike the QnA Maker API, CustomQuestionAnswering stores its metadata in an object rather than an array. However, the function languageServiceUtils.formatQnaResult tries to map the metadata object from the response as if it were an array.

**Comment by anishprasad01** [comment]
Hi @jesus-diaz-rivero,

I'm able to reproduce this behavior. Looking into next steps.

**Comment by anishprasad01** [comment]
This can be reproduced with the following steps:

1. Create a Language resource
2. Add some question and answer pairs with metadata
3. Save and deploy the resource
4. Clone a fresh sample [12.customQABot](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/12.customQABot) and put the connection details for the language resource
5. In the sample, go to like 53 in `CustomQABot.js` and add `console.log(response);` to print out the response received from the Language service.
6. Run the bot and ask a question, then observe the result.
7. Optionally, also ask the question externally (for example by curl or Postman), and observe the metadata being received.

**Comment by johnataylor** [comment]
@jesus-diaz-rivero we have a fix in the works for this, thanks.
