### ISSUE TITLE
Tab response type (silentAuth) from bot is not supported

### ISSUE THREAD

**Issue by moira2k** [microsoft/botbuilder-js#4312]
## Versions
What package version of the SDK are you using: v4.17.0
What nodejs version are you using: v16.15.1
What browser version are you using: Version 104.0.1293.54 (Official build) (64-bit)
What os are you using: windows 10

## Describe the bug
I want to enable SSO for Adaptive Cards Tab following the SSO pattern for message extensions.

And the type of interface TabResponsePayload includes "silentAuth". refer to the url: https://github.com/microsoft/botbuilder-js/blob/main/libraries/botframework-schema/src/teams/index.ts#L1352
```
type?: "continue" | "auth" | "silentAuth"
```

In handleTeamsTabFetch, I return the tabResponse:
```
{
            tab: {
                type: "silentAuth",
                suggestedActions: {
                    actions: [
                        {
                            type: "openUrl",
                            value: signInLink,
                            title: "Sign in to this app"
                        }
                    ]
                }
            }
}
```
However, when I was debugging in Microsoft Teams, the error occurred(go to the Network Tab of DevTools): {"errorCode":1008,"message":"Error when processing invoke response: Tab response type (silentAuth) from bot is not supported"}
## Screenshots
![image](https://user-images.githubusercontent.com/74166031/185879071-edabdb0d-2a02-4a92-9ea8-6bcf08b69cf2.png)

**Comment by ramfattah** [comment]
Hi @moira2k, I'm investigating.

**Comment by ramfattah** [comment]
Hi @moira2k,

Looks like this is related to https://github.com/microsoft/botbuilder-js/issues/4296
This will probably be fixed in next release. PR has been merged. https://github.com/microsoft/botbuilder-js/pull/4305. 

In the meantime, @moira2k instead of SDK v4.17.0, could you please try [botbuilder 4.18](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder) from the [JS daily build feed](https://botbuilder.myget.org/gallery/botbuilder-v4-js-daily).

Thanks.

**Comment by moira2k** [comment]
I try [botbuilder 4.18](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder) but the same error occurs again.

**Comment by anishprasad01** [comment]
Hi @moira2k,

It looks like the [fix](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botframework-schema/src/teams/index.ts#L1352) in question is part of the `botframework-schema` package. If you solely updated the [botbuilder](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder) package, you would not have pulled this fix. Could you please try updating the `botframework-schema` package in your solution to the latest [botframework-schema daily](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botframework-schema) and try again?

**Comment by moira2k** [comment]
I think this is because Teams doesn't support it yet, not botbuilder.

**Comment by ramfattah** [comment]
Looks like this is a feature request for Teams.

**Comment by ramfattah** [comment]
@moira2k,

There is no SSO support for Adaptive Card Tabs. At the time when it was built message extensions did not support SSO.
Could you please raise a feature request here: [Microsoft Teams Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)
