### ISSUE TITLE
click to zoom into image not working in MS Teams - Hero Card Attachment - Bot Framework Composer/botbuilder-js

### ISSUE THREAD

**Issue by saskialorraine** [microsoft/botbuilder-js#4321]
**Background:**

We are adding images in Bot Framework Composer with Hero Cards, like so:

[HeroCard
  title = Example of a phishing email
  text = Here's an example of a phishing email!
  images = _link_
]

**Is your feature request related to a problem? Please describe.**

We are deploying our Bot to users in MS Teams. We add internal produced images where we show an E-Mail with Text. The text is a bit small. Instinctively, users would want to click on the image and wait for it to maximize/zoom in, but that doesn't work in the Bot. 
So user couldn't read the text in the image properly.

**Describe the solution you'd like**
Would be great if by default images would be able to maximize.

**Describe alternatives you've considered**

An alternative would be to adjust the size manually.

**Comment by tracyboehrer** [comment]
Bot Framework does not control Teams UI issues.  Redirect to Teams.
