### ISSUE TITLE
Explicit error logging inside `jwtTokenExtractor` in `botframework-connector`

### ISSUE THREAD

**Issue by itstaby** [microsoft/botbuilder-js#4324]
## Versions
What package version of the SDK are you using. 4.16 (`botframework-connector`)
What nodejs version are you using 14.17.1
What browser version are you using N/A
What os are you using MacOS Monterey 12.5.1

## Describe the bug
There is an explicit `console.error` statement [here](https://github.com/microsoft/botbuilder-js/blob/32c137952902402f9b78f27f33cdafa514e0452f/libraries/botframework-connector/src/auth/jwtTokenExtractor.ts#L106) in `jwtTokenExtractor`. This error is then thrown and handled by us, but the log entry is still made which results in noise in our logs as well as the possibility for triggering associated alarms. 

Why is this needed if the error is being thrown and will be logged if not handled by the caller?

## Expected behavior
Error is thrown, handling/logging is left to the caller.

**Comment by johnataylor** [comment]
@itstaby thanks for opening the issue, you make a good point, I think we can fix this
