### ISSUE TITLE
Response object misnamed in botFrameworkAdapter

### ISSUE THREAD

**Issue by bcomerford** [microsoft/botbuilder-js#4332]
## Versions
What package version of the SDK are you using.
4.1.6
What nodejs version are you using
v16
What browser version are you using
Chrome
What os are you using
Mac

## Describe the bug
Very little typo, response type in JSDoc was misnamed `req` in the `process` method of `botFrameworkAdapter`

## To Reproduce
1. Go to https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/botFrameworkAdapter.ts#L1879
2. You should see `req` in place of `res`

## Expected behavior
Should read `res`

**Comment by ramfattah** [comment]
Thanks for the PR @bcomerford.

**Comment by johnataylor** [comment]
thanks for the PR, looks great
