### ISSUE TITLE
Conversation state was not saved properly on Blob Storage side - skillDialog.ts

### ISSUE THREAD

**Issue by ramfattah** [microsoft/botbuilder-js#4345]
Long short story, customer is owning a Root Bot (built with Composer 2.X) and a Skill bot (built with Bot Framework SDK).

 

It looks like that under certain circumstances, the root bot is throwing an exception that it could NOT save the state of the conversation once it tries to call the skill bot, as seen here:
![image](https://user-images.githubusercontent.com/38049078/196222973-c57d0763-8e5b-4ede-beb4-f0a8b3091d3c.png)

Source code of skillDialog.ts that is complaining from our SDK: [botbuilder-js/skillDialog.ts at main · microsoft/botbuilder-js (github.com)](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-dialogs/src/skillDialog.ts)

Going forward, they are not using the in-memory storage to store the conversation state, but a Blob Storage.

What we observed on the Blob Storage side is that, the blob file created for the conversation when the bot crashed, contains nothing but:

``` js
{"_lastAccess":"2022-10-13T09:25:45.390Z","DialogStateProperty":{"dialogStack":[]}} \
```

**We can say for sure that no conversation state has been saved.**

 

A “healthy” blob file that contains a conversation state looks like this:

` ":"2022-10-13T13:21:28.181Z","DialogStateProperty":{"dialogStack":[{"id":"omni-root","state":{"eventCounter":22,"_adaptive":{"actions":[{"dialogId":"ActionScope[If[=conversation.idkCount==0|SendActivity[${SendAc...-1499581726]","dialogStack":[{"id":"ActionScope[If[=conversation.idkCount==0|SendActivity[${SendAc...-1499581726]","state":{"offset":0}},{"id":"FalseIf[=conversation.idkCount==0|SendActivity[${SendActivity_ut1ylh()}],SetProperty...]","state":{"offset":0}},{"id":"TrueIf[=conversation.idkCount==1|SendActivity[${SendActivity_cllLm8()}],BeginSkill[...]","state":{"offset":4}},{"id":"TrueIf[=dialog.hoursOfOperationStatus==\"open\"|ChoiceInput[ActivityTemplate(${ChoiceInput_Prompt_...]","state":{"offset":1}},{"id":"TrueIf[=$agentPrompt==\"Yes\"|BeginDialog[[object Object]]]","state":{"offset":0}},{"id":"BeginDialog[[object Object]]","state":{}},{"id":"LiveAgent","state":{"eventCounter":18,"_adaptive":{"actions":[{"dialogId":"ActionScope[SendActivity[${SendActivity_WHmgOi()}],TextInput[A...1339857160]","dialogStack":[{"id":"ActionScope[SendActivity[${SendActivity_WHmgOi()}],TextInput[A...1339857160]","state":{"offset":4}},{"id":"BeginSkill['=settings.skill['liveAgentSkillBot'].msAppId','${BeginSkill_Activity_2H5zA0()...']","state":{"BeginSkill.dialogOptionsData":{"skill":{"appId":"17d5d13a-ba2e-4c8c-8184-85317b82850f","id":"17d5d13a-ba2e-4c8c-8184-85317b82850f","skillEndpoint":"[https://stage.ava.optum.com/agent-escalation-skill-app-stage-v1/messages"},"botId":"61a569cf-09a9-4003-8b6d-fafa7150f552","skillHostEndpoint":"https://stage.ava.optum.com/omni-root-app-stage-v1/skills","conversationIdFactory":{"storage":{"name":"BlobsStorage"}},"skillClient":{"credentialProvider":{"appId":"61a569cf-09a9-4003-8b6d-fafa7150f552","appPassword":""},"conversationIdFactory":{"storage":{"name":"BlobsStorage"}}},"conversationState":{"storage":{"name":"BlobsStorage"},"namespace":""}},"SkillDialog.skillConversationId":"65216d34-5c07-4b3c-940e-1c05d7d820bd"}}]}]},"lastIntent":"None","firstName":"asfa","lastName":"sadf","userEmail":"asdf","Transcript":"Aditya:](https://stage.ava.optum.com/agent-escalation-skill-app-stage-v1/messages%22%7D,%22botId%22:%2261a569cf-09a9-4003-8b6d-fafa7150f552%22,%22skillHostEndpoint%22:%22https:/stage.ava.optum.com/omni-root-app-stage-v1/skills%22,%22conversationIdFactory%22:%7B%22storage%22:%7B%22name%22:%22BlobsStorage%22%7D%7D,%22skillClient%22:%7B%22credentialProvider%22:%7B%22appId%22:%2261a569cf-09a9-4003-8b6d-fafa7150f552%22,%22appPassword%22:%22HHQ8Q~Xm~_y4glKxX1.-2WTULwqphCDGxSyCncCe%22%7D,%22conversationIdFactory%22:%7B%22storage%22:%7B%22name%22:%22BlobsStorage%22%7D%7D%7D,%22conversationState%22:%7B%22storage%22:%7B%22name%22:%22BlobsStorage%22%7D,%22namespace%22:%22%22%7D%7D,%22SkillDialog.skillConversationId%22:%2265216d34-5c07-4b3c-940e-1c05d7d820bd%22%7D%7D%5d%7D%5d%7D,%22lastIntent%22:%22None%22,%22firstName%22:%22asfa%22,%22lastName%22:%22sadf%22,%22userEmail%22:%22asdf%22,%22Transcript%22:%22Aditya:) asfas\r\nomni-root-bot-stage-v1: Sorry, I didn't get that.\r\nAditya: asdfadsf\r\nomni-root-bot-stage-v1: Sorry, I still didn't get that.\r\nomni-root-bot-stage-v1: Do you want to connect with a live agent instead?\r\nAditya: Yes\r\nomni-root-bot-stage-v1: I need some information before connecting you to the live agent"},"version":"-1988760274"}]}]},"lastIntent":"Help","lastEvent":"None","skillResult":"{\"hoursOfOperationStatus\":\"open\",\"hoursOfOperation\":\"Sun-Sat:12:00AM-11:59PM\",\"longestWaitTime\":0,\"chatsInQueue\":0}","JSONResult":{"hoursOfOperationStatus":"open","hoursOfOperation":"Sun-Sat:12:00AM-11:59PM","longestWaitTime":0,"chatsInQueue":0},"hoursOfOperationStatus":"open","hoursOfOperation":"Sun-Sat:12:00AM-11:59PM","chatsInQueue":"0","longestWaitTime":"0","agentPrompt":"Yes"},"version":"-1693064354"}]},"idkCount":1} `

Some conclusions:

* It looks to me that the conversation state was not saved for one or more particular conversations.
* When this happened, the Bot Framework SDK has thrown some errors when it tried to save the conversation state.  Which makes sense, since the blob file we found is indeed “empty”, indicating that nothing was saved.

The real question is, what are the possible reasons why a conversation state could not have been saved on the Blob side?
We tried to find the request sent to the Blob storage, but we couldn't find one in App Insights.
Maybe that request was not even issued for some reason?
In parallel, we do find the conversation state file created on the Blob side, so an interaction between the bot and the Blob took place... but not as expected in the end.

ICM 341513077

**Comment by ceciliaavila** [comment]
Hi @ramfattah, we are trying to reproduce this issue but we are not sure how to configure the blob storage in a composer bot. Do you have the bot's configuration?
And just to confirm, the customer is using a Node composer root and a JS skill bot?
Thanks!

**Comment by ramfattah** [comment]
Thanks @ceciliaavila.

Looks like the customer is not able to reproduce this issue anymore.

I believe they manually defined a "BlobStorage" object inside their Composer bot's settings.
[botbuilder-dotnet/ServiceFactory.cs at 402bc02b4cbbd2f4ec359134640e99211367e4a5 · microsoft/botbuilder-dotnet (github.com)](https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/ServiceFactory.cs)

[botbuilder-dotnet/BlobsStorageSettings.cs at 402bc02b4cbbd2f4ec359134640e99211367e4a5 · microsoft/botbuilder-dotnet (github.com)](https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Settings/BlobsStorageSettings.cs)

**Comment by ramfattah** [comment]
Closing this for now.

**Comment by ceciliaavila** [comment]
Thanks, @ramfattah. 
We were able to have a .NET composer root bot saving the transcripts in a blob container by adding the settings you mentioned. However, we couldn't find a way to save the conversation state.
We'll drop this for now, then.
Thanks!
