### ISSUE TITLE
adapter.useNamedPipe not working with the new CloudAdapter (Node.js SDK)

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-js#4371]
Our docs are only teaching us how to use the adapter.useNamedPipe to inject named pipes to enable DL ASE in node.js SDK- [Configure Node.js bots for Direct Line App Service extension in the Bot Framework SDK - Bot Service | Microsoft Learn](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-node-bot?view=azure-bot-service-4.0)

However, that method is no longer working with the new CloudAdapter introduced with BotBuidler V4.15.

1. As such, what is the new method compatible with the new CloudAdapter?
2. Can you provide a full sample as well please (with all the parameters required)?
3. Can we update the documentation as well, to make customers aware that the useNamedPipe method is working only with BotFrameworkAdapter, and also introduce a new sample specific to CloudAdapter?

IcM link: https://portal.microsofticm.com/imp/v3/incidents/details/347795623/home

**Comment by ceciliaavila** [comment]
Closing as the PR with the sample was merged and the docs were updated.
