### ISSUE TITLE
Method (TurnContext) context.updateActivity is not working properly

### ISSUE THREAD

**Issue by husniddin96** [microsoft/botbuilder-js#4396]
## Versions
SDK: botbuilder@4.16.0
NodeJS:  v14.21.1
OS: MacOS Monterey

## Describe the bug
Method `(TurnContext) context.updateActivity` is not working properly. 

## To Reproduce
I've send a message using Teams-SDK and got activityId and conversationId
```json
{
    "id": "a773b6c8-974d-44b4-826d-68d96755fcea",
    "conversation": {
        "id": "a:1PLNtByhl0fgu_k9hiMAWJwkOxmPt_DRuDTlRPbb62G87TrLGKFi92grig_sL0sHhAVr1OZjcO9Ij7YhEKAeBgvOTwdKCNjaTjv8JJX-oAopsrvvWxSptjDEBeGhPAzIH"
    }
}
```

I tried to update this activity using `context.updateActivity` method.
I created a message activity with payload, then set message.id to the existing activityId.
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/23168303/209310400-eac2fb8e-d56d-487c-b9ae-ce5d0f9f5c3e.png">

When I called this method with a new message activity, it threw an error:
```json
{
    "error": "Invalid activity ID 1:14V-AqmDStlQxcTuiOQ27qP6ve1JumC1vAjiLvYOpLNLA0LhO1T4Q_kxmr8fMe-QI"
}
```

## Expected behavior
Should update existing activity

**Comment by ramfattah** [comment]
Thanks @husniddin96, we are investigating.

**Comment by erquirogasw** [comment]
Hi @ramfattah, we can help you reviewing this issue. We were able to reproduce it. Let us know if you prefer something else.

**Comment by ramfattah** [comment]
Hi @erquirogasw, 

That would be great! Thank you so much for helping out.
Please let me know in case you have any questions or if you need me to take further actions.

Also, shall I add you to the assignees list of this issue?

**Comment by erquirogasw** [comment]
@ramfattah, I just assigned the issue. Thanks.

**Comment by erquirogasw** [comment]
Hi @husniddin96, we tested the _updateActivity_ method using the following [sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation/nodejs), and worked as expected when passing the correct _activityID_.
We suspect the _activityID_ you are using is not the right one, the format is off.
If you wish, you can send us a sample with your code so we can verify this.

**Comment by husniddin96** [comment]
Hi @erquirogasw, you're right I was using incorrect activityId. It should be something like "1673069928".
It worked as expected when I passed numeric id.
Thanks all for your help!)

**Comment by ramfattah** [comment]
Thanks @erquirogasw  😊
