### ISSUE TITLE
Can't create a bot from templates using node.js 18.12.1

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-js#4401]
Originally opened as https://github.com/MicrosoftDocs/bot-docs/issues/2253 by @abhisheke1mishra

## Versions
What package version of the SDK are you using: 4.17.1 (presumably) 
What nodejs version are you using: 18.12.1 (npm 9.2.0)
What browser version are you using: unknown
What os are you using: unknown

## Describe the bug
> The steps to [create a basic bot](https://learn.microsoft.com/azure/bot-service/bot-service-quickstart-create-bot?tabs=javascript%2Cvs) are not working with latest node.js version 18.12.1 and npm 9.2.0 version.
During npm start getting error for restify - "TypeError: Cannot set property closed of # which has only a getter"

## To Reproduce
1. Follow steps in [create a basic bot](https://learn.microsoft.com/azure/bot-service/bot-service-quickstart-create-bot?tabs=javascript%2Cvs).
1. Error: `npm start` generates a restify error.

## Expected behavior
The current bot templates should work with the current version of node.js.

**Comment by anishprasad01** [comment]
@JonathanFingold,

This is a known restify issue. restify versions <10.0.0 are incompatible with Node 18.x. I've opened a [PR](https://github.com/microsoft/botbuilder-js/pull/4392) to update the Yeoman templates, but in the meantime, the customer can resolve the issue by manually updating restify.
