### ISSUE TITLE
CloudAdapter don't work with Teams SSO

### ISSUE THREAD

**Issue by goetzal** [microsoft/botbuilder-js#4408]
## Versions
What package version of the SDK are you using. 4.19.0
What nodejs version are you using: 16.19.0
What browser version are you using: Teams Windows Client
What os are you using. Windows 10

## Describe the bug
Teams SSO doesn't work with the CloudAdapter class. I spent a lot of time with debugging and checking my configuration.
I followed the instructions at this repo: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/js

After sending the OAuthPromt Dialog, I get an error message "ExtendedUserTokenProvider".
If I use the deprecated BotFrameworkAdapter everything works as expected.

This happens because the CloudAdapter doesn't implement the "exchangeToken" method (i guess).
So I'm not sure whether the samples or the lib is not as expected.

## To Reproduce
Use the code and instructions from: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/js

## Expected behavior
Teams SSO with the CloudAdapter class.

**Comment by jaytees** [comment]
interested in the answer to this issue as well

**Comment by erquirogasw** [comment]
Hi @johnataylor. We were able to reproduce this issue using the [bot-conversation-sso-quickstart](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/js) sample.
If there's no problem, we could continue reviewing it.

**Comment by ramfattah** [comment]
Thanks @erquirogasw.

Can I assign this issue to you?

**Comment by erquirogasw** [comment]
@ramfattah sure. We already have the fix and we are finishing adding new unit tests.
