### ISSUE TITLE
[Documentation]: Write directly to storage - Using blob storage - Incorrect JS examples

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/botbuilder-js#4411]
The JavaScript guidance given in the [Using Blob storage](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript#using-blob-storage) section is incorrect and has a number of issues.

In the [Installing Blob storage packages](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=javascript#installing-blob-storage-packages) section, the reader is asked to install the `botbuilder-azure-blobs` package, however the text and further examples on this page all refer to implementing storage using the `botbuilder-azure` package.

As the `BlobStorage` class is deprecated in the `botbuilder-azure` package, and the `BlobsStorage` class is suggested in the deprecation message which is in the `botbuilder-azure-blobs` package, this page requires updating to use the new approach.

**Comment by anishprasad01** [comment]
Hi @garrytrinder,

Thank you for the report. I'll take a look and get the ball rolling.

**Comment by anishprasad01** [comment]
@garrytrinder,

I've confirmed the issues with the document and identified the correct steps for the `botbuilder-azure-blobs` package. I've also opened an [issue](https://github.com/MicrosoftDocs/bot-docs/issues/2261) on the bot-docs repo with the correct steps and will see that those get updated soon.

Thanks again for reporting this.

**Comment by JonathanFingold** [comment]
Fixes merged and should be visible in the docs later today.
