### ISSUE TITLE
teamsTokenExchangeMiddleware

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-js#4426]
## Describe the bug
teamsTokenExchangeMiddleware should use UserTokenAccess.exchangeToken (to support CloudAdapter)

## To Reproduce
test teamsTokenExchangeMiddleware with cloud adapter

## Additional context
See OAuthPrompt

**Comment by ceciliaavila** [comment]
Hi @EricDahlvang, this was addressed in #4408. This issue can be closed.
