### ISSUE TITLE
Runtime settings issue Builder Version 4.17.0

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-js#4428]
[PROBLEM DESCRIPTION] –

Some of the values are not getting read with later BotBuilder versions (4.17.0-preview, 4.19.0-preview), but same works with 4.13.4-preview)

[TROUBLESHOOTING STEPS]

Customer has the Bot Builder Version as 4.13.4-Preview, where they are using custom action to read the values out of Appsetting.json, which works fine.

When the BotBuilder version is updated as 4.17.0-preview, only few values are read not all.

These are botbuilder versions that Im using the the node project (version which is not able to fetch the connectionString)

![image](https://user-images.githubusercontent.com/1024902/217867257-409bf686-80ee-439b-87c4-c96f589bde05.png)
 

As you can see, when I try to print settings.runtimesettings, these are the information that is being printed.

 
![image](https://user-images.githubusercontent.com/1024902/217867169-38615631-1306-4b7d-9f5c-2b916e2075ea.png)

But when I try to do the same while using 4.13.4-preview, I can see all the values are logging

![image](https://user-images.githubusercontent.com/1024902/217867439-f58a0449-dd0a-41bc-819a-1f74a0a27498.png)

**Comment by tracyboehrer** [comment]
@ceciliaavila Can you research this?  I don't immediately see a settings difference between 4.13 and 4.17 (or 4.19 for that matter).  It does appear that there was a change to settings processing in 4.14 though.

**Comment by tracyboehrer** [comment]
Internal:  ICM issue https://portal.microsofticm.com/imp/v3/incidents/details/364520101/home

**Comment by ceciliaavila** [comment]
Hi @tracyboehrer, we'll start reviewing this today.

**Comment by sw-joelmut** [comment]
Hi @tracyboehrer, we reviewed this issue and noticed that sensitive properties from the `settings` are blocked at runtime. Additionally, we found that [this implementation](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-dialogs/src/memory/scopes/settingsMemoryScope.ts#L44) was added by the PR # 3740 (~2 years ago).
As a workaround, the app settings can be retrieved within a Composer Custom Action from the `BotComponent.configureServices` method like the following:
![image](https://user-images.githubusercontent.com/62260472/218547287-50ac632e-3242-4e92-a646-9d4fa7e53a0b.png)

**Comment by ceciliaavila** [comment]
Hi @tracyboehrer, we think this issue can be closed as the reported behavior is by design and we provided a workaround.
