### ISSUE TITLE
Linux Build State Currently Failing, Possibly Related To Bcrpyt?

### ISSUE THREAD

**Issue by Hudson-Hughes** [microsoft/botbuilder-js#4434]
## Versions
SDK Version 4.19.1
Node Version 16
Linux

## Describe the bug
My team is using Node 16 on Linux Azure Web Apps and had trouble with the new bcrpyt library. I figured out that the error (invalid elf header) was because our build pipeline is on windows, but the Web App is on Linux and bcrypt uses native libraries. Can we have an option or branch that allows us to use "non-native" cryptography call, such as from bcryptjs. This will keep us from having to make drastic changes to our pipeline and web apps. 
In exploring this I also noticed the Linux Build is failing.

**Comment by anishprasad01** [comment]
Hi @Hudson-Hughes,

The build failures on main appear to be related to a bot publishing issue with the tests, and not a direct code defect. Just to verify, I built the latest version of main on Linux with Node 16 and it was successful.

Regarding your question about alternative branches, that would be a feature request, and it will be passed on for further consideration.

**Comment by LeeParrishMSFT** [comment]
I spoke to Hudson and they are going to align their build servers to the platforms that they are deploying to, i.e. using windows for windows targeted builds, and Linux for Linux targeted builds. This should mitigate the issue.
