### ISSUE TITLE
onInstallationUpdateRemove activity handler is not firing

### ISSUE THREAD

**Issue by rastym** [microsoft/botbuilder-js#4435]
## Versions
 botbuilder: "4.18.0",
nodejs: v14.17.3

## Describe the bug
My team is working on the tabs application, and this application using bot as well. After the user has removed our app manually, **onInstallationUpdateRemove** handler is not firing, but at the same time **onInstallationUpdate** handler working as expected. There is the code which is responsible for logging (sceenshot 3), and the resulting output in the AWS console (screenshot 4). Please let me know if you need some extra info. 

## To Reproduce
1. Inside of the Microsft Teams go to Apps -> Manage your apps (screenshot 1)
2. Press on the trash icon and confirm removing (screenshot 2)

## Expected behavior
onInstallationUpdateRemove method must be triggered once the user has uninstalled the application.

## Screenshots
![image](https://user-images.githubusercontent.com/33793538/219642540-89bb0c4a-c2cd-41b2-9a57-706569a6eae6.png)
![image](https://user-images.githubusercontent.com/33793538/219642914-1d3be1bc-5ba7-41c4-8f2d-198b22666c18.png)
![image](https://user-images.githubusercontent.com/33793538/219646193-57f7a6d2-1209-4295-871d-158734589bca.png)
![image](https://user-images.githubusercontent.com/33793538/219645985-726399a5-2143-457e-a1aa-af50493cd8d0.png)

**Comment by stevkan** [comment]
@rastym - I'll be taking a look at this and will attempt a repro of the issue. In the meantime, can you check to see if the issue occurs when using either v4.17.1 or v4.19.1 of the SDK? I will test the same.

Also, did this previously work and now has stopped? Or is this a new implementation that has never worked when using?

**Comment by rastym** [comment]
@stevkan Sorry for delay, I can confirm that immediately after updating the sdk to version 4.19.1 the event fires as expected, so the issue can be closed.
