### ISSUE TITLE
`OAuthPrompt` not successfully calling back on Android

### ISSUE THREAD

**Issue by isweetland** [microsoft/botbuilder-js#4438]
## Versions
What package version of the SDK are you using: `4.19.1`
What nodejs version are you using: `18.6`
What os are you using: `Android 13`

## Describe the bug

On Android: `OAuthPrompt()` does not trigger next step in `WaterfallDialog` after `PostSigninCallback`, we are also unable to get token from Microsoft. 

On Web/Desktop/IOS: Everything works as expected.

## To Reproduce

On Android:

1. Create a `WaterfallDialog` with an `OAuthPrompt` and some arbitrary callback step
2. Trigger the `WaterfallDialog` with some login command  
3. Authenticate with OAuth provider
5. Notice second step was not triggered
6. Fail to get user token from `CloudAdapter`

## Expected behavior

We expect that the second step is fired after successfully authenticating with OAuth Provider

## Additional context

This seems to be very similar to the issue described here: https://learn.microsoft.com/en-us/answers/questions/837781/in-mobile-user-is-not-able-to-login-in-the-tab

**Comment by ramfattah** [comment]
Thanks for reporting this issue @isweetland,

I've notified the Microsoft "Teams" team about this issue. Will report back as soon as there are updates.
Thanks.

**Comment by jineshjin** [comment]
Hi @ramfattah, do we have any updates on this? It's affecting us as well.

**Comment by jineshjin** [comment]
Hi @ramfattah, can we have any input on this? It's been opened since 18th Feb, do you see this will be addressed in near future? Or can you please update when we are planning to fix this? 
Thanks!

**Comment by ramfattah** [comment]
This is Teams issue.

Continuing this thread in Microsoft-Teams-Samples repository:
https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/902
