### ISSUE TITLE
InstallationUpdate event is not firing when app was removed from the organization

### ISSUE THREAD

**Issue by rastym** [microsoft/botbuilder-js#4443]
## Versions
botbuilder: 4.19.1
nodejs: 14.17.3

## Describe the bug
Hello, we're want to clear some data in an external cloud service, once the application was uninstalled for entire organization.We follow the steps which is described in the reproduce section, and we have the next result: 
1.Application was successfully uninstalled for the users in this specific organization.
2.InstallationUpdate event was not fired for the users.

## To Reproduce
1. Go to [admin.teams.microsoft.com](https://admin.teams.microsoft.com/policies/manage-apps/)
2. Click on 'Manage Apps'
3. Select application
4. Click on the 3 dots on the top right, and press 'delete' button. 
(Check first attached screenshot)

## Expected behavior
Event must be fired
## Screenshots
![image](https://user-images.githubusercontent.com/33793538/225902057-27ae8086-c343-4572-b35a-7cf2b597f772.png)

**Comment by ramfattah** [comment]
Thanks @rastym, I'm investigating.

**Comment by ramfattah** [comment]
Hi @rastym,

This is by design.

According to Microsoft Teams "[Installation update event](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#installation-update-event:~:text=to%20remove.-,Note,-When%20you%20upgrade)" documentation:
> When you upgrade an application, the bot receives the installationUpdate event only to add or remove a bot from the manifest. For all other cases, the installationUpdate event isn't triggered.

**Comment by rastym** [comment]
Hello, @ramfattah, thanks a lot.
