### ISSUE TITLE
Azure Blob Storage should support Identity authentication

### ISSUE THREAD

**Issue by XVincentX** [microsoft/botbuilder-js#4446]
Azure Blob Storage asks for a container name as well as a connection string, implying that the only way to use it is through a shared access key.

Azure Blob Storage should support Managed and System Identities to avoid having to put secrets here and there

**Comment by ceciliaavila** [comment]
> Sweet. Has this been released?

Hi @XVincentX, these changes are included in the preview version [4.21.0-dev.20230612.5ee34c0](https://www.npmjs.com/package/botbuilder/v/4.21.0-dev.20230612.5ee34c0).

**Comment by ceciliaavila** [comment]
> I downloaded that version but it sounds like the change was not included. I still can see the old constructor

The new parameters (URL and credential) were added as optional in the old constructor.
![image](https://github.com/microsoft/botbuilder-js/assets/44245136/d049506b-d653-4d97-ab05-5222695dd9e0)

**Comment by BeigeBadger** [comment]
What stable version is this targeted to be released in v4.21.0? Is there an estimated release date for this?
