### ISSUE TITLE
ClientOptions.AgentSettings are not being used in api call TeamsInfo.sendMessageToTeamsChannel

### ISSUE THREAD

**Issue by ChupaCabre** [microsoft/botbuilder-js#4469]
## Versions
What package version of the SDK are you using: 4.19.3
What nodejs version are you using v14.19.1
What browser version are you using n/a
What os are you using Mac

## Describe the bug
Give a clear and concise description of what the bug is.
I'm running the proactive message node sample: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-initiate-thread-in-channel/nodejs and it works fine. However when I pass in a proxy agent, the proxy is not used in the api call. The message still arrives in the Teams channel, but the proxy logs show no traffic has passed through it. Here's how the proxy agent is passed into the adapter:
```
const clientOptions = {};
const proxy = 'http://user:auth@localhost:9191';
const http = new hpagent.HttpProxyAgent({ proxy });
const https = new hpagent.HttpsProxyAgent({ proxy });
clientOptions.agentSettings = {
    http,
    https
};

const botFrameworkAuthentication = new ConfigurationBotFrameworkAuthentication({
    MicrosoftAppId: process.env.MicrosoftAppId,
    MicrosoftAppPassword: process.env.MicrosoftAppPassword,
    MicrosoftAppTenantId: ''
}, undefined, undefined, undefined, clientOptions);
const adapter = new CloudAdapter(botFrameworkAuthentication);
```
I've used hpagent for a Slack bot and it successfully sends the traffic through the proxy. Not sure what's going wrong here. I tried tracing through the code but it's a bit tricky to find out which service client is being used to make the api call. Please let me know if I need to pass in the http agent in a different way. I've also tried passing in `proxySettings` in the same way but no luck.
## To Reproduce
1. Follow instructions for running the bot sample: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples
2. Get a forward proxy running. I used this one: https://github.com/berstend/straightforward
3. Pass proxy agent into client options as shown above.
4. Run the sample again and see that no traffic has passed through the proxy.

## Expected behavior
Teams api call goes through proxy.

**Comment by anishprasad01** [comment]
Hi @ChupaCabre,

`ConfigurationBotFrameworkAuthentication` does not take an hpagent, it takes a `ConnectorClientOptions`. When instantiating this object, you will need to pass in the baseUrl. I'm not entirely sure is this is a supported scenario, however.
