### ISSUE TITLE
Migrate off `@azrue/ms-rest-js`

### ISSUE THREAD

**Issue by jeremymeng** [microsoft/botbuilder-js#4470]
### Use this [query](https://github.com/Microsoft/botbuilder-js/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
It looks that old version of autorest typescript generator was used to generate code that depends on `@azure/ms-rest-js`.  Please consider moving to use latest autorest.typescript code generator as `@azure/ms-rest-js` is no longer actively maintained.  Free free to reach out if you have any questions.

**Describe the solution you'd like**
use the latest autorest.typescript to re-generate code. adjust to use newer `@azure/core-client`, `@azure/core-rest-pipeline`, `@azure/core-auth`, `@azure/identity` if needed.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tracyboehrer** [comment]
@ceciliaavila Lets chat to talk about this.

**Comment by jeremymeng** [comment]
@tracyboehrer thank you for moving off ms-rest-js!  However, we are planning to deprecate `@azure/core-http` soon too in favor of the newer and better `@azure/core-client` and `@azure/core-rest-pipeline` packages.

**Comment by jeremymeng** [comment]
We also deprecated `@azure/core-http`.  You should consider moving to  @azure/core-rest-pipeline.
