### ISSUE TITLE
Always ConversationNotFound 404, even after welcome proactive message

### ISSUE THREAD

**Issue by Steffi3rd** [microsoft/botbuilder-js#4479]
Hi !

Since this week-end, 
**Our bot always returns "ConversationNotFound" 404**. We don't understand why. 
The user has the conversation and the user exists in storage. 

If I remove the user from the storage, I have the error "Not found" (this is normal).
So : 
- the user exists in storage 
- but conversation is not found whereas 
- bot has successfully send the proactive message (Welcome...)

How to fix that?

***POSTMAN***

endpoint: 
```
https://____.azurewebsites.net/api/notifications
```
payload: 
```
{
	"users": [{
                "id": "_0_c_b_3-_a_8-4_4_-9_b_-_3_c_1_a_c_0"
         }]
}
```

***CODE***

```
const { bot } = require("../internal/initialize");
const { AdaptiveCards } = require("@microsoft/adaptivecards-tools");
const { GetDeepLinkTabStatic } = require("../helpers/DeepLinkTabHelper.js");
const notificationTemplate = require("../adaptiveCards/notification-default.json");
const t = require("../internal/language.js");

module.exports = async ({ body }, res) => {
  for await (const user of body.users) {
    try {
      const teamsMember = await bot.notification.findMember(async (member) => {
        return member.account.aadObjectId === user.id;
      });

      if (!teamsMember) {
        notFoundUsers.push(user.id);
        continue;
      }

      const message = {
        title: "Title",
        description: "Description",
      };

      try {
        await teamsMember.sendAdaptiveCard(
          AdaptiveCards.declare(notificationTemplate).render(message),
          async (_context, error) => {
            throw new Error(error);
          }
        );
      } catch (error) {
        console.log("sendAdaptiveCard >>>", error);
        throw new Error("sendAdaptiveCard : " + error);
      }
    } catch (error) {
      console.log(`For ${user.id} : catch error >>>>>`, error);
      continue;
    }
  }

  return res.send(204);
};

```

**Comment by ramfattah** [comment]
Thanks @Steffi3rd, I'm investigating.

**Comment by ramfattah** [comment]
Hi @Steffi3rd, could you please provide the [steps to reproduce](https://github.com/microsoft/botbuilder-js/blob/main/.github/ISSUE_TEMPLATE/javascript-sdk-bug-report.md#to-reproduce) this issue?

**Comment by Steffi3rd** [comment]
I found an alternative here : https://github.com/OfficeDev/TeamsFx/issues/8759#issuecomment-1561159073

**Comment by ramfattah** [comment]
Hi @Steffi3rd, 

Is this an issue with Bot Framework SDK or TeamsFx SDK?

**Comment by Steffi3rd** [comment]
@ramfattah The issue is : `bot.notification.findMember(...)`

**Comment by ramfattah** [comment]
@Steffi3rd, it seems that the method [findMember(...)](https://github.com/OfficeDev/TeamsFx/blob/b3cdd7bd554511551f07b714ea263146e3c609c3/packages/sdk/src/conversation/notification.ts#L568-L583) is a component of the TeamsFX SDK, not the Bot Framework SDK.

Please raise an issue in the [TeamsFx](https://github.com/OfficeDev/TeamsFx) repository.
Thank you.
