### ISSUE TITLE
port: Allow sending GET requests with a body

### ISSUE THREAD

**Issue by ceciliaavila** [microsoft/botbuilder-js#4480]
The changes in [Allow sending GET requests with a body](https://github.com/microsoft/botbuilder-dotnet/pull/6633) may need to be ported to maintain parity with microsoft/botbuilder-dotnet.

<blockquote>
#minor

## Description
This PR allows sending GET requests by adding a body to the request's content.

Composer related issue: [#9158](https://github.com/microsoft/BotFramework-Composer/issues/9158).

## Specific Changes
  - Modified the switch clause to move the GET request case, to allow the body to be added to the request content.
 
## Testing
The following image shows the GET request sent with a body in the content.
![image](https://github.com/southworks/botbuilder-dotnet/assets/122501764/47e1d515-1819-4473-9f2a-0c787522a7e1)
</blockquote>

**Comment by erquirogasw** [comment]
These changes can't be ported because [node-fetch](https://github.com/node-fetch/node-fetch) doesn't support GET requests with body.
Related issue: https://github.com/node-fetch/node-fetch/issues/1728.
Closing issue.
