### ISSUE TITLE
Breaking change in LUIS recognizer in V4.20

### ISSUE THREAD

**Issue by guy-microsoft** [microsoft/botbuilder-js#4498]
## Versions
What package version of the SDK are you using - botbuilder-ai & core
What nodejs version are you using - 4.20.0

## Describe the bug
In V4.19.0, when we used `LuisRecognier` and called the `recognize()` function, we eventually arrived to this function:
`async recognizeInternal(contextOrUtterance: DialogContext | TurnContext | string): Promise<RecognizerResult>`
and when code evaluated `contextOrUtterance instanceof TurnContext` it was true.
However, in V4.20.0 `contextOrUtterance instanceof TurnContext` is evaluated to false, which results in context equals to undefined.

## Expected behavior
Behavior should not break between those versions.

**Comment by guy-microsoft** [comment]
Any updates about that?
Version 4.19 has a vulnerability in one of its dependencies (fast-xml-parser).

**Comment by ceciliaavila** [comment]
Hi @guy-microsoft, we tried reproducing this issue but didn't get the error you mentioned.
When we call the _LuisRecognizer.recognize()_ function with an instance of _TurnContext_ or _DialogContext_, it works as expected.
Could you give us more details on the parameters you pass to the function?

**Comment by guy-microsoft** [comment]
I'm sorry @ceciliaavila, there was a mismatch of versions in our side that caused the issue. Closing this thread.
