### ISSUE TITLE
Dependency package @azure/ms-rest-js has a new version available

### ISSUE THREAD

**Issue by aftabmustafa** [microsoft/botbuilder-js#4504]
### Use this [query](https://github.com/Microsoft/botbuilder-js/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
I am using botbuilder-ai@4.20.0 which has a dependency on @azure/ms-rest-js(v2.6.6). This version of azure/ms-rest-js is using tough-cookie package which has been identified as a critical vulnerability. ms-rest-js has removed this dependency in their latest version.

**Describe the solution you'd like**
Please use the latest version of azure/ms-rest-js

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tracyboehrer** [comment]
Should be resolved by #4470.  This will be in the next release.
