### ISSUE TITLE
[Bug]: 401 Unauthorized error while consuming an uploaded text file

### ISSUE THREAD

**Issue by joe733** [microsoft/botbuilder-js#4505]
## Versions

```console
$ node --version
v18.16.1
$ npm ls   
epitoma@1.0.0 /home/us-er/TeamsApp/epitoma
├── @types/node@14.18.53
├── @types/restify@8.5.7
├── axios@1.4.0
├── botbuilder@4.20.0
├── env-cmd@10.1.0
├── nodemon@2.0.22
├── restify@10.0.0
├── ts-node@10.9.1
└── typescript@4.9.5
$ teamsfx --version          
2.0.1
$ code --version                 
1.80.1
74f6148eb9ea00507ec113ec51c489d6ffb4b771
x64
$ code --profile TeamApp --list-extensions --show-versions | grep 'teams'
TeamsDevApp.ms-teams-vscode-extension@5.0.1
$ microsoft-edge-beta --version
Microsoft Edge 115.0.1901.175 beta
$ cat /etc/os-release                                                               
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"

```

## Describe the bug

401 Unauthorized error thrown when the bot tries to access an user uploaded file.

## To Reproduce

1. Setup a project using either `teamsfx` cli or VSCode Teams-Toolkit extension.
2. Provision and deploy the bot.
3. Preview in MS Teams.
4. Upload a file, see error.

Source Code : https://gitea.com/joe733/epitoma

## Expected behavior

Bot is able to read file without any authorization error.

## Screenshots

![image](https://github.com/microsoft/botbuilder-js/assets/38415384/3dcc7fb7-8cce-43a6-bec4-c2b2a9846ab8)

`console.log`

```console
Bot Started, restify listening to http://[::]:3978

Received user input
No of attachments: 2
Asynchronous processing
        Handling attachment of class: 'application/vnd.microsoft.teams.file.download.info' & of type: 'txt'
        Handling attachment of class: 'text/html' & of type: 'txt'
        Attachment class: 'text/html' & of type: 'txt' isn't supported

        ==> Attempting to download: sample.txt of class: 'application/vnd.microsoft.teams.file.download.info' & of type: 'txt'
        ==> Download Source: https://XXvsms-my.sharepoint.com/personal/example-user_XXvsms_onmicrosoft_com/Documents/Microsoft Teams Chat Files/sample.txt
        ==> Download Error: 401 Unauthorized
        ==> Skipping unsupported attachment
Awaiting next user input
```

## Additional context

[Code snippet](https://gitea.com/joe733/epitoma/src/commit/8ba681cde0f52900ce697af5594c0af24743808c/src/teamsBot.ts#L129-L167) from the source causing trouble:

```ts
...
  const authToken = await new MicrosoftAppCredentials(
    config.botId,
    config.botPassword
  ).getToken();

...

  try {
    const response = await axios.get(url, {
      responseType: "text",
      headers: { Accept: "text/plain", Authorization: `Bearer ${authToken}` },
    });

...

  } catch (error) {
    if (error instanceof AxiosError) {
      console.error(
        `\t==> Download Error: ${error.response.status} ${error.response.statusText}`
      );
    }
    
...
```

Am I giving the wrong token? or wrong header? Please provide suggestions, hints, documentation reference, forums or links that could help resolve this.

**Comment by vishn2200** [comment]
Had the same errors

**Comment by vishn2200** [comment]
I still have the same error.

**Comment by anishprasad01** [comment]
Did you use a specific Teams sample as a starting point?

**Comment by joe733** [comment]
> Did you use a specific Teams sample as a starting point?

No, just started with a `Basic Bot`.

![image](https://github.com/microsoft/botbuilder-js/assets/38415384/a7038f64-b7e6-41cd-8085-f896bc905301)
![image](https://github.com/microsoft/botbuilder-js/assets/38415384/d4e60d4b-7f7a-4ebf-ab2b-c531a9e793d1)

**Comment by joe733** [comment]
Turns out `attachment.content.downloadUrl` does not throw 401 as opposed to `attachment.contentUrl`. But on the browser the former URL opens file in a onedrive/sharepoint interface, whereas the latter URL shows up as a plain text.

Anyway, I can now grab the file using `attachment.content.downloadUrl`, with same HTTP token authentication.
