### ISSUE TITLE
botbuilder-ai@4.20.0 is still installing @azure/ms-rest-js@1.11.2 for @azure/cognitiveservices-luis-runtime

### ISSUE THREAD

**Issue by aftabmustafa** [microsoft/botbuilder-js#4509]
## Versions
What package version of the SDK are you using: botbuilder-ai@4.20.0
What nodejs version are you using: Node 18
What browser version are you using: Google Chrome
What os are you using: MacOS Ventura

## Describe the bug
When I am trying to install botbuilder-ai@4.20.0 package, it is still installing @azure/cognitiveservices-luis-runtime/@azure/ms-rest-js@1.11.2 but based on the [PR 4508](https://github.com/microsoft/botbuilder-js/pull/4508/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R52) it should install @azure/cognitiveservices-luis-runtime/@azure/ms-rest-js@2.7.0. The older version of ms-rest-js package is using tough cookie which has been identified as a critical vulnerability.

## To Reproduce
1. install botbuilder-ai package using this command `npm i botbuilder-ai`
2. Run `npm ls tough-cookie` to see the @azure/cognitiveservices-luis-runtime and @azure/ms-rest-js version

## Expected behavior
@azure/ms-rest-js version under @azure/cognitiveservices-luis-runtime should be equal to 2.7.0

## Screenshots
![image](https://github.com/microsoft/botbuilder-js/assets/48243759/f34ba391-ba76-4f78-8a15-820dd75f1b4d)

## Additional context
https://github.com/microsoft/botbuilder-js/issues/4504

**Comment by ceciliaavila** [comment]
Hi @aftabmustafa,
[PR#4508](https://github.com/microsoft/botbuilder-js/pull/4508) was merged last week. The fix should be in version [4.21.0-dev.20230724.faf57c5](https://www.npmjs.com/package/botbuilder-ai/v/4.21.0-dev.20230724.faf57c5) of botbuilder-ai.
Could you check if the preview version installs the correct version of ms-rest-js?

**Comment by aftabmustafa** [comment]
I still see tough-cookie
![image](https://github.com/microsoft/botbuilder-js/assets/48243759/4d124b61-4c30-4178-8b11-ba2c80c6f971)

**Comment by guy-microsoft** [comment]
@ceciliaavila Hi, is there an ETA for a fix?

**Comment by ceciliaavila** [comment]
> @ceciliaavila Hi, is there an ETA for a fix?

Hi @guy-microsoft, 
We are testing a post-install script to remove the vulnerable dependencies because none of the usual ways of forcing package versions worked in this case.
We estimate having the script ready by tomorrow's end of day.

**Comment by guy-microsoft** [comment]
Thanks!

**Comment by ceciliaavila** [comment]
> > @ceciliaavila Hi, is there an ETA for a fix?
> 
> Hi @guy-microsoft, We are testing a post-install script to remove the vulnerable dependencies because none of the usual ways of forcing package versions worked in this case. We estimate having the script ready by tomorrow's end of day.

Unfortunately, the script didn't solve the issue. Although the _tough-cookie_ package was removed from the node_modules and the yarn.lock file, the _npm audit_ command still reports the vulnerability. 
Next week, we'll try as an alternative, upgrading _@azure/cognitiveservices-luis-runtime_ to version 4.x. This version has significant changes, we'll attempt to avoid breaking compat.

**Comment by aftabmustafa** [comment]
Just out of curiosity, will version 4.x of _@azure/cognitiveservices-luis-runtime_ install the latest version of @azure/ms-rest-js?

**Comment by ceciliaavila** [comment]
> Just out of curiosity, will version 4.x of _@azure/cognitiveservices-luis-runtime_ install the latest version of @azure/ms-rest-js?

Yes, it will install @azure/ms-rest-js@^2.0.3 which resolves to 2.7.0.

**Comment by guy-microsoft** [comment]
@ceciliaavila Hi, do you have an estimation of when it's going to be published? Are you going to publish it as a patch version for 4.20?

**Comment by ceciliaavila** [comment]
> @ceciliaavila Hi, do you have an estimation of when it's going to be published? Are you going to publish it as a patch version for 4.20?

Hi @guy-microsoft, I don't know the release plan, maybe @tracyboehrer can help us with that.

**Comment by aftabmustafa** [comment]
Can we expect the change to be available in version [4.21.0-dev.20230825.81e2d98](https://www.npmjs.com/package/botbuilder-ai/v/4.21.0-dev.20230825.81e2d98)?

**Comment by ceciliaavila** [comment]
> Can we expect the change to be available in version [4.21.0-dev.20230825.81e2d98](https://www.npmjs.com/package/botbuilder-ai/v/4.21.0-dev.20230825.81e2d98)?

Hi @aftabmustafa, Yes. The PR was merged on the 22 so the 20230825 preview version contains the changes.

**Comment by guy-microsoft** [comment]
@tracyboehrer Hi, do you have an ETA of when it's going to be in a non-preview (non dev) version?
