### ISSUE TITLE
Got an error when trying to npm install botbuilder-js

### ISSUE THREAD

**Issue by jcodog** [microsoft/botbuilder-js#4533]
When running 'yarn add botbuilder' the following error occured:
`$ yarn add botbuilder@4.21.0-dev.20230907.3685e5e
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
warning botbuilder > botframework-connector > adal-node > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] Fetching packages...
error @azure/msal-node@1.18.3: The engine "node" is incompatible with this module. Expected version "10 || 12 || 14 || 16 || 18". Got "19.8.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

I was expecting to use my installed node version that works fine for every other package I use in my project to work with botbuilder so that I can use botservice within my nextjs app to provide support for users. However this error shows that I cannot install botbuilder at all.

I know there is now a version 2.1.0 of msal-node and the uuid error has uuid@9.0.0 as lts, i tried installing these seperately into my package to rectify the install but still got the error when running this. Could I get a fix that would allow me to use this package without downgrading my node version?

**Comment by ramfattah** [comment]
Thank you @jcodog, i'm looking into this.

**Comment by ramfattah** [comment]
Hi @jcodog, 

I'm able to reproduce this error using node version `19.x.x`:
```zsh

# yarn add botbuilder@4.21.0-dev.20230907.3685e5e
yarn add v1.22.19
warning ../../../../../package.json: No license field
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning botbuilder > botframework-connector > adal-node > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] 🚚  Fetching packages...
error @azure/msal-node@1.18.3: The engine "node" is incompatible with this module. Expected version "10 || 12 || 14 || 16 || 18". Got "19.8.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

```

#

Looks like there is an incompatibility issue between Node.js version (19.8.1) and the package `@azure/msal-node@1.18.3`.

Switching node to version `v18.17.0` resolved this issue:
```zsh
 ram on  ~/Documents/bot/BF/js_bots/botbuilder-js-repro
# nvm use 18
Now using node v18.17.0 (npm v9.6.7)
 ram on  ~/Documents/bot/BF/js_bots/botbuilder-js-repro
# yarn add botbuilder@4.21.0-dev.20230907.3685e5e
yarn add v1.22.19
warning ../../../../../package.json: No license field
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning botbuilder > botframework-connector > adal-node > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 74 new dependencies.
info Direct dependencies
└─ botbuilder@4.21.0-dev.20230907.3685e5e
info All dependencies
├─ @azure/core-client@1.7.3
├─ @azure/core-rest-pipeline@1.12.1
├─ @azure/core-tracing@1.0.1
├─ @azure/core-util@1.4.0
├─ @azure/identity@2.1.0
├─ @azure/msal-browser@2.38.2
├─ @azure/msal-node@1.18.3
├─ @tootallnate/once@2.0.0
├─ @types/node@10.17.60
├─ @types/ws@6.0.4
├─ @xmldom/xmldom@0.7.13
├─ abort-controller@3.0.0
├─ adal-node@0.2.3
├─ async@2.6.4
├─ base64url@3.0.1
├─ botbuilder-core@4.21.0-dev.20230907.3685e5e
├─ botbuilder-dialogs-adaptive-runtime-core@4.21.0-dev.preview.20230907.3685e5e
├─ botbuilder@4.21.0-dev.20230907.3685e5e
├─ botframework-streaming@4.21.0-dev.20230907.3685e5e
├─ combined-stream@1.0.8
├─ cross-fetch@3.1.8
├─ date-utils@1.2.21
├─ dayjs@1.11.9
├─ define-lazy-prop@2.0.0
├─ delayed-stream@1.0.0
├─ dependency-graph@0.10.0
├─ dom-serializer@1.4.1
├─ domutils@2.8.0
├─ event-target-shim@5.0.1
├─ events@3.3.0
├─ filename-reserved-regex@2.0.0
├─ filenamify@4.3.0
├─ follow-redirects@1.15.2
├─ form-data@2.5.1
├─ fs-extra@7.0.1
├─ graceful-fs@4.2.11
├─ htmlparser2@6.1.0
├─ http-proxy-agent@5.0.0
├─ https-proxy-agent@5.0.1
├─ is-docker@2.2.1
├─ is-wsl@2.2.0
├─ jsonfile@4.0.0
├─ jwa@1.4.1
├─ jws@3.2.2
├─ lodash.includes@4.3.0
├─ lodash.isboolean@3.0.3
├─ lodash.isinteger@4.0.4
├─ lodash.isnumber@3.0.3
├─ lodash.isplainobject@4.0.6
├─ lodash.isstring@4.0.1
├─ lodash.once@4.1.1
├─ lodash@4.17.21
├─ lru-cache@6.0.0
├─ mime-db@1.52.0
├─ ms@2.1.3
├─ node-fetch@2.7.0
├─ open@8.4.2
├─ rsa-pem-from-mod-exp@0.8.6
├─ sax@1.2.4
├─ semver@7.5.4
├─ stoppable@1.1.0
├─ strip-outer@1.0.1
├─ tr46@0.0.3
├─ trim-repeated@1.0.0
├─ tunnel@0.0.6
├─ underscore@1.13.6
├─ universalify@0.1.2
├─ webidl-conversions@3.0.1
├─ whatwg-url@5.0.0
├─ ws@7.5.9
├─ xml2js@0.5.0
├─ xmlbuilder@11.0.1
├─ xpath.js@1.1.0
└─ yallist@4.0.0
✨  Done in 3.49s.

```

**Comment by ramfattah** [comment]
@jcodog, we will discuss this internally with the engineers and report back. Thanks.

**Comment by ramfattah** [comment]
@jcodog, I'll discuss this internally with the engineers and report back. Thanks.

**Comment by ramfattah** [comment]
Hi @jcodog, 

This is a feature request and not a bug. 

The error message is quite clear:
> Expected version "10 || 12 || 14 || 16 || 18". Got "19.8.1"

Using Node version 18.x resolves this issue.

#

Node.js even-numbered versions (18.x) are Long-Term Support (LTS) releases, favored for their stability, while odd-numbered versions(19.x) are short-lived and less stable. Given this, and considering this is a Microsoft enterprise project, we won't be upgrading to version 19. We recommend using an LTS version for optimal stability.
