### ISSUE TITLE
Implementing updateActivity on Custom adapter not working as expected

### ISSUE THREAD

**Issue by tariromukute** [microsoft/botbuilder-js#4537]
## Versions
@botbuildercommunity/core: "^1.0.0",
 botbuilder": "^4.8.0"

## Describe the bug
Hi. I am trying to implement the updateActivity on a custom adapter. The adapter is for WhatsApp business. The implementation should not update the message on WhatsApp but should trigger the `onUpdateActivity` on the middleware. I tried following this simple example [here](https://github.com/microsoft/botbuilder-js/blob/cbb187dec6ccfe096bf6df70dad898a41a90ae49/libraries/botbuilder-core/src/testAdapter.ts#L300), 

```javascript
/**
     * @private
     * Replaces an existing activity in the activeQueue.
     * @param context Context object for the current turn of conversation with the user.
     * @param activity Activity being updated.
     * @returns promise representing async operation
     */
     public async updateActivity(context: TurnContext, activity: Partial<Activity>): Promise<ResourceResponse | void> {
        if (activity.id) {
            const idx = this.activeQueue.findIndex((a) => a.id === activity.id);
            if (idx !== -1) {
                this.activeQueue.splice(idx, 1, activity);
            }
            return Promise.resolve({ id: activity.id });
        }

        return Promise.resolve();
    }
```

The `onUpdateActivity` is triggered but the dialogs does not continue. The console prints `undefined` but I can't trace where the undefined is coming from. Since I have followed the signature of the method, I expected the dialog flow to continue after calling `await stepContext.context.updateActivity(activity)`

## Expected behavior
The WaterfallDialog should continue after calling `await stepContext.context.updateActivity(activity)`

## Additional context
I am trying to update the transcript when an activity is updated. The TranscriptLoggerMiddleware does this when `onUpdateActivity` event is invoked . In this case I use speech to text in one of the dialog steps and I would like to update the transcript with the resulting text for the audio that was provided by the user.

**Comment by stevkan** [comment]
@tariromukute - Are you using one of the @botbuildercommunity adapters and, if so, which one? Or is this an adapter you are custom building, yourself?

**Comment by tariromukute** [comment]
Hi @stevkan. I am using the **@botbuildercommunity/core** version 1.0.1.

```javascript
/**
 * @module botbuildercommunity/adapter-facebook-whatsapp
 */
import { Activity, ActivityTypes, TurnContext, ConversationReference, ResourceResponse, WebRequest, WebResponse, Attachment, GeoCoordinates, BotFrameworkAdapterSettings } from 'botbuilder';
import { CustomWebAdapter } from '@botbuildercommunity/core';

// ...

export class FacebookWhatsAppAdapter extends CustomWebAdapter {

// ...

  /**
     * @private
     * Replaces an existing activity in the activeQueue.
     * @param context Context object for the current turn of conversation with the user.
     * @param activity Activity being updated.
     * @returns promise representing async operation
     */
     public async updateActivity(context: TurnContext, activity: Partial<Activity>): Promise<ResourceResponse | void> {
        if (activity.id) {
            const idx = this.activeQueue.findIndex((a) => a.id === activity.id);
            if (idx !== -1) {
                this.activeQueue.splice(idx, 1, activity);
            }
            return Promise.resolve({ id: activity.id });
        }

        return Promise.resolve();
    }

// ...
}
```

**Comment by stevkan** [comment]
@tariromukute - I believe your core issue is `updateActivity` isn't supported by the service. Unfortunately, WhatsApp hasn't exposed an API that allows for creating a WhatsApp only adapter. As such, it must be implemented via another service that does have access.

In the botbuilder-community-dotnet repo, InfoBip is used as the base service in the InfoBipWhatsApp adapter and you can see [here](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Infobip.WhatsApp/InfobipWhatsAppAdapter.cs#L22) that the `updateActivity` method is not implemented. And, in the botbuilder-community-js repo, Twillio is used as base service in the TwilioWhatsApp adapter and looking [here](https://github.com/BotBuilderCommunity/botbuilder-community-js/blob/master/libraries/botbuilder-adapter-twilio-whatsapp/src/twilioWhatsAppAdapter.ts#L126) you can see the same. Looking at our [channel reference guide](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#activity-support-by-channel), neither of those services support the Message Update (i.e. `updateActivity`) method.

Looking at your provided code, I'm _assuming_ you are trying to use Facebook as the base service. However, Facebook also does not support `updateActivity`. So, as I mentioned above, I believe your core issue is simple that that method isn't supported resulting in the unexpected results.

**Comment by tariromukute** [comment]
Hi @stevkan, thank you for information and feedback. I understand that WhatsApp doesn't expose an API to update a message that has been sent already. I would like to emulate that behaviour, to have botframework interpret it as an activity that has been successfully updated with the service provider.

The reason I want to do this is so that I can trigger the `onUpdateActivity` in the `TranscriptLoggerMiddleware`. I am receiving a voice message, and after transcribing it I would like to update the activity that has been logged by the `TranscriptLoggerMiddleware` to include the result text.

How do I emulate the `updateActivity` such that the botframework will interpret it as a successful action.

**Comment by tracyboehrer** [comment]
The Adapter.updateActivity would need to return a ResourceResponse object.  Most likely could just set ResourceResponse.id to the Activity.id.
