### ISSUE TITLE
Choice options should be more robust

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-js#454]
In the v3 code you could pass the `ChoicePrompt` a list of choices with a partially filled `action` field and the SDK would fill in the missing fields. So choice a list like this:

``` 
const choices = [
     { value: 'red', action: { title: 'Red Color' } },
     { value: 'green', action: { title: 'Green Color' } },
     { value: 'blue', action: { title: 'Blue Color' } }
];
```

Would be automatically converted to this:

``` 
const choices = [
     { value: 'red', action: { type: 'imBack', title: 'Red Color', value: 'Red Color' } },
     { value: 'green', action: { type: 'imBack', title: 'Green Color', value: 'Green Color' } },
     { value: 'blue', action: { type: 'imBack', title: 'Blue Color', value: 'Blue Color' } }
];
```

The v4 code base doesn't do this so the suggested actions sent by the `ChoicePrompt` end up being incomplete. You'll see the buttons but clicking them won't result in a message being sent.

We should make the v4 version of the `Choice` structure more robust and allow a `Partial<CardAction>` like v3 supports.  This should be a non-breaking change so we could easily post-pone it to 4.1

**Comment by stevengum** [comment]
Closing via #511's merge into master
