### ISSUE TITLE
JwtTokenExtractor.getIdentity:err! FetchError: request to https://login.botframework.com/v1/.well-known/openidconfiguration failed, reason: connect ETIMEDOUT

### ISSUE THREAD

**Issue by saulo2** [microsoft/botbuilder-js#4544]
Hi,

I am getting the error below with the botbuilder 4.15.0:

JwtTokenExtractor.getIdentity:err! FetchError: request to https://login.botframework.com/v1/.well-known/openidconfiguration failed, reason: connect ETIMEDOUT 104.41.13.179:443
    at ClientRequest.<anonymous> (/opt/nexos-teams/bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

I am behind a corporate fiewall. I have tried setting the HTTP_PROXY and HTTPS_PROXY variables, but it did not solve the problem.

I have also tries configuring the proxySettings options as below, but it also did not solve the problem.

const botFrameworkAuthentication = createBotFrameworkAuthenticationFromConfiguration(null, credentialsFactory, null, null, {
    proxySettings: {
        host: "cachesv",
        port: 8080
    }
});

Does botbuilder supports http proxies?

**Comment by saulo2** [comment]
After some investigation, the problem seems to be in the refreshCache method of the OpenIdMetadata class. More specifically, in the line:

const res = await fetch(this.url);

which does not use the proxySettings provided for the createBotFrameworkAuthenticationFromConfiguration method.

**Comment by tracyboehrer** [comment]
@saulo2 There is a test version on NPM we think addresses this.  The version is: 4.21.4-dev.  Can you try this version and check if it corrects the problem?

**Comment by ceciliaavila** [comment]
This is how we set the proxy settings for testing the fix:
![image](https://github.com/microsoft/botbuilder-js/assets/44245136/88c34894-e02a-408a-bf4c-cd739edbe57f)

**Comment by saulo2** [comment]
> @saulo2 There is a test version on NPM we think addresses this. The version is: 4.21.4-dev. Can you try this version and check if it corrects the problem?

@tracyboehrer and @ceciliaavila thanks for addressing this issue. Right now, I am travelling on vacation. As soon I come back (circa 10 days) I am going to test the fix and give you feedback.

**Comment by denisogolubev** [comment]
@tracyboehrer @ceciliaavila hi)
We're facing the same issue.

To solve it we've followed your instructions, installed:
```json
{
    "botbuilder": "4.21.4-dev",
}
```
Also, we have added `proxySettings` to the `botFrameworkAuthentication`.
And now the error a bit changed:
`
FetchError: request to https://login.botframework.com/v1/.well-known/keys failed, reason: connect ECONNREFUSED XX.XXX.XXX.XX:XXX
    at ClientRequest.<anonymous> (/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:517:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
`

It started to fail on request to `https://login.botframework.com/v1/.well-known/keys`.
Could you help us?

**Comment by tracyboehrer** [comment]
@saulo2 and @denisogolubev There is a new test version: 4.21.4-dev2

**Comment by denisogolubev** [comment]
@tracyboehrer thanks a lot, it fixed the previous issue.
Now we see this error:
```
[onTurnError] unhandled error: ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
    at ClientAuthError.AuthError [as constructor] (/node_modules/@azure/msal-common/src/error/AuthError.ts:49:9)
    at new ClientAuthError (/node_modules/@azure/msal-common/src/error/ClientAuthError.ts:223:15)
    at Function.ClientAuthError.createEndpointDiscoveryIncompleteError (/node_modules/@azure/msal-common/src/error/ClientAuthError.ts:269:16)
    at Function.<anonymous> (/node_modules/@azure/msal-common/src/authority/AuthorityFactory.ts:58:35)
    at step (/node_modules/@azure/msal-common/dist/index.cjs.js:79:23)
    at Object.throw (/node_modules/@azure/msal-common/dist/index.cjs.js:60:53)
    at rejected (/node_modules/@azure/msal-common/dist/index.cjs.js:51:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errorCode: 'endpoints_resolution_error',
  errorMessage: 'Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.',
  subError: '',
  correlationId: 'fddc35e1-2192-4ff5-a8f8-0c196ad8da6d'
}
```

Is it something with our configurations or is it still the issue with the proxy?
Because I don't see `knownAuthorities` as a property in any existing configs we use.

**Comment by ceciliaavila** [comment]
Hi @denisogolubev,
This same error was reported by another customer that was using a proxy.
The problem seems to be in a call that the _@azure/msal-node_ library does internally.
Can you try the following?

- 	Check if you can access this URL in a browser or your proxy is blocking it:
	https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/botframework.com/oauth2/v2.0/authorize

- 	There's a _proxyUrl_ property that can be configured in the bot ([more info](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#why-doesnt-my-app-function-correctly-when-its-running-behind-a-proxy)). Here is an example of how to provide this setting:

![image](https://github.com/microsoft/botbuilder-js/assets/44245136/74dbf222-8279-47d9-8544-60699b7874ca)

**Comment by ceciliaavila** [comment]
According to [this issue](https://github.com/nodejs/node/issues/8381), proxy settings are not globally set in NodeJS, we need to use libraries to manage this.
Using the [node-global-proxy](https://www.npmjs.com/package/node-global-proxy) package, we can set the HTTP_PROXY and HTTPS_PROXY variables for Node to use.
There's no need to make changes in the SDK, just a simple configuration in the bot's _index.js_ file.

![image](https://github.com/microsoft/botbuilder-js/assets/44245136/3f628603-704f-4b7b-86e3-b1c5b215f81e)

This is a better alternative than setting the proxy host and port values in the _BotframeworkAuthentication_ options. However, for the `untrusted_authority` error, you should try the [workaround proposed by _msal-node_](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#why-doesnt-my-app-function-correctly-when-its-running-behind-a-proxy).

**Comment by denisogolubev** [comment]
> According to [this issue](https://github.com/nodejs/node/issues/8381), proxy settings are not globally set in NodeJS, we need to use libraries to manage this. Using the [node-global-proxy](https://www.npmjs.com/package/node-global-proxy) package, we can set the HTTP_PROXY and HTTPS_PROXY variables for Node to use. There's no need to make changes in the SDK, just a simple configuration in the bot's _index.js_ file.
> 
> ![image](https://private-user-images.githubusercontent.com/44245136/292232174-3f628603-704f-4b7b-86e3-b1c5b215f81e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzY2OTYsIm5iZiI6MTcwMzIzNjM5NiwicGF0aCI6Ii80NDI0NTEzNi8yOTIyMzIxNzQtM2Y2Mjg2MDMtNzA0Zi00YjdiLTg2ZTMtYjFjNWIyMTVmODFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA5MTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYjc5YTU2MTJkZWRhNWI4ZGZjNGE3MThhYjdiNmY1N2JlZGMyNDlmODYwODRkZTgxZWI2MmE1M2M1ZjM2NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CmAB3Ojvl2uCW4cCaRQrwZmP1FdTRaeqCAkuDB1CsQ4)
> 
> This is a better alternative than setting the proxy host and port values in the _BotframeworkAuthentication_ options. However, for the `untrusted_authority` error, you should try the [workaround proposed by _msal-node_](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#why-doesnt-my-app-function-correctly-when-its-running-behind-a-proxy).

@ceciliaavila it looks like this configuration solves the issue)
Thanks a lot)

**Comment by saulo2** [comment]
@tracyboehrer and @ceciliaavila I confirm version 4.21.4-dev2 fixes the matter. However, I have tested 4.21.4 and it seems it does not contain the fix. Also, it seems the fix is not in the main branch. For example, the constructor of the class OpenIdMetadata (https://github.com/microsoft/botbuilder-js/blob/main/libraries/botframework-connector/src/auth/openIdMetadata.ts) does not receive a ProxySettings instance as it second argument.

**Comment by ceciliaavila** [comment]
Hi @saulo2, we discarded the fix from 4.21.4-dev2 because we found a simpler solution by adding to the bot the [node-global-proxy](https://www.npmjs.com/package/node-global-proxy) package. Can you try this solution to see if it fixes the issue on your side?

**Comment by saulo2** [comment]
@ceciliaavila the solution around [node-global-proxy](https://www.npmjs.com/package/node-global-proxy) also fixed the issue, but it caused undesirable side effects. My bot access APIs on other intranet servers, which the corporate proxy does not have access to because it only access servers on the internet. Thus, with [node-global-proxy](https://www.npmjs.com/package/node-global-proxy) my bot is able to access https://login.botframework.com/v1/.well-known/openidconfiguration but it does not work, because it is not able to access the othe intranet servers. Could you reintroduce your fix in a new botbuilder-js version?

**Comment by ceciliaavila** [comment]
@saulo2, thanks for your input.
@tracyboehrer, we re-opened the PR with the fix, if you think it's correct, you can merge it. Thanks!

**Comment by tracyboehrer** [comment]
@ceciliaavila @saulo2 @denisogolubev Can we clarify what does work?  denisogolubev reported that 4.21.4-dev2 (which was built from the PR branch) caused a subsequent problem, but that node-global-proxy worked.  Is the final solution this PR and possibly node-global-proxy?

BTW, the actual 4.21.4 release done recently does NOT have that PR fix.

**Comment by saulo2** [comment]
@tracyboehrer and @ceciliaavila I am happy to confirm that the fix has been successfully incorporated into the codebase. I tested version 4.22.1 and it is working as expected.
