### ISSUE TITLE
Please upgrade zod package

### ISSUE THREAD

**Issue by dominykas** [microsoft/botbuilder-js#4545]
**Is your feature request related to a problem? Please describe.**

The `zod` version (`1.11.17`) used across the project has a security vulnerability, which gets picked up by various scanners, e.g. https://security.snyk.io/vuln/SNYK-JS-ZOD-5925617 and it is also over two years old.

**Describe the solution you'd like**

Please upgrade to `v3.x` release line (first released some 2+ years ago).

**Describe alternatives you've considered**

n/a

**Additional context**

Would it make sense to turn on Renovate (or change Dependabot config) for this project? There does not seem be a clearly visible dependency upgrade strategy in place.

**Comment by arthurfeduniv** [comment]
+1

**Comment by Ermak-13** [comment]
🔐

**Comment by alyaptsev** [comment]
➕

**Comment by jineshjin** [comment]
+1

**Comment by Joao-pina-fernandes** [comment]
👍

**Comment by Harvey1976** [comment]
+1 we are use the botkit to generate our application ,in recently trivy scan , we found the issue of Zod. 

actually zod already fix this, but bot builder did not fix this. please upgrade of Zod to 3.xx

**Comment by seanhsmith** [comment]
+1

**Comment by cdeliens** [comment]
+1

**Comment by hieumoscow** [comment]
Hi @sw-joelmut, have you started a branch to upgrade Zod to 3.22.4? I have a project that is blocked, due to this CVE, from going to production this week.

Can you help me to look into this issue please, thank you.

**Comment by sw-joelmut** [comment]
> Hi @sw-joelmut, have you started a branch to upgrade Zod to 3.22.4? I have a project that is blocked, due to this CVE, from going to production this week.
> 
> Can you help me to look into this issue please, thank you.

Hi @hieumoscow,

We are working on this, we'll have news soon.

**Comment by hieumoscow** [comment]
Hi @sw-joelmut, took me a bit of time to upgrade and test locally, it seems to run find and parses the test. 

However there is 1 test at the CloudAdapter Test that the stub seems unable to get the desired expired error message. 

https://github.com/microsoft/botbuilder-js/blob/842baf30b64906495914d428f19bbcd16fb81532/libraries/botbuilder/tests/cloudAdapter.test.js#L181

![image](https://github.com/microsoft/botbuilder-js/assets/5441003/459ab55b-8bb8-476a-ae84-6b9ab2edd017)

Could you please help me review. Pardon me for anythings that I might have missed out as it is my first time contributing to this repo.

**Comment by Harvey1976** [comment]
hi I check the Pull request proposed by @hieumoscow , it seems this PR is try to merge code to 4.21.release of bot kit. 
as a user of botkit, current the zod CVE is blocked our project to release actually. 
then , may I know the possbile release date of 4.21？ thanks a lot

**Comment by shabbir-dhangot** [comment]
What is the release version and date for this change to be made available for consumption?
