### ISSUE TITLE
Need support for Node.js 20

### ISSUE THREAD

**Issue by XiaofuHuang** [microsoft/botbuilder-js#4550]
Node.js 20 will be designated as the active LTS version as of October 24, 2023. 
The SDK has a dependency on `@azure/msal-node`, which appears to be outdated. Running the `npm install` commandresults in warnings due to its incompatibility with Node.js 20.

**Comment by frbayart** [comment]
@ramfattah Any news to support the current nodejs LTS

**Comment by oFlo193o** [comment]
Also Waiting for Node.js 20 Support...

**Comment by seanhsmith** [comment]
+1 We were hoping to update our project to node 20 but were limited to node 18 due to this dependency.

**Comment by oFlo193o** [comment]
Any news on this one @microsoftopensource  / or maybe @ceciliaavila?

**Comment by elovin** [comment]
[Apparently there are no breaking changes between `@azure/msal-node` v1 and v2 aside from the dropped nodejs 16 support in v2.](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6759)

So until the dependency is being updated you could just overwrite the dependency globally in `package.json`

[...]
```json
        "overrides": {
		"@azure/msal-node": "2.6.0"
	},
	"dependencies": {
		"@azure/msal-node": "2.6.0",
```
[...]

**Comment by alexnault** [comment]
Are there plans to upgrade to [@azure/msal-node](https://www.npmjs.com/package/@azure/msal-node#node-version-support) v2 and therefore support Node 20?

**Comment by tracyboehrer** [comment]
@alexnault Yes.  But there is a complication.  While it's out of support, we still have a healthy number of customers on Node 16.  Not good manners to just drop it without a heads up.  For the next few releases, the release notes will include a notice about updating to Node 18+.  Does elovins suggestion work for you?

**Comment by alexnault** [comment]
@tracyboehrer Great to hear that Node 20 support is on the horizon!

I understand that dropping support for Node 16 is a breaking change. To me, this shoudl warrant a major version upgrade over a notice, like @azure/msal-node did.

Meanwhile, I added `overrides` as @elovin suggested and it does work:
```json
"overrides": {
  "@azure/msal-node": "^2.6.1"
}
```

Cheers!

**Comment by mogadanez** [comment]
is error @azure/msal-node@1.18.4 really not support  node 20?
maybe  just  remove this constraint  and allow node 20 in @azure/msal-node@1.18.5 ?
``` 
The engine "node" is incompatible with this module. Expected version "10 || 12 || 14 || 16 || 18".
```

**Comment by eitanlevinzon-astrix** [comment]
Hey, what's the status of this? Waiting for this to be implemented for https://github.com/OfficeDev/TeamsFx/issues/10849

**Comment by Bomret** [comment]
We received an email today that Azure Functions will drop node <18 next month and projects need. to update to keep receiving security updates and costumer service. In this regard I think this issue's priority should be elevated and done as soon as possible.

Excerpt from the Microsoft email:
> Support for Node.js 18 ends on 30 April 2025—upgrade your apps to Node.js 20 
> 
> You’re receiving this email because you have one or more Node.js 18 app(s) on Azure Functions.
> 
> On 30 April 2025, Node.js 18 will end. Your apps that are hosted on Azure Functions will continue to run, but security updates will no longer be available, and we’ll no longer provide customer service for Node.js 18. Learn more about [Azure Functions stack version support](https://learn.microsoft.com/azure/azure-functions/language-support-policy).

**Comment by tracyboehrer** [comment]
Thanks all.  This is high priority for us, but we are blocked by another dependency.  Working it.

**Comment by dominykas** [comment]
Outdated dependencies in `botbuilder` are starting to rack up vulnerabilities, e.g. https://security.snyk.io/vuln/SNYK-JS-AZUREIDENTITY-7246760, https://security.snyk.io/vuln/SNYK-JS-AZUREMSALNODE-7246761 - `@azure/identity` is two major versions behind, and then there's `axios@0.x`.

Given that some of these are inside Microsoft, perhaps there could be a way to backport some of the fixes to the older versions, to keep things maintained?

As much as the breaking changes are not necessarily viable for certain customers who are on old versions of Node.js (which is unmaintained for 9 months, mind you), increasing the vulnerability footprint is a problem for other customers, and I'm not sure which one is more important (and dangerous).

**Comment by dominykas** [comment]
One more vulnerable outdated dependency under `botframework-streaming`: https://security.snyk.io/vuln/SNYK-JS-WS-7266574
