### ISSUE TITLE
Extensibility for Teams AI - ability to add to User Agent for Teams AI telemetry

### ISSUE THREAD

**Issue by corinagum** [microsoft/botbuilder-js#4552]
Request is from https://github.com/microsoft/teams-ai team

[connectorFactoryImpl](https://github.com/microsoft/botbuilder-js/blob/593cd3b86d9b5058cebfd552c2db1953e066291b/libraries/botframework-connector/src/auth/connectorFactoryImpl.ts#L20) Adds Bot Framework / Bot Builder information which is used to track telemetry. 
![image](https://github.com/microsoft/botbuilder-js/assets/14900841/8c0dc2ae-51fe-4d55-9fc1-7009622bcfcd)

We are hoping to have the ability to add Teams AI information for SMBA to parse for telemetry. 

Since Teams AI is JavaScript first, we request this would be done in the JS SDK first with fast follow for C# and Python

**Comment by corinagum** [comment]
C# SDK request: https://github.com/microsoft/botbuilder-dotnet/issues/6701

**Comment by corinagum** [comment]
@tracyboehrer @stevengum @aacebo FYI

**Comment by tracyboehrer** [comment]
I believe Alex handled this is a different way by subclassing CloudAdapter.
