### ISSUE TITLE
scoreThreshold no longer works in 4.17.0 and later

### ISSUE THREAD

**Issue by dmvtech** [microsoft/botbuilder-js#4568]
## Describe the bug
When supplying scoreThreshold, it is not honored and will return the answer even though the score is much lower.

## Versions
4.17.0 and later
Works in 4.16.0

## Describe the bug
When supplying scoreThreshold, it is not honored and will return the answer even though the score is much lower.

```javascript
const qnaOptions = {scoreThreshold:0.65};
const qnaResults = await this.qnaMaker.getAnswers(context,qnaOptions);
```

## To Reproduce
1.  Use sample such as: https://github.com/microsoft/BotBuilder-Samples/tree/releases/4.16/samples/javascript_nodejs/11.qnamaker
2. Add options to use the scoreThreshold
    const qnaOptions = {scoreThreshold:0.65};
    const qnaResults = await this.qnaMaker.getAnswers(context,qnaOptions);
4. Test with a question that has a score that will not meet the threshold
5. See that you will get a valid answer anyway

## Expected behavior
Should give `No QnA Maker answers were found.` or similar error as the answer is not above the threshold.

## Additional context
- .NET SDK does not seem to have the issue.
- Note that we (at least in the JS SDK, do not send a valid scoreThreahold to QnA endpoint. QnA endpoint will use 0-100 for the threshold, and the SDK uses a float 0.0-1 and therefore will almost always hit the QnA threshold. We then filter/compare after the results returned and determine if it is a valid answer.

Somewhat related issue:
https://github.com/microsoft/botbuilder-js/issues/1808

**Comment by dmvtech** [comment]
@ceciliaavila Let me know if there are any questions. I can reproduce and will try and add some screenshots shortly.

**Comment by dmvtech** [comment]
In my example;

- The question `What are pickles?` has a score of `100`
- The question `Do you know those cucumbers in vinegar?` has a score of `46.31`
- The scoreThreshold in the bot is set to `0.65`

### Working as expected in 4.16.0
![image](https://github.com/microsoft/botbuilder-js/assets/43397658/1cea0609-74bf-421c-8931-6b4f774ec5ba)

### Failing in 4.17.0
![image](https://github.com/microsoft/botbuilder-js/assets/43397658/350b3f1c-1e00-4759-9545-0ddca72918e1)

**Comment by tracyboehrer** [comment]
Possibly related to this:  https://github.com/microsoft/botbuilder-js/pull/4208
