### ISSUE TITLE
Can't start basic Echo bot

### ISSUE THREAD

**Issue by matthieudelaro** [microsoft/botbuilder-js#4572]
## Versions
What package version of the SDK are you using : botbuilder@4.15.0
What nodejs version are you using : v19.4.0
What browser version are you using: None
What os are you using : OSX 12.2.1

## Describe the bug
Same as described in https://github.com/microsoft/botbuilder-js/issues/4520

## To Reproduce
1. Follow the instructions from [the official documentation](https://learn.microsoft.com/en-gb/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=javascript%2Cvs)
2. `yo botbuilder`, Select the Echo bot, in Javascript
3. npm start
```
# ...
node_modules/restify/lib/request.js:848
    Request.prototype.closed = function closed() {
# ...
```
5. See error

## Expected behavior
It should run as follows:
```

> my-chat-bot@1.0.0 start
> node ./index.js

restify listening to http://[::]:3978

Get Bot Framework Emulator: https://aka.ms/botframework-emulator

To talk to your bot, open the emulator select "Open Bot"
```

## Additional context
Restify is outdated:
```
npm list restify
# => ~v8
```

This solves the issue:
```
npm install restify@^10.0.0
```

This is surprising, since this seemed to be solved by PR merged related to https://github.com/microsoft/botbuilder-js/issues/4520

**Comment by stevkan** [comment]
@matthieudelaro - I was able to repro the issue you experienced tested using both Node v18.9.0 and v19.4.0. It seems the generator is installing `botbuilder@4.15.0` when it should be installing v4.20.0, at a minimum. If you upgrade the `botbuilder` package, leaving `restify` at v11.1.0, the echo bot performs, as expected.

We will look into this and correct the issue. Thank you for the notification.

**Comment by tracyboehrer** [comment]
Pushed updated JS generators which use SDK 4.20.0.
