### ISSUE TITLE
Cannot catch MemberNotFoundInConversation error when calling getConversationPagedMembers

### ISSUE THREAD

**Issue by seanhsmith** [microsoft/botbuilder-js#4614]
## Versions
What package version of the SDK are you using. `4.21.4`
What nodejs version are you using `18.12.0`
What browser version are you using `N/A`
What os are you using `N/A`

## Describe the bug
We are receiving a "MemberNotFoundInConversation" error extremely frequently in our middleware logs (69k times in the last 30 days). Our middleware sits between our client instances and the bot API and facilities communication between them. This error is thrown when we call the `getConversationPagedMembers` method of `ConnectorClient` from the `botframework-connector` package. The following is an example of one of these errors but I have redacted any conversation IDs, tenant IDs and hostnames with `[REDACTED]`.
```
DEFAULT 2024-01-31T15:49:29.983978Z 2024-01-31T15:49:29.984Z app:info Started GET "/users?payload=[REDACTED]“ for [REDACTED].uc.r.appspot.com at Wed Jan 31 2024 15:49:29 GMT+0000 (Coordinated Universal Time)
DEFAULT 2024-01-31T15:49:29.983978Z 2024-01-31T15:49:29.984Z app:info Started GET "/users?payload=[REDACTED]” for [REDACTED].uc.r.appspot.com at Wed Jan 31 2024 15:49:29 GMT+0000 (Coordinated Universal Time)
DEFAULT 2024-01-31T15:49:30.411493Z 2024-01-31T15:49:30.410Z app:error [TID [REDACTED]] Error while getting users: RestError: Member not found in conversation.
DEFAULT 2024-01-31T15:49:30.411517Z at new RestError (/layers/google.nodejs.yarn/yarn_modules/node_modules/@azure/ms-rest-js/dist/msRest.node.js:2479:28)
DEFAULT 2024-01-31T15:49:30.411525Z at /layers/google.nodejs.yarn/yarn_modules/node_modules/@azure/ms-rest-js/dist/msRest.node.js:3644:37
DEFAULT 2024-01-31T15:49:30.411534Z at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
DEFAULT 2024-01-31T15:49:30.411540Z at async /workspace/dist/server.js:1:166031
DEFAULT 2024-01-31T15:49:30.411548Z at async /layers/google.nodejs.yarn/yarn_modules/node_modules/p-timeout/index.js:50:13 {
DEFAULT 2024-01-31T15:49:30.411560Z code: 'MemberNotFoundInConversation',
DEFAULT 2024-01-31T15:49:30.411566Z statusCode: 400,
DEFAULT 2024-01-31T15:49:30.411572Z request: WebResource {
DEFAULT 2024-01-31T15:49:30.411579Z streamResponseBody: false,
DEFAULT 2024-01-31T15:49:30.411590Z url: 'https://smba.trafficmanager.net/ca/v3/conversations/[REDACTED]/pagedmembers?pageSize=1000&continuationToken=',
DEFAULT 2024-01-31T15:49:30.411596Z method: 'GET',
DEFAULT 2024-01-31T15:49:30.411602Z headers: HttpHeaders { _headersMap: [Object] },
DEFAULT 2024-01-31T15:49:30.411609Z body: undefined,
DEFAULT 2024-01-31T15:49:30.411615Z query: undefined,
DEFAULT 2024-01-31T15:49:30.411621Z formData: undefined,
DEFAULT 2024-01-31T15:49:30.411627Z withCredentials: false,
DEFAULT 2024-01-31T15:49:30.411634Z abortSignal: undefined,
DEFAULT 2024-01-31T15:49:30.411640Z timeout: 0,
DEFAULT 2024-01-31T15:49:30.411647Z onUploadProgress: undefined,
DEFAULT 2024-01-31T15:49:30.411654Z onDownloadProgress: undefined,
DEFAULT 2024-01-31T15:49:30.411660Z proxySettings: undefined,
DEFAULT 2024-01-31T15:49:30.411666Z keepAlive: undefined,
DEFAULT 2024-01-31T15:49:30.411672Z agentSettings: undefined,
DEFAULT 2024-01-31T15:49:30.411678Z redirectLimit: undefined,
DEFAULT 2024-01-31T15:49:30.411684Z operationSpec: {
DEFAULT 2024-01-31T15:49:30.411691Z httpMethod: 'GET',
DEFAULT 2024-01-31T15:49:30.411697Z path: 'v3/conversations/{conversationId}/pagedmembers',
DEFAULT 2024-01-31T15:49:30.411704Z urlParameters: [Array],
DEFAULT 2024-01-31T15:49:30.411711Z queryParameters: [Array],
DEFAULT 2024-01-31T15:49:30.411717Z responses: [Object],
DEFAULT 2024-01-31T15:49:30.411723Z serializer: [Serializer]
DEFAULT 2024-01-31T15:49:30.411730Z }
DEFAULT 2024-01-31T15:49:30.411736Z },
DEFAULT 2024-01-31T15:49:30.411742Z response: {
DEFAULT 2024-01-31T15:49:30.411750Z body: '{"error":{"code":"MemberNotFoundInConversation","message":"Member not found in conversation."}}',
DEFAULT 2024-01-31T15:49:30.411757Z headers: HttpHeaders { _headersMap: [Object] },
DEFAULT 2024-01-31T15:49:30.411763Z status: 400
DEFAULT 2024-01-31T15:49:30.411769Z },
DEFAULT 2024-01-31T15:49:30.411775Z body: undefined
DEFAULT 2024-01-31T15:49:30.411782Z }
```
The status code appears to be 400 and the code seems like it should be `MemberNotFoundInConversation`:
```
DEFAULT 2024-01-31T15:49:30.411560Z code: 'MemberNotFoundInConversation',
DEFAULT 2024-01-31T15:49:30.411566Z statusCode: 400,
```

The following two code samples are the methods in the middleware (JS running on node) that are called when one of our client instances attempts to fetch the linked users from the middleware. Depending on the number of linked users, this usually means multiple requests from the client instance to the middleware (and thus the middleware to the Bot API). For this, we pass a `continuationToken` parameter to continue through the paged results.

You'll note that we attempt to catch both `ConversationNotFound` and `MemberNotFoundInConversation` error codes with a `try-catch` in the `getConversationMembers` method:
```
async function getConversationMembers(
  connector: ConnectorClient,
  continuationToken: string | null,
  conversationId: string,
) {
  try {
    const options = {
      continuationToken: continuationToken || '',
      pageSize: 1000,
    }

    return await connector.conversations.getConversationPagedMembers(
      conversationId,
      options,
    )
  } catch (error) {
    if (hasKey(error, 'code')) {
      if (error.code === 'ConversationNotFound') {
        logDebug(
          `Ignoring conversation ID '${conversationId}'` +
            ' because it is no longer valid',
        )

        return {
          continuationToken: '',
          members: [],
        }
      }

      if (error.code === 'MemberNotFoundInConversation') {
        logDebug(
          `Ignoring conversation ID '${conversationId}'` +
            ' because the member was not found in the conversation',
        )

        return {
          continuationToken: '',
          members: [],
        }
      }
    }

    throw error
  }
}

interface Args {
  continuationToken: string | null
  conversationId: string
  serviceUrl: string
}

export default async function getUsers({
  continuationToken,
  conversationId,
  serviceUrl,
}: Args) {
  const responsePromise = getConversationMembers(
    createConnector(serviceUrl),
    continuationToken,
    conversationId,
  )

  const timeoutMs = 60 * 1000
  const response = await pTimeout(responsePromise, timeoutMs)

  return {
    continuationToken: response.continuationToken || '',
    users: convertToUsers(response.members),
  }
}
```

## Expected behavior
Being able to capture this error so we can gracefully handle it and return empty data to our client instances.

**Comment by JhontSouth** [comment]
Hi @seanhsmith
We have not been able to replicate the error when getting the list of members of a conversation in different channels.
In our tests, the data extracted from the method _getConversationPagedMembers_ returned the members list without problems.
Could you please tell us which channel you are using and if this error happens after a re-call with _continuationToken_ or randomly?

**Comment by seanhsmith** [comment]
Hi @JhontSouth, we have also been unsuccessful in reproducing this ourselves as well. We are adding additional logging around this code to try and identify some specific conversations with which this is happening. We also don't know what channels are involved, just the conversation.

I just checked the most recent instances of this error in our logs and it looks like none of them specify a `continuationToken` but recalls also do not succeed. It's as if the conversation being requested just begins to throw the error. One thing we noticed is verbiage around the `serviceUrl` that suggests that it _should_ be stable but the possibility exists that it could change. If the `serviceUrl` did change and the old one was still being used for the request, would it result in this error?

I can provide client tenant and conversation ID examples when I have them, provided we can do it in a secure manner, and so long as it's not potentially violating Microsoft Teams TOS.

**Comment by JhontSouth** [comment]
Hi @seanhsmith,
Thank you very much for your information. We will analyze if the _serviceUrl_ is involved.
We look forward to receiving more details about the error.

**Comment by JhontSouth** [comment]
Hi @seanhsmith,
We tested changing the ServiceURL value in the middle of the conversation, but it caused a different kind of error (bad syntax - bad format of conversation ID). It seems related to the conversationId format that each channel required.
So, unfortunately, we couldn't reproduce the issue.
Could you share with us the method that you're using to create the ConnectorClient instance?
Additionally, could you provide us a simplified project? To understand the architecture that you're using.

**Comment by seanhsmith** [comment]
Hi @JhontSouth,
We create the instance of `ConnectorClient` as follows where `serviceUrl` is the serviceUrl value from the related conversation, nothing fancy:
```
const credentials = new MicrosoftAppCredentials(
  getEnv('MICROSOFT_APP_ID'),
  getEnv('MICROSOFT_APP_PASSWORD'),
)

return new ConnectorClient(credentials, { baseUri: serviceUrl })
```

The good news is we have resolved not being able to trap this RestError as it was a deployment issue on our side. Our path forward at this point is removing the conversation records that throw these errors from our system when they occur. This issue can likely be closed until the error is reproducible.

**Comment by ceciliaavila** [comment]
Hi Tracy, we couldn't reproduce this issue. As mentioned in the previous comment, it can be closed for now. Thanks!

**Comment by tracyboehrer** [comment]
@seanhsmith @ceciliaavila Thanks all.  If needed, reopen this issue.
