### ISSUE TITLE
Support for multi-instance app customization in Teams?

### ISSUE THREAD

**Issue by tobiasviehweger** [microsoft/botbuilder-js#4644]
**Is your feature request related to a problem? Please describe.**
One thing that caught our eye on the Teams roadmap is this item:
![image](https://github.com/microsoft/botbuilder-js/assets/2111803/46ab68cf-42f0-4f2f-8a81-3306595d2c54)

We were wondering how this will deal with regards to the bot? Currently, it's very clumsy if you are using the same bot across multiple Teams apps, as they all will share the same conversation reference with the user, as opposed to one conversation per app. This leads to weird behavior when sending a bot message and Teams displays a different app name, because botframework has no way of sending something like an "appCatalogIdHint" for bot messages, to support multi-app scenarios (which the roadmap item will also enable natively?)

**Describe the solution you'd like**
Support something like a "appCatalogIdHint" on incoming message handlers (to be able to reference the installed app on Teams side) and on the outgoing side (when sending bot messages), so Teams knows to which app to assign this message to.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by tracyboehrer** [comment]
This should be brought up with Teams.  I'd start with the Teams AI SDK repo.  SDK itself doesn't control what comes in on the Activity.  Historically though, Teams would add values in ChannelData (which is where channel specific data goes).
