### ISSUE TITLE
contentType for excel attachment

### ISSUE THREAD

**Issue by Kalyan492** [microsoft/botbuilder-js#4662]
Hi,

   I am working on a bot where it will post an excel attachment to a Channel. I have the following piece of code for the same:
            const attachment = {
              contentUrl: {public access enabled blob url},
              contentType: "**application/vnd.openxmlformats-officedocument.spreadsheetml.sheet**",
              name: "new_excel_blob.xlsx"
            };
            const reply: any = {type: ActivityTypes.Message}
            reply.text = `Please find your excel`;
            reply.attachments = [attachment];
            await context.sendActivity(reply);

Above code throws **"Unknown attachment type"** error. I have also tried **contentType: "reference"**. Getting the same error.

If I use the same code for image (contentType: "image/png") then I am able to post image with message to the channel. What sshoudl be the correct contentType for excel / .xslx files?

Thanks & Regards,
Kalyan

**Comment by tracyboehrer** [comment]
@Kalyan492 What channel are you using?

**Comment by Kalyan492** [comment]
> @Kalyan492 What channel are you using?

Its Teams channel (Private team -> Standard channel)

**Comment by dmvtech** [comment]
You might have to use `application/vnd.microsoft.teams.file.download.info`. Please see here for more info:
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4

Also; here is a sample that you can test to see if that works for you as well:
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-file-upload/nodejs

**Comment by tracyboehrer** [comment]
@Kalyan492 That particular error is not a BF SDK related error.  Do a search for that error message and see if any of those solutions apply.

**Comment by dmvtech** [comment]
Closing as is a Teams and/or Graph issue.
