### ISSUE TITLE
‎Teams botbuilder inline attachment download stopped working‎

### ISSUE THREAD

**Issue by nodkrot** [microsoft/botbuilder-js#4666]
## Versions
What package version of the SDK are you using.
- botbuilder@4.16.0
What nodejs version are you using
- v16.20.2
What browser version are you using
- Chrome latest
What os are you using
- Mac

## Describe the bug
On 5/10/24 we started receiving errors from Microsoft API when attempting to download inline attachments that we receive by bot builder sdk. This is impacting all of our apps. No changes were done from our side. Here is the example api:

Received payload by the bot:
{
"contentType": "image/*",
"content": {
"downloadUrl": "https://smba.trafficmanager.net/amer/f5cedd40-cc83-4a78-8c26-3328f7ceea20/v3/attachments/0-wus-d7-c727ca4fc1e3d4f753a36db52ebc183a/views/original",
"uniqueId": "da962cd8-1828-4d56-a5b0-bd1e4f36343e",
"fileType": "png",
"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCIsImtpZCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCJ9.eyJhdWQiOiJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZDZkNDk0MjAtZjM5Yi00ZGY3LWExZGMtZDU5YTkzNTg3MWRiLyIsImlhdCI6MTcxNTY3ODMzNCwibmJmIjoxNzE1Njc4MzM0LCJleHAiOjE3MTU3NjUwMzQsImFpbyI6IkUyTmdZTGlWMi9LenhrbFQ1OVZoSHFhajA4N1BCd0E9IiwiYXBwaWQiOiIwYzQ1NzUzNC01ZDllLTQ0ODgtODJhZC1iZWJmMzVjZmNkOWUiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9kNmQ0OTQyMC1mMzliLTRkZjctYTFkYy1kNTlhOTM1ODcxZGIvIiwicmgiOiIwLkFXNEFJSlRVMXB2ejkwMmgzTldhazFoeDIwSXpMWTBwejFsSmxYY09EcS05RnJ4dUFBQS4iLCJ0aWQiOiJkNmQ0OTQyMC1mMzliLTRkZjctYTFkYy1kNTlhOTM1ODcxZGIiLCJ1dGkiOiJaNzl0SmNJcUtFQ0dYWUcxbDNGYUFBIiwidmVyIjoiMS4wIn0.ICOrwGAsSsSJtb4ieYRf2ZLYIgJ5SB_PpBoMA-YvQweTiitXROTwJaX6h-zp1QHQdvj30nCpSUaMtgysMqTscNm25j9tyU2zpj6nZdVm8XMhYKodNNZogQxxIwXT97eahVc61R9zVZQoM4Bz2Alf8tGjPa-zVIybcBZp1F9PeRnZsweQS9zPakO0Ps0AQWk01H2QVFMKEYSxvAv9mGHn1RLJOgmRqdeW3Lm-Uf0GY7Mn6OFV4ClVGAvbSstkXzRvzRT8g6CLpFdzYiccZbxEZmNfPDBFZGk_To1mVvkX7e4DbeNjoCnG2jQlvOaDznIkwZrA_7ntyExMWSjQ9e4_Zw"
},
"contentUrl": "https://smba.trafficmanager.net/amer/f5cedd40-cc83-4a78-8c26-3328f7ceea20/v3/attachments/0-wus-d7-c727ca4fc1e3d4f753a36db52ebc183a/views/original",
"name": "attachment-1c1eef31-8d4d-4185-a9fd-056774c5ef09.png"
}

Attempt to download as per this example: https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/javascript_nodejs/15.handling-attachments/bots/attachmentsBot.js#L83

GET https://smba.trafficmanager.net/amer/f5cedd40-cc83-4a78-8c26-3328f7ceea20/v3/attachments/0-wus-d7-c727ca4fc1e3d4f753a36db52ebc183a/views/original
Headers: Authorization: Bearer {{token}}
Error response: 405Method Not Allowed
```
{
    "error": {
        "code": "BadArgument",
        "message": "API isn't enabled for the bot"
    }
}
```

## To Reproduce
1. Send inline message in teams to the bot (IGNORE THE MESSAGES ITS JUST A SCREENSHOT)
<img width="853" alt="image" src="https://github.com/microsoft/botbuilder-js/assets/5076567/31098315-70e5-429f-8c59-62f7f5076ddf">

## Expected behavior
We should be able to download the image with the given url and token as per example [here](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/javascript_nodejs/15.handling-attachments/bots/attachmentsBot.js#L83) 

## Screenshots
<img width="1131" alt="image" src="https://github.com/microsoft/botbuilder-js/assets/5076567/21c702b1-e22b-432d-8151-6baa95761e50">

**Comment by tracyboehrer** [comment]
I suggest looking at the Teams sample for this and check for differences.  Especially in the Teams manifest used to install the app.  The 405 is coming from that end.

https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-file-upload

**Comment by nodkrot** [comment]
Thank you for fast reply. Just checked the sample and it looks the same as the one I included https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-file-upload/nodejs/services/fileService.js

Regarding the manifest I don't see anything different, we have supportsFiles enabled.

**Comment by Gnoompje** [comment]
We have the exact same issue. It just stopped working, same error: 
```
{
    "error": {
        "code": "BadArgument",
        "message": "API isn't enabled for the bot"
    }
}
```
We have a couple of Teams bots, all have the same problem.

**Comment by avilabiel** [comment]
I got the same error yesterday: `API isn't enabled for the bot`.

**Comment by Gnoompje** [comment]
MS fixed it yesterday evening. For us, it works again like it used to do.

**Comment by nodkrot** [comment]
Confirming its resolved, would be nice if someone could send reason for this outage

**Comment by tracyboehrer** [comment]
Glad to hear.  The root cause wouldn't be known by this team, but if we come about this info I'll share here.

**Comment by tracyboehrer** [comment]
This was related to an incident on the Teams side.  Nothing you (or me) could have done about it.  Though the Teams AI SDK folks are a better source of information about these type issues in Teams.

**Comment by thanhdatdev** [comment]
Does anyone still have this problem?, I received that Teams have fixed it.

**Comment by wsp174212** [comment]
@thanhdatdev  Hi I have this issue on this url: https://smba.trafficmanager.net/jp/.
And https://smba.trafficmanager.net/apac/ works fine for me.
Do you encounter the same issue for JP? Thanks a lot.
