### ISSUE TITLE
Click "Open" my Org Teams App, open Microsoft Copilot Dialogue instead of my Org Teams App

### ISSUE THREAD

**Issue by CatherineLiyuankun** [microsoft/botbuilder-js#4674]
## Versions
What package version of the SDK are you using.  4.22.2
What nodejs version are you using  v18.20.2
What browser version are you using Chrome
What os are you using MacOS

## Describe the bug

The Copilot icon appears next to the app name for all teams app with bot framework in recent days. 
Now click the "Open" button to go to the Copilot app wrongly.
It should open my Org Teams App instead of Microsoft Copilot Dialogue

The screenshot on 5/24 doesn't have the icon.
Some users who cannot see the icon won't meet any issues.
<img width="917" alt="Screenshot 2024-06-07 at 14 41 50" src="https://github.com/microsoft/botbuilder-js/assets/8176214/1fa65c13-ebf4-499c-8e5b-9e3b7ff51301">

## To Reproduce
Key condition:
- This teams app **must be added before**
- The teams app must use the **bot framework**, but doesn't have the bot chat. For example, only use bot framework message extension but don't have bot chat.
    - This means in the Teams app `manifest.json`, which has the `composeExtensions` section, the `botId` is the Azure application resource id which has bound to a bot, but  the `bots` section `manifest.json` is empty

```json
    "bots": [],
    "composeExtensions": [
      {
        "botId": "8fxxxx86-xxxx-xxxx-xxxx-9xxa7xxxxxxx",
        "commands": [
          {
            "id": "webView",
            "description": "Fetch the Web View",
            "title": "Web View",
            "type": "action",
            "fetchTask": yes,
            "context": ["compose"],
          },
        ],
      }
    ],
```

1. "Add" Teams app "Viva Goals"
2. Go to 'Apps', Click "Open" in Teams app "Viva Goals"
3. A popup dialogue shows
    3.1 **[Wrong behavior here]** If your Teams account already has "Copilot", it will show "Copilot" Dialogue 

https://github.com/microsoft/botbuilder-js/assets/8176214/6b9b55bf-9a8a-420c-948e-1886fd83633f

    3.2 **[Wrong behavior here]** If your Teams account doesn't have "Copilot", it will show empty Dialogue and then the error "This app cannot be found" 

https://github.com/microsoft/botbuilder-js/assets/8176214/4bed4568-4389-463a-bd2a-76b3afce49ab

## Expected behavior
Expect behavior should open the  "Viva Goals" app itself.

**Comment by tracyboehrer** [comment]
This really isn't a Bot Framework SDK issue though.  I recommend opening this issue with Teams.

**Comment by CatherineLiyuankun** [comment]
> This really isn't a Bot Framework SDK issue though. I recommend opening this issue with Teams.

Hi, @tracyboehrer which repo does this issue belong to? I found so many repos related with Teams 😢
