### ISSUE TITLE
ShowTypingMiddleware is missing from the JavaScript

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/botbuilder-js#470]
### Versions
4.0.5

### Description
In the C# we have a ShowTypingMiddleware, this is missing from the JavaScript and should be added for parity. Note, it is important that the implementation follows that of the C# around sending the actual Activity because we don't want sending the Typing indicator Activity to flip the Responded flag.

**Comment by cleemullins** [comment]
This exists in Steve's Toybox and should be moved into the primary repo.
