### ISSUE TITLE
AutoSaveStateMiddleware.add() should use apply()

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-js#471]
The current implementation of [AutoSaveStateMiddleware.add()](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/autoSaveStateMiddleware.ts#L67) uses a loop to add passed in objects to the underlying `BotStateSet`. This can be made more efficient by using `apply()` instead. 

[enhancement]

**Comment by stevengum** [comment]
Closing via #497
