### ISSUE TITLE
Attachment's DownloadURL is missing when attaching cloud files

### ISSUE THREAD

**Issue by mutt0-ds** [microsoft/botbuilder-js#4723]
## Versions
- botbuilder@4.22.2
- node v18.19.0
- Microsoft Edge | 127.0.2651.86
- Windows 10 Pro 22H2

## Describe the bug
`TurnContext.activity.attachments` doesn't show the files attached using "Attach Cloud Files". It only works with "Upload from this device"

## To Reproduce
1. Run the EchoBot demo
2. Click on '+' -> Attach File -> Attach Cloud Files
![image](https://github.com/user-attachments/assets/a9352018-ea89-4fb7-88d8-ce5db6cdf293)
3. Log context.activity.attachments
```ts
private test(context: TurnContext): Message {
        const { attachments } = context.activity;
        console.log('attachments', attachments);
```
![image](https://github.com/user-attachments/assets/0e1aed2c-3156-459c-bac8-67aad992618d)

## Expected behavior
To see the downloadUrl in context.activity.attachments just like it happens when uploading the file from the device
![image](https://github.com/user-attachments/assets/cccf6dad-4817-4358-8cb5-12f070c518cd)

**Comment by stevkan** [comment]
@mutt0-ds - Thank you for your patience. Are you still having an issue with this?

Unfortunately, I have been unable to repro the issue. Every attachment I have sent using 'Attach cloud files' shows the file details in the `activity.attachments` property array. For example:

```js
attachments: [
    {
      contentType: 'application/vnd.microsoft.teams.file.download.info',
      content: [Object],
      contentUrl: 'https://XXXXXXXXXXX/personal/XXXXXXXXXXX/Documents/DahliaList.xlsx',
      name: 'DahliaList.xlsx'
    },
    {
      contentType: 'text/html',
      content: '<p>Sending a file</p>'
    }
  ]
```

Can you try capturing the attachment in the activity handler's "on message" handler and see if the result is the same?

**Comment by mutt0-ds** [comment]
Thank you for the assistance!
I have used the handler as the following

```typescript
import { TeamsActivityHandler, TeamsInfo, TurnContext } from 'botbuilder';

export class TeamsBot extends TeamsActivityHandler {
    constructor() {
        super();
        this.onMessage(async (context: TurnContext, next: () => Promise<void>) => {
            console.log(`Received message: ${context.activity.text}`);

            const attachments = context.activity.attachments;
            if (attachments) {
                for (const attachment of attachments) {
                    console.log(`Received attachment: ${JSON.stringify(attachment)}`);
                }
            }
            const response = `Received message: ${context.activity.text}`;
            await context.sendActivity(response);
            await next();
        });
```

And the issue persists. 

![image](https://github.com/user-attachments/assets/2edc1bed-0a11-4f31-9e2f-f3d5e6ea07ce)

![image](https://github.com/user-attachments/assets/b6cfd8d1-afdf-49ef-9d4b-0abd072670d7)

Do I need to change something in my code?

**Comment by stevkan** [comment]
@mutt0-ds - I'll test your code tomorrow and let you know what I find. In the meantime, can you tell me the size of the file you are trying to send?

**Comment by mutt0-ds** [comment]
Much appreciated! In the example, the .png is 80kb and the .pdf is 1MB, I also tried with other files of various sizes during my tests.

**Comment by stevkan** [comment]
@mutt0-ds - I tested your code and it is working without issue for me.

![image](https://github.com/user-attachments/assets/ead6d235-b56c-431e-ad27-b975fcbaad13)

![image](https://github.com/user-attachments/assets/43ece051-f69b-4213-8727-ae32fb9e90b5)

It's possible this is an issue related to your tenant and/or OneDrive. The notes listed in this portion of the Teams [docs](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams#storage) regarding storage may point to a cause. Namely,

> If you don't have SharePoint Online enabled in your tenant, Microsoft Teams users can't always share files in teams. Users in private chat also can't share files because OneDrive for Business (which is tied to the SharePoint license) is required for that functionality.

and

> all compliance rules configured at the tenant level are followed.

I don't know that any of the above is the cause. Only that any of it could be. I would expect an error or warning to appear or the option to send be disabled vs. the attachment just being ignored, but I don't know what the expected functionality should be.

Regardless, at the moment, this is looking less like a BotFramework issue and more like a configuration issue. But let me know what you discover.

I would also recommend posting this issue on Microsoft's Q&A docs [forum](https://learn.microsoft.com/en-us/answers/tags/108/office-teams), tagged with `microsoft-teams`, and see what response you get. If you do so, include details such as it's not reproducible and your code worked fine when tested.

**Comment by mutt0-ds** [comment]
Will do! Thank you so much for your help! I will keep you posted

**Comment by sameretto** [comment]
This needs to be reopened when attaching files that are shared to you so not in your personal it doesn't appear as anything but can be sent.

**Comment by sameretto** [comment]
> Will do! Thank you so much for your help! I will keep you posted

any update on this?
