### ISSUE TITLE
Can not find my bot and configure it anymore, although it exists

### ISSUE THREAD

**Issue by kurbaitis** [microsoft/botbuilder-js#4727]
I have a Teams app with bot.

Recently something happened and I can't find it to edit or view.
I can't see it on https://dev.botframework.com and also on Azure portal.

The bot is working for many our clients. I want to gain its access again for making sure I have control if I need to edit anything within the setup.

What would be the steps to return back the bot?

**Comment by tracyboehrer** [comment]
@kurbaitis Did you resolve this?

**Comment by kurbaitis** [comment]
@tracyboehrer thank you for asking. I'm working with Azure customer support to fix this. We can close the issue I believe.
