### ISSUE TITLE
DCR: TranscriptInfo and PagedResult should be interfaces not classes

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-js#474]
## Versions

version 4.0.5

## Describe the bug
I just noticed that [TranscriptInfo](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/transcriptLogger.ts#L188) and [PagedResults](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/transcriptLogger.ts#L210) are defined as classes and not interfaces. In JavaScript/TypeScript these should definitely be interfaces as they wont serialize/deserialize properly as classes.

To make matters worse... The `MemoryTranscriptStore` is using `TranscriptInfo` [as if it was an interface](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/memoryTranscriptStore.ts#L111) so its not even mapping its values to the class properly.

[bug]

**Comment by yochay** [comment]
@Stevenic what is the impacts on transcripts logging (aka transcript middleware)?

**Comment by stevengum** [comment]
Note to self: mark PR as a breaking change when filing.
