### ISSUE TITLE
Files whose names include a plus sign are not referenced in TeamsActivityHandler.onMessage attachments

### ISSUE THREAD

**Issue by vojtechcahlik-ext44653** [microsoft/botbuilder-js#4750]
## Versions
botbuilder version: 4.22.2
Node version: 18.14.0

## Expected behavior
When a user uploads a file and sends it as part of a message, the `TeamsActivityHandler.onMessage` method should be called and the file should be correctly referenced in `context.activity.attachments`.

## Describe the bug
When the uploaded file contains a plus symbol (e.g. for a file named "document+comments.pdf"), the `TeamsActivityHandler.onMessage` method is called without referencing the file in `context.activity.attachments`. Therefore, the information about a file being included in the message is lost.

Curiously, with the application I'm working on, the file (e.g. "document+comments.pdf") gets uploaded to SharePoint. So it seems that the information about the file is lost somewhere further along the way.

## To Reproduce
1. On your computer, create a local file with a plus symbol in its name (e.g. "document+comments.pdf")
2. In a Teams bot chat, write a message (any text) without sending it yet
3. Attach the file to the message (choose upload from local device)
4. Send the message (with the attached file)
5. Information about the uploaded file will be missing from `context.activity.attachments` in `TeamsActivityHandler.onMessage`

**Comment by tracyboehrer** [comment]
OP should report to Teams Samples or Teams AI SDK repo.
