### ISSUE TITLE
botframework-connector 4.23.0 uses a vulnerable version of semver

### ISSUE THREAD

**Issue by guy-microsoft** [microsoft/botbuilder-js#4754]
botframework-connector 4.23.0 -> browserify-fs 1.0.0 -> levelup 0.18.6 -> semver ~2.3.1 and bl ~0.8.1.

This needs to be addressed asap.

**Comment by tracyboehrer** [comment]
Included in next patch.  Closing since policy requires us to not advertise vulnerabilities.  We get notifications automatically from our builds.
