### ISSUE TITLE
Could not find Connection Setting with name 'Myconnection' - SSO issue in Microsoft Teams bot

### ISSUE THREAD

**Issue by arundhathiMenon** [microsoft/botbuilder-js#4773]
Description:
I am developing a Microsoft Teams bot that integrates Single Sign-On (SSO) using Azure Active Directory OAuth. Despite configuring the OAuth connection as per the documentation, I keep encountering the following error when testing my bot on Teams: Could not find Connection Setting with name 'Myconnection'

I have followed the documentation for setting up OAuth in Azure Active Directory and Azure Bot Service, but it seems like the bot cannot locate the connection.

Expected Behavior:
The bot should initiate the OAuth login and obtain the access token for the user when using Microsoft Teams.

Configuration Details:
Bot Framework SDK: botbuilder
Microsoft Teams
OAuth Connection: Azure Active Directory v2
Authentication Endpoint: https://token.botframework.com/.auth/web/redirect
I am not any environment for tunneling(Is that an issue?)

Bot Code (OAuth Prompt Setup):
this.dialogs.add(
new OAuthPrompt("OAuthPrompt", {
connectionName: process.env.CONNECTION_NAME || "Myconnection",
text: "Please sign in",
title: "Sign in",
timeout: 300000,
})
);

Additional Information:
I have also tried restarting the bot, re-adding the OAuth connection in Azure, and re-registering the app in AAD.

**Comment by dmvtech** [comment]
@arundhathiMenon Under the OAuth connection settings in the bot resource, if you click the `Test Connection` button; does that work?

**Comment by dmvtech** [comment]
Closing due to lack of response.
