### ISSUE TITLE
Can adaptive-expressions npm package be used without MS Bot Framework for commerical purpose?

### ISSUE THREAD

**Issue by bhushanvadgave** [microsoft/botbuilder-js#4779]
The [adaptive-expressions npm package](https://www.npmjs.com/package/adaptive-expressions) offers many prebuilt functions and expression parser/evaluator.

We have a SaaS product that works like a Rule Engine and we would like to use the adaptive-expressions package in it. We do not use MS Bot Framework service. Please let us know if there are any limitations or considerations we should be aware of before using the package for commercial purposes.

**Comment by dmvtech** [comment]
Yes you can. Adaptive Expressions are part of the SDK and supported for use within the supported boundaries and version lifetime of the SDK. That being said, it is unlikely that there will further developments or features added to the package going forward.
