### ISSUE TITLE
Property 'services' does not exist on type 'TurnContext'.

### ISSUE THREAD

**Issue by MarekLani** [Microsoft/botbuilder-js#484]
## Versions
What package version of the SDK are you using.
"botbuilder": "^4.0.6"

## Describe the bug
I am developing custom middleware (using Typescript) and after updating to latest botbuilder packages I am getting error stating that Property 'services' does not exist on type 'TurnContext' when trying to call this line of code: ` context.services.set(this.cacheKey,score);`

## To Reproduce
See above

[bug]

**Comment by benbrown** [comment]
I believe this property has been renamed to `turnState`.

**Comment by Stevenic** [comment]
Yes... as @benbrown  said we renamed `DialogContext.services` to `DialogContext.turnState` as its more descriptive of what its used for.
