### ISSUE TITLE
Add an option to allow bots to acquire tokens from a specified tenant

### ISSUE THREAD

**Issue by mingweiw** [Microsoft/botbuilder-js#504]
This is the same request as this [dotnet issue](https://github.com/Microsoft/botbuilder-dotnet/issues/999).

**Comment by sgellock** [comment]
This issue is a duplicate of https://github.com/Microsoft/botbuilder-dotnet/issues/999.  If that ticket is approved, then a master tracking ticket in botbuilder should be opened to track the various language work
