### ISSUE TITLE
Cannot add botbuilder-ai to node project, EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by sdg9** [Microsoft/botbuilder-js#517]
## Versions
What package version of the SDK are you using.
4.0.6

What nodejs version are you using
Attempted both 8.12.0 and 10.6.0

What browser version are you using
n/a (node server)

What os are you using
Attempted on both Windows 10 and Mac OS 10.13.6

## Describe the bug
When running `yarn add botbuilder-ai` the following error is encountered

> error An unexpected error occurred: "https://registry.yarnpkg.com/botbuilder-ai/-/botbuilder-ai-4.0.6.tgz: EISDIR: illegal operation on a directory, open '/Users/<myID>/Library/Caches/Yarn/v1/npm-botbuilder-ai-4.0.6-fe8914b56a8755dfc4ad0c3f739d04b2726dfc64/'"

## To Reproduce
1. `mkdir newProject`
2. `cd newProject`
3. `npm init`
4. Click `enter` through all the `npm init` prompts
5. `yarn add botbuilder-ai`
6. See error

## Expected behavior
botbuilder-ai should not error out when adding to the project

## Screenshots

![image](https://user-images.githubusercontent.com/3091143/46446545-7cc73880-c742-11e8-88fc-8d69c6422c86.png)

## Additional context

[bug]

**Comment by sdg9** [comment]
Seems to be a conflict with some other modules.  If I clear out my package.json of all other dependencies and devDependencies I can add botbuilder-ai, then if I add everything else it works.  I'll keep poking around to see if I can find the conflict, but I confirmed on two separate machines (windows and mac) that a fresh clone of my project can't add `botbuilder-ai` as a new dependency without error (4.0.0-preview1.2 works)

**Comment by sdg9** [comment]
Found workaround until new package is published.

Per https://www.npmjs.com/package/botbuilder-ai

> npm config set registry https://botbuilder.myget.org/F/botbuilder-v4-js-daily/npm/

This makes it so when I add the package it works

**Comment by sdg9** [comment]
I will note another team using this did not run into a problem with this, although everyone on our team spanning windows & mac did (tried on 4 machines, mix of npm, yarn, new project, and existing)

**Comment by sgellock** [comment]
Let's make sure we do a yarn install of the package

**Comment by sgellock** [comment]
@sdg9, using yarn v1.12.1 i am able to 'yarn install botbuilder-ai' without error.
