### ISSUE TITLE
Yeoman generator creates incompatible LUIS model

### ISSUE THREAD

**Issue by pmc-a** [Microsoft/botbuilder-js#520]
## Versions
What package version of the SDK are you using: **v4.0.6**
What nodejs version are you using: **v8.11.3**
What browser version are you using: **Chrome 69.0.3497.100**
What os are you using: **macOS - High Sierra v10.13.6**

Yeoman version: v2.0.5

## Describe the bug
When using the Yeoman generator and selecting the `Basic` template, the generator successfully creates the bot. 

However, inside the `cognitiveModels/` dir, the model that is created has the extension `.luis`. This file type is incompatible when attempting to create the bot on LUIS.ai - it is expecting a `.json` file extension. 

Changing the extension to be `.json` solves the issue.

LUIS doesn't give an error message feedback to the user, it simply just doesn't allow the user to continue and upload the file.

## To Reproduce
1. Generate new bot using Yeoman generator -> `yo botbuilder`
2. Select the `basic` template when prompted
3. Once generation has completed, attempt to upload the `basicBot.luis` file to LUIS.ai
4. User cannot continue the creation of a new bot - with no error message explaining why.

## Expected behavior
When I upload the the `cognitiveModels/basicBot.json` file, it should create my model on LUIS.ai.

## Screenshots

**LUIS.ai not allowing user to continue:**
<img width="575" alt="disabled-button-luis" src="https://user-images.githubusercontent.com/13116189/46570421-eb331300-c95b-11e8-8e1d-11c3326a3716.png">

## Additional context
N/A

[bug]

**Comment by benbrown** [comment]
This pertains to this file:
https://github.com/Microsoft/BotBuilder-Samples/blob/master/generators/generator-botbuilder/generators/app/templates/basic/cognitiveModels/basicBot.luis

**Comment by JasonSowers** [comment]
@daveta do you have another version of this file?

**Comment by JasonSowers** [comment]
Confirming I am seeing the same behavior

**Comment by JasonSowers** [comment]
@pmc-a If you rename the file from basicBot.luis => basincBot.json  it will work.  The model was built under the assumption that people would be using the command line tools to upload the model.  In this situation it would accept the .luis extension.  If you are going to use the luis.ai UI to upload the model just change the name as the portal will only allow .json files.
