### ISSUE TITLE
optimizeWrites required by StorageMiddleware

### ISSUE THREAD

**Issue by LarsLiden** [Microsoft/botbuilder-js#53]
Example is not valid:
bot.use(new FileStorage({
      path: path.join(__dirname, 'storage')
 }));

Fails because not passed "optimizeWrites" in FileStorageSettings (which inherits from StorageSettings)
 
Do you want optimizeWrite to be optional in StorageSettings and given the value of true if it isn't set?

**Comment by Stevenic** [comment]
It should have been optional. I have a [pull request](https://github.com/Microsoft/botbuilder-js/pull/55) with a fix if you wouldn't mind reviewing.  I'll go ahead and publish an updated version of botbuilder to npm as well.
