### ISSUE TITLE
Cannot createConversation with my own reference

### ISSUE THREAD

**Issue by mecampbellsoup** [Microsoft/botbuilder-js#531]
## Versions
What package version of the SDK are you using. `4.x`
What nodejs version are you using `8.12.0`
What browser version are you using `N/A`
What os are you using `Mac OS`

## Describe the bug

I am not able to use the [`createConversation`](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/botFrameworkAdapter.ts#L243) SDK function from the `BotbuilderFrameworkAdapter`. 

Here is the code I'm running:
```js
let contextHelper = new ContextHelper(turnContext)
let directMessageReference = contextHelper.buildDirectMessageReference(user.name)
await this.consoleLogAndSendActivity(turnContext, directMessageReference, 'directMessageReference')

// If we have already persisted the current conversation into this.conversationState
// then we continue that conversation; otherwise we create a new one.
if (storageKey.includes(conversationId)) {
    await this.adapter.createConversation(directMessageReference, async (proactiveTurnContext) => {
        await proactiveTurnContext.sendActivity(`(2) Hello (in private), new user!`)
    })
}
```

However, `this.adapter.createConversation` (where `this.adapter` is the BotFrameworkAdapter passed in from `app.js`) fails with `[onTurnError]: Error: Mandatory 'members' property is missing`.

## Expected behavior

I expect to be able to create a new conversation/DM a user for the first time programatically via the `createConversation` bot framework SDK.

**Comment by mecampbellsoup** [comment]
I'm pretty sure the issue is that the `parameters` object [here](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/botFrameworkAdapter.ts#L248) is not being constructed properly, i.e. it is missing required parameters for the REST API endpoint to which it sends the `POST` request.

## Steps to reproduce

### Add bot to an existing Skype chat

![image](https://user-images.githubusercontent.com/2043821/46883699-de616400-ce20-11e8-8852-ab9273515cde.png)

![image](https://user-images.githubusercontent.com/2043821/46883729-f0430700-ce20-11e8-932d-9a52bfac0d6e.png)

### Our bot then tries to invoke `BotFrameworkAdapter.createConversation()`

However the function encounters an error regarding missing a required `members` parameter.

![image](https://user-images.githubusercontent.com/2043821/46883771-0f419900-ce21-11e8-8d76-0fb22b69d489.png)

**Comment by benbrown** [comment]
Just adding this for clarity: This pertains to the Skype channel

**Comment by JasonSowers** [comment]
@mecampbellsoup thanks for reporting this, I am looking into it.  If you feel you have a fix in mind please submit a pull request.

**Comment by nyxsys** [comment]
Currently looking into this, could you post your implementation of the method `buildDirectMessageReference` if possible?

**Comment by mecampbellsoup** [comment]
```js
class ContextHepler {
    constructor(activityId) {
        this.activityId = activityId
    }

    buildDirectMessageReference(userId, userName) {
        return({
            activityId: this.activityId,
            user: {
                id: userId,
                name: userName
            },
            bot: {
                id: process.env.BOT_ID,
                name: process.env.BOT_NAME
            },
            channelId: 'skype',
            serviceUrl: 'https://smba.trafficmanager.net/apis/'
        })
    }
}

module.exports = ContextHepler
```

I ended up using the connector client to make API requests more directly: https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botframework-connector/src/generated/operations/conversations.ts#L1475

**Comment by mecampbellsoup** [comment]
I think my PR resolved it more or less though... it seems like a conversation param-mapping issue from `conversations.ts` <-> `botframework-adapter.ts`.

**Comment by nyxsys** [comment]
Ah, yes I think that does seem to be the case, I was having a bit of trouble figuring out where your issue could be with that additional parameter included. Going to close this issue now, thank you for contributing your fix.

**Comment by mecampbellsoup** [comment]
You're welcome man, thanks to you guys for the nice framework!
