### ISSUE TITLE
Does ILuisService need getEndpoint()?

### ISSUE THREAD

**Issue by benbrown** [Microsoft/botbuilder-js#546]
## Describe the bug

The [interface declaration of ILuisService](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botframework-config/src/schema.ts#L183) does not include the getEndpoint() method that is included in the [LuisService implementation](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botframework-config/src/models/luisService.ts#L14).

If a developer casts to an ILuisService, this will cause issues with Typescript complaining that getEndpoint is not defined.  Is getEndpoint actually a required member of this method? Should we add it to the interface?

**Comment by justinwilaby** [comment]
This should be an accessor and not a function:

```js
public get endpoint() {
  ...
}
```
