### ISSUE TITLE
nodejs OAuthPrompt : No reply address is registered for the application 

### ISSUE THREAD

**Issue by jonathanhotono** [Microsoft/botbuilder-js#565]
## Versions
What package version of the SDK are you using. v4
What nodejs version are you using v8.12.0
What browser version are you using edge
What os are you using win10

## Describe the bug
OAuthPrompt doesn't seem to handle the return url correctly 
![image](https://user-images.githubusercontent.com/6864547/47397317-70029700-d77a-11e8-902a-1c2812932f68.png)

## To Reproduce
1. Clone https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/24.bot-authentication-msgraph
2. Create the AADV2 token and configure the OAuth on bot as per documentation instruction
3. Test in emulator

I'm not entirely sure whether I made a wrong step here, but I kept on getting the "No Reply Address is registered for the application". Or do I need to create a restify endpoint to handle the oauthcallback? Any guidance on this would be much appreciated.

Thanks

**Comment by JasonSowers** [comment]
In your AAD app did you put in a reply url?

**Comment by JasonSowers** [comment]
@jwiley84 for awareness

**Comment by jonathanhotono** [comment]
@JasonSowers its working fine on AADV1, I haven't checked V2 yet again.
