### ISSUE TITLE
Analytics Blade doesn’t track Skype for business.

### ISSUE THREAD

**Issue by nyxsys** [Microsoft/botbuilder-js#568]
This is unlikely a node-specific issue, but I'm moving it here from services (https://github.com/Microsoft/BotFramework-Services/issues/13) due to this being an easier location for tracking and reporting: 

Original:

I have bots working with the Bot Framework v3 and v4 through Web, Skype for Business, MS Teams and Slack. In the Azure Portal, in the Bot service I go to analytics and see usage data but not for Skype for Business. Also when I query for custom events in App Insights Analytics I only see entries for the other channels.
Is there a problem with that channel? Is there something that has to be done in order to enable it? I didn't see any mention about that in the documentation, and interestingly enough the example screenshot contains a lot of channels but not Skype for business, odd being a Microsoft documentation.

**Comment by yochay** [comment]
The right place for such an issue is the [Microsoft/BotFramework-Services](https://github.com/Microsoft/BotFramework-Services) repo. Ping @dandriscoll for updates on that repo. 

Closing this one.
