### ISSUE TITLE
Update MSRest Tool Chain

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-js#577]
1. The version of ms-rest-js we use is 0.2.8. Current is 1.0.455. 

2. Sync to latest version of autorest.typescript. 

3. Add code generation step to the build, to avoid checking in generated code. 

Deep dive for other packages in the tool chain that need to be updated.

**Comment by stevengum** [comment]
In a tangential manner, we have out of date dependencies or non-synced in places such as [`tools/`](https://github.com/Microsoft/botbuilder-js/tree/master/tools/package.json) and [`transcripts/`](https://github.com/Microsoft/botbuilder-js/blob/master/transcripts/package.json).

"non-synced" meaning the dependencies in these folders don't match dependencies that are either globally installed or hoisted in the build process.

Additionally, there are a large number of dependencies in the `tools/package.json` that aren't used, namely the `azure` packages.

Staying at an older version of npm may have (somehow) shielded us from some of the changes that have been added to PR #575, e.g. the updates to the "set-dependency-versions" script; but at a superficial level the changes to the script should have been performed quite some time ago.

**Comment by stevengum** [comment]
Fixed via #601
