### ISSUE TITLE
language translator not working with botbuilder-ai

### ISSUE THREAD

**Issue by deepanigi** [Microsoft/botbuilder-js#578]
Hi All,

I am using version 4 sdk and building bot using nodejs. I am using the QnAMaker, LuisRecognizer library from botbuilder-ai. I want to use language translation library by refering to the steps in the following link.I see that language translation ins only included in the `npm install --save botbuilder-ai@preview
` built but when i try to install it over my existing `botbuilder-ai` the bot doesnot complaint about transalation instance but the other luis part of the bot is broken. Is there other way to use langauge transalator ? I also tried to manully import the translation library files into the botbuilder-ai still does not work. Is there solution for this issue ?

[https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-how-to-translation?view=azure-bot-service-4.0&tabs=jsrefs%2Cjssetuptranslate%2Ccshelp%2Cjstranslateback%2Ccschangelanguage%2Ccslanguageluis%2Ccsbypass%2Ccstranslation](url)
> const { QnAMaker, LuisRecognizer, LanguageTranslator, LocaleConverter } = require('botbuilder-ai')

**Comment by sgellock** [comment]
Please look at the following sample. 
https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/17.multilingual-conversations

**Comment by deepanigi** [comment]
> Please look at the following sample.
> https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/17.multilingual-conversations
> 
> Also, please run on the latest bits, not the preview bits.

Thanks , I had seen the sample but in think, the inbuilt language translator is not used but only custom built by calling the api directly . Does it mean the LanguageTranslator library is not supported anymore?

**Comment by sgellock** [comment]
Yes.  I’m afraid the sample is the only way going forward.  The middleware option was pulled out of the preview and not shipped as part of the v4 release.
