### ISSUE TITLE
DCR: Add ability to create a ConversationReference from a TurnContext + ResourceResponse

### ISSUE THREAD

**Issue by benbrown** [Microsoft/botbuilder-js#586]
SendActivities returns an array of ResourceResponses.

These ResourceResponses contain the activity id, which is a key value needed to call updateActivity or deleteActivity in the future. However, ResourceResponse does not necessarily contain all of the information required to construct a ConversationReference needed to actually call these methods.

Since the type of messages that will be deleted or updated are most likely to be those sent by the bot itself, we need to provide an easy to use method that takes a ResourceResponse returned from sendActivity and combines it with a TurnContext to create a reusable (and data-complete) ConversationReference.

**Comment by yochay** [comment]
@benbrown , please ping @johnataylor  once you are done with this.

**Comment by yochay** [comment]
This issue was moved to Microsoft/BotBuilder#5128
