### ISSUE TITLE
botframework-connector contains Node-only Dependencies

### ISSUE THREAD

**Issue by justinwilaby** [Microsoft/botbuilder-js#600]
The dependency `request` is a very heavy node-only dependency that prevents this package from being used in a web client. It can be easily replaced by `node-fetch` or some other `fetch`-like polyfill for the 2 calls that is it used for and would eliminate a great number of dependencies from the package.

**Comment by stevengum** [comment]
Justin and I talked this afternoon. The key takeaways is that `request` makes the package Node specific, that `request` is only used in one http request and that request is a very heavy dependency.  There may be other Node specific dependencies inside of the library, but request could be swapped out for a more lightweight way of conducting http requests in a pollyfilled manner, which would allow the library to be used in the browser.
