### ISSUE TITLE
Initial state for prompts

### ISSUE THREAD

**Issue by shmuelgutman** [Microsoft/botbuilder-js#607]
Is it make sense to have the option to send "initla state" to prompt?
Something like:
```
step.prompt('dialogId', {initialState: {foo: 'bar'}/*More options for prompt...*/})
```
and then here:
https://github.com/Microsoft/botbuilder-js/blob/16f47826ec7fa960b9bb89889b84d222497a54b1/libraries/botbuilder-dialogs/src/prompts/activityPrompt.ts#L45

could be something like `state.state = options.initialState || {};

Thanks

**Comment by sgellock** [comment]
@shmuelgutman could you elaborate a bit on the scenario you're looking to support?

**Comment by sgellock** [comment]
close due to inactivity.
