### ISSUE TITLE
Cryptiles dependency needs update

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-js#608]
The JS SDK needs to update to Cryptiles >4.1.2 to resolve known vulnerabilities. 

https://github.com/Microsoft/BotBuilder-js/network/alerts

**Comment by carlosscastro** [comment]
This dependency is an indirect dependency: botbuilder -> request -> hawk -> cryptiles. As such, we cannot control the cryptiles version. Filing issues against the repositories for now requesting to upgrade cryptiles.

**Comment by benbrown** [comment]
@carlosscastro didn't you finish this?

**Comment by carlosscastro** [comment]
@stevengum Are we going to remove request from this repo?

In the meantime, moving to 4.3 as we cannot do anything directly, as the dependency is indirect.

I filed issues against request and hawk to try to update the dependency:

[Ticket in request repo](https://github.com/requests/requests/issues/4875)
[Ticket in hawk repo](https://github.com/hueniverse/hawk/issues/249)

**Comment by benbrown** [comment]
I just checked the status of @carlosscastro's tickets, and both are closed and marked as essentially wontfix.

However, we should be able to fix this by updating our version of `request`

**Comment by carlosscastro** [comment]
Thanks @benbrown yes they weren't motivated enough. I'll try updating tomorrow verify that it fixes it.

**Comment by carlosscastro** [comment]
Since we upgraded to request 2.88 this problem is gone.
