### ISSUE TITLE
NO_KEY error messages incorrectly refer to "context.request"

### ISSUE THREAD

**Issue by stevengum** [Microsoft/botbuilder-js#610]
## Versions
All stable versions.

## Describe the bug
Error messages in the `State` classes incorrectly reference `"context.request"`.

## To Reproduce
1. Go to UserState, ConversationState or PrivateConversationState.
2. Examine the `NO_KEY` value and see references to "context.request". For example:
```ts
const NO_KEY: string = `UserState: channelId and/or conversation missing from context.request.`;
```

## Expected behavior
Should refer to `context.activity` instead.

[bug]

**Comment by stevengum** [comment]
The `getStorageKey` method is public and can be easily overwritten with a user's own specific storage key generation logic. In C# the `getStorageKey` method is a protected override, so users can also provide their own key logic.

While our implementation for the `getStorageKey` method will not trigger the `NO_KEY` error message, our default implementation of the StorageKeyFactory will check to see if the key exists before attempting to do any reads or writes.

**Comment by v-kydela** [comment]
Thanks Steven, I hadn't thought about overriding `getStorageKey`. If that's the only way for the `NO_KEY` message to show up, shouldn't the message reflect that? Anything could be in `getStorageKey` and it might have nothing to do with `context.activity`. Perhaps the message should be `Overridden UserState.getStorageKey method did not return a key`
