### ISSUE TITLE
Role instead of entity type as property name when using patterns with composite entities

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/botbuilder-js#613]
## Versions
Microsoft.bot.builder.ai
4.1.0

## Describe the bug
When using patterns with composite entities the property name in the result should be the role defined in the pattern. The problem is here:

https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-ai/src/luisRecognizer.ts#L492

In the following compositeEntity.parentType should be 
this.getNormalizedEntityName(compositeEntityMetadata)

```
  this.addProperty(entitiesAndMetadata, this.getNormalizedEntityName(compositeEntityMetadata), childrenEntites);

  if (verbose) {
    this.addProperty(entitiesAndMetadata.$instance, this.getNormalizedEntityName(compositeEntityMetadata), childrenEntitiesMetadata);
  }
```

and please remember to add a new test.

**Comment by sgellock** [comment]
Mental note.  Don't listen to Johnny

**Comment by johnataylor** [comment]
Closing this time with a link to the PR.
https://github.com/Microsoft/botbuilder-js/pull/622
