### ISSUE TITLE
Make botbuilder-ai browser compatible

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#620]
**Is your feature request related to a problem? Please describe.**
botbuilder-ai has a dependency on request which is only used in the QnAMaker class. Additionally, there exists the azure-sdk-for-js repo which contains an isomorphic luis runtime client which can be used instead of the current Node.js-specific client. We can use `node-fetch` instead of `request`, and `@azure/cognitiveservices-luis-runtime` instead of `azure-cognitiveservices-luis-runtime` to remove the Node.js-specific dependencies.

(Related to #600)

[enhancement]

**Comment by stevengum** [comment]
Additionally, it looks like there are some Node.js libraries like `html-entities` that would need to be replaced.

**Comment by cleemullins** [comment]
@juanar Any update on this?

**Comment by gabog** [comment]
@JuanAr Any update on this?

**Comment by JuanAr** [comment]
@cleemullins @gabog we still haven't had the chance to start digging into this one. However, we realized #818 is related to this one and should be tackled first.
As a ballpark ETA, we are going to fix this issue early next week.

**Comment by stevengum** [comment]
Fixed with #914
