### ISSUE TITLE
Send Typing Indicator Helper

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/botbuilder-js#621]
**Send Typing Indicator Helper**
In the v3 SDK and in early iterations of the v4 SDK, there was a simple utility that allowed developers to have their bot send typing indicators. Albeit a minor user experience feature, it gives the end user of the bot the sense that they're communicating with a real agent that's actively typing. 

**Describe the solution you'd like**
In the current iteration of the SDK there appears to be a ```showTypingMiddleware``` which sends typing indicators for every outgoing message. While this may be valuable for some bots, I'd like to see a solution that allows the developer to send typing messages themselves. 

**Additional context**
While digging around the [source code](https://github.com/Microsoft/botbuilder-js/blob/c472cb4b34e461b48807f9ef18b678def9816209/libraries/botbuilder-core/src/turnContext.ts) I found this comment that demonstrates how to send a typing indicator. It both seems like too much code, which could easily be abstracted into a helper function, and doesn't seem to work: 

```
     * // Send a typing indicator without going through a middleware listeners.
     * const reference = TurnContext.getConversationReference(context.activity);
     * const activity = TurnContext.applyConversationReference({ type: 'typing' }, reference);
     * await context.adapter.sendActivities([activity]);
```

I also noted [this bug](https://github.com/Microsoft/botbuilder-js/issues/290), but was not able to use the resolution to send the indicator: 

```
await dc.context.sendActivity({ type: ActivityTypes.Typing });
```

**Note**: I'm currently testing the typing in the emulator. It's entirely possible that the above code works in other channels, and that this is an emulator bug

[enhancement]

**Comment by Ric01** [comment]
Typing indicator is a very important feature for improving ux experience. SDKv3 was way easier than SDKv4, i couldnt make it work for SDKv4. Saw some examples for the dotnet sdk but none for javascript. Love to hear improvements on this topic

**Comment by Ric01** [comment]
Recently checked the documentation and find out about the SendActivities method.
Tried it and it worked!, in case someone writing on javascript runs with the same issue.

await context.sendActivities([
     *    { type: 'typing' },
     *    { type: 'delay', value: 2000 },
     *    { type: 'message', text: 'Hello... How are you?' }
     * ]);

**Comment by hinojosachapel** [comment]
> Recently checked the documentation and find out about the SendActivities method.
> Tried it and it worked!, in case someone writing on javascript runs with the same issue.
> 
> await context.sendActivities([
> * { type: 'typing' },
> * { type: 'delay', value: 2000 },
> * { type: 'message', text: 'Hello... How are you?' }
> * ]);

Great! Thanks! Your solution worked for me, though I introduced a little modification:

async sendTyping(context) {
&nbsp;&nbsp;&nbsp;&nbsp;await context.sendActivities([
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{ type: 'typing' },
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{ type: 'delay', value: 2000 }
&nbsp;&nbsp;&nbsp;&nbsp;]);
}

**Comment by sgellock** [comment]
We've talked this over, and I don't see us adding this, given the view lines of code above to implement the behavior.

**Comment by sanjeevgaut** [comment]
Hi It worked for me also in localhost/emulator. but when i deployed in azure it is not working. 
i can see there is delay in the response but typing is not coming

**Comment by NereaCabiedasMoreno** [comment]
(node:25523) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sendActivities' of undefined
    at MainDialog.sendTyping (/var/www/vhosts/webciudadreal.es/httpdocs/enuntio/dialogs/mainDialog.js:314:17)
    at MainDialog.actStep (/var/www/vhosts/webciudadreal.es/httpdocs/enuntio/dialogs/mainDialog.js:193:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:25523) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25523) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sanjeevgaut** [comment]
This is for node js. It should work..
 
await step.context.sendActivities([
                        { type: 'typing' },
                        { type: 'delay', value: 2000 }

                    ]);

**Comment by NereaCabiedasMoreno** [comment]
yes, that work well, thanks!!, but how to add Typing Indicator whenever BOT have received a message and is processing? @sanjeevgaut thanks!!

**Comment by sanjeevgaut** [comment]
> yes, that work well, thanks!!, but how to add Typing Indicator whenever BOT have received a message and is processing? @sanjeevgaut thanks!!
Just add await step.context.sendActivity({ type: ActivityTypes.Typing }); in the next step.
or when any processing is hepening add below 
 step.context.sendActivity({ type: ActivityTypes.Typing });

it should work.
