### ISSUE TITLE
METRICS: P0: Ensure tracing telemetry being logged in Application Insights Trace

### ISSUE THREAD

**Issue by daveta** [Microsoft/botbuilder-js#624]
## Title: METRICS: P0: Ensure tracing telemetry being logged in Application Insights Trace

Application Insights has ability to intercept ILogger events (in C#), find out equivalent in NodeJS - make sure this is turned on for all samples.  Add to documentation.

**Comment by benbrown** [comment]
Theoretically this means intercepting messages sent to console.*

**Comment by daveta** [comment]
@benbrown: Haven't tested, but I think the way to enable the console hook is 
`.setAutoCollectConsole(true)`.  

Here's the blurb:
https://github.com/Microsoft/ApplicationInsights-node.js/#configuration

If you agree, we can probably close this.
I think this matches reasonably close what we're doing on C#:

```js
appInsights.setup(appInsightsSettings.instrumentationKey)
    .setAutoDependencyCorrelation(true)
    .setAutoCollectRequests(true)
    .setAutoCollectPerformance(true)
    .setAutoCollectExceptions(true)
    .setAutoCollectDependencies(true)
    .setAutoCollectConsole(true)
    .start();
```

**Comment by benbrown** [comment]
Looks like we need it to be `.setAutoCollectConsole(true, true)` to get the actual console.logs, which I believe is what we're trying to do. 

To be clear, this would capture ALL debug/trace output that would normally go to the terminal.

**Comment by benbrown** [comment]
OK I can confirm that calling `.setAutoCollectConsole(true, true)` will capture all console.logs and send them to Applicaiton Insights as TRACE events.
