### ISSUE TITLE
Switch Lib Output from CommonJS to UMD

### ISSUE THREAD

**Issue by justinwilaby** [Microsoft/botbuilder-js#632]
Currently, all packages are set to use `commonjs` in the `tsconfig.json` as the output. While this is ok when standardizing for NodeJS, it is less optimal for web-based consumers since CommonJS is a non-ESM format and often presents interoperability issues (`import` vs `require`) and often eliminates the ability to use tree-shaking to minimize file size.

Changing output to `U`niversal `M`odule `D`efinition is better suited for NodeJS and Web consumers.

**Comment by sgellock** [comment]
@cleemullins wanted to know if "one would assume this?"  see me for more details.

**Comment by benbrown** [comment]
Seems like switching to UMD breaks dependencies, as Node can't import UMD style modules, so fails to compile.

@justinwilaby suggests that we might be able to compile _both_ styles, allowing es6 users to pull in the more modern version. however, this would require a pretty substantial change and would probably be breaking.

**Comment by benbrown** [comment]
Looks like we won't be able to do this now without substantial changes.  Closing this ticket.
