### ISSUE TITLE
ActivityId for outgoing activities

### ISSUE THREAD

**Issue by shmuelgutman** [Microsoft/botbuilder-js#635]
Outgoing activities don't have Ids attached to them
Is it make sense to attach the ids from the `ResourceResponse[]` here:
https://github.com/Microsoft/botbuilder-js/blob/314e1c5dab621d59956a540643a437f15893dead/libraries/botbuilder-core/src/turnContext.ts#L202-L207

Something like this:
```javascript
 .then((responses: ResourceResponse[]) => { 
      responses.forEach((response, index) => {
          output[index].id = response.id
      })
     // Set responded flag 
     if (sentNonTraceActivity) { this.responded = true; } 
  
     return responses; 
 }); 
```

**Comment by vishwacsena** [comment]
@shmuelgutman - can you clarify what scenario or issue you believe this helps address?

**Comment by shmuelgutman** [comment]
I have a transcript-logger (like the "official" BlobTranscript but for S3), the key of each log record is consists of the `activity.id`, of course, I can get work around it by generating some unique id or something like this, but I wonder, if for incoming activities I have ids why not for outgoing?
I understand that the id is not available immediately, but as soon as we get the id from the adapter i believe we can set it and then give the option for developers to later use it in `onActivitySent` like this:

```
        context.onSendActivities(async (ctx, activities, next) => {
           //here we dont have the id availabels yet
            const responses: ResourceResponse[] = await next();
            // here we can use the ids 
            return responses;
        });
```

**Comment by CoHealer** [comment]
@shmuelgutman, the activity ID is not unique and can be reused for things like update and delete actions.  It seems generating your own IDs may be a better solution for what you're trying to accomplish.

**Comment by shmuelgutman** [comment]
@CoHealer, do you know for sure that the IDs for update or delete activities are the same as the original activity? or maybe they're considered as different activities (with just a reference to the original activity)?
It's very interesting to know how directline-api handling it...
