### ISSUE TITLE
qnamaker trace activity is not sent on generateAnswer calls off the qna recognizer

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-js#637]
## Describe the bug
Trace activity should be emitted by the SDK (so emulator can render appropriate inspectors) when the generateAnswer method is called. At the moment the JS SDK only sends trace activity on answer() call. .

## To Reproduce
1. Get set up with 51.cafe-bot sample for nodejs
2. Run the bot (with the QnA and LUIS services configured)
3. Connect to the bot using the V4 Emulator
4. Send 'what are your locations'
5. The log section in emulator does not show any QnA trace activity

## Expected behavior
SDK generates trace activity and emulator can show it in logs and when i click on the QnA trace activity, emulator renders the qna inspector.

[bug]

**Comment by Zerryth** [comment]
Good news: got the QnAMaker Trace in generateAnswer()
Bad news: the info on the trace is fairly unhelpful, as it doesn't display the actual results of qna service

Currently investigating if this is an issue in the SDK or if it's on the emulator end

### Compare
**QnAMaker Trace** - not much shown in results
![image](https://user-images.githubusercontent.com/35248895/48744492-53903800-ec1c-11e8-9ee4-1ab509a933c6.png)

vs.

**Luis Trace** - luis results (intents, entities, scores, etc.) actually displayed
![image](https://user-images.githubusercontent.com/35248895/48744507-5f7bfa00-ec1c-11e8-8e4b-79cad40ecf18.png)

**Comment by CoHealer** [comment]
Closing as addressed with PR. Reopen in event of PR rollback.

**Comment by stevengum** [comment]
Reopening as we track work by open issue, not PR. 

Please check with @sgellock or @cleemullins if there are any questions.

**Comment by CoHealer** [comment]
Ack &  thx. Will follow up post build release.
