### ISSUE TITLE
CardAction requires channelData property

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/botbuilder-js#639]
## Versions
What package version of the SDK are you using.
4.1.5

What nodejs version are you using
v10.13.0

What os are you using
Windows

## Describe the bug
CardAction interface requires unexplained ```channelData``` property. [06.using-cards sample](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/06.using-cards/bot.js) creates CardActions without channelData, implying that it should not be required: 
```
            CardFactory.actions([
                {
                    type: 'openUrl',
                    title: 'Get started',
                    value: 'https://docs.microsoft.com/en-us/azure/bot-service/'
                }
```

## To Reproduce
Follow [06.using-cards sample](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/06.using-cards/bot.js) sample to create a HeroCard with a card action. Don't pass in ```channelData```.

## Expected behavior
Card should not require unnecessary properties. If there is a reason for this property, samples/docs should use it and explain it. 

## Screenshots
![image](https://user-images.githubusercontent.com/3891951/48573485-30ceee00-e8c1-11e8-84cc-e00f664be416.png)

## Additional context
I'm developing in TypeScript, so I have to adhere to more rules. This is a bug nonetheless. 

[bug]

**Comment by stevengum** [comment]
I'm pretty sure that we need to make it optional, similar to what we do on the Activity interface. This is would probably be fixed on this [line](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/swagger/model_fixes.js#L14).

**Comment by stevengum** [comment]
Reopening this as we need to regenerate the schema libraries for this fix to be in. 

@sgellock, I can do a one line (two line?) fix to just add the `?` where necessary to unblock for 4.2.

For later/4.3 we should also consider a bump of autorest and then regenerating the libraries to get the new azure namespaced "goodies".

**Comment by stevengum** [comment]
For public record, we'll be regenerating the the connector and schema libraries for 4.2, no manual changes!

**Comment by sgellock** [comment]
Let’s decide if we are picking up the lastest ms-rest-js or staying pinned to the current version we are using

**Comment by stevengum** [comment]
@sgellock, @stevenic and I decided to stay with the versions of autorest used to create our current bits. This is so that we introduce as little changes in the code base right before we release 4.2. 

I spoke with @cleemullins as well to make sure we're all on board and have created #665 to make sure that we pick up the latest autorest bits for 4.3.

In #666, we address this issue as well as the issue Shahin brought up regarding the `aadObjectId` property (Microsoft/BotBuilder#5187)

**Comment by sgellock** [comment]
That seems right.  Good call!  Thanks Steven
