### ISSUE TITLE
Use of depreciated methods causing Warnings during build and tests

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-js#640]
## Describe the bug
The tests run as part of CI/CD via Travis-CI show the following warning:

```
EncryptionTests
    ✓ EncryptDecrypt
(node:4467) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

## Expected behavior
I would expect the JS SDK to use one of the recommended methods.

**Comment by justinwilaby** [comment]
After a quick search, it looks like uses of `new Buffer()` can be safely swapped with `Buffer.from()`
