### ISSUE TITLE
Unable to continue dialog when using continueConversation

### ISSUE THREAD

**Issue by ivarkallejarv** [Microsoft/botbuilder-js#641]
**Is your feature request related to a problem? Please describe.**

1. I create the bot
2. I use continueConversation to change adressee
3. I create a dialogContext, inside the continueConversation
4. User answers to the question
5. I can't continue the dialog, because the dialogContext is gone
P.S. I can't save the dialogContext inside continueConversation, because I need it with the answer.

**Describe the solution you'd like**
Something similar to v3, where it was easier to handle dialogs and changing addressees.

[enhancement]

**Comment by dmvtech** [comment]
@ivarkallejarv , can you share any sample code you might have so that we can better understand the scenario and how you are attempting to accomplish? Also, I want to confirm that by addressee, you are meaning separate, specific users?

**Comment by ivarkallejarv** [comment]
@dmvtech 
1. To start a conversation with someone, I have to use continueConversation
2. When I want that conversation to contain a dialog, then I have to create a dialog context
3. Because I have to give the turnContext to create a context, I create it inside the proxy

All of these steps are illustrated by the following snippet:
```
await this.adapter.continueConversation(this.reference, async (proactiveTurnContext) => {
  const dc = await this.dialogs.createContext(proactiveTurnContext);
  await dc.beginDialog('dialog');
});
```
Now, if I wanted to access the dialog outside this proxy, I thought that I could assign it to a variable that I create outside.

```
public dcTracker;

And inside the continueConversation, I do:
this.dcTracker = dc;
```

But when I try to access `this.dcTracker`, I get an error => ``` Proxy has been revoked```

**Comment by dmvtech** [comment]
@ivarkallejarv Thank you. I am looking into this.

**Comment by CoHealer** [comment]
@dmvtech, any update?

**Comment by dmvtech** [comment]
Hi @ivarkallejarv  Sorry for the delay. We've been able to reproduce what you are seeing and working to see if we can come up with any other approaches to accomplish the goal. Thanks for your patience.

**Comment by ivarkallejarv** [comment]
@dmvtech I'll take a look during the weekend and try to migrate to v4 then, thank you for the example

**Comment by ivarkallejarv** [comment]
@dmvtech Thanks again, got it.
So for anyone who might have a similar problem =>
Apparently I missed the saveContext part
``
  await this.adapter.continueConversation(this.reference, async (proactiveTurnContext) => {
    const otherDialogContext = await this.dialogs.createContext(proactiveTurnContext)
    await otherDialogContext.beginDialog(DIALOG)
    await this.conversationState.saveChanges(proactiveTurnContext)
  })
``

After every turn, I saved the turnContext, but you also have to save the proactiveTurnContext, if you create a different conversation.

That saves the context properly, and you can properly continue it another time.
