### ISSUE TITLE
ShowTypingMiddleware missing await on adapter.send

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/botbuilder-js#645]
bot.builder.core 4.1.5

await missing in callback implementation:

https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/showTypingMiddleware.ts#L75

(this is being sent from a timer callback, so maybe this is harmless?)

there is more implementation below it... is this redundant?

**Comment by sgellock** [comment]
pulling back into 4.2

**Comment by benbrown** [comment]
I think this IS harmless, since we don't really need to block on the typing activity having been sent before ... waiting to send another one for a few seconds.  But it doesn't HURT either...
