### ISSUE TITLE
How to have localization in botbuilder SDK v4?

### ISSUE THREAD

**Issue by imdineshgrewal** [Microsoft/botbuilder-js#658]
Hi,

I'm trying to create a bot using SDK v4. The bot needs to be localized in Spanish, Portuguese and French. Could someone please help me with any documentation is available to create multi-languages bot using botbuilder SDK v4? Or do SDK v4 supports multi-languages internally?

Regards,

**Comment by benbrown** [comment]
We have a multilingual sample application that demonstrates one approach to this problem:

https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/17.multilingual-conversations

**Comment by sgellock** [comment]
@imdineshgrewal if the help BenBrown provided above doesn't answer your questions, then please vector product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

**Comment by armstrong-charles** [comment]
I don't think translating the conversation using Translation API is a right solution. We have multi resource files, correct localization resource system should be hooked at right place. If i am using LUIS, right LUIS model (per localization) should be hooked. Need a right sample in V4 SDK.

**Comment by armstrong-charles** [comment]
Latest enterprise bot template fix this issue
