### ISSUE TITLE
proposal: new Middleware.updateActivity() and Middleware.deleteActivity() methods

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-js#67]
We recently realized that we're missing `updateActivity()` and `deleteActivity()` middleware pipes. You currently have to use the adapter directly if you need to modify or delete an existing activity. The issue with that is it bypasses middleware meaning that you log out changes or deletes which you really want to log. 

The proposal is to add two new middleware pipes and then extend the context object with some new methods for calling the adapter through those pipes. See issue #66 for that proposal.

**Comment by billba** [comment]
I find I'm fairly confused by Update and Delete in general. Based on [this old PR for DirectLineJS](https://github.com/Microsoft/BotFramework-DirectLineJS/pull/25) I thought they were just activities you post like any other, in which case wouldn't they go through the existing Post middleware?

**Comment by Stevenic** [comment]
@billba when you post a new activity to a channel the ID of that activity will be returned to you as part of the response to the post.  Normally you can ignore this but there are scenarios where you'll want to save this ID off so that you can later update the activity or delete it. A good example of this is an expense report bot that writes a card to the channel with "approve" and "deny" buttons. When the approve button is clicked the bot wants to overwrite the existing card with a new version without buttons that says "Steve approved this". If deny is clicked the bot may want to go back and actually remove the card all together from the channel.

What @tomlm and I realized the other day is that these updates and deletes aren't going through our middleware pipes currently which means things like logging and translation cant happen against in these cases which feels broken. To address this we need to add two new pipes that middleware can optionally override.  This is a critical scenario for MS Teams.

**Comment by billba** [comment]
Right, I understand the feature at a high level, but how is it implemented? At one point we talked about implementing `update` and `delete` as activities themselves, that take the relevant activityId as a property.

This sounds like a feature that starts with additions to the `ActivityAdapter`. Once that API is settled, it can move upstream into middleware/context.

**Comment by Stevenic** [comment]
The API has actually been in the Adapter for 2 years. I just forgot about it given it's rarely used. There are others that are used even less.  There's a whole attachment CRUD system on there for uploading images to twilio and slack for instance. We're not trying to model any of that directly.

Update would be tricky to model as an activity given that you need to be able to specify the type of activity you're updating. Delete would be more do able but still leaves a bit of a bad smell to it.

**Comment by Stevenic** [comment]
This work is done.
