### ISSUE TITLE
Control/configure size of rich cards or adaptive cards

### ISSUE THREAD

**Issue by mecampbellsoup** [Microsoft/botbuilder-js#670]
Hey guys,

I wrote out this question in an Emulator PR but wanted to open an issue here as well to make sure it falls in the right category:

https://github.com/Microsoft/BotFramework-Emulator/pull/667#issuecomment-443537958

Basically, when we try to use rich/adaptive cards in the Bot Framework, our card contents get cut off at seemingly arbitrary spots - i.e. cards render differently in Skype iOS, vs. Skype webchat, vs. Skype Mac OS, etc. 

Is there a way to configure card size and guarantee they will be rendered to show all the card's contents?

**Comment by tdurnford** [comment]
Unfortunately, the size of the various cards are channel specific and cannot be modified. However, you do have control over font size and other features within the card.
