### ISSUE TITLE
is there a way to access session.conversationData while intercepting 'send' hook from middleware?

### ISSUE THREAD

**Issue by ghost1996110** [Microsoft/botbuilder-js#671]
bot.use({
botbuilder (session, next) {
logger.info("MESSAGE RECEIVED:" + session.message.text);
next();
},

send (event, next) {
logger.info("MESSAGE SENT:" + event.text);
next();
}
});

is there a way to access session in send hook in middleware ?

**Comment by stevkan** [comment]
Hi @ghost1996110, I'm looking into this and will connect with you when I know more.

**Comment by stevkan** [comment]
@ghost1996110, this can be accomplished by calling the loadSession method on the bot. The method takes the session address which can be found in the event parameter that is passed into the send middleware call. This will load the whole session object including the conversationData bag. The code would look something like this:

```js
let logger = {
    info: function (data) {
        console.log(data)
    }
}

bot.use({
    botbuilder(session, next) {
        logger.info("MESSAGE RECEIVED:" + session.message.text);
        next();
    },
    send(event, next) {
        let address = event.address;
        bot.loadSession(address, function (err, session) {
            if (err) {
                console.log(err);
            };
            logger.info("MESSAGE SENT: " + event.text);
            logger.info("CONVERSATION DATA: " + session.conversationData);
        });
        next();
    }
});
```

Hope of help!

**Comment by ghost1996110** [comment]
i did what you told and it printed nothing and then i printed the whole session variable
then it shows conversationdata as empty {},
i have shown the log below which got printed 

"botbuilder:noExp":"^(2|n|no|nope|not|false)(\\W|$)"}},"en-US":{"loaded":{"_40":1,"_65":1,"_55":true,"_72":null},"entries":{}}},"_defaultLocale":"en"}},"userData":{},"conversationData":{},"privateConversationData":{},"sessionState":{"callstack":[{"id":"*:/","state":{"BotBuilder.Data.WaterfallStep":0}}],"lastAccess":1544593218646,"version":0},"dialogData":{"BotBuilder.Data.WaterfallStep":0},"message":{"type":"message","agent":"botbuilder","source":"emulator","sourceEvent":{},"address":{"id":"fa5c9kb2d5e4","channelId":"emulator","user":{"id":"default-user","name":"User"},"conversation":{"id":"d7cac33fj39"},"bot":{"id":"4ahlc9lmbb6m","name":"Bot"},"serviceUrl":"http://localhost:56960"},"text":"","user":{"id":"default-user","name":"User"}}}

**Comment by CoHealer** [comment]
@stevkan, what are next steps?

**Comment by stevkan** [comment]
@ghost1996110, apologies for the delay in responding.

'conversationData' is empty until you populate it with a value/values. This is done as part of the dialog you want to capture. Once populated you will see data in your logger. Keep in mind that 'conversationData' is an array so your logger will only print [Object Object]. In the example below, I assign the results.response.entity to session.conversationData.response which then outputs 'Yes' during the logger method. (If of interest, userData functions in the same manner.)

```js
bot.dialog('/isTicket', [
    function (session, args, next) {
        builder.Prompts.choice(session, "Do you want to raise a ticket for this problem?", "Yes|No",
            {
                maxRetries: 3,
                retryPrompt: 'Sorry, that is not a valid input',
                listStyle: builder.ListStyle.button
            }
        );
    },
    function (session, results, next) {
        // console.log("session: ", session)
        session.conversationData.response = results.response.entity;
        if (session.conversationData.response == "Yes") {
            session.beginDialog('/createTicket');
        } else {
            session.beginDialog('/other');
        }
    }
]);
```

Hope of help!
