### ISSUE TITLE
QnAMaker class does not throw helpful error when not passing in argument for required endpoint parameter

### ISSUE THREAD

**Issue by Zerryth** [Microsoft/botbuilder-js#676]
## Versions
What package version of the SDK are you using. - JS botbuilder-ai 4.1.6
What nodejs version are you using - v10.14.1
What browser version are you using - Chrome

## Describe the bug
`QnAMaker` class requires an `endpoint` parameter.

However when you create an instance of `QnAMaker` without passing in an endpoint, no helpful errors are thrown.

The bot only replies "`Oops. Something went wrong!`" without any helpful indication as to what went wrong (i.e. needs endpoint)

[enhancement]

**Comment by cleemullins** [comment]
@Zerryth This also needs to align across both C# and JS

**Comment by stevengum** [comment]
@Zerryth, I'm assuming this work is done in your dotnet PR and am going to close this issue. If it's not addressed there please either address it in that PR or file a new tracking issue in the dotnet repo so we don't drop the ball on this.
