### ISSUE TITLE
PromptOptions validations property is neither typed nor documented

### ISSUE THREAD

**Issue by ryanvolum** [microsoft/botbuilder-js#680]
## Versions
Package 4.1.5
Node v10.13.0
Windows

## Describe the bug
PromptOptions has a `validations` property on it:

![image](https://user-images.githubusercontent.com/3891951/49476561-32f4e000-f7cf-11e8-9322-f94066dc374d.png)

It seems potentially useful for passing some additional validation logic, but it's unclear how to. The property is typed as an `object` and no docs/samples seem to mention how to use it. 

[bug]

**Comment by benbrown** [comment]
This field is not used in any of our modules or in any of the samples.

@stevenic - can you shed some light on how this is supposed to be used?  Or maybe it should be deprecated?

**Comment by Stevenic** [comment]
This was added as a way of passing through additional validation rules to a custom validator.  For instance you might want to pass a `minLength` value through to the validator routine.  We could update our samples to show this.

**Comment by justinwilaby** [comment]
Seems like generics could help here:
```js
export interface PromptOptions<T extends object> {
 // ...
  validations?: T
}
```

**Comment by Stevenic** [comment]
So here's a simple text length validation rule that would take advantage of the validation field:

```JS
this.addDialog(new TextPrompt('NamePrompt', async (prompt) => {
     const value = prompt.recognized.value || '';
     const minLength = prompt.options.validations.minLength;
     if (minLength != undefined && value.length < minLength) {
          await prompt.context.sendActivity(`Please enter a value that's at least ${minLength} characters long.`);
          return false;
     } else {
          return true;
     }
}); 
```

Then to call it from within a waterfall step you'd use this code:

```JS
async (step) => {
     return await step.prompt('NamePrompt', {
          prompt: `What is your name?`,
          validations: {
               minLength: 2
          }
     });
}
```

**Comment by Stevenic** [comment]
@Kaiqb can you please add this to the list of things needed documentation or samples?  Feel free to use the code snippets above.

**Comment by Kaiqb** [comment]
@Stevenic - can you look at the [issue ](https://github.com/Microsoft/botbuilder-js/issues/785)around sendActivities not working within prompt validate?

**Comment by JonathanFingold** [comment]
We have a small amount of documentation about this in the **About dialogs** topic uner [Prompt options](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0#prompt-options) and [Prompt validation](https://docs.microsoft.com/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0#prompt-validation). Without a more comprehensive prompt validations sample, we're blocked on adding a how-to topic about this.
