### ISSUE TITLE
LuisRecognizer.recognize should offer a string overload

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/botbuilder-js#681]
As of now, LuisRecognizer.recognize can only take a context object. If all the recognize function needs is some text, it should at least take it as an overload. 

This ultimately affects testability and code structure - unit tests shouldn't have to manufacture context objects just to test LUIS recognition. Correspondingly, developers shouldn't have to pass context deep into code that doesn't need it. 

[enhancement]

**Comment by johnataylor** [comment]
It is a core design tenent of the 4.0 framework that information is uniformly shared to all the components that are invoked within a turn of conversation using the TurnContext.

Certainly this design choice has implications and in many ways you might see the TurnContext as something of a [god object](https://en.wikipedia.org/wiki/God_object). But this is the design and it is consistently applied.

Coming back to this specific case the notion of a recognizer is something that gets used within the context of a turn of conversation, it shouldn't be surprising that it takes the TurnContext. The model is layered, if you want to call LUIS more directly and in a way decoupled from the notion of turn then it is easy and natural to use the underlying LUIS client. In fact its not unreasonable to see the point of the recognizer as tying the underlying LUIS client to the executing turn.

Regarding testing, given the recognizer is all about making the LUIS calls from a context it makes sense to mock the context. Its is easy to create a TurnContext using the TestAdapter included in the SDK.
