### ISSUE TITLE
adapter.createConversation in microsoftTeams 'Could not parse tenant id'

### ISSUE THREAD

**Issue by gNechitailo** [Microsoft/botbuilder-js#685]
## Versions
What package version of the SDK are you using: "botbuilder": "^4.1.7",
What nodejs version are you using: v8.9.3
What os are you using: mac OS X

## Describe the bug
microsoftTeams chat doesn't work with `createConversation`

Documentation says that I can create a direct conversation with a user after he/she mentioned the bot using 
BotFrameworkAdapter.createConversation(address, logic);
**example from documentation:** 
```
const reference = TurnContext.getConversationReference(context.activity);

// Start a new conversation with the user
await adapter.createConversation(reference, async (ctx) => {
   await ctx.sendActivity(`Hi (in private)`);
});
```
but the actual behavior I get is exception "Could not parse tenant id"
I tried to research the problem
I have noticed the line:
botbuilder-core/botFrameworkAdapter.ts 229:
```
public async createConversation(reference: Partial<ConversationReference>, logic?: (context: TurnContext) => Promise<void>): Promise<void> {
...
    const parameters: ConversationParameters = { bot: reference.bot, members: [reference.user] } as ConversationParameters;
}
```

Then I performed a "monkey patch" (replacing the method) in which I've added
`{ ..., channelData: { tenant: { id: %actual_tenant_id% } } }` in that line
to parameters. After that everything is okay. How should I fix this the right way?

[bug]

**Comment by benbrown** [comment]
This should be fixed by #712

**Comment by benbrown** [comment]
The tenantId field is being moved to a new location as part of the fix to this issue:
https://github.com/Microsoft/botframework-obi/pull/43

**Comment by sgellock** [comment]
PR #1274 addresses this issue.  Will exist in the 4.3 release
