### ISSUE TITLE
Missing typing for DialogContext.prompt()

### ISSUE THREAD

**Issue by navzam** [Microsoft/botbuilder-js#697]
## Versions
SDK version: 4.2.0
Node version: 10.5.0

## Describe the bug
This is the only signature available for the `DialogContext.prompt()` method:
```
prompt(dialogId: string, promptOrOptions: string | Partial<Activity> | PromptOptions): Promise<DialogTurnResult>
```

which does not contain the `choices` parameter.

## To Reproduce
1. Install `botbuilder-dialogs` and use it according to the docs/samples.
2. Trigger IntelliSense on a `DialogContext` object and observe the options for the `prompt()` method. The `choices` parameter is missing.
3. Confirm by opening `npm_modules/botbuilder-dialogs/lib/dialogContext.d.ts` and looking at the definition of `prompt()`. The `choices` parameter is missing.

## Expected behavior
I expected to see multiple choices for `prompt()` with different sets of parameters. Or at least an optional `choices` parameter.

[bug]

**Comment by stevengum** [comment]
@stevkan can you take a look at this? Let me know if you have any questions.
