### ISSUE TITLE
Breaking dialogs + botbuilder change in 4.2

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/botbuilder-js#698]
## Versions
```
   "botbuilder": "^4.1.5",
   "botbuilder-dialogs": "^4.2.0",
```

## Describe the bug
When using `botbuilder 4.1.5` and downloading the latest `botbuilder-dialogs`, I'm seeing a type mismatch issue on `StatePropertyAccessor`. Upgrading `botbuilder` fixes the issue. I discovered this by using the generator to build a bot last week, and then adding `botbuilder-dialogs` today. 

## To Reproduce
1. Download 4.1.5 of `botbuilder`
2. Download 2.0 of `botbuilder-dialogs`
3. Create a state property accessor for your dialog state: 
`this.dialogState = new BotStatePropertyAccessor(conversationState, 'dialogState');`
4. Create a new dialog set, passing `dialogState`: 
`this.dialogs = new DialogSet(this.dialogState);`

## Expected behavior
I would expect the types between packages to be consistent on packages within the same major version. 

## Screenshots
![image](https://user-images.githubusercontent.com/3891951/49956567-5ba96380-feba-11e8-8a63-250d2fa695d6.png)

## Additional context

[bug]

**Comment by sgellock** [comment]
botbuilder-dialogs only has a dependency on botbuilder-core.

**Comment by ryanvolum** [comment]
Roger that - I do think this is likely to trip people up, as it's not inconceivable that developers will get started with `botbuilder` and add (a newer version of) `botbuilder-dialogs` or other `botbuilder` peripheral packages. I'm not sure if there's a good way to communicate to the community that all `botbuilder` packages should always be on the same major version - this may just be a known tripping point.

**Comment by stevengum** [comment]
Are there any built-in checks in npm to look for for these version mismatches? Specifically botbuilder-dialogs@4.2.0 requires `"botbuilder-core": "~4.2.0"`. (We started [pinning to patch versions](https://github.com/Microsoft/botbuilder-js/pull/656) on the path to 4.2)

As you indicated, there probably isn't a good way to communicate to the community that botbuilder packages should be used by `Major.Minor.Z`, not `Major.Y.Z`

Related issue: Microsoft/Botbuilder-tools#890

**Comment by benbrown** [comment]
Our position is that you should use the matching versions of the libraries.
