### ISSUE TITLE
Cortana OAuth prompts to copy magic code 

### ISSUE THREAD

**Issue by bezysoftware** [Microsoft/botbuilder-js#699]
## Versions
What package version of the SDK are you using - 4.2.0
What nodejs version are you using - 6.11.5
What browser version are you using ???
What os are you using Windows 10

## Describe the bug
I wrote a bot and tested it in the Emulator. First step is to authenticate the user - I used the pieces from this sample: https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/18.bot-authentication/bot.js
It works - I registered my bot in Azure Portal, created custom "OAuth Connection Settings" provider (google), used that connection name in my bot for the `OAuthPrompt`.  In the Emulator everything works - user clicks button to login, does the login, bot gets the access token.

The problem is with Cortana Skill - I set up the Cortana channel, added myself to the test group. I am able to invoke the skill, click to login button, do the login. But then it navigates (still in the login dialog, see screenshot) to a page where it tells me to "Enter this validation code to the chat window to complete the sign-in". I would love to do that, but the login window is modal and I cannot paste the code into the Cortana chat.

## Expected behavior
The framework should somehow instruct the Cortana channel to not require the magic code copy-paste, because it isn't possible to do (login dialog is modal)

## Screenshots
![image](https://user-images.githubusercontent.com/6108688/50052387-9530d780-0123-11e9-9a4e-935799ee6b14.png)

[bug]

**Comment by stevkan** [comment]
@bezysoftware, I was able to repro your circumstances and you are right in that you can't copy/paste the code. However, if you copy the code down you can enter the code as a new command to the bot. It's not a perfect option, but it will work. Follow these steps:

1. Open Cortana and connect to your bot ("tell [bot] hi")
2. Click login option
3. Write down magic code from window
4. Open Cortana and re-connect to your bot
   a. Tell your bot the magic code ("tell [bot] [magic code]")
   b. Login should succeed
5. Interact with your bot

In the mean time, I'll mark this as a potential bug.

**Comment by bezysoftware** [comment]
Thanks for looking into this. I will try the suggested workaround, but a regular user cannot be expected to use this approach.

**Comment by bezysoftware** [comment]
I tried your approach and it works - but only if I invoke Cortana via voice. At that point I actually don't have to reconnect to the bot, I can just "respond" with the code.

If I type the command, after closing the login dialog, Cortana disconnects from the bot completely and reconnecting to it resets the conversion, at which points sending the magic code doesn't work (my guess is activity.type becomes 'message' and the bot tries to interpret it). But that could be an issue in my code...

**Comment by stevkan** [comment]
I completely agree with you re: user expectations which is why I'll be flagging this as a bug. It's interesting that it only responds to you via voice as well as disconnecting. As you point out, it could be related to your specific code. I was testing with a very simple bot.

**Comment by bezysoftware** [comment]
Was this resolved?
