### ISSUE TITLE
SearchEngine and scoreThreshold should be optional fileds for QnAMakerOptions

### ISSUE THREAD

**Issue by anastasiia-zolochevska** [Microsoft/botbuilder-js#70]
As a workaround we had to cast QnAMakerOptions to type any 
const qna = new QnAMaker({
    knowledgeBaseId: ‘x',
    subscriptionKey: ‘x',
    top: 4,
} as any);

**Comment by Stevenic** [comment]
Good feedback.... I'll make those changes. I'd fixed some issues around that but must have missed QnA maker.

**Comment by cleemullins** [comment]
Please be sure to file tracking bugs against the C# version of the QnA Maker stack. 
@johnataylor was in there last and would be a good assignee for them.

**Comment by Stevenic** [comment]
QnA maker has since be re-written and no longer references search engine
