### ISSUE TITLE
TranscriptLoggerMiddleware maybe architecture issue? 

### ISSUE THREAD

**Issue by shmuelgutman** [Microsoft/botbuilder-js#700]
TranscriptLoggerMiddleware is holding the class property `private transcript: Activity[] = [];` at application-wide level (not per context/turn), imagine that my bot instance is getting a lot of concurrency connections(messages), in this case, the transcript array can be  blown up, and more than that, a single turn may be need to be a "slave" of other connections and handle their activities logging.

If we're talking about scale, this definitely something that requires attention

**Comment by tomlm** [comment]
Thanks for the bug report, it's been fixed and will be in the next release.

**Comment by shmuelgutman** [comment]
Great. Thanks.
