### ISSUE TITLE
botState assigns '*' unconditionally, preventing storage implementation from using eTag

### ISSUE THREAD

**Issue by nurih** [Microsoft/botbuilder-js#705]
## Versions
| Item | Version |
|--- |--- |
|botbuilder | 4.2.0|
|nodejs | 10.4 |
|browser | N/A|
| os | win |

## Describe the bug
[`botState.saveChanges(...)` assigns '*' to the eTag ](https://github.com/Microsoft/botbuilder-js/blob/4589b5bdd7e7f450f1455c62401aec9bff409ce7/libraries/botbuilder-core/src/botState.ts#L119
) on state, implying forced overwrite of existing stored state unconditionally. For state already cached, this prevents the framework from flowing through an eTag along to the storage instance.
Tests seem to pass even when removing the eTag assignment line 119, so it's unclear whether this behavior is by design.

## To Reproduce
1. Run `npm test`
1. Observe all tests pass
1. Remove botState.ts L119 and save file
1. Run `npm test`
1. Observe all tests pass

## Expected behavior
`botState` should not assign eTag to an existing state.

[bug]

**Comment by sgellock** [comment]
This is by design.  @Kaiqb can you provide a link to our state docs

**Comment by Kaiqb** [comment]
Here is the [link](https://review.docs.microsoft.com/en-us/azure/bot-service/bot-builder-custom-storage?branch=live&view=azure-bot-service-4.0) to the doc.
