### ISSUE TITLE
ComponentDialog initialDialogID property causes confusing behavior

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/botbuilder-js#710]
## Versions
botbuilder version: "botbuilder": "^4.2.0",
node version: v10.13
OS: Windows

## Describe the bug
When using component dialogs, I found that my dialogs would only start if I set `this.initialDialogId` to the dialogId passed in: 
```js
        this.initialDialogId = dialogId;
```

It was unclear why I had to do this, as it isn't documented anywhere (see [doc bug](https://github.com/MicrosoftDocs/bot-docs/issues/673). Digging further into the source code, I discovered that `initialDialogId` is a protected property off of ComponentDialog, and that if not explicitly set, it defaults to the first dialog added. 

This behavior is confusing and will likely lead to many errors. In my case, the first "dialog" I added was a ChoicePrompt, so my bot failed completely silently. If it's necessary to define the initial dialog, I'd recommend using a method to set it (instead of having to explicitly set a property) and documenting it well. 

## To Reproduce
1. Create a `ComponentDialog`
2. Don't set `this.initialDialogId`
3. Add a choice promt: `this.addDialog(new ChoicePrompt('choicePrompt'));`
4. Attempt to start your `ComponentDialog`

[bug]

**Comment by sgellock** [comment]
making any change here will be breaking.  @Stevenic to drive

**Comment by stevengum** [comment]
See Microsoft/botbuilder-dotnet#905

**Comment by johnataylor** [comment]
Thanks for opening this issue, unfortunately this would be a breaking change to the API. The current default behavior seems pretty intuitive, to the degree that its hard to imagine an alternative. And the explicit override of the behavior seems pretty discoverable. If you think this needs more clarification in docs and samples please go ahead and open issues there.

**Comment by ryanvolum** [comment]
We've had several developers trip over this. I think they find it weird that they need to explicitly set a property - when polling devs on whether they'd rather have an method that sets it they've said yes. Would adding an method on ComponentDialogs still be a breaking change?
