### ISSUE TITLE
ChoicePrompt list style 'suggestedAction' not working in Microsoft Teams

### ISSUE THREAD

**Issue by blsmith9** [Microsoft/botbuilder-js#713]
## Versions
What package version of the SDK are you using. - 4.1.5
What nodejs version are you using - 10.14.1
What os are you using - Windows 10

## Describe the bug
Give a clear and concise description of what the bug is.
When creating a new ChoicePrompt and setting the list style to suggestedAction, the choices are not visible in Microsoft Teams. When the list style is set to auto, inline, or list, the choices are visible.

## To Reproduce

```
var queryPrompt = new ChoicePrompt(QUERY_PROMPT);
queryPrompt.style = ListStyle.suggestedAction;		
this.dialogs.add(queryPrompt);
```

## Expected behavior
Suggested actions be visible in teams

[bug]

**Comment by v-kydela** [comment]
Hello @blsmith9 

Microsoft Teams does not support suggested actions. This can be seen in the [Channel Inspector](https://docs.botframework.com/en-us/channel-inspector/channels/Teams?f=SuggestedActions&e=example1), the [source code](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/choices/channel.ts#L30), and [this post](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/36025015-bot-support-for-suggested-actions) on UserVoice.

Sorry for the inconvenience!
