### ISSUE TITLE
[Botframework-Connector] Proxy Settings are Ignored

### ISSUE THREAD

**Issue by justinwilaby** [microsoft/botbuilder-js#717]
Currently, the botframework-connector package ignores HTTP_PROXY and HTTPS_PROXY environment variables and will not work for networks that require a proxy. There are a number of tools that depend on this package and each of them are broken for customers that require the use of a proxy.

## Repro
1. Set the HTTP_PROXY and HTTPS_PROXY environment variables in your node project to a proxy url.
2. initiate a call using an API in the botframework-connector

## Observe
The rest call does not use the proxy and times out when on a network requiring a proxy.

## Expected Behavior
The rest call will use the proxy settings.

## Notes
Consider removing ms-rest-js since it [does not appear to support proxies](https://github.com/Azure/ms-rest-js/issues/169) and replace it with an isomorphic `fetch` implementation similar to [this implementation](https://github.com/Microsoft/botbuilder-tools/blob/master/packages/QnAMaker/bin/qnamaker.js#L16)

**Comment by stevengum** [comment]
@justinwilaby https://github.com/Azure/ms-rest-js/pull/322 was merged, is this now unblocked?

@EricDahlvang as an FYI

**Comment by cleemullins** [comment]
@juanar, is this something we can move forward with this cycle? We just finished getting Proxy support working in the C# SDK (thanks @carlosscastro and @dmvtech and @drub0y !!), and having parity in the JS would be great.

**Comment by cleemullins** [comment]
Keeping as P1 in the 4.6 time frame, and prioritizing with @juanar

**Comment by cleemullins** [comment]
I don't believe we will fix this in the near term.

**Comment by patrickianco** [comment]
Hello we are also experiencing this issue right now, in the logs we're getting this error and the chatbot is deployed in openshift
![image](https://user-images.githubusercontent.com/27019238/117115968-5d905c00-adc0-11eb-80a2-4f54b146f303.png)

**Comment by joshgummersall** [comment]
`ETIMEDOUT` indicates that there is a problem connecting to the IP address in the logs. Using `dig` I see that `login.botframework.com` resolves to a different IP address than the one logged.

```bash
> dig +short login.botframework.com
bc-api.trafficmanager.net.
connector-api-westus.azurewebsites.net.
waws-prod-bay-049.vip.azurewebsites.windows.net.
waws-prod-bay-049.cloudapp.net.
40.83.182.206
```

That tells me that perhaps there is something wrong with your proxy. Can you share your `BotFrameworkAdapter` configuration?

**Comment by ChupaCabre** [comment]
Hi @cleemullins @justinwilaby  is there proxy support for the javascript SDK at this point? If so, how are the proxy settings passed into the CloudAdapter? I've looked through the [docs](https://learn.microsoft.com/en-us/javascript/api/botbuilder/?view=botbuilder-ts-latest) & [samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples) but I don't see any mention of proxies.
