### ISSUE TITLE
[Feature Request] Bot Framework Publish validation for JS

### ISSUE THREAD

**Issue by gasper-az** [microsoft/botbuilder-js#720]
It would be very useful to implement a tool which validates the bot's configuration prior to publishing it, for preventing common issues like missing endpoints.

There is a similar tool which is being implemented in BotBuilder-Dotnet (more info [here](https://github.com/Microsoft/botbuilder-dotnet/pull/1262)), which validates, before a publish operation, if  the `.bot` file exists; if the `.csproj` file doesn't have any whitespace in its name; the existence of `Luis` & `QnA` keys; and the presence/absence of some specifics endpoints (e.g: `production`, `development`). In this implementation, some basics validation methods are included in the `Microsoft.bot.configuration` library (which equivalent in `Botbuilder-js` is `botframework-config`), which will be used both directly from the implementation of this library, and indirectly, through the usage of a `nuget` package created specifically for this task.

**Comment by cleemullins** [comment]
We added this in PR https://github.com/Microsoft/botbuilder-dotnet/pull/1262 to the C# Repo, as part of the plans around publish validation. 

We should either:
1. Add the parity in the JS repo (this Issue)
2. Remove the feature from C#. 

The thought behind having it is that it's easy for developers to make the call and figure out what to do. This applies to the VSIX, Templates, and samples. They can easily throw errors on startup saying "XYZ isn't configured" if these checks are present.

**Comment by stevengum** [comment]
Closing this as we've fully moved away from `.bot` files and rely on each languages'/runtimes' configuration answers (`appsettings.json` & `appsettings.development.json`, `.env` files, etc).
