### ISSUE TITLE
tslint doesn't lint botbuilder-js repo

### ISSUE THREAD

**Issue by Zerryth** [Microsoft/botbuilder-js#727]
## Versions
4.2.0

## Describe the bug
Running command `npm run tslint` (or more specifically `tslint ./libraries/*/src/*.ts ./libraries/*/src/**/*.ts  -t verbose`) from botbuilder-js root

results in:
`No valid rules have been specified for TypeScript files`

## Expected behavior
For linting rules to run

## Screenshots
From travis:
![image](https://user-images.githubusercontent.com/35248895/51574805-441fac00-1e64-11e9-96b3-c11ddbe2383d.png)

[bug]

**Comment by stevengum** [comment]
To clarify on this, @Zerryth is going to _reenable_ tslint, because we've been checking code that hasn't been going through the linting process. 

For her PR #704 that addressed some ongoing issues with QnAMaker, she will go back in another PR and lint that class after TSLint is back online.

**Comment by benbrown** [comment]
We will re-enable the linter the day after 4.3 ships!

**Comment by benbrown** [comment]
This will be replaced by #806 where I've re-enabled linting and switched over to using eslint.
