### ISSUE TITLE
Short-circuiting is broken in intentRecognizerSet

### ISSUE THREAD

**Issue by navzam** [Microsoft/botbuilder-js#73]
`intentRecognizerSet` doesn't seem to be short-circuiting the recognizers when `recognizeOrder` is `series` and  `stopOnExactMatch` is `true`. I believe this is due to a bug in [hasExactMatch](https://github.com/Microsoft/botbuilder-js/blob/13506b4afa7267d82be0adb0f420ff94450c378f/libraries/botbuilder/src/intentRecognizerSet.ts#L141): 
``` 
private hasExactMatch(intents: Intent[]): boolean { 
        intents.forEach((intent) => { 
            if (intent.score >= 1.0) { 
                return true; 
            } 
        }); 
        return false; 
    } 
``` 
where the `return true` is returning in the `forEach` callback rather than the outer function.

**Comment by Stevenic** [comment]
Good catch... This bites me I don't know how many times :( 

I was planning to push out new bits tomorrow so will fix this before hand.

**Comment by Stevenic** [comment]
See PR #75

**Comment by Stevenic** [comment]
This class was removed for //build
