### ISSUE TITLE
Introduce Card support for Prompts and have Teams / Cortana fallback

### ISSUE THREAD

**Issue by garypretty** [Microsoft/botbuilder-js#736]
## Describe the bug
Raising issue here to ensure change on the .NET side to introduce Card based prompts and for Teams / Cortana (which don't support suggested actions) to automatically fall back to use this style.

PR in the .NET repo https://github.com/Microsoft/botbuilder-dotnet/pull/1339 
[bug]

**Comment by garypretty** [comment]
Closing as duplicate of #737 raised by @cleemullins

**Comment by Stevenic** [comment]
Didn't see you had added this sorry...
