### ISSUE TITLE
IntentDialog in SDKv4

### ISSUE THREAD

**Issue by parag-nikhal** [Microsoft/botbuilder-js#739]
IntentDialog class is not in SDK v4 is there any subtitution for this ?

**Comment by stevkan** [comment]
Hi @parag-nikhal, I'm looking into this and will let you know what I find.

**Comment by stevkan** [comment]
@parag-nikhal, there is an equivalent to IntentDialog being developed to be included in a future build. Unfortunately, at this time there is no substitution.
