### ISSUE TITLE
Make a consistent and strict usage of tslint/eslint across bot framework, samples and generators

### ISSUE THREAD

**Issue by kichinsky** [Microsoft/botbuilder-js#745]
**Is your feature request related to a problem? Please describe.**
The usage of linting tools and applied rules is not consistent across the bot framework, generators and samples. It would be helpful from code quality and coding experience perspectives to have one shared approach everywhere. 

E.g., the echobot generator enforces using single quotes!

**Describe the solution you'd like**
Setup some share policy on using linting tools and default rules.

[enhancement] 
Related #728

**Comment by benbrown** [comment]
I think if we implement eslint everwhere, this will be a good start. (See #728)

We'll be applying _typescript_ rules to typescript code, so there won't be a 100% match on the linter rules, but we'll at least be using the same tool and broadly the same set of rules.

**Comment by benbrown** [comment]
We've now implemented eslint on the main botbuilder-js project, which incorporates the same ruleset that is applied to the samples.

**Comment by benbrown** [comment]
Upon review of the samples work in progress, I believe this is done!
