### ISSUE TITLE
Portal link takes you to the old deployment config screen

### ISSUE THREAD

**Issue by codefoster** [Microsoft/botbuilder-js#746]
## Versions
What package version of the SDK are you using. 4.2
What nodejs version are you using 11
What browser version are you using Edge
What os are you using Win10

## Describe the bug
This is actually an Azure Portal issue, but I was encouraged to submit here for visibility.
When following the links to setup continuous deployment in a Bot Service in Azure, the links take you to the deprecated deployment configuration screen instead of the new Deployment Center. Navigating to the underlying App Service allows you to access the Deployment Center.

## To Reproduce
1. Log in to Azure
1. Navigate to the Bot Service
1. Click on "Publish your bot from your local environment..."
1. Click on "Publish updates automatically..."

## Expected behavior
Deployment Center

## Screenshots
![deploy1](https://user-images.githubusercontent.com/1494781/52147883-f30a7780-261c-11e9-8661-373a10c86ad4.png)
![deploy2](https://user-images.githubusercontent.com/1494781/52147886-f7cf2b80-261c-11e9-8573-94228cf0c4b8.png)
![deploy3](https://user-images.githubusercontent.com/1494781/52147890-faca1c00-261c-11e9-8ee1-5f3ed4e07409.png)

## Additional context

[bug]

**Comment by Kaiqb** [comment]
This is now being tracked internally in our bugs database.

**Comment by sgellock** [comment]
@codefoster I spoke with the portal team and they are tracking to have this fixed for their next deployment.  Right now, it looks like that deployment is scheduled on or about 2/21.
