### ISSUE TITLE
Dialogs doesn't allow hierarchical functionality

### ISSUE THREAD

**Issue by codefoster** [Microsoft/botbuilder-js#748]
## Versions
4.2
## Describe the bug
One of the best things about Bill Barnes' [Topical](https://github.com/billba/topical) library was that topics (dialogs) were configured in a hierarchical fashion - topics had child topics which had child topics. On every turn, a topic was able to determine whether it should handle an activity or delegate to one of its children. I don't see this functionality in the built-in Dialogs library.

## To Reproduce
N/A

## Expected behavior
N/A

## Screenshots
N/A

## Additional context
N/A

[bug]

**Comment by codefoster** [comment]
Realizing that this should have been a feature request. Sorry.

**Comment by benbrown** [comment]
We've got a lot of improvements coming, including the ability for dialogs to bubble activities up to parent dialogs -- however we are not currently planning on implementing this feature.  Thanks!
