### ISSUE TITLE
Inconsistency between user/conversation state and step state

### ISSUE THREAD

**Issue by codefoster** [Microsoft/botbuilder-js#749]
## Versions
4.2

## Describe the bug
User and conversation state require strong typing. That requirement makes it a bit cumbersome to use. Step state (step values) do not and are implemented as a simple `object`. This makes it very easy to use, but is more difficult to type. I'm honestly not sure which method I like better, but it seems there should be consistency.
To type step values, we ended up creating an interface...
```
interface StepValues {
  property1:string;
  property2:number;
}
```
And then in the step we cast as the interface...
```
(step.values as StepValues).property1 = ...
```

## To Reproduce
N/A

## Expected behavior
N/A

## Screenshots
N/A

## Additional context
N/A

[bug]

**Comment by benbrown** [comment]
Thanks for your input. The state stuff as implemented can be tricky -- we are making big improvements in an upcoming release! :)

**Comment by Stevenic** [comment]
This will all be simpler in 4.next so closing this for now.
