### ISSUE TITLE
GetConversationReference and ApplyConversationReference should be on Activity

### ISSUE THREAD

**Issue by watadarkstar** [Microsoft/botbuilder-js#750]
In dotnet this already landed here: https://github.com/Microsoft/botbuilder-dotnet/issues/703 but it never made it to javascript.

Quote from @tomlm:

In javascript, we don't have an actual "Activity" class which caused the utility methods of

- GetConversationReference()
- ApplyConversationReference() to be implement as global functions off of TurnContext.

That's the wrong place for them because of 

a. they have nothing to do with TurnContext
b. They are operations on the activity. (Get a Conversation reference from an activity, apply a conversationReference to an activity).

In OO languages, I propose that we have the Activity class have the helper methods for ConversationReference methods **and in Javascript the helper functions should be centred around the Activity.**

**Comment by Stevenic** [comment]
This would be a breaking change... We can't do it in 4.x

**Comment by Stevenic** [comment]
Activity is an interface in JavaScript so its a plain old json object.  We can't add methods to it because it won't serialize.  We had to stick these methods somewhere and moving them now would be a breaking change.
