### ISSUE TITLE
npmjs and myget packages are different

### ISSUE THREAD

**Issue by navzam** [Microsoft/botbuilder-js#758]
## Versions
SDK version: 4.2.0
Node version: 10.5.0
npm version: 6.1.0

## Describe the bug
For a given version, the npm packages that are being published on npmjs and myget are different. I've observed this for `botbuilder` and `botframework-config` but I believe it applies to others as well.

## To Reproduce
1. Download the `botbuilder v4.2.0` package from npmjs: https://registry.npmjs.org/botbuilder/-/botbuilder-4.2.0.tgz
2. Run your favorite hash function on this file
```
> (certutil -hashfile .\botbuilder-4.2.0.tgz SHA1)[1]
4133e7ef8bda1505ce894d607cc9f438292d9bfd
```
3. Download the `botbuilder v4.2.0` package from myget: https://botbuilder.myget.org/F/botbuilder-v4-js-daily/npm/botbuilder/-/botbuilder-4.2.0.tgz
4. Run the same hash function on this file
```
> (certutil -hashfile .\botbuilder.4.2.0.tgz SHA1)[1]
e8e8db32cac989f765965c1b28f873fb0af7d2ce
```

## Expected behavior
For a given version, I expect the published package to be exactly the same, regardless of the registry.

## Additional context
This causes issues if you are using one registry when your `package-lock.json` is created, and then you switch to the other registry and run `npm install`. npm gives EINTEGRITY errors because the checksum in your `package-lock.json` doesn't match the new checksum.

The only actual difference I've found between two packages is a newline at the end of the `package.json`. One package has a newline and the other does not. No functional difference, but enough to change the hash.

[bug]

**Comment by cleemullins** [comment]
This is a surprise. I would also expect those files to be exactly the same. Given how we push these packages, which is by actually uploading the MyGet one to Npmjs with no human touch, I'm additionally surprised. 

This appears to be a muliti-year old NPM bug, as seen here:
https://github.com/npm/npm/issues/18545

From that bug, the issue appears to be:
> The more technical answer is that in POSIX standard there is a [3.206 Line definition](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206) that tells what the line is. It has nothing about EOF - it is about EOL. But also there is a [3.195 Incomplete Line definition](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_195). That defines a line at the EOF that has no termination symbol at the EOL. So files with and without line termination at the EOF from the perspective of the standard are completely the same files. The difference is only in lines, and this difference nowadays is just a stylistic

**Comment by cleemullins** [comment]
I'm still digging. 
https://github.com/npm/npm/issues/17161

It seems like we can fix this with the right .gitattributes file, so that any edited .json files have CRLF at the end. Checking on that now.

**Comment by cleemullins** [comment]
I've updated the .gitattributes to properly set EOF markers in package.json files. I don't know if this will fix the issue here. 

Given this only impacts folks using both MyGet and NPMJS, I don't think this is something we need to fix at this time. 

I propose we close this as "Won't fix".

**Comment by navzam** [comment]
Agreed that the number of people affected is likely small, but I think it's still a severe issue to publish different packages. Are there any other processes running between the publish to myget and the publish to npmjs?

**Comment by cleemullins** [comment]
Still digging. 

I wrote this Powershell script to check all the packages for all the current versions:

```
$botbuilderPackages = @("botbuilder", "botbuilder-core",
                    "botbuilder-ai", "botbuilder-azure", 
                    "botbuilder-dialogs", "botframework-config",
                    "botframework-schema", "botframework-connector")

$versions = "4.1.7","4.2.0", "4.2.1"

New-Item -ItemType Directory -Force -Path .\NPMJS | Out-Null
New-Item -ItemType Directory -Force -Path .\MyGet | Out-Null

foreach ($element in $botbuilderPackages) 
{    
    foreach ($version in $versions)
    {     
        $fileName = "$element-$version.tgz"
        $npmuri = "https://registry.npmjs.org/$element/-/$fileName"
        $mygetUri = "botbuilder.myget.org/F/botbuilder-v4-js-daily/npm/$element/-/$fileName"
                     
        Invoke-WebRequest -Uri $npmuri -OutFile "NPMJS/$fileName"
        Invoke-WebRequest -Uri $mygetUri -OutFile "MyGet/$fileName"

        $npmHash = Get-FileHash "NPMJS/$fileName" -Algorithm MD5        
        $MyGetHash = Get-FileHash "MyGet/$fileName" -Algorithm MD5        

        if ($npmHash.Hash.Equals($mygetHash.Hash))
        {
            Write-Host "MATCH!!!! " + $npmOuput -ForegroundColor Green
        }
        else {
            
            Write-Host "NO MATCH. Package: $element-$version, NPMJS Hash: $($npmHash.Hash)  MyGet Hash: $($MygetHash.Hash)"  -ForegroundColor red
        }

    }
}
```

That script tells us, EVERYTHING is different:
```diff
- NO MATCH. Package: botbuilder-4.1.7, NPMJS Hash: 83FE26A5867F4E7B7C018A94BCA89458  MyGet Hash: 4CBBAF3701706466432AFF41D94ABC70
- NO MATCH. Package: botbuilder-4.2.0, NPMJS Hash: FF1E95B5A246A8EEC564D4AE6980337E  MyGet Hash: 163A3102D4AE5F543129F2156B7BF7CF
...
...
...
- NO MATCH. Package: botframework-connector-4.2.1, NPMJS Hash: E331948A70170DAFB616D8B5C4ADC029  MyGet Hash: DBCC759BEDE70B806566C50C182C90D9
```

**Comment by cleemullins** [comment]
I'm still digging. I've file a few bugs for *weird* stuff that's going on, but I still don't know what's causing this. 

My script not diffs EVERY FILE in the packages looking for mis-matches. The good new: The only not-matching files (except for the test weirdness, #777, #778) are the package.json files, as seen below. 

```
Files DO NOT Match: C:\Users\chris\fubar\NPMJS\botbuilder-4.2.1\package\package.json C:\Users\chris\fubar\MyGet\botbuilder-4.2.1\package\package.json
Files DO NOT Match: C:\Users\chris\fubar\NPMJS\botbuilder-core-4.2.1\package\package.json 
Files DO NOT Match: C:\Users\chris\fubar\NPMJS\botbuilder-ai-4.2.1\package\package.json C:\Users\chris\fubar\MyGet\botbuilder-ai-4.2.1\package\package.json
Files DO NOT Match: C:\Users\chris\fubar\NPMJS\botbuilder-azure-4.2.1\package\package.json C:\Users\chris\fubar\MyGet\botbuilder-azure-4.2.1\package\package.json
Files DO NOT Match: C:\Users\chris\fubar\NPMJS\botbuilder-dialogs-4.2.1\package\package.json C:\Users\chris\fubar\MyGet\botbuilder-dialogs-4.2.1\package\package.json
Files DO NOT Match: C:\Users\chris\fubar\NPMJS\botframework-config-4.2.1\package\package.json C:\Users\chris\fubar\MyGet\botframework-config-4.2.1\package\package.json
Files DO NOT Match: C:\Users\chris\fubar\NPMJS\botframework-schema-4.2.1\package\package.json C:\Users\chris\fubar\MyGet\botframework-schema-4.2.1\package\package.json
Files DO NOT Match: C:\Users\chris\fubar\NPMJS\botframework-connector-4.2.1\package\package.json C:\Users\chris\fubar\MyGet\botframework-connector-4.2.1\package\package.json
```

The script used to generate this list is:
```powershell
$botbuilderPackages = @("botbuilder", "botbuilder-core",
                    "botbuilder-ai", "botbuilder-azure", 
                    "botbuilder-dialogs", "botframework-config",
                    "botframework-schema", "botframework-connector")

# $versions = "4.1.7","4.2.0", "4.2.1"
$versions = "4.2.1"

New-Item -ItemType Directory -Force -Path .\NPMJS | Out-Null
New-Item -ItemType Directory -Force -Path .\MyGet | Out-Null

foreach ($element in $botbuilderPackages) {    
    foreach ($version in $versions) {     
        $fileName = "$element-$version.tgz"
        $npmuri = "https://registry.npmjs.org/$element/-/$fileName"
        $mygetUri = "https://botbuilder.myget.org/F/botbuilder-v4-js-daily/npm/$element/-/$fileName"
       
        Invoke-WebRequest -Uri $npmuri -OutFile "NPMJS/$fileName"
        Invoke-WebRequest -Uri $mygetUri -OutFile "MyGet/$fileName"

        $npmHash = Get-FileHash "NPMJS/$fileName" -Algorithm MD5        
        $MyGetHash = Get-FileHash "MyGet/$fileName" -Algorithm MD5        

        if ($npmHash.Hash.Equals($mygetHash.Hash)) {
            Write-Host "MATCH!!!! " + $fileName -ForegroundColor Green
        }
        else {                        
            New-Item -ItemType Directory -Force -Path .\NPMJS\"$element-$version" | Out-Null
            New-Item -ItemType Directory -Force -Path .\MyGet\"$element-$version" | Out-Null
            
            Copy-Item "NPMJS/$fileName" -Force -Destination .\NPMJS\"$element-$version\$fileName" | Out-Null
            Copy-Item "MyGet/$fileName" -Force -Destination .\MyGet\"$element-$version\$fileName" | Out-Null

            Start-Process "tar.exe" -WorkingDirectory ".\NPMJS\$element-$version\" -ArgumentList "-xzf $fileName"
            Start-Process "tar.exe" -WorkingDirectory ".\MyGet\$element-$version\" -ArgumentList "-xzf $fileName"                                    
            
            foreach($file in Get-ChildItem -r ".\NPMJS\$element-$version\") 
            {
                if (!$file.PSIsContainer) 
                {
                    if (! $file.FullName.EndsWith("tgz"))
                    {
                        $npmFileHash = Get-FileHash $file.FullName
                        
                        $mygetFileName = $file.FullName.Replace("NPMJS", "MyGet")                    
                        $mygetFileHash = Get-FileHash $mygetFileName
                        
                        if ($npmFileHash.hash -eq $mygetFileHash.hash)
                        {                        
                            # Write-Host "Files Match: $mygetFileName" -ForegroundColor Green
                        }
                        else {
                            Write-Host "Files DO NOT Match: $($file.FullName) $mygetFileName" -ForegroundColor Red
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by cleemullins** [comment]
It seems *VERY* clear that something is unpacking / changing / repacking our npm files during the upload to npmjs.org. We have instances of EVERY package.json having it's final newline character stripped off, and 1 instance (in botbuilder-ai) of 2 unexpected .json files being added into the package on NPMJS.org (and not present on the MyGet server). 

From data, I cannot tell if this is MyGet, npmjs.org, or some nefarious man-in-the-middle.

There's no indication online npmjs.org changes these files/packages, so I doubt it's them. I suspect it's something in the MyGet process.
 
Our next debugging steps:
1. Manually upload the MyGet packages to NPMJS, and see what happens. 
2. Create the packages manually and upload them to both services, and see what the Diff is.

**Comment by cleemullins** [comment]
I pulled the Build Logs from Azure Devops for this build, and I have the original "Create" data. From those logs, I see:

> [command]/Users/vsts/hostedtoolcache/node/10.15.1/x64/bin/npm publish
> [...]
> + botbuilder@4.2.1
> [...]
> npm notice === Tarball Details === 
> npm notice name:          botbuilder                              
> npm notice version:       4.2.1                                   
> npm notice package size:  34.8 kB                                 
> npm notice unpacked size: 193.1 kB                                
> npm notice shasum:        112ed83dfdec645d20fb39b24dde8781ebed4151
> npm notice integrity:     sha512-dNWR3SVQ8FxK8[...]nKgTZXns1s4ZQ==

When I run "npm view" against the package on MyGet, I get the Expected SHA Sum:
```
C:\Temp\npm>npm config set registry https://botbuilder.myget.org/F/botbuilder-v4-js-daily/npm/
C:\Temp\npm>npm view botbuilder@4.2.1 dist.shasum
112ed83dfdec645d20fb39b24dde8781ebed4151
```
When I run "npm view" against the package on NPMJS, I get an incorrect value:
```
C:\Temp\npm>npm config set registry https://registry.npmjs.org/
C:\Temp\npm>npm view botbuilder@4.2.1 dist.shasum
ae4fe62de7c2640b66730efef6ca919c3fbceeeb
```
This tells us that the package on MyGet **MATCHES** the output of the build. Knowing that is a good start.

**Comment by cleemullins** [comment]
I've created [botbuilder-4.3.0-testing-do-not-use](https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=49438). That [published to MyGet](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder/4.3.0-testing-do-not-use) just fine, and has the correct Hash. 

I then MANUALLY publish the tarball to NPMJS.org.
```
C:\Temp\npm>npm publish botbuilder.4.3.0-testing-do-not-use.tgz --tag testing
npm notice package: botbuilder@4.3.0-testing-do-not-use
[...]
npm notice shasum:        1539afa4693b73b9c52c5877956f798ab55e1cc1
```

When I test that, the hash passes. 
```
C:\Temp\npm\foo>npm view botbuilder@4.3.0-testing-do-not-use dist.shasum
1539afa4693b73b9c52c5877956f798ab55e1cc1
```
[Note: I then unpublished the package, so it's gone. No sense in polluting the global namespace]

This confirms I can publish a tarball to NPMJS.Org w/o having the hash files corrupted.

**Comment by cleemullins** [comment]
The process of "Push" from MyGet to Npmjs.org is corrupting / changing the files. I have a repo. 
The Package that is built has this:
```
[From the build Logs]
npm notice shasum:        45059a1bafa2fc540f03d9b0f763590790a9a903
```
On botbuilder.myget.org, has this sha hash:
```
C:\Temp\npm>npm config set registry https://botbuilder.myget.org/F/botbuilder-v4-js-daily/npm/
C:\Temp\npm>npm view botbuilder@4.3.0-testing-do-not-use-2 dist.shasum
45059a1bafa2fc540f03d9b0f763590790a9a903
```
After "Push" via MyGet, the package is pushed to Npmjs.org, and has the WRONG hash:
```
C:\Temp\npm>npm config set registry https://registry.npmjs.org/
C:\Temp\npm>npm view botbuilder@4.3.0-testing-do-not-use-2 dist.shasum
8c5ec6c854cb3f597bdee87b7c004339545413f3    <---- !! WRONG WRONG WRONG !!
```

**Comment by cleemullins** [comment]
Note: I've escalated this to MyGet Enterprise support and am researching alternative publishing approaches.

**Comment by cleemullins** [comment]
We've resolved this as far as we're going to. For 4.3 and later versions of the SDK, we will no longer publish upstream using MyGet. For older packages we're not going to retcon the "right" versions, as that has it's own set of issues. 

As a side note, we'll be moving the upstream packaging / publishing to Azure Artifacts, which should cleanly (hopefully!) integrate with our various builds.

**Comment by navzam** [comment]
@cleemullins That all sounds good. Thanks for taking the time to look into it, sorry it took you into this rabbit hole.

Is it possible to add a test somewhere in the publishing pipeline to ensure the two packages match for future versions? Maybe before publishing to npmjs if you always publish to MyGet first?
