### ISSUE TITLE
A readme.md file is needed describing the steps for re-generating clients from swagger

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-js#761]
We should add a readme.md to the `libraries\swagger` directory describing the exact steps from end-end that's needed to regenerate the connector client and schema from swagger.  We should probably do something similar in the `libraries\botbuilder-ai` directory.  It's not clear where we need to get the swagger files from.

[enhancement]

**Comment by axelsrz** [comment]
In 4.5 we're going to discuss the plan for moving forward with this.

**Comment by sgellock** [comment]
we've moved off of swagger generated updates
