### ISSUE TITLE
botbuilder-luis should use official runtime swagger file

### ISSUE THREAD

**Issue by stevengum** [Microsoft/botbuilder-js#77]
The currently used [swagger file][luis-q] for LUIS is missing the options for [`spellCheck`][rt-spellCheck], [`bing-spell-check-subscription-key`][rt-key] and [`log`][rt-log]. Therefore the LuisRecognizer class does not recognize these parameters and customers aren't able to use these features. Instead of relying on the handcrafted file, botbuilder-luis should use the approved [LUIS-Runtime.json][runtime].

  [luis-q]: https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botframework-luis/swagger/Luis-q.json#L60
  [rt-spellCheck]: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/LUIS/Runtime/stable/v2.0/LUIS-Runtime.json#L72
  [rt-key]: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/LUIS/Runtime/stable/v2.0/LUIS-Runtime.json#L78
  [rt-log]: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/LUIS/Runtime/stable/v2.0/LUIS-Runtime.json#L84
  [runtime]: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/LUIS/Runtime/stable/v2.0/LUIS-Runtime.json

**Comment by Stevenic** [comment]
@stevengum97 (or @cleemullins) do you know is the official LUIS-Runtime client published as an NPM? I'd like to move that out of our repo.

**Comment by stevengum97** [comment]
Conversation continued in emails; currently there is no officially published LUIS-Runtime client.

**Comment by Stevenic** [comment]
Need to verify if we have the latest schema.

**Comment by Stevenic** [comment]
Blocked until we can track down where the latest LUIS swagger file actually lives.

**Comment by stevengum** [comment]
chrimc62 has an open PR to resolve this issue: #351

**Comment by stevengum** [comment]
#351 was merged so this issue can be closed.
