### ISSUE TITLE
Lerna is a dependency but is not installed automatically nor listed in documentation

### ISSUE THREAD

**Issue by chrimc62** [Microsoft/botbuilder-js#774]
## Describe the bug
If you sync the SDK and do 'npm install' it will complain about lerna not being there.  Either install should work or it should be documented you need to install it. 

[bug]

**Comment by Aliandi** [comment]
Hey @chrimc62! After reviewing your issue we agreed that lerna should be listed bellow the devDependencies to make working of the SDK a smoother experience. We will add it on the PR #802. Meanwhile, we also found some documentation regarding this topic [here](https://github.com/Microsoft/botbuilder-js/wiki/Building-the-SDK#build-and-test-locally), where lerna is described as required to work with the SDK.
