### ISSUE TITLE
botbuilder-ai package has un-necessary files

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-js#777]
Note: Related to #758, but a different problem.

Download the NPM package for botbuilder-ai, from NPMJS.org:
`https://registry.npmjs.org/botbuilder-ai/-/botbuilder-ai-4.2.0.tgz`

Now, untar the file (note: this works on Windows as well):
`tar -xzf botbuilder-ai-4.2.0.tgz`

There are test files that show up in the results:
```
should_return_0_answers_for_a_question_with_no_answer_after_a_succesful_call.1.json
should_return_0_answers_for_a_question_with_no_answer_after_a_succesful_call.2.json
```

These files do not show up during NPM install of the package, but need to be removed. 

What's *REALLY* weird, is the MyGet version of this same package DOES NOT have these files. 
`https://botbuilder.myget.org/F/botbuilder-v4-js-daily/npm/botbuilder-ai/-/botbuilder-ai-4.2.0.tgz`

**Comment by tomstarstuck** [comment]
This is breaking `yarn`. Because of this issue it is impossible to use botbuilder-ai dependency in projects using `yarn`.

I have tested it locally, and removing those extra files solves the problem with `yarn`.
