### ISSUE TITLE
Update LuisRecognizer description after sample reorganization

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-js#779]
## Tracking Issue:
Update LuisRecognizer description after sample reorganization efforts. 

The LuisRecognizer currently points to the 12.nlp-with-luis sample which may be renumbered in the upcoming sample work. If it is renumbered, we will need to change the link in the [doc string](https://github.com/Microsoft/botbuilder-js/commit/6acf62fe67533738712b35a155be43626a79741b#diff-d746df635d42aa7e8228fc3af83d6852R105):

```ts
/**
 * Recognize intents in a user utterance using a configured LUIS model.
 *
 * @remarks
 * This class is used to recognize intents and extract entities from incoming messages.
 * See this class in action [in this sample application](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/12.nlp-with-luis).
 *
 * This component can be used within your bots logic by calling [recognize()](#recognize).
 */
export class LuisRecognizer {
```

[Link to code in master](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-ai/src/luisRecognizer.ts#L103-L112)

**Comment by CoHealer** [comment]
@Kaiqb, please let us know if you need help on this and we can reassign to an SE

**Comment by Kaiqb** [comment]
@CoHealer - now that luis sample is renamed and renumbered this needs to be updated.
