### ISSUE TITLE
In intentRecognizerSet, "exact match" threshold is not configurable

### ISSUE THREAD

**Issue by navzam** [Microsoft/botbuilder-js#78]
`intentRecognizerSet` only short-circuits the recognizers if an intent meets a hardcoded threshold of 1.0. See filter [here](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/intentRecognizerSet.ts#L139):
```
private hasExactMatch(intents: Intent[]): boolean {
    return intents.filter((intent) => intent.score >= 1.0).length > 0;
}
```
This threshold is not configurable, but in some cases we may want to consider a lower score as an "exact match" (or a "good enough" match).

More generally, it'd be nice to be able to configure a different value for each recognizer in the set (e.g. 1.0 for my regex recognizer, but 0.8 for my LUIS recognizer).

**Comment by Stevenic** [comment]
Seems reasonable... I'll add that to the Pull Request

**Comment by Stevenic** [comment]
removed the class for //build
