### ISSUE TITLE
.sendActivities is not working within prompt validation

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-js#785]
## Versions
What package version of the SDK are you using: **botbuilder botbuilder-dialogs** 4.2.1.
What nodejs version are you using: **node** v10.14.2, **npm** 6.8.0.
What browser version are you using:...the Emulator? v4.2.1.
What os are you using: Windows 10 x64

## Describe the bug
From within a prompt validator, `sendActivity(x)` works as expected, but `sendActivities([x])` does not,
whether `x` is an activity or a string.

## To Reproduce
1. Create a bot that runs a dialog that calls a prompt that includes validation.
2. In the validation function, call the PromptValidatorContext object's .context.sendActivities method.
3. Run the bot, trigger the prompt, and trigger the condition for sendActivities.
4. See error: no messages are sent back to the user in the Emulator.

## Expected behavior
`sendActivities` should work here as advertised, with a string or activity in an array.

## Additional context
These are excerpts from the code I'm using:
```javascript
        // Create the dialog set and add the prompts, including custom validation.
        this.dialogSet = new DialogSet(this.dialogStateAccessor);
        this.dialogSet.add(new NumberPrompt(SIZE_RANGE_PROMPT, this.rangeValidator));
        this.dialogSet.add(new ChoicePrompt(LOCATION_PROMPT));
        this.dialogSet.add(new DateTimePrompt(RESERVATION_DATE_PROMPT, this.dateValidator));

        // Define the steps of the waterfall dialog and add it to the set.
        this.dialogSet.add(new WaterfallDialog(RESERVATION_DIALOG, [
            this.promptForPartySize.bind(this),
            this.promptForLocation.bind(this),
            this.promptForReservationDate.bind(this),
            this.acknowledgeReservation.bind(this),
        ]));
```
```javascript
    async promptForPartySize(stepContext) {
        // Prompt for the party size. The result of the prompt is returned to the next step of the waterfall.
        return await stepContext.prompt(
            SIZE_RANGE_PROMPT, {
                prompt: 'How many people is the reservation for?',
                retryPrompt: 'How large is your party?',
                validations: { min: 3, max: 8 },
            });
    }
```
```javascript
    async rangeValidator(promptContext) {
        // Check whether the input could be recognized as an integer.
        if (!promptContext.recognized.succeeded) {
            await promptContext.context.sendActivity(
                "I'm sorry, I do not understand. Please enter the number of people in your party.");
            return false;
        }
        else if (promptContext.recognized.value % 1 != 0) {
            await promptContext.context.sendActivity(
                "I'm sorry, I don't understand fractional people.");
            return false;
        }

        // Check whether the party size is appropriate.
        var size = promptContext.recognized.value;
        if (size < promptContext.options.validations.min
            || size > promptContext.options.validations.max) {
            // This doesn't work:
            // await promptContext.context.sendActivities([
            //      'Sorry, we can only take reservations for parties of '
            //      + `${promptContext.options.validations.min} to `
            //      + `${promptContext.options.validations.max}.`,
            //      promptContext.options.retryPrompt]);

            // This works:
            // await promptContext.context.sendActivity(promptContext.options.retryPrompt);

            // This works:
            //await promptContext.context.sendActivity(
            //    'Sorry, we can only take reservations for parties of '
            //    + `${promptContext.options.validations.min} to `
            //    + `${promptContext.options.validations.max}.`);

            // These don't work either:
            // await promptContext.context.sendActivities([promptContext.options.retryPrompt]);
            await promptContext.context.sendActivities(["Testing..."]);
            return false;
        }

        return true;
    }
```

Really, this only comes up because I don't get to send a message from the validator and also get the prompt object to display the reprompt.

[bug]

**Comment by JonathanFingold** [comment]
Note: this is blocking updates to the docs to address #680.

**Comment by GasparAcevedoZainSouthworks** [comment]
Hi @JonathanFingold,
We have been researching on the usage of the methods [sendActivity](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/turnContext.ts#L183) & [sendActivities](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/botFrameworkAdapter.ts#L578), from the libraries [Builder-Core](https://github.com/Microsoft/botbuilder-js/tree/master/libraries/botbuilder-core) & [BotBuilder](https://github.com/Microsoft/botbuilder-js/tree/master/libraries/botbuilder) respectively. As we can see, the first method's firm allows to send a _string_ or a _partial Activity_:

![image](https://user-images.githubusercontent.com/43762887/53912709-41ee6700-4038-11e9-86ff-017293c40f75.png)

By the other hand, we have the method _sendActivities_ (which is the one with you are having problems), which only allows using a list of partial Activities:

![image](https://user-images.githubusercontent.com/43762887/53912766-63e7e980-4038-11e9-819b-4a770d83790b.png)

But this method doesn’t allow using a list of strings as you do.

```
 // This doesn't work:
 // await promptContext.context.sendActivities([
//      'Sorry, we can only take reservations for parties of '
//      + `${promptContext.options.validations.min} to `
//      + `${promptContext.options.validations.max}.`,
//      promptContext.options.retryPrompt]);
```

A possible workaround to solve it consists of creating two (or more) separated activities as we did in this screenshot and pass them to the method _sendActivities:_

![image](https://user-images.githubusercontent.com/43762887/53912788-75c98c80-4038-11e9-9a7d-789c60792546.png)

![image](https://user-images.githubusercontent.com/43762887/53912793-7a8e4080-4038-11e9-9e28-0e1dbe90e18d.png)

However, we think that the best approach is to allow that _sendActivities_ could receive both a _list of string_ and a _list of Partial Activities_. So, to accomplish this, we will be creating a new issue requesting these changes.

**Comment by JonathanFingold** [comment]
@GasparAcevedoZainSouthworks , please link to the new issue, once it's open, and then close this issue.

Thanks much.

**Comment by GasparAcevedoZainSouthworks** [comment]
Hi @JonathanFingold,
Despite yesterday we said that the best approach to solve this issue could be creating a new ISSUE requesting that the `sendActivities` could receive both an activity list and a list of string, we continue researching on this topic and we found that:

- In the C# version, the method [sendActivities](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L265) only allows a list of activities, not a list of strings.

- In this [sample in JS](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=javascript#custom-validation), we have not found references for the usage of sendActivities, but instead, it uses sendActivity.

This means that allowing sendActivities to receive as a parameter a list of string is not a good approach.

So, in order to fix this ISSUE you could:

- Instead of using sendActivities with a list of string, make a call to sendActivity for every string on the list. Or,
-  For each string, create a new Partial<Activity>, and pass it to sendActivities as we do in any of these screenshots:
![image](https://user-images.githubusercontent.com/43762887/53986586-5ba5b200-40fd-11e9-820c-a869332fce09.png)
Or:
![image](https://user-images.githubusercontent.com/43762887/53986589-606a6600-40fd-11e9-9866-9e56d481449d.png)

Please, let us know if any of these approaches solve your problem, so we can close the ISSUE.

**Comment by JonathanFingold** [comment]
I'll make a separate suggestion to overload MessageFactory.Text to accept an IEnumerable<string> parameter. Thanks.
