### ISSUE TITLE
Cleanup: Use either async-file or fs-extra in the libraries and tests

### ISSUE THREAD

**Issue by stevengum** [Microsoft/botbuilder-js#786]
## Versions
What package version of the SDK are you using.  __4.2.x-4.3.x__

## Describe the bug
`async-file` and `fs-extra` are both used in the libraries, and they both do the same thing, so we should reduce down to one package.

In `botbuilder` we use `async-file` for the library and for tests. 

In `botframework-config`, the `tools/` folder,  we use `fs-extra` for the library and helper code. `fs-extra` is also used in the tests for `botbuilder-azure` and `botbuilder-ai`, but isn't listed as a devDependency for these two projects. (The tests rely on the hoisted dependencies, otherwise they will fail with import errors) 

@justinwilaby FYI

Edit: added `fs-extra` as a devDependency to botbuilder-ai in #766

[bug]

**Comment by cleemullins** [comment]
@benbrown, this seems straight forward provided it can be fixed w/o breaking compat. If this is just internal implemenation we're good. If we've exposed these on interfaces, then we should live with what we've got rather than break compat.

**Comment by benbrown** [comment]
These aren't really the same, as they provide non-overlapping sets of helper methods... and we're using those methods!

That said, this is all internal implementation details so we should be able to change them without introducing any breaking changes.

**Comment by benbrown** [comment]
I went with fs-extra, as it required the fewest changes to our codebase.

https://github.com/Microsoft/botbuilder-js/pull/805
