### ISSUE TITLE
UserToken flow not exposed in BotFrameworkAdapter

### ISSUE THREAD

**Issue by dfavretto** [Microsoft/botbuilder-js#787]
**Is your feature request related to a problem? Please describe.**
The [`BotFrameworkAdapter`](https://github.com/Microsoft/botbuilder-js/blob/4d99d3322391c2f354208d7824fa5ee1881f548d/libraries/botbuilder/src/botFrameworkAdapter.ts) is missing some methods of the [C# version](https://github.com/Microsoft/botbuilder-dotnet/blob/924eaa286fe3cebfaebae27570f504977c8591e9/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs), including the ones to [get the User's Tokens](https://github.com/Microsoft/botbuilder-dotnet/blob/924eaa286fe3cebfaebae27570f504977c8591e9/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L663).

**Describe the solution you'd like**
The logic to retrieve these tokens is already present in [`botframework-connector`](https://github.com/Microsoft/botbuilder-js/blob/4d99d3322391c2f354208d7824fa5ee1881f548d/libraries/botframework-connector/src/tokenApi/operations/userToken.ts#L135), and it should be used in a method inside the `BotFrameworkAdapter` just like the C# version does.

**Describe alternatives you've considered**
\-

**Additional context**
\-

[enhancement]

**Comment by cleemullins** [comment]
PR has been merged. Closing Issue.
