### ISSUE TITLE
Is there an attachment layout property in SDKv4 

### ISSUE THREAD

**Issue by karthikeyanrj** [Microsoft/botbuilder-js#789]
Hi, 
I am unable to find any documentation on how to render carousel cards using the v4 framework.
Thanks for your help.

**Comment by jwiley84** [comment]
Hi @karthikeyanrj! 

The Bot Framework Team prefers that **'How-To'** questions be asked on StackOverflow using the 'botframework' tag [here](https://stackoverflow.com/questions/tagged/botframework). 

That being said, feel free to take a look at the BotBuilder-Samples Repo. The repo there contains a JS example of using cards([No.6 Using Cards](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/06.using-cards)) that shows how to render cards, including a snippet on placing them in a carousel.

![image](https://user-images.githubusercontent.com/17333688/53187009-045cf900-35b7-11e9-9245-f6df30e628b2.png)

**Comment by karthikeyanrj** [comment]
Thank you..Its working..
