### ISSUE TITLE
Azure Bot Service returns expired access tokens if auth is revoked

### ISSUE THREAD

**Issue by navzam** [Microsoft/botbuilder-js#807]
**(I don't think this is an SDK bug... if there's a better place for this issue, please help me direct it there.)**

## Describe the bug
Azure Bot Service manages your OAuth access tokens, including refreshing them. But if a user manually revokes authorization from your app, once your access token expires, Azure Bot Service continues giving you the same (now expired) access token.

## To Reproduce
1. Follow the [Azure Bot Service authentication docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp) and the [bot authentication sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/18.bot-authentication) to set up a bot that authorizes against AAD.
2. Run the bot and log in. Ensure that your access token is valid.
3. Go to https://myapps.microsoft.com and revoke access by clicking on your AAD app and choosing "Remove".
4. Wait until your access token expires, based on the `exp` claim. Likely 1 hour, but it's good to wait a bit longer in case there's leeway on the expiration time.
5. Talk to your bot again. Notice that you still get an access token and that it's the same token as before.
6. Try using the access token to access a resource such as Microsoft Graph. You should get a `401 Unauthorized` with the error message "Access token has expired."

## Expected behavior
I expected Azure Bot Service to realize that the token can't be refreshed, and reset its internal state such that `OAuthPrompt` (and probably `adapter.getUserToken()`) no longer gives an access token, allowing me to re-prompt the user to auth.

[bug]

**Comment by Jeffders** [comment]
Thanks for the comment. Indeed the component we have in Azure Bot Service to do the token refreshes still returns potentially expired tokens (i.e. there is nothing in the SDK we can change). Until that is changed, the proper behavior is something like:

Get the token
Try to use the token
If you get a 401/403 response (forbidden or unauthorized), you sign the user out with the API call and have them sign back in with a new OAuthCard.

**Comment by navzam** [comment]
@Jeffders Is there somewhere to track issues for the token component of Azure Bot Service? Or Azure Bot Service in general?

**Comment by mingweiw** [comment]
This is tracked [here](https://fuselabs.visualstudio.com/BotFramework/_workitems/edit/28336).
