### ISSUE TITLE
Unable to add post-"Turn" logic in ActivityHandler.run()

### ISSUE THREAD

**Issue by stevengum** [Microsoft/botbuilder-js#814]
## Versions
What package version of the SDK are you using. **4.3.2**
What nodejs version are you using. **10.14.1**

## Describe the bug
In C# it's trivial to override the onTurn method to add logic to run at the _end_ of a turn. Due to the event system used in the JS SDK, it's not possible to register a handler that fires after the turn in JS SDK. Developers would need to copy the ActivityHandler.run() method, then override it in their derived class with the same logic and add any post-turn logic.

## Additional context
Discovered during the rewrite of BasicBot to CoreBot for 4.3.x in the botbuilder-samples repo ([PR](https://github.com/Microsoft/BotBuilder-Samples/pull/1320)).

[bug]

**Comment by benbrown** [comment]
@stevengum can you drop some C# code here that uses this functionality and I'll be able to port it over...

**Comment by stevengum** [comment]
Here's the [code](https://github.com/Microsoft/BotBuilder-Samples/blob/samples-work-in-progress/samples/csharp_dotnetcore/13.core-bot/Bots/DialogBot.cs#L33-L40) that prompted the issue:
```cs
public override async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
{
    await base.OnTurnAsync(turnContext, cancellationToken);

    // Save any state changes that might have occured during the turn.
    await _conversationState.SaveChangesAsync(turnContext, false, cancellationToken);
    await _userState.SaveChangesAsync(turnContext, false, cancellationToken);
}
```

**Comment by benbrown** [comment]
@stevengum I actually this this is what Javascript's `onDialog` method is intended for.

The `onDialog` event fires _last_ after all other events have fired.  It is intended to do end-of-turn type things like run the dialog stack and save state changes.

Do we need to add something like `onAfterTurn` or something as well?

**Comment by benbrown** [comment]
Here's the code fwiw -> https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/activityHandler.ts#L144

**Comment by stevengum** [comment]
As long as we document this we should be fine, it's unfortunate about the naming... @sgellock, @Kaiqb, we'll need to pick this change up for the next run-through on the CoreBot sample.

[C# code for OnTurnAsync in ActivityHandler.cs](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/ActivityHandler.cs#L30)

`OnTurnAsync == onDialog`

**Comment by benbrown** [comment]
Another thing to keep in mind is that there is also an `onTurn` for Javascript that runs _first_ before any other more specific event.

**Comment by stevengum** [comment]
@Kaiqb FYI

We also need to make sure to document that people call next, otherwise developers might run into some confusing bugs

**Comment by cleemullins** [comment]
@benbrown @Kaiqb I believe this should be assigned to @kaiqb for doc updates, as there's no code to be written here.

**Comment by Kaiqb** [comment]
Content update will appear on the staging server.
