### ISSUE TITLE
Migrate BotBuilder to use Scoped Packages (@Azure) on NPM

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-js#820]
Migrate the JS SDK Packages to use proper Scoping so packages can be trusted by source.

**Comment by stevengum** [comment]
We should use `@Microsoft` for parity in Dotnet and then add botbuilder Python to the microsoft namespace as well.

**Comment by benbrown** [comment]
Perhaps we wait for this until 5.0? It seems disruptive to the ecosystem -- devs will have to change their package files, and we'll lose all our download counts.

**Comment by cleemullins** [comment]
This is never going to happen in 4.x. Closing.
