### ISSUE TITLE
[declarative-hack] WelcomeRule doesn't CallDialog if the dialog called only has DefaultRule

### ISSUE THREAD

**Issue by Zerryth** [microsoft/botbuilder-js#831]
## Versions
In stevenic/4.4-planning branch for hackathon, using declarative node version

## Describe the bug
Setting up a `WelcomeRule`

```js
dialogs.addRule(new WelcomeRule([
    new SendActivity(`Hi I'm a declarative bot!`),
    new CallDialog('HelpDialog')
]));
```

When `HelpDialog` had only `DefaultRule`, dialog does not get called

_DefaultRule_
```js
const helpDialog = new AdaptiveDialog('HelpDialog');
helpDialog.addRule(new DefaultRule([
    new SendActivity(`I can:
    - tell a joke
    - ask age
    - schedule you for a yoga class
    - assist when you type 'help'`),
    new EndDialog()
]));
dialogs.addDialog(helpDialog);
```
![image](https://user-images.githubusercontent.com/35248895/54856243-b7a03700-4cb6-11e9-8ec2-9199c4bd6ca1.png)

Changing `DefaultRule` to `BeginDialogRule` allows the `HelpDialog` to be called and run as intended, however

```js
const helpDialog = new AdaptiveDialog('HelpDialog');
helpDialog.addRule(new BeginDialogRule([
    new SendActivity(`I can:
    - tell a joke
    - ask age
    - schedule you for a yoga class
    - assist when you type 'help'`),
    new EndDialog()
]));
dialogs.addDialog(helpDialog);
```

![image](https://user-images.githubusercontent.com/35248895/54856194-7f98f400-4cb6-11e9-8acb-9bdc9e728891.png)

## Expected behavior
`DialogCall` should fire from `WelcomeRule` even if the only rule in the dialog that is called is `DefaultRule`

[bug]

**Comment by Stevenic** [comment]
Old issue
