### ISSUE TITLE
How to maintain session in Email Channel when the choices are rendered in Button style

### ISSUE THREAD

**Issue by wanzhiqing2010** [Microsoft/botbuilder-js#835]
One of my customers is using email channel with button-style choice ({ listStyle: builder.ListStyle.**button** }). The problem is that when I directly click No button, a brand new email will be created in a new window in Outlook, when I send this email, what I expect is to receive an email of “Create a new SR for you!”.  However I got the email of “Does this help for you” again, which is the email in the previous conversation.

Below is the simple code logic for example:

```
bot.dialog('/', [
    function (session) {
            builder.Prompts.choice(session, "Does this help for you?", "Yes|No", { listStyle: builder.ListStyle.button });    
},
    function (session, results) {
        var value = results.response.entity;
        if(value.trim() == 'No' || value == 2){
           session.send("Crete a new SR for you!");        
        }
    }]); 
```

I find the reason behind is that the **mailto** html tag creates a brand-new email without any previous email content, the bot framework regards it as if the very first email is coming and the bot framework starts a new session instead of an ongoing session. 

![bot-1](https://user-images.githubusercontent.com/15812364/54887404-b2690500-4ecd-11e9-992d-9316843494d6.png)
![bot-2](https://user-images.githubusercontent.com/15812364/54887405-b3019b80-4ecd-11e9-829b-95c80bb9b4d8.png)

I did some research like how to add previous email content to <mailto> html tag, but it seems not possible.

I got two workarounds for this problem temporarily. 

**WORKAROUND 1**
A workaround is to directly reply this email by clicking the Reply button. 
![bot-3](https://user-images.githubusercontent.com/15812364/54887416-d0cf0080-4ecd-11e9-9b26-f40f0ce90ec8.png)

Then manually type No and send out this email. The secondary function in the above code snippet will be invoked and I will get the response of “Crete a new SR for you!”. When doing like this, as you can see, the whole email thread is sent, which includes the previous email content. The bot framework regards it as an ongoing session so that the second function of the above code snippet is invoked. If we capture a Fiddler trace we can see it contains much more content than the fiddler trace captured in the above scenario. 
![bot-4](https://user-images.githubusercontent.com/15812364/54887417-d1679700-4ecd-11e9-9443-201d495c7f04.png)
 
**WORKAROUND 2**
I asked the customer to use Auto style ({ listStyle: builder.ListStyle.**auto**}) to render the choices.
```
bot.dialog('/', [
    function (session) {
            builder.Prompts.choice(session, "Does this help for you?", "Yes|No", { listStyle: builder.ListStyle.auto});    
},
    function (session, results) {
        var value = results.response.entity;
        if(value.trim() == 'No' || value == 2){
           session.send("Crete a new SR for you!");        
        }
    }]);
```
 
Using auto style, the choices are just rendered in plain-text. This will force the user to type either Yes or No and then to click the Send button of the Outlook.
![bot-5](https://user-images.githubusercontent.com/15812364/54887418-d1679700-4ecd-11e9-9ee0-6b08e3f41593.png)

**Question**
My customer didn't accept these two workarounds.
May I know if there is any way to tackle this problem (mainly due to **mailto**) or is there any document talking about best practice when using choices (button style) in Email channel?``

**Comment by v-kydela** [comment]
@wanzhiqing2010 - Buttons in dialogs pose a significant challenge in the email channel for the reasons you've described. If there was a way to get a mailto link to continue an existing email thread then I suspect the Bot Framework would already be creating links like that.

I can give you another workaround for your customer to consider. While the bot won't be able to use the new conversation ID in the new email thread to track the existing conversation, you can configure your bot to store its dialog state using the user ID instead of the conversation ID. However, this is considerably difficult to do in the V3 Node SDK. Would your customer be willing to upgrade to V4?

**Comment by wanzhiqing2010** [comment]
@v-kydela - Yes, my customer is willing to upgrade to V4. Could you shed some light on how to utilize user ID to maintain the conversation?

**Comment by v-kydela** [comment]
@wanzhiqing2010 - If you look in a Basic Bot's [constructor](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/13.basic-bot/bot.js#L61), you can see where the dialog state is created from the conversation state:

```node
// Create the property accessors for user and conversation state
this.userProfileAccessor = userState.createProperty(USER_PROFILE_PROPERTY);
this.dialogState = conversationState.createProperty(DIALOG_STATE_PROPERTY);

// Create top-level dialog(s)
this.dialogs = new DialogSet(this.dialogState);
```

All you have to do is create it from the user state instead:

```node
this.dialogState = userState.createProperty(USER_PROFILE_PROPERTY);
```

**Comment by v-kydela** [comment]
@wanzhiqing2010 - Did that resolve your issue?

**Comment by CoHealer** [comment]
Hi @wanzhiqing2010. It's been 20 days since your last response. Closing as resolved. If you feel it is not please follow up with us.

**Comment by wanzhiqing2010** [comment]
Hi,

Sorry for the late reply.

I have investigated in Bot SDKv4 and found out that the ListStyle of Choice Prompt has no more button option.

![2019-05-09_11h58_59](https://user-images.githubusercontent.com/15812364/57426479-e4ea7980-7251-11e9-92c3-c6988a8a4c96.png)

Does this imply that button ListStyle is obsolete in SDKv4 as button ListStyle is hard to maintain the session?

Another thing is that my customer still wants to look for a solution in SDKv3 to use button style in Email channel while keeping the session.

Any idea?

BR,
Zhiqing

**Comment by v-kydela** [comment]
@wanzhiqing2010 - The button list style in v3 just used hero cards, so `heroCard` is the equivalent list style in v4. That makes more sense than calling it the "button" list style since suggested actions are also considered buttons.

**Comment by v-kydela** [comment]
> Another thing is that my customer still wants to look for a solution in SDKv3 to use button style in Email channel while keeping the session.

I'm unsure what you're asking. Are you saying your customer wants to use the user-state workaround in v3? Or are you saying your customer wants a solution that allows them to keep using conversation state?

**Comment by wanzhiqing2010** [comment]
> I can give you another workaround for your customer to consider. While the bot won't be able to use the new conversation ID in the new email thread to track the existing conversation, you can configure your bot to store its dialog state using the user ID instead of the conversation ID. However, this is considerably difficult to do in the V3 Node SDK.

@v-kydela - based on your comment above, I'd like to know how to store the dialog state using user ID in V3 Node SDK.

**Comment by v-kydela** [comment]
@wanzhiqing2010 - Well it can't be done with the `UniversalBot` class (which almost all v3 Node bots use). You can see in the [source code](https://github.com/microsoft/BotBuilder-V3/blob/master/Node/core/src/bots/UniversalBot.ts#L470) that it's built to associate `sessionState` with `privateConversationData`:

```typescript
if (session.privateConversationData.hasOwnProperty(consts.Data.SessionState)) {
    sessionState = newStack ? null : session.privateConversationData[consts.Data.SessionState];
    delete session.privateConversationData[consts.Data.SessionState];
}
```

I would probably either try to extend `UniversalBot` or try to recreate most of its behavior in another bot class that extends `Library`.

**Comment by wanzhiqing2010** [comment]
@v-kydela Sorry for the late reply. Based on your above comment, may I know if you mean my initial question (maintain session in Email Channel when the choices are rendered in Button style) in SDK v3 is not possible to implement?

**Comment by v-kydela** [comment]
@wanzhiqing2010 - My above comment was just explaining how one might go about associating `sessionState` with `privateConversationData` in Node SDK v3

**Comment by wanzhiqing2010** [comment]
> I would probably either try to extend UniversalBot or try to recreate most of its behavior in another bot class that extends Library.

@v-kydela Does this mean that extending UniversalBot and recreating most of its behavior is possible but needs great effort? Also does this needs the individual users to implement by themselves?
