### ISSUE TITLE
Context should act as EventEmitter?

### ISSUE THREAD

**Issue by shmuelgutman** [microsoft/botbuilder-js#851]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to "notify" other parts(like middlewares) of the system regarding something important happens in the midst of active dialog.

**Describe the solution you'd like**
The Context object can act as [EventEmitter](https://nodejs.org/docs/latest-v8.x/api/events.html), in this way developer can send event: `context.emit('fileUploaded', {file: attachment})`
And handle it, for example from ActivityHandler:
```
context.on('fileUploaded', ({file}) => {
  // file
})
```

Would be happy to hear other alternatives.

Thanks

**Comment by benbrown** [comment]
We are considering something like this - there are some similar features in development in the 4.next branch.  We need to make sure we don't create multiple competing eventing systems.

**Comment by Stevenic** [comment]
We already have a mechanism for this.  You can send an event to middleware using the following code:

```
await context.sendActivity({
     type: 'event',
     name: 'fileUploaded',
     value: { file }
});
```

You can then catch the event from within middleware using:

```
context.onSendActivities(async (ctx, activities, next) => {
     if (activities[0].type == 'event') {
          switch (activities[0].name) {
               case 'fileUploaded':
                    const file = activities[0].value;
                    return [{}];
          }
     }
     return await next();
});
```

The entire activity protocol is just an eventing system. If want to stop propagation of an event just don't call `await next()`.

**Comment by shmuelgutman** [comment]
It looks like a workaround and not the real solution.
the purpose of the activity is to send activities back and forth to and from the bot, isn't it?
What if I have many events in a single turn? all the events will be sent to the user and the turn will take aprox 30 seconds? (which I have this problem already and I sometimes get timeout which is another problem for another discussion)
OK you said to stop propagate the event but if I want to only stop one activity and not the entire activity array?

The real issue here is to enable an internal events system which doesn't rely on any other existing mechanism.

**Comment by Stevenic** [comment]
@shmuelgutman we actually derived from EventEmitter in v3 but the feedback we received was that we had too many different eventing mechanisms (we had both events and middleware) and it wasn't what mechanism developers should use in a given situation.  In v4 we specifically wanted to simplify things so we decided to rout all notifications through middleware using activities. So while it might seem like a workaround its a conscious design decision we made.

It's worth noting that while `onSendActivites` does pass an array there's never more than one item in the array if you're using all of the built-in prompts.  The only way you'd ever have more than one item in the array is if your bot called `TurnContext.sendActivites()` with multiple activities.

The other thing to note is that we're in the process of designing a new eventing system for Dialogs which would just add even more confusion if we also added an EventEmitter based event system.  This new event system works a lot like browser events in that they bubble up and down the dialog stack.  You can use them in much the same way you would EventEmitter based events but they're a little different. If you're interested check out the Adaptive Dialog stuff we announced at //build.
