### ISSUE TITLE
[Parity Issue] Ability to change the Prompt Styling through PromptAsync

### ISSUE THREAD

**Issue by stevengum** [Microsoft/botbuilder-js#852]
PR for Dotnet: https://github.com/Microsoft/botbuilder-dotnet/pull/1606
Original C# Issue: https://github.com/Microsoft/botbuilder-dotnet/issues/1433

**Comment by stevengum** [comment]
@Zerryth when the PR is ready, please have @stevenic look through it.

**Comment by Zerryth** [comment]
should have pr in by tomorrow :)

**Comment by Zerryth** [comment]
Good news!
* I have the code written that should bring prompt styling in parity with C#

Bad news!
* making 100% sure is blocked by [this bug I found in `ChoicePrompt`](https://github.com/Microsoft/botbuilder-js/issues/869) when testing the styling from a bot

* per Steven Gum, created ticket, and will work on fixing that bug to confirm that this feature is good to go

**Comment by Zerryth** [comment]
managed to get work around bug described above and code for parity for styling is good to go

wrapping changes for this PR and issue #869 together

**Comment by cleemullins** [comment]
@Zerryth Awesome! Is the PR ready?
