### ISSUE TITLE
BaseUri for LuisRecognizer is missing /luis

### ISSUE THREAD

**Issue by mattmazzola** [Microsoft/botbuilder-js#86]
https://github.com/Microsoft/botbuilder-js/blob/a10e27053e166800faa54f3cd673a8dfb0bfdc2d/libraries/botbuilder-ai/src/luisRecognizer.ts#L49

Expected:
The third parameter to LuisRecognizer is optional and should default to the correct endpoint.
This allows user to program such as:
```typescript
const luisRecognizer = new LuisRecognizer("<removed-app-id>", "<removed-subscription-key>")
...

bot.use(luisRecognizer)
```

Actual:

Because the base url is wrong, the requestUrl generated will be:
`https://westus.api.cognitive.microsoft.com/v2.0/apps/<appId>?subscription-key=<subscription-key>`
Which will return 404 and leave developer confused thinking their app id is wrong.

However, it should be:
`https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/<appId>?subscription-key=<subscription-key>`

The work around is that the user must manually enter the base url as:
```
const luisRecognizer = new LuisRecognizer("<app-id>", "<subscription-key>", "https://westus.api.cognitive.microsoft.com/luis")
```

**Comment by Stevenic** [comment]
I commented on your pull request #87

**Comment by mattmazzola** [comment]
Not sure how I reproduced this after looking at PR comment so closing for now.

**Comment by Stevenic** [comment]
Look for new bits to get published this week and then please re-open if the issue persist.
