### ISSUE TITLE
[Feature Request] Implement botbuilder-templatemanager

### ISSUE THREAD

**Issue by Batta32** [microsoft/botbuilder-js#868]
**Is your feature request related to a problem? Please describe.**
It would be very useful to implement a `botbuilder-templatemanager` which is implemented in BotBuilder-Dotnet (you can find it [here](https://github.com/Microsoft/botbuilder-dotnet/tree/master/libraries/Microsoft.Bot.Builder.TemplateManager)).

**Describe the solution you'd like**
Implement a library with this solution.

**Describe alternatives you've considered**
\-

**Additional context**
\-

[enhancement]

**Comment by cleemullins** [comment]
The template manager in C# is coupled with ASP.Net Razor and doesn't directly have a corresponding JS technology. What would you suggest?

**Comment by gabog** [comment]
Hi Martin, this one doesn't apply to JS, we may need another framework for that so closing this one.
