### ISSUE TITLE
ChoicePrompt does not send choices if PromptOptions are passed in to waterfallStepContext.Prompt()

### ISSUE THREAD

**Issue by Zerryth** [Microsoft/botbuilder-js#869]
## Versions
What package version of the SDK are you using. - `4.3.4`
What nodejs version are you using - `v10.14.1`
What os are you using - Windows
Sample - node `10.prompt-validations`

## Describe the bug
`ChoicePrompt` does not send choices if `PromptOptions` are passed in.
___
### _Working_ - `ChoicePrompt`, *without* passing `PromptOptions`
![image](https://user-images.githubusercontent.com/35248895/55915136-c1bea280-5b9d-11e9-92fc-6c12bbda6a1d.png)
Instead of passing `PromptOptions`, a string is passed as 2nd argument to `prompt()`

![image](https://user-images.githubusercontent.com/35248895/55915179-dd29ad80-5b9d-11e9-8a0d-ee0b7c6f9b3a.png)

### _Not Working_ - `ChoicePrompt` *with* `PromptOptions`
![image](https://user-images.githubusercontent.com/35248895/55915822-68577300-5b9f-11e9-8d61-ba5afc432da8.png)

![image](https://user-images.githubusercontent.com/35248895/55915799-5b3a8400-5b9f-11e9-9a4b-a581a256f2d6.png)

Above it finishes the waterfall dialog doesn't move onto our "`promptForChoicy`" `ChoicePrompt` (no prompt given, since it wasn't passed into `PromptOptions`, nor are the choices displaced, even though they were passed in as 3rd argument in `step.prompt()`)

But the retry prompt _does_ show up, as the options are successfully consumed:
![image](https://user-images.githubusercontent.com/35248895/55915898-a3f23d00-5b9f-11e9-88c3-9121da5bbf54.png)

Even if you go the route of specifying `PromptOptions.prompt`, to pass to `waterfallStepContext.prompt()`, it will consume the prompt, but again no choices from the choice prompt are displayed

## Expected behavior
For `ChoicePrompt`s to display choices, even when `PromptOptions` are passed to `waterfallStepContext.prompt()` to consume

[bug]

**Comment by Zerryth** [comment]
ahhh ok, figured it out

`DialogContext.prompt()` has a couple overloads that take 3 parameters
  * 2nd parameter is options and 3rd parameter is choices.
* `PromptOptions` actually has a `choices` property too, and `.prompt()` assigns the choices that are set in `PromptOptions`, ignoring the 3rd arg choices passed into `DialogContext.prompt()`
* so if I only set `PromptOptions.retryPrompt`, for example, and therefore leave `PromptOptions.choices` undefined, then choices is set to empty array in `.prompt()` method

working on fix

**Comment by cleemullins** [comment]
Any update on the fix?

**Comment by Zerryth** [comment]
@cleemullins ah, I distracted myself with the declarative hackathon, and didn't push the PR. I needed to write a test and wanted to fire up a bot using new code to double check

Realizing April 15th is NOW--I'll do better next time with being aware of the date

PR with tests is in and ready to go now, pending review
