### ISSUE TITLE
[Feature Request] botbuilder v4 multilingual management

### ISSUE THREAD

**Issue by montacerdk** [Microsoft/botbuilder-js#876]
Hi,

Is there a coming version of botbuilder SDK v4 that integrates the localization management?

Using the V3 SDK, we used to get the locale just by running:

```
session.preferredLocale();
// returns "en" for example.
```

**Comment by tdurnford** [comment]
I don't believe there are any upcoming plans to add locale functionality to the BotFramework SDK in the immediate future; however, there is a [Multilingual Sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/17.multilingual-conversations) that prompts the user for their language choice and proceeds to translate messages accordingly that may be helpful.
