### ISSUE TITLE
Add staging boolean option to LuisRecognizerOptions

### ISSUE THREAD

**Issue by mattmazzola** [Microsoft/botbuilder-js#88]
From what I see there is no way to configure the LuisRecognizer to use the staging deployment slot.

It needs to construct the url with the `staging=true` query parameter; however, there no option in `LuisRecognizerOptions` for staging.

I looked into submitting PR to add the boolean; but the request url is generated inside the LuisClient which is constructed from a swagger file and that needs to understand the staging option.

- [ ] Update `botframework-luis` swagger to have staging query parameter
- [ ] Regenerate client
- [ ] Add `staging: boolean` to `LuisRecognizerOptions`

**Comment by Stevenic** [comment]
I was about to make the same comment. The swagger used was out of date. We should get this issue resolved and the LUIS client updated this week.

**Comment by Stevenic** [comment]
Covered in #77 .
