### ISSUE TITLE
BotStatePropertyAccessor.get takes default value opposed to C# which takes a factory

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-js#895]
All versions. 

In JS, the file [botStatePropertyAccessor](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/botStatePropertyAccessor.ts) has a definition of "Get" that is different, and incompatable with, the C# version. 

The JS code has 3 overloads (the first one is redundant and should be deleted). These take a default value for <T>. 

```ts
    public async get(context: TurnContext): Promise<T|undefined>;
    public async get(context: TurnContext, defaultValue: T): Promise<T>;
    public async get(context: TurnContext, defaultValue?: T): Promise<T> {
        const obj: any = await this.state.load(context);
[...]
    }
```

In C#, the method takes a `Func<T>` as a default value factory as part of the [IStatePropertyAccessor](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/IStatePropertyAccessor.cs) interface:
```cs
   Task<T> GetAsync(ITurnContext turnContext, Func<T> defaultValueFactory = null, CancellationToken cancellationToken = default(CancellationToken));
```

We should:
1. Add the `Func<T>` to the JS code.
2. Add the "Default Value" to the C# code. 

The **PROBLEM** is that in C# we cannot extend the interface w/o breaking compatibility. So at the least, we need to make the TS code take the lambda.

**Comment by benbrown** [comment]
We can add a factory here in Javascript for parity says @stevenic

**Comment by johnataylor** [comment]
we don't need this in the JavaScript, it doesn't add any value @stevenic
