### ISSUE TITLE
[BotBuilder-AI] build failing

### ISSUE THREAD

**Issue by Bill7zz** [microsoft/botbuilder-js#916]
## Versions
BotBuilder-js latest package version.
nodejs version 10.14.2
npm version 6.9.0

## Describe the bug
The BotBuilder-ai library is not installing the latest version of the `@azure/ms-rest-js` package. 
This makes some conflicts with the `cognitiveservices-luis-runtime` library, as this is installing the latest version of the `@azure/ms-rest-js` package (1.8.4)

## More info
According to the NPM CLI documentation, one of the [package.lock.json](https://docs.npmjs.com/files/package-lock.json) goals are:
 
```Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.```

This suggests that the version defined in the package-lock.json will have priority over the ones defined in the package.json when the first one is present. 

Additionally, we found an example of the usage of the package-lock.json that clarify the current issue in the `botbuilder-ai` library. More info [Here](https://medium.com/coinmonks/everything-you-wanted-to-know-about-package-lock-json-b81911aa8ab8). 

The problem is that, by one hand the `cognitiveservices-luis-runtime` does not have a package-lock.json (that is because it must not be published, and it will be ignored. More info [here](https://docs.npmjs.com/files/package-lock.json)) and, when the `npm install` command runs, the latest version of `@azure/ms-rest-js` (v1.8.4) will be installed; by the other hand, the `botbuilder-ai` library has a package-lock.json that specify to install the version (1.8.2) of the same dependency, which will cause some dependency issues regarding the versions.

## To Reproduce
1. Clone the botbuilder-js repository
2. run `npm install`
3. run `npm run build`
4. You will see the build of `botbuilder-ai` library broken. 

## Expected behavior
Build the solution successfully.

## Screenshots
Build error:
![image](https://user-images.githubusercontent.com/37461749/57384167-72609780-7186-11e9-8c74-8156704816a5.png)

## Proposed Solution
1. Update the BotBuilder-ai package.json to use @azure/ms-rest-js (~1.8.4) version, which will force the update of the package-lock.json 
2. Delete the package-lock.json and `npm install` to create it.

**Comment by sgellock** [comment]
I don't think the Cog Svc client team is pinning their version of ms-rest

**Comment by Bill7zz** [comment]
Hi @sgellock, we want to let you know that we updated the description of the issue with more information.

**Comment by cleemullins** [comment]
@Bill7zz CAn we update the Cognitive Services client to pin the ms-rest-js version? Unless we do that, we'll be chasing out tail.

**Comment by Bill7zz** [comment]
@cleemullins Yes we can, but we need also to pin the version of ms-rest-js in botbuilder-ai library, 
just to avoid possible problems.
