### ISSUE TITLE
Infinit loop with more than 255 services

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-js#928]
In the [BotConfigurationBase](https://github.com/microsoft/botbuilder-js/blob/2115012394877abcfc8234ebad43d09b9ac2d9d0/libraries/botframework-config/src/botConfigurationBase.ts#L114) class, the following code is present:

```ts
       let found = false;
        do {
            found = false;
            service.id = Math.floor((Math.random() * 255)).toString();
            for (const existingService of this.services) {
                if (existingService.id === service.id) {
                    found = true;
                    break;
                }
            }
	} while (found);
```
Problem 1:
This code results in an infinite loop if 255 or more services are specified. 

Problem 2:
This code DOES NOT check to see if the Service exists the way the C# code does. Sync with @tomlm to figure out the "Why?" of this behavior, along with the reason for the ID Reassignment. 

This is similar to C# Bug: 
https://github.com/microsoft/botbuilder-dotnet/issues/1910

**Comment by justinwilaby** [comment]
should be:
```js
et found = false;
        outer: do {
            found = false;
            service.id = Math.floor((Math.random() * 255)).toString();
            for (const existingService of this.services) {
                if (existingService.id === service.id) {
                    found = true;
                    break outer;
                }
            }
	} while (found);
```
