### ISSUE TITLE
Error: MiddlewareSet.use(): invalid plugin type being added.

### ISSUE THREAD

**Issue by mlaiandbots** [microsoft/botbuilder-js#929]
## Versions
**What package version of the SDK are you using.**

"botbuilder": "~4.4.0",
"botbuilder-ai": "~4.4.0",
"botbuilder-azure": "~4.4.0",
"botbuilder-dialogs": "~4.4.0",

**What nodejs version are you using**
node -v
v10.15.3

**What browser version are you using**

chrome 

**What os are you using**
windows 10
**## Describe the bug**
**Code :**

```
const { BotFrameworkAdapter, ConversationState, MemoryStorage, UserState, **BotStateSet** } = require('botbuilder');

const adapter = new BotFrameworkAdapter({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword
});

const memoryStorage = new MemoryStorage();

const conversationState = new ConversationState(memoryStorage);
const userState = new UserState(memoryStorage);

adapter.use(new BotStateSet(conversationState,userState));
```
Throws following error on running " node index.js"

node_modules\botbuilder-core\lib\middlewareSet.js:58
                throw new Error(`MiddlewareSet.use(): invalid plugin type being added.`);
                ^

Error: MiddlewareSet.use(): invalid plugin type being added.
    at middleware.forEach (C:\Users\ankugup\EIP\MPAAS-JIRA-ASSISTANT\node_modules\botbuilder-core\lib\middlewareSet.js:58:23)
    at Array.forEach (<anonymous>)
    at MiddlewareSet.use (C:\Users\ankugup\EIP\MPAAS-JIRA-ASSISTANT\node_modules\botbuilder-core\lib\middlewareSet.js:50:20)
    at BotFrameworkAdapter.use (C:\Users\ankugup\EIP\MPAAS-JIRA-ASSISTANT\node_modules\botbuilder-core\lib\botAdapter.js:31:53)
    at Object.<anonymous> (C:\Users\ankugup\EIP\MPAAS-JIRA-ASSISTANT\index.js:57:9)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

[bug]

**Comment by tdurnford** [comment]
BotStateSet is used by different middlewares like the AutoSaveStateMiddleware to manage botStates and is not a standalone middleware. Take a look at [AutoSaveStateMiddleware's](https://github.com/microsoft/botbuilder-js/blob/aeb72abada5a5dba613101279eb01d834ee7d524/libraries/botbuilder-core/src/autoSaveStateMiddleware.ts#L46) implementation for more details. If you want to add state to your project, you can pass conversationState and userState as parameters to your bot. For an example of using state, take a look at the [Core Bot Sample](https://github.com/microsoft/BotBuilder-Samples/blob/a2137ec85a3a0179756ab908fc318d92ac022b73/samples/javascript_nodejs/13.core-bot/index.js#L56).

Hope  this helps!

**Comment by TCarmine** [comment]
@tdurnford thanks, I do have same issue and I am on Ubuntu 18.04 with the following in my package.json:

 "dependencies": {
    "@types/restify": "^8.4.2",
    "botbuilder": "~4.7.2",
    "restify": "^8.5.1",
    "typescript": "^3.8.2"
  }
}

My app.ts is the following:

import { BotFrameworkAdapter, MemoryStorage, ConversationState } from "botbuilder";
import * as restify from "restify";
import { ConfState } from "./types";

let server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, ()=> {
   console.log(`${server.name} listening on ${server.url}`);
});

const adapter = new BotFrameworkAdapter({
    appId:process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

let conversationState;
const memoryStorage = new MemoryStorage();
conversationState = new ConversationState(memoryStorage);

adapter.use(conversationState);

server.post("/api/messages", (req,res)=>{
   adapter.processActivity(req,res, async(context)=>{
       if(context.activity.type === "message"){
           const state = conversationState.get(context);
           await context.sendActivity(`Echo: ${ context.activity.text }`);
        // Continue with further processing.
        }else{
           await context.sendActivity(`${context.activity.type} event detected`);
       }
   });
});

and type.ts following:

export interface ConfState{
     state: String;
}

When I compile Typescript I don't get any error.

How we should we deal with, I think, this middleware not transpiled correctely?
