### ISSUE TITLE
ActivityHandler implimentation in JS is problematically different than in C#

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-js#933]
## Versions
What package version of the SDK are you using: 4.4.
What nodejs version are you using: irrelevant.
What browser version are you using: irrelevant.
What os are you using: irrelevant.

## Describe the bug
Significant differences in behavior exist between the JS and C# implementations of the ActivityHandler class.
- In general:
  - JS: implemented as some sort of pipe, where you call `next` to continue processing.
  - C#: implemented via class inheritance, where you can short-circuit "drill-down style operations by overriding the more general method and then not calling the base implementation of the method.
  - This difference alone is enough to cause untold confusion for anyone trying to use both versions of the SDK. Also, it's impossible to document in a language agnostic way.
- _On members added/removed_:
  - JS: called whenever any member is added or removed from the conversation.
  - C#: called only when a non-bot member is added or removed.
- _On event_:
  - JS: This happens before the on token response event handler
  - C#: This is only called for non token response events.
- _On event activity_:
  - JS: No such method (or the _on event_ method is really this method in disguise, and there's not a real on event handler in JS).
  - C#: This handles all event activities, and the base passes control to the token response event handler or the [unrecognized] event handler.
- _On dialog_:
  - JS: Appears to happen at the end of the "pipe", though it still has a next method to call.
  - C#: no such method. Accomplish the same thing by adding code in the `OnTurnAsync` override, after the call to the base implementation.

Those are the ones I found before deciding I was going on too much. I'm marking this as a JS issue, since the **welcome users** sample bot adds the non-bot member check back in.

## To Reproduce
1. Compare the `ActivityHandler` [implementation in JS](https://github.com/microsoft/botbuilder-js/blob/4.4/libraries/botbuilder-core/src/activityHandler.ts) to [the one in C#](https://github.com/microsoft/botbuilder-dotnet/blob/4.4/libraries/Microsoft.Bot.Builder/ActivityHandler.cs).
1. Superficial error: Try to figure out all of the ways in which the behavior is different between the two implementations.
1. More profound error: How certain are you that you found all the behavior differences?

## Expected behavior
We've committed to making the behavior of all the various flavors of the SDK behave in the same way as much as possible. It doesn't look like we tried for this class.

## Additional context
This is causing major headaches just in documentation, as the current messaging is that this class a cornerstone of bot development.

[bug]

**Comment by johnataylor** [comment]
The decision was made to model the JavaScript differently than the C# because JavaScript programmers favor events over subclassing. So all these issue are by design (I prefer the C# design myself but the team decided it was important to do the right thing for the JavaScript programmer). Possibly there is an unnecessary inconsistency in the member added/removed semantics but we shouldn't change that at this point.
