### ISSUE TITLE
Implement JS unit tests for TestBot

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-js#972]
Implementation task for https://github.com/microsoft/botframework-sdk/issues/5419

**Comment by benbrown** [comment]
Related to #987

**Comment by cleemullins** [comment]
Testbot isn't customer facing, so can be pushed to 4.6.

**Comment by gabog** [comment]
Hi @cleemullins, we are using testbot as the base to update corebot JS in samples, this task should be done today and we'll port the code to samples.

**Comment by gabog** [comment]
Still to do, port changes to Samples.

**Comment by sgellock** [comment]
Samples work is being tracked in the samples repo. refer to https://github.com/microsoft/BotBuilder-Samples/issues/1561
