### ISSUE TITLE
Testbot - Implement Flight Assistant

### ISSUE THREAD

**Issue by gasper-az** [microsoft/botbuilder-js#974]
**Is your feature request related to a problem? Please describe.**
Help reduce the gap between the JS and .NET versions by implementing the _Flight Assistant_ in the Testbot for _Botbuilder-JS_.

**Describe the solution you'd like**
Right now there's only an Echobot implemented in the library tests . It would be good to implement the Flight Assistant TestBot to increase parity with .NET.
If we look at the [Startup.cs](https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.TestBot/Startup.cs#L59) on .NET, we can see this:

![image](https://user-images.githubusercontent.com/20074735/59125642-5133c800-8939-11e9-864b-24bfbf48504f.png)
that there are many types of bots initialized depending on the specified endpoint. The top bot (_myBot_) is an Echobot that is [already implemented in JS](https://github.com/microsoft/botbuilder-js/blob/master/libraries/testbot/bots/myBot.js).

It would be nice to continue by implementing the following bot, the Flight Assistant. This is shown in the above image as [DialogBot](https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.TestBot/Bots/DialogBot.cs) and it takes a [MainDialog](https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.TestBot/Dialogs/MainDialog.cs) as the type.

It's required to implement the DialogBot as one of the bots that are already in `/libraries/testbot/bots/` and its corresponding MainDialog.

Here's how the Flight Assistant bot is running right now in the .NET library:
![image](https://user-images.githubusercontent.com/20074735/59126794-4b8bb180-893c-11e9-9920-55b711105e25.png)

![image](https://user-images.githubusercontent.com/20074735/59126856-770e9c00-893c-11e9-90ac-a3eb667b1428.png)

**Describe alternatives you've considered**
[n/a]

**Additional context**
[n/a]

[enhancement]

**Comment by johnataylor** [comment]
Moving this work to 4.6.

The thing is we need 2 discrete things and we are conflating those in TestBot.
1) We need to run functional tests from the nightly build.
2) We need a debug project whereby developers can walk through the code they are working on. Walking through the code is important and having to create and link to local packages is a hassle.

The original intention of TestBot was strictly (2).

The work needed is as follows:
1) introduce a new designed-for-purpose functional-test-bot
2) restore TestBot to a mirror of CoreBot

...and ideally add TestBot to the gitignore so developers can easily use it as a playground without accidentally checking it in (and ruining other developers' playgrounds.)

**Comment by cleemullins** [comment]
Low priority work. Moving to backlog.

**Comment by gabog** [comment]
Closing it
