### ISSUE TITLE
Test adapter tests only test for success case

### ISSUE THREAD

**Issue by microsoftly** [Microsoft/botbuilder-js#99]
The test adapter does not have tests ensuring it fails when appropriate. I made a similar mistake when making the BotTester framework. As reference, here's its [failure](https://github.com/microsoftly/BotTester/blob/master/test/mocha/chai/BotTesterFailure.mocha.spec.ts) vs [success](https://github.com/microsoftly/BotTester/blob/master/test/mocha/chai/BotTester.mocha.spec.ts) tests

**Comment by Stevenic** [comment]
Are you looking in the M2 branch or Master? This is all largely prototype code in Master. The M2 branch is still a work in progress but it's more production ready code with more exhaustive unit tests.  The tests are also more fine grained there.  Look at [botbuilder-core](https://github.com/Microsoft/botbuilder-js/tree/m2/libraries/botbuilder-core) and [botbuilder-core-extensions](https://github.com/Microsoft/botbuilder-js/tree/m2/libraries/botbuilder-core-extensions). I have 100% code & branch coverage on core and I'm currently working on the unit tests in core-extensions.

**Comment by Stevenic** [comment]
I now have 100% code coverage for the `TestAdapter`. Please feel free to look over the [current set of tests](https://github.com/Microsoft/botbuilder-js/blob/m2/libraries/botbuilder-core-extensions/tests/testAdapter.test.js) and feel free to send a PR with additional tests if you think we're still missing some.

**Comment by microsoftly** [comment]
I was definitely looking at master. I will check out the m2 branch
